### ISSUE TITLE
Structure view for the whole package

### ISSUE THREAD

**Issue by growler** [go-lang-plugin-org/go-lang-idea-plugin#1020]
Go building block is package. However, unlike java, we often enjoy breaking go package sources into few logical parts, files. 

I prefer to keep plugin's structure view for the sake of quick navigation, yet I noticed that quite often I have to switch to project view just to navigate to another file from the very same package I'm working on right now.

I believe it would be really great if plugin could offer structure view for the whole package (i.e. all files located in the same directory).

**Comment by dlsniper** [comment]
This is fixed under 1.0
