### ISSUE TITLE
Updating GOPATH automatically after adding additional 'src' folders in 'Project Structure'

### ISSUE THREAD

**Issue by ajres** [go-lang-plugin-org/go-lang-idea-plugin#1041]
I have a project that places third party module src under a 'vendor' directory.

I added the 'vendor/src' directory as a src folder in the 'Project Structure', but this does not update the GOPATH when I run the application from within the IDE.

I have worked around this by manually setting GOPATH as an environment variable containing both src locations in the Runtime Configuration.

Is there a way to set GOPATH automatically after adding a new directory to the module Sources in 'Project Structure'?

IDEA 14 C, JRE 1.8, plugin 0.9.16alpha

Andy

**Comment by JoeBruner** [comment]
I have Alpha 11 installed, and I don't see Google Go under `Settings -> Tools`.  Was this removed? How do we set multiple GOPATHs (one for core stuff plus one for invidual project)?  I can do from the command line, but trying to figure out how to do from tool

**Comment by dlsniper** [comment]
Please go to Settings | Languages and Frameworks | Go and then you can configure the GOPATH as you need, be it global, per project or per module

**Comment by JoeBruner** [comment]
Ah thanks.

**Comment by dlsniper** [comment]
Shouldn't happen anymore.
