### ISSUE TITLE
very slow to parse a file 

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1084]
That file come from:
```
https://github.com/miekg/exdns/blob/master/q/q.go
```
It is open source,you can use `go get github.com/miekg/exdns` to try it
![image](https://cloud.githubusercontent.com/assets/1107541/5224156/93a66f32-7708-11e4-83d7-6ca6f0e495c7.png)
![image](https://cloud.githubusercontent.com/assets/1107541/5224171/e7ebfd50-7708-11e4-8c9e-cd7bbee1e8ea.png)

**Comment by dlsniper** [comment]
This should be fixed in 1.0 branch.
