### ISSUE TITLE
Prioritize imported types in completion

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#1099]
https://www.dropbox.com/s/gnmsccfevlv50i1/Screenshot%202014-11-26%2018.50.30.png?dl=0

**Comment by ignatov** [comment]
Please check out a fix for more effective memory consuming: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/42af60a6e8d0d8822ba9b919de8fd835716ca200
