### ISSUE TITLE
Unable to detect imported packages

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1109]
The code:
```go
package server

import (
	"github.com/gorilla/websocket"
	"logger"
	"net/http"
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin:     checkOrigin,
}
//...
```
Here package "github.com/gorilla/websocket" marked as unused, and "websocket" package reference is marked as unimported with popup saying ```Import ""```. Pressing Alt-Enter adds empty package name to the imports section: ```""```.

IDE: IU-139.658.4
Plugin: 0.9.16-alpha.8
OS: Xubuntu

**Comment by dlsniper** [comment]
This is fixed in 1.0 as far as I can tell.
