### ISSUE TITLE
Inspection: Unknown type when checking presence of value in a map

### ISSUE THREAD

**Issue by kortemy** [go-lang-plugin-org/go-lang-idea-plugin#1116]
SDK: Go 1.3.3 linux/amd64
OS: ElementaryOS 0.2.1 Luna 64-bit
IDEA: 14.0.1 Community Edition
Plugin version: 0.9.16-alpha.9

When reading values from a map, there is a second variable to check if such value exists:

```go
val, exists := myMap[someKey]
```

Inspection states that `exists` is of unknown type, and suggests to cast it to `bool` when used. That shouldn't happen, because type is always `bool`.

https://golang.org/doc/effective_go.html#maps

Example code:
http://play.golang.org/p/pDdttixZ-G

**Comment by dlsniper** [comment]
This is fixed in 1.0
