### ISSUE TITLE
Variable name marked as having typo after editing

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1120]
I edited variable name, renamed from "message" to "err" and now IDE thinks it is "errmessage":
![screenshot - 081214 - 22 31 25](https://cloud.githubusercontent.com/assets/4119321/5346626/a156a442-7f2a-11e4-8714-839a7743021e.png)
IDE: UI-139.658.4
Plugin: 0.9.16-alpha.9

**Comment by dlsniper** [comment]
This should be fixed at some point before 1.0 release in the 1.0 release branch.
