### ISSUE TITLE
Method expressions not counted as parameter

### ISSUE THREAD

**Issue by ajres** [go-lang-plugin-org/go-lang-idea-plugin#1125]
When passing a Method expression as a parameter, the method call is incorrectly reported as having too few arguments:

e.g.

```
r := mux.NewRouter()
r.Handle("/{db:"+dbRegex+"}/", makeHandler(sc, privs, (*handler).handleGetDB)).Methods("GET", "HEAD")
``` 
The Method expression '(*handler).handleGetDB' results in the IDE error 'Not enough arguments in call to makeHandler'

I couldn't see an existing issue for this, the code compiles and runs correctly.

Andy

**Comment by dlsniper** [comment]
This shouldn't happen anymore in 1.0. Please reopen with more details.
