### ISSUE TITLE
Context detection error

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1128]
Code:
```go
func osListener(o chan os.Signal) {
	log.Fatalf("Caught %s. Exiting.", <-o)
}
```
Second parameter ```<-o``` marked as error "multiple-value <-o in single-value context".

IDE: IU 14.0.2
Plugin: 0.9.16-alpha.9

**Comment by dlsniper** [comment]
Please check 1.0 branch and reopen if it's not fixed. Thank you.
