### ISSUE TITLE
How to solve "Unresolved symbol" for non built-in (custom) packages?

### ISSUE THREAD

**Issue by kalopsia** [go-lang-plugin-org/go-lang-idea-plugin#1129]
I tried to find some well-defined steps to solve "Unresolved symbol" for non built-in (custom) packages in Intellij IDEA. I tried to solve this by "Invalidate Caches/Restart" - but it doesn't solve the problem.

Here is screenshot for clarity:
![screenshot from 2014-12-11 22 01 14](https://cloud.githubusercontent.com/assets/6209197/5400862/c8f13c4c-8187-11e4-8755-3a007ae3c640.png)

What can I do?

**Comment by dlsniper** [comment]
This should be fixed in 1.0 branch.
