### ISSUE TITLE
missing code hints  in all test files

### ISSUE THREAD

**Issue by ypwu1** [go-lang-plugin-org/go-lang-idea-plugin#1145]
It works fine with source files,
Test files have following issues:
1. Some of the core libraries are grey out at import declaration
2. variables, functions and structures referencing  source files are all missing support(source file variables using in test files are all red)  
![screenshot 2014-12-24 22 34 48](https://cloud.githubusercontent.com/assets/479768/5548104/148b473a-8bbd-11e4-8e5d-ec9aab55f249.png)
![screenshot 2014-12-24 22 37 03](https://cloud.githubusercontent.com/assets/479768/5548119/67adcbc2-8bbd-11e4-8576-1dde41d348a5.png)

**Comment by dlsniper** [comment]
Assuming 0.9.x branch. Fixed in 1.0
