### ISSUE TITLE
0.9.16-alpha.9 package not found in project

### ISSUE THREAD

**Issue by yuntan** [go-lang-plugin-org/go-lang-idea-plugin#1146]
Arch Linux
JDK 1.8.0_25
IntelliJ IDEA 14.0.2
plugin version 0.9.16-alpha.9
Go1.4 linux/amd64

In Settings -> Tools -> Google Go
GOROOT=/usr/local/go
GOPATH=/home/yuntan/Workspace/go
Project GOPATH=Project-Workdir; GOPATH

In Project Structure -> SDKs
Go SDK home path: /usr/local/go
Classpath: /usr/local/go/src; /home/yuntan/Workspace/go/src
Sourcepath: /usr/local/go/src

![141225-1](https://cloud.githubusercontent.com/assets/574575/5552461/b28e5e70-8c41-11e4-9741-7aa5f59fd531.png)

**Comment by dlsniper** [comment]
This should be fixed in 1.0
