### ISSUE TITLE
Bugs: 100% CPU load of Intellij and _test.go files behave weird

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#1147]
Intellij 14.0.2
Plugin Alpha9
Go 1.4 via brew on OSX 10.10

1. After coding some time (4-5min) the CPU usage of Intellij goes up to >100% and does not decrease. I have to restart the IDE.
2. the testing package gets in _test files only then recognized when I invalid the caches and reindex everything. I have to do this several times
3. typing e.g. fm... to list all the packages starting with fm* does not do anything.
Recognizing unimported packages to import them takes very long.
4. Sometimes randomly packages are greyed out.

**Comment by arjunsharma** [comment]
+1 on item 4. 

I am seeing random packages greyed out in imports in _test.go files, but it's not happening in my source files. I have included the imports that are in my test file, and put arrows next to the ones that are not recognized.

import (
	"bytes" <-----
	"crypto/md5"
	"crypto/sha512"
	"database/sql"
	"encoding/hex"
	"golang.org/x/crypto/bcrypt"
	"net/http"
	"net/http/httptest"
	"net/url" <-----
	"strconv"
	"testing" <-----
	"strings" <-----
)

**Comment by ngdinhtoan** [comment]
+1, same here

Intellij 14.0.2
Plugin Alpha9
Go 1.4.1 via brew on OSX 10.10.1

**Comment by dlsniper** [comment]
Hi, this is a known issue. Please try alpha7. Thank you

**Comment by SchumacherFM** [comment]
Will there be an alpha10 coming? :-) :+1:

**Comment by dlsniper** [comment]
This should be fixed in 1.0 branch.

**Comment by SchumacherFM** [comment]
Fix confirmed
