### ISSUE TITLE
close method inspection false positives

### ISSUE THREAD

**Issue by heavenlyhash** [go-lang-plugin-org/go-lang-idea-plugin#1149]
Application code with a `close` method can trigger the inspection that's intended for the builtin golang `close` method, causing the application method call to be incorrectly flagged as broken.

This appears to be purely a function of the inspection mechanism.  Using the jump to source feature correctly jumps to the application's `close` method.

I bisected this behavior to appearing in bcec5500acc589d70322cb3978e197fa1bd37b8b .

An example of code that triggers the behavior can be found here: https://github.com/flynn/flynn/blob/4b37829b88d3b1647f6b5350f06049403382fd60/pkg/exec/exec.go#L301

Previously to bcec550, the bug appears to have worked in approximately the opposite direction: a bare call (that is, to golang's builtin `close` method) to close could be marked as having too many arguments, since the applications `close()` method in this file took zero arguments.

**Comment by dlsniper** [comment]
Please check the 1.0 releases.
