### ISSUE TITLE
Expression type mismatch, expected type is func 

### ISSUE THREAD

**Issue by poyannabati** [go-lang-plugin-org/go-lang-idea-plugin#1158]
There seems to be an issue with using functions as parameters with plugin version 0.9.15. I get "Expression type mismatch, expected type is func". However, the code is valid and will build/run. If I put the parameter name inside of parentheses, then IDEA will not complain about the type. 

![image](https://cloud.githubusercontent.com/assets/1499050/5602284/81156894-9343-11e4-80d8-75a4ffa22bc7.png)

**Comment by poyannabati** [comment]
![image](https://cloud.githubusercontent.com/assets/1499050/5602288/c0935fd0-9343-11e4-9ed6-b2ea5d3fb3b0.png)

**Comment by mtoader** [comment]
This is a known issue. Working on it.

**Comment by dlsniper** [comment]
It should be fixed in 1.0 branch
