### ISSUE TITLE
Import unused and unresolved symbol

### ISSUE THREAD

**Issue by hobbs** [go-lang-plugin-org/go-lang-idea-plugin#1159]
Over the last year I've never successfully used this plugin although I've spent many hours trying. So after many attempts, I've decided to start over, try again, and document my process.

Fresh install of everything (deleted all installation folders and user prefs, deleted entire GOPATH, etc):
 - IntelliJ 14.0.2
 - Go 1.4 using official mac package, installed at /usr/local/go
 - Go app engine (appengine-1.9.17) installed at /usr/opt/go_appengine
 - go-lang-idea-plugin 0.9.16-alpha.9 (I've tried other versions as well) installed via jar at https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases
 - GOPATH is a fresh Go folder, with nothing in it but an empty "src" folder.

I've setup the Go settings as follows:
![screen shot 2015-01-03 at 2 56 36 pm](https://cloud.githubusercontent.com/assets/37571/5604043/bd9691d4-9358-11e4-8f5c-d310d9ab64da.png)

Now, I did the following (here is the screen cap video of all of these steps: https://www.youtube.com/watch?v=UyVwX3Cmm44 )
 - Created a new GAE project inside the gopath/src
 - Fiddled with SDK/module/project settings until everything was working
 - Successfully "go get" a package from github
 - Import that package into main.go (intellij sees this package and autocompletes the import)
 - Use package in src

Result:
 - Says the import is unused
 - Says that "halgo" symbol not resolved, and suggests that I import "" (http://cl.ly/image/3V0S1T1D1D3J)

Other notes:
 - I can "run" this no problem, goapp successfully builds it
 - I've tried rebuilding, restarting intellij, etc., still nothing works.

**Comment by hobbs** [comment]
If it helps any, after downgrading to alpha 7, the halgo package is resolved, but nothing inside that package is resolved. So the error changes to 'Unresolved symbol "Links"'

**Comment by dlsniper** [comment]
Hi @hobbs . Thanks for the detailed report.
These problems are known to us, and while we'd love to fix them, the simple fact is that we don't have time to do it. Also, as you notice from the name of the release, 0.9.16 is alpha quality, some things are implicitly broken. You could try alpha4, I think that's the last one before the refactoring of the internal resolving engine.
We welcome any contributions that would help us move forward.
Thank you.

**Comment by estebarb** [comment]
I'm having a similar problem: if I use the Go GAE SDK then the IDE can't resolve the AppEngine packages XOR my installed packages (with goapp get <package>). Yes, sometimes are the AppEngine packages, other times are the installed packages. Other times the plugin works perfectly, and in all cases the program runs.
What should I upload to the bug report? I have tried with the 1.x, 0.9.16.x and 0.9.15.3

**Comment by dlsniper** [comment]
@estebarb GAE is not usable yet on 1.0 branch unfortunately.
Let me ping @ignatov to see if something can be done for it.
I'm afraid I still can't help w/ codding for about 1 month.

**Comment by dlsniper** [comment]
GAE support has been fixed in 1.0 branch so completion and all the other stuff should work now. Please feel free to open a new ticket if needed after the next release.
