### ISSUE TITLE
Unresolved symsbol

### ISSUE THREAD

**Issue by kostonstyle** [go-lang-plugin-org/go-lang-idea-plugin#1164]
What do I wrong? Why symbol can not resolve?
![capture](https://cloud.githubusercontent.com/assets/701611/5628360/42d370f2-95a6-11e4-84d2-f8c66614a5a2.JPG)

**Comment by mtoader** [comment]
What is the version that you are using ?

**Comment by kostonstyle** [comment]
I use 
![capture1](https://cloud.githubusercontent.com/assets/701611/5629255/bb64b098-95b1-11e4-9603-7701bc1f3c90.JPG)
![capture2](https://cloud.githubusercontent.com/assets/701611/5629257/bb6ba790-95b1-11e4-9bdd-93c48df2b08b.JPG)
![capture3](https://cloud.githubusercontent.com/assets/701611/5629256/bb6b1532-95b1-11e4-9a1f-4ca0eb272ea3.JPG)

**Comment by mtoader** [comment]
The reason 0.9.16 is not released is because it has these kind of issues. We are working on fixing them.

**Comment by fzerorubigd** [comment]
I have the exact same problem in 0.9.15.3

**Comment by justinsb** [comment]
@mtoader Is there a version that doesn't have these kind of issues?

And if not, how can I (or others) help fix the issues?

**Comment by mtoader** [comment]
The closest you can get is one of the alpha release. That fixes a lot of
those issues but it has others. Go here:
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases/ and try
the last one.

On Sat, Jan 17, 2015 at 12:42 PM, Justin Santa Barbara <
notifications@github.com> wrote:

> @mtoader <https://github.com/mtoader> Is there a version that doesn't
> have these kind of issues?
>
> And if not, how can I (or others) help fix the issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1164#issuecomment-70383502>
> .
>



-- 
Mihai Claudiu Toader
 ym: mtoader
 twitter: @mtoader

**Comment by dlsniper** [comment]
This should be fixed in 1.0

**Comment by fzerorubigd** [comment]
For my own code, yes its resolved, but now, can not detect the go symboles, like string, true, false, and other symbols. 
Is this another reported bug, or I should report it?

**Comment by dlsniper** [comment]
@fzerorubigd please follow the instructions from here:https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project and if things still don't work out for you the yes, please open a new issue (please follow the instructions on how to report issues as well). Thank you
