### ISSUE TITLE
Support for internal packages

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#1168]
For the futher information please see http://golang.org/s/go14internal

**Comment by dlsniper** [comment]
Here are some example of packages using the 'internal' package:
- https://github.com/awslabs/aws-sdk-go
- https://github.com/GoogleCloudPlatform/gcloud-golang
- https://github.com/golang/oauth2
- https://github.com/onsi/gomega
- https://github.com/garyburd/redigo

Hope this helps :)
