### ISSUE TITLE
Unable to configure a go SDK in Idea CE 14

### ISSUE THREAD

**Issue by Cornoualis** [go-lang-plugin-org/go-lang-idea-plugin#1169]
Hi,
I cannot configure a new go sdk in Idea CE 14: when I click on "new" and then select the good directory (actually, the file browser is already on the good one), then validate..nothing happens!

Versions:
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
golang: 1.4
Idea CE: 14
Os: Mac Os Yosemite

**Comment by Sorien** [comment]
same for create new project wizzard 
1.0.0 alpha, idea comunity 14.0.2, go 1.4, win 8.1

**Comment by oillio** [comment]
I have the same problem, but I get a different error:

http://pastebin.com/vKpQ01tX

Idea 14.0.2
golang: 1.4
Mac OSX 10.10.1 (Yosemite)

**Comment by Hesamedin** [comment]
Same to me. I have created a question on Stackoverfolw (http://stackoverflow.com/q/27936844/513413) before I find this issue. Please have a look at it. thanks.

**Comment by dlsniper** [comment]
@Cornoualis @oillio @Sorien and @Hesamedin please have a look here: http://stackoverflow.com/a/27939351/951414

**Comment by oillio** [comment]
Version 0.9.16-alpha.7 of the plugin (from the release page) worked for me.  Thanks.

**Comment by alesj** [comment]
Same here.
This is the stack-trace: https://gist.github.com/alesj/d08473fae4ad557ab8a4
@mtoader @zolotov ^^ HTH

**Comment by wrunk** [comment]
Thanks Alpha 7 seems to work now. I created a doc (with screenshots) for getting this plugin setup (scroll down to the IDEs section). This should help folks less familiar with IntelliJ:
https://docs.google.com/document/d/1JXFFfHxDwu4kRjhdAR6zeWPfQsnfT6yJfaq57G8Krjo
