### ISSUE TITLE
[1.0] Side-effects import statement flagged as unused

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1170]
The following code will produce a warning about unused import ``` _ "net/http/pprof" ``` but that import is a valid one per [documentation for import declartion](https://golang.org/ref/spec#Import_declarations)

```go 
package main

import (
    _ "net/http/pprof"
    "fmt"
)

func main() {
    fmt.Println("works")
}
```
or
```go
package main

import _ "net/http/pprof"
```

/** big private program that uses all of the above packages **/
```

**Comment by ignatov** [comment]
Thanks for reporting.
Please provide a small code sample for reproducing.
Without a sample we can't fix the issue.

**Comment by dlsniper** [comment]
I've updated the code sample with two scenarios that reproduce the error in both cases. Thank you.

**Comment by ignatov** [comment]
Thanks, fixed.

**Comment by dlsniper** [comment]
Confirmed. Thanks.
