### ISSUE TITLE
Out of control importing

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1180]
Most bizarre bug.  I decided that I'd try out the latest and greatest plugin since I was starting to get annoyed with some of the errors like it https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1150 .  I did a `git clone`,  went in and pointed the build to `` and everything built.  I then uninstalled the plugin, reloaded and then pointed it to install from disk.  When it restarted IntelliJ, I opened up my old project and one of my files started going haywire.  For whatever reason, in one (and only one) .go file it decides to add "" to the imports like someone is asleep on the keyboard.  So my file starts filling up like:

    import (
        "myProj1"
        "myProj2"
        "github.com/foo/bar/baz"
        "labix.org/v2/mgo/bson"
        "fmt"
        ""
        ""
        ""
        ""
        ""
        ""
    )

If I make a copy of the file and change the import to

    import (
    )

in `vim` then it starts doing:

    import ""

    import ""
    
    import ""

    import ""

    import ""

    import (
    )

This is against:
IntelliJ 14.0.2 Ultimate
build 139.659
JRE 1.7.0_72-b14 amd64
go versoin 1.4 
on Ubuntu 14.04 LTS

After playing around with commenting, I've narrowed it down to a single line in my code:

    func X(a string) ([][]string, error) {
      return baz.Foo(a) // <==== Comment out this line to make it stop repeating
    }

`baz` is  module that contains one file that has:

    package baz

    /* Comments */

    /*
    cgo pkg-config: somelib-0.1
    #include <stdlib.h>
    #include <a/b/c.h>
    */
    import "C"

     import (
        "fmt"
        "strings"
        "unsafe"
     )

    // Comments
    func Foo(a string) ([][]string, error) {
        //stuff
    }

**Comment by mtoader** [comment]
Can you try the alpha.9 release (https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases/) to see how it works for you ?

**Comment by JoeBruner** [comment]
Actually, there was a second file that was having the same problem.   It calls a function (but a different function) from the same file that had the problem above.  The code path of that function call doesn't call `baz` at all.

**Comment by JoeBruner** [comment]
Having the same problem with alpha.9

**Comment by mtoader** [comment]
That is usually happening because of the autoimport feature. If you can try to disable that in the settings it might help. One of the root causes is some sort of invalid configurations of the sdk.

**Comment by JoeBruner** [comment]
I unchecked `Show import popup` and `Optimize imports on the fly` under `Editor>General>Auto Import` and it still does it.  I did a `File >   Invalidate Caches / Restart` and still no dice.

**Comment by JoeBruner** [comment]
FWIW, this happens with 14.0.1 Community Edition as well.  I tried that and it was complaining that my GOROOT wasn't set, so I did a export GOROOT=/usr/local/go and restarted and the warning went away.  Odd that it was giving that error, as according to https://golang.org/doc/install
> Note: GOROOT must be set only when installing to a custom location.

Any other suggestions to try?

**Comment by JoeBruner** [comment]
I followed the steps at https://www.jetbrains.com/idea/help/configuring-global-project-and-module-sdks.html to set up the SDK.  Just for giggles, I removed the GO SDK from Platform Settings and Project Settings and Modules.  I then re-created it for Platform (which it knew it was Go 1.4 now) and then Project and Modules.  I did a restart and now it's even more angry.  Instead of doing 2 or so "" at a time, it's doing 5 or so.

**Comment by JoeBruner** [comment]
Reverting to 0.9.15.3 fixes the problem.

**Comment by mtoader** [comment]
Thanks for your efforts. That's one of the reasons we didn't yet released 0.9.16.

**Comment by sonicflare** [comment]
Same issue. Closing, reopening solution helps a little.

**Comment by jdeppe-pivotal** [comment]
This happens for me when I start editing a file named as `_test.go`. I created a new project and then created a filed called `throw_test.go`. Starting to type `fmt.` and the import looping starts.

**Comment by JoeBruner** [comment]
I updated to Alpha.11 and it seems to have gone away, but unfortunately 11 seems to have taken away the ability to set the ENVIRONMENT as I can't get my tests working anymore (see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1210 )

**Comment by dlsniper** [comment]
Hi, alpha#11 is from built from a different branch, with less functionality in some areas that others. Please file a different issue if you want to see something that you need and it's not there. Thank you

**Comment by JoeBruner** [comment]
This doesn't seem to be a problem with the alpha line, so I'm going to close
