### ISSUE TITLE
"cap(slice)" is error inspection by editor 

### ISSUE THREAD

**Issue by igordonshaw** [go-lang-plugin-org/go-lang-idea-plugin#1183]
IDEA version:   14.0.2
OS version: OSX 10.10
JDK version: 1.8
golang-plugin version: 0.9.16-alpha.8
    package main

    import "fmt"

    func main() {
	  slice := []string{"golang", "idea", "plugin"}
	  fmt.Println(len(slice))
	  fmt.Println(cap(slice))
   }

"cap(slice)" is error inspection by editor 

and more,this version plugin can not import package automatically

**Comment by arvenil** [comment]
I'm facing similar issues

**Comment by dlsniper** [comment]
fixed in 1.0
