### ISSUE TITLE
[1.0] Cannot register Go SDK on Windows

### ISSUE THREAD

**Issue by mkuzmin** [go-lang-plugin-org/go-lang-idea-plugin#1186]
In have 
- IDEA 14.0.2 Ultimate 
- Windows 8.1 x64.
- Go SDK 1.4.1 x64
- intellij-go plugin version 1.0 build 3

Go SDK is not registered in IDEA. When I pick c:\Go in *Select Home Directory* dialog , clicking *OK* button does nothing.

![image](https://cloud.githubusercontent.com/assets/712402/5862516/abd19252-a283-11e4-85b8-f99a98335007.png)

**Comment by ricsmania** [comment]
Hi. I'm trying this plugin and got the same problem. Also, why do we need to select the SDK? Shouldn't it read from $GOROOT?

**Comment by zolotov** [comment]
Hi @ricsmania, what version are you using?

> Shouldn't it read from $GOROOT?

1. $GOROOT variable is not required for go
2. You may want to use different versions of SDKs
3. Environment is not really convenient (do you want restart IDE on changing GOROOT?) and not reliable (especially for desktop applications on Mac) thing.

**Comment by ricsmania** [comment]
Hi @zolotov 

I'm using:

Windows 7 x64
Go 1.4.1 x64 and x86 (I have both and tried both)
IntelliJ IDEA 14.0.2 Community
Go plugin 0.9.15.3

Thanks!

**Comment by zolotov** [comment]
@ricsmania, then this is not exactly the same issue. Your case is more like #1169. Suggested solution described here: http://stackoverflow.com/questions/27936844/why-intellij-idea-cannot-find-location-of-go-sdk/27939351#27939351

**Comment by zolotov** [comment]
@mkuzmin please try build 6

**Comment by ricsmania** [comment]
@zolotov, I followed the link, installed 0.96-alpha9 and it's working now.

Thanks!
