### ISSUE TITLE
function refactor can not work

### ISSUE THREAD

**Issue by jiangyubao** [go-lang-plugin-org/go-lang-idea-plugin#1194]
package main

import "fmt"

func main() {
	fmt.Printf("Hello world!")
	test1()
}
func test1() {
	fmt.Println("hello")
	test2()
}
func test2() {
	fmt.Println("hello")
}

select test1 and press 'Shift+F6' to rename to abc, it can not work after click Refactor button.

**Comment by zolotov** [comment]
@jiangyubao specify plugin version please

**Comment by dlsniper** [comment]
I believe this is 0.9.x branch. closing as it doesn't have any feedback in more than 2 weeks.
