### ISSUE TITLE
QUESTION : How to disable autosave and gofmt?

### ISSUE THREAD

**Issue by ankushagarwal** [go-lang-plugin-org/go-lang-idea-plugin#1195]
This plugin autosaves every 2 seconds and gofmts and it's very annoying. Is there a way to disable this? Is there a preferences file?

**Comment by dlsniper** [comment]
Hi. Which version of the plugin are you using? Also, as far as I know, there's no such functionality in the plugin. The only thing possible is to format the code on save (or while typing it, which is native to IDEA), but that option is configurable in the plugin.

**Comment by ankushagarwal** [comment]
I am 0.9.16-alpha.9. How do I configure this option in the plugin?

**Comment by dlsniper** [comment]
Not sure on Mac, but on Windows / Linux you can go to File -> Settings then you can type ```go fmt``` (or ```gofmt``` if first one doesn't bring out anything) and that should be it.

This setting is per project but you can configure it when creating a new project.

You can only disable ```gofmt``` / ```goimports``` from running, not the builtin formatter.

**Comment by ankushagarwal** [comment]
Got it. Disabled it during project creation and the problem does not happen now.

Thanks.

**Comment by Jamiltz** [comment]
I have the same problem when importing a project. Is there a way to disable the gofmt on save action for an imported project?

**Comment by dlsniper** [comment]
@Jamiltz unless you are more specific, all I can say is read above. Please give us more details, and a very good question is: why do you want to disable gofmt in the first place? Thank you.

**Comment by Jamiltz** [comment]
Sorry, it wasn't well explained. Basically I was having the same problem as @ankushagarwal. In IDEA, files a re automatically saved. And I believe the go-plugin runs `gofmt` on save as well. So when I press the `enter` key it keeps reformatting (see video http://cl.ly/0r3q1O1b302x).

**Comment by zolotov** [comment]
> In IDEA, files a re automatically saved.

Not every second, not on every change, but yes it happens automatically.

 > So when I press the enter key it keeps reformatting (see video http://cl.ly/0r3q1O1b302x).

This is expected behaviour and it has nothing to do with 'go fmt'. What do you expect should be happened on enter?

**Comment by Jamiltz** [comment]
It's all good sorry for the confusion :+1:

**Comment by gonnafaraway** [comment]
You should go to File -> Settings -> Tools -> Actions on Save and turn off "Reformat code" and "Optimize imports"
