### ISSUE TITLE
[1.0] support +build flag

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1199]
```go
package main

import "net"

var _ net.TCPListener

func main() {
}
```
Unresolved type 'TCPListener'

plugin: 1.0.0.alpha#11
os: windows
idea 14.0.3 (IC-139.1117)

**Comment by ignatov** [comment]
Can't reproduce. Please share more information for reproducing.

**Comment by vastbinderj** [comment]
@ignatov do we install both jar files included in the zip file?

I was not able to create an SDK after install the larger of the two jar files.

**Comment by mark-anders** [comment]
Same here.  I installed Intellij-go.jar and inspected the plugin from within Intellij CE 14 and it said 1.0.  I then went to configure an SDK (1.4.1) and it took me to the directory, but no matter what I did, I could not select one.

**Comment by ignatov** [comment]
You need to install the whole zip file. Please the message above about the
pre-release build.

On Saturday, January 31, 2015, Mark Anders <notifications@github.com> wrote:

> Same here. I installed Intellij-go.jar and inspected the plugin from
> within Intellij CE 14 and it said 1.0. I then went to configure an SDK
> (1.4.1) and it took me to the directory, but no matter what I did, I could
> not select one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1199#issuecomment-72293341>
> .
>


-- 
Sergey Ignatov

**Comment by ignatov** [comment]
Note for Mac OS X users: you need to download the entire zip file, not a several jars (see [Apple discussion forum](https://discussions.apple.com/thread/1483114)).

**Comment by linniksa** [comment]
I hava no idea to provide more information
I'm work on windows
net.TCPListener declared in go/src/pkg/net/tcpsock_posix.go and allow to build in windows by // +build windows
maybe you check file name suffix for platform selection?

**Comment by ignatov** [comment]
That's info is ok for the next session of debugging. Thanks.

**Comment by mark-anders** [comment]
Thanks so much @ignatov !  Downloading the zip (by turning off Prefs/General/Automatically open safe files) and opening the zip fixed my problems.  I was then able to install the plugin.

Now that I've done so - WOW! I was able to open an existing, GOPATH based project and it works great!
