### ISSUE TITLE
Imports specifying a PackageName are not resolved.

### ISSUE THREAD

**Issue by Symmetric** [go-lang-plugin-org/go-lang-idea-plugin#1201]
I have an import that specifies a PackageName, like so:

```go
import (
    //...
    docker "github.com/fsouza/go-dockerclient"
    //...
)

// Sample usage
dockerData := []*docker.Container{}
```

I get the error "Unresolved symbol: Container". I can't get autocompletion for the docker package either. I have run `go get` on the go-dockerclient package, so it should be there.

If you want a working sample, the code is in the module `github.com/GoogleCloudPlatform/kubernetes` in the file `pkg/kubelet/kubelet.go`.

**Comment by dlsniper** [comment]
Hi,

Can you give us some more details please?
- which plugin version are you using? 
- how does your gopath looks like? 
- where is your project stored? 

Thank you.

**Comment by Symmetric** [comment]
Sorry, here you go:

plugin version 0.9.15 (running in pycharm v3.4.1)

Running commands from the root directory of my PyCharm project:

```bash
paul@ubuntu:~/goapps$ find -name kubernetes
./src/github.com/GoogleCloudPlatform/kubernetes
./src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubernetes
paul@ubuntu:~/goapps$ echo $GOPATH
/home/paul/goapps
paul@ubuntu:~/goapps$ pwd
/home/paul/goapps
paul@ubuntu:~/goapps$ 
```

**Comment by dlsniper** [comment]
That's an old issue of the plugin. I don't remember if 0.9.16-alpha7 (or 9) works with PyCharm but you can try that from the Releases section from Github. If it doesn't help, I'll try to make 1.0.0-alpha0 behave with PyCharm soon (but no guarantees as my schedule is a mess right now). Let me know the result.

Alternatively, you can try Idea Community + 1.0.0-alpha0 (I can help out with building it manually as there's no release for that yet).

**Comment by Symmetric** [comment]
Awesome, will give that a go -- thanks for the quick response.

**Comment by dlsniper** [comment]
@Symmetric can I close this one?

**Comment by Symmetric** [comment]
Got sidetracked and haven't had a chance to test this - feel free to close,
I will post again if the versions you suggested don't work out.

Thanks.
