### ISSUE TITLE
Can't add a new line

### ISSUE THREAD

**Issue by arekkas** [go-lang-plugin-org/go-lang-idea-plugin#1202]
Since version 0.9.16-alpha* I can't seem to create a new line by hitting enter. The new line is instantly removed and the cursor jumps back. 0.9.15 works fine!

![intellij](https://cloud.githubusercontent.com/assets/3372410/5982079/fb6ab18a-a8bf-11e4-9b01-75f4bd1a2191.PNG)

**Comment by dlsniper** [comment]
That's the first time I hear of it. Could it be that other plugins are actually the problem?

**Comment by dlsniper** [comment]
Ah, scratch that, how does your project, GOPATH and GOROOT paths look like?

**Comment by arekkas** [comment]
No, it's a fresh IntelliJ install. GOROOT is in C:\Go and GOPATH is in D:\workspaces\go\

The project can be found here: https://github.com/ory-platform/uuid-server

**Comment by arekkas** [comment]
I even reinstalled the IDE because of the problem, but it didn't fix it

**Comment by dlsniper** [comment]
As @ignatov just released earlier [1.0.0-alpha#11](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases/tag/%2311) can you try that one please?

**Comment by arekkas** [comment]
Oh cool, I'll try it tomorrow :)

Keep up the good work!

**Comment by arekkas** [comment]
Unfortunately, I didn't get past the "Select Home Directory for Go SDK" as nothing happens when I press "OK":

![go10](https://cloud.githubusercontent.com/assets/3372410/5987505/78cbbee0-a92d-11e4-906d-fd4e7abbd352.PNG)

I'll reinstall the IDE later, it seemed to have some conflicts (IDEA showed me errors regarding a missing plugin although 1.0.0 was installed) with the old version of the plugin (which I removed before of course).

**Comment by dlsniper** [comment]
@arekkas how did you install the plugin? as far as I can see you are on Windows. While I don't have a Windows machine anymore, the plugin should be installed using the zip file itself, don't extract it. I've seen similar problems reported by other early adopters, hence the question.

**Comment by alehano** [comment]
I have the same issue. When I hit Enter IDEA saves a file and gofmt runs. But in the settings I switched off gofmt command, but it doesn't work. In one project I fix it by switching on and off several time. But in a new project this bugs appeared again.

**Comment by dlsniper** [comment]
@alehano I'm not sure how that is related to this. Also, can you please say which plugin version are you using? which ide and what version? Running gofmt is not happening yet in 1.0.0.

**Comment by alehano** [comment]
In v 1.0.0 works just fine.

**Comment by dlsniper** [comment]
@alehano that's good to hear. In this case I'd advise to stay on 1.0.0 and keep an eye on updates ;) Ofc, if you have any issues feel free to open up a new issue here. Have fun ;)

**Comment by arekkas** [comment]
> @arekkas how did you install the plugin? as far as I can see you are on Windows. While I don't have a Windows machine anymore, the plugin should be installed using the zip file itself, don't extract it. I've seen similar problems reported by other early adopters, hence the question.

I extracted the zip file, thanks for the hint - I'll try it again :)

**Comment by arekkas** [comment]
Ok, after installing v 1.0.0 via zip everything works like a charm again! Thank you guys!

**Comment by dlsniper** [comment]
Good!
