### ISSUE TITLE
[1.0] Support for IDEA Community (and other IntelliJ IDEs)

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1204]
Hi,

I've tried the plugin on a Mac w/ IDEA Community and there I've got the following log: [http://pastebin.com/yL5c7X61](http://pastebin.com/yL5c7X61)
One of the big advantage of 0.9.15 / 0.9.16 was that it supported Community version as well as other IDEs as PHPStorm and so on. For now at least IDEA community would be a good start to have.
Hope it helps.

Kind regards.

**Comment by ignatov** [comment]
Please try pre-release version or build the plugin with java 1.6
```
Unsupported major.minor version 52.0
```

**Comment by dlsniper** [comment]
@ignatov you are right, that one worked.  I compiled on my laptop w/ java 8. Thank you!
