### ISSUE TITLE
[1.0] Not find the fields of a struct in a slice

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1206]
For example, I have this:

```go
type Param struct {
	Key   string
	Value string
}

type Params []Param
```

And I want to access to field "Key" but the inspector not find the field:

```go
func main() {
   n := make(Params, 0)
   n[0] = Param{Key: "hi", Value: 1}
   n[0].Key // the inspector not find the Key field
}
```

IDEA version: 14.0.3
OS version: OSX 10.10
JDK version: 1.8
golang-plugin version: 1.0.0.alpha#11

**Comment by SchumacherFM** [comment]
Having the same issue.

![screen shot 2015-02-01 at 7 18 16 am](https://cloud.githubusercontent.com/assets/372027/5989686/af050050-a9e3-11e4-9830-1e2cc1a7e282.png)

**Comment by dlsniper** [comment]
@dashaus @SchumacherFM for them the example mentioned in the original description works perfectly.
Please try to submit a minimal sample that reproduces the issue. It might be that you need different packages or something else to make it trigger, but as long as the sample doesn't reproduce the issue, it's very hard to investigate. Thanks.

**Comment by ignatov** [comment]
@dashaus your example works, please provide more information for reproducing.

**Comment by dashaus** [comment]
Ok, here a example:

```go
type Params []struct{
    Id string
}

func hola(params Params) {
    params[0]. // the inspector not find the Id field
}
```

The problem is when a custom type is a slice of struct, then this custom type is passed by argument to a function, if you want to access to the fields, the inspector does not find it...

**Comment by SchumacherFM** [comment]
The 1st example from dashaus is also working for me. The second fails.

**Comment by dashaus** [comment]
A better example:

It works:

```go
type Param struct{
    Id string
}

type Params []Param

func hola(params []Param) {
    params[0].Id  // the inspector find the Id field
}
```

But if I passed Params instead of []Param, it does not works:

```go
type Param struct{
    Id string
}

type Params []Param

func hola(params Params) {
    params[0]. // the inspector not find the Id field
}
```

It seems that the inspector does not know that "Params" is a slice.

**Comment by ignatov** [comment]
Thanks for reporting, fixed.

**Comment by SchumacherFM** [comment]
Awesome! Thank you!
