### ISSUE TITLE
[1.0] Error in syntax when declares function with arguments in various line

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1207]
![captura de pantalla 2015-01-31 17 23 10](https://cloud.githubusercontent.com/assets/1870208/5988956/20e08a94-a96e-11e4-8b54-01692ab9c531.png)

IDEA version: 14.0.3
OS version: OSX 10.10
JDK version: 1.8
golang-plugin version: 1.0.0.alpha#11

**Comment by dlsniper** [comment]
Hi, can you please send a sample code for that? To me the error in the screenshot looks valid as you are not sending a parameter after the ``` _ httprouter.Params ```...

**Comment by dashaus** [comment]
```go
 func hello(
	id string,
) error {
   return nil
}
```

The compiler compiles this without problem too.

**Comment by dlsniper** [comment]
Thanks, that should help tracking this down.

**Comment by ignatov** [comment]
Fixed, thanks.
