### ISSUE TITLE
Project creation: What is the source file path dialog about and why is New->Go disabled?

### ISSUE THREAD

**Issue by arechsteiner** [go-lang-plugin-org/go-lang-idea-plugin#1208]
With the plugin installed, I'm creating a new project and selecting "Go" without "SQL Support". On "Next", I'm getting the following dialog:

![](http://i.imgur.com/h7xlJiz.png)

I wanna point out that the browse button (...) is disabled. I'm rather confused by this dialog because I'm not sure what it means in the context of golang and because the example states java/src which makes me believe this dialogue has nothing to do with golang in the first place?

When clicking through (regardless of the choice in above dialogue), I'm getting to the newly created project in my workspace. However, on right clicking, selecting New, "Go" has always been disabled and I haven't found out how to enable it.

![](http://i.imgur.com/2wbL5Hp.png)

This is a bit confusing as a whole. Are those bugs or am I missing something here?

**Comment by dlsniper** [comment]
Hi @arechsteiner . unfortunately you've left out the plugin version. as far as I can see, that's the 0.9.16? Maybe try 1.0.0-alpha release?

**Comment by arechsteiner** [comment]
@dlsniper: It is 0.9.15.3 which I believe is the version you get by installing it through the IDEA plugins settings. From looking at the version tags this is the latest stable version, no?

**Comment by dlsniper** [comment]
At this point I'd recommend installing 1.0.0-alpha#11 as it would solve some problems in the 0.9.x branch.

**Comment by arechsteiner** [comment]
Ok, I'll try that. So what you're saying is that those *are* bugs?

Also, if it's the recommended version, why not release it?

**Comment by dlsniper** [comment]
Because, as the name suggests it, it's alpha state. Also, since me and Mihai are very busy, it's only up to two other people to work on this and time is a problem for everyone.

**Comment by arechsteiner** [comment]
I understand. Quick question: Which version of Go should I use for this alpha version?

**Comment by dlsniper** [comment]
With 1.0.0-alpha#11 you should be able to use anything from 1.2 up. AppEngine is not supported yet. I'm currently using 1.4.1. Please make sure you install the zip file, not the jars inside it. If you are on Mac, you might want to look into the readme from the v1.0,0-alpha0 branch

**Comment by arechsteiner** [comment]
How should I go about installing an alpha version from GitHub? The readme states:

> EAP download

> This is not supported anymore. We are in progress of defining a proper release channel for alpha / beta builds.

I'm not familiar with IntelliJ IDEA plugin development so any help would be appreciated.

**Comment by dlsniper** [comment]
Cool. Please feel free to close this when you think it's solved. Thanks.

**Comment by arechsteiner** [comment]
The original questions are solved, yes. The plugin still seems to create a `src` folder which I think it shouldn't (according to [this comment](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1032#issuecomment-64133084)).

**Comment by dlsniper** [comment]
Currently the way to create go projects from scratch needs work deep within IDEA itself as there are many thing that need to be changed to support the way Go wants projects to be created. Also, there's no way to tell if the user wants to create a project in the first dir of the gopath or a dir outside gopath or not in the first gopath but still in gopath.

Just ignore that folder, delete it, if you are creating projects inside gopath and that's it.
