### ISSUE TITLE
Syntax coloring: cannot set color of "Global variable"

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1211]
"Global variable" setting is missing from Editor>Color&Fonts>Go dialog.

Package variables and function variables are colored the same color in latest plugin version, thus indistinguishable from each other. Version 0.9.16-alpha.9 was ok.

IDEA: 14.0.3
Plugin: 1.0.0.alpha#11

**Comment by ignatov** [comment]
BTW, please describe your criteria of "global variable".

**Comment by dmitry-vovk** [comment]
I would say that "global" are package variables.
```go
package main
var packageVar int
func main() {
  localVar := packageVar
}
```
Having different coloring helps to see collisions, when package variable being redefined locally.

**Comment by dlsniper** [comment]
I'll need to dig in the user groups / docs again, but maybe we could use the following naming:

- package.Var1 -> Var1 is a package Exported variable
- package.var2 -> var2 is a package private variable
- struct.Var3 -> Var3 is a struct Exported variable
- struct.var4 -> var4 is a struct private variable
- func(){ var var5, var Var6 } -> var5 and Var6 are local variables

Does it makes sense for everyone?

**Comment by dmitry-vovk** [comment]
That would be great if we could set color for each type individually.
