### ISSUE TITLE
Syntax coloring: cannot set color of function name

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1212]
Func names are treated as identifiers in Editor>Color&Fonts>Go dialog.

Identifiers and function names are colored the same color in latest plugin version. Version 0.9.16-alpha.9 was ok, though function names color setting was used from "Language Defaults > Function declaration" and could not be set for Go specifically.

IDEA: 14.0.3
Plugin: 1.0.0.alpha#11

**Comment by dmitry-vovk** [comment]
Also, looks like something wrong with what plugin considers as identifier. This is what it highlights when I click on "Identifier" in the list:

![screenshot - 310115 - 21 52 47](https://cloud.githubusercontent.com/assets/4119321/5989541/1c8cb3b6-a994-11e4-8c2b-2e59eeeba2fe.png)

**Comment by ignatov** [comment]
Relates to #1211
