### ISSUE TITLE
[1.0] Inexistent fields on structs are flagged as existing when a struct with the field name exists

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1221]
The inspector recognize a field of a struct that not exists and if it makes "go to definition" over this field, this goes to a variable/struct/etc with same name

An example:

```go
package db

type Database struct {
    
}
```

```go
package main

import "example/db"

type search struct {
    generals []string
}

type context struct {
    Db db.Database
}

func initDb(c context) {
    // this is not marked as syntax error, furthermore if I make "go to definition" over
    // "search" this goes to "search" struct...
    _ := c.Db.search 
}
```

**Comment by dlsniper** [comment]
@dashaus you never import the ``` db ``` package in ``` main ```, correct?

**Comment by dashaus** [comment]
I forgot add the import statement...

**Comment by dashaus** [comment]
I also want mention that if the search struct is not created, the inspector marks it correctly as syntax error.

**Comment by ignatov** [comment]
Relates to #1222
