### ISSUE TITLE
Weird syntax highlighting color

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1224]
The syntax highlighting for backquoted-string are weird.

![image](https://cloud.githubusercontent.com/assets/1061610/5996883/e576f448-aae4-11e4-8c9a-401fb3dbfa0e.png)

Plugin version: `1.0`
OS: `ArchLinux 64-bit`
OpenJDK: `javac 1.7.0_75`
IDE used: `WebStorm 9.0.1`

**Comment by dlsniper** [comment]
Hi. Which plugin version are you using? Thank you.

**Comment by kokizzu** [comment]
1.0

**Comment by kokizzu** [comment]
1.0
