### ISSUE TITLE
[1.0] Non-IDEA IDE doesn't allow for sdk to be configured for project

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1225]
Unresolved built-in libraries/types, but the auto-complete works correctly.

![image](https://cloud.githubusercontent.com/assets/1061610/5996943/69e2a8c0-aae6-11e4-9ba6-2c5f76f9c6fb.png)
![image](https://cloud.githubusercontent.com/assets/1061610/5996950/75849332-aae6-11e4-8d25-11791d14fcf8.png)

**Comment by dlsniper** [comment]
Do you have a go sdk attached to the project? Which OS version are you using? How does your gopath looks like? 

Please read how to report errors here:https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/contributing.md#reporting-errors 

Thank you.

**Comment by kokizzu** [comment]
Plugin version: `1.0`

OS: `ArchLinux 64-bit`

```
$ javac -version
javac 1.7.0_75
```

My GOPATH: `/home/kyz/Dropbox/go`

**Comment by dlsniper** [comment]
Which IDEA version? Also where is your project located? Does the project have any attached go SDK to it?

**Comment by kokizzu** [comment]
I'm using WebStorm, not IDEA
my project located in `/home/asd/Dropbox/go/PUKIS`
How to attach the go SDK?

`Setup SDK` link cannot be clicked (nothing happened when clicked, no error on terminal)
![image](https://cloud.githubusercontent.com/assets/1061610/5996977/f48a0aa4-aae6-11e4-9d55-03a6f6800879.png)

the `Go Libraries` also only show `loading...` when clicked (also no error on terminal)
![image](https://cloud.githubusercontent.com/assets/1061610/5997027/e0b84260-aae7-11e4-9fb1-36286cbcc1da.png)

**Comment by dlsniper** [comment]
@ignatov you might want to look at this. 

@kokizzu meanwhile please use IDEA Community or Ultimate as the plugin works with those. Thank you.

**Comment by dlsniper** [comment]
@kokizzu also your project setup looks wrong as if your gopath is ```/home/asd/Dropbox/go``` then your project should be in ```/home/asd/Dropbox/go/src/PUKIS```, notice the src folder.

**Comment by kokizzu** [comment]
my bad, I forgot to type the `src/` part, it's already on `src`
```
$ pwd
/home/asd/Dropbox/go/src/PUKIS
```

**Comment by kokizzu** [comment]
Maybe this is related to this `event log`:

```
1:09:12 PM Unknown Module Type
           Cannot determine module type ("JAVA_MODULE") for the following module:"PUKIS"
           The module will be treated as a Unknown module.
```

![image](https://cloud.githubusercontent.com/assets/1061610/5997157/d8eee7ee-aae9-11e4-8f2c-072f2e8fa060.png)

**Comment by zolotov** [comment]
Go Libraries configurable is fixed. 
Related issues: #1236 and #1237
