### ISSUE TITLE
[1.0] Constants in global and function scope are not flagged as unused if unused

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1227]
In the following example:
```go
package main

import "fmt"

const demo1 = "asda"

func main() {
	const demo2 = "asda"
	fmt.Println("Hello, playground")
}
```

Both ``` demo1 ``` and ``` demo2 ``` constants are not flagged as unused even if they are unused.
As Go doesn't complain about them, as in this [playground example](http://play.golang.org/p/QCOQNsw_IQ) maybe the plugin should flag them with weak warnings?

Thank you

**Comment by ignatov** [comment]
Relates to #1226
