### ISSUE TITLE
standard types are marked as unresolved; code completion does not provide standard types and funtions

### ISSUE THREAD

**Issue by zippelmann** [go-lang-plugin-org/go-lang-idea-plugin#1229]
Hello

### the problem
Standard types like string and error are marked as unresolved. Also standard functions like len and panic are unresolved. If you need more information, let me know it. Thank you for your work on this plugin.

### example intervalDao.go
**source code**
https://github.com/zippelmann/gtt/blob/master/models/intervalDao.go

**screenshot**
![bildschirmfoto 2015-02-02 um 11 26 03](https://cloud.githubusercontent.com/assets/433536/5999064/7a3ce2d4-aace-11e4-8a0c-17518808b384.png)

**compilation in console works**
![bildschirmfoto 2015-02-02 um 11 32 27](https://cloud.githubusercontent.com/assets/433536/5999148/4876da7e-aacf-11e4-829d-05d4113c82ef.png)

**code completion for function len(..)**
![bildschirmfoto 2015-02-02 um 11 39 00](https://cloud.githubusercontent.com/assets/433536/5999242/42377b68-aad0-11e4-83cd-8f81cc2de599.png)

### example intervalDao_test.go
**source code**
https://github.com/zippelmann/gtt/blob/master/models/intervalDao_test.go

**screenshot**
![bildschirmfoto 2015-02-02 um 11 45 29](https://cloud.githubusercontent.com/assets/433536/5999345/4becf3b2-aad1-11e4-99dd-1f3e49f12388.png)

### my system:
- macos 10.10.2
- golang 1.4.1 installed via homebrew
- intellij-idea-ce 14.0.3 installed via homebrew
- golang idea plugin 1.0 alpha 11

**golang idea plugin preferences**
![bildschirmfoto 2015-02-02 um 11 20 45](https://cloud.githubusercontent.com/assets/433536/5998985/b0366b40-aacd-11e4-8460-99c36f75f35c.png)

**environment variables from .zshrc**
![bildschirmfoto 2015-02-02 um 11 42 18](https://cloud.githubusercontent.com/assets/433536/5999283/a0d3d1f8-aad0-11e4-9eeb-fbd42c81dab9.png)

**Comment by dlsniper** [comment]
Hi, How did you installed the plugin? Have you followed the instructions in the release notes? https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases/tag/%2311

Did you installed the plugin like described here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/tree/v1.0.0-alpha0#pre-release-builds (using the zip file not the jar files)?

Thank you

**Comment by dlsniper** [comment]
Is there any Go SDK attached to the project?

**Comment by zippelmann** [comment]
Yes I downloaded the zip file with firefox and it became a zip file. I selected the zip file in the plugin installer.

I am so sorry, I updated golang so the sdk path was invalid.

**Comment by dlsniper** [comment]
Good that's solved!

**Comment by zippelmann** [comment]
yeah, I realy like this plugin and the ide. It was the last I miss, when writing golang code.
