### ISSUE TITLE
[1.0] const type not work with iota used

### ISSUE THREAD

**Issue by antonikonovalov** [go-lang-plugin-org/go-lang-idea-plugin#1230]
alpha#11 from zip, InelliJ IDEA 14.0.3
![2015-02-02 14 20 10](https://cloud.githubusercontent.com/assets/1614346/5999817/da2a7d7e-aae6-11e4-9273-6d5ccd1d2468.png)
![2015-02-02 14 21 10](https://cloud.githubusercontent.com/assets/1614346/5999816/da28f698-aae6-11e4-83db-39bb2eee3311.png)

**Comment by dlsniper** [comment]
Thanks for reporting. Could you please add a sample of code that's easily copy-pastable and reproduces the issue? Thank you.

**Comment by antonikonovalov** [comment]
In next case send code, Thanks!
