### ISSUE TITLE
[1.0] Dublicate unnamed functions

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1233]
```go
func _() {
}
func _() {
}
```
Duplicate function name

**Comment by dlsniper** [comment]
Hi, this is not a bug.
Please see the [playground example](http://play.golang.org/p/MsCwet0LuS)

**Comment by linniksa** [comment]
it compiles and work

**Comment by dlsniper** [comment]
I'd rather report it to the Go team, I'm not really sure why it would be useful to have a function named ```_()``` as you cannot call it.
