### ISSUE TITLE
[1.0] Show function arguments and return value in quick doc

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1234]
Quick documentation should show the function / method full signature as the first line in the output, followed by the rest of the documentation.

Original:
Currently shown only to the function documentation.

**Comment by ignatov** [comment]
Please use a parameter info popup (Ctrl+P, Cmd+P on Mac OS X).

**Comment by dlsniper** [comment]
@ignatov should parameter info popup also the return types? Currently it doesn't

**Comment by linniksa** [comment]
@ignatov 
nothing shown to me (ctrl+p or View -> Parameter info)

**Comment by ignatov** [comment]
@dlsniper I think it shouldn't.

**Comment by ignatov** [comment]
@linniksa Please provide a sample for reproducing.

**Comment by linniksa** [comment]
```go
package main

import "fmt"

func main () {
	fmt.Println("Hello")
}
```
maybe add prototype in quick doc like in https://godoc.org/fmt#Println

**Comment by dlsniper** [comment]
Then I think it makes sense to have this done, at least for the return types as currently there's no way to tell what is the function returning (unless you are using the autocomplete, but that's the only place)

Also, I don't know how it's named, but if you ctrl+mouse over (Linux + netbeans 6.5 keymap), you only get the information for a function like this:

![snapshot102](https://cloud.githubusercontent.com/assets/607868/6004627/63693e0a-ab04-11e4-910f-a1a0c56dea10.png)

![snapshot103](https://cloud.githubusercontent.com/assets/607868/6004628/6771f01e-ab04-11e4-8521-1b4e8299c20c.png)

So there's no way to know that ``` fmt.Println ``` has return values that one can use ( ``` func Println(a ...interface{}) (n int, err error) ````) unless you pay attention when you type ``` fmt.Prin<carret-autocomplete> ```

**Comment by linniksa** [comment]
ah Ctrl+P inside brackets...

**Comment by dlsniper** [comment]
Fixed in latest release
