### ISSUE TITLE
[1.0]Compile xx.go with windows error

### ISSUE THREAD

**Issue by brenthub** [go-lang-plugin-org/go-lang-idea-plugin#1240]
log：
Error:Failed to launch go compiler: Cannot start process, the working directory C:\xxx\xxx does not exist

but my project on the disk D

**Comment by zolotov** [comment]
Duplicates #1209

**Comment by caylorme** [comment]
I get the same issue as this. It doesn't appear to be the same issue indicated by zolotov.

Having Intellij on drive C: and your GOPATH / Project on another partition results in this error. The plugin seems to think it needs to look in C:\ when my project is loaded from E:\
`Error:Failed to launch go compiler: Cannot start process, the working directory C:\GOPATH\src\github.com\myuser\myproject does not exist`

when the path of the project (it even shows this under the project window) is 
`E:\GOPATH\src\github.com\myuser\myproject`

**Comment by zolotov** [comment]
@caylorme that's all about relates to one single subsystem and we're going to get rid of it in favor of simple 'go build' running.
