### ISSUE TITLE
[1.0] Coloring for various visibility levels

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1241]
Hi,

Based on the discussion from #1211, I've created this ticket so we can keep track of the various coloring progress:

- package.Var1 -> Var1 is a package Exported variable
- package.var2 -> var2 is a package Private variable
- struct.Var3 -> Var3 is a struct Exported variable
- struct.var4 -> var4 is a struct Private variable
- func(){ var var5, var Var6 } -> var5 and Var6 are Local variables
- package.Const1 -> Const1 is a package Exported constant
- package.const2 -> const2 is a package Private constant
- func(){ const const3, const const4 } -> const4 and Const5 are Local constants
- package.Func1() -> Func1() is a package Exported function
- package.func2() -> func2() is a package Private function
- interface.Func3() -> Func3() is a struct Exported function
- interface.func4() -> func4() is a struct Private function.
-  variable redefined by usage in if statement (which makes it local to the if statement)

As a code sample, we could use this:

```go
package demo

type (
	PublicInterface interface {
		PublicFunc() int
		privateFunc() int
	}

	private interface {
		PublicFunc() int
		privateFunc() int
	}

	PublicStruct struct {
		PublicField  int
		privateField int
	}

	privateStruct struct {
		PublicField  int
		privateField int
	}
)

const (
	PublicConst  = 1
	privateConst = 2
)

var (
	PublicVar  = 1
	privateVar = 2
)

func PublicFunc() int {
	const LocalConst = 1
	localVar := PublicVar
	return localVar
}

func privateFunc() int {
	const localConst = 2
	LocalVar := privateVar
	return LocalVar
}

func (ps PublicStruct) PublicFunc() int {
	return ps.privateField
}

func (ps PublicStruct) privateFunc() {
	return ps.PublicField
}

func (ps privateStruct) PublicFunc() int {
	return ps.privateField
}

func (ps privateStruct) privateFunc() {
	return ps.PublicField
}

func variableFunc() {
	var demo1 int
	demo1 = 3

	if demo1 := privateFunc(); demo1 != 3 {
		_ = demo1
		return
	}

	_ = demo1
}
```

**Comment by dlsniper** [comment]
@dmitry-vovk did I miss anything in the example?

**Comment by dlsniper** [comment]
updated example w/ all listed use-cases.

**Comment by dmitry-vovk** [comment]
How about adding function argument(s) coloring?

**Comment by dlsniper** [comment]
Maybe those should be considered as local variables? Since they are defined in the local scope of the function. Different colors for pointers vs non-pointers would be better I think, no?

**Comment by dlsniper** [comment]
I've added variable redefined in if statements example

**Comment by ignatov** [comment]
BTW, it's a good ticket for a PR, so any help is welcome and feel free to ask me about some internal stuff.

**Comment by dlsniper** [comment]
I've looked over https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/e47bebd695bdc2990175f91fd7b58dc111d41b5b#diff-c0610615a0aedbe9e98e368d6ace7869R60 and https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/abfba5f073041b01384d512255afa9148bb765a8 and indeed it seems pretty straight forward to do it, I'll see if I can manage the time to get this done (if not one else does it before me)

**Comment by ignatov** [comment]
Relates to #1257
