### ISSUE TITLE
[1.0] Open channel check fails in assignment statements

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1247]
In go its possible to check if the channel is open or not during assignment for retrieving the value, see http://stackoverflow.com/a/16105721/951414

The plugin should always accept an extra, optional, boolean variable when the syntax is encountered.

--- Original text ---

The following example is syntactically correct and compiles perfectly well, but the plugin highlights errors:
```go
func test() (bool, string) {
	ch := make(chan string)
	var str string
	var isOpen bool
	select {
		case str = <-ch: // Reported "Assignement count mismatch: 0 = 2", but it is correct
		case str, isOpen = <-ch: // Reported "Assignement count mismatch: 0 = 3", but it is correct
		case s, ok := <-ch:
			str = s
			isOpen = ok
		case s := <-ch:
			str = s
	}
	return isOpen, str
}
```

**Comment by ignatov** [comment]
Relates to #1160
