### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by FredFool** [go-lang-plugin-org/go-lang-idea-plugin#1249]
Howdy!

I was wondering what is the state of the project? The 0.9.16 out as fast as possible statement has been there for quite some time - is there gonna be one? 

Can I get the latest build somewhere for testing? Dropbox is empty and no channel in sight.

So this issue is more about adding a wiki page and update it regulary, so people know whats the hold, where can we help and when could what happen.

Cheers guys! :)

**Comment by kokizzu** [comment]
You could use this [one](http://kokizzu.blogspot.com/2015/02/how-to-build-latest-go-idea-plugin.html)

**Comment by dlsniper** [comment]
Hi @FredFool. Unfortunately both me and Mihai have a major problem with the availability thse days. 

However, the project is making good progress thanks to Sergey and Alexander and we now have a 1.0.0 alpha which solves a bunch of problems. 

Unfortunately, people that seem interested in the project don't seem interest in help in getting isses solved, which is a shame. 

So, in short, the project is not dead, but the outside progress doesn't look much even if it's not true. 

You should check the releases on github, https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases and if you do have the time, any contribution is welcomed.

Thank you.

**Comment by dlsniper** [comment]
As for hownto contribute to the plugin, please see the readme. https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/CONTRIBUTING.md

The link from @kokizzu is missing some steps. 

Thank you.

**Comment by linniksa** [comment]
Maybe set v1.0.0 as default branch? Also auto crash plugin can be disabled.

**Comment by dlsniper** [comment]
The reason why 1.0 is not thr default brach is that things are still missing. Quite a few things.
The plan is to find the time to release 0.9.16, by fixing the few bugs it has left, and then move to 1.0.
The crash auto-reporter will be ported to 1.0 as well, sono reason to disable it.

**Comment by dlsniper** [comment]
@FredFool and all, maybe this will help you understand the situation http://www.florinpatan.ro/2015/02/the-state-of-go-plugin-for-intellij.html

**Comment by FredFool** [comment]
Hi disniper, thank you for sharing - for me it clears a lot! I am not shy about helping, but I am sure you would not want the worst java guy ever contributing code :)) 

You do all this in your free time, so no need to explain yourself in any way, we are grateful nontheless! Perhaps a wiki page about the status would be helpful for people to find out what is happening next - and we could track changes to the plan easily.

**Comment by dlsniper** [comment]
Hi @FredFool. 

First of all, don't worry about your Java skill, I have very little experience with it as well.

Bad code can be improved at review time, no code can never be improved. 

And it doesn't have to be Java 100%. You can help with tests as well (I know that it's not the most interesting thing to do, but if we have good test cases we can have better quality overall). 

As for an wiki page, that's a good idea, I'll do something about it. Thanks you (see, you are already contributing ;-) ) 


Kind regards

**Comment by dlsniper** [comment]
I've created this page: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Development-status

**Comment by FredFool** [comment]
Thanks, that could help. Keep it updated - even if it's the only change you make :))

**Comment by dlsniper** [comment]
I'm going to close the issue for now.
