### ISSUE TITLE
[1.0] variables marks as unused when it is used as key in map initialization

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1250]
The inspector does not detect the use of variables when it is used as key in map initialization

```go
package main

func main() {
    langId := "es"

    // the inspector marks langId as "unused variable"
    _ = map[string]string{langId: "hola"}
}
```

**Comment by linniksa** [comment]
It's only about map initialization:
```go
package main

func main() {
	langId := "es"
	_ = map[string]string{langId: "hola"}
}
```

**Comment by dashaus** [comment]
you've right! I changed the issue adjusted to your example.

**Comment by dlsniper** [comment]
As a small token of appreciation, thank you guys for help us out with good, reproducible, bug reports: [contributors](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/contributors.md#contributors)

**Comment by dashaus** [comment]
You welcome, @dlsniper. While I use the plugin, I will keep reporting bugs :+1:
