### ISSUE TITLE
Use Delve as debugger

### ISSUE THREAD

**Issue by tarqe39** [go-lang-plugin-org/go-lang-idea-plugin#1252]
Hi,
is dlv support integrated in plugin? I cant seem to set it up neither with gdb od dlv.

**Comment by dlsniper** [comment]
Hi, 


Delve is not yet integrated into the plugin as it's missing support for IDEs. 
Please keep an eye on https://github.com/derekparker/delve/issues/22 or help us getting it done, that always speeds things up ;-) 
Thanks

**Comment by tarqe39** [comment]
Thx for the reply. I will look into it and see if I can help :)

**Comment by dlsniper** [comment]
@tarqe39 the first thing would be building the interface with IDEs via websockets into Delve, then we can work with that for all the projects to use it. As it requires Go not Java, maybe that can be something where you could help out Delve to grow ;)

If you need any help, either ask here or on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin).

Thank you.

**Comment by dlsniper** [comment]
Delve support is done: https://github.com/derekparker/delve/pull/88 so I'll start poking around this after second week of May, should be a fun one to do, hopefully it's going to be here in time for 1.0 :)

**Comment by zolotov** [comment]
I belive it's required for 1.0, feel free to create branch for debugger, we can implement it all together.

**Comment by ignatov** [comment]
The latest nightly build contains dlv integration.
