### ISSUE TITLE
[1.next] the plugin adds a new import statement by each package added by auto-completion or by the alt+enter shortcut.

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1258]
the plugin adds a new import statement by each package added by auto-completion or by the alt+enter shortcut.

```go
package main

import "fmt"
import "database/sql"

func main() {
    fmt.Println("")
    sql.Drivers()
}
```

**Comment by ignatov** [comment]
Can't realise your problem, really.

**Comment by dashaus** [comment]
When it add a new package with an existing **import** statement, this should look as:

```go
import (
    "fmt"
    "database/sql"
)
```

**Comment by zolotov** [comment]
@dashaus why? Is there some code style convention about it?

**Comment by dlsniper** [comment]
Neither ```gofmt``` nor ```goimports``` group it like this but I believe it's the preferred way by the community to group all imports under a single import statement, like described in the example above. At least from all the packages I've seen so far (and it's how I like it as well).

The plugin can be tricked into doing one single import statement by doing the grouped import even when using a single package, then the plugin will do the rest correctly.

Maybe it could be considered as a _1.next_ improvement but I don't see any problem with this as it's working right now.

**Comment by zolotov** [comment]
@dlsniper I guess we'll have to introduce Code style options sometime, agreed about scheduling on 1.next

**Comment by dashaus** [comment]
I don't sure if this is a style convention, but almost always I see it grouped.
Anyway, I am fully agree with @dlsniper :+1:.

**Comment by m0sth8** [comment]
The official styleguide is there https://github.com/golang/go/wiki/CodeReviewComments#imports.
It says:
```
Imports are organized in groups, with blank lines between them.
The standard library packages are in the first group.
```
And really, the behaviour with imports on every package is really annoying. Every time I make a new file I have to change imports by myself.

**Comment by ignatov** [comment]
OK, we're going to use imports groups by default.

**Comment by m0sth8** [comment]
Thank you very much =) It's really important.
