### ISSUE TITLE
"Error while processing go fmt command" dialog

### ISSUE THREAD

**Issue by timequotient** [go-lang-plugin-org/go-lang-idea-plugin#1261]
I am using alpha 0.9.16-dev-0.9.16-alpha.9 on Windows 8.1 with Intellij 14.0.2.  Every time I save a Go source file I am getting a pop up dialog stating "Error while processing go fmt command".

From the source I looked and saw the plugin code is trying to call "go fmt <file>" and encountering an exception.  Is there an easy way to tell what command it is executing?  I did not find any logs in the logs.

For the record I am using the Google App Engine SDK and I have confirmed if I run "goapp.exe fmt <file>" everything works fine.

As a work around, is there any way I can disable the formatting?

**Comment by dlsniper** [comment]
Hi,  search for "gofmt" or "go fmt" in IDEA settings and you can find the option. It not, let me know and I'll let you know exactly the settings path to search for.

**Comment by timequotient** [comment]
I was able to find the setting, thank you for letting me know!  

I figured this is just working around the issue thought.  If you would like help as in logs or running a debug build, please let me know as I'd be happy to help in any way I can.

**Comment by dlsniper** [comment]
Thanks. Glad to know it worked. I think I know where the problem is but I'm not sure if I'll fix it for 0.9 branch or port AppEngine support for 1.0.
I'll ping you if I need the logs, thanks.
