### ISSUE TITLE
[1.0] Now to create a subpackage of arlready exists package

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1262]
![example](https://cloud.githubusercontent.com/assets/424343/6061863/672935e0-ad5c-11e4-800a-ef2d69931fe2.png)
How i can create a internal/frontend package?

**Comment by dlsniper** [comment]
I think this should be reported to https://youtrack.jetbrains.com/dashboard rather than here. It's not something that the plugin does. (@ignatov please correct me if I'm wrong). I'll close this for now.

**Comment by linniksa** [comment]
it not only about how i can create a package
internal.backend is not valid go package reference it should be internal/backend, and allow created package internal/frontend

**Comment by dlsniper** [comment]
If you open you ```moduleName.iml file``` can you see a line like this:
```<module type="GO_MODULE" version="4">```
or like this:
```<module type="JAVA_MODULE" version="4">``` ?

**Comment by linniksa** [comment]
```xml
<module type="GO_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="GOPATH &lt;watcher&gt;" level="project" />
  </component>
</module>
```

**Comment by linniksa** [comment]
this not work with slashes
![2015-02-05 18 10 20](https://cloud.githubusercontent.com/assets/424343/6062633/55063f88-ad62-11e4-9906-f8e146809e04.png)

but work with dots

**Comment by dlsniper** [comment]
How do you get the "New Package" dialog? I don't have any option to create a new package as far as I can see

**Comment by linniksa** [comment]
![123](https://cloud.githubusercontent.com/assets/424343/6062829/b514d3d4-ad63-11e4-9fdb-c0eddf9dada9.png)

**Comment by dlsniper** [comment]
Ok, so then we are back on my original assumption.

It's IDEA who does that as a platform not the plugin.

The problem comes in when you mark a directory as source and then you have the option to create a ```Package``` but that ```Package``` is in fact a Java package, not a go specific package.

So, please report it to JetBrains, see the link above, as that conflicts with other project types (such as the one for Go). I'd be surprise if there's no report for this already, as it's annoying for me as well so it must be for others. I couldn't find any option in IDEA to not compress paths in project view.

Thanks.

**Comment by dlsniper** [comment]
P.S. If you unmark src as source, the package option won't be there anymore and the behavior will disappear.

**Comment by linniksa** [comment]
![2015-02-05 18 59 09](https://cloud.githubusercontent.com/assets/424343/6063536/217c8800-ad69-11e4-9ca6-60b98ca736f4.png)
it is golang package source

**Comment by dlsniper** [comment]
What I mean is unmark it like in the screenshot below:

![snapshot105](https://cloud.githubusercontent.com/assets/607868/6064632/99e3054e-ad5f-11e4-9528-1bc3c2578d26.png)

**Comment by dlsniper** [comment]
Also, I'm not sure about your layout and how you have stuff organized, so please share, but what I have is this:

GOROOT (aka where the SDK is): /usr/local/go
GOPATH: /home/florin/golang
and all my projects are in /home/florin/golang/src/<orgName>/<projectName>

As for the libs, I have this:
![snapshot106](https://cloud.githubusercontent.com/assets/607868/6064771/8b495faa-ad60-11e4-97b6-6cc144994142.png)

**Comment by dlsniper** [comment]
Ah, finally found it. Disable the checkbox in the screenshot and the project view won't compact the empty package names.

![snapshot107](https://cloud.githubusercontent.com/assets/607868/6064931/a6a9fccc-ad61-11e4-83f0-ac7c96d1f440.png)

**Comment by linniksa** [comment]
@dlsniper Thankns.
Also interesting with unmark directory as source:
 - all files and folders have yellow background
 - some inspection is false positive, for example:

```go
package app

var App; // app marked as unused

```
```go
package main

func main() {
    app.App.Init();
}
```

**Comment by dlsniper** [comment]
Interesting. If you marknitnas source again does it still happen?

**Comment by linniksa** [comment]
no, if i mark src as source this have white background and App not marked as unused

**Comment by linniksa** [comment]
![2015-02-06 18 53 57](https://cloud.githubusercontent.com/assets/424343/6082322/ac5059fc-ae31-11e4-815d-5fab0add871b.png)
![2015-02-06 18 54 04](https://cloud.githubusercontent.com/assets/424343/6082323/ac50dcd8-ae31-11e4-8a27-96412e1d567c.png)

**Comment by dlsniper** [comment]
That's another feature of IDEA, not plugin specific. I asked for screenshots as I wasn't sure if it was the same things I was thinking about. Thanks.
