### ISSUE TITLE
<parameter declaration> expected, got ')' 

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1265]
The library that I'm working with has functions that has many parameters with long names.  To make the code more readable, the parameters a put one per line (a standard practice in many languages).  When doing this in Go, you need to put a comma after the last parameter if the ) isn't on the same line as the last parameter.

https://play.golang.org/p/97hdtV0Qwf

![image](https://cloud.githubusercontent.com/assets/5578559/6081669/6ebf78ea-ade9-11e4-81a8-35bec183ae61.png)

**Comment by dlsniper** [comment]
Hi @JoeBruner, which version of the plugin are you using? What IDE are you using? Can you also provide a sample of code that reproduces the error in a copy-pasteable manner? Thanks

**Comment by JoeBruner** [comment]
IDE 14.0.3
Alpha 11

func Foo(
  x int,
  y int,
) int {
  return x + y
}

**Comment by linniksa** [comment]
interesting:
'.' after `d int64` show as expected character
also if i place point after int (int.):
![2015-02-06 18 52 37](https://cloud.githubusercontent.com/assets/424343/6082298/6c0b339e-ae31-11e4-8e60-0fab56e7ab20.png)

**Comment by dashaus** [comment]
This error is already fixed. I reported it here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1207

**Comment by JoeBruner** [comment]
Ahh.  I did a quick search for a similar issue but didn't run accross #1207.  Sorry about that.
