### ISSUE TITLE
[1.0] Cannot resolve directory import within the same project

### ISSUE THREAD

**Issue by notzippy** [go-lang-plugin-org/go-lang-idea-plugin#1266]
Under "Go Libraries" I have added my "gopath" to Global libraries, (this path does not include the code that is contained in the ide). The project libraries and module libraries are empty. The "src" folder is marked as the source. The error "Cannot resolve directory" pops up for all packages imported that are in the same source tree. Although packages that are in the go library or the go path library are resolved without issues. 

Other oddness, opening source code (that is able to be resolved through an import, ie code that is in the GOPATH) opens fine, but any imports that code does fails to be resolved as well.

I am coming from 0.9.16 and testing 1.0.0 alpha so if this is still an alpha limitation feel free to close, but if I missed something setting up the module let me know..

**Comment by zolotov** [comment]
Sorry but it's impossible to recreate the issue with some "gopath" and resolving "some directory" from unknown file. I need more details about your workflow.

> Other oddness, opening source code (that is able to be resolved through an import, ie code that is in the GOPATH) opens fine, but any imports that code does fails to be resolved as well.

Code sample please. Also Go Libraries screenshot and local path to your project could be useful.

**Comment by notzippy** [comment]
Here is an example of not being able to resolve a structure within the project
![gosnap](https://cloud.githubusercontent.com/assets/1387526/6084970/bc88655e-adea-11e4-8074-5e29ebd76488.png)

**Comment by zolotov** [comment]
And Go Libraries screenshot?

**Comment by notzippy** [comment]
Here:
![golibsnap](https://cloud.githubusercontent.com/assets/1387526/6085280/37157030-aded-11e4-8445-75f07910f3d6.png)

**Comment by zolotov** [comment]
Works fine for me. Please try this build: https://dl.dropboxusercontent.com/u/2304564/Go.40.zip

**Comment by notzippy** [comment]
Thanks, unfortunately same issue. running idea 14.0.3 , invalidated the cache and restarted. Same issue

**Comment by dlsniper** [comment]
Could you please post the paths that you have for:

- project path
- gopath
- if there's any symlunk going on (at least from the screenshot I'm getting a feeling that something like that might be involved

Also, in the project view, under External libraries which nodes do you see? There should be two, one for the sdk and one for the gopath libs, if you use the standard layout. Is there any package with the same name in the gopath?

**Comment by notzippy** [comment]
Project Path : /home/homeu1/**work**/IWork/GoLangTest/
gopath : /home/homeu1/**work**/builds/gopath/
External Libs below:
**work** is a symlink, in the gopath, project path, and go sdk home.
![golibsnap1](https://cloud.githubusercontent.com/assets/1387526/6088467/95b91876-ae0b-11e4-8af2-d18c967f7d12.png)

**Comment by dlsniper** [comment]
Thanks for the info. If you go on ```  /home/homeu1/work/IWork/GoLangTest/src/github.com/foobar/``` and run ``` go run GoLangTest.go ```, does it compile?
Also, can you please paste the output of your ``` go env ``` command?

**Comment by notzippy** [comment]
No it does not, the gopath does not point to the root of the project, but if I add to the gopath like

	...GoLangTest>export GOPATH=$PWD:GOPATH
	...GoLangTest>go run src/github.com/foobar/GoLangTest.go 
	Hello world!Hi there {}
	...GoLangTest>go env
	GOARCH="amd64"
	GOBIN=""
	GOCHAR="6"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/mnt/DevSystem/Work/IWork/GoLangTest:GOPATH"
	GORACE=""
	GOROOT="/home/homeu1/work/builds/go"
	GOTOOLDIR="/home/homeu1/work/builds/go/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
	CXX="g++"
	CGO_ENABLED="1"

It works, (opps I messed up the export in the gopath... o well)

So is it a requirement for the source folder to be part of the gopath ? The previous module did not have this requirement.

**Comment by dlsniper** [comment]
I'm not sure it's a requirement as much as it's a different case of using go and gopath.

In this case, it looks like you are using something similar to the [second use-case here](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/GOPATH-use-cases#b-global-multiple-paths)

Also, in the above script, there's an error.
Instead of
```shell
export GOPATH=$PWD:GOPATH
```
you should do
```shell
export GOPATH=$PWD:$GOPATH
```
or even better, as this allows you to keep the first directory as the one where go get stores the common packages
```shell
export GOPATH=$GOPATH:$PWD
```

I'll try and confirm the setup in the weekend.
Thanks.

**Comment by notzippy** [comment]
Yup I fat fingered the export, I added a symlink to my gopath folder (gopath/src/github.com/foobar --> projectpath/src/github/foobar) for the project and it was able to resolve the model.A structure, but when you click to drill into it intellij thinks it is opening the file in the gopath, not the file in the local project, so that doesnt strike me as being the right way either....

**Comment by dlsniper** [comment]
@notzippy your use case doesn't fall into the "normal" (or better said, most common) use case. Also any symlinking and so on is likely to create more problems that it solves.
The reason why I asked earlier for the output of ```go env``` and if the project compiles was the fact that I needed to know if go itself works on your setup or not. Given the steps you've took to "fix" the problem, it makes me to think that my first statement is indeed true.

I think I have a better grasp of the problem now but as I'm not near my computer I'll wait until tomorrow to test and (hopefully) replicate the issue, then I'll post here my findings so that @zolotov can have a better look on it.

Thanks for helping us tracking down the issue.

**Comment by kokizzu** [comment]
Same thing for me (using latest git go plugin, Idea Ultimate 14):

```
$ echo $GOPATH 
/home/asd/Dropbox/go
$ pwd # project path
/home/asd/Dropbox/go/src/PUKIS
```

**Comment by evandertino** [comment]
## Its simple just follow the steps below
![step1](https://cloud.githubusercontent.com/assets/2353639/6091615/ad2f2602-aec5-11e4-9945-8dc116c2a503.png)
![step2](https://cloud.githubusercontent.com/assets/2353639/6091616/b7cba7b6-aec5-11e4-9396-08f081d564fd.png)
![step3](https://cloud.githubusercontent.com/assets/2353639/6091617/d3a7656a-aec5-11e4-847a-20aa89e3ad52.png)
![step4](https://cloud.githubusercontent.com/assets/2353639/6091618/d5dd53e4-aec5-11e4-8d3c-1ea752e5a0fd.png)
![step5](https://cloud.githubusercontent.com/assets/2353639/6091619/d7b211d2-aec5-11e4-850d-5bb99911b125.png)
![step6](https://cloud.githubusercontent.com/assets/2353639/6091620/d95074d4-aec5-11e4-9c82-5f4eb42a5a95.png)
![step7](https://cloud.githubusercontent.com/assets/2353639/6091621/db2ed1ce-aec5-11e4-9ff6-ef099a525df6.png)
### And it will automatically detect your GOPATH

Happy Coding :smiley:

**Comment by dlsniper** [comment]
@zolotov I have a way to reproduce the issue described by @notzippy , please see below. Drom pe a line on Gitter if it's not clear and I'll try to be more helpful.

As I suspected, it's the [second use-case](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/GOPATH-use-cases#b-global-multiple-paths) from the wiki doc (maybe I should have made it more clear, sorry).

The setup is like this:
- GOPATH -> ```/home/florin/golang```
- Go libraries | Global libraries -> ```/home/florin/golang```
- project path -> ```/home/florin/IdeaProjects/untitled2```

Expected result:
- if GOPATH would be changed to: ```/home/florin/golang:/home/florin/IdeaProjects/untitled2``` then go toolchain would be able to compile everything
- as we have a case of multiple values in the GOPATH, each folder from should contain the layout 
```shell
ls -l /home/florin/golang
bin/
pkg/
src/

ls -l /home/florin/IdeaProjects/untitled2
bin/
pkg/
src/
```
- packages will me contained under the ```src/``` folder from each gopath folder

Obtained result:
- as in the screenshot below, IDEA can do the auto-completion part
- however, it marks a valid import path as being invalid.

![snapshot108](https://cloud.githubusercontent.com/assets/607868/6091582/6f674424-aeb3-11e4-96db-e939912a37a9.png)

The order in which the go tool resolves the packages (at least in 1.4.1) is the following:
- GOROOT (sdk dir)
- GOPATH[1]
- GOPATH[2]
....
- GOPATH[n]
where GOPATH[x] is a directory from GOPATH.

For example, with my settings is:
- /usr/local/go/src/*
- /home/florin/golang/src/*
- /home/florin/IdeaProjects/untitled2/src/*

Hope it makes sense. Thank you.

**Comment by dlsniper** [comment]
I've also checked the case made by @kokizzu. Unfortunately I can't reproduce the problem. @kokizzu please ping me on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin) so that I can work with you to solve the problem.

His problem is like this:
- GOPATH -> ```/home/florin/golang ```
- Go libraries | Global libraries -> ```/home/florin/golang```
- project path -> ``/home/florin/golang/src/untitled3```

The expected result is that I should be able to define a package ```demo``` in ```/home/florin/golang/src/untitled3/demo``` and  the import should work by just using ```untitled3/demo``` as the import path.

I have no idea what's happening for him but I'll try and dig out the problem.

However, the original poster is correct with his use-case.

**Comment by dlsniper** [comment]
@evandertino I do not understand the reason why you need to add the project itself as a library to itself. What problem did you faced? if it doesn't fit into what I've described above, please open a new issue. Thank you.

**Comment by tijs** [comment]
I am having the same issue as some of the people above (i think) although i do not have my project outside of my GOPATH. I'm running IDEA 14.0.3 with the latest 1.1 plugin from the releases page.

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tijs/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
The GO SDK is automatically detected correctly and from any file in my project it can resolve the imports but when i open any of the 'external' dependencies, which reside in the same GOPATH as my project code, it cannot resolve the dependency. So with the `go env` settings above my project file:

    GOPATH/github/tijs/myfile.go

Would work, and i can cmd+click a function to go there. But if i would open one of the files in a dependency like:

    GOPATH/github/someone/other.go

Than in that file none of the imports from the go library are resolved but imports from the GOPATH *are* resolved...

```
package other

import (
	"net/http" # this is 'red'

	"github.com/gorilla/mux" # this is 'green'
)
```

I tried adding the gopath myself in the plugin configuration but that did not help. Also on the current project configuration i cannot select a module "Error: module not specififed" since the select is empty. Which might be related, or not, hard to tell :)

**Comment by dlsniper** [comment]
@tijs I think this is just a config issue on your end. Please ping me on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin) so we can talk there further without spamming the ticket. Thanks.

**Comment by dlsniper** [comment]
@zolotov I've confirmed the issue with @kokizzu and it was a setup issue on his end. Things work for him now. However [my comment](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1266#issuecomment-73357445) is still valid for the original prolem described.

**Comment by zolotov** [comment]
@dlsniper thanks a lot for investigation, I'll look at it asap.

**Comment by notzippy** [comment]
@dlsniper thanks for demonstrating it better than I did, if you need a build tested let me know.

**Comment by zolotov** [comment]
@notzippy since the project is part of GOPATH I've just added it to Go Libraries and everything works fine now. Does it work for you?

**Comment by notzippy** [comment]
If you do that, then Ctrl+click a type the ide thinks the code is outside
the project scope

**Comment by zolotov** [comment]
What does it mean?

**Comment by notzippy** [comment]
I am not sure I understand your original post, if I symlink the project source to the GOPATH the project will resolve imports but the file locations will be messed up and the plugin thinks that the imported file is different then the file in the source folder. IMHO the source folders inside the IDE should be internally added to the gopath so that the ide may be able to resolve imports.

**Comment by dlsniper** [comment]
@notzippy can you drop me a line on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin) either on the public room or in private so that I can better understand the problem you have and help Alexander solve it? Thank you.

**Comment by zolotov** [comment]
@notzippy I'm not saying about symlinking anything to GOPATH, just add you project root to Settings | Go Libraries.

>  IMHO the source folders inside the IDE should be internally added to the gopath so that the ide may be able to resolve imports.

It shouldn't, there are other different approaches of project organising that don't require this.

**Comment by notzippy** [comment]
@dlsniper Sorry was away, am back again if you want to discuss

**Comment by notzippy** [comment]
Closing issue, was all my fault - I was adding my paths to Project structure - when I should have been adding them to the Settings->Languages & Frameworks -> Go Libraries (frack).

Sorry for the time waste...

**Comment by zolotov** [comment]
Thanks for update
