### ISSUE TITLE
[1.0] Incorrect variable scope resolution in switch context

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1269]
In the following example, the var ```err``` declared in ```main()``` will be flagged as unused variable.
However, in the ```switch``` syntax it it used correctly.
If you look at the screenshots, it reveals how the shorthand assignment from withing the case statement 
will take over as the one that declares the variable for the remaining of the code execution while in the switch statement.

```go
package main

import "fmt"

func Demo() error {
	return fmt.Errorf("err")
}

func main() {
	var err error

	switch  {
	case 1==2:
		err := Demo()
		panic(err)
	default:
		err = Demo()
		panic(err)
	}
	//panic(err)
}
```

![snapshot109](https://cloud.githubusercontent.com/assets/607868/6092552/26096fb0-aee4-11e4-978f-95fc5aaafcc5.png)

![snapshot110](https://cloud.githubusercontent.com/assets/607868/6092554/34cdcb68-aee4-11e4-93a6-14b19faf73d3.png)

Thank you.

**Comment by dlsniper** [comment]
Hi @ignatov,

I have to reopen this, seems the initial example was not good enough to reproduce all the scenarios. The scenario reported above works, but the one below doesn't.

Please see below another one for which the issue happens again:

```go
package main

import (
	"fmt"
)

func someFunc() error {
	return fmt.Errorf("someFunc")
}

func otherFunc() {

}

func someOtherFunc() (string, error) {
	return "demo", nil
}

func main() {
	var (
		boolVar bool
		demo string
		err error
	)

	switch {
		case boolVar:
		err := someFunc()
		if err != nil {
			otherFunc()
		}
		default:
		demo, err = someOtherFunc()
		if err != nil {
			otherFunc()
		}
	}

	_ = demo
}
```

Thank you.

**Comment by dlsniper** [comment]
Not sure if it's related, or I should open a different ticket for this one but I've found another example where a variable redeclared inside of a switch (case) statement and used later on in the function is referencing to the scoped declaration not to the non-scoped one. Please see the example bellow:

```go
func demoFunc(demo1 int) {
    demo1 = 2
    switch {
    case 1==2 :
        demo1 := 1 // variable referenced below the switch statement
        _ = demo1
    default:
        _ = demo1
    }

    _ = demo1  // here the variable is referencing to the one in the case declaration
}
```

**Comment by ignatov** [comment]
@dlsniper Please provide a link to the reference. I can't actually understand the rules.

**Comment by dlsniper** [comment]
@ignatov, I'm not sure I can help you with more that https://golang.org/ref/spec#Declarations_and_scope

Should I improve the second example maybe?
