### ISSUE TITLE
1.0.0.alpha#11 can work on mac but no ubuntu

### ISSUE THREAD

**Issue by paulhsu** [go-lang-plugin-org/go-lang-idea-plugin#1270]
1.0.0.alpha#11 can work on mac but no ubuntu

I use idea 14 to try on both platforms

**Comment by dlsniper** [comment]
Hi @paulhsu . Unfortunately your report is extremely not helpful.

Please read [how to report bugs](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/tree/v1.0.0-alpha0#bugs)

Also, including some more details about the problem would help.
Does anything appear in the log files from IDEA, do you have any exception triggered by the plugin? Even more helpful would be to know what doesn't work exactly...

Thank you.

**Comment by dlsniper** [comment]
Even more documentation on [how to report bugs](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/CONTRIBUTING.md#reporting-errors) (which can be read when creating an issue).

**Comment by vdininski** [comment]
Was on 1.0.0.alpha#11 and moved to 1.0.0.alpha#58 on Ubuntu 14.04 with Idea 14 Community - both are working fine.

Should this be closed are reopened when/if feedback is provided?

**Comment by dlsniper** [comment]
@vdininski are you colleague / friend with @paulhsu ? I'd still like to understand what happened there as it might hide a different problem. Thank you

**Comment by vdininski** [comment]
I don't know @paulhsu. Just thought some input regarding Ubuntu would've been useful.

**Comment by dlsniper** [comment]
I see, thanks. I'm also running on Ubuntu, but I haven't encountered an issue, hence the question.

**Comment by dlsniper** [comment]
I'm closing this as it doesn't have feedback from the author. Please feel free to open it again if needed.
