### ISSUE TITLE
Can't add the go sdk

### ISSUE THREAD

**Issue by Salon-sai** [go-lang-plugin-org/go-lang-idea-plugin#1272]
I installed the plugin in the IDE. After restarting the IDE,the Event log show me that 
Problem with env variables
         GOPATH environment variable is empty or could not be detected properly.
         This means that some tools like go run or go fmt might not run properly.
         See instructions on how to fix this. (show balloon)

Meanwhile,I can't add the go sdk with the support.

OS version : win8.1
IED version : 13.1
go version : 1.4
plugin version : 0.9.5

**Comment by Salon-sai** [comment]
the repositories only have the plugin with version 0.9.5

**Comment by dlsniper** [comment]
@salon-sai which repository are you talking about? Please check the github releases section of this repository and you will find 1.0.0-alpha#11. Follow the install instructions and everything else and rhings should work for you.
