### ISSUE TITLE
Unresolved reference to all built-in packages

### ISSUE THREAD

**Issue by kalopsia** [go-lang-plugin-org/go-lang-idea-plugin#1273]
Hello, after upgrading to the new version (1.0.0.alpha#11) new problem was appeared! Please see screenshot.

![screenshot from 2015-02-08 22 04 11](https://cloud.githubusercontent.com/assets/6209197/6097898/10e0a166-afdf-11e4-9eee-59e53a4a8041.png)

Any built-in packages are unresolved. Invalidate caches and restart doesn't solve the problem.
My settings:
 - idea 14.0.3 (139.1117)
 - go 1.4.1
![screenshot from 2015-02-08 22 12 21](https://cloud.githubusercontent.com/assets/6209197/6097927/9f840b42-afdf-11e4-95af-cf77c83938a8.png)

- ubuntu 14.10 )
- project directory you can see from the screen
- environments:
  - export PATH=$PATH:/usr/local/go/bin
  - export GOPATH=$HOME/cloud/go
  - export GOPATH=$HOME/cloud/go

**Comment by dlsniper** [comment]
Hello,

Please create a new SDK for the project as the previous SDK version is not compatible with the new one.
If you have any problems, ping me on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin).

@ignatov, I'm not sure about the SDK upgrade, we used to have this capability to upgrade SDKs between versions of the plugin where we changed things. Do you think it's worth investigating?

**Comment by ignatov** [comment]
@dlsniper For instance, we can show a file-level notification if detect the previous SDK and ask to reimport it.

**Comment by kalopsia** [comment]
> Please create a new SDK for the project as the previous SDK version is not compatible with the new one.
If you have any problems, ping me on Gitter.

Hey! Creating new SDK really solve this problem. Thanks! It is the first time when there is no any "resolve" problems for both built-in and custom packages!

![screenshot from 2015-02-08 22 45 47](https://cloud.githubusercontent.com/assets/6209197/6098081/6eb2e7b8-afe4-11e4-8dea-f2d89ef42164.png)

However as you can see there is now syntax highlighting for var names or packages namespaces. Highlighting looks a little bit chilly. Is it new behaviour?

**Comment by dlsniper** [comment]
Glad it worked!

Yes, 1.0.0-alpha branch has a completely rewritten engine and some (most) of the things that used to work in the previous version are not yet ported. Syntax highlight is one of them, you can see one example of an open issue [here](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1241).

We warmly welcome any contributions to the plugin ;)

I'll close this for now, you can still add comments to it and so on. If you do encounter something else, feel free to open further issues (please search for already created ones in milestone 1.0.0 first).

**Comment by kalopsia** [comment]
Good. I'm glad that it worked even only now! Thanks)
