### ISSUE TITLE
[1.0] Possible Infinite loop when indexing go source repository

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1276]
It seems that the indexing phase of the go sources never stops, I've left it running for more than 10 minutes.

Steps to reproduce this:
- git clone https://go.googlesource.com/go
- use ```File | Open``` and point it to the sources
- don't add any SDK or anything else

Version used: commit sha 3b48c1f1980a55b5a4c46879b582e9b98ffc3aea

**Comment by ignatov** [comment]
Reproduced, thanks. We need to unify index/slice expression. File to reproduce is ```./test/torture.go```.

**Comment by dlsniper** [comment]
:+1: I've just finished profiling it myself and was about to send the snapshot. Thank you!
