### ISSUE TITLE
[1.0] Analysis becomes slow when New() method exists

### ISSUE THREAD

**Issue by m0sth8** [go-lang-plugin-org/go-lang-idea-plugin#1277]
Idea 14.0.3, plugin alpha#58

After I add `New` function in empty file then inspection analysis becomes very slow.
I don't know what is the reason for that. Maybe it's because I worked on a big project with a lot of New functions in different modules??

![image](https://cloud.githubusercontent.com/assets/470078/6099199/3157edea-afd1-11e4-9c83-8483903abb24.png)

**Comment by dlsniper** [comment]
This might be related to the #1276 but I'm not sure that the ```New``` is the one that triggers it. Unfortunately I'm too tired to check it now, I'll run it in YourKit tomorrow and see where the time is spent.
Thanks.

**Comment by ignatov** [comment]
@m0sth8 Can't reproduce with my test project. Please share a code example or a sample project for reproducing.

**Comment by dlsniper** [comment]
@m0sth8 can you check the latest v1.0.0-alpha0 branch and see if the problem still happens to you?

**Comment by m0sth8** [comment]
@dlsniper Sure, how can I built alpha0 for MacOs?

**Comment by dlsniper** [comment]
Follow these steps:
- ```shell 
git clone git@github.com:go-lang-plugin-org/go-lang-idea-plugin.git
git checkout v1.0.0-alpha0
```
- open the project in IDEA
- ```Build | Build Artifacts | Go.zip```

In case you don't have them already:
- configure the Java SDK to be version 6 (I assume you are using java6 not the experimental java8 release of IDEA)
- configure the IntelliJ SDK to use IDEA as sdk

If you have any problems, drop me a line on Gitter ;)

**Comment by m0sth8** [comment]
@ignatov 

1) Make an empty project with `src`
2) Download `github.com/docker/docker` to the `src`
3) Make an empty go file in `src` 
4) If you have a function `New()` in this file then inspection is slower then if you have a function `NewF()`
5) [Optional] If you duplicate docker project then inspection becomes slower and slower.

**Comment by m0sth8** [comment]
@dlsniper I've built the latest v1.0.0-alpha0 and nothing changes for me =(

**Comment by ignatov** [comment]
@m0sth8 Thanks for the STR, I'm going to investigate it soon.

**Comment by ignatov** [comment]
@m0sth8 some work's been already done for this issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/util/GoUtil.java#L137-137

**Comment by m0sth8** [comment]
It seems like the issue has gone. Thank you!
