### ISSUE TITLE
[1.0] Add support for Go tip SDK

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1279]
Currently it's not possible to add the Go tip SDK (aka custom build from git repository, usually on HEAD). The SDK detection rules should be improved to support this case.

**Comment by dlsniper** [comment]
Obsolete

**Comment by hyangah** [comment]
Does it mean the plugin now support Go tip?
I am using plugin 0.9.296, and it doesn't allow me to set the tip as Go SDK yet.
I get "The selected directory is not a valid home for Go SDK" error message if I select the tip go directory.

**Comment by dlsniper** [comment]
I wish the go team would be consistent on their naming....
@hyangah you are right, go tip is not supported anymore, I'll reopen this...

**Comment by dlsniper** [comment]
I'll fix it this weekend.

**Comment by dlsniper** [comment]
Fixed in #1602
