### ISSUE TITLE
Func init() wrongfully reported as duplicate

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1280]
In Go "each source file can define its own niladic init function to set up whatever state is required" ([from official site](https://golang.org/doc/effective_go.html#init)).

**Expected result:** each file in a package can have own ```func init()```, and that is not considered as duplicate.

**Actual result:** Plugin marks ```func init()``` with "Duplicate function name" error when there are more than one file in a package, each having the function defined.

**Plugin version:** 1.0.0.alpha#58

**Comment by dlsniper** [comment]
This duplicates #1213.
