### ISSUE TITLE
Support godep project workspaces

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1282]
Godep has it's own way to save and the use the dependencies in a project, thus providing a special, isolated, workspace for each project.

It would be nice if the plugin would detect automatically the ```Godeps/Godeps.json``` when the project is created / imported / folder is opened and then configure the library sources to point first to the ones in the ```Godeps``` dir, then the rest of the GOPATH.

Normally, a GOPATH for a godeps project looks like this: ```GOPATH=`godep path`:$GOPATH```.

Also, this means that the plugin should have a way to introduce the way the libraries are used in the project.

More info about godeps here: https://github.com/tools/godep

**Comment by drpotato** [comment]
Any progress on this?

**Comment by dlsniper** [comment]
The plan is to evaluate this after 1.0 is released. There are quite a few different dependency management tools out there and go1.5 will also add its own. 

Meanwhile, people should be able to create a project in the normal way then set the Project Libraries to the _vendor directory and things should work out (instead of doing this automatically). Please try it this way and if it doesn't work, open a separate issue. Thanks

**Comment by dlsniper** [comment]
As a reference for others:

- For the Go one there's this discussion here: https://groups.google.com/d/msg/golang-dev/74zjMON9glU/4lWCRDCRZg0J and this is the commit: https://groups.google.com/d/msg/golang-dev/74zjMON9glU/EOKSoaL5p8wJ

- other dependency management tools: https://github.com/golang/go/wiki/PackageManagementTools (list is too long to list here)

**Comment by dlsniper** [comment]
As Go seems to standardize against a common format (for which we have already a ticket) I'll close this one.
