### ISSUE TITLE
[1.0] Order of Go Libraries

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1283]
Hello,

While creating #1282 I realized that there should be a order in which the libraries are used for both auto-complete and executing the various go tools.

Following the logic that could be found in the wild, I believe the best way to use them would be:
```
GOPATH=Module_Libraries:Project_Libraries:Global_Libraries
```

This will allow people to configure projects with Godeps for example, which assume that their local dependencies are first in the GOPATH then the actual GOPATH is used (due to the way of how GOPATH is processed by the go tools)

If this is the current order, I'm sorry, I just needed to clarify it so that I can document it.

Thank you

**Comment by zolotov** [comment]
Yes, it's in current order while passing to external tools. Completion and resolving doesn't consider their order at all, @ignatov do you think that order could be important for resolving stuff?
