### ISSUE TITLE
Do not fold imports by default

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1293]
When opening an old file imports are folded by default

![image](https://cloud.githubusercontent.com/assets/1061610/6160924/f151801c-b29b-11e4-986e-6ab8652313b1.png)

This is quite annoying when we need to move certain function to another package.

**Comment by kokizzu** [comment]
and it seems that the configuration doesn't work..

`editor` > `general` > `code folding` > `import`, checked or unchecked has no effect

**Comment by zolotov** [comment]
I won't change default settings but I'll fix the configuration

**Comment by zolotov** [comment]
> This is quite annoying when we need to move certain function to another package.

And what exactly is annoying? Why do you need modify imports by hand?

**Comment by kokizzu** [comment]
It's related to this issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1294

**Comment by zolotov** [comment]
It's not really. And question is still open: why do you need modify imports by hand?

**Comment by kokizzu** [comment]
Annoying because I have to expand first.. (`ctrl+shift++`) then add or rename the imported package, my use case is: a function named `fun1` moved from `pkg1/subpkg1/fun1/foo.go` to `pkg2/fun2/bar.go` (the `Refactor` > `Move` doesn't work well, so I do it manually)

**Comment by zolotov** [comment]
What about using Optimize imports action and adding imports by Alt+Enter shortcut? Does it work for you?

**Comment by kokizzu** [comment]
After moving the function to another package, since the package name still wrong and the caller still uses old package, optimize import doesn't work..

`Alt+Enter` shortcut works but I still have to move my cursor to the unimported package name.

and one more thing, I use backtick ``` instead of double quote `"`, that's why I like to do it manually..

**Comment by zolotov** [comment]
> After moving the function to another package, since the package name still wrong and the caller still uses old package, optimize import doesn't work..

Well it's quite correct behaviour. Package statement has more priority then the directory.

> Alt+Enter shortcut works but I still have to move my cursor to the unimported package name.

F2

> and one more thing, I use backtick "`" instead of double quote"`, that's why I like to do it manually..

Fair enough, I think we need introduce the code style settings for that.

**Comment by kokizzu** [comment]
Well thank you ^^

**Comment by zolotov** [comment]
Folding configuration will be fixed in the next build. Also I've filed an issue about code style #1302
