### ISSUE TITLE
[1.0] Possibly slow inspection / syntax analysis

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1296]
In the go SDK, please see the file ```src/crypto/md5/md5block.go``` 
The file contents are a bit special by themselves, so not sure how relevant things are, but at some point you can notice how 1-2 inspections will stop in place for a fraction of a second.
Hope it helps

**Comment by ignatov** [comment]
Hmm, can't reproduce, the code analysis is pretty fast for this file. Please attach a performance snapshot.

**Comment by dlsniper** [comment]
Hi @ignatov, sorry for delay.
Please have a look at the section from 04:07 to the end, the section before that is done by IDEA starting and loading the project.

https://www.dropbox.com/s/uyjk4j49difrrgi/IntelliJIdea14-2015-02-20.snapshot.zip?dl=0

It's done directly from YourKit attached to a standalone IDEA instance. 

Thank you

**Comment by ignatov** [comment]
Please repeat your activity and record a new one.
https://www.yourkit.com/docs/java/help/cpu_intro.jsp

Sergey Ignatov

**Comment by dlsniper** [comment]
I'm a noob. Here it is: https://www.dropbox.com/s/60w4p07qiuo5lt9/IntelliJIdea14-2015-02-20-1.snapshot.zip?dl=0

**Comment by dlsniper** [comment]
The timing for the issue is from minute 2, I've just typed something random and quickly undone it.

**Comment by dlsniper** [comment]
and the commit hash for the plugin is: 4f59cb0a3e0bd69d20c09c088a2b8c4a5589bb55

**Comment by ignatov** [comment]
Nothing interesting, just symbols resolution. If you can share a project
it'll be cool.

Sergey Ignatov

**Comment by ignatov** [comment]
Are you still suffer from this?

**Comment by dlsniper** [comment]
I can't tell for sure at the moment as I've switched laptops to an older model and some things are slower by default. I'll close it for now.
