### ISSUE TITLE
[1.0] goto label not recognized as a valid identifier

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1298]
The docs from language specs: https://golang.org/ref/spec#Goto_statements

```go
package main

func main() {
	for a:= 1; a<10; a++ {
		goto err
	}
	err: // <statement> expected, got '}'
}
```

**Comment by ignatov** [comment]
Very funny that the official specification has a non-optional statement here: https://golang.org/ref/spec#Labeled_statements

**Comment by dlsniper** [comment]
I've got that from the Go sdk, guess they need better docs as well :-D
