### ISSUE TITLE
[1.0] Functions with multiple return parameters used in function calls are flagged as "not enough parameters"

### ISSUE THREAD

**Issue by kalopsia** [go-lang-plugin-org/go-lang-idea-plugin#1300]
Please see the screenshot. I don't know why it happens, but actually go code is correct and properly work.

![screenshot from 2015-02-12 22 11 08](https://cloud.githubusercontent.com/assets/6209197/6174991/15465c1e-b304-11e4-9df8-e897d2681fe9.png)

![screenshot from 2015-02-12 22 06 49](https://cloud.githubusercontent.com/assets/6209197/6174978/fa392654-b303-11e4-91ac-78654bfcea38.png)

**Comment by dlsniper** [comment]
Here's an example to reproduce this:

```go
package main

import "html/template"

func main() {
    _ = template.Must(template.New("t").Parse(`temp`))
}
```

**Comment by dlsniper** [comment]
I've added a much better example to reproduce it :)
