### ISSUE TITLE
[1.0] inline defer/go without method call doesn't show an error

### ISSUE THREAD

**Issue by rekby** [go-lang-plugin-org/go-lang-idea-plugin#1308]
For example any of the lines:
```go
func demo() {
	defer func(){} // syntax error: argument to go/defer must be function call
	go func(){} // syntax error: argument to go/defer must be function call
	func(){} //func literal evaluated but not used
}
```
must be show as error but they aren't.

I use plugin 1.0.0.alpha#58

**Comment by linniksa** [comment]
Same for go statement, in golang this produce same error:
> syntax error: argument to go/defer must be function call

**Comment by dlsniper** [comment]
Thanks both for reporting, I've updated the example to contain all the cases ;)

**Comment by ignatov** [comment]
@linniksa @rekby deref/go case has been fixed. "evaluated but not used" it's another inspection, please file another issue.

**Comment by dlsniper** [comment]
I've opened #1310, thanks for solving it!
