### ISSUE TITLE
unresolved reference with gorilla websocket pkg

### ISSUE THREAD

**Issue by jakecoffman** [go-lang-plugin-org/go-lang-idea-plugin#1312]
I tried getting this boiled down to what exactly was causing the problem with no luck. Something in the gorilla websocket package is causing the error returned from Upgrade to be unrecognized. 

1.0 alpha branch on Windows, 14.0.3 Community Edition

```
package main

import (
	"fmt"

	"github.com/gorilla/websocket"
)

func main() {
	_, err := websocket.Upgrade(nil, nil, nil, nil, nil)
	if err != nil {
		fmt.Println(err.Error()) // unresolved
	}
}
```

**Comment by dlsniper** [comment]
Hi @jakecoffman, what do you have in the ```Settings | Languages & Frameworks | Go Libraries ```?

It might be a bit of a configuration issue with the project libraries, please try and see the [setup guide](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project) for 1.0.0 projects, hopefully that should help solve the problem.

**Comment by ignatov** [comment]
Reproduced.
