### ISSUE TITLE
"The selected directory is not a valid home for Go SDK" still happen

### ISSUE THREAD

**Issue by XinwenCheng** [go-lang-plugin-org/go-lang-idea-plugin#1313]
Hi @mtoader ,

"The selected directory is not a valid home for Go SDK" still prompt even I installed Go successfully on Windows 7 Enterprise SP1.

I use Intellij Idea V14.0.3 Community Edition with Go V1.4.1 amd 64, and I've added bin directory path of Go to System Path. Command "go env" works correctly.

But I still meet "The selected directory is not a valid home for Go SDK" when I'm trying config Go SDK in Intellij Idea.

Sorry, I'm new to Go, would you please help to check? Thanks very much!
![gosdkerror](https://cloud.githubusercontent.com/assets/795334/6202347/7bc5381c-b51f-11e4-96aa-29971cc3d8e4.JPG)

**Comment by dlsniper** [comment]
Hi @XinwenCheng, please add the root directory of the go SDK, in this case ```C:\Go``` rather that the bin dir. That should work.

**Comment by XinwenCheng** [comment]
Hi @dlsniper , when I choose C:\Go but not C:\Go\bin, this error message won't be shown after I click OK button, but panel below Project SDK: of New Project dialog will still be empty.

**Comment by dlsniper** [comment]
Sorry, I don't have a laptop with Windows anymore so I can't help reproducing the issue.

**Comment by XinwenCheng** [comment]
@dlsniper thanks all the same!

**Comment by andornaut** [comment]
I'm experiencing a similar issue on Ubuntu 14.04. I select /usr/local/go in the "Select Go home folder" window, but then nothing is displayed in the New Project / Project SDK window.

go 1.4.2
Idea 14.0.3
go-lang-idea-plugin 0.14.15

The go installation appears to be working fine otherwise.

**Comment by dlsniper** [comment]
@andornaut unfortunately I'm not aware of any version of the plugin called 0.14.15. Where did you installed the plugin from? Also how did you installed the go sdk?

**Comment by andornaut** [comment]
@dlsniper Sorry, that was a typo. I meant 0.9.15. The latest version no longer exhibits this issue, though.

**Comment by dlsniper** [comment]
ok, glad to hear it's fixed. Please use the 1.0.0-alpha releases until we'll get a chance to release the 1.0.0 stable on the plugin manager :)

**Comment by andornaut** [comment]
Will do, thanks!

**Comment by fwlab** [comment]
I have exactly the same problem under Yosemite Mac OSX.

**Comment by dlsniper** [comment]
@fwlab can you please send more details than that? It's very had to identify a problem by commenting on a closed issue with "me too". Which plugin version do you have? Have you read the readme of the project? How did you installed go? Which settings have you made before coming here?

**Comment by fwlab** [comment]
Hello. 
I'm using the last Go and Google App Engine Go SDKs available now: 1.4.2 golang.
I had tried the version which came installed via the IntelliJ Idea standard repositories. 

I then switched to the alpha version of the plugin (0.2.9.1).
The alpha version of the plugin does indeed recognise the Install path correctly. 
Why isn't the default plugin repository updated? 
The "standard" version is pretty much unusable in its state, if it does not recognize valid golang and go gae installs.

**Comment by dlsniper** [comment]
@fwlab the plugin currently is in alpha releases as it's not where we want it to be yet. I agree it's not nice to keep the old version around but it will be updated when it will be updated :)

**Comment by YeTianZhou** [comment]
go to the latest ideaIU version~Yeah I fix the problem.

**Comment by MKeshta** [comment]
I had this problem once and i solved it be opens the application in android studio and run it them opened it in intilij..
