### ISSUE TITLE
Builtin functions colored as identifiers

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1319]
[Builtin functions](http://golang.org/pkg/builtin/) (such as ```new```, ```make```, etc.) are predefined and should have different coloring (e.g. as keywords), but now those are colored as identifiers.

IDEA: IU-140.2285.5
Plugin: 1.0.0.alpha#92

**Comment by dlsniper** [comment]
I'll see if I can fix it in #1315
