### ISSUE TITLE
New Go File is not valid

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1320]
As of alpha#92

If I try to right click on a dir in my project and do `New > Go File` and try to create a file of name `Foo.go` it will error saying 

    'foo.go' is not a valid Go file name

If I change it to just `foo` it works fine.  The error is not intuitive that it's trying to automatically append the `.go` extension to the file name.  Also, it should be smart enough to know that if you append the `.go` to just roll with it.

**Comment by dlsniper** [comment]
I'll take a stab at this and do it before the next alpha
