### ISSUE TITLE
Incorrect "No new variables on left side of :=" when func in signature

### ISSUE THREAD

**Issue by carmandrew** [go-lang-plugin-org/go-lang-idea-plugin#1323]
When I pass a function to a method, and that function takes named arguments, the plugin says those variables are already defined, but they shouldn't be. For example, this shouldn't be an error:

![generic_go_-__s0__-_s0_-____code_s0_](https://cloud.githubusercontent.com/assets/630721/6222363/036ed3bc-b607-11e4-8487-373ad35c9f1c.png)

**Comment by dlsniper** [comment]
Hi @carmandrew, can you please be more specific with the issue? Which plugin version are you using? Also, can you post a minimal sample code that reproduces the issue? Thank you.

**Comment by landaire** [comment]
This is actually correct. You have `stop` as a parameter. `:=` is used for declaring and inferring new variables. Use the `=` operator instead. The playground provides the same error message: http://play.golang.org/p/-5g7eANxSl

And proper: http://play.golang.org/p/xqBBvpE1th

**Comment by dlsniper** [comment]
@landaire thanks for investigation. I've missed that detail. I'll close this for now based on that. 

@carmandrew please feel free to reopen it if you have more details on this. Thank you.

**Comment by carmandrew** [comment]
Sorry, should have made a playground example. [Here is a working example](http://play.golang.org/p/ZRKivMoenv). But when I copy it into intellij 14.0.3 with plugin version 1.0.0.alpha#92, it shows the error I mentioned above:
![generic_go_-__s0__-_s0_-____code_s0_](https://cloud.githubusercontent.com/assets/630721/6233784/4e590298-b68a-11e4-8d26-3daaf72d6e13.png)

**Comment by landaire** [comment]
Ah I had misread the original example -- my mistake. Yes, the plugin doesn't separate the parameter to `operation` and the local scope.
