### ISSUE TITLE
Execute Go format after saving file

### ISSUE THREAD

**Issue by raoptimus** [go-lang-plugin-org/go-lang-idea-plugin#1324]
hotkey on macosx: cmd+alt+shift+f (uncomfortably)
please execute command "go fmt" after saving file (great)

thank you

**Comment by dlsniper** [comment]
@ignatov I'd like to work on this. Also, after I finish on the highlight PR, maybe I can get some guidance for formatter. Thanks.

**Comment by mmadfox** [comment]
hotkey on macosx: cmd+alt+shift+f (uncomfortably)
please execute command "go fmt" after saving file (great)

thank you

**Comment by povod** [comment]
"hotkey on macosx: cmd+alt+shift+f (uncomfortably)
please execute command "go fmt" after saving file (great)"

it's seem there should be an option, to switch between mods. I think this will be a more right way )

**Comment by rogierlommers** [comment]
Is it possible to run go fmt at the save file event? If so, how? I'm using version Go.92.zip.

**Comment by dlsniper** [comment]
Right now I'm not sure if it's possible (unless there's a way to make it so from IDEA to run a tool on file save). I'll work on integrating the option to do either gofmt, goimports or nothing on save, make the shortcuts configurable for the actions we have right now and push it hopefully in time for the next alpha. Then I'll start working on the formatter, which should hopefully make things easier and render gofmt or goimports not needed (as it should be since we are an IDE).

**Comment by rogierlommers** [comment]
Great to hear! Love your plugin. Works fine and will be even better I suppose!

**Comment by raoptimus** [comment]
I found a solution - plugin File Watchers
but would still be more convenient to integrate into your plugin

**Comment by jakecoffman** [comment]
You can also create a macro where you go fmt and then save-all. Bind that macro to ctl-s or whatever you usually hit to save. The only downside is when it saves on lose focus it won't go fmt.

**Comment by rogierlommers** [comment]
Therefore It's better to solve this with the plugin itself.

**Comment by raoptimus** [comment]
![](http://i.imgur.com/Yt5hMca.png)

**Comment by dlsniper** [comment]
As this can be solved without changing the plugin, I'll close this for now.
The proper way to solve this would be to have the plugin take advantage of the builtin formatting engine anyway, which is the plan for 1.0 release.

**Comment by dlsniper** [comment]
We've decided not to use this approach but rather fix the formatter. Please watch #1215 for progress on it.

**Comment by jaytaylor** [comment]
It's worth noting that it is necessary to install the "File Watcher" plugin to use the workaround proposed above proposed in the interim.

**Comment by zolotov** [comment]
@jaytaylor how do you usually save files in IDEA?

**Comment by jaytaylor** [comment]
The standard way:

    Ctrl-s

(or `Cmd-s` on darwin).

**Comment by zolotov** [comment]
@jaytaylor so if this ok for you to use shortcut for saving and formatting why don't you invoke cmd-alt-shift-l instead? It will save file and invoke gofmt. Also you can rebind this action to any other shortcut, even to Cmd-s.

**Comment by jaytaylor** [comment]
Ah, now I see!  Thank you for the info, I didn't know about that shortcut.

It still seems preferable to have gofmt happen on cmd-s so remembering a different rule for Intelli-J compared to other editors (vim, sublimetext) is not necessary.

**Comment by zolotov** [comment]
> It still seems preferable to have gofmt happen on cmd-s so remembering a different rule for Intelli-J compared to other editors (vim, sublimetext) is not necessary.

Unfortunately it inevitably because intellij saves your files always (on loosing focus, on completion, on intention, on refactoring, on run, etc.), and other editors requires explicit Cmd+S.

As I said before, due to frequent file saving the main concern is that the code under caret will be changed by gofmt. Imagine you're typing some code and in the other moment the line you're editing is moved down and the caret on the empty line now, I'm sure nobody likes this. 

Also there might be a problem with big files. Imagine that IntelliJ decided to save file and invoke gofmt, and you're continuing typing. If gofmt work a few seconds on big file, you'll have time to type several symbols, so when gofmt finished there would be conflict between result of gofmt file version and file version in the editor – also not enjoyable situation.

**Comment by zolotov** [comment]
@jaytaylor sorry, I said the wrong shortcut, the proper one is `shift ctrl alt F`

**Comment by jaytaylor** [comment]
That's right, I hadn't made that connection yet of these foreseeable
issues.  I don't really like auto-save so I've disabled it (though I
can understand the appeal, especially if one is able to use Intelli-J
exclusively).

Should disabling auto-save make the cmd-s gofmt behavior safe and function
similarly to vim?

**Comment by zolotov** [comment]
> Should disabling auto-save make the cmd-s gofmt behavior safe and function
similarly to vim?

Not exactly safe, but indeed it would much safer. Nice idea actually to provide gofmt on save via settings with the suggestion to disable auto-save. Thanks.

**Comment by openinx** [comment]
FileWatcher under mac osx  is working.  :)

**Comment by raoptimus** [comment]
> FileWatcher under mac osx is working. :)

yep

**Comment by jeromefroe** [comment]
Does anyone else run into the an issue with File Watcher that it runs `go fmt` or any other command (for example `golint` or `goimports`) you have set up on files that you do not have open? I used my $GOPATH directory as my working directory in Intellij and when I use `go get` to download a repo it runs the File Watchers I have set up on all the files that I pull down even though I don't open them in Intellij.

**Comment by dlsniper** [comment]
@jeromefroe please jump on Gitter https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin or open a new issue, there's a bunch of people on this closed issue :) Thanks.

**Comment by jeromefroe** [comment]
Sorry. That I will do!

**Comment by seratch** [comment]
Just FYI

With IDEA 2017.2.3, I needed to setup a file watcher as below:
<img width="638" alt="screen shot 2017-09-16 at 14 56 22" src="https://user-images.githubusercontent.com/19658/30509588-3e8b80c4-9aef-11e7-8930-92aeab432b99.png">

**Comment by dlsniper** [comment]
@seratch fyi, this plugin is no longee supporting intellij idea community 2017.2+. If you use the JetBrains maintained plugin, then there's a simpler way to run gofmt on save: Settings | Languages & Frameworks | Go | On Save

**Comment by seratch** [comment]
@dlsniper Thank you so much! It works for me.
