### ISSUE TITLE
Quick fix for not exists packages - "run go get for this package"

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1331]
if package not exists in GOPATH/GOROOT add user quick fix (not sure it's the right name) which launches "go get" command for this package

maybe for very known prefixes like github.com/code.google.com/golang.org etc.

**Comment by zolotov** [comment]
There is one https://www.dropbox.com/s/u0mwv4257e0260d/Screenshot%202015-02-20%2012.18.24.png?dl=0

**Comment by linniksa** [comment]
I missed it.
though it seems he has a lower priority (?) than the "unresolved import":

```go
package main

import (
	"github.com/golang/net/html" // if i write this after html.Parse i not see quick fix before two clicks in this line
)

func main() {
	html.UnescapeString("123");

	return
}
```

**Comment by zolotov** [comment]
Yes, 'import popup' is too noisy, I'll try to fix it
