### ISSUE TITLE
Change usage from unidentified to proper usage types in the 'Find usages' functionality

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1332]
Right now, if you do a find usages or a variable, function or anything else, things work but there's no separation between assignment and reading, definition and usage for example.

**Comment by dlsniper** [comment]
@ignatov I'm not sure if it's such a problem for 1.0, but I'd like to work on it myself rather than you or Alexander if that's ok for you. I'd want to learn more from the internals and hopefully this should help ;)

**Comment by ignatov** [comment]
See `com.intellij.codeInsight.highlighting.ReadWriteAccessDetector`.
