### ISSUE TITLE
Can't run app in 1.0.0.alpha#92

### ISSUE THREAD

**Issue by mark-anders** [go-lang-plugin-org/go-lang-idea-plugin#1333]
I'm on a Mac, 10.10.3, using Idea community edition 14.0.3 with alpha#92.  I've opened existing projects and created new ones and, after creating a run config get the following error:

Error running <filename.go>:  Cannot start process, the working directory <proj-path>/out/production/<proj-name> does not exist.

Even if I create the ./out/production/name directory, I still get the error.

**Comment by zolotov** [comment]
Indeed, application run configuration is broken now. 'Go Run file' works fine though.

**Comment by mark-anders** [comment]
Will try that.  

Thanks!

Mark

(Sent from my iPhone)

**Comment by Scukerman** [comment]
I have the same problem with new project...
How to setup compile and run configuration?! And where is my executable file will be stored?

I'm totally confused. When i ran "Make" Event log tells me "All files are up-to-date", but where?! I suppose this information about my executable file...or not

Can you provide some doc or screens, or example project to view how does it working?
Because I'm still can't work with 1.0.0, but want to...

Now I'm so sad and using 0.9.16-alpha.9

**Comment by dlsniper** [comment]
@Scukerman, I'll quote from @zolotov : 
> Indeed, application run configuration is broken now. 'Go Run file' works fine though.

Just go to ``` Run | Edit Configurations | + | Go Single File ```, select the file that contains the ```main()``` function and things should work.

**Comment by Scukerman** [comment]
@zolotov, Yeah I'm doing the same stuff, it runs and it works...but where is the executable file?!

**Comment by zolotov** [comment]
Go Single File run configuration is synonym to `go run` command. It doesn't produce any executable files.

**Comment by Scukerman** [comment]
Then what I should do if I want to get executables?
Should I just wait for a new release where it's gonna be working or can I use another build with working "application run configuration"?

**Comment by dlsniper** [comment]
You can test that things work from the IDE using the configuration described above.

As for getting a binary, you can safely use ``` go build ``` until there's a release that can build executables. Please refer to [the manual](https://golang.org/cmd/go/) on how to use it.

**Comment by zolotov** [comment]
@Scukerman  in IDEA – nothing, as I said before it's broken, it will be fixed soon but in the end IDEA is not a build tool so the building abilities will be poor anyway.

Without IDEA – there is [some docs](https://golang.org/cmd/go/) about it

**Comment by Scukerman** [comment]
@zolotov, @dlsniper: Yeah, thanks to you both. I know about manual compiling and I'm using it, but it's not comfort and I thought it should be somehow working like on first place of plugin implementation.

**Comment by dlsniper** [comment]
@Scukerman normally you need the binary only for deployment or running outside the IDE itself. While I know Alexander is working on this feature very hard, it's not an easy thing to support as the original implementation was... not nice (to put it nicely).
As the releases say, the plugin is in alpha, and, as the docs say in the release notes, some features might not be there yet. Else I'm sure we'd tell @mark-anders and others as well :D

**Comment by Scukerman** [comment]
@dlsniper Of course I understand that :+1: Just want to get it asap ;-)

**Comment by dlsniper** [comment]
@Scukerman we are always welcoming contributions. So if you'd like to see something in, we'd definitely like a contribution to fix this issue. Thank you for your patience.

**Comment by zolotov** [comment]
@mark-anders running should be fixed in 1.0.0alpha#164. Please check it out.
@Scukerman making binary files not implemented yet and I'm not sure that it will be targeted on 1.0.0 release. Please create a separate issue for that.
