### ISSUE TITLE
Support for file-based projects (.ipr)

### ISSUE THREAD

**Issue by frogprog** [go-lang-plugin-org/go-lang-idea-plugin#1340]
GoProjectLibrariesService storages need to be modified like this to support ipr projects:

  storages = {
    @Storage(id = "default", file = StoragePathMacros.PROJECT_FILE),
    @Storage(id = "dir", file = StoragePathMacros.PROJECT_CONFIG_DIR + "/" + GoConstants.GO_LIBRARIES_CONFIG_FILE, scheme = StorageScheme.DIRECTORY_BASED)
  }

**Comment by dlsniper** [comment]
@frogprog thanks for this. Please feel free to open up a PR with the change.
Also, for which version of the plugin would you like to see this one?
Thanks.

**Comment by frogprog** [comment]
@dlsniper I'm not sure what you mean about version. I've downloaded the latest 1.0.0.alpha#92 and because all my projects are file-based I wasn't able to save any of them - IDEA was throwing errors about missing macros. So I think its necessary to include this fix ASAP (for folks like me).

Thank you for hard work! Today I was able to upgrade from some old 0.9 release at last :) New version feels so much better.

**Comment by dlsniper** [comment]
@frogprog that's actually the work of @zolotov and @ignatov that you are seeing, for which I'm very glad as well. ;)

Happy to hear you like the new version.

Maybe you can detail a bit the use case, as I can't figure it out right now, but it might be helpful for other parts of the plugin as well.

Thank you for your contribution ;)

**Comment by frogprog** [comment]
Use case of a file based project? I just select it when creating the project..

![ipr-project](https://cloud.githubusercontent.com/assets/5803104/6310025/17471a3a-b953-11e4-8110-b7fd3728d505.png)

**Comment by ignatov** [comment]
It's a legacy storage format (https://www.jetbrains.com/idea/help/project.html#file_based_format)

**Comment by frogprog** [comment]
@ignatov when it will be dropped from IDEA?

**Comment by ignatov** [comment]
I don't know actually, but can ask a responsible developer.

**Comment by chashnikov** [comment]
We can probably remove this option from 'New Project' wizard but we'll still need to support file-based project created in previous versions of IDEA, so it wouldn't make much sense. However I think we can add @Storage annotation for file-based format implicitly to avoid such problems, feel free to create an issue about that in [our tracker](https://youtrack.jetbrains.com/issues/IDEA).

**Comment by dlsniper** [comment]
I've opened https://youtrack.jetbrains.com/issue/IDEA-137327 and I'll see if I can send a PR with the first part of the change to remove the ipr stuff from the UI.

Is there a way I could do the PR to make it in time for IDEA 14.1? Thank you.

**Comment by chashnikov** [comment]
IDEA 14.1 is currently in stabilization phase and will be released in a few weeks so I don't think that this change should be pushed to it.
