### ISSUE TITLE
[1.0] Autoimport completion for variables and constants 

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1346]
```go
package main
func main() {
    os.<caret>
}
```

Also i think autocomplete should contain package name itself, for example if i write os first 2 lines got from vfs package:

![123](https://cloud.githubusercontent.com/assets/424343/6315803/7f3843a4-ba1f-11e4-838f-20e78028e06b.png)

**Comment by zolotov** [comment]
There is no dot in your screenshot, so it's supposed that you may want to complete the function/type that is called "os". With the dot I can't see any function from not os-package.

**Comment by zolotov** [comment]
BTW, types/function from already imported package have more priority, so they will be on the top on completion list. After completing type/function from not-imported package, the proper import will be added. I don't see any misleading/confusing things here. Any details are welcome as always :)

**Comment by linniksa** [comment]
at this time if package not imported autocomplete only show methods for example os.Stdout, io.EOF (vars) is not shown.

**Comment by zolotov** [comment]
Sorry, I didn't understand the issue then. You're right, variables and constant are not supported in this way yet. I believe it's important to support it, thanks for the issue.
