### ISSUE TITLE
Cat not set project sdk

### ISSUE THREAD

**Issue by kostonstyle** [go-lang-plugin-org/go-lang-idea-plugin#1347]
I can not set project sdk, even when clicking on the link 

![image](https://cloud.githubusercontent.com/assets/701611/6316148/0517487a-ba1c-11e4-90a3-ecc9a787e96f.png)

What do I wrong? Why is the key words are red?
I am using webstorm 9.0.3

**Comment by dlsniper** [comment]
@kostonstyle thanks for reporting this. I can confirm the issue happens to me as well. Please use IDEA Community until this gets fixed.

@ignatov I've tried to reproduce this by building 3de78e607bc4282517671d1ff4c01ffea3161352 and the installing and running in a standalone WebStorm installation (WS-139.1112 to be more exact). Iirc this happened before this commit as well so it's not something new.

**Comment by dlsniper** [comment]
I also can't see anything else in the logs mentioning any error/exception with the plugin.

**Comment by kostonstyle** [comment]
I download the community edition, works until now like a charm. Good work guys.
