### ISSUE TITLE
A package should not be able to import itself

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1350]
$GOPATH/src/demo/fol/fol.go
```go
package fol

func Func1() {}
```

$GOPATH/src/demo/fol/fol_test.go
```go
package fol

import "demo/fol"

func Demo() {
    fol.Func1()
}
```

**Comment by ignatov** [comment]
@dlsniper please assign everything about import to @zolotov by default.

**Comment by sjamesr** [comment]
Can this be closed?

**Comment by dlsniper** [comment]
Oh, yes, it can. Thank you for catching this!
