### ISSUE TITLE
Can't use any imported packages, from the go get command 

### ISSUE THREAD

**Issue by moadqassem** [go-lang-plugin-org/go-lang-idea-plugin#1355]
Hello,

I have just imported the mgo package which is the mongodb driver for go, I tried to get it from idea but I keep get this error:

Something went wrong with `go get`
 package gopkg.in/mgo.v2: cannot download, $GOPATH not set. For more details see: go help gopath, even so the GOPATH is set and if I get it from the command line(" go get gopkg.in/mgo.v2 ") I can see it imported and when I build my project(from the command line) it builds successfully however if I try to use the imported package from idea it wont work.

Go version: go version go1.4.1 linux/amd64
plugin version: 0.9.92 
and idea : 14.0.3 
OS: Ubuntu 14.04
GOPATH: /home/moath/Development/goprojects/go/golak

Thanks in progress

**Comment by moadqassem** [comment]
Hey I have found the solution for it even so its really weird, I had to add the gopath inside the /etc/profile next to the goroot and then it worked, it supposed to be working to if I have set the path in .bashrc !! anyway its working now

**Comment by dlsniper** [comment]
@moadqassem with 1.0 release you should not be doing that.

How did you created the project? And what did you added to the Go Libraries under: ``` Settings | Languages & Frameworks | Go Libraries``` ?

Also, have you seen this page: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project ?

**Comment by moadqassem** [comment]
Hey, I ve just did what its written in that page by details, however it didn't work and I have no idea why, so I am doing I am only using idea as text editor and if I want to build or run the project I do it from the command line which is fair and square to me, I don't know mate but sounds really weird !!

**Comment by dlsniper** [comment]
Can you please post some screenshots of the Go SDK and Go libraries. It's a very strange error and I'd rather track it down and either fix the docs or fix the issue.

Thank you for helping us.

**Comment by moadqassem** [comment]
I have just found out what was the problem and basically it's not an issue maybe its a workaround solution(ugly one I know specially when it becomes to the root permissions).

The thing is the go sdk or the plugin its self looks for the GOPATH and if it didn't find it it goes to the root and looks in it too, which means if you have set the gopath in the /etc/profile you don't need to add it via idea(File ->Settings->Languages & Frameworks | Go Libraries. 

For me removed everything from the Global Libraries and I have created a shell script to build and run my application, so idea is only for text editing which is fair enough for me.

I will add some screen shots in a moment.

**Comment by moadqassem** [comment]
I have just created a new project just and tested again, and it works :$ , I really don't know what happened, but I have started a whole new fresh projects and I set the path through the global libs and it worked, I really don't what happened for a sec!!
