### ISSUE TITLE
Autocomplete import path by package name instead of directory structure

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1356]
```go
package main

import "<caret>"

```

At this time i see first part of import path (bufio, github.com ... etc)
I think the better to show packages in autocomplete list instead of directory structure

**Comment by dlsniper** [comment]
I have mixed feelings for this one.

For example you can have a package called "demo" under "github.com/dlsniper/demo" and you can have another one under "de".
Their layout in the GOPATH would be:
- demo -> $GOPATH/src/github.com/dlsniper/demo/file.go
- demo -> $GOPATH/src/de/dem.go

From the go docs, https://golang.org/ref/spec#Import_declarations, the import section should contain a list of import paths, not import packages.

Right now I think it's respecting the go docs, as there's no confusion when you type in which package you want to use. Also the auto-import / import dialog when the same package is in two different paths is informative and also provides the import path not the package name so this offers a sense of consistency imo.

**Comment by linniksa** [comment]
at this time is very vardnes to write import manually, for example i try import globalconf to import this with autocomplete i need write github.com > rakyll > globalconf instead of simple write globalconf and enter to confirm selection in autocomplete

**Comment by dlsniper** [comment]
I see. But you can just write ```globalconf.//autocomplete``` and let the plugin do the rest. In case there are more than one ```globalconf``` packages are present you'll be able to select which one you want to have imported, if not, it will import the correct package.
