### ISSUE TITLE
Cannot load artifact intellij-go.jar, unknown artifact properties ant-postprocessing

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1359]
When opening the project, there are some error: `Cannot load artifact intellij-go.jar`

steps to reproduce

```
git clone -b v1.0.0-alpha0 https://github.com/go-lang-plugin-org/go-lang-idea-plugin.git
ln -s ~/idea-IU* idea-IC
```

open the sdk (error: cannot load artifact), rename SDK to `IDEA sdk`, set the sdk, then build, close idea, reopen the project, still got the same error

When the `ant-postprocessing` property removed from the `.idea/artifacts/intellij_go_jar.xml` it builds successfully
![image](https://cloud.githubusercontent.com/assets/1061610/6321813/182f2cf2-bb39-11e4-808a-aaedafc5c263.png)

**Comment by dlsniper** [comment]
From our [contributing](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/CONTRIBUTING.md#getting-started-with-the-plugin-development) doc: ```Getting started with the plugin development / 6. Setup the ant support plugin ````

**Comment by kokizzu** [comment]
Ah, right, I forgot to re-enable Ant plugin..
