### ISSUE TITLE
[1.0] Assignment check not recognized when inline

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1362]
The following code produces two red squiggles, even though it is valid go https://play.golang.org/p/HB_wIfj-nk:

    x := make(map[string]int)
    x["foo"] = 1

    if _, ok := x["foo"]; !ok {fmt.Println("Missing key 'foo'")}

If it is changed to multiple lines, the squiggles go away:

    x := make(map[string]int)
    x["foo"] = 1

    if _, ok := x["foo"]; !ok {
       fmt.Println("Missing key 'foo'")
    }

**Comment by ignatov** [comment]
Fixed in 2d88e525042e874045f08145593fb4633ccd53b1
