### ISSUE TITLE
Automatically convert the tab to spaces when coding

### ISSUE THREAD

**Issue by KID-WuMeng** [go-lang-plugin-org/go-lang-idea-plugin#1366]
I have cancelled the "Use tab character" in "Settings / Editor / Code Style /" and "Settings / Editor / Code Style / Go Lang /", but it still use tab when I input a tab.

Where I input a tab in the JavaScript, PHP and so on with Idea, the tab will be automatically converted the spaces.

What should I do if I hope the tab to spaces automatically when coding Go Lang ?

**Comment by dlsniper** [comment]
Hi, please descibe a bit better the issur you have. When is it happening? What do you expect instead.
What version of IDEA are you using? What version of the plugin? 
Go uses by default tabs to indent the source code, so fighting for this one is not an option. Thank you.

**Comment by KID-WuMeng** [comment]
@dlsniper thank you, I have solved this problem by used the " Edit / Convert Indents / To Spaces ".
