### ISSUE TITLE
[1.0] Hexadecimal number not has color 

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1372]
```go
i := 0xFFFF;
```

**Comment by dlsniper** [comment]
To be clear, the 0xFFFF part is not colored as a number, yes?

**Comment by linniksa** [comment]
yes:
![123](https://cloud.githubusercontent.com/assets/424343/6366931/d73efd5c-bcdd-11e4-83fd-e74bb53dd035.png)

**Comment by ignatov** [comment]
@dlsniper you need to process hex literals as well.

**Comment by zolotov** [comment]
Fixed by @jakecoffman
