### ISSUE TITLE
[1.0] Package constants not offered to autocomplete

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1375]
See the example below:

```go
time.Parse(time.<cursor>)
```

Possible variants would be:
```
RFC850
RFC1123
RFC1123Z
RFC3339
```

Not sure if this is related to the type inference system or not.

**Comment by ignatov** [comment]
Can't reproduce.
![screenshot 2015-02-25 14 44 57](https://cloud.githubusercontent.com/assets/426890/6370024/e659ded2-bcfc-11e4-9f5b-e41342e4a1d8.png)

**Comment by dlsniper** [comment]
I'll try to replicate this better, strange.

**Comment by ignatov** [comment]
Any news?
