### ISSUE TITLE
how to set GOPATH in 1.0.0.alpha#134?

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1378]
I have set src as my source path as the document said.

When I run a test I got following
```
kmgGob.go:6:2: cannot find package "github.com/bronze1man/kmg/kmgIo" in any of:
	/usr/local/Cellar/go/1.4/libexec/src/github.com/bronze1man/kmg/kmgIo (from $GOROOT)
	($GOPATH not set)
```
![image](https://cloud.githubusercontent.com/assets/1107541/6384328/1166978e-bd96-11e4-8981-d64bf6cee38e.png)

I have serval project with different GOPATH,so set GOPATH global may not be a good idea.

**Comment by dlsniper** [comment]
Go to Settings | Languages and Frameworks | Go and use the project level libraries.

**Comment by bronze1man** [comment]
It works.
1.0.0.alpha#134 has less bugs than the 9.x.x.
Thanks for your great job.
