### ISSUE TITLE
Test Framwwork isn't actually running tests

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1380]
With alpha#134

I create the following test:

    func TestFoo(t *testing.T){
        fmt.Println("Ran the test")
        t.Fatalf("Intentionally failed")
    }

and I run it from the command line:

    dev@devbox:~/projects/go/src/proj/subdir$ /usr/local/go/bin/go test -v proj/subdir --run='^TestFoo$'
    === RUN TestFoo
    Ran the test
    --- FAIL: TestFoo (0.00s)
            my_test.go:118: Intentionally failed
    FAIL
    exit status 1
    FAIL    proj/subdir   0.005s

Buf if I run it from IntelliJ by right clicking and running:

     /usr/local/go/bin/go test -v proj/subdir --run='^TestFoo$'
    Testing started at 9:30 PM ...
    PASS
    ok  	proj/subdir	0.010s

with the Test framwork error I reported in the other issue.

**Comment by zolotov** [comment]
The same as #1379
