### ISSUE TITLE
Autocomplete for unimported internal package

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1381]
The autocomplete for unimported internal package seems doesn't work well, or is there anything else that I should set?

IntelliJ version: 14
Plugin version: latest-git
GOPATH: /home/kyz/Dropbox/go
GOROOT: /usr/lib/go

autocomplete shown when typing `bytes.Buffer`:
![image](https://cloud.githubusercontent.com/assets/1061610/6385864/b1ca52a4-bda2-11e4-8935-7b0240627898.png)

expected output: `bytes.Buffer{}` and automatically importing `bytes` :3

the configurations:
![image](https://cloud.githubusercontent.com/assets/1061610/6385878/d68c45ac-bda2-11e4-9559-44dbbfead9e3.png)

![image](https://cloud.githubusercontent.com/assets/1061610/6385892/fcc46e48-bda2-11e4-8b87-45e9c47d480e.png)
![image](https://cloud.githubusercontent.com/assets/1061610/6385893/01b2b3a6-bda3-11e4-9807-0342dc9038bf.png)

![image](https://cloud.githubusercontent.com/assets/1061610/6386114/8923aac2-bda6-11e4-94dc-602b26125c73.png)

![image](http://i.imgur.com/mdK4SHo.png)

**Comment by kokizzu** [comment]
after adding `/usr/lib/go` on the `Go Libraries` (last screenshot) more autocomplete shown, but not the `Buffer` type:
![image](https://cloud.githubusercontent.com/assets/1061610/6386184/9b7969c2-bda7-11e4-8527-de91ca2bedce.png)

**Comment by dlsniper** [comment]
@kokizzu please don't add the GOROOT to the libraries. The GOROOT is meant to be as an SDK only. As well, please don't change the SDK yourself, the SDK should never contain the GOPATH itself, I don't know why you did that change.

Also, you've added the GOPATH all over the place. This is not what the plugin tells you to do when you install it. It points you to the following document: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project you should add it to the Global Libraries only (or if you need project / module).

Finally, the autocompletion doesn't work as you provided the first screenshot which looks like ```bytes``` is not imported yet in the file and the plugin noticed there are multiple versions of ```bytes``` present so it cannot import it automatically. You should use the Alt+Enter shortcut as told in the screenshot to be presented with the import list and then you'd be able to chose the which versions of ```bytes``` package the file will use to its import list.

**Comment by zolotov** [comment]
@kokizzu indeed we don't complete not imported types for that context, only in places when actually type definition is expected:

![screenshot 2015-02-26 11 27 31](https://cloud.githubusercontent.com/assets/140920/6388443/0a022156-bdab-11e4-9153-a75cc6658ab1.png)

Do you think that it's useful to complete them everywhere?

**Comment by kokizzu** [comment]
ah you're right..

one more thing, how to add exception there's a lot of folders inside my GOPATH, and I don't want it to show..
![image](https://cloud.githubusercontent.com/assets/1061610/6388511/3f38cea2-bdcd-11e4-9d95-e5ac5fd6b7b3.png)

but this one seems not giving the types also.. (`bytes` not yet imported)
![image](https://cloud.githubusercontent.com/assets/1061610/6388515/50c0ac08-bdcd-11e4-811b-1560fe55b1cc.png)

**Comment by zolotov** [comment]
> one more thing, how to add exception there's a lot of folders inside my GOPATH, and I don't want it to show..

There is no way to do it right now, but I can add excluding rules by package. Please file a separate issue about that.

> but this one seems not giving the types also.. (bytes not yet imported)

They are not types but functions :)

**Comment by kokizzu** [comment]
for comparison, when `bytes` imported (manually) 

![image](https://cloud.githubusercontent.com/assets/1061610/6388624/8a841a64-bdce-11e4-8abd-094b8b48a2e7.png)

**Comment by zolotov** [comment]
Yes, I know. As I said that we don't complete only not imported types in these contexts. I'm not sure that it's right decision and it's indeed looks inconsistently. So yet again:

Do you think that it's useful to provide completion for non-imported types in these context?
Or maybe we should disable completion for imported types here as well?

**Comment by kokizzu** [comment]
yes, it would be useful to show also non-function (types) in those context, since assigning to variable not always comes from a function.

```
  x := [[types here]]
// or
 blabla( [[types here]] ) 
```
