### ISSUE TITLE
Feature request: import exclusion/inclusion by directory

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1382]
the case, when there are a lot of libraries in `GOPATH/src`, the autocomplete shows too much unused library:

![image](https://cloud.githubusercontent.com/assets/1061610/6388665/0874c766-bdcf-11e4-91c6-8971aa70b58a.png)

It would be nice to add exception directories, 
or better way `GOPATH` and list of directories to be autocompleted within `GOPATH`

most cases I only need certain <10 libraries (from hundreds that available on GOPATH)..

**Comment by dlsniper** [comment]
One possible candidate for exclusion should be the directory called ```Godeps```. The nature of ```godep``` tool will make it to duplicate things. There's already a ticket to support ```godep``` workspaces at a later time after 1.0.

I'll try and investigate other package managers as well to see if we can eliminate by default directories.

**Comment by zolotov** [comment]
Exclusions added in 460 alpha build
