### ISSUE TITLE
Support Go App Engine project launcher, and possibly project type

### ISSUE THREAD

**Issue by jimbojetlag** [go-lang-plugin-org/go-lang-idea-plugin#1387]
The old plugin used to support a Go App Engine project type, and launcher. Currently, Intellij Idea Ultimate supports these for Java App Engine.

Integrating gae dev server with IDE has advantages like being able to click the error line and going straight to the right line of the right file.

There are downsides like gae dev server interfering with Intellij as it runs its own `go fmt` and changes the files externally.

**Comment by jimbojetlag** [comment]
Seems like you use `gcloud/google-cloud-sdk/platform/google_appengine/goapp` to run appengine dev server.

Since gae 1.9.18, this does not work anymore, leading to:

```
...
ImportError: No module named docker
error while running dev_appserver.py: exit status 1
```

You should use `gcloud/google-cloud-sdk/bin/goapp` instead.

**Comment by zolotov** [comment]
> You should use gcloud/google-cloud-sdk/bin/goapp instead.

According to https://cloud.google.com/appengine/docs/go/gettingstarted/devenvironment I shouldn't

> Since gae 1.9.18, this does not work anymore, leading to:

Why since exactly 1.9.18? Where I can find the information about it?

Actually it works fine for my hello world projects. Could you show how you run goapp from terminal and how you configured GAE run configuration?

**Comment by jimbojetlag** [comment]
> According to https://cloud.google.com/appengine/docs/go/gettingstarted/devenvironment I shouldn't

*Last updated September 22, 2014.*

Just google for 'ImportError: No module named docker' and you'll see this problem everywhere (Google engineering quality seems to have declines recently). You will find most fixes include [changing the path](https://github.com/gae-init/gae-init/issues/318). 

`/path/to/gcloud/google-cloud-sdk/platform/google_appengine/goapp serve .` in terminal gives me exactly the same error as Idea.

`/path/to/gcloud/google-cloud-sdk/bin/goapp serve .` works fine in terminal for me.

**Comment by zolotov** [comment]
I see, thanks

**Comment by zolotov** [comment]
I've tried the bin/goapp on appengine 1.9.18 and got this issue: http://stackoverflow.com/questions/21198584/goapp-serve-unable-to-find-dev-appserver-py/21215399#21215399

As a workaround, they said, I should use goapp "from the top of the SDK" :(

**Comment by jimbojetlag** [comment]
Does bin/goapp work fine for you in terminal? If so,have a look at `gcloud/google-cloud-sdk/completion.bash.inc` maybe you need to set some env variables in IJ.

**Comment by zolotov** [comment]
Nope, the terminal gives the same error. Maybe it's macos-specific. In this case we can use `goapp` for mac and `bin/goapp` for linux. The only question what should we do on windows?

**Comment by jimbojetlag** [comment]
If you have the same error in terminal, probably your installation has a problem. Try `gcloud components update`, Google has recently made many patches for 1.9.18.

I think with a proper installation, bin/goapp should works fine in IJ, and it should be cross platform.

**Comment by zolotov** [comment]
It's not broken installation, it's installation without using gcloud utility. I just followed this instruction: https://cloud.google.com/appengine/downloads#Google_App_Engine_SDK_for_Go, not that https://cloud.google.com/sdk/#Quick_Start. I believe we should support both installations. Any ideas how to handle it in IDE?

**Comment by dlsniper** [comment]
@zolotov in the old 0.9 version I was just setting the env variable ```APPENGINE_DEV_APPSERVER``` to the GAE SDK home and things where then running nicely. I know it's a bit hacky but maybe that's a way to do it? What do you think/

**Comment by zolotov** [comment]
@dlsniper yes, it is solution and indeed it's hacky :) I will do it in this way if we won't think of something better till tomorrow.

**Comment by jimbojetlag** [comment]
@zolotov the gcloud and standalone appengine sdk installation are not consistent.

If you plan to support both, you'll probably end up with detecting the installation type, and take a different approach for each type.

**Comment by zolotov** [comment]
Ok, I try to figure out how to distinguish these installations. I'm going to use standalone version and will be really appreciate if you'll report an issues about gcloud installation. We'll be able to cover all cases with your help :)

**Comment by zolotov** [comment]
Fixed for gcloud installation

**Comment by jimbojetlag** [comment]
As of 0.9.241 it still runs `gcloud/google-cloud-sdk/platform/google_appengine/goapp serve .`. please ignore this if the fix is not included in this build.

**Comment by zolotov** [comment]
It's fixed in 0.0.242. I've update repository, new build will be available soon

**Comment by jimbojetlag** [comment]
Thanks, launchers works fine in 0.9.242. However, the most useful part of this does not work: when there is an error, the error file/line in console is not clickable.

**Comment by zolotov** [comment]
Some of them works. I'm working on it (see #1495). Could you give me more examples for testings?

**Comment by jimbojetlag** [comment]
It looks like go appengine dev server copies the files to a tmp directory. When the errors appear from the tmp dir, they are clickable. But sometimes the errors happen directly from the project dir, which are not clickable.

It is not clear to me under which condition the tmp and the project dir are shown in the console.

**Comment by zolotov** [comment]
Yes, I know that. I made some efforts with links to tmp files and didn't do anything with directly paths. It would be nice if you give me examples of real logs so I'll be able use it in tests.

**Comment by dlsniper** [comment]
@zolotov here are some logs for this, maybe it's useful: http://pastebin.com/mfsxLnjz
You can ```go get https://github.com/gophergala/yps``` to install the app in your GOPATH.
Hope this helps.

**Comment by jimbojetlag** [comment]
Try a project with 2 modules: one an appengine project, and the other just a package somewhere in your GOPATH.

The errors for the appengine module (from tmp dir) are clickable. But errors for the package module are not clickable.

You probably want to make this pattern clickable:
```
/any/path/to/a/gofile.go:linenumber
```
, with the exception of a file copies to the tmp dir being mapped to the actual project file, which is already handled correctly.

**Comment by zolotov** [comment]
> /any/path/to/a/gofile.go:linenumber

This pattern is clickable now: ^[ \t]*/any/path/to/a/gofile.go:linenumber$. And there is the exception for files from tmp-dir.
Anyway this info is unusable for testing, I asked for real logs.

@dlsniper thanks, will try the project too.

**Comment by jimbojetlag** [comment]
0.9.244 uses `gcloud/google-cloud-sdk/platform/google_appengine/goapp` again :( I'm not able to generate some log for testing.

**Comment by dlsniper** [comment]
@jimbojetlag try running the server directly and do some of the stuff you'd do normally in the IDE. That should work ;)

**Comment by zolotov** [comment]
@jimbojetlag sorry, my bad, I need a test for that.

**Comment by jimbojetlag** [comment]
@zolotov You're regex will work correctly. There's nothing special about the log, anything should do the job, including this:

```
*errors.errorString this function is supposed to crash
/0/go/src/github.com/go-errors/errors/crashy/crashy.go:8 (0x41280)
    Crash: return errors.New(Crashed)
/0/go/src/github.com/go-errors/errors/example/main.go:11 (0x2026)
    main: err := crashy.Crash()
```

**Comment by zolotov** [comment]
thanks, good sample.

meanwhile i've uploaded the new nightly build, please try it, running should be fixed.
