### ISSUE TITLE
Can't find Go SDK on OSX 

### ISSUE THREAD

**Issue by lox** [go-lang-plugin-org/go-lang-idea-plugin#1391]
Trying to install the latest public version of the plugin (0.9.15.3) on IDEA Community 14.0.3. Go is installed at `/usr/Cellar/go/1.4`. I select the Add SDK and choose the directory using the keyboard shortcut and then nothing happens. No SDK is added to my list. I see the following error in the logs:

```
> [  58375]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
```

**Comment by lox** [comment]
@lwc also experienced this issue using IntelliJ Ultimate edition.

**Comment by dlsniper** [comment]
Please use the latest release from github releases https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases.
