### ISSUE TITLE
Provide support for Printf placeholders

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1392]
Support for Printf placeholders should be added so that we can count how many placeholders are vs how many parameters are.

**Comment by zolotov** [comment]
Examples:

https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/inspections/PyStringFormatInspection.java

https://github.com/JetBrains/intellij-community/blob/master/plugins/InspectionGadgets/InspectionGadgetsAnalysis/src/com/siyeh/ig/bugs/MalformedFormatStringInspectionBase.java
