### ISSUE TITLE
[1.maybe] Display const value rather than name

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1393]
```go
package main

const demo = "Demo text here"
func main() {
	println(demo) // IDE should display Demo text here not demo by default
}
```

Question: should I use a FoldingBuilder like in the example from https://confluence.jetbrains.com/display/IntelliJIDEA/Folding+Builder to solve this?

**Comment by zolotov** [comment]
> should I use a FoldingBuilder 

Yes, platform has no any other approaches for solving this task yet

**Comment by dlsniper** [comment]
I've closed the PR for this a while ago as this might not be always useful from real life tests.
