### ISSUE TITLE
Fix version number for 1.0.0

### ISSUE THREAD

**Issue by alpe** [go-lang-plugin-org/go-lang-idea-plugin#1395]
`1.0.0.alpha#134` release is shown as `0.9.134` (in Intellij 14.0.3)
This may confuse others who want to upgrade as well.
![screen shot 2015-02-28 at 14 20 32](https://cloud.githubusercontent.com/assets/28003/6426325/16a4d5f6-bf55-11e4-9f1a-39a5ea67eab6.png)
Anyway, thanks for a new release. I'm looking forward to use it.

**Comment by dlsniper** [comment]
The change made by @zolotov looks intentional to me https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/23d41bc41bb38b6904f4aa1529652f40a677156e

I suspect the reasons behind it but I can't tell you for sure why the plugin is named like that.

**Comment by zolotov** [comment]
Yes, it was intentionally. When 1.0.0 will be released its version should be higher of current weekly releases.
