### ISSUE TITLE
Support "Go project" types in small IDEs

### ISSUE THREAD

**Issue by dvshapkin** [go-lang-plugin-org/go-lang-idea-plugin#1398]
plugin version 1.0.0.alpha#164
In the list of types of projects is not a project Go
![image](https://cloud.githubusercontent.com/assets/6525348/6435470/437f0862-c0d1-11e4-8e0b-a11c1ee6eda5.png)

**Comment by dlsniper** [comment]
Thank you for creating a issue, again. 
Please create an empty project and then a go file. You will be prompted to setup the go sdk and then the go libraries.

**Comment by zolotov** [comment]
@dvshapkin I don't see any reasons to create `Go Project` item in `new project`-wizard. What do you expect `Go Project` wizard will do?

**Comment by dvshapkin** [comment]
And what makes a Go Project wizard in IDEA? There it is. 
The absence of the master is surprising, since the user expects to see him. And the user begins to think that the plugin does not work.

**Comment by TheDistractor** [comment]
Additional info: I use Community (all works fine excepting known limitations), however I also have Webstorm 9/10EAP, The create GO SDK [Link] does not work in Webstorm 9/10, the toast notification pops up with hyperlink but you cannot click it. Seems no other way to set correct SDK info in Webstorm 9/10?? - do not seem to be able to do it in Settings->Plugins or Settings->Project etc.

**Comment by zolotov** [comment]
> And what makes a Go Project wizard in IDEA?

Changes module type and selects SDK from predefined application-level SDKs. Small IDEs don't have application-level SDKs and `go` module type.

**Comment by zolotov** [comment]
@TheDistractor go plugin version? That was fixed in #164 only, [release notes](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases/tag/%23164) contain the info about setting SDK in small IDEs.

**Comment by zolotov** [comment]
@dvshapkin 
> The absence of the master is surprising, since the user expects to see him. And the user begins to think that the plugin does not work.

WebStorm also doesn't contain JavaScript Project but it doesn't mean that JavaScript plugin doesn't work.
Well, I'm still not sure that it's needed so I won't implement it. But feel free to contribute this.

**Comment by TheDistractor** [comment]
@zolotov hmm, just rechecked, seems my 164 did not apply in WS, still 134!, Community all fine though. Will retry update in WS again.

**Comment by zolotov** [comment]
@TheDistractor 1.0.0 branch still doesn't support autoupdate so you have to install new releases manually

**Comment by TheDistractor** [comment]
@zolotov my bad, seems I may not have correctly installed 164 in WS, only in IntelliJ. Just reinstalled 164 in WS 9.0.3 now, SDK setting works fine, however I got a:
> Unknown Module Type
>         Cannot determine module type ("GO_MODULE") for the following module:"test1"
>         The module will be treated as a Unknown module.
The SAME project opens "without" this message in IntelliJ. Both compile and run file.

**Comment by dlsniper** [comment]
@theDistractor that happens because you've opened the same project in IDEA and WebStorm. I think you can safely ignore it as well

**Comment by TheDistractor** [comment]
@dlsniper 
> I think you can safely ignore it as well
Yep - seems no adverse affect, and switched between some pretty large multi-module projects in last 20mins.

BIG high five for the plugin team ! 
over and out.

**Comment by dlsniper** [comment]
As a reference, if someone wants to implement this, I think [this](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/ro/redeul/google/go/template/GoApplicationGenerator.java) and the commits in master branch can be used as a reference (unless @zolotov says it's not good enough).

**Comment by niwaywood** [comment]
I experienced the same thing. I installed 164 and I thought the plugin wasnt working because `Go Project` wasnt in the `new project` wizard. If I didnt find this issue I would have given up thinking the plugin is broken.

It is especially confusing because the setup instructions here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project says this:
- create a new project by going to `Create New Project | Go` and follow the setup steps

In my opinion a `Go Project` item in the `new project` wizard would be good, even it all it does is create a dummy file with Hello World in it

**Comment by Codenator81** [comment]
Keep in mind WebStorm good for AngularJs and html5 css work on. Golang very often used with Angular so WebStorm is good IDE for that. Please support it more there. On idea Community many thing builded for Java and on PhpStorm for PHP. So I think WebStorm is best platform for Go.

**Comment by thawkins** [comment]
we are a PHP and golang shop, we have licensed versions of PHPStorm, all setup with various tools we use, we would rather not have to have multiple IDE's. A typical application would have JS/HTML/CSS clientside, PHP based presentation layer and a golang REST backend. PHPStorm hits all levels with the plugin in a single IDE.

**Comment by zolotov** [comment]
@thawkins and what is exactly stopping you from using golang plugin in PhpStorm?

**Comment by dlsniper** [comment]
@zolotov seems that people are confused by the lack of Go as a project type. I don't understand this last comment @thawkins did especially since he did this comment earlier https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1763#issuecomment-132830824 which states that they know how to use PHPStorm and Go. I'll address the documentation issue today as it slipped my mind but I do understand why people are confused by the lack of a project type specific for Go in small IDEs. I'll try and find some time to send a PR for that.

**Comment by ignatov** [comment]
Duplicates #1763
