### ISSUE TITLE
Case indentation always wrong

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1399]
Sample snippet
```
case bla:
    bla bla // press enter here
// cursor not indented, is this behavior intended?
```
![image](https://cloud.githubusercontent.com/assets/1061610/6437948/09223a10-c0f7-11e4-898e-5b50c8ac5bf7.png)

Desired behavior:
```
case bla: // press enter here
    // cursor indented

case bla:
    bla bla // press enter here
    // cursor indented

case bla:
    bla bla
    bla bla
    case bla: // press enter here
    // cursor indented, and previous line de-indented
```

**Comment by dlsniper** [comment]
Please watch #1363

**Comment by zolotov** [comment]
@dlsniper why did you close this? #1363 doesn't cover this case yet. Also such issues could be useful for creating tests.

**Comment by dlsniper** [comment]
Sorry, I've misclicked without realizing
