### ISSUE TITLE
[1.0]tip error when struct has same method name

### ISSUE THREAD

**Issue by brenthub** [go-lang-plugin-org/go-lang-idea-plugin#1401]
![20150302185646](https://cloud.githubusercontent.com/assets/10822807/6439495/2cf071d4-c10e-11e4-906d-17f765724471.png)

the last method will cover the front method when struct has same method name

**Comment by dlsniper** [comment]
Hi, can you please send a small reproducible, copy-pasteable sample that reproduces the error? Thank you

**Comment by brenthub** [comment]
import (
    "github.com/codegangsta/martini"
)

func Start(){

    var m *martini.ClassicMartini = martini.Classic()

    m.Get("/",func() string{ //this code can run
        return "Hello,world!"
    })

    m.RunOnAddr(":3001")
}

**Comment by brenthub** [comment]
the same with [too many arguments in call to... #1369]
already fixed，thank you!
