### ISSUE TITLE
[1.0] Builtin function(s) not available for autocomplete

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1403]
In the following sample, the ```println``` function is not offered to auto-completion (see the attached screnshot).

```go
package main

func main() {
	println("deo")
	printl<caret>
}
```

![snapshot13](https://cloud.githubusercontent.com/assets/607868/6442720/25662768-c0f2-11e4-801f-006f1668d2a8.png)

Thank you.

**Comment by zolotov** [comment]
@ignatov why? `com/goide/psi/impl/GoReference.java:121`
