### ISSUE TITLE
Invalid hint on HTML sources when Go package has the same name as JavaScript function

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1408]
problem: Go hint shown on HTML instead of JavaScript's

how to reproduce:
1. create a go package named `A`
2. create a JavaScript function named `A` 
3. call `A` function on JavaScript, the hint shown as Go instead of JavaScript

hover on `A` in the JavaScript part of HTML source file, then hold `Ctrl`
![image](https://cloud.githubusercontent.com/assets/1061610/6455576/70eaa79a-c188-11e4-8859-7b5c07232a76.png)

hover on `A`, then hold `Ctrl` and click on `A`
![image](https://cloud.githubusercontent.com/assets/1061610/6455560/3ed7b234-c188-11e4-9d62-f6e8312b574d.png)
this should not be happened, since it's a JavaScript function call, not a Go package..

for comparison for JavaScript function that not collide with Go package's name (`IMG`):
![image](https://cloud.githubusercontent.com/assets/1061610/6455584/857b349a-c188-11e4-8f60-ac2ee9b083dd.png)
when holding `Ctrl` and click on `IMG` it goes to correct JavaScript source.

Idea version: Ultimate 14.0.3
Plugin version: latest git

**Comment by zolotov** [comment]
I didn't undestand anything. Could you give a whole code sample with function definitions and with imports that you're using? What are you expectations about behaviour of IDE?
Also, if you're building plugin from git, specify revision number, tomorrow it might not be `latest git`

**Comment by kokizzu** [comment]
1. create a `A.go` in a folder named `A` (`A` package):
```
package A
func Anything() {
}
```
2. create a javascript file, with any name, for example:`global.js`, but has a function named `A`
```
function A(foo,bar) {
}
```
3. create a html file, with any name, and call `A()` function within javascript
```
<script>
   A() // gives incorrect hint as seen on the screenshot above
</script>
```

**Comment by zolotov** [comment]
ok, thanks, I'll check it

**Comment by dlsniper** [comment]
A bit of an off-topic topic and possibly not even related with the issue, can you please send a screenshot of your Go SDK ```File | Settings | SDK ````.  I suspect that things are not setup properly there as I don't recall having a function A() in the Go SDK.

**Comment by kokizzu** [comment]
Project Structure > Platform Settings > SDK?


![image](https://cloud.githubusercontent.com/assets/1061610/6460043/79d8bab6-c1c6-11e4-932a-3e1777fc0bfd.png)

**Comment by kokizzu** [comment]
or this one?

Settings > Go Libraries?
![image](https://cloud.githubusercontent.com/assets/1061610/6460068/b64b2f60-c1c6-11e4-8213-651ef432511c.png)
(2 listbox below that screenshot are empty)

**Comment by dlsniper** [comment]
Sorry for my confusion, I wasn't near my computer when I've wrote it. However, both are useful. As I suspected, you have a malformed setup. Please make the following changes:
- in the Go SDK from ```File|Project structure|SDKs|Go 1.4.1``` leave only the ```/usr/lib/go``` paths (remove anything extra from ```Classpath``` and ```Sourcepath```)
- in ```File|Settings|Languages & Frameworks|Go Libraries``` leave only ```/home/kyz/Dropbox/go```

You shouldn't mix the two together (Go SDK root and Go libraries paths) as they might / will have unexpected effects.

**Comment by kokizzu** [comment]
error shown on the editor `Cannot resolve directory somethingThatInMyGOPATH`

**Comment by dlsniper** [comment]
@kokizzu lets take this on [Gitter](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin) as it's off-topic but it looks like there's a problem with your setup or with the plugin. And if it's with the plugin, I'd rather not fix it like this, with workarounds but with something that all users can benefit from. Thanks.

**Comment by zolotov** [comment]
Cannot recreate. I'll reopen it if you give me working steps for reproducing.

**Comment by kokizzu** [comment]
when you tried, it gives you correct autocomplete?

**Comment by zolotov** [comment]
Yes. It's just impossible that JS symbols is appeared in completion/resolving in go. Unless you're using some other third-party plugin that does it.

**Comment by kokizzu** [comment]
no, it's the opposite, Go's symbols appeared on JS's completion..

**Comment by zolotov** [comment]
The same. You can attach the project when I can recreate it.
