### ISSUE TITLE
Better recover until switch statement is needed

### ISSUE THREAD

**Issue by kostonstyle** [go-lang-plugin-org/go-lang-idea-plugin#1409]
The ide complain missing return value, even though I return it.
![capture](https://cloud.githubusercontent.com/assets/701611/6460254/e5e7b6c0-c195-11e4-98cd-8e62ef386aee.PNG)
As you can see on the picture, three return statement.

Thanks

**Comment by dlsniper** [comment]
I've tried to reproduce this with the following code and I couldn't:

```go
package main

func demo(a int) int {
	switch a {
	case 1:
		return 2
	case 2:
		return 1
	default:
		return 3
	}
}

func main() {
	println("Hello, playground")
}
```

Can you please share a code that reproduces the issue?
Also, please share a bit more details, like which version of the plugin are you using (and if you compile it, what's the commit hash).

Thank you.

**Comment by kostonstyle** [comment]
Here we go
```go
func User(createBase base.AuthFunc) base.Ajaxer {

    log.Println("Restful user request.")
    authCtrl := createBase("controller/account/user")

    switch authCtrl.Req.Method {
        "PUT":
            return &edit{AuthCtrl: authCtrl}
        "DELETE":
            return &delete{AuthCtrl: authCtrl}
        default:
            return &read{AuthCtrl: authCtrl}
    }
}
```
![1](https://cloud.githubusercontent.com/assets/701611/6465081/00e386e2-c1bf-11e4-924d-9216f41ab517.png)
![2](https://cloud.githubusercontent.com/assets/701611/6465082/028b7f68-c1bf-11e4-85d8-6acace198040.PNG)

**Comment by kostonstyle** [comment]
I've forgot the case statement.

**Comment by dlsniper** [comment]
@kostonstyle I've just noticed, does your code compile? You are missing the ```case``` keywords from the cases.

**Comment by zolotov** [comment]
@ignatov better recover until switch statement is needed
