### ISSUE TITLE
[1.0] don't add GO_PATH in non-go project

### ISSUE THREAD

**Issue by natrim** [go-lang-plugin-org/go-lang-idea-plugin#1411]
Hello i use this plugin v1.0#164 aplha with PhpStorm 
and the plugins adds GO_PATH external library even for non-go projects

**Comment by dlsniper** [comment]
Hi @natrim. Can you please detail a bit more what's happening. Unfortunately I don't understand from the description what's going wrong with the plugin. Thank you.

**Comment by zolotov** [comment]
There is no difference between go-project and non-go projects in small IDEs.
Why does the library bother you?

**Comment by natrim** [comment]
It'z just a something i find ugly, to have go libs in PHP projects .)
it'z something i can live with though, it'z just that it would be nice to not be it like this

**Comment by zolotov** [comment]
Since now any project without go-sdk are treated as non-go project

**Comment by natrim** [comment]
![fluttershy_yay100](https://cloud.githubusercontent.com/assets/488136/6551414/71625038-c638-11e4-8cbc-8a5e827a8639.png)
yay!
