### ISSUE TITLE
Incorrect autocomplete insertion

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#1412]
Example:
![image](https://cloud.githubusercontent.com/assets/1061610/6478037/3e0fac6e-c25d-11e4-98a1-938b50b64cf8.png)
after pressing enter (or clicking the first one):
![image](https://cloud.githubusercontent.com/assets/1061610/6478040/48f5b10a-c25d-11e4-845c-b77bddd95e27.png)
it should be: `W.Context` instead of `W.W.Context`

IDEA version: 14.0.3
plugin version: f0a0b123bcbf7e2326cd48e5c404f8345c105c1b (today's latest git)

**Comment by dlsniper** [comment]
I'm closing this as we currently don't have a type inference system (thay I know of) and this doesn't bring anything new to it (also copy-pasting code from screenshots it's known to be a bit tricky)

**Comment by zolotov** [comment]
It's not about type inference system, it's about calculating prefix for completion
