### ISSUE TITLE
Should the Go plugin be used when compiling IDEA from IDEA?

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1416]
Hi,

I'm having the following issue:
- I'm using java 8 as default on my system (linux)
- I have java 6 installed for compiling and running IDEA from IDEA(139.1117)
- I have the go plugin which I'm compiling with java 8 installed in the IDE

Compiling IDEA using ant works fine from command line. However, I've noticed that if I try and compile IDEA from IDEA, I get the following error:

```
Error:Internal error: (java.lang.UnsupportedClassVersionError) com/goide/jps/model/JpsGoModelSerializerExtension : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/goide/jps/model/JpsGoModelSerializerExtension : Unsupported major.minor version 52.0
```

I understand that I get the error because of the version mismatch from java, but the question is: is it ok for the go plugin to be triggered when I try to build a Java project such as IDEA?

Thank you

**Comment by zolotov** [comment]
Yup, compiling task uses all defined serializer extensions.

**Comment by dlsniper** [comment]
Got it, thanks!
