### ISSUE TITLE
go-lang-idea-plugin takes over Run context configuration

### ISSUE THREAD

**Issue by Mingan** [go-lang-plugin-org/go-lang-idea-plugin#1418]
After I installed the plugin the function `Run context configuration` in Idea no longer works correctly. I can run go program just fine but when I switch to a completely separate Ruby project and try to use the `Run context configuration` option on Rspec folder it fails with: `Error running All in 'module-name': Sdk is not set or Sdk home path is empty for module`.

It's not a Go project, uninstalling the plugin fixes the problem. Rspec configuration can be run just fine if manually configured. Only situation is when I try to use the context option.

Idea: 14.0.3
go-lang-plugin-org: Go.164
go: 1.4.2

**Comment by zolotov** [comment]
Fixed, thanks for report

**Comment by Mingan** [comment]
That was fast! Thanks!

**Comment by proudlily** [comment]
ｉ　see the Go.164.zip,whether put it in idea plugins?and then it will be ok?

**Comment by zolotov** [comment]
@proudlily Settings | Plugins | Install plugin form disk

**Comment by proudlily** [comment]
whether i choose intellij-go.jar to idea install ?i have tried,but it said Plugin Go is incompatible with current installation.beside my idea is 14.0.1 .

**Comment by zolotov** [comment]
@proudlily from release's description

```
You need to install the zip file, do not extract its contents. For more information, check the README
```

```
Plugin can be installed on IntelliJ platform 139.1111 or greater. It corresponds to IntelliJ IDEA 14.0.3, WebStorm 9.0.3, PhpStorm 8.0.3 and future PyCharm 4.0.5.
```
