### ISSUE TITLE
Find by symbol name doesn't work when prefixing symbol with receiver name

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1428]
In the following example, searching for ```Method``` works but searching for ```a.Method``` doesn't.

```go
package main

type Demo struct {
	field int
}

type ctx int

func (a *Demo) Method(p *ctx) {
}
```

**Comment by ignatov** [comment]
Are you talking about `go to symbol` action?

**Comment by dlsniper** [comment]
I'm thinking of ``` Navigate | Symbol ``` menu action
