### ISSUE TITLE
Cannot create new Go file with dashes in the name

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1429]
*Steps to reproduce:*
* Right click in Project view pane and select New > Go File
* Enter name with dashes, e.g. "test-test" and click OK
* Observe error message ```'test-test' is not a valid Go file name```

*Expected result:*
* File with dashes in its name is created

*Actual result:*
* Error message is shown and OK button is disabled

I can create new Go file with underscores and then rename it ti use dashes ok.

IDEA: 141.104.1
Plugin: 0.9.176

**Comment by zolotov** [comment]
@ignatov do you remember why you made validator?

**Comment by ignatov** [comment]
Not really.

Sergey Ignatov
