### ISSUE TITLE
Go SDK setting doesn't recognizes OS X Go installations

### ISSUE THREAD

**Issue by lewgun** [go-lang-plugin-org/go-lang-idea-plugin#1432]
os: os x 10.10
go sdk: go version devel +1c86edd196bd Fri Jan 03 10:41:56 2014 +1100 darwin/amd64
intellij idea: Intellij IDEA Community Edition: 14.0.3
plugin: 164 or 176
problem: After installing go-lang-idea-plugin it is not possible to select the Go SDK using the Project Structure setting. When clicking on New ... then select the  Go SDK location by me but after clicking okay, nothing is selected

plugin: 0.9.15.3 is OK

**Comment by dlsniper** [comment]
Can you please paste what you have in the "src/runtime/zversion.go"? Thank you

**Comment by zolotov** [comment]
@lewgun are you trying to use go sources as an SDK without building them? The plugin expects that go already built and zversion.go file already created (see https://github.com/golang/go/blob/master/src/cmd/dist/ for details)

**Comment by lewgun** [comment]
@zolotov, i had builded it, but there is no zversion.go, maybe it's too old, i will update and build it again,

**Comment by lewgun** [comment]
@dlsniper @zolotov with go 1.4.2 that's work thx
