### ISSUE TITLE
Again: unresolved reference to methods of external packages and GOPATH as external library

### ISSUE THREAD

**Issue by kalopsia** [go-lang-plugin-org/go-lang-idea-plugin#1435]
I don't understand what happens, but after updating to the latest version of plugin I faced with the same problems like in previous versions:

Here we see that methods of custom types don't resolve
![screenshot from 2015-03-14 11 36 15](https://cloud.githubusercontent.com/assets/6209197/6650954/85dc8754-ca3e-11e4-9383-0884af705f0f.png)

Every time I add new project, IDEA automatically add GOPATH directory as a module and then indexing all of the huge staff inside.
![screenshot from 2015-03-14 11 33 24](https://cloud.githubusercontent.com/assets/6209197/6650955/87d7cca8-ca3e-11e4-8ed0-8570d2ed96bc.png)

**Comment by dlsniper** [comment]
What do you have in ```Settings | Languages & Frameworks | Go Libraries ```?

**Comment by kalopsia** [comment]
![screenshot from 2015-03-14 11 50 27](https://cloud.githubusercontent.com/assets/6209197/6650993/5fe643bc-ca40-11e4-9d13-c4eeb8b446b4.png)

**Comment by dlsniper** [comment]
So the plugin detects the GOPATH setting in your environment and adds it automatically to the libraries section in order to mimic the environment you are on.
If you don't want it added to your project, I guess you should remove it from the ```Global Libraries``` section and add it per project in the ```Project Libraries``` section.
Does this work?

Also, what's the output of ```go env``` from command line and what happens if you want to the app with ```go run```. I believe you are trying to make an AppEngine app, no? If so, you'd need to manually define a new Go SDK for AppEngine and assign it to the project (I can guide you as well).

@zolotov it's the same problem I've noticed earlier, maybe we should not force add things to the plugin but rather send a message to the users and prompt them to configure it?

**Comment by zolotov** [comment]
> @zolotov it's the same problem 

What's the problem? I didn't get it.

@kalopsia please provide as small as possible code samples (in text) that will allow us to recreate the problem, we can't guess resolving problems basing on screenshot, it's more like divination

**Comment by kalopsia** [comment]
just a mininute

**Comment by kalopsia** [comment]
> If you don't want it added to your project, I guess you should remove it from the Global Libraries section and add it per project in the Project Libraries section.

@dlsniper What the reason to add it into each project? As all we know IDEA like to indexing indexing and indexing everything and everytime we start|restart project.

I tried to remove it from settings, but the "-" (delete button) is disabled:
![screenshot from 2015-03-14 13 10 08](https://cloud.githubusercontent.com/assets/6209197/6651272/faf2e72e-ca4b-11e4-8e53-8ea003f3c5b2.png)

`go env`:
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/timur/cloud/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

`go run` work correctly, program build successfully.

**Comment by kalopsia** [comment]
I've tried to reinstall IDEA, deleting any preference from home directory but it doesn't work)

**Comment by zolotov** [comment]
> What the reason to add it into each project? 
In order to resolve symbols to sources from GOPATH and provide completion from there, it's not discussable. 

> As all we know IDEA like to indexing indexing and indexing everything and everytime we start|restart project.

No, it's not. If you're experiencing endless indexing or full reindexing on each project opening it means that something wrong with it, tell me the libraries that you have in GOPATH and I'll try to recreate the problem. Also logs would be useful (Help | Show log)

> I tried to remove it from settings, but the "-" (delete button) is disabled

It means that this path is defined in your environment, not in IDEA.

> I've tried to reinstall IDEA, deleting any preference from home directory but it doesn't work)

It will be surprising if something could change after reinstall.

**Comment by zolotov** [comment]
I still don't see the problem that you're trying to report. I see unresolved symbols problem but you didn't provide anything to reproduce it. About external library I didn't get the problem at all.

**Comment by kalopsia** [comment]
> I still don't see the problem that you're trying to report. I see unresolved symbols problem but you didn't provide anything to reproduce it. About external library I didn't get the problem at all.

I found out the problem. The problem was in I every time delete GOPATH from `External Libraries` in `Project structure...` dialog. So I do it because in previous version everything works without adding GOPATH as external library and indexing of GOPATH hanged IDEA (as you can see in the screen below here is huge `node_modules` folder).

![screenshot from 2015-03-14 13 41 58](https://cloud.githubusercontent.com/assets/6209197/6651385/102f4ca4-ca51-11e4-851a-312c189254c6.png)

Thanks for help!) Now problems almost solved, but the new one: how to exclude `node_modules` from indexing (this folder exists in the parent directory/out of the project so I can't mark it as `excluded`)

**Comment by kalopsia** [comment]
Why IDEA create `[project-name].iml` file? Can I get rid of it?

**Comment by zolotov** [comment]
>  The problem was in I every time delete GOPATH from External Libraries in Project structure... dialog. So I do it because in previous version everything works without adding GOPATH as external library and indexing of GOPATH hanged IDEA (as you can see in the screen below here is huge node_modules folder).

It doesn't matter why did you remove library, it's just weird decision to remove something that IDE prepared for you.

> indexing of GOPATH hanged IDEA (as you can see in the screen below here is huge node_modules folder).

It doesn't matter how big folder is, as I said before if IDEA hangs then it's bug and it'd be nice if you provide information about content of gopath/node_modules to reproduce it.

> Now problems almost solved, but the new one: how to exclude node_modules from indexing (this folder exists in the parent directory/out of the project so I can't mark it as excluded)

I didn't get what exactly was solved and I don't know what're you going to solve by removing node_modules from library. Just wondering why did you add node_modules into your GOPATH in the first place?

> Why IDEA create [project-name].iml file? Can I get rid of it?

No, it's module configuration file, it contains information about sdk, module type, attached libraries, source/resource roots and so on.

**Comment by kalopsia** [comment]
@zolotov Слушай, ты русский и это видно. Почему `node_modules` внутри проекта и внутри `GOPATH`? Посмотри https://github.com/google/web-starter-kit, `node_modules` нужен для `gulp`a, у меня такая же структура как WSK, только внутри папки `app` есть go файлы и папка `app` как рут проекта. Помоему логично все это добро держать внутри одного пректа и не плодить кучу папок в разных местах. Если ты пользовался gulp, то знаешь, что для стандартных задач (ES6->ES5, SASS, CSS minify, JS uglify etc) ему нужны зависимости на целых 360мб (которые находятся в `node_modules`), поэтому как ты сам понимаешь ждать индексации такого количества файлов для меня реально "hang".

Знаешь я не особо разбираюсь во внутренностях и тонкостях работы JetBrains, ты пойми не все люди пишут плагины для Jetbrains и не все знают java и мне нужно от него только автозаполнение и подсветка (если Атом от гитхаба когданибудь достигнет нормального автозаполнения я наверняка перейду на него). Могу ли я все таки избавиться от файла `[project-name].iml` или в новых версиях плагина этот файл необходим? (почему мне это нужно - итак файлов хватает, еще один ни к чему))

> It doesn't matter why did you remove library, it's just weird decision to remove something that IDE prepared for you.

Для меня weird что раньше и без этого работало, поэтому посчитал за баг добавление GOPATH как внешней библиотеки. Но сейчас это выглядит логично.

**Comment by zolotov** [comment]
@kalopsia моя национальность не повод для фамильярности. Тем не менее, я и так знаю для чего нужен node_modules, мой вопрос был в том, почему директория попала в $GOPATH/src, в чём задумка? На web-starter-kit посмотрел, какое отношение это имеет к go не понял.
В любом случае node_modules индексируется не go-плагином, а JavaScript плагином, если очень волнует скорость индексациий, то советую снять CPU snapshot и завести issue на http://youtrack.jetbrains.com со списком node-зависимостей, которые вы используете.

> ты пойми не все люди пишут плагины для Jetbrains и не все знают java 

К чему был этот пассаж я не понял, извините.

>  мне нужно от него только автозаполнение и подсветка (если Атом от гитхаба когданибудь достигнет нормального автозаполнения я наверняка перейду на него).

Это задачи текстового редактора, думаю вам стоит внимательней взглянуть на существующие плагины для vim/emacs/sublime. С другой стороны, в зависимости от того, что вы называете «нормальным» автодополнением, оно может быть не реализуемо без вот этих долгих индексаций и анализа кода.

> . Могу ли я все таки избавиться от файла [project-name].iml или в новых версиях плагина этот файл необходим?

[module-name].iml — платформенный файл и никак не регулируется нашим плагином. Избавиться от него нельзя в принципе, но маленькие IDE, типа WebStorm, умеют их складировать в .idea/. Я не знаю способов, как сделать подобное через UI, но скорее всего можно перенести *.iml в .idea/ руками и поправить файл `.idea/modules.xml`, чтобы указывал на правильное место.

> Для меня weird что раньше и без этого работало, поэтому посчитал за баг добавление GOPATH как внешней библиотеки. Но сейчас это выглядит логично.

Понятно. Если под раньше подразумеваются версии, которые лежат на http://plugins.jetbrains.com, то действительно они версии не имеют почти ничего общего с теми, что лежат в releases. И я не очень хорошо знаю, как оно работало.

**Comment by kalopsia** [comment]
> @kalopsia моя национальность не повод для **фамильярности**.

Прикольное слово) Ок не будем разводить неясные диалоги, я тебя услышал, благодарю за помощь и ответы.
