### ISSUE TITLE
Add SDK fails with internal error and no details

### ISSUE THREAD

**Issue by DonBranson** [go-lang-plugin-org/go-lang-idea-plugin#1439]
OS: Ubuntu 14.10
JDK: java version "1.7.0_71"
Intellij: 14.0.3

I cloned the repo into $HOME/apps/go, did `git checkout go1.4.2`, and ran all.bash. The hello world program runs correctly. My .profile includes:

export GOROOT=$HOME/apps/go
export GOPATH=$HOME/projects/go
export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"

This step:

* Add a new Google Go SDK by clicking the plus sign an choosing the appropriate SDK type.

Fails with "IDE internal error occurred" when selecting the directory $HOME/apps/go The error offer details by clicking on the error popup, but shows no details when clicked.

**Comment by DonBranson** [comment]
My thought is that I may have missed something on the install which leads to this failure. As far as bugs are concerned, though, the popup should show the details offered, and that would probably show me what I need to fix.

**Comment by DonBranson** [comment]
More info. This stack trace is dumped where I ran idea.sh:

[  37749]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null
	at com.intellij.openapi.projectRoots.impl.ProjectRootContainerImpl.addRoot(ProjectRootContainerImpl.java)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.addRoot(ProjectJdkImpl.java:368)
	at ro.redeul.google.go.config.sdk.GoSdkType$2.run(GoSdkType.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at ro.redeul.google.go.config.sdk.GoSdkType.setupSdkPaths(GoSdkType.java:173)
	at com.intellij.openapi.projectRoots.SdkType.setupSdkPaths(SdkType.java:85)
...

**Comment by DonBranson** [comment]
The fix to the underlying problem is to clone and build the plugin from github, because the released version does not support go 1.4. Will there be a release cut soon that supports that?

I'd still like some info in the details error popup, though, to help figure out these issues.

**Comment by eddgrant** [comment]
Exactly the same issue here with the following:

OS: Ubuntu 14.04
JDK: java version "1.7.0_67"
Intellij: 14.0.3

**Comment by dlsniper** [comment]
Please use the search function of github, there's at least a half dozen issue with this error. In all of them you'll be sent to download the latest version of the plugin from the releases section https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases. It's not published yet because we are not there yet in terms of quality. For more info, read the existing closed issue. Thank you

**Comment by DonBranson** [comment]
I searched on this issue and found nothing. Because why? Because THE ERROR BOX DOES NOT SHOW THE ERROR! Fix that.

**Comment by DonBranson** [comment]
@dlsniper The error is not the bug - the lack of a searchable error in the error display is the bug.

**Comment by dlsniper** [comment]
Before you go all caps lock: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues?q=is%3Aissue+Argument+for+%40NotNull+parameter+%27virtualFile%27+of+

Also, all the errors in IDEA have a stack trace, like the one above, selecting part of it and searching for it. The fact that you've pasted it here tells me you've seen it :)

IntelliJ Platform doesn't integrate with Github in a manner to provide such a functionality. If you'd like to see it implemented either in the error reporter provided by the IDEA for all the plugins or in this plugin specifically, you are more than welcome to contribute.

**Comment by DonBranson** [comment]
:) Sorry about the caps lock. https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues?q=is%3Aissue+Argument+for+%40NotNull+parameter+%27virtualFile%27+of+ is not related to the bug I'm reporting. Thanks, though.

**Comment by dlsniper** [comment]
That's the way how IntelliJ platform reports errors that we, the plugin authors, don't catch. It's how it works, you didn't provided the plugin version nor a screenshot or anything to help seeing the issue you are describing. After that, there's the stack trace from the exception saying "Argument @NotNull".. which, upon a search, reveals a dozen matches of closed issues.

Also, the error that IDEA presents in that pop-up is for uncaught exceptions... which means that someone missed a condition somewhere and things went unexpected... Providing info for users to help them figure out how to work around unexpected exceptions doesn't make any sense
