### ISSUE TITLE
Cannot even install properly...

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1441]
The one from the current repo in intellij won't use my go installation? It just won't?

The one here that I can download just says internal error when trying to create a new project lol.

I tried the latest dev build and my intellij wouldn't even start...

Mac latest stable osx yosmite along with the latest stable intellij

**Comment by aubble** [comment]
fixed it, simply changed my JRE version in the info.plist file of intellij to use 1.8 instead of 1.6 and its blazing awesome! 

I don't know how to compile for 1.6 yet.

**Comment by zolotov** [comment]
The content of internal error would be useful

**Comment by dlsniper** [comment]
@aubble which branch did you compile? Also, have you tried just downloading the latest release from the Releases section of the repository? That one is compiled against Java 1.6.

**Comment by dlsniper** [comment]
I'll close this one as the user refers to 0.9.15.3 and there's a dozen of threads on how to deal with it. Also the compilation problem with Java is properly documented in the readmes
