### ISSUE TITLE
Cross file completion when packages are *_test

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1442]
Hi,

I've came across this bug in the following situation:

github.com/dlsniper/project/pack1/pack1.go
```go
package pack1_test

type Demo struct {
	Field int
}
```

github.com/dlsniper/project/pack2/pack2_test.go
```go
package pack2_test

import "github.com/dlsniper/project/pack1"

func Demo() bool {
        _ = pack1_test.Demo{}
	return true
}
```

In this example, ```pack1_test```from ```pack1_test.Demo``` is flagged as unresolved reference.
The go code compiles however.

**Comment by dlsniper** [comment]
I've forgot to add that if I change the code to the thing below, it works:

github.com/dlsniper/project/pack1/pack1.go
```go
package pack1

type Demo struct {
    Field int
}
```

github.com/dlsniper/project/pack2/pack2_test.go
```go
package pack2_test

import "github.com/dlsniper/project/pack1"

func Demo() bool {
        _ = pack1.Demo{}
    return true
}
```

```pack1.Demo``` is resolved properly now.

**Comment by dlsniper** [comment]
And another two things:
- I'm not sure this applies only to *_test packages / files
- plugin version is: a28598998e1cc20491cbf675dfebc3aa09d42463

**Comment by ignatov** [comment]
@zolotov Please see [GoUtil#getAllPackagesInDirectory](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/util/GoUtil.java#L182-182).

**Comment by zolotov** [comment]
Reverted #1182, it was right :)
