### ISSUE TITLE
autocomplete for field json tag is inserting more that it should

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1443]
I'm using: a28598998e1cc20491cbf675dfebc3aa09d42463 on IDEA 141.104.1

If i have the following example

```go
var demo struct{
	Field1 string `j<caret>`
}
```
and I receive the `json:""` then the result is:
```go
var demo struct{
	Field1 string ``json:""``
}
```

I haven't seen when the commit for this happened so I'm not sure if it's related to the plugin or not but I don't recall seeing this until now happening.

**Comment by zolotov** [comment]
duplicate #1440

**Comment by zolotov** [comment]
And it's not completion, it's live template

**Comment by dlsniper** [comment]
it was bound to happen that I open a duplicate ticket :D Thanks for update
