### ISSUE TITLE
Add using JDK 1.6 to build plugin in the build read me for OS X

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1445]
It currently has outdated instructions. First, it asks you for idea and then the JDK, and you have to make sure the JDK is 1.6, least on mac because it runs on only JDK 1.6 and using 1.8 to compile leads to a startup crash. Perhaps I've overlooked but I didn't see this information anywhere.

You can change to 1.8, its like 4 times faster but it has bugs, eats battery and looks ugly.

**Comment by dlsniper** [comment]
Hi, the mention for JDK 6 is already in the docs: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/v1.0.0-alpha0/CONTRIBUTING.md#important-macos-x-users-note
