### ISSUE TITLE
On Windows, the Go SDK directory is not properly detected

### ISSUE THREAD

**Issue by jbuberel** [go-lang-plugin-org/go-lang-idea-plugin#1447]
- I downloaded and installed IntelliJ Community Edition, v14.0.3 on Windows8.1.
- Following the online instrucitons, opend Settings -> Plugins -> Browse Repositories
- I then filtered the list for 'golang' and proceeded to install v0.9.15.3
- I then restarted IntelliJ to activate the feature.
- Once restarted, I started a new project. I selected Go as the project type
- Clicked "next" on the "Additional Libraries" dialog.
- Left default selections on the next dialog as "Create source directory" with name "src"
- Clicked next and was prompted to select the Go SDK directory.
- I opened the directory browser, and selected C:\go\ which holds an install of v1.4.2 of Go for Win/64
- Clicked "OK" in the directory chooser dialog, but when I was returned to the  "Please select the Go SDK" dialog, no selection appeared in the Project SDK area (see screenshot):

![image 1](https://cloud.githubusercontent.com/assets/1711364/6701025/0ec4c9f4-ccd4-11e4-8699-4aa9ce410262.png)

- When I did click "next" on that dialog, I was asked if I really wanted to create a project without an SDK defined:

![image 2](https://cloud.githubusercontent.com/assets/1711364/6701039/3984aeca-ccd4-11e4-8fa1-fd526c7c064f.png)

- I was unable to proceed from that point.

**Comment by dlsniper** [comment]
Please download and install the latest version of the plugin from the Github releases section of this repository. Thank you.

**Comment by jbuberel** [comment]
That works much better! Playing with it now.
