### ISSUE TITLE
"Make Project" doesn't actually compile/verify code

### ISSUE THREAD

**Issue by armhold** [go-lang-plugin-org/go-lang-idea-plugin#1453]
Build Menu -> Make Project (or CMD+F9 on Mac) *seems* to compile/verify your code, as it briefly prints "Make..." in the IDEA window gutter. However in reality it does not seem to actually run the compiler. 

To reproduce: create a simple go file with an error:

```
package foo

x // syntactic error
```

Build Menu -> Make Project produces no errors. "go build" from the command line will complain.

* Intellij 14.0.3
* Java 1.6.0_65
* OSX Yosemite 10.10.2
* Go 1.4.2

**Comment by dlsniper** [comment]
Plugin version plx?

**Comment by armhold** [comment]
I did leave out the most important bit of information, didn't I?  :-)

Sorry, it's 0.9.164.

**Comment by dlsniper** [comment]
Can you please try with the latest release? I think there were some
improvements for running stuff frlm IDEA but I can remember for sure.

Thank you.

**Comment by armhold** [comment]
The IDEA repo only seems to have 0.9.15.3 from 2014-01-09. Where can I get the latest plugin?

**Comment by zolotov** [comment]
> However in reality it does not seem to actually run the compiler.

Indeed it doesn't run the compiler. What do you think it should run (I mean what exactly go command)?

**Comment by armhold** [comment]
I would expect it to run "go build", and if there is any error output it should show up as errors in the Intellij build results window. Then the line #s with errors would be clickable for easy fixing. This is the normal way of handling builds in Intellij.

However I'm new to Go (about 1 week so far), so perhaps someone wiser than I am has a better idea than "go build"? Thanks for your attention.

**Comment by zolotov** [comment]
> I would expect it to run "go build"

On which file?

**Comment by armhold** [comment]
"Make Project" is for building the entire project, so I would expect it to run "go build" without arguments, in the root of the project dir, thereby building all packages in the current project.

**Comment by armhold** [comment]
... and is there a more recent version of the plugin than  0.9.164? If so, where can I get it? Do I really need to build the entire Intellij Community Edition just to compile the plugin, as the docs suggest?  Thanks.

**Comment by dlsniper** [comment]
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases

**Comment by zolotov** [comment]
> "Make Project" is for building the entire project, so I would expect it to run "go build" without arguments, in the root of the project 

If project root doesn't contain any package (e.g. https://github.com/limetext/lime) it fails. If project root contains several main files – if fails. If project root is the whole GOPATH – it fails. It seems that it's not a universal approach.

>  is there a more recent version of the plugin than 0.9.164?

Yes, you can find it on [releases page](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases)

> Do I really need to build the entire Intellij Community Edition just to compile the plugin, as the docs suggest?

Not necessary, we upload new plugin builds every week, so you can use them.

**Comment by zolotov** [comment]
> Do I really need to build the entire Intellij Community Edition just to compile the plugin, as the docs suggest?

And if you want to compile plugin manually then it''s not required too. Only plugin will be compiled, your IDEA will be used as an SDK so you don't need IntelliJ CE source at all.

**Comment by armhold** [comment]
> https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases

Thanks. I would suggest making that more prominent on the [main page](https://github.com/go-lang-plugin-org/go-lang-idea-plugin#how-to-use-it).

**Comment by zolotov** [comment]
We'll make but later.
About `make project`. If someone think of a way to do it for any type of go project I'll be glad to implement it. Until then closing the issue.

**Comment by armhold** [comment]
> If project root doesn't contain any package (e.g. https://github.com/limetext/lime) it fails. 
> If project root contains several main files – if fails. If project root is the whole GOPATH – it fails. 
> It seems that it's not a universal approach.

Perhaps the term "project root" is incorrect. I am **not** referring to all of GOPATH/**. I am referring only to the "content roots" in the IDEA project. For example, I have my project configured like this:

![go-plugin](https://cloud.githubusercontent.com/assets/528692/6717175/1ddb3588-cd81-11e4-8331-2af4635922ba.png)

There is `pinwheel`, `pinwheel.static`, `pinwheel.dao`, and `pinwheel.geo` subdirs. I can go into any of these directories from the command line and issue "go build -v", and it will build everything in the current level and below. I assume this is standard for "go build", and I would expect the plugin to do the same thing in the top-level content root of my project.

**Comment by armhold** [comment]
OK, I see, if there is no .go file in the toplevel, then it fails. Best I can suggest is to run it in all subdirs with at least one .go file.

**Comment by zolotov** [comment]
> Best I can suggest is to run it in all subdirs with at least one .go file.

It also might fail if couple packages are depending on each other :) Also `go build` could produce different results depending on compiling packages, main files, target arch and so on, IDE has no this information while making project.

"content roots" doesn't mean anything for go. Because many users have very different project layout and because different IDEs (RubyMine, IDEA, WebStorm) have different types of "roots". Also I don't want to make go-specific roots, it will make configuration complicated and it seems senseless to me.

For now you can create Go Application run configuration and it will run `go build` and show you the errors. Build | Make project is too ambiguous action for `go build` tool.

**Comment by DmitriyMV** [comment]
Can't we have
```go build ./...```
for make button?

**Comment by zolotov** [comment]
@DmitriyMV `go build ./...` it's not a universal way for any type of project, e.g. you can't build golang sdk with it, but for example you can create run configuration that will build `gofmt` tool. 

We can say that if your project is not compiled by `go build ./...` then you shouldn't use `make project` action but it doesn't work if you have a project with java and go modules, so you have to use `make` action for java and will be disappointed every time when it fails because of go module. 

As a workaround for checking errors, you can try to configure [external tool](https://www.jetbrains.com/idea/help/external-tools.html) with any command you want, bind it on some shortcut and invoke every time you want to see compiling errors.

**Comment by DmitriyMV** [comment]
@zolotov 
> you can't build golang sdk with it
I don't think that's a problem. Util (maybe) we have some sort of third(?) party build tool that can handle complex build tool tasks and it will be adopted by community, I don't see a problem in the fact that some projects are using make files or bash scripts to build them and IDEA's Go can't handle them. IDEA doesn't support every building tool which is out there for Java either (there also some projects that are using Makefile, lol) but it didn't stop them. Why this should be issue here?

> but it doesn't work if you have a project with java and go modules
Cross language projects are always hard to work with. This kind of project will require some sort of complex build tool. I suggest we don't wait for it, because it could probably never even come out.

> We can say that if your project is not compiled by go build ./... then you shouldn't use make project action
This is actually very explicit behavior. Go cross language support is still somewhat new and if you want to do "experimental" stuff you should be ready to get your hands dirty. Also supporting cross language builds is rather complex and I would wait until golang-nuts would have some sort of agreement of how Go boundaries work at all. 1.6 is changing rules again for sharing data between languages.

> you can try to configure external tool
Thanks - i will look into it.

**Comment by zolotov** [comment]
@DmitriyMV make project action compiles all sources despite of using build tool. Go Sdk was just example. Actually for any solution that you suggest (`go build ./...` or anything else) I believe I can provide a project or think of an example which won't work for suggested solution. All these things were discussed a lot in this or related issue.  

> This is actually very explicit behavior. Go cross language support is still somewhat new and if you want to do "experimental" stuff you should be ready to get your hands dirty. Also supporting cross language builds is rather complex and I would wait until golang-nuts would have some sort of agreement of how Go boundaries work at all. 1.6 is changing rules again for sharing data between languages.

It's not about crosslanguage support at all. It's about project structure, I may have Java module for some android application and some go-module that sends push notifications for this app. I don't care how these parts of application talk to each other, the point is that they are placed in one single project.

> Cross language projects are always hard to work with. This kind of project will require some sort of complex build tool. I suggest we don't wait for it, because it could probably never even come out.

No, it's not always hard to work with. No, they doesn't require complex build tool and it has nothing to do with files compilation via `make project` action actually.

**Comment by DmitriyMV** [comment]
> I believe I can provide a project or think of an example which won't work for suggested solution.

I also can. But de facto standard is that the project should be either go gettable or should compile using ./...
If you want to integrate every possible solution, then first step would be to provide full customization for build action in which user can replace ```go build``` with ```gb build``` for example.

> I may have Java module for some android application and some go-module that sends push notifications for this app. I don't care how these parts of application talk to each other, the point is that they are placed in one single project.

Right now there is gradle plugin to build go module for java project. But its quite simple wrapper around gomobile bind\build.

> No, it's not always hard to work with. No, they doesn't require complex build tool and it has nothing to do with files compilation via make project action actually.

In theory - yes. In practice - Java\C++ android projects still requires separation, at least in Android Studio.

In the end you gonna end up with the solution that covers only % of entire thing, or enabling full customization of build process. The choice is your's...

**Comment by zolotov** [comment]
Once again, I didn't talk about interop between go and other languages, I don't care how bad it is. I'm talking about two modules in one project: Java and go, that's all.


What the point to invent all of this if it cannot be universal? Your target was "show all errors", I said how you can reach this. Inventing building process for showing errors is overkill.

**Comment by zolotov** [comment]
> In theory - yes. In practice - Java\C++ android projects still requires separation, at least in Android Studio.

Why is that?

**Comment by zolotov** [comment]
> enabling full customization of build process

What? How? How do you think I will customize main file and build flags every time whine I want compile the project?

**Comment by aanm** [comment]
@zolotov I'm facing this problem as well. Isn't possible to have something similar to the option "Run 'Build project/sub-directory'"?

**Comment by zolotov** [comment]
@aanm there is not problem and no, it's not possible, please read this thread and related issues.

**Comment by aanm** [comment]
@zolotov What about creating/linking a build target to a specific makefile target?

**Comment by zolotov** [comment]
@aanm what do you mean?

**Comment by aanm** [comment]
@zolotov I was just thinking out loud.

For everyone with similar problems you can just create a `Run/Debug configuration` for that specific code directory under IntelliJ.

**Comment by dlsniper** [comment]
@aanm there are some complex questions to be answered for a build to work from the IDE.
For example, what should the plugin build for these files:
- https://github.com/kubernetes/kubernetes/blob/master/Makefile (no default)
- https://github.com/docker/docker/blob/master/Makefile (has a default to binary)
- https://github.com/hashicorp/terraform/blob/master/Makefile (has a default to test)
- https://github.com/derekparker/delve/blob/master/Makefile (no default, needs environment variable)

And what if:
- there are multiple binaries in the project?
- different build flags?
- no makefile but a bash script?
- or no bash script but a cmd one (hello Windows :D)
- or multiple modules with different types?
- or, like someone was asking the other day, a Gradle build script?

If you want to compile the binary from the IDE (for whatever reason) but not run it, you can do so by creating an external tool (see the tutorial here: https://www.jetbrains.com/idea/help/external-tools.html) and assign it a shortcut. Not sure which IDEs support this, IntelliJ Ultimate has this feature.
