### ISSUE TITLE
Autocomplete show functions from _test.go files

### ISSUE THREAD

**Issue by linniksa** [go-lang-plugin-org/go-lang-idea-plugin#1454]
```go
// foo_test.go
package foo

func MyBar() {

}
```

```go
package main

func main () {
	MyBar<ctrl+space>
}
```

**Comment by dlsniper** [comment]
I can't replicate it on my machine / setup.
Can you please provide more details on how to replicate it? What's the plugin build ID, how are your Go libraries configured and what's the path for the files you mentioned.
Also, does the problem happen if you have ```packge foo_test``?

**Comment by linniksa** [comment]
I put whole test project to dropbox:
https://www.dropbox.com/sh/yov3bkj3ripmynf/AAAgQXTx5bgBTWwo2G6wXI3ja?dl=0
plugin version 2a2abd070ffa95dfe11465bae70232036cfc5389

> Also, does the problem happen if you have `packge foo_test?

I not understand this part

Small collage:
![default](https://cloud.githubusercontent.com/assets/424343/6718954/87ed447e-cdc8-11e4-9422-37e14fa4b110.png)
