### ISSUE TITLE
Redeclared package import inspection

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1461]
the following should produce an error:

```go
import (
	"crypto/rand"
	"math/rand"
)
```

```
./file.go:Line: rand redeclared as imported package name
        previous declaration at ./file.go:Line
```

**Comment by sjamesr** [comment]
I'm having a go at this, it's my first attempt at a change to the go plugin

**Comment by dlsniper** [comment]
That's great, if there's something that we can help out, let us know. And please feel free to open a PR as soon as you have something or you get stuck somewhere ;)

**Comment by sjamesr** [comment]
Oh, this case is apparently already handled by GoUnusedImportDeclaration, I'm just going to add it to GoHighlightingTest unit tests

**Comment by sjamesr** [comment]
The patch is done, before I create a pull request, I have to get it OK'd by Google's open source legal folks.

I should already have a CLA on file with Jetbrains.

**Comment by dlsniper** [comment]
There's no need for the CLA for JetBrains, the plugin is under Apache 2 licence :)
