### ISSUE TITLE
In middle of a comment text, if I press Enter should creates a new comment line but it doesn't do.

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#1462]
```go
package main

// Context it is created and used a new context 
in each user request
type Context struct {
}
```

**Comment by ctd1500** [comment]
How will the editor know that it is the middle of a comment text, and that you don't simply want to move on to writing code on the next line?
Isn't this what block comments are for?
```
/*
  Context it is created and used a new context 
  in each user request
 */
```

Though it seems block comments are not auto-completed for Go when typing `/*` and pressing enter, so unless I'm missing a setting, maybe that should be fixed.

**Comment by zolotov** [comment]
@ctd1500 it's common feature for IntelliJ IDEs. See how it works in JavaScript: http://screencast.com/t/beW2iNtj

**Comment by zolotov** [comment]
> How will the editor know that it is the middle of a comment text, and that you don't simply want to move on to writing code on the next line?

If the comment is placed just before function declaration it's unlikely that you simply want make empty line.

**Comment by zolotov** [comment]
Sorry for the third message in a row.

> Though it seems block comments are not auto-completed for Go when typing /* and pressing enter, so unless I'm missing a setting, maybe that should be fixed.

It's not implemented yet. I believe I'll implement it all together: line and block comments.

**Comment by dlsniper** [comment]
Also, I'd argue that the multi-line doc block isn't used by the go team, by the number of comments like this: https://github.com/golang/go/blob/master/src/time/time.go#L12

**Comment by ctd1500** [comment]
> If the comment is placed just before function declaration it's unlikely that you simply want make empty line.

That I can understand. And now that I see how it's implemented in Webstorm, it only continues the comment if you split an existing comment line, not simply by hitting enter at the end, which makes sense to me.

> It's not implemented yet. I believe I'll implement it all together: line and block comments.

Fair enough, thanks for the explanation.
