### ISSUE TITLE
Can't resolve exported struct field from different package from exported var

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1463]
Hi,

Using 43e38a2982ad138f4ba189e957cc54e784725767 I can't use exported fields from structs anymore, this was working in c275c80bc1ec93236b8df47f37310519c853ceb7

To reproduce:

$GOPATH/src/demo/pack/pack.go
```go
package pack

type Demo struct {
	Field int
}

var DemoVar = &Demo{Field: 1}
```

$GOPATH/src/demo/main.go
```go
package main

import "demo/pack"

func main() {
	a := pack.DemoVar
	_ = a.Field // this works
	b := &pack.Demo{Field: 2}
	_ = b.Field // this works
	c := *pack.DemoVar
	_ = c.Field // this fails
}

**Comment by ignatov** [comment]
Can't reproduce.
https://www.dropbox.com/s/h3d0iunfkowxhz5/Screenshot%202015-03-20%2023.37.21.png?dl=0

Sergey Ignatov

**Comment by dlsniper** [comment]
I should stick to my examples in code when I post them online... Here's mine:

![snapshot22](https://cloud.githubusercontent.com/assets/607868/6760606/a864241a-cf4a-11e4-9c87-b4d22a8d4c58.png)

I'll try to find a better example soon

**Comment by ignatov** [comment]
Please share your sample

Sergey Ignatov

**Comment by dlsniper** [comment]
Please see: https://www.dropbox.com/s/ymppfv385ew4xld/u.tar.gz?dl=0 I can reproduce it on a different project but that one is closed source, I'm trying to find an open source version of it with the problem.

**Comment by dlsniper** [comment]
Eurika! I've finally found an open source project that I can reproduce the error: https://code.google.com/p/go/source/browse/html/charset/gen.go?repo=net#37 from the package  ```go get http://godoc.org/golang.org/x/net/html```

**Comment by dlsniper** [comment]
This seems to be fixed in the latest master.
