### ISSUE TITLE
Parser issue with for syntax

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1464]
Please see this (it's present in the go1.4.2 sdk as well, not just latest devel)

https://github.com/golang/go/blob/master/src/runtime/race/race_test.go#L167

This might be related to another "for" issue but I can't find that one right now. 
Using 43e38a2982ad138f4ba189e957cc54e784725767

**Comment by dlsniper** [comment]
This is as well related to "for" parsing: https://github.com/golang/go/blob/master/src/runtime/proc_test.go#L117 
Should I open a different ticket for it?

**Comment by ignatov** [comment]
Yes, please


Sergey Ignatov

**Comment by ignatov** [comment]
Duplicates #1466
