### ISSUE TITLE
indirected pointer isn't "in use"

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1468]
https://www.dropbox.com/s/h74ajidbf4w6vvj/Screenshot%202015-03-20%2023.39.56.png?dl=0

As you can see in that picture, I have a program that calculates the absolute value of a vertex. There is a pointer pointing to my vertex, but when indirected there is a line under it that says 

https://www.dropbox.com/s/d1cx9ebrm7kytgg/Screenshot%202015-03-20%2023.41.42.png?dl=0

Unused variable?

**Comment by ignatov** [comment]
Duplicates #1434. Please download the latest release.
