### ISSUE TITLE
A interface types function is not highlighted.

### ISSUE THREAD

**Issue by nhooyr** [go-lang-plugin-org/go-lang-idea-plugin#1469]
https://www.dropbox.com/s/008sy2mh5h2zo7w/Screenshot%202015-03-21%2000.55.16.png?dl=0

As you can see in that picture, fmt.Println(a.Abs()), Abs is not considered a func and not highlighted. a is of type Abser (a interface). Its value currently is a *Vertex and there is a method implemented for this type, called Abs with same signature as declared in the interface. Code compiles fine but it won't highlight the func (if you go over it, there is no "func" popup like this https://www.dropbox.com/s/jg98gko1t13d3qp/Screenshot%202015-03-21%2000.58.31.png?dl=0, nor syntax highlighting as aforementioned)

Full code here: https://play.golang.org/p/jF0xTfzMYt

**Comment by dlsniper** [comment]
@ignatov this might be a problem of resolving not highlighting.

I've took the example from the playground and did the following:
- ctrl+click on ```v.Abs()``` which sent me to ```func (v *Vertex) Abs() float64```
- ctrl+click on ```a.Abs()``` which sent me to ```Abs() float64``` interface definition not to ```func (f MyFloat) Abs() float64```

In the highlighting part I'm checking where we resolve the method and based on that select the color.

**Comment by ignatov** [comment]
If so, please create a nice code sample and reassign the issue too me.

**Comment by dlsniper** [comment]
```go
package main

import (
    "fmt"
    "math"
)

type Abser interface {
    Abs() float64
}

func main() {
    var a Abser
    f := MyFloat(-math.Sqrt2)
    v := Vertex{3, 4}

    a = f  // a MyFloat implements Abser
    a = &v // a *Vertex implements Abser

    // In the following line, v is a Vertex (not *Vertex)
    // and does NOT implement Abser.
    //a = v
    fmt.Println(v.Abs())
    fmt.Println(a.Abs())
}

type MyFloat float64

func (f MyFloat) Abs() float64 {
    if f < 0 {
        return float64(-f)
    }
    return float64(f)
}

type Vertex struct {
    X, Y float64
}

func (v *Vertex) Abs() float64 {
    return math.Sqrt(v.X*v.X + v.Y*v.Y)
}
```

**Comment by ignatov** [comment]
I'm not sure that we can fix this issue.
`var a Abser` has a type Abser. And the resolution algorithm is going though the interface not though implementations.

**Comment by linniksa** [comment]
@ignatov 
but "type" Abser has method Abs()

**Comment by dlsniper** [comment]
Fixed for now by coloring everything the same :trollface: On the other hand, when we'll have a way to detect if a type implements an interface then we can revisit this (along with other aspects from the highlighting engine)
