### ISSUE TITLE
Dereferencing a pointer to struct does not highlight the variable

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1470]
https://www.dropbox.com/s/a9xdig6h1hmsv0d/Screenshot%202015-03-21%2001.22.11.png?dl=0

(same code from my previous issue https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1469)

Here the problem is that as you can see, if I manually dereference the *Vertex in the first function, Y, and X are not recognized as variables. But when I let go do it for me automatically, it does. Code compiles fine with either one but just the syntax highlighting.

**Comment by dlsniper** [comment]
@ignatov, same problem here as well.

Change the code from
```go
func (v *Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}
```
to
```go
func (v *Vertex) Abs() float64 {
	return math.Sqrt((*v).X*v.X + v.Y*v.Y)
}
```

and you'll notice that the ```(*v).X``` doesn't resolve anymore where as ```v.X is resolving```
