### ISSUE TITLE
Latest Release says 0.9.201 in plugin settings

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1471]
https://www.dropbox.com/s/m0v1xtorcs0hmre/Screenshot%202015-03-21%2004.49.21.png?dl=0

Or is this intended until the "real" 1.0?

**Comment by dlsniper** [comment]
While the name for 1.0 is v1.0.0-alpha0 in the branch, the releases are done with 0.9.XYZ until we reach 1.0 in order to properly work with the plugin manager versioning system.
