### ISSUE TITLE
Cannot add go SDK

### ISSUE THREAD

**Issue by MichaelKuger** [go-lang-plugin-org/go-lang-idea-plugin#1475]
I can't add a go sdk to my project.

Error:
IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null

IntelliJ Ultimate 14.03
Plugin Version: 0.9.15

**Comment by ignatov** [comment]
Please make your best in searching through the issues.
