### ISSUE TITLE
1.0.0: Field is reported unknown if it is instantiated by a local var of the same name

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1476]
```go
type A struct {
	b int
	c int
}

func NewA(b int) *A {
	return &A{
		b: b, // Reported error: "unknown field b", but that is not correct
		c: 1,
	}
}
```

**Comment by dlsniper** [comment]
As another point, if you CTRL+click on the "b" from ```b:``` section, you'll get that it references multiple implementation, one is the parameter b and the other one is the field in the struct. It should only reference to to the field in the struct as the one in the parameter is unrelated.

**Comment by ignatov** [comment]
Thanks for reporting, will be fixed soon.

**Comment by horkhe** [comment]
Indeed it is. Thank you.
