### ISSUE TITLE
Project GOPATH gets reset after restarting idea (1.0.0.alpha#201)

### ISSUE THREAD

**Issue by jimbojetlag** [go-lang-plugin-org/go-lang-idea-plugin#1482]
I need the current project to be in GOPATH. _I think this should happen by default anyway, even if the project is out of GOPATH._ For this to happen, I have to set the absolute path to my project in the project settings > Libraries, which is a bad idea, as this should not be shared to other developers.

Forgetting about the above flaws (hint: we shouldn't), the GOPATH project settings > Libraries gets reset to default after restarting idea.

**Comment by zolotov** [comment]
>  I think this should happen by default anyway, even if the project is out of GOPATH.

It shouldn't. IDE has no idea what directory should be in GOPATH. Project root? Parent directory of project root? One of child directories?

> Forgetting about the above flaws (hint: we shouldn't), the GOPATH project settings > Libraries gets reset to default after restarting idea.

Please attach .idea/goLibraries.xml just after changing libraries list and the same file after restarting IDE.

**Comment by jimbojetlag** [comment]
> It shouldn't. IDE has no idea what directory should be in GOPATH. Project root? Parent directory of project root? One of child directories?

At least, allow an option to add a relative directory (relative to project root), so that this can be sharable. (Does idea allow this already? Sorry I'm not an idea expert)

The xml file does not change after restart:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="GoLibraries">
    <option name="urls">
      <list>
        <option value="file://$PROJECT_DIR$/web" />
      </list>
    </option>
  </component>
</project>
```

**Comment by zolotov** [comment]
> Does idea allow this already?

It does, as you can see `web` directory is stored in settings as a relative path to project. We just show absolute paths in settings, it's just representation.

> The xml file does not change after restart

But Go Libraries dialog became empty?

**Comment by zolotov** [comment]
project settings > Libraries should be updated automatically

**Comment by jimbojetlag** [comment]
1. Adding module directory in Project Settings > Libraries > GOPATH <my-module> has no effect (eg autocomplete does not work for the code in module)
2. After making the above change, .idea/goLibraries.xml does not have any libraries:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="GoLibraries">
    <option name="urls">
      <set />
    </option>
  </component>
</project>
```

**Comment by jimbojetlag** [comment]
The above bugs are for 0.9.241.

**Comment by zolotov** [comment]
Works as expected, you shouldn't modify Project Settings > Libraries > GOPATH. Use Go Libraries configuration.

**Comment by jimbojetlag** [comment]
After updating to 0.9.242, I tried these with no luck:

- Deleted the project an recreated a new Go project.
- Added the project path to Go Libraries Global part.
- Added the project path to Go Libraries Project part.
- Added the project path to Go Libraries Module part.
- Invalidated cache and restarted IDE.

Autocomplete still does not work for the code in the project.

**Comment by dlsniper** [comment]
@jimbojetlag can you try to create a video of what's happening? Also, do you have any other plugin or do you run only with the default plugins? Do you have any errors reported by the IDE (```Help | Show Log in File Manager```, you might want to open the folder, close idea, wipe everything from there and start IDEA again, then the logs should be more clean). Do you have any antivirus or otherwise something that could interfere with the IDE?
Hope this helps :)

**Comment by zolotov** [comment]
@jimbojetlag please tell about your project configuration and give an code example where completion doesn't work.

**Comment by jimbojetlag** [comment]
Regenerating this problem is easy:

- Create a new Go project _outside of your GOPATH_
- Create a simple package and main file like this:
```
├── foo
│   └── foo.go
└── main.go
```
```go
package foo

var Bar = 42
```
```go
package ijgotest

import "foo"

func test() int {
    return foo.Bar
}
```
- In IJ Preferences > Languages & Frameworks > Go Libraries, add the current project path to Global libraries (or Project libraries, or Module libraries).

- The Go Project package is not parsed:

![image](https://cloud.githubusercontent.com/assets/11205806/6964972/02d28c8e-d946-11e4-91ac-55d5d4cdf919.png)

**Comment by zolotov** [comment]
> Create a new Go project outside of your GOPATH

So try to add you project root to Go Libraries

**Comment by dlsniper** [comment]
But that's not a valid go project layout.
If you want to have a project outside of the GOPATH, you MUST follow the instructions here: https://golang.org/doc/code.html#Workspaces

Your layout must be:
```
$PROJECT_DIR
|-- src/
         |-- main.go
         |-- foo/
                   |-- foo.go
```

@zolotov I've noticed that in this setup it's impossible to create a runner configuration. If it's not a known issue, should I open a new one?

**Comment by jimbojetlag** [comment]
> If you want to have a project outside of the GOPATH, you MUST follow the instructions here

Not necessarily, that's just a recommendation. Specifically, appengine projects do not have the src directory.

**Comment by dlsniper** [comment]
> Not necessarily, that's just a recommendation. Specifically, appengine projects do not have the src directory.

"Go code must be kept inside a workspace. A workspace is a directory hierarchy with three directories at its root:"

Also, this blog post reflects how GAE is workspace aware https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath 

So, at least to my understanding, if you want to have a project outside of the main GOPATH, you should respect the workspace structure. The plugin behaves correctly in this case.

**Comment by jimbojetlag** [comment]
Appengine Go SDK does not follow the above convention, see https://cloud.google.com/appengine/docs/go/#Go_Organizing_Go_apps :

> The SDK will look for the package "foo/bar" in these locations when you run or deploy module1:
>   `project-dir/module1/foo/bar`
>  `/home/fred/go/src/foo/bar`

Here, `project-dir` is any arbitrary directory outside, or inside GOPATH, with, or without the `src` directory.

I think the IDE must follow the Appengine SDK conventions, rather than the golang workspace conventions. At the very least, this should be applied to a Go Appengine project. You can keep the golang workspace conventions for a standard Go project.

Google Appengine go team had to break their own restricting rules about workspaces to make it consistent with the appengine projects.

**Comment by zolotov** [comment]
@jimbojetlag got it, created the separate issue #1525
