### ISSUE TITLE
Primitive types are not resolved in projects (1.0.0.alpha#201)

### ISSUE THREAD

**Issue by jimbojetlag** [go-lang-plugin-org/go-lang-idea-plugin#1483]
![image](https://cloud.githubusercontent.com/assets/11205806/6855062/28e38d00-d3ed-11e4-992d-3301da042ddc.png)

**Comment by dlsniper** [comment]
What SDK do you have attached to the project?

**Comment by jimbojetlag** [comment]
Go 1.4.1 (appengine-1.9.18)

**Comment by dlsniper** [comment]
and it's attached to the module as well?

**Comment by jimbojetlag** [comment]
I believe so:

![image](https://cloud.githubusercontent.com/assets/11205806/6855413/d10d6490-d3ef-11e4-85a6-46d7c56e867c.png)

**Comment by zolotov** [comment]
did recreating sdk fixed this?

**Comment by jimbojetlag** [comment]
No, I did not.

Custom GOPATH in Project Settings > Libraries > GOPATH <project-name> still gets reset after restart. I tried invalidating cache and restarting with no effect.

**Comment by zolotov** [comment]
I've asked about primitive types.

> Custom GOPATH in Project Settings > Libraries > GOPATH still gets reset after restart. I tried invalidating cache and restarting with no effect.

Is this a problem? Actually you don't need `Project Settings > Libraries > GOPATH`? It's internal library and it's configured by IDE according to directories in `Settings | Language & Frameworks | Go Libraries` and directories in the project.

**Comment by jimbojetlag** [comment]
The primitive types problem is still present. It used to go away when I added the project directory to GOPATH with the above method, but this does not work anymore.

**Comment by jimbojetlag** [comment]
Sorry, the primitive types problem is now resolved for me. I got it mixed it with the project path problem.

**Comment by zolotov** [comment]
So I can close the issue?

**Comment by jimbojetlag** [comment]
I guess so!
