### ISSUE TITLE
go fmt throws exception com.intellij.execution.process.ProcessNotCreatedException (1.0.0.alpha#201)

### ISSUE THREAD

**Issue by jimbojetlag** [go-lang-plugin-org/go-lang-idea-plugin#1484]
At least for app engine:

```
com.intellij.execution.process.ProcessNotCreatedException:
Cannot run program "/usr/local/gcloud/google-cloud-sdk/platform/google_appengine/bin/go":
error=2, No such file or directory in GeneralCommandLine.createProcess(GeneralCommandLine.java:296)
Caused by: java.io.IOException:
Cannot run program "/usr/local/gcloud/google-cloud-sdk/platform/google_appengine/bin/go": error=2, No such file or directory at java.lang.ProcessBuilder.processException(ProcessBuilder.java:478)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:457) in GeneralCommandLine.startProcess(GeneralCommandLine.java:306) ... 39 more Caused by: java.io.IOException: error=2,
No such file or directory at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess. (UNIXProcess.java:53) at java.lang.ProcessImpl.start(ProcessImpl.java:91)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:452) ... 41 more
```

**Comment by zolotov** [comment]
You've already created the issue #1387.

Where is the exception is appeared? In event log or just as notification?

**Comment by zolotov** [comment]
Sorry, didn't noticed that it's about go fmt. But anyway it's related to #1387

**Comment by dlsniper** [comment]
@zolotov as a comment, on AppEngine the ```go fmt``` doesn't work as the ```go``` tool is not there anymore (on the 1.9.18 version that is) and we should run ```gofmt -w path```.

The layout of AppEngine dir is now:
```
ls -alh /usr/local/go_appengine/
total 296K
drwxr-x---  8 florinp florinp 4,0K Mär  5 14:51 .
drwxr-xr-x 12 root    root    4,0K Feb 14 00:48 ..
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 appcfg.py
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 backends_conversion.py
-rw-r-----  1 florinp florinp  156 Feb 12 13:38 BUGS
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 bulkload_client.py
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 bulkloader.py
drwxrwxr-x 12 florinp florinp 4,0K Feb 12 13:38 demos
-rwxr-x---  1 florinp florinp 1,9K Feb 12 13:38 dev_appserver.py
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 download_appstats.py
-rwxr-x---  1 florinp florinp 3,1K Feb 12 13:38 endpointscfg.py
-rwxr-xr-x  1 florinp florinp 1,5K Feb 12 13:38 goapp
-rwxr-xr-x  1 florinp florinp 1,5K Feb 12 13:38 godoc
-rwxr-xr-x  1 florinp florinp 1,5K Feb 12 13:38 gofmt
drwxrwxr-x  6 florinp florinp 4,0K Mär  5 14:51 google
drwxrwxr-x  2 florinp florinp 4,0K Feb 12 13:38 gopath
drwxrwxr-x  6 florinp florinp 4,0K Feb 12 13:38 goroot
drwxrwxr-x 41 florinp florinp 4,0K Feb 12 13:38 lib
-rw-r-----  1 florinp florinp 5,9K Feb 12 13:38 LICENSE
-rwxr-x---  1 florinp florinp 1,9K Feb 12 13:38 php_cli.py
-rwxr-x---  1 florinp florinp 1,9K Feb 12 13:38 _python_runtime.py
-rw-r-----  1 florinp florinp  15K Feb 12 13:38 RELEASE_NOTES
-rw-r-----  1 florinp florinp 156K Feb 12 13:38 RELEASE_NOTES.python
-rwxr-x---  1 florinp florinp 2,1K Feb 12 13:38 run_tests.py
drwxrwxr-x  2 florinp florinp 4,0K Feb 12 13:38 tools
-rw-r-----  1 florinp florinp  221 Feb 12 13:38 VERSION
-rwxr-x---  1 florinp florinp  11K Feb 12 13:38 wrapper_util.py
-rw-r-----  1 florinp florinp 8,7K Mär  5 14:51 wrapper_util.pyc
```

**Comment by jimbojetlag** [comment]
I'm not sure if this is related to #1387. I tried Code > Go fmt file (awkward keyboard shortcut on OS X by the way)
![image](https://cloud.githubusercontent.com/assets/11205806/6855319/04831690-d3ef-11e4-82a2-3d242b0e920d.png)
The exception appears as a notification.

**Comment by zolotov** [comment]
@dlsniper I believe that goapp wrapper is able to run `goapp fmt`

**Comment by zolotov** [comment]
@jimbojetlag thanks

**Comment by zolotov** [comment]
@jimbojetlag 
> awkward keyboard shortcut on OS X by the way

You can use internal formatting processor (cmd+shift+L), it's not fully matched with gofmt but all these cases are bugs and we're going to fix it.

**Comment by zolotov** [comment]
Fixed

**Comment by jimbojetlag** [comment]
I just tried the nightly build and got the below error. Should I try the next nightly build, or is the existing one supposed to fix it?

```
Error:Cannot run program "/path/to/gcloud/google-cloud-sdk/platform/google_appengine/bin/go" (in directory "/path/to/project"): error=2, No such file or directory
```

**Comment by zolotov** [comment]
What did you do exactly?

**Comment by zolotov** [comment]
And specify gae sdk version please

**Comment by jimbojetlag** [comment]
I removed the existing GO SDK (1.9.18), and create it again, and it worked fine. Now 'go fmt file' and 'go fmt project' work as expected.

One problem is that when having multiple modules, 'go fmt project' only formats one of them.

**Comment by zolotov** [comment]
> I removed the existing GO SDK (1.9.18), and create it again, and it worked fine. Now 'go fmt file' and 'go fmt project' work as expected.

Thanks, I didn't think about it.

> One problem is that when having multiple modules, 'go fmt project' only formats one of them.

This actions formats base directory of project. Are some your modules is outside project directory?

**Comment by jimbojetlag** [comment]
> This actions formats base directory of project. Are some your modules is outside project directory?

Yes. The modules outside of the base directory do not get formatted. If an IJ project is supposed to consist of modules which could be outside of the project base directory, perhaps all modules should get formatted.

**Comment by zolotov** [comment]
You're. Since this is not about GAE I've filed another issue #1505
