### ISSUE TITLE
wrong defer hint 

### ISSUE THREAD

**Issue by ElvizLai** [go-lang-plugin-org/go-lang-idea-plugin#1487]
The code blow works well，but the hint is improper.
This hint works well on release 201,but not ok on 223.

```
func writeValues(values []int, outfile string) error {
    file, err := os.Create(outfile)
    if err!=nil {
        fmt.Println(err)
        return err
    }

    defer file.Close()
    for _, value := range values {
        str := strconv.Itoa(value)
        file.WriteString(str+"\n")
    }
    return nil
}
```

![qq20150327-3](https://cloud.githubusercontent.com/assets/501861/6860359/f2d0e922-d461-11e4-8d71-01b11f1e6991.png)
![qq20150327-4](https://cloud.githubusercontent.com/assets/501861/6860473/87f257b0-d463-11e4-88bd-e29a89799aa0.png)

**Comment by ignatov** [comment]
Thanks for reporting, reproduced. Will be fixed soon.

**Comment by ElvizLai** [comment]
release 238 in nightly， still unsolved.

**Comment by dlsniper** [comment]
@ElvizLai we warmly accept contributions :)
