### ISSUE TITLE
compile (build) fails: no buildable Go source files in /home/user/go

### ISSUE THREAD

**Issue by ichekrygin** [go-lang-plugin-org/go-lang-idea-plugin#1489]
Possibly relate to #1288

Repro steps:

select go file (any go file) and try to compile using go plugin:
 (Ctrl+Shif+F9) or via right click or build menue

Expected: go build run on the selected file
Actual: Error:go: can't load package: package .: no buildable Go source files in /home/user/go

/home/user/go - is a $GOPATH

**Comment by dlsniper** [comment]
Which version of the plugin are you using? Also, if you are trying to use the build menu options (or shortcuts)  please don't. You've read already, it's not possible. Thank you.

**Comment by dlsniper** [comment]
Yeah, I've just checked, it's the build menu.

**Comment by ichekrygin** [comment]
What are the alternatives to build go files/packages (other than command line)?

**Comment by dlsniper** [comment]
You can use the runners option. Asside from that, building from command
line is known to work very well

**Comment by ichekrygin** [comment]
By "runners" I assume you're talking about RUN menu. If so, how do I use runners, especially for "non main" go files? It seems I don't even get an options to create a runner where I can navigate to a non-main go file.

I guess the same question is for "go test". If I recall, in previous version of the plugins (older than 1.0.0) go test used to work. Now it seems doesn't. I am getting this:

/usr/local/go/bin/go test -v foo/bar/buz/qux -run ^TestQux$
Testing started at 8:48 AM ...
can't load package: package foo/bar/buz/qux: cannot find package "foo/bar/buz/qux" in any of:
	/usr/local/go/src/foo/bar/buz/qux (from $GOROOT)
	/home/user/go/src/src/foo/bar/buz/qux (from $GOPATH)

**Comment by zolotov** [comment]
>  It seems I don't even get an options to create a runner where I can navigate to a non-main go file.

I didn't understand anything. What exactly do you want to do and how do you run your application without IDE?

> /usr/local/go/bin/go test -v foo/bar/buz/qux -run ^TestQux$
Testing started at 8:48 AM ...
can't load package: package foo/bar/buz/qux: cannot find package "foo/bar/buz/qux" in any of:
/usr/local/go/src/foo/bar/buz/qux (from $GOROOT)
/home/user/go/src/src/foo/bar/buz/qux (from $GOPATH)

Obviously it's output of go. So here are two questions:
1. what do you get if you run `/usr/local/go/bin/go test -v foo/bar/buz/qux -run ^TestQux$` from terminal, and if it works in terminal then your configuration in IDEA is different from terminal's.
2. what do you usually run in terminal for running these tests?

**Comment by ichekrygin** [comment]
@zolotov thx for following up. Actually it was a "user error", I had invalid configuration for $GOPATH as per out: `/home/user/go/src/src/foo/bar/buz/qux (from $GOPATH)`

**Comment by zolotov** [comment]
@ichekrygin Ok, thanks for update. And what about runners for 'non-main go file'?
 
About `make file` you can read discussion in #1453. TL;DR: I have no know idea what `make` action should do in terms of go.
