### ISSUE TITLE
Exclude directories "testdata" and "_*" from Alt-Enter auto-include

### ISSUE THREAD

**Issue by bong0** [go-lang-plugin-org/go-lang-idea-plugin#1490]
I discovered that in one of my procect's files a package from `golang.org/x/tools/cmd/vet/testdata` was included for some reason. This may likely have happened due to semi-automatic including which comes up when the plugin detects a name of a non-imported package.

Like Dave suggests here https://groups.google.com/d/msg/golang-nuts/WS39uEWUA-0/A4WpJ1fLA_gJ testdata and directories beginning with an underscore should not be included via this feature since they are not buildable in some cases => breaking the build

**Comment by dlsniper** [comment]
@zolotov if it's not too complicated, I think it would be useful to mark ```testdata```, any ```_dirName``` as excluded when creating the project (or importing the libraries). Also, I'd suggest adding ```Godeps``` to the list of excluded dirs. What do you think?

**Comment by zolotov** [comment]
@dlsniper Excluding `testdata` and `_dirname` approach works for SDK sources only. And they should be excluded indeed, it will fix the issue and speed up indexing.

What about Godeps? What the rules of exclusions?

**Comment by dlsniper** [comment]
Sorry for not being clearer.

In regards to Godeps, it already contains a directory called ```_workspace``` so if ```_*``` or ```testdata``` dirs are excluded automatically then it would it shouldn't be a problem. 

How I see this working:
- the plugin detects when loading a project the dirs that start with _ or are named testdata and marks them as excluded
- the plugin detects when indexing the SDK / libraries the dirs with the same pattern and skips them from indexing.

Does it make sense?

Here's a few examples on how I'd see this working for projects:
etcd (```github.com/coreos/etcd```)
![snapshot27](https://cloud.githubusercontent.com/assets/607868/6881376/08614312-d55d-11e4-9b24-31b829df6eca.png)

ini package (```gopkg.in/ini.v1```, https://github.com/go-ini/ini/tree/v1)
![snapshot28](https://cloud.githubusercontent.com/assets/607868/6881382/63cce346-d55d-11e4-9eab-a13e977a9214.png)

**Comment by zolotov** [comment]
> the plugin detects when loading a project the dirs that start with _ or are named testdata and marks them as excluded

No, excluded directories is excluded from all indices, it means that TODO index and `Find in path` won't work there as well. It's ok for Godeps but I'm not sure that this is right way for `testdata` and underscored directories.

**Comment by dlsniper** [comment]
@zolotov I'd like to work on this over the weekend, any tips on where to pick this up? Thank you.

**Comment by zolotov** [comment]
@dlsnipet leave this to me, this is hard one with questionable possible solutions and with harmful side effects for non-go modules

**Comment by dlsniper** [comment]
Ok, sure. I wanted to get a bit more familiar with the completion code and see where I can help with other tickets so this one seemed simple enough (discard matches from "testdata" && "^_(.*)$" dirs).

**Comment by zolotov** [comment]
@dlsniper 

#1511 should be simple. See  constructor of GoAutoImportCompletionContributor and GoAutoImportCompletionContributor#autoImport.

#1382 also not really complicated but it could lead to performance problem, you can try to implement in the same way as functions/types completion done in GoAutoImportCompletionContributor in the separate branch and create some performance tests for that.

And following:
- do not insert space after return if function is void
- delete functions from completion
```
type name <caret>
```
- delete types from completion
```
type name <caret> {
}
```
- delete types from completion
```
func findMarker(c <-ch<caret> int) int {
}
```

**Comment by akaspin** [comment]
Excludes not works. It's pain.

**Comment by zolotov** [comment]
Partially reverted, exclusion works only in small IDEs now

**Comment by dlsniper** [comment]
From [http://golang.org/cmd/go/#hdr-Description_of_package_lists](http://golang.org/cmd/go/#hdr-Description_of_package_lists) about the ```go tool``` and how ```go [command]``` works ```Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".```

**Comment by zolotov** [comment]
So what? Check out the real compiling:
<img width="1392" alt="screenshot 2015-07-19 14 33 31" src="https://cloud.githubusercontent.com/assets/140920/8765706/360d9184-2e23-11e5-967c-809ae57633bd.png">

**Comment by zolotov** [comment]
Or with underscore
<img width="1392" alt="screenshot 2015-07-19 14 35 27" src="https://cloud.githubusercontent.com/assets/140920/8765711/72f41762-2e23-11e5-988d-d9c2fabd8fba.png">
