### ISSUE TITLE
Possible performance issue?

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1493]
Maybe it's my slow laptop (i7-2630QM CPU, 8GB RAM, Ubuntu 14.10), but I've noticed while working on a personal project that sometimes I can't even rely on autocomplete to be there when typing something as simple as http.Status<ctrl+space>.

As such, I've followed the tutorial [on snapshoting](https://intellij-support.jetbrains.com/entries/29983118-Reporting-performance-problems) and I've created the ```go-IU-141.177_florinp_28.03.2015_00.30.10.zip.zip``` file which I've uploaded to the FTP repository mentioned there.

I've also noticed that sometimes, the Inspections reach around 98% or so, then Syntax Analysis starts again followed by Inspections again and then it finishes, I think it's mostly when the Slow inspections are also present in the list of things running, which strangely enough, finish faster than normal Inspections.

The file on which I've produced the snapshot is about 1.5k lines but I've noticed the slowdown earlier than this size, the project itself is like this:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              55           2213            838           9370
XML                             13              0              0           2766
SQL                              1             43            103            147
Bourne Shell                     7             22              0            122
YAML                             1              0             12             48
-------------------------------------------------------------------------------
SUM:                            77           2278            953          12453
-------------------------------------------------------------------------------
```

I'll do my best to find an open-source project that I can replicate the issue on.

Thank you!

**Comment by JoeBruner** [comment]
I've noticed that my desktop fan is churrning way more these days as my files get bigger and bigger.  I don't _usually_  have problems with autocomplete, but I have the problem frequently where the IDE will "red squiggle" a variable and say it's an "Unused variable" when in reality it's used in many places.  Oddly (or maybe it's just a figment of my imagination), it seems like I can speed up the process of the squiggles going away by going to the terminal and building or testing the project.   It does get very annoying when it's trying to tell me that variables are invalid when I'm using them on the next line.

FWIW, I'm running on an i7 870, 16GB Ram, Ubuntu 14.10 and SSD.

**Comment by ignatov** [comment]
I'll do my best on this issue. BTW, it'll be really cool to have some
reproducible sample.

Sergey Ignatov

**Comment by dlsniper** [comment]
I've managed to replicate it in an open-source project! :tada: 

The package is: ```golang.org/x/net``` (```go get golang.org/x/net ``` and then switch to the revision 7dbad50ab5b31073856416cdcfeb2796d682f844, to have the same version as I have)

To replicate it, after you have the said package in your GOPATH, create a project pointing to where the package is, in my case ```/home/florinp/golang/src/golang.org/x/net/```.

After the project is loaded in the IDE, go to ```webdav/file_test.go``` on line 1022, (should be ```case "mkdir":```) then transform it to:

before:
```go
		case "mkdir":
			err := fs.Mkdir(op[1], os.ModeDir|0777)
			if err != nil {
```

after:
```go
		case "mkdir":
			err := fs.Mkdir(op[1], os.ModeDir|0777)
			err = fs.M// the problem should be noticeable by the time you've finished typing this
			if err != nil {
```

Hope this works for you as well.

@JoeBruner if you have a different package (or you can reproduce it as well) that would be awesome as I can't publish the project where I've noticed this one.

**Comment by JoeBruner** [comment]
I loaded that up and the Intellisense popped up the millisecond I typed `.`

Unfortunately, my proj is not hosted on a public repo.  I'll see if I can reproduce my probs in that project.

**Comment by JoeBruner** [comment]
I can get my Unresolved ref problem in that file

**Comment by dlsniper** [comment]
@JoeBruner are you referring to the line which contains a ```nil```, like this line: ``` if err = json.Unmarshal([]byte(result.(string)), user); err != nil {``` ?

**Comment by JoeBruner** [comment]
So at line 791 I did this (it's not useful, but reproduces the problem)

    q = t
    if err := TestMemFile(q); err != nil {
    }

this will cause problems because TestMemFile doesn't return a value.  It then marked `a` on line 799 and 800 as problems.  I then change it back to:

    q = t
    TestMemFile(q)

and it takes a while (min or 2) and eventually the problems at line 799/800 go away, but I still have a problem on 791/792

![image](https://cloud.githubusercontent.com/assets/5578559/6879397/6396360e-d4ca-11e4-808c-e6caa586dc04.png)

**Comment by JoeBruner** [comment]
Then I changed `q = t` to `q := t` and about 25 seconds later it finally figures out that it's legit.

**Comment by ignatov** [comment]
Please reopen if needed.
