### ISSUE TITLE
Feature request: make "file_name:line_number" references in run output clickable

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1495]
Log package allows to include file names and line numbers in log output:
```go
var DebugLog *log.Logger = log.New(os.Stdout, "", log.Lmicroseconds|log.Lshortfile)
```
And this produces output like this:
![screenshot - 280315 - 13 59 35](https://cloud.githubusercontent.com/assets/4119321/6880973/c7df699a-d552-11e4-9fab-a1a975ccc93c.png)

It would be really nice to make reference to ```file:line``` clickable, so clicking on ```tcp-server.go:30``` would open the file ```tcp-server.go``` and place caret on line 30.

**Comment by dlsniper** [comment]
@zolotov I might do it in a few days if you don't have time until then

**Comment by JoeBruner** [comment]
:thumbsup:

**Comment by zolotov** [comment]
Will implement for Llongfile. Lshortfile is questionable, what directory I should use to look for a file? At the moment "link-maker" uses working directory of running process, gopath entries and project basedir for that.

**Comment by dlsniper** [comment]
Unless there's a very simple way to display all the files with the same name as the one in the output in a list, I'd say try current dir and if not, don't link the file.

**Comment by zolotov** [comment]
>  I'd say try current dir and if not, don't link the file.

It will work. Files that exists in working directory of running process, gopath entries and project basedir will be highlighted
