### ISSUE TITLE
Better run configuration description for running a project for the first time

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1498]
Hi,

As I'm starting to slowly migrate my habit of running the programs I'm writing from the console to the IDE, I've noticed something that I think the plugin should address a bit better.
When I tried to run the source code, I've got two different options: what appeared to be the file and the other one to be the file again, but this time with a Run in front of it. For me that was confusing quite a bit (I don't remember what I've chose but I did it and it worked, which was good enough) but I think I'm not the only one to be confused by this and for new users there should be a better onboarding experience.
What do you guys think?

![snapshot29](https://cloud.githubusercontent.com/assets/607868/6885590/c08c0368-d626-11e4-84cc-daf18960b5de.png)

**Comment by zolotov** [comment]
You've created two run configuration, what's the problem of plugin?

**Comment by dlsniper** [comment]
I'll show a dialog on a fresh project if it helps but the "output" will be the same as in the screenshot. On a fresh project, when you go to ``` Run | Run ``` you are still greeted with two different run configs.

**Comment by zolotov** [comment]
Stil don't understand what do you mean.

**Comment by zolotov** [comment]
I've understood what do you mean :)

What about this?
![screenshot 2015-03-30 12 38 52](https://cloud.githubusercontent.com/assets/140920/6893955/da154192-d6d9-11e4-9806-ade9958321d4.png)

**Comment by dlsniper** [comment]
Hi, yes, that would be much better! Thank you.
