### ISSUE TITLE
Problem detecting types with casts

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1500]
https://play.golang.org/p/yd3yhaCNnj

try putting that code in the plugin. It fails to detect casts:

https://www.dropbox.com/s/qlx1fhrmt2qnnbl/Screenshot%202015-03-29%2015.41.59.png?dl=0

Code compiles fine.

**Comment by dlsniper** [comment]
Thanks for reporting.

There's something interesting that happens, if the code is changed to this:

```go
package main

import "fmt"

type T1 string
type T2 T1
type T3 []T1
type T4 T3

func main() {
    var t3 T3 = []T1{"a", "b"}
    fmt.Println("t3='%+v'", t3)
    // var t4 T4 = []string{}
    // cannot use []string literal (type []string) as type T4 in assignment
    var t4 T4 = T4(t3)
    fmt.Println("t4='%+v'", t4)
    t4 = []T1{T1("c"), T1("d")}
    fmt.Println("t4='%+v'", t4)
}
```

Things work again properly.

**Comment by aubble** [comment]
Well hope it gets fixed soon xD thanks
