### ISSUE TITLE
Plugin doesn't autocomplete fsnotify.v1

### ISSUE THREAD

**Issue by omribahumi** [go-lang-plugin-org/go-lang-idea-plugin#1501]
I just installed Intellij IDEA 14.1 with Go plugin 0.9.223.
When using the following code:
```
package main

import (
    "gopkg.in/fsnotify.v1"
)

func main() {
	watcher, _ := fsnotify.NewWatcher()
}
```

Entering `watcher.` inside `main` doesn't list possible function calls

**Comment by dlsniper** [comment]
How did you configured the sdk and go libraries?

**Comment by omribahumi** [comment]
@dlsniper just the automated configurations. Anything you would like to know in particular?
Did you successfully reproduce it?

**Comment by zolotov** [comment]
Actually I can't recreate this.

![screenshot 2015-03-30 12 02 03](https://cloud.githubusercontent.com/assets/140920/6893311/992d9774-d6d4-11e4-8930-e3077673be1c.png)

**Comment by zolotov** [comment]
Is "import gopkg.in/fsnotify.v1" resolved (it's red if not)?

**Comment by omribahumi** [comment]
The `NewWatcher()` works. What happens if you do `watcher.` in the next line?
And the import is resolved.

**Comment by omribahumi** [comment]
![image](https://cloud.githubusercontent.com/assets/2558457/6893819/d6253a8e-d6d8-11e4-8c88-78d5aaabc38e.png)

**Comment by zolotov** [comment]
First of all, set project SDK, there is a link to configure on the top of editor.

If it doesn't help there are two variants. You haven't installed fsnotify.v1 or installed package is not in IDE's GOPATH.
To fix the first one just place caret in red import, invoke Alt+Enter and choose `go get`.
To fix the second one, check that there is appropriate GOPATH in Settings | Languages & Frameworks | Go Libraries.

**Comment by dlsniper** [comment]
Are you coming from 0.9.16 or earlier version of the plugin?

**Comment by omribahumi** [comment]
@dlsniper yes I am. I installed the stable version before this one.

**Comment by dlsniper** [comment]
Hmmm, I need to better document this case.
Please remove follow the plugin instructions, they should work even in this
case. You need to remove the old (plugin?) and sdk and follow the guidance
from the plugin afterwards.

**Comment by omribahumi** [comment]
Steps to reproduce:

With a fresh IntelliJ installation (I deleted all `~/Library/*/IdeaIC14` folders):
1. Press next until you get to the new project wizard
2. Click configure and follow the instructions to install the `alpha` plugin from [here](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md)
3. Create a new Go project (configure the SDK)
4. Configure an empty directory as `GOPATH` (Settings -> Languages & Frameworks -> Go Libraries -> Project libraries)
4. Create a `main.go` file
5. Paste this code in (from the example [here](https://github.com/go-yaml/yaml)):
```go
package main

import (
        "fmt"
        "log"

        "gopkg.in/yaml.v2"
)

var data = `
a: Easy!
b:
  c: 2
  d: [3, 4]
`

type T struct {
        A string
        B struct{C int; D []int ",flow"}
}

func main() {
        t := T{}

        err := yaml.Unmarshal([]byte(data), &t)
        if err != nil {
                log.Fatalf("error: %v", err)
        }
        fmt.Printf("--- t:\n%v\n\n", t)

        d, err := yaml.Marshal(&t)
        if err != nil {
                log.Fatalf("error: %v", err)
        }
        fmt.Printf("--- t dump:\n%s\n\n", string(d))

        m := make(map[interface{}]interface{})

        err = yaml.Unmarshal([]byte(data), &m)
        if err != nil {
                log.Fatalf("error: %v", err)
        }
        fmt.Printf("--- m:\n%v\n\n", m)

        d, err = yaml.Marshal(&m)
        if err != nil {
                log.Fatalf("error: %v", err)
        }
        fmt.Printf("--- m dump:\n%s\n\n", string(d))
}
```
6. Move your cursor to `"gopkg.in/yaml.v2"` import, <alt>+<enter> on it (on OSX), go get the `yaml.v2` package
7. Right under `err := yaml.Unmarshal([]byte(data), &t)`, type `yaml.`

![image](https://cloud.githubusercontent.com/assets/2558457/6897651/a5043494-d6fd-11e4-800b-940ae1a81b88.png)

**Comment by zolotov** [comment]
You can't set empty directory as GOPATH. The directory should corresponds [go workspace](https://golang.org/doc/code.html). At least it should contains `src` directory, otherwise it will be ignored and won't be passed to `go get` execution.

**Comment by omribahumi** [comment]
@zolotov it created the `src` after the first `go get`. It's ok.
I'll upload a screenshot tomorrow. Thanks!

**Comment by zolotov** [comment]
any news on it?

**Comment by omribahumi** [comment]
![image](https://cloud.githubusercontent.com/assets/2558457/6962578/5461ea20-d93e-11e4-9f7b-8f30e1e4f027.png)

**Comment by zolotov** [comment]
It's red, so something wrong with it. Are you sure that the directory exists?

**Comment by omribahumi** [comment]
@zolotov I tried playing with it and left it as `gopath2`, tuning it back to `gopath` solved the problem.
I think the problem was old plugin data after the upgrade (or even a duplicate of the two plugins)
Fresh install of the current alpha version with a _right_ gopath seems to work.

Thanks and sorry for the trouble

**Comment by zolotov** [comment]
Thanks for feedback. I think we should do something for painless migration on alpha version.

**Comment by omribahumi** [comment]
+1
