### ISSUE TITLE
, at the end of receiver

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1503]
In this piece of code: https://play.golang.org/p/qpCPe2BCsR

https://www.dropbox.com/s/0gs8dgue0ab55kd/Screenshot%202015-03-30%2014.09.51.png?dl=0

On line 24, the int part of "d.int" has no color. I think it should :D. Another more real problem is that notice at the top, line 8, I have a comma after "func (ds *dasa" This screws everything up, it is valid go syntax but the plugin doesn't recognize it and flags it. It works fine for parameter list and return list, but not for the receiver.

**Comment by zolotov** [comment]
Please specify plugin version

**Comment by aubble** [comment]
Latest alpha from the channel. 0.9.223
