### ISSUE TITLE
auto-importing for packages doesn't keep track of existing packages

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1511]
I'm yet to be very sure when this issue happens but I've find it quite a few times now when I find myself seeing 2 to 5 or more copies of the same package being added to the imports list automatically.

```go
package main

import "log/syslog"

func main() {
	syslog.New(1, "a")
	syslog.LOG_ALERT
	sysl<caret> -> select syslog.NewWriter() from the suggestion list
}
```

Commit: 502f466236f8cb6aec7bd68403c2664fcaae4e3f

**Comment by dlsniper** [comment]
I've updated the description to reflect the way to reproduce the issue. Please let me know if it's clear on how to do it. Thank you.

**Comment by bronze1man** [comment]
It seems I had faced a issues that looks like this Monday.
Sorry,I can not reproduce it again.
