### ISSUE TITLE
Cannot run application in latest nightly build

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1514]
It works fine in alpha. What happens in nightly when I try to run is that instead of looking at my file specified in the Go Application build setting thing, it looks at the working directory, doesn't find any files and gives me a error?

Alpha:
https://www.dropbox.com/s/tbfsx6cqgwhz3pd/Screenshot%202015-04-01%2010.03.46.png?dl=0 

Nightly:
https://www.dropbox.com/s/lvev3znoe3m6azz/Screenshot%202015-04-01%2010.06.19.png?dl=0

The folder it mentions is my working directory: https://www.dropbox.com/s/x5ief9mnx3dkzde/Screenshot%202015-04-01%2010.06.36.png?dl=0

I have the file specified there. Everything works perfectly fine with the alpha, but not the nightly?

**Comment by aubble** [comment]
Oh, to add, if I do make the working directory, the directory of the file it works fine?

**Comment by zolotov** [comment]
Oops, will be fixed in the next build. Thank you.
