### ISSUE TITLE
Can't specify a relative path?

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1515]
https://www.dropbox.com/s/lxv1fs148jimwtz/Screenshot%202015-04-01%2010.07.48.png?dl=0

That file is inside of my working directory but I have to use the full path? When I used to use java in intellij I believe I could use the relative path from my working directory?

**Comment by zolotov** [comment]
> When I used to use java in intellij I believe I could use the relative path from my working directory?

No, when you use java, you're using class, not file.

Well, it makes sense, but has quite minor priority to me. Feel free to contribute if you want (see GoRunConfigurationEditorForm and GoRunConfigurationWithMain).

**Comment by zolotov** [comment]
Fixed by @azhidkov
