### ISSUE TITLE
Unknown field for embedded structs if they are from another package

### ISSUE THREAD

**Issue by jgroeneveld** [go-lang-plugin-org/go-lang-idea-plugin#1516]
IDE: Intellij CE 14.1 March, 23
Plugin: 0.9.223 from repo

Embedded structs from other packages are marked as unknown. Structs from the same package work as expected.

```go
// wuff/wuff.go
package wuff

type Inner struct {
	Foo string
}
```

```go
// miau/miau.go
package miau

import "[...]/wuff"

type Outer struct {
	*wuff.Inner
	*MyInner
	Bar string
}

type MyInner struct {
}

func DoStuff() {
	_ = &Outer{
		Inner: &wuff.Inner{ // <-------- "unknown field 'Inner' in struct literal"
			Foo: "hi",
		},
		MyInner: &MyInner{},
		Bar: "World",
	}
}
```

**Comment by akaspin** [comment]
Bump

**Comment by dlsniper** [comment]
@akaspin we're gladly accepting contributions, thank you for asking. Please find out more on how to contribute by reading this: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md Thank you for offering to bump the contributors numbers :)
