### ISSUE TITLE
Broken run configuration

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1517]
Run/Debug configuration stopped working:
![screenshot - 010415 - 20 10 12](https://cloud.githubusercontent.com/assets/4119321/6946858/bd894630-d8ab-11e4-8e04-57a2a48c9785.png)

Looks like command line arguments are all mixed up.

IDEA 14.1.1
Plugin 0.9.242

**Comment by aubble** [comment]
Just update to the new version, I already complained about it and they fixed it :D

Reload the plugins in the nightly repo and just click update.

**Comment by dmitry-vovk** [comment]
Both "Go Application" and "Go Single File" are broken if "Program arguments" is set. If it is left empty, runs as usual.

**Comment by dlsniper** [comment]
@zolotov I'll submit a patch for this shortly.
