### ISSUE TITLE
Updating IntelliJ version automatically

### ISSUE THREAD

**Issue by juddernaught** [go-lang-plugin-org/go-lang-idea-plugin#1518]
By pointing IntelliJ to https://plugins.jetbrains.com/plugins/alpha/list, will IntelliJ automatically update as a new alpha version is available? Just want to know how to keep my version updated to the latest. Thanks!

**Comment by dlsniper** [comment]
By reading the readme you can do that https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds :)

**Comment by juddernaught** [comment]
Thanks for responding so fast! I followed the steps on that readme and have installed version 2.3.0, but my IntelliJ hasn't automatically updated to the current version. Any ideas?

**Comment by dlsniper** [comment]
As you've selected the alpha channel, as mentioned in the readme, you'll get updates to the plugin about once a week (maybe less). Nightly is updated every night, but it might increase chances for bugs.
Also, I can see 0.9.223 in the alpha channel, I have no clue how you see 2.3.0 (there's not even a 1.0 release yet :D)

**Comment by juddernaught** [comment]
Apologies, I meant version 0.9.230 as the version it shows under my installed plugins, but if I click on browse repositories, and select the repository pointing to https://plugins.jetbrains.com/plugins/alpha/list, it shows version 0.9.223, as it should. I wanted to make sure I am still using the alpha version, even though it shows version 0.9.230 when I select the Go plugin that I installed.

**Comment by dlsniper** [comment]
did you at any point added the nightly channel then removed it? Other than that, the only other issue I can think of is a rollback but for that either Sergey or Alexander should confirm. I can't really help with that as I'm compiling the plugin manually, sorry :)

**Comment by juddernaught** [comment]
I'm certain I never used the nightly because I did this with two other team members. We all seem to be showing a nightly version under our installed plugins and a lower alpha version when clicking on browse repository. One of us did it at a different time and are showing an even later version of 0.9.244 (I'm not positive on the exact number but think it was that) and the other two of us are showing 0.9.230 on our installed plugins.

**Comment by dlsniper** [comment]
0.9.244 is the latest nightly. Which IDEA / other IDE version are you using?

**Comment by dlsniper** [comment]
I've just checked, 0.9.220 is the last version for IntelliJ platform < 141.2 (aka IntelliJ IDEA 14.0.x). Are you sure it's not not 0.9.220 the version that you are seeing?
