### ISSUE TITLE
update through alpha channel doesn't work

### ISSUE THREAD

**Issue by Kane-Sendgrid** [go-lang-plugin-org/go-lang-idea-plugin#1519]
When trying to install from here: alpha: https://plugins.jetbrains.com/plugins/alpha/list
Idea says 404 not found

**Comment by dlsniper** [comment]
Please read the readme which states for which versions of IDEA / other IDEs this plugin currently works https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

As a tip, it works for all IDEs that have the plaform version 141.2 or greater
