### ISSUE TITLE
Allow running projects composed of multiple files

### ISSUE THREAD

**Issue by ltzMaxwell** [go-lang-plugin-org/go-lang-idea-plugin#1520]
for instance:
I can run in terminal like this : go run test0.go test1.go
How can I run this in Idea ?

**Comment by zafayar** [comment]
This bug makes this plugin completely useless.

**Comment by zafayar** [comment]
As an addition, when I try to run the project, the command executed is: 

``` /usr/local/go/bin/go build -o /tmp/run6go /home/niral/go/src/xxx/main.go ```

and because this project has more files, I get bunch of 'undefined' errors.  I get the same error if I do "go build main.go".

**Comment by zolotov** [comment]
@ltzMaxwell it's not possible via UI yet. How do you think it should looks like? You can try to configure Go Application configuration that uses `go build` instead. 

> @zafayar This bug makes this plugin completely useless.

Seriously? Running application is the only reason why you use IDE? Anyway see #1414 and #1413 discussions, you have a chance to be the first who will invent the solution and make plugin `usable`.

**Comment by dlsniper** [comment]
@zolotov for running a project composed of multiple files, would it be possible to have a "Go Multiple File" runner with an interface that lets you choose which files from the project to run?

Another option would be to provide an option to allow the IDE to create a list of all files that are in the same directory as the file that contains "func main()" and invoke go tool with that list (same should happen for running _test.go files)

What do you think?

**Comment by ltzMaxwell** [comment]
@zolotov How can I set go build in configuration?, in 'before launch ,go command'? It seems not work.

**Comment by dlsniper** [comment]
@ltzMaxwell ```Run | Edit Configurations | + | Go Application```

**Comment by ltzMaxwell** [comment]
@dlsniper  and then?

**Comment by dlsniper** [comment]
Then you can configure the runner and that will run a ```go build``` command instead of ```go run```

**Comment by landaire** [comment]
I'm having this issue myself. If you *really* want to run an application from within the IDE you can set the path to the package import path ([example](http://i.imgur.com/xNWC9yb.png)), hit run, you'll get an error window, continue anyways, then hit run again and all will work as expected.

**Comment by kiryaka** [comment]
@dlsniper can you please be more specific about "configure the runner and that will run a go build command instead of go run". [here](https://www.dropbox.com/s/fhpnwyim7lpbz7h/Screenshot%202015-04-09%2020.08.33.png?dl=0) is the new configuration -> Go Application. What next? I'm using go build && app_name from the terminal view right now and it is annoying.

**Comment by dlsniper** [comment]
@kiryaka from your screenshot I can see an error, you need to specify the main file. Also, if your project has multiple files in the main package, things won't work. See Alexanders' comment for why this is not supported (yet). We gladly welcome contributions.

**Comment by kiryaka** [comment]
I need to do *go build* on the directory and then run the binary. What main.go can do with it? I can put it there. It will to run it and exit with error, because the application have way more files then just main.go How to include other files?

**Comment by dlsniper** [comment]
I'm really not sure what's so unclear. You cannot do that yet. The original poster asked where he can run go build, I pointed him there, there was no mention that you can run / compile multiple files.

**Comment by kiryaka** [comment]
It's actually still unclear for me from your replies where to run "go build" on the directory. But anyhow, if the feature allowing to build and run the whole project from run configuration is not ready yet, then just consider my posts as +1 to this feature request :) Thank you.

**Comment by M-Gray** [comment]
I've been using a "make" file for building multiple files. Make sure the working directory includes your source code. https://github.com/M-Gray/IdeaJGO/blob/master/make.go

**Comment by lukamicoder** [comment]
Do I understand it correctly? Currently a project like this cannot be compiled and run with this extension: https://github.com/rapidloop/rtop 
LiteIDE can build and run projects like this with no problem. Isn’t it a perfectly valid way to organize code? How should then the code be organized so that this extension can build it?

**Comment by dlsniper** [comment]
That's correct. Currently there's no multiple file/directory runner support in the plugins so you would have to launch the application manually from the terminal. 
As for how should the code be structured? It shouldn't contain multiple go files in the same folder as `main()`.

**Comment by dlsniper** [comment]
Also, IDEA provides a builtin terminal, which isn't exactly a one button command, it will still allow users to stay within the IDE while working.

**Comment by zolotov** [comment]
> Do I understand it correctly? Currently a project like this cannot be compiled and run with this extension: https://github.com/rapidloop/rtop 

@lukamicoder no, it's not correct. Besides bulitin terminal you also can just open project and invoke run action from UI, it will work.
<img width="956" alt="screenshot 2015-09-17 10 54 37" src="https://cloud.githubusercontent.com/assets/140920/9935002/ba33b6c4-5d2a-11e5-8f27-2a17e0b9671e.png">
<img width="1183" alt="screenshot 2015-09-17 10 54 51" src="https://cloud.githubusercontent.com/assets/140920/9935006/bededbae-5d2a-11e5-8b45-ab118859079b.png">

**Comment by lukamicoder** [comment]
Awesome, thank you guys for your help!

**Comment by dlsniper** [comment]
> @lukamicoder no, it's not correct. Besides bulitin terminal you also can just open project and invoke run action from UI, it will work.

@zolotov I think I need to learn how to use the plugin, sorry for bad intel :D

**Comment by dlsniper** [comment]
@zolotov I think this can be closed now as `go build` supports running a directory. Or am I missing something in this sea of comments (in which case I vote for closing this and waiting for someone else to open a new ticket?)

**Comment by zolotov** [comment]
@dlsniper agree
