### ISSUE TITLE
Unresolved reference issue

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1523]
This code compiles:
```go
type RateHistoryResponse struct {}
type RateHistoryResponses []RateHistoryResponse

func (r *RateHistoryResponses) persist() {
	for _, rh := range []RateHistoryResponse(*r) {
		rh.persist() // Unresolved reference 'persist'
	}
}

func (r *RateHistoryResponse) persist() {
	// ...
}
```
But gives "Unresolved reference 'persist'" in IDE

IDEA 14.1.1
Plugin 0.9.244

**Comment by imikushin** [comment]
I'm seeing Unresolved references all over. Is this the same or a new bug?

```go
type Project struct {
	Name string
	// skip
}

func (p *Project) Up() error {
	wrappers := make(map[string]*ServiceWrapper) // 'wrappers' is reported as "Unused variable" although highlighted both usages (here and on the next line) :)
	return p.startAll(wrappers) // 'startAll' reported as "Unresolved reference"
}

func (p *Project) startAll(wrappers map[string]*ServiceWrapper) error {
	// skip
}
```

**Comment by imikushin** [comment]
IDEA-14.1.2, plugin 0.9.291

**Comment by ignatov** [comment]
Please create another issue.

**Comment by dlsniper** [comment]
@imikushin I'd suggest opening a new issue as and provide a bit more details as I can't replicate the issue, see my screenshot:

![snapshot65](https://cloud.githubusercontent.com/assets/607868/7371368/bf470000-edc0-11e4-91ed-6e242f9635d8.png)

Are is the ```Go Libraries``` section configured properly? I'm running on the latest master but I don't think it's that mach of a difference.

**Comment by imikushin** [comment]
@dlsniper Turns out, I've misconfigured my project. I have `Godeps/_workspace/src` dir with dependencies. And though I have `Godeps/_workspace` in my project's Go Libraries, I also had this folder marked as excluded. Now, after unmarking it as excluded everything looks great. Thanks!

(I'm probably sounding like an idiot, but that's okay). Lesson learned: don't mark your Godeps or gopath as excluded
