### ISSUE TITLE
Test runner should display test names

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1528]
It would be nice if the test runner could display the test names as they happen. We could then correlate those with the test functions we have in the project.

For example:
```
go test -v github.com/labstack/echo
=== RUN TestContext
2015/04/03 14:14:19 echo: response already committed
--- PASS: TestContext (0.00s)
=== RUN TestEchoMaxParam
--- PASS: TestEchoMaxParam (0.00s)
=== RUN TestEchoIndex
--- PASS: TestEchoIndex (0.01s)
=== RUN TestEchoStatic
--- PASS: TestEchoStatic (0.00s)
=== RUN TestEchoMiddleware
--- PASS: TestEchoMiddleware (0.00s)
=== RUN TestEchoHandler
--- PASS: TestEchoHandler (0.00s)
=== RUN TestEchoSubGroup
--- PASS: TestEchoSubGroup (0.00s)
=== RUN TestEchoMethod
--- PASS: TestEchoMethod (0.00s)
=== RUN TestEchoServeHTTP
--- PASS: TestEchoServeHTTP (0.00s)
=== RUN TestResponse
--- PASS: TestResponse (0.00s)
=== RUN TestRouterStatic
--- PASS: TestRouterStatic (0.00s)
=== RUN TestRouterParam
--- PASS: TestRouterParam (0.00s)
=== RUN TestRouterCatchAll
--- PASS: TestRouterCatchAll (0.00s)
=== RUN TestRouterMicroParam
--- PASS: TestRouterMicroParam (0.00s)
PASS
ok      github.com/labstack/echo        0.017s
```

**Comment by zolotov** [comment]
didn't understand the issue

**Comment by dlsniper** [comment]
When running the tests on the package ```github.com/labstack/echo```, you'll get the output of the tests and the following two lines: 
```
=== RUN TestFunctionNameHere
--- PASS: TestFunctionNameHere (duration)
```

It would be nice if the test runner could parse the output, extract the test name, ```TestFunctionNameHere``` and then check for each test if there's a line with ```---STATE: TestFunctionNameHere```` where STATE is one of the following: ```PASS```, ```SKIP```, ```FAIL``` (for fail state we should include ```PANIC``` and ```MISS```)

Ideally, the test runner window should show the results / test function just like the Java test runner does it.

I hope the description is a bit better now.

**Comment by zolotov** [comment]
It works for couple month

![screenshot 2015-04-03 17 41 51](https://cloud.githubusercontent.com/assets/140920/6983621/bb52ce1c-da28-11e4-9519-55be539d1d5f.png)

**Comment by dlsniper** [comment]
Then I either do something wrong for the said project or there's something that breaks the test runner because I've never got any test names there.

![snapshot32](https://cloud.githubusercontent.com/assets/607868/6983902/4728188a-da23-11e4-924b-92c3d7a87f21.png)

I'll try to investigate the issue as well in the weekend. Thank you

**Comment by zolotov** [comment]
You have enabled test filter: only failed tests is shown.

![screenshot 2015-04-03 18 08 16](https://cloud.githubusercontent.com/assets/140920/6983955/72555bd6-da2c-11e4-8248-efc69680101a.png)

**Comment by dlsniper** [comment]
I need to learn to use the IDE... thank you
