### ISSUE TITLE
Feature request: Replace built-in go fmt with goimports

### ISSUE THREAD

**Issue by jbuberel** [go-lang-plugin-org/go-lang-idea-plugin#1529]
Consider using the 'goimports' tool as a drop-in replacement for 'go fmt'.
http://golang.org/x/tools/cmd/goimports

In addition to code reformatting, it will also fix common import problems, such as missing or unused imports. It is maintained by the core Go team, and works across all Go platforms.

**Comment by dlsniper** [comment]
Hi, I'll address this in order:
- the platform takes care already of the missing imports as you write the code, which is far better that what goimports 
- support for removing unused imports is yet to be done, I'm not sure if there's an easy way to have it done
- formatting code has been debated and it's much better to have the platform do the formatting rather that use an external tool.

However, until the plugin gets the formatting engine done, you can still use goimports from the ```Code | Go fmt file / Go fmt project / Goimports file``` options, as well as a precommit hook with go fmt, If you'd like to add a goimports precommit hook, please feel free to send a PR, we'll gladly accept it.

I'll close this for now as it's already a duplicate feature request and the reminder of the problems are known.

**Comment by zolotov** [comment]
> support for removing unused imports is yet to be done, I'm not sure if there's an easy way to have it done

It implemented long time ago: Code | Optimize imports or Code | Reformat code

**Comment by dlsniper** [comment]
Sorry, I mean it to be automatic, without invoking the command specifically.

**Comment by zolotov** [comment]
#1268
