### ISSUE TITLE
Performance issue with nested functions

### ISSUE THREAD

**Issue by ukautz** [go-lang-plugin-org/go-lang-idea-plugin#1530]
Using [Goconvey](http://goconvey.co/) quite a lot I noticed that the performance degrades measurable when nesting (multiple) functions: On saving a file with (deeply) nested functions a single CPU core is bumped to 100% usage for a couple of seconds (feels geometrically'ish proportional to the nesting depths). 

An (extreme) example project to reproduce the issue (works on my two machines (i7-3770 w/ 16GB RAM, i3-something w/ 8GB RAM, both Ubuntu 14.04)) can be found here: https://github.com/ukautz/go-ide-performance

I think this is not the same issue as #1493, but I could be wrong.

**Comment by ignatov** [comment]
Thanks for reporting.
