### ISSUE TITLE
Issue with literal maps

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1532]
```go
package main

import (
	"fmt"
	"log"
	"strings"
)

func main() {
	if val, err := ValidName("basic"); err != nil {
		log.Fatalf("Not valid: %s", err)
	} else {
		log.Printf("Valid: %s", val)
	}
}

func ValidName(name string) (string, error) {
	if kind, ok := map[string]string{
		"basic":  "Basic",
		"active": "Active",
	}[strings.ToLower(name)]; ok {
		return kind, nil
	} else {
		return "", fmt.Errorf("Invalid name: %s", name)
	}
}
```
Valid and compiling code (https://play.golang.org/p/cX966bbUwg), but first two lines of ```ValidName``` func are marked as "Missing return at end of function" and "Unused variable kind".

IDEA 14.1.1
Plugin 0.9.251 (and 0.9.250)

**Comment by dlsniper** [comment]
The actual error is on line 21, ```}[strings.ToLower(name)]; ok {``` before ```; ok``` with the value ``` const,func,type or var expected, got ; ```
