### ISSUE TITLE
struct field name completion doesnt seem to work

### ISSUE THREAD

**Issue by sclasen** [go-lang-plugin-org/go-lang-idea-plugin#1533]
@dlsniper do these illustrate the issue enough?

![image](https://cloud.githubusercontent.com/assets/523338/7013017/b86de8d2-dc6a-11e4-8190-bc38eed9ad03.png)

![image](https://cloud.githubusercontent.com/assets/523338/7013039/dfd58240-dc6a-11e4-98dc-d08d1ca92f81.png)

I would expect a popup with 

```
Name string
NotName int
Truthy bool
```

thats how 0.9 worked anyhow

```go
package demo

type CompleteMe struct {
	Name string
	NotName int
	Truthy bool
}

var completeMe = CompleteMe {

}

func inFunc() {
	completed := CompleteMe{

	}
}
```

**Comment by sclasen** [comment]
similar behavior with stdlib structs and library structs too

**Comment by dlsniper** [comment]
Strangely enough, this works on my machine, please see below:
![snapshot33](https://cloud.githubusercontent.com/assets/607868/7013154/565d0b1c-dcb7-11e4-8c7e-ea3632989198.png)

![snapshot34](https://cloud.githubusercontent.com/assets/607868/7013155/56619aa6-dcb7-11e4-8a2a-c41d172a0821.png)

(I've updated the issue to contain the go code I'm using, it should be the same as in your example)

**Comment by dlsniper** [comment]
@sclasen is your project in the Go libraries paths? It's about the only thing that I can think of right now for this not to work. I'm using a build of the plugin from master (commit 7192e5a7a1a0824dfea50fba66efa8665dee19a0) but I don't think it should be a problem vs the alpha / nightly builds. Have you tried typing the first 1-2 letters (sorry if it seems silly)? Thank you.

Also, here's what I have in the Code Completion settings from the IDE itself, maybe it helps.
![snapshot35](https://cloud.githubusercontent.com/assets/607868/7013326/77b2852a-dcb8-11e4-9c58-ab37f8a371a6.png)

@ignatov, a bit of topic but maybe a higher completion priority could be given to the struct fields that the rest of the variants?

**Comment by sclasen** [comment]
![image](https://cloud.githubusercontent.com/assets/523338/7013432/fbf7a856-dc6d-11e4-980a-dd3674f116a5.png)

![image](https://cloud.githubusercontent.com/assets/523338/7013435/09f57398-dc6e-11e4-81b9-955d3d372726.png)

similar lists with `Na<aoutcomplete>`


This is on OSX btw, if that makes a difference. You look like you are on linux @dlsniper 

The libraries in question are all in the project.  The only difference in my code completion settings was autopop documentation and show full signatures were disabled. I enabled that and see the same behavior.

**Comment by dlsniper** [comment]
Unfortunately I have to leave this to Sergey as I can't figure out why the problem could happen. The OS definitely shouldn't be a problem. Thanks once again for reporting.

**Comment by sclasen** [comment]
Thanks @dlsniper, and everyone who works on this project!

**Comment by JoeBruner** [comment]
@sclasen , I'm using Ubuntu, but I noticed that this feature did not work as of build 201, but it apprears to be working as of 250.  I believe there was an issue to fix this, but don't know the number or status off the top of my head.

**Comment by sclasen** [comment]
@JoeBruner this one? https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1162  

If so, I am using a build that supposedly has this fix, yet still exhibits the symptoms I screenshotted.

**Comment by sclasen** [comment]
Ooh! I do have 201 though.   The alpha repo is timing out for me. I will try and test once I can get a list.

**Comment by dlsniper** [comment]
@sclasen make sure you are using IDEA 14.1+ and the nightly / alpha repositories should work for you. Thank you.

**Comment by JoeBruner** [comment]
Yah, I didn't realize that you needed 14.1.  I was trying with 14.0.x and
it wasn't updating.  I just updated my version to 14.1 today and it
upgraded my plugin.

**Comment by sclasen** [comment]
Woo!  250 works for me!

**Comment by sclasen** [comment]
fixed in 250
