### ISSUE TITLE
Coloring Issues

### ISSUE THREAD

**Issue by nhooyr** [go-lang-plugin-org/go-lang-idea-plugin#1534]
https://www.dropbox.com/s/d7jaqqxv7twfw6t/Screenshot%202015-04-06%2019.57.25.png?dl=0

In that code, in the struct literal, var1 should be highlighted just as it is in the println statement no? It is treated as simply an identifier in the colors and fonts list for go.

Also, why are packages treated as identifiers as well? Should they not have their own colors in the fonts and colors tab? I haven't done any real investigation but I would imagine there are perhaps more issues similar to this which should be resolved. But really, awesome plugin so far!

**Comment by dlsniper** [comment]
Thanks for reporting.

@ignatov I can work on this but I'd like to understand why the PSI tree has different values for the two fields.

```go
package main

type type1 struct {
	var1 int
	var2 int
	string1 int
}

func main() {
	struct1 := type1{var1: 1} // var1 is FIELD_NAME here
	println(struct1.var2) // var2 is REFERENCE_EXPRESSION here
	println(struct1)
}
```

![snapshot36](https://cloud.githubusercontent.com/assets/607868/7014870/f3d198dc-dcca-11e4-8ddc-f6dea7c52fd1.png)


Thank you!
