### ISSUE TITLE
Default Go project encoding windows-1252 instead of UTF-8?

### ISSUE THREAD

**Issue by johnleegrant** [go-lang-plugin-org/go-lang-idea-plugin#1537]
Creating a new Go project from File > New > Project... > Go... defaults to Windows-1252 encoding:

![image](https://cloud.githubusercontent.com/assets/5324735/7027541/f3c4af32-dd47-11e4-8081-b08fa7393c1a.png)

This means the following won't compile because of error: line 6: illegal UTF-8 sequence

```go
package main

import "fmt"

func main() {
    fmt.Println("More £ !")
}
```
Can everything be set to always default to UTF-8?

IDEA version: 14.1.1
OS version: Windows 8.1
Go version: go1.4.2 windows/amd64
Plugin version: 0.9.250

**Comment by zolotov** [comment]
Didn't get it. Why do you set windows-1252 if you know that it won't compile?

**Comment by johnleegrant** [comment]
Plugin version: 0.9.250 creates projects using windows-1252. There's no way to change the encoding during the initial wizard. If you forget to change to UTF-8 ( in File > Settings > Editor > File Encodings ) at the start you inevitably have to manually convert all your go files to UTF-8 when you hit an encoding problems with the compiler at a later stage.

My point is, the plugin should start with UTF-8 at project creation by default and not use windows-1252 for Go projects.

**Comment by zolotov** [comment]
I believe that go plugin has nothing to do with it. Try to close all projects and check encoding settings while none of project is opened, maybe you or some third-party plugin changed the default value.

**Comment by johnleegrant** [comment]
My apology. OK, you have to configure IDEA to use a specific encoding before you start with Go. Maybe the plugin could provide a warning if the global setting is not UTF-8 to prevent subsequent build problems? The Go spec does state that source code should be Unicode text encoded in UTF-8 [golang.org/ref/spec#Source_code_representation](http://golang.org/ref/spec#Source_code_representation)

**Comment by zolotov** [comment]
Hmm, it makes sense. Actually I can forbid changing encoding for Go files, so despite of project settings it will be always UTF-8:
![screenshot 2015-04-07 20 19 58](https://cloud.githubusercontent.com/assets/140920/7029108/845b1bb0-dd63-11e4-9faf-b74d081a0608.png)

Do you think it's a good solution or someone may want to change the encoding for Go files?

**Comment by mtoader** [comment]
It has been like that since the first days. If you really are concerned with the changing it can be done as a customization option as: "Enforce UTF-8 for Go files". If set, which should be the default, will enforce it, it not set it will default to the normal behaviour. That way if the standard will ever change people will be able to tweak their local config to work. 

But also, this might be overkill :).

**Comment by johnleegrant** [comment]
For someone as forgetful as me, I think that's a great suggestion. I can't think why you would want to use anything other that UTF-8.

**Comment by zolotov** [comment]
> If you really are concerned with the changing it can be done as a customization option as: "Enforce UTF-8 for Go files".

The option is the last thing that I want to do :)
Ok, I'm going to do so for Go file types and will think about other solutions if someone will ask for it.
