### ISSUE TITLE
Performance test "testUnusedFunction" fails with RuntimeException

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1539]
Hi,

I've finally got around running the performance tests from the plugin, and one of them ended up in failure.
You can see the logs here: http://pastebin.com/mctdJBnN

Commit hash: 3fe5150f633206d7d8e7a3f960914fb7564ef800
Ubuntu 14:10
Docker: 1.5.0
IDEA: 141.498.1
Java:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Hope this helps.

**Comment by zolotov** [comment]
We know this and run performance tests regularly, it will be fixed when it will be fixed :)

**Comment by dlsniper** [comment]
Ah, ok, I thought it's something I've did wrong on my setup or something. Thank you.
