### ISSUE TITLE
[1.0] An embedded struct name is not recognized as a valid field name

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1546]
```go
import "net"

type MyConn struct {
	net.Conn
}

func Test(c net.Conn) *MyConn {
	return &MyConn{Conn: c}  // Error: "unknown field `Conn` in struct literal", but it is ok
}

```

**Comment by dlsniper** [comment]
Hi, at least in the example you are missing the quotes for import and I believe the right import should be: ```import "net"``` not ```import net.Conn```.
Did you took the example via copy&paste or you typed it in here?

**Comment by horkhe** [comment]
@dlsniper sure you are right. I fixed the example.

**Comment by dlsniper** [comment]
@horkhe cool, thanks. Which version of the plugin and IDE are you running? I can't replicate it with da79d7a823e1fee75c08b499b58d2ed6b72d4f66 (roughly equivalent to whatever it's the latest nightly)

**Comment by horkhe** [comment]
@dlsniper I am on d02c1cc of v1.0.0-alpha0 branch, and using Idea 14.1.1

**Comment by dlsniper** [comment]
Unless there's a really good reason to stay on that, I'd say it's safe to remove that version and use either the alpha or nightly channels. The info on how to do so is in the readme, https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by horkhe** [comment]
@dlsniper I used it since it was very different from master. But I see that the alfa branch has been merged to master so I am switching to master. You are right the master has the problem fixed. Thank you.

**Comment by dlsniper** [comment]
@horkhe that's good. Thanks for feedback ;)
