### ISSUE TITLE
Highlighting the package?

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1547]
Normally whenever I select a variable, all instances of the variable are highlighted.

https://www.dropbox.com/s/nbwef22vilbjdov/Screenshot%202015-04-09%2019.52.43.png?dl=0

My cursor is over the first var2 in the struct type definition. Doing so also highlights all the usages like in the println statement and the struct literal. Now this is all fine and dandy. The problem is doing the same with packages. 

https://www.dropbox.com/s/2zs1yk32bthdtkh/Screenshot%202015-04-09%2019.49.43.png?dl=0

Here I have my cursor over the "fmt" in the import statement. The problem is that all the other usages of fmt aren't highlighted. And they are all related because if I put my cursor of one of the fmt parts of the println statements, the "fmt" gets highlighted. 

https://www.dropbox.com/s/j3ut10ddunfds5z/Screenshot%202015-04-09%2019.51.35.png?dl=0

Notice how I have my cursor over the fmt in the println statements? It doesn't get highlighted but the "fmt" does in the import

**Comment by dlsniper** [comment]
I've put it to "1.0 maybe?" as it's rather an improvement / feature request than a bug imo.
If someone wants to take a stab at it, the sources for the highlighter can be found here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/tree/master/src/com/goide/highlighting It would be very much appreciated.

**Comment by ignatov** [comment]
`com.goide.util.GoUtil#couldBeReferenceTo`
