### ISSUE TITLE
Disable CGO inspection if import "C" is present

### ISSUE THREAD

**Issue by coocood** [go-lang-plugin-org/go-lang-idea-plugin#1548]
If ```import "C"``` is present, then all the references to ```C.``` should be ignored by the analysis engine.

```go
package main

/*
int one() {
    return 1;
}
*/
import "C"

import (
	"fmt"
)

func main() {
	fmt.Println(C.one()) // inspection reports 'unresolved reference'
}
```

**Comment by dlsniper** [comment]
I've changed a bit the wording in the description and hopefully assigned it to the right person :)

**Comment by ignatov** [comment]
Relates to #1260
