### ISSUE TITLE
Functions used from package main are not marked as in use

### ISSUE THREAD

**Issue by esiqveland** [go-lang-plugin-org/go-lang-idea-plugin#1550]
Example code:

IDE: WebStorm 10 WS-141.506
GO plugin: 0.9.250

```go
// $GOPATH/src/issue/main.go
package main

import "issue/ctx"

func main() {
	cx := ctx.NewContext() // Resolves correctly to c.NewContext() :-)
	_ = cx
}
```

```go
// $GOPATH/src/issue/ctx/context.go
package ctx

func NewContext() *Context { // this func is marked as not in use
	return &Context{}
}
type Context struct {}
```
A usage search for NewContext func usage, says no usage is found in project. 

Could be main package is not correctly identified as part of project?

**Comment by dlsniper** [comment]
I've checked with creating a different package in the same project and indeed it does seem that the example is valid. The inspections don't process ```package main``` as part of the package for some reason.

```go
// $GOPATH/src/issue/demo/demo.go
package demo

import "issue/ctx"

func hello() {
	cx := ctx.NewContext() // when this is present, NewContext() from ctx package is flagged as used
	_ = cx
}
```

**Comment by esiqveland** [comment]
Possibly related:

https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/206

**Comment by ignatov** [comment]
@zolotov Please check `GoFile#getImportedPackagesMap` cache dependencies and https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/util/GoUtil.java#L163-163
