### ISSUE TITLE
Intellij 14: homebrew install, can't recognize SDK

### ISSUE THREAD

**Issue by hufeng** [go-lang-plugin-org/go-lang-idea-plugin#1557]
λ ~GOROOT git:(master) ✗ ll
total 8
-rw-r--r--   1 bee1314  admin   273B Feb 28 12:28 INSTALL_RECEIPT.json
drwxr-xr-x   4 bee1314  admin   136B Jan 16 09:10 bin
drwxr-xr-x  20 bee1314  admin   680B Apr 15 17:31 libexec
λ ~GOROOT git:(master) ✗ pwd
/usr/local/Cellar/go/1.4.1
λ ~GOROOT git:(master) ✗ 

bin and libexec can't recognize sdk

**Comment by zolotov** [comment]
plugin version?

**Comment by zolotov** [comment]
also logs could be useful (Help | Show Log)

**Comment by hufeng** [comment]
@zolotov version: 0.9.15.3,  thank you!

**Comment by dlsniper** [comment]
@hufeng please install a newer version of the plugin by following the instructions from here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by hufeng** [comment]
@dlsniper thank you very much. let me try.
