### ISSUE TITLE
The selected directory is not a valid home for Go SDK on Fedora

### ISSUE THREAD

**Issue by hyt-hz** [go-lang-plugin-org/go-lang-idea-plugin#1559]
OS: fedora 21
intellij: 14.1.1
go plugin: 0.9.250

golang is installed vi yum:

    (1/4): golang-1.4.2-2.fc21.x86_64.rpm                       | 3.0 MB  00:04     
    (2/4): golang-pkg-bin-linux-amd64-1.4.2-2.fc21.x86_64.rpm   |  14 MB  00:06     
    (3/4): golang-pkg-linux-amd64-1.4.2-2.fc21.noarch.rpm       | 7.2 MB  00:02     
    (4/4): golang-src-1.4.2-2.fc21.noarch.rpm                   | 5.8 MB  00:02  

go version go1.4.2 linux/amd64

    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/usr/lib/golang"
    GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="1"

In "Select Home Directory for Go SDK", when I choose /usr/lib/golang,  it says
"The selected directory is not a valid home for Go SDK"

**Comment by dlsniper** [comment]
Hi @hyt-hz, thanks for reporting.
Can you please also do a ```ls -alh /usr/lib/golang```?

**Comment by zolotov** [comment]
duplicates #1558. @hyt-hz please try the workaround that I suggested there.

**Comment by hyt-hz** [comment]
@zolotov  Thanks, it works.

@dlsniper 
Here is the output:

ls -alh /usr/lib/golang
total 84K
drwxr-xr-x  10 root root 4.0K Apr 16 22:26 .
dr-xr-xr-x. 77 root root  36K Apr 16 22:26 ..
drwxr-xr-x   2 root root 4.0K Apr 16 22:26 api
drwxr-xr-x   3 root root 4.0K Apr 17 20:23 bin
drwxr-xr-x   8 root root 4.0K Apr 16 22:26 doc
-rw-r--r--   1 root root 1.2K Feb 18 12:38 favicon.ico
drwxr-xr-x   3 root root 4.0K Apr 16 22:26 include
drwxr-xr-x   2 root root 4.0K Mar 20 00:06 lib
drwxr-xr-x  12 root root 4.0K Apr 16 22:26 misc
drwxr-xr-x   5 root root 4.0K Apr 16 22:26 pkg
-rw-r--r--   1 root root   26 Feb 18 12:38 robots.txt
drwxr-xr-x  46 root root 4.0K Apr 16 22:26 src
