### ISSUE TITLE
Bug: private funcs and struct fields accessible in package_test test files

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#1560]
![screen shot 2015-04-16 at 8 07 41 pm](https://cloud.githubusercontent.com/assets/372027/7214836/428fba2e-e600-11e4-956c-42a917e16b8a.png)

![screen shot 2015-04-18 at 7 20 56 pm](https://cloud.githubusercontent.com/assets/372027/7214842/8eff9dde-e600-11e4-8f92-1ef71423a195.png)

Reproduceable:

file1:

```go
package intlbug

import "strings"

type MyPrivates struct {
	value1 int
	value2 string
}

func (p MyPrivates) AFunc() string {
	return strings.Repeat(p.value2, 2)
}
```

file2 is in the same package as file1:

```go
package intlbug_test

import (
	"testing"

	"intlbug"
)

func TestAFunc(t *testing.T) {
	mp := intlbug.MyPrivates{}
	mp.....
}
```

Expected result: I cannot access the fields of my privates :laughing:

Idea 14.1.1, go-lang-idea-plugin: latest commit from branch master. Runs on OSX latest.

Thanks for having a look into this!

**Comment by ignatov** [comment]
Thanks for reporting.

Sergey Ignatov

**Comment by ignatov** [comment]
Sorry, can't reproduce. Please attach a layout (output from `tree` util) or just a small project for reproducing.

**Comment by SchumacherFM** [comment]
Here is the repo: https://github.com/SchumacherFM/intellijGoPluginBug `go get github.com/SchumacherFM/intellijGoPluginBug`

It is still reproduceable.

**Comment by ignatov** [comment]
Thanks, http://linux.die.net/man/1/tree

**Comment by SchumacherFM** [comment]
Cool! Thanks a lot!
