### ISSUE TITLE
Rename function between package.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1565]
I have call a function from packageA in packageB.
I rename the name of function in the origin packageA.
The name of the function of Imported packageB is not changed.

**Comment by zolotov** [comment]
Can't recreate. Is packageB part of your project?

**Comment by dlsniper** [comment]
@bronze1man any updates on this? Thank you.

**Comment by bronze1man** [comment]
Sorry.I can not recreate it either.
