### ISSUE TITLE
compile error on system library code

### ISSUE THREAD

**Issue by yangzhe1991** [go-lang-plugin-org/go-lang-idea-plugin#1570]
hi, I use idea 14.1.1 and plugin 0.9.284, in my project, library by "go get" has no problem but system library(like package net/http ) will get error like this:

![2015-04-22 5 13 08](https://cloud.githubusercontent.com/assets/860739/7270980/e684397e-e912-11e4-8692-1414189b689a.png)

In this code, the variable err will be reported "unused variable err", and the function ParseForm won't be indexed so the code use this function in my project will report "unresolved reference ParseForm"

**Comment by ignatov** [comment]
Please provide a small code sample for reproducing. Thanks.

**Comment by yangzhe1991** [comment]
hi, in my project almost every sdk library has this compile error, so each code that use sdk library will reproduce this

**Comment by dlsniper** [comment]
Can you please post a screenshot of your Go SDK? ```File | Project Structure | Platform Settings / SDKs ``` select the Go SDK? Also, what plugin version do you use? What IDE / which version? How did you configured the Go SDK? How did you installed the Go SDK?

**Comment by ignatov** [comment]
OK, please specify the path of the file from your screenshot?

Sergey Ignatov

**Comment by yangzhe1991** [comment]
![2015-04-22 5 26 27](https://cloud.githubusercontent.com/assets/860739/7271270/cbfba8d8-e914-11e4-8458-ad34c516b7d9.png)
this sdk is installed by go1.4.2.darwin-amd64-osx10.8.pkg in https://golang.org/dl/

**Comment by yangzhe1991** [comment]
the sdk library screenshot file is /usr/local/go/src/net/http/request.go

**Comment by dlsniper** [comment]
And is the SDK attached to project? Can you find the net/http/request.go file there? You should see it in the "External Libraries" section of the "Project" tool window. 

![snapshot63](https://cloud.githubusercontent.com/assets/607868/7271388/611d808a-e8e3-11e4-85ef-614ab2b0531c.png)

And like @ignatov already said, can you try and replicate it on a smaller code sampler?

**Comment by yangzhe1991** [comment]
Oh, I tried to recreate this project and it is no problem now, maybe it is because that I created this project by an older plugin version months ago.
Thank you all, sorry for disturbing

**Comment by dlsniper** [comment]
Glad to hear it worked! Feel free to open up issues or ask on Gitter if you have any other problems in the future.
