### ISSUE TITLE
Feature: Generate interface from struct

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#1571]
and the other way round to issue #1568 :-)

I do not know Java ... so I'm aware that this feature may take some time.

I'm also aware of: https://medium.com/@rakyll/interface-pollution-in-go-7d58bccec275

**Comment by tejasmanohar** [comment]
https://github.com/vburenin/ifacemaker

**Comment by SchumacherFM** [comment]
stale - won't fix. There are other options ;-)

**Comment by dlsniper** [comment]
That is correct. It's implemented in GoLand, see https://www.jetbrains.com/help/go/extract-interface.html
