### ISSUE TITLE
Incorrectly flagging unused imports

### ISSUE THREAD

**Issue by diwakergupta** [go-lang-plugin-org/go-lang-idea-plugin#1572]
Plugin version: 0.9.250
Idea version: 14.1.2

The plugin is planning spurious imports as unused. E.g. in the following code fragment:

```go
import (
...
  "syscall"
)

...
func registerSignalHandler() {
	signal.Notify(server.stopChan, syscall.SIGUSR1)
	signal.Notify(server.stopChan, syscall.SIGTERM)
	signal.Notify(server.stopChan, syscall.SIGINT)
...
)
```

The plugin incorrectly flags `syscall` as unused. As it stands, the plugin is basically unusable for me due to all the spurious errors.

**Comment by zolotov** [comment]
Works fine for me on 0.9.300, please try it

**Comment by dlsniper** [comment]
@diwakergupta any news on this? I can't reproduce it either running the latest version. Please upgrade the plugin as described in the README and it should work properly. If not, feel free to reopen this. Thank you.
