### ISSUE TITLE
go compiler using wrong drive if project's drive != goSDK's drive

### ISSUE THREAD

**Issue by epixerion** [go-lang-plugin-org/go-lang-idea-plugin#1574]
Plugin version : 0.9.250
Idea verison : 14.1.2

Have the current error when trying to run module :
```
Error : Failed to launch go compiler: Cannot start process, the working directory C:\Project\GoWorkSpace\src does not exist
```

The expected path was : 
```
F:\Project\GoWorkSpace\src
```
goSDK installed on C:/ drive

**Comment by angelow1337** [comment]
I can confirm this issue.

**Comment by zolotov** [comment]
Cannot recreate on 0.9.291. Please attach screenshot of run configuration that you're trying to run.

**Comment by epixerion** [comment]
Have updated plugin to 0.9.291
working fine now !
