### ISSUE TITLE
Completion suggestions should prioritize the builtin keywords when the full keyword is typed

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1581]
I have the following scenario:
```go
a := &struct<caret>
```
At this point, the completion window shows me a bunch of things that match ```struct``` 
![snapshot64](https://cloud.githubusercontent.com/assets/607868/7352053/781963f6-ed09-11e4-84f9-2d5a06ecdea0.png)
The problem is that I don't want any of those as the option since all I want is to create a new struct. If I press Enter, then the wrong thing will happen unfortunately.

As such, I think the suggestions should contain as the first match (selected) the builtin keyword then the rest of the suggestions as they are now.

Please let me know if you need any details (such as how the IDE is configured).

Thank you!

**Comment by zolotov** [comment]
What exactly the code that you want to get? It seems that 

```
a := &struct {i int}
```

is not valid construction

**Comment by zolotov** [comment]
Nevermind, struct{}{} should work

**Comment by zolotov** [comment]
And one more question. Is it true that it doesn't make sense to completion function in unary &-operation?

E.g. following code shouldn't complete `println` function

```
a := &<caret>
```

**Comment by dlsniper** [comment]
> And one more question. Is it true that it doesn't make sense to completion function in unary &-operation? 

That's correct. I've chose the ``` a := &struct``` scenario as it was one of the handy ones but it can very well be ```a := struct``` or other things as well.

I'll test out tomorrow the latest changes. Thank you very much!

**Comment by zolotov** [comment]
> other things as well.

Not true for other thing, types are valid after &-operator
