### ISSUE TITLE
WebStorm issue, figuring out code completion for 'appengine' and 'strconv'

### ISSUE THREAD

**Issue by bmw0128** [go-lang-plugin-org/go-lang-idea-plugin#1583]
My WebStorm is showing 'ParseInt(...)' in red, which means, i think, that it cannot 'see' this method 'strconv'. I think there is a conflict, and I do not know how to rectify the issue.

My set up:

I Preferences, under “Go”, i have:

Go SDK= /usr/local/go (which is version 1.4.2)
Under “Go Libraries”, in “Global Libraries” section i have: /opt/go_appengine/goroot
and under “Project Libraries”, i have path to my projects’ ‘src’ directory: /Users/bmw/goProjects/src

I am now able to have WebStorm ‘see’ “appengine” in my imports, but now, for instance, when i use Go’s ‘strconv’, the methods show up in red, as to say WebStorm cannot ‘see’ the methods for ‘strconv’.
Example is strconv.ParseInt(), “ParseInt(…)’ is in red.

I do not know if this is related, but I want to say, under External Libraries in my left pane, under my project source code, i now see these two:

Go SDK
GOPATH

Under GoSDK, is ‘src (library home), and if i expand it, i see a bunch of folders, and ‘strconv’ is one folder.
Under GOPATH, are a bunch of folders, and ‘appengine’ is one folder, and so is ‘strconv’.

I believe WebStorm is confused about which ‘strconv’ to use, so that’s why it is red (i am guessing, i do not know for sure).

I’m attaching some screen shots.
Note that I am on OS X, Yosemite.
And i am attaching some screen shots.

![screen shot 2015-04-27 at 10 47 11 am](https://cloud.githubusercontent.com/assets/1458050/7354524/d3f1d0b6-ecd0-11e4-9a1f-6ab3d40b2dc5.png)
![screen shot 2015-04-27 at 10 47 45 am](https://cloud.githubusercontent.com/assets/1458050/7354526/d6204020-ecd0-11e4-9743-34d8b4b0c0c0.png)
![screen shot 2015-04-27 at 10 48 06 am](https://cloud.githubusercontent.com/assets/1458050/7354527/d7ed8926-ecd0-11e4-8171-c862d946facd.png)
![screen shot 2015-04-27 at 10 48 29 am](https://cloud.githubusercontent.com/assets/1458050/7354529/d97882a0-ecd0-11e4-9c05-f56fd356671e.png)
![screen shot 2015-04-27 at 10 49 03 am](https://cloud.githubusercontent.com/assets/1458050/7354532/db085794-ecd0-11e4-9323-7f4f296bd134.png)

**Comment by dlsniper** [comment]
Hi @bmw0128.

Firs of all, I'd like to know which plugin version you are using as all the instructions bellow refer to releases from 0.9.200+. If you have anything lower, please see the README doc in the root of the repository to get information on how to get the latest releases.

As for the setup itself, I think there's a small mistake in your setup that we should fix with better documentation.
If you want to work with appengine, then you should create a Go SDK that points to the Go AppEngine SDK, not the normal Go installation.
Once that is done, you don't need to point the Global Libraries to either Go SDK or Go AppEngine SDK but to your GOPATH, in case you have a global one. If you'd like to have a GOPATH / project, then you should use the Project libraries instead.

Once this is done, you can create the IDE project in the root directory of your project.

Assuming the following:

AppEngine SDK path:   /opt/go_appengine/ -> point the Go SDK in the IDE to this directory
GOPATH: /Users/bmw/goProjects/ -> point the Global libraries to this
Your_Project_Name: /Users/bmw/goProjects/src/github.com/bmw0128/DemoProject -> point the IDE project directory to this path.

Let me know if this works out. If not, or you'd like some more 1-1 help, feel free to ping me on Gitter (the channel is in the README of the project).

Thank you.

**Comment by bmw0128** [comment]
I am using plugin 0.9.291...i will try the suggestions you have given (thank you!) and report back

**Comment by bmw0128** [comment]
Your suggestions resolved my issue, thank you very much.
So I understand, may i think of my /opt/go_appengine install like my original go install (/usr/local/go), but with appengine stuff added? If so, when I look at the 'strconv' directory for each (the appengine version vs original go version), why are they different? I am assuming that this directory would not change, for example, between the two, am i not seeing something correctly as I try to understand my go_appengine vs my original go ?

**Comment by dlsniper** [comment]
Glad to hear it worked!

The differences that I see on my setup are related to the lack of test files in the Go AppEngine SDK distribution. I think that's a decision the AppEngine team took in order to ship only what's needed for them. Also, please keep in mind that the Go versions might be different between AppEngine and the regular Go (1.4.1 vs 1.4.2 in my case).
If you plan to work on projects involving AppEngine I highly recommend to use the Go SDK shipped with the AppEngine one as you'll be on the safe side of using only what's permitted by the AppEngine runtime.
That's why, for the IDE, we allow people to choose which SDK they want to use as we must allow for both scenarios.
If you'd like to find out more info about the AppEngine SDK, you can check their docs: https://cloud.google.com/appengine/docs/go/
If you bump into further issues with the plugin, feel free to open up issues (if they are not already there :D).
I'll close this for now.

**Comment by bmw0128** [comment]
Thanks very much.

**Comment by bmw0128** [comment]
Hi….I was thinking, is it possible for me to get involved in the project somehow?

I am a pretty average java programmer, and I am learning Go by building a side project (uses Go, Angular, with WebStorm).

I want to grow my skills as a dev, and I want to contribute to a project, to learn and to be involved.

If so, would you give me a push in a direction?

Thanks

**Comment by ignatov** [comment]
@bmw0128 Nice to hear that. We need some time to realise what we can offer you. Stay tuned!

**Comment by bmw0128** [comment]
Great, thanks.
I am willing to do most anything, I want to learn and be helpful however I can.

**Comment by ignatov** [comment]
BTW, you can start with building the plugin from scratch and reading the following links: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#useful-links

**Comment by bmw0128** [comment]
Will do, thanks.

I may have a few ‘getting started’ questions, and I’ll just email if so.

**Comment by dlsniper** [comment]
@bmw0128 feel free to check out the Gitter room as well, I usually lurk there and at least with the basic stuff I can help as well. Looking forward for your contributions ;)

**Comment by bmw0128** [comment]
Sorry, Gitter room, haven’t heard of such, I’ll look it up, but….

I will see how to get to the Gitter room on the main page?

**Comment by dlsniper** [comment]
Yeap, the link is in readme:
https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin you can
authenticate with Github and things should work ;)
