### ISSUE TITLE
gofmt not found

### ISSUE THREAD

**Issue by smallsmallwolf** [go-lang-plugin-org/go-lang-idea-plugin#1586]
![5f939a57-ec37-4835-8cae-0ac1a85758bd](https://cloud.githubusercontent.com/assets/975175/7385091/9bee368a-ee71-11e4-8e49-e075d520cfc6.jpg)

`gofmt` is here `/usr/local/bin/gofmt` and `Global libraries` had been added, but `gofmt not found`

**Comment by dlsniper** [comment]
There are a few ways to fix this:
- launch the ide from the command line
- change the idea.sh (i don't know the Mac equivalent) file to add your PATH there as it's not being transmitted from your environment to the Java process.

**Comment by zolotov** [comment]
Both solutions are not the best. 
I can add running `/path/to/sdk/bin/gofmt` instead of running `go fmt`. Meanwhile, @smallsmallwolf where you have defined `/usr/local/bin/` in PATH variable?

**Comment by zolotov** [comment]
@smallsmallwolf also what happens if you run the same command as on screenshot in terminal?

**Comment by smallsmallwolf** [comment]
@zolotov `/usr/local/bin/`defined in `~/.zshrc`, and I try to run the same command in terminal, it works fine.
Then I try `mv /usr/local/bin/gofmt /bin/gofmt`, it solved this problem.

**Comment by dlsniper** [comment]
@zolotov might be a stupid idea but instead of changing from ```go fmt``` to ```gofmt``` shouldn't the plugin add ```SDK/bin``` and each ```Go Library/bin``` folders to the path if they are not there? That way we could recreate the environment closer to the user environment when such information is not sent to the IDE. What do you think?

**Comment by zolotov** [comment]
> might be a stupid idea but instead of changing from go fmt to gofmt shouldn't the plugin add SDK/bin and each Go Library/bin folders to the path if they are not there?

Actually it's good idea. We shouldn't rely on it and invoke applications by their absolute paths. But this approach can solve the issue like this, when we can't control execution.
