### ISSUE TITLE
IDEA14.1.1 and IDEA14.1.2 both can not recognize the go1.4.2 sdk!help!

### ISSUE THREAD

**Issue by itnik** [go-lang-plugin-org/go-lang-idea-plugin#1587]
I had try the all the solution to make the IDEA can recognize the sdk these days.

This plugin i try all the version but faild.
My Env is:
OXS Yosemite 10.10.3
zsh
Go1.4.2
IDEA14.1.1 ULTIMATE and IDEA14.1.2 ULTIMATE
go-lang-idea-plugin (all version from 0.9.15.3 ~ 0.9.292)

Plugin can install but can't choose the SDK. It don't let me to click the 'Choose' button.I think it might can not recognize the SDK.
Please help me ,cause it make me crazy.

**Comment by dlsniper** [comment]
Please read the docs: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project 
Also, what error do you have? Is there anything in the logs? How did you installed 0.9.292? How did you installed the go SDK? where are you trying go point the go SDK root to? how is the go sdk setup looking like? Can you make some screenshots of what's happening? Do you see any errors in the UI / in the logs?

**Comment by dlsniper** [comment]
I'll close this for now as there's no feedback. If anything changes please reopen this. Thank you.
