### ISSUE TITLE
Cannot customize target OS for development via UI.

### ISSUE THREAD

**Issue by JakeWarner** [go-lang-plugin-org/go-lang-idea-plugin#1590]
(Creating this for tracking purposes)

In chat earlier today:

> I'm on OSX using this golang plugin and I'm not able to develop with any of the files that end with _linux.go. We have an actual build environment that compiles these native linux binaries but I'd still like to develop on OSX without needing to setup a container/vm, etc.
> tl;dr: Is there any way to tell the golang plugin "hey, include the linux source files in auto-complete even though this is on OSX."

@zolotov responded:
> In order to pass to IDE this property copy /Applications/IntelliJ IDEA 14 CE.app/Contents/bin/idea.vmoptions file to ~/Library/Preferences/IntelliJIdea14(or IdeaIC14)/idea.vmoptions and add there following content: 
> -Dgo.target.os=linux
> windows and mac values are also supported.
> Another way to pass this property: /Applications/IntelliJ IDEA 14 CE.app/Contents/Info.plist file, you should add following text inside VMOptions value:
> -Dgo.target.os=linux

It worked great and I asked if it would be implemented on a per-project basis, to which @zolotov responded:
> sure, this implementation is just quick workaround, later I’ll add real per-project setting in UI

**Comment by linniksa** [comment]
also _{target}.go not the only way to specify platform for file, see #1199 (and alse // +build ignore)
@zolotov What do you think about when or how to "build" flag processing can be done?

**Comment by zolotov** [comment]
@linniksa I think it will be my next task. As for how, I don't know yet, at least we should index and parse build flags, then I'll think about supporting.

**Comment by zolotov** [comment]
@linniksa I've added build flags stubbing. So now we can retrieve go flags for particular file without performance degradation. Not sure when I will support the build flags in resolving, so in case you'll get to it faster then me, there are a `GoFile#getBuildFlags()` method for retrieving flags and `GoUtil#allowed()` method for checking context while completion/resolving.

**Comment by JakeWarner** [comment]
Thanks for making this change @zolotov! Unfortunately, I can't find the interface to configure this.

**Comment by zolotov** [comment]
Settings | Languages & Frameworks | Go

**Comment by JakeWarner** [comment]
Hmm. I don't see anything there about flags / operating systems. I'm using the alpha repo for the plugin, current version according to IntelliJ is 0.9.325 on OSX. Is this proper?

Thanks again.

**Comment by zolotov** [comment]
Should be there. Please attach screenshot and logs.

**Comment by zolotov** [comment]
Sorry for misinformation. Build flags configurable was implemented in 0.9.329. Next alpha will contain it.
