### ISSUE TITLE
Code completion: high CPU load on first letter

### ISSUE THREAD

**Issue by ukautz** [go-lang-plugin-org/go-lang-idea-plugin#1591]
Not sure if this is just a local issue of mine or if anybody else has the problem:

With either `Autopopup code completion` activated, or if code completion (`ctrl + space`) is triggered manually:
* On typing the first letter a single CPU core goes up to 100%
* Unless one continues typing, the CPU load stays at 100% while the code completion dialog is present
* Not all letters are "affected the same", I could see the effect best with `e`, `n`, `a`
* I could not figure out a specific "code structure" or code size which makes the behavior more likely

I confirmed the behavior on two machines (Ubuntu 14.04, i7-3770 and i5-xx) both using the latest IntelliJ EAP 141.814.3, Java 1.8.0_45-b14, Go 1.4.2 and the the Go lang plugin build 298 (nightly).

If this is not a local problem of mine, than the behavior was introduced within the last 2 weeks (sorry I cannot be more specific since I could not figure out how to go back to older builds).

**Comment by dlsniper** [comment]
@ukautz can you please provide a way to reproduce this? You can search for current / previous issue which match for "performance" in search. Any test sample would that can reproduce it would be good.
Also, you can help by profiling the CPU used by IntelliJ, please read the docs here: https://intellij-support.jetbrains.com/entries/29983118-Reporting-performance-problems

**Comment by dlsniper** [comment]
If you want to try older versions, you can download some of them from the Github releases section, but I'm not sure how nice they will play with IDEA 14.1.

**Comment by ukautz** [comment]
@dlsniper Thanks for the super fast reply. After submitting the issue I got a hunch and while I cannot provide you a project to reproduce it, I think I nailed the source of the issue down:

The effect is most visible with `e`. `n` and `a` since those are simply very common letters in English. When I started a new project with an empty `GOPATH` (besides go core packages) the behavior did not occur on any letter. Adding more packages to the `GOPATH`, with more code and thereby more candidates for code completion, the behavior returned. There is no counter of the length of items in the auto complete list so I cannot give you a threshold.

To reproduce, just `go get` more packages. Not sure if I simply overdid it. My `GOPATH` contains lot's of "try out" packages (27 in total). However, if you can reproduce it and there is an easy fix, I'd appreciate it (projects tend to grow).

As for the two weeks: I remember to have added more packages to compare against each other back than, which must have triggered the described behavior.

**Comment by zolotov** [comment]
@ignatov please fix unstubbing on completion or disable showing types in lookup items

**Comment by ukautz** [comment]
I think this issue can be ignored. Sorry for the waste of time. I "fixed" it by doubling general heap memory and especially `ReservedCodeCacheSize` for IntelliJ. I guess I simply use too many packages...

**Comment by zolotov** [comment]
We want the plugin works fine with default settings and with many packages :)

**Comment by zolotov** [comment]
So if you made a cpu dump while long completion it would be very helpful.

**Comment by ukautz** [comment]
Alright, never used this YourKit before (not a Java guy for some time now). Got a dump, but it's large and not sure if it's the right one. Can I mail you the URL (the dump contains sys infos..)?

**Comment by dlsniper** [comment]
@ukautz if you don't want to share it, there's a way in the docs to upload it to the JetBrains FTP server which only they have access to read from. Also, we are on Gitter so if you send me the URL I can forward it to the private chat there ;)

As a fun fact, my setup has about 1.1Gb of files in GOPATH/src and well, quite a few lines of code :D  
![snapshot67](https://cloud.githubusercontent.com/assets/607868/7413733/747ec726-ef4e-11e4-9356-f1ecf9694eb5.png)

If you have problems generating the sample, ping me on Gitter as well :)

**Comment by ukautz** [comment]
Alright, I send you the URL on Gitter. My GOPATH is much smaller, btw:
```
    4058 text files.
    3355 unique files.                                          
    4337 files ignored.

http://cloc.sourceforge.net v 1.60  T=10.09 s (255.7 files/s, 55164.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Go                             2351          63487          52991         403429
Javascript                       22            390            201          11349
HTML                             18            945             17           5427
Assembly                         10             45             65           3286
Bourne Shell                     56            641            511           2946
XML                              19              6              2           2416
Bourne Again Shell               37            352            280           2175
CSS                               7            470             52           1716
SASS                             13            205            199           1088
C                                 4            158             47            677
YAML                             24             61             19            352
make                             12            100             23            235
Python                            2             16             11            102
C/C++ Header                      1              2              4             66
Perl                              1             11             37             29
Ruby                              1              4              6             18
vim script                        2              8              3             13
--------------------------------------------------------------------------------
SUM:                           2580          66901          54468         435324
--------------------------------------------------------------------------------
```

**Comment by ukautz** [comment]
Alright. This time I think I really nailed it: I work with a project consisting of multiple modules:
![project-layout](https://cloud.githubusercontent.com/assets/600604/7584220/303e7cbc-f89c-11e4-97c0-955181c84a11.png)

Now, whenever starting IDEA, each module brings it's own `GOPATH`:
![all-go-path](https://cloud.githubusercontent.com/assets/600604/7584234/47439d02-f89c-11e4-89d3-22c04c5865d9.png)

This is probably because I setup the `GOPATH` as _Project libraries_, not _Global libraries_ (working on multiple projects, want them kept cleanly apart).

Those happen to be the same, but i see all of them listed individually as external libraries:
![external-libs](https://cloud.githubusercontent.com/assets/600604/7584308/e2209492-f89c-11e4-86f4-0650f995ee46.png)

This of course blows up the amount of go modules/packages to look into when auto-completing. I can confirm that the problem is gone when removing all but one of the `GOPATH` from the project:
![reduced-go-path](https://cloud.githubusercontent.com/assets/600604/7584341/1a2742be-f89d-11e4-8154-46629c9004bc.png)

This solved it for me. However, the removals are not persistent (i.e. whenever I restart IDEA all modules individual `GOPATH` will be in the external libraries once more). Not sure if those ext libs are managed by the Plugin or the IDE.

**Comment by zolotov** [comment]
@ukautz restoring libraries on restart is happened intentionally, GOPATH library can be configured only in Settings | Languages & Frameworks | Go Libraries. There you can configure different GOPATH for different modules.

I'll take a look on it but it's not a bottleneck according to your snapshot.

**Comment by zolotov** [comment]
@ukautz please try 0.9.337 build

**Comment by ukautz** [comment]
@zolotov Sorry for the late reponse. I tried 0.9.339 yesterday and 0.9.340 today (not sure how to get earlier versions). Neither seems to be affected by the behavior I described anymore. Very much appreciated!

**Comment by zolotov** [comment]
@ukautz cool, thanks for feedback.

**Comment by zolotov** [comment]
Well, we've done all that we could. Hope it's better now.
