### ISSUE TITLE
Can't find app engine packages when using app engine SDK

### ISSUE THREAD

**Issue by jaydonnell** [go-lang-plugin-org/go-lang-idea-plugin#1592]
I'm using intellij 14.1.2 and version 0.9.300 of the plugin.

I've setup the SDK to point to the google app engine SDK, but the plugin is still unable to find app engine specific packages with error message "Cannot resolve directory 'appengine'". Images below show the issue and my configuration. 

![intellij-sdk](https://cloud.githubusercontent.com/assets/8443/7419554/9c216b4a-ef2a-11e4-8456-3ece77997dd4.png)

![app-engine-intellij](https://cloud.githubusercontent.com/assets/8443/7419510/5fc31518-ef2a-11e4-9afa-411a78efc0d2.png)

**Comment by dlsniper** [comment]
Hi, your SDK looks very strange to me, at least on Linux.
Also, you seem to be using an outdated version of the Go AppEngine SDK, please update that first and create a new SDK with that, then make sure it's attached to the project. If you have any troubles, please let me know.

Thank you.

**Comment by dlsniper** [comment]
I've forgot to mention, I have the SDK installed from the sources directly, not via OS package manager and for example, the Go SDK root points to ```/usr/local/go_appengine``` (without any of the subdirectories). Hope this helps.

**Comment by dlsniper** [comment]
@jaydonnell any updates on this? I'll close it for now and if something changes please reopen it. Thank you.
