### ISSUE TITLE
Go plugin 0.9.300, Can not see debug preference.

### ISSUE THREAD

**Issue by johnnywidth** [go-lang-plugin-org/go-lang-idea-plugin#1593]
After update plugin from link ttps://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds,
on mac 10.10.3 with idea 14.1 my go application preference looks like this
![image](https://cloud.githubusercontent.com/assets/3796597/7430203/fa8f05be-f017-11e4-93d0-6f49fd26f216.png). And i can not configure debug preference, but earlier i could.

**Comment by dlsniper** [comment]
I get it now, if you want to use GDB with the latest versions of the plugin, please create a Go GDB runner not a Go Application.

![snapshot68](https://cloud.githubusercontent.com/assets/607868/7430606/cc86b54c-f015-11e4-878f-402237eefc7e.png)

**Comment by johnnywidth** [comment]
Do you have some example how configure Go GDB? Because i saw that and can not understand how use it.

**Comment by dlsniper** [comment]
You must build the application like this: ``` go build -gcflags "-N -l" main_file.go``` then, when you get the binary, create the run configuration in IDEA, point the ```Application Executable``` filed to the binary and you can try it.
Again, it's highly experimental and things might not work as Go doesn't properly support GDB (or vice-versa better said) https://golang.org/doc/gdb

**Comment by dlsniper** [comment]
I'll close this for now

**Comment by johnnywidth** [comment]
Ok
