### ISSUE TITLE
Reopening: Can't find app engine packages when using app engine SDK

### ISSUE THREAD

**Issue by jaydonnell** [go-lang-plugin-org/go-lang-idea-plugin#1594]
I'm reopening the following issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1592

I've installed the latest go SDK and am still getting the same issue.

![intellij-go](https://cloud.githubusercontent.com/assets/8443/7439809/7eafdb60-f041-11e4-803c-20adc82c3cbc.png)

**Comment by dlsniper** [comment]
Please point the sdk dir to ```/Users/ddonnell/bin/go_appengine```, without the goroot dir.

**Comment by zolotov** [comment]
Please attach screenshot of `Project Structure | Project` and `Project structure | Modules | Dependencies` pages.

**Comment by zolotov** [comment]
> Please point the sdk dir to /Users/ddonnell/bin/go_appengine, without the goroot dir.

It's correct path

**Comment by jaydonnell** [comment]
Thanks @zolotov it's working now. The right SDK wasn't selected in Project and Dependencies.
