### ISSUE TITLE
Structure view for multiple files in a package?

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1595]
Hi,

Before considering this being an issue, I'd like to ask what's the feeling in regards to changing the ```Structure view``` to display the whole package contents rather than the single file? Or maybe it should be an option / highlight differently the contents from the current file vs rest of the package?
What do other people think about this?

As a note, I don't really use this functionality so maybe I'm viewing this in the wrong way?

**Comment by zolotov** [comment]
Don't know, I don't use this functionality as well, maybe option is a good way but I'm not sure

**Comment by JoeBruner** [comment]
Hmm,  Interesting.  I use the Structure view all of the time as a quick way to jump to the functions that I'm looking for.  I think that having the whole package might be confusing to some, especially Java people where you're used to everything being contained in the same file.  For Go, however, it's perfectly acceptable to have related things spread out amoungst multiple files.  I think you'd want to have it as a toggle option, as I can see if being useful both ways.  File-wise makes it convenient to navigate your current file structure quickly, whereas project-wise lets you know everything that's available, regardless of what file it resides in.
