### ISSUE TITLE
Plugin doesn't use the file template from either project or default settings

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1596]
I've tried changing the default and project templates for Go files but either I don't know how to actually use this feature or there's something that the plugin doesn't do as the files created still have the same format.

To be a bit more clear, I've tried adding a default header to the file but the file gets created without it.

![snapshot78](https://cloud.githubusercontent.com/assets/607868/7440941/f2cb6aac-f0d0-11e4-8651-458192ecce86.png)

**Comment by zolotov** [comment]
Works fine for me. Screencast maybe?

**Comment by dlsniper** [comment]
Aparently I need to reload the project for this to take effect but I'm ok with that for now.

**Comment by zolotov** [comment]
> Aparently I need to reload the project for this to take effect but I'm ok with that for now.

Reloading is not required, maybe something helpful remained in logs?
