### ISSUE TITLE
Debug Configuration not starting

### ISSUE THREAD

**Issue by mvbaffa** [go-lang-plugin-org/go-lang-idea-plugin#1599]
Hi,

I have installed the Plugin Ok. I have created a Go Simple Application that is working but I cold not debug it. 

When I start the debug nothing happens. Is there any addtional configuration to do ?

Thanks

**Comment by dlsniper** [comment]
Please see the discussion in: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1593
