### ISSUE TITLE
os.Getenv("GOPATH") is broken when running inside IDE

### ISSUE THREAD

**Issue by davelondon** [go-lang-plugin-org/go-lang-idea-plugin#1600]
Since 935919824f8ff7b3b589c35ba5b0f640fb6d09ea landed I'm getting an unexpected value from os.Getenv("GOPATH") when running my code inside IntelliJ:

Expected:
```
/Users/dave/dev/proj/go
```

Actual:
```
file:///Users/dave/dev/proj/go
```

**Comment by dlsniper** [comment]
Thanks for reporting, I'll work on a fix for it.

**Comment by dlsniper** [comment]
See #1601

**Comment by zolotov** [comment]
PR is not really good but I'll fix it soon, thank you

**Comment by davelondon** [comment]
Confirmed fixed in the latest version. Thanks!
