### ISSUE TITLE
why Intellij IDEA close file on save and then copy another?

### ISSUE THREAD

**Issue by oblank** [go-lang-plugin-org/go-lang-idea-plugin#1604]
How can I disable this? the file name be add suffix 201505031440055...

I try to rename it, but IDEA will create another
![Image of error](http://i.stack.imgur.com/HQ7Sn.jpg)
when I use COMMAND+S to save file, the file will be closed auto, and then IEDA create another with suffix
Intellij IDEA is V14.1.2 Community Edition for Mac

**Comment by dlsniper** [comment]
I'd rather say this is a problem to report to JetBrains than a plugin problem but I'm clueless on how to reproduce it to be sure. 

Can you please add a screencast which replicates the issue? 

Also, maybe you can find a similar issue here: https://youtrack.jetbrains.com/dashboard

**Comment by oblank** [comment]
thx :)

fixed by install Intellij IDEA again, not Community Edition

**Comment by ignatov** [comment]
BTW, looks really weird. @zolotov What do you think about it?

**Comment by zolotov** [comment]
@ignatov have no idea, have never seen this before
