### ISSUE TITLE
Tab complete does not work on method chaining

### ISSUE THREAD

**Issue by lindroth** [go-lang-plugin-org/go-lang-idea-plugin#1605]
If a method has a named return variable method chaining has no tab completion and the method name will be marked red and as not found.

```go
package main

type A struct {
}

func (self *A) chain() *A{
	return self
}

func getAnA() (result *A) {
	result = &A{}
	return
}

func getAnotherA() *A {
	return &A{}
}

func main() {
	//This works and gets tab completed
	getAnotherA().chain()

	//So does this.
	t := getAnA()
	t.chain()

	//This is not tab completed and chain is marked as not found
	getAnA().chain()
}
```

**Comment by zolotov** [comment]
`getAnA` doesn't return anything, why it should work?

**Comment by zolotov** [comment]
Sorry, you're right, it should work

**Comment by dlsniper** [comment]
@zolotov in go it is ok to have a function like this:

```go
func getAnA() (result *A) {
    result = &A{}
    return
}
```
When you have named return values, ```return``` without anything else will act as ```return result```.  Please see: https://golang.org/doc/effective_go.html#named-results

**Comment by dlsniper** [comment]
You were faster than me.. :D

**Comment by lindroth** [comment]
Wow that was quickly fixed. Thanks!
