### ISSUE TITLE
slow with a long line.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1608]
Here is the code.
![image](https://cloud.githubusercontent.com/assets/1107541/7475366/b98ea848-f379-11e4-8086-5dcb1ef40142.png)

```golang
package kmgCompress
import (
	"testing"
	"github.com/bronze1man/kmg/kmgFile"
	"github.com/bronze1man/kmg/kmgTest"
)

func TestZipUncompressFromBytesToDir(ot *testing.T){
	kmgFile.MustDeleteFileOrDirectory("testfile")

	contentB:=[]byte{0x50, 0x4b, 0x3, 0x4, 0xa, 0x3, 0x0, 0x0, 0x0, 0x0, 0x79, 0xb1, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, 0x0, 0x0, 0x0, 0x31, 0x2e, 0x74, 0x78, 0x74, 0x50, 0x4b, 0x3, 0x4, 0x14, 0x3, 0x0, 0x0, 0x0, 0x0, 0x2c, 0xb3, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x74, 0x65, 0x73, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x50, 0x4b, 0x3, 0x4, 0xa, 0x3, 0x0, 0x0, 0x0, 0x0, 0x2c, 0xb3, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe, 0x0, 0x0, 0x0, 0x74, 0x65, 0x73, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x31, 0x2e, 0x74, 0x78, 0x74, 0x50, 0x4b, 0x1, 0x2, 0x3f, 0x3, 0xa, 0x3, 0x0, 0x0, 0x0, 0x0, 0x79, 0xb1, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20, 0x80, 0xa4, 0x81, 0x0, 0x0, 0x0, 0x0, 0x31, 0x2e, 0x74, 0x78, 0x74, 0x50, 0x4b, 0x1, 0x2, 0x3f, 0x3, 0x14, 0x3, 0x0, 0x0, 0x0, 0x0, 0x2c, 0xb3, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x80, 0xed, 0x41, 0x23, 0x0, 0x0, 0x0, 0x74, 0x65, 0x73, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x50, 0x4b, 0x1, 0x2, 0x3f, 0x3, 0xa, 0x3, 0x0, 0x0, 0x0, 0x0, 0x2c, 0xb3, 0xa5, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20, 0x80, 0xa4, 0x81, 0x4a, 0x0, 0x0, 0x0, 0x74, 0x65, 0x73, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x31, 0x2e, 0x74, 0x78, 0x74, 0x50, 0x4b, 0x5, 0x6, 0x0, 0x0, 0x0, 0x0, 0x3, 0x0, 0x3, 0x0, 0xa6, 0x0, 0x0, 0x0, 0x76, 0x0, 0x0, 0x0, 0x0, 0x0}
	err:=ZipUncompressFromBytesToDir(contentB,"testfile")
	kmgTest.Equal(err,nil)
	kmgTest.Equal(kmgFile.MustReadFileAll("testfile/testfile/1.txt"),[]byte(""))
}
```

Here is the code:
https://github.com/bronze1man/kmg/blob/master/kmgCompress/zip_test.go

**Comment by dlsniper** [comment]
Quick question, what's slow about it? It would help narrow things down. Thank you!

**Comment by bronze1man** [comment]
It takes long time to parse (or highlight?) this file.
After the parse finished, the idea itself become slow.

**Comment by zolotov** [comment]
It's parsed fast for me. Yes, scrolling is slow because of enabled soft wraps, I'll pass this issue to IDEA team.

**Comment by bronze1man** [comment]
@zolotov It took about 5s to parse https://github.com/bronze1man/kmg/blob/master/kmgCompress/zip_test.go
It only took about 2s to parse https://github.com/bronze1man/kmg/blob/master/kmgCompress/zip.go

The parsed time should be good enough right now,but I think it can be improve.

After it parse https://github.com/bronze1man/kmg/blob/master/kmgCompress/zip_test.go ,when move the curse with up key,the idea response slow.

Can you provide the IDEA issue link?

**Comment by dlsniper** [comment]
@bronze1man can you please do a profiling on your system? For me it took less tahn a second to parse the file (I didn't do a go get on the kmg project yet tho) https://intellij-support.jetbrains.com/entries/29983118-Reporting-performance-problems

**Comment by bronze1man** [comment]
I will do the profilling later.
I think the file number of the project may be the reason of problem.
My working project has 1540 golang files.
Those golang files have 12MB size totally.

The kmg project is only part of it,and kmg project has 384 golang files.

**Comment by ignatov** [comment]
@bronze1man please specify your idea and java version.

**Comment by bronze1man** [comment]
jre 1.6.0_xxx
idea 14.1.2

**Comment by zolotov** [comment]
Fixed in Intellij Platform. See https://youtrack.jetbrains.com/issue/IDEA-141585 for details
