### ISSUE TITLE
Quick documentation doesn't correctly display this < > signs

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1613]
Given the following example from ```strings``` package in go sdk:

```go
// Replace returns a copy of the string s with the first n
// non-overlapping instances of old replaced by new.
// If old is empty, it matches at the beginning of the string
// and after each UTF-8 sequence, yielding up to k+1 replacements
// for a k-rune string.
// If n < 0, there is no limit on the number of replacements.
func Replace(s, old, new string, n int) string{
	return s
}
```

The quick documentation functionality doesn't display the ``` < ``` from ``` // If n < 0, there is no limit on the number of replacements. ```

![snapshot89](https://cloud.githubusercontent.com/assets/607868/7491671/dfb9dbce-f3eb-11e4-9d07-1b6f7c51b7fe.png)

Plugin revision: e668080d626ea0be46c4937e173c0133443da9bd

**Comment by zolotov** [comment]
see com.intellij.xml.util.XmlStringUtil#escapeString(java.lang.String)

**Comment by dlsniper** [comment]
@ignatov thanks! but I wanted to do it myself :(

**Comment by ignatov** [comment]
@dlsniper Please don't worry. We have lot of issues and I can assign several of them to you ;)
