### ISSUE TITLE
Support Analyze Stacktrace feature?

### ISSUE THREAD

**Issue by wallyworld** [go-lang-plugin-org/go-lang-idea-plugin#1615]
Are there plans to support the Analyze Stacktrace feature for Go thread dumps?

**Comment by dlsniper** [comment]
(side note to clarify the milestone ping-pong. I should mark it as a maybe rather than x.x.x as I have no clue how that feature works in IntelliJ :D)

**Comment by wallyworld** [comment]
The Analyze Stacktrace feature is awesome. If you paste a thread dump, if hyperlinks all the method and line references so you click and navigate through to the code.
https://www.jetbrains.com/idea/help/analyzing-external-stacktraces.html

**Comment by dlsniper** [comment]
apparently it's simple to do :) Thank you @zolotov

**Comment by zolotov** [comment]
@wallyworld I'm not sure that it will work correctly for Go tread dumps but it's enabled now and you can report bugs about particular unrecognisable stacktraces

**Comment by wallyworld** [comment]
@zolotov That is awesome, thank you!!
