### ISSUE TITLE
Recursive symlinks break inspection

### ISSUE THREAD

**Issue by xealot** [go-lang-plugin-org/go-lang-idea-plugin#1616]
At least, that's what I think is happening.

Glide (https://github.com/Masterminds/glide) is one of the less awful strategies for managing Go's "challenging" package system.

Glide, basically, just manages a _vendor folder and checks out everything to there by setting GOPATH to _vendor. So my project looks like this:

```
<root>
  - _vendor
    - github.com
      - project
        - repo -> ../../../../
  - package
  - another package
  - main.go
  - etc
```

When I replace the "repo" dir with a real clone of the repo that isn't linked up to the root inspections work. When I split the root of the project into a _vendor and src folder inspection seems to work also. However, the way in which glide recommends doing things seems to break it.

All inspection works perfectly except for the things in my own project in another package. So, anything that requires an import from my own project.

**Comment by dlsniper** [comment]
I'll have a look at it to see what's happening but I have to be honest, that's a very strange one to do. godep (without import rewriting) is by far nicer than this (from a Go point of view). Thanks for reporting.

**Comment by xealot** [comment]
I will not defend the "strangeness" of it, it's just a bug I noticed. Personally I will definitely re-evaluate godep though as I was under the assumption that you always had to do rewriting which was a big turn-off for me.

**Comment by xealot** [comment]
I spent a few hours re-evaluating Godep. It does seem to behave a lot better in the IDE and with some of the go tools but I think nesting your project root deep inside of a go environment structure is still a little silly.

**Comment by dlsniper** [comment]
@xealot can you try the latest alpha / nightly? I think the issue you are describing should be fixed now. If not I'll try to replicate it. Thanks.

**Comment by dlsniper** [comment]
I'll close this due to lack of updates.
