### ISSUE TITLE
Analyze stacktrace doesn't work so well for panic dumps

### ISSUE THREAD

**Issue by wallyworld** [go-lang-plugin-org/go-lang-idea-plugin#1617]
If I debug some code by adding:
debug.PrintStack()
then the analyze stacktrace feature correctly highlights the source reference because the filenames are fully qualified paths. eg

/home/ian/project/src/github.com/wallyworld/cmd/cmd.go:211 (0x49dd24)    <---- correctly linked
        (*Info).Help: debug.PrintStack()
/home/ian/project/src/github.com/wallyworld/cmd/help.go:611 (0x4a7dc1) <---- correctly linked
        (*helpCommand).Run: ctx.Stdout.Write(info.Help(f))

But when a panic() is used, the filenames are not fully qualified paths and so no linking happens, eg

... Panic: testing (PC=0x43D2C5)

/home/ian/.gvm/gos/go1.4/src/runtime/panic.go:387   <-- linked
  in gopanic
volumes.go:197            <---- not lined
  in disks.volumes
volumes_test.go:56       <--- not linked
  in volumeSuite.TestInstanceVolumes
/home/ian/.gvm/gos/go1.4/src/reflect/value.go:296    <--- linked
  in Value.Call
/home/ian/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232    <--- linked
  in goexit

**Comment by zolotov** [comment]
where `volumes.go` and `volumes_test.go` are located?

**Comment by wallyworld** [comment]
The volumes.go and test files are located in the source tree of the project. Sadly, the location is not included in the output of the panic. I'm not sure if the location can be inferred somehow? From the program counter and any debug information in the compiled binaries? Seems unlikely I guess.

**Comment by zolotov** [comment]
Try the next nightly please
