### ISSUE TITLE
_workspace Godeps directory not recognized in source tree

### ISSUE THREAD

**Issue by Symmetric** [go-lang-plugin-org/go-lang-idea-plugin#1619]
I've got a library home set to the root of my project, and all my imports are green in my .go file. However I can't navigate to any of my godeps - if I goto-source on any part of the path `github.com/coreos/rkt/Godeps/_workspace/src/github.com/appc/cni/pkg/plugin` up to and including the `_workspace` directory, it jumps to the correct part of the directory tree. But goto-source on `src` or later does nothing.

Here's a screenshot of the issue -- I suspect there's significance in the fact that the directories in question are red, but I don't know how to affect that.

Is this a bug, or a misconfiguration?

![image](https://cloud.githubusercontent.com/assets/1524910/7599125/80ac1ebc-f8b4-11e4-8a79-4712070c9cf4.png)

**Comment by dlsniper** [comment]
Hi, I see that you marked the code as excluded so I'm not sure what you'd expect in this case. Can you please remove the mark from the folder and try again? Also, which plugin version do you use?

**Comment by dlsniper** [comment]
Please see https://www.jetbrains.com/idea/help/configuring-content-roots.html for some info on how to mark/unmark a folder as source/excluded and so on.

**Comment by Symmetric** [comment]
I didn't mark anything as excluded. In the main project tree it's listed as a normal directory:

![image](https://cloud.githubusercontent.com/assets/1524910/7599434/e008c99e-f8b6-11e4-9c6a-6fd37e85fae7.png)

Perhaps my config is slightly perverse though -- my IntelliJ project is rooted in the src/github.com/coreos/rkt directory, and I put a reference to src as the project library path. I can confirm that changing this to have the IntelliJ project rooted in src as well resolves this.

**Comment by dlsniper** [comment]
ok, so I don't really understand, sorry.

What is / was your setup looking like, where was the project root dir pointing to and what are / were the configured Go Libraries?

Thanks.
