### ISSUE TITLE
Autocompletion freezes

### ISSUE THREAD

**Issue by akaspin** [go-lang-plugin-org/go-lang-idea-plugin#1623]
After update autocompletion freezes about a second. IDEA 14.1.3 (141.1010), Go plugin 0.9.325.

**Comment by ignatov** [comment]
Please attach your thread dumps and logs. If it's reproducible please attach a performance snapshot. For the further information please see https://devnet.jetbrains.com/docs/DOC-192

**Comment by akaspin** [comment]
https://gist.github.com/akaspin/b6d355e0aec1a6d829bf

**Comment by probepark** [comment]
:+1:

**Comment by dlsniper** [comment]
@probepark, if you want for this to be fixed, please follow what @ignatov said earlier. +1 is really not helping.

**Comment by probepark** [comment]
@dlsniper I see
I have enabled to use yourkit.
If i get freeze again, i will attach with log

**Comment by dlsniper** [comment]
@probepark that's perfect, thank you!

**Comment by probepark** [comment]
https://gist.github.com/probepark/c4a344a89cd720a17771

**Comment by akaspin** [comment]
Rolled back to 0.9.325. No freezes.

**Comment by zolotov** [comment]
@akaspin I thought that 0.9.325 was the first build with freezes, no?

**Comment by akaspin** [comment]
@zolotov Whats funny. But freezes occurs on nightly plugin repo.

**Comment by akaspin** [comment]
@zolotov Ooops. Freezes again. Sorry for misinformation. Whats pain.

**Comment by dlsniper** [comment]
I've seen the following in the log
```
:82 [5337600]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class com.goide.configuration.GoConfigurableProvider$GoCompositeConfigurable 
2015-05-14 15:15:52,186 [5387904]   INFO - ellij.vfs.persistent.FSRecords - Creating VFS corruption marker; Trace=
java.lang.Exception
````
And then, later on the indexing appears to be cancelled, or pauswd or something, have you tried to clean all the cache from the ide and restart it? Maybe that will help.

**Comment by zolotov** [comment]
@dlsniper it has nothing to do with freezing.

@akaspin if you can't share the project, could you at least share its open sourced parts? Looks like the reasons of freezing are many similar completion items, completion sorting and GC; it's hard to reproduce these without proper test project.

**Comment by pftbest** [comment]
For me it happens with any project, even with an empty one, probably because my $GOPATH is full of different libraries and projects.
IDEA version 141.1010, plugin version 325
yourkit Snapshot: http://googledrive.com/host/0B4ouTzM6vLORflJYVGZHUzk2VTZpRW1KUzh5VEhOWXNGVlBlbjBRYlZzcEJBTzNkWFpneVE/Main-2015-05-28.snapshot
CPU usage 12% means one of my 8 cores is fully loaded and ui is not responding.

**Comment by zolotov** [comment]
Thanks, we've reproduced the issue. The next IDEA EAP will contain the fix, please give us feedback when you'll try it.

**Comment by pftbest** [comment]
Can you give me IDEA issue code?

**Comment by zolotov** [comment]
There is no one. Here is the commit: https://upsource.jetbrains.com/idea-community/revision/3178bb7943614fc5e8b761ed01353e8c85b8535e

**Comment by zolotov** [comment]
I've made some optimizations in completion. Please check build >=0.9.337

**Comment by ivankorobkov** [comment]
:thumbsup: Thanks.

**Comment by akaspin** [comment]
Thanks a lot!

**Comment by zolotov** [comment]
@ivankorobkov @akaspin have you tried it? Does it work for you? I'm going to make some more optimisations but it's important to know whether I'm on the right way.

**Comment by ivankorobkov** [comment]
0.9.337 resolves the autocompletion freeze for me. Before it CPU went up to 100% and UI froze on autocompletion for up to several seconds (especially on typing `e` and `n`), plus, Idea constantly generated thead-dumps. I think the issue is better described in #1591.

Now everything works rather smooth.

**Comment by zolotov** [comment]
@ivankorobkov cool, thanks for feedback
