### ISSUE TITLE
A good candidates for inspections

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#1624]
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/

**Comment by dlsniper** [comment]
Interesting, thanks for sharing. I think we should also see what fits from this list: https://github.com/golang/go/wiki/CodeReviewComments

**Comment by eugene-auduchinok** [comment]
These inspections are needed as code with such mistakes won't compile.

Can't Use "nil" to Initialize a Variable Without an Explicit Type
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#nil_init
Using "nil" Slices and Maps (OK for slice and runtime error for map)
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#nil_slices_maps
Strings Can't Be "nil"
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#nil_strings
Strings Are Immutable
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#imm_strings
Comparing Structs, Arrays, Slices, and Maps
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#compare_struct_arr_slice_map
Type Declarations and Methods
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#type_decl_methods
Using Pointer Receiver Methods On Value Instances
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#ptr_receiver_val_inst
Updating Map Value Fields
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#map_value_field_update

**Comment by dlsniper** [comment]
Another place to look for inspections: https://github.com/alecthomas/gometalinter

**Comment by dlsniper** [comment]
I'm going to open separate issues for all the various inspections that the tools mentioned in this ticket have so that we can better coordinate what's missing from the plugin and so on. Right now it's pretty complicated to keep an eye on this.

**Comment by dlsniper** [comment]
I've opened all the related issues. I'll close this one for now. Please reopen if needed. Thank you.
