### ISSUE TITLE
no completion / package function highlighted as non existent

### ISSUE THREAD

**Issue by eau-u4f** [go-lang-plugin-org/go-lang-idea-plugin#1625]
Hello,

I have a Go project, first I could not import it as Go project.

I imported it nonetheless and it see some of the packages, but on my linux installation,
for some reason since the update (today), when I try to access some methods/function from another package, it does not see it and hence does not do any completion.

Some of my (before recognized) function are now highlighted in red like they don't exist.

I guess the code is indexed somehow, regularly, how to make it happens again from scratch?

I'm running it from Clion 1.0.1.

How to fix this?
Thank you for all your work,
eau

**Comment by zolotov** [comment]
Any details please. Plugin version, go sdk, code sample, screenshot

**Comment by eau-u4f** [comment]
Go SDK: 1.4.2
Screenshots of the "highlighted red" and the definition in the package.

![missingdefinition](https://cloud.githubusercontent.com/assets/4609393/7666378/67efe994-fbe3-11e4-8e71-05e575b233e3.png)
![seckeydefinition](https://cloud.githubusercontent.com/assets/4609393/7666380/6df4e024-fbe3-11e4-8739-12e5a8ad7617.png)

**Comment by eau-u4f** [comment]
plugin: 0.9.325

**Comment by zolotov** [comment]
Ok, also please attach screenshot of 'Settings | Go Libraries' screen

**Comment by eau-u4f** [comment]
![golibraries](https://cloud.githubusercontent.com/assets/4609393/7666393/0d74970c-fbe4-11e4-920c-5b4088623892.png)

**Comment by eau-u4f** [comment]
It sees "some" of the information declared in that package, but not all, only one or 2 struct types.
It was working before I accepted the update of the plugin.

**Comment by zolotov** [comment]
/home/eau/dev/go/src/github.com/unix4fun/ac looks like wrong gopath entry, why do you need this?

**Comment by zolotov** [comment]
Also please show how you import ackp package

**Comment by eau-u4f** [comment]
I just saw "project libraries"
so as my libraries (such as ackp) are part of my project I added the project dir in project libraries, i guess it goes deeper on its own to index the symbols doesn't it?

The whole project build perfectly, it did work in previous version, it does not since the updates.
![imports](https://cloud.githubusercontent.com/assets/4609393/7666432/8e3ec73a-fbe5-11e4-96e1-253652c9c23f.png)

**Comment by eau-u4f** [comment]
https://github.com/unix4fun/ac

**Comment by eau-u4f** [comment]
As said previously, it sees that ackp exists, but only propose "some" of the available types for completion. Also, previously detected types are now highlighted in red in other packages, while they were not before the go-plugin update I did this morning.

**Comment by eau-u4f** [comment]
any ideas what could be or could have gone wrong? how can I help tracking down my issue.

**Comment by zolotov** [comment]
It's bug with matching +build flags

**Comment by eau-u4f** [comment]
ok, cool that it is identified, let me know if you need anything else.

**Comment by zolotov** [comment]
Sure, thanks for report, I believe the nightly build with the fix will be available tonight. Meanwhile you can remove `+build go1.4` as a workaround

**Comment by eau-u4f** [comment]
oki doki! will change my plugin repository for the nightly instead of alpha tonight.
Thanks for the fast response and workaround.
Great work! keep it going :)
