### ISSUE TITLE
why is source , i want a jar 

### ISSUE THREAD

**Issue by ToniYang** [go-lang-plugin-org/go-lang-idea-plugin#1626]
i want to install go-lang-idea-plugin for idea which is need a jar .But I can only download source code .

**Comment by dlsniper** [comment]
Reading the readme will let you discover the way of installing the plugin.

**Comment by dlsniper** [comment]
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md#pre-release-builds
