### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1629]
Please see below:

```go
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

type jsonTime struct {
	time.Time
	f string
}

func (j jsonTime) format() string {
	return j.Time.Format(j.f)
}

func (j jsonTime) MarshalText() ([]byte, error) {
	return []byte(j.format()), nil  // j.format() should be resolved but it's not
}

func (j jsonTime) MarshalJSON() ([]byte, error) {
	return []byte(`"` + j.format() + `"`), nil
}

func main() {
	jt := jsonTime{time.Now(), time.Kitchen}
	if jt.Before(time.Now().AddDate(0, 0, 1)) {
		x := map[string]interface{}{
			"foo": jt,
			"bar": "baz",
		}
		data, err := json.Marshal(x)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%s", data)
	}
}
```

**Comment by ignatov** [comment]
Can't reproduce with Go SDK 1.4.2, Mac OS X
![screenshot 2015-05-19 00 02 50](https://cloud.githubusercontent.com/assets/426890/7690170/6fc471a2-fdba-11e4-95ff-370f5f21fcd6.png)

**Comment by dlsniper** [comment]
You are right, sorry, I've forgot to mention that it happens only if you use a scratch file in a go project. Then it doesn't work. I'm not sure it it's important or not in this case (to have it for 1.0 release I mean).

**Comment by ignatov** [comment]
It's completely separate platform issue – to support a proper symbol resolution for scratches.
