### ISSUE TITLE
Inetllij 14.1.3 - build 141.1010 is not supported

### ISSUE THREAD

**Issue by nitsanfiverr** [go-lang-plugin-org/go-lang-idea-plugin#1630]
Hey All, 
Just updated my intellij to latest version and Go support just gone. Tried to create a new project and add a go file but looks like the SDKs are not recognised by intellij (http://cl.ly/image/450Y0U1k1U0V).
Tried to re-add the link to alpha repository with no luck.
Any suggestion ?

BTW - great plugin. Thanks.

**Comment by nitsanfiverr** [comment]
Update - tried to download older version of intellij and update the plugin to version 5047 - still not working. same issue, the SDK is not recongnised. I'm working on OS X Yosemite 10.10.3. go version 1.4.1 and 1.4.2.

**Comment by nitsanfiverr** [comment]
Fixed.
Needed to re-add the plugin and reinstall it! now it's working.

**Comment by dlsniper** [comment]
Hi @nitsanfiverr can you please share more details? I didn't understood where you've got the 5047 version as I'm pretty sure there's no such release. As for the SDK being recognized, it should work even on IDEA 14.1.3 (which is the one I'm using right now, but on Linux not OS X).
Also, which alpha / nightly links are you using for the SDK? They've been updated a while ago, please see them in the README.
Thanks.
