### ISSUE TITLE
Allow customising gofmt path

### ISSUE THREAD

**Issue by nubela** [go-lang-plugin-org/go-lang-idea-plugin#1632]
Hi,

I'm not wrong, code formatting with go-lang-idea-plugin uses gofmt (correct me if i'm wrong). However, there are some annoyances such as gofmt not removing unnecessary import lines.

There are some gofmt replacements that does that, and I'd like to change the gofmt default behavior to a gofmt alternative.

If you can find time, it'd be great if this feature can be supported down the road.

Thank you!

**Comment by dlsniper** [comment]
Hi, goimports is also supported, albeit it doesn't have a shortcut assigned. Is this what you are looking for? As for the underlying formatting engine, this will get better in time (and with help from the community). There's also a ticket to support autoremove of unused imports at save time (but that's a bit more complicated) afaik. Does this help?

**Comment by dlsniper** [comment]
I've forgot, goimports is "hidden" somewhere in the edit menu, towards the end of it (I think :D)

**Comment by nubela** [comment]
Ahh, I never noticed goimports. But I'm guessing I can't assign a keyboard shortcut now, eh? Is this planned?

That aside, how can I help with the project?

**Comment by nubela** [comment]
Ok, managed to assign a KB shortcut, so that works. I wonder if it is possible to have an option to do gofmt + goimports

**Comment by dlsniper** [comment]
You don't need gofmt + goimports, goimports does gofmt + import stuff you need.

**Comment by nubela** [comment]
Oh amazing, thank you!

**Comment by dlsniper** [comment]
Ok, so should I close this then as the issue, run goimports, is "fixed"?

**Comment by nubela** [comment]
Yes please! Thanks again for your help.

**Comment by dlsniper** [comment]
You're welcome, glad I could help. Enjoy using the plugin and if there's anything you bump into feel free to ask us.
