### ISSUE TITLE
refactor remove the whole function prototype.

### ISSUE THREAD

**Issue by eau-u4f** [go-lang-plugin-org/go-lang-idea-plugin#1634]
Hello,

Try to rename a function name to be refactored and all calls to be modified too in the whole project.
The entire function prototype is being deleted and have to be rewriten, while before just the function name was modified (not the function prototype).

Running:
Clion: 1.0.2
Plugin version:  0.9.328 (nightly builds channel)
Ubuntu Linux

HTH

**Comment by dlsniper** [comment]
Hi, I'm not sure what exactly is the problem. As far as I can see, the only issue right now is that if you refactor a function, by just renaming it, from the interface the implementations are not refactored and same goes for the other way around. Is this what you mean?
Or you want to have a refactoring with the parameters as well.
Can you please provide a concrete example, that would help make the case a bit more clear.

Thank you.

**Comment by eau-u4f** [comment]
Sorry if i'm not clear, terminology is not perfectly clear in my head,
basically I want to rename a function and it will reflect the change everywhere that function is called.
Before when i was doing it, it was just renaming the function name and then changing it everywhere, now it's deleting the entire prototype with it, i have to retype everything, may be it's on purpose?!

HTH.

**Comment by zolotov** [comment]
Hi. We need code: given code, name of refactoring that you're doing, expected result and actual result. Thank you.

**Comment by ignatov** [comment]
@eau-u4f are you talking about interface method and it implementations?

**Comment by eau-u4f** [comment]
I'm sorry I could not answer right away, preparing a reproducible example that I can link from the golang playground.
@ignatov : I'm trying to rename a function, the bluebox highlight the function name i wanted to rename, it rename everything including the prototype which get deleted, so I undo, but it does not happen all the time, so let me produce an example that trigger this issue all the time, as I'm in a rush (work wise), it will take some days probably, sorry for that. ttyl.
eau.

**Comment by eau-u4f** [comment]
I'm sorry I could not answer right away, preparing a reproducible example that I can link from the golang playground.
@ignatov : I'm trying to rename a function, the bluebox highlight the function name i wanted to rename, it rename everything including the prototype which get deleted, so I undo, but it does not happen all the time, so let me produce an example that trigger this issue all the time, as I'm in a rush (work wise), it will take some days probably, sorry for that. ttyl.
eau.

**Comment by dlsniper** [comment]
I'll close this as it doesn't have feedback for almost half a year now. @eau-u4f please feel free to reopen it in case you can come back with additional feedback. Thank you.
