### ISSUE TITLE
Find Usage of a Type Receiver.

### ISSUE THREAD

**Issue by eau-u4f** [go-lang-plugin-org/go-lang-idea-plugin#1635]
Hello,

Trying to find usage of a local type received methods, It answers None, while there are several, 
as shown on the following screenshot:
![findusage](https://cloud.githubusercontent.com/assets/4609393/7726126/43a0216a-ff00-11e4-846a-a708b3f7174c.png)

ToDER() method is used in a another Type receiver just below on the screenshot, ToPEM() method.

HTH,
Rgs,
eau.

**Comment by ignatov** [comment]
Can't reproduce, please share a code sample for reproducing.

**Comment by dlsniper** [comment]
@ignatov, I might be wrong on this one but at least according to the the example, the file that the @eau-u4f has is in the libraries of the project, not the project itself, so in this case, shouldn't the search scope be altered by the user to include libraries as well? At least that's how I've seen the search for usages works in Java.

**Comment by eau-u4f** [comment]
will do, I have not answered to both issues i have opened, sorry again for that, under work load.

**Comment by eau-u4f** [comment]
will answer, please give me some time, being under workload, that's why i'm silent, will retest with the nightly updates i've seen being pushed and provide a reproducible test.

**Comment by ignatov** [comment]
Please reopen if needed.
