### ISSUE TITLE
project file gone bug.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1637]
I have a golang project I used to be setuped correctly.
After some git clean command,it becomes : 
![image](https://cloud.githubusercontent.com/assets/1107541/7751486/dc0d073a-000c-11e5-8ef2-78c0d267b5b1.png)
![image](https://cloud.githubusercontent.com/assets/1107541/7751580/68c5551a-000d-11e5-894e-0d44eea977b1.png)
![image](https://cloud.githubusercontent.com/assets/1107541/7751586/7567d48c-000d-11e5-9583-34dbd06505b4.png)

**Comment by dlsniper** [comment]
that's because you've removed the ```iml``` file which describes your module setup. Please create the project again (and don't add the .iml file to the gitignore). You can also create the module again and keep the existing project.

**Comment by bronze1man** [comment]
Thanks for your help.
Import Modules solve this problem.

**Comment by dlsniper** [comment]
Yaaay, glad it worked!
