### ISSUE TITLE
Switch/case operators indentation

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1638]
Starting with this:
```go
switch myVar {<caret>}
```
and pressing enter gives this:
```go
switch v {
    <caret>
}
```
while it is more appropriate to have this:
```go
switch v {
<caret>
}
```
because ```case``` is not indented, but has the same indentation level as ```switch```.

**Comment by ignatov** [comment]
Please specify your build. A few days ago I've fixed the same issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/35b54c8b41e44572e1ea2d876277a113177f3da4

**Comment by dmitry-vovk** [comment]
Just checked on the latest, could not reproduce.
