### ISSUE TITLE
IDEA freezes on app run

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1642]
For the last couple days I experience strange behavior of IDEA (IU-141-1192.2) with nightly build (0.9.330).

I have project with run configuration. When I start the IDEA and click Run, it works fine running my app. But after I made some changes to the sources and click Run, it completely freezes with "Please wait..." message at the status line. I can see two /usr/lib/jvm/java-8-oracle/bin/java processes eating 100% CPU each. The only way to get it back is to kill it with SIGKILL (SIGTERM does not work). I can reproduce this all the time on two different machines (Ubuntu 12 and 14), but with only one of my projects.

I noted that freeze happens only when I have Run window left open and when the Run window contains error message telling it unable to run the app due to errors. If I close the window  all works fine.

**Comment by dlsniper** [comment]
Hi, can you please attach any logs that idea generates? I'd advise first to clear the logs directory, start IDEA and replicate the issue then save and send them.

Also, you might want to have a look into this: https://intellij-support.jetbrains.com/entries/23348667-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond as it seems to correspond to your description of the problem.

Thanks.

**Comment by dmitry-vovk** [comment]
Ok, I got IDEA opened, cleared the logs and reproduced the issue. Here are two dumps that appeared after killing the frozen IDE: https://gist.github.com/dmitry-vovk/478b99874f224bc96093

Hope it helps.

**Comment by dlsniper** [comment]
Thanks. One least thing that might be also helpful would be to know if this happens regardless of project, say a simple Hello World type or it's in a more complex one only. That's about all the details I can think of right now that either @zolotov or @ignatov might need for this. Thank you!

**Comment by dmitry-vovk** [comment]
The issue is reproduced with just one of my projects (which holds about 200 files), but on two different Linux machines. I tried with other projects, but all is fine.

**Comment by dlsniper** [comment]
I've managed to replicate this! :D 

First of all, it only happens if you run the plugin in a standalone installation of IDEA. If you run IDEA from IDEA it doesn't crash (think of developing the plugin and running IDEA to see the results / debug it).

How to replicate this:
- create a go run configuration on a file that won't compile (say for example it has a syntax error) and add to the ```Go tool arguments``` something like: ```-o demoexec```
- run the configuration and it will break due to the syntax error (but the IDE will still work)
- edit the run configuration and remove the ```Go tool arguments``` content
- run the configuration again and this time around the IDE will break.

Here's the automatic thread dump I've got from the IDE: https://www.dropbox.com/s/tdx0iyn8x2na7me/threadDumps-20150525-143048-IU-141.1192.zip?dl=0

**Comment by ignatov** [comment]
Is it still actual?

**Comment by dmitry-vovk** [comment]
Looks like it is no more relevant. Did not experience with latest builds.

**Comment by roncohen** [comment]
FWIW I'm still experiencing this. It's characteristic in that it always freezes up on the second run, if the first one failed.

**Comment by dlsniper** [comment]
@roncohen can you please open a new issue and provide more details? What's the IDE version (and name), what's the plugin version, what's the run configuration like? I'm currently on latest master and I don't have this happening, nor do I have it for some time now. With more details will be able to fix the issue. Thank you.

**Comment by roncohen** [comment]
@dvirsky Thank you for the incredibly fast reply.  I just updated PyCharm from 4.5.0 to 4.5.3 and the problem went away. Sorry for the noise and thank you for the great work.

**Comment by dlsniper** [comment]
Happy to hear it worked and thanks for the nice words. Have fun developing with Go on PyCharm ;)

**Comment by dvirsky** [comment]
@roncohen I don't know why I'm mentioned (probably a typo), but you're welcome ;P
