### ISSUE TITLE
IntelliJ freezes in every a few minutes

### ISSUE THREAD

**Issue by tomohiro-n** [go-lang-plugin-org/go-lang-idea-plugin#1644]
Hi,

* IntelliJ Version: 141.1010
* OS Version: Mac OS Yosemite 10.10.3
* JDK Version: 1.8.0_45
* Plugin Version: 1.0.0.alpha#325

I really like this plugin but IntelliJ hangs in every a few minutes and I need to force quit the application every time it occurs.
I have used IntelliJ for a long time but am new to Go and this plugin so it might be due to my terrible way of writing this language.

Sample Code
https://github.com/tomohiro-n/go-twitter

Thread Dump
https://gist.github.com/tomohiro-n/b74d22f7a82ca76aac87

I took thread dumps twice and apparently the only thing related to this plugin seems to be that
_com.goide.codeInsight.imports.GoImportOptimizer.commit(GoImportOptimizer.java:226)_
is in _java.lang.Thread.State: WAITING (parking)_

Thank you,
Tomo

**Comment by zolotov** [comment]
Can't recreate and don't see anything suspicious in thread dump. Is this reproducible with disabled go plugin? Does UI freeze on these moments? When did you take a thread dump? Does log directory contains automatically thread dumps?

**Comment by tomohiro-n** [comment]
Thanks for looking at it.

> Is this reproducible with disabled go plugin?
I'll try it. However I haven't experienced UI freeze except when I edit Go files recently.

> Does log directory contains automatically thread dumps?
> Does UI freeze on these moments?
Yes, but I took a thread dump after the UI froze through jstack before shutting it down. Now I checked IntelliJ's log directory and I could find many dump files but the contents are almost the same as what I provided. I'll update with more details next time this occurs.

**Comment by zolotov** [comment]
Ok, looking forward to update. Thanks.

**Comment by tomohiro-n** [comment]
1. I've used IntelliJ for a day with this plugin enabled for another project in html/CSS/TypeScript and no significant error occurred.
2. Later, I created another very simple project in Golang, only main.go, without having any third-party dependencies and UI froze in several minutes. Thread dumps look very similar to yesterday's one.
https://gist.github.com/tomohiro-n/b7fd98b36cea56c84929

Given that my OS and JDK are quite standard but other people are not impacted as far as I can see, I suppose this conflicts with another plugin I have? I use IntelliJ for many types of projects such as for Java, Node.js, Python, PHP and 135 plugins are enabled. Another possibility might be that some of my IntelliJ settings are not so normal and they somehow cause deadlock with this plugin's behavior?

I'm happy to provide further information and will do when I find something but let me know if you could point out a possible cause or a solution.

Thank you.

**Comment by tomohiro-n** [comment]
Looked into idea.log but nothing suspicious could be found...

**Comment by dlsniper** [comment]
@tomohiro-n can you do a screencast of what you are doing when this happens? I can't reproduce this either unfortunately. I'm hoping I can find something there that would help me reproduce it. Also, are you using any of the go fmt / goimports / file watcher plugin / gin (the one that reloads binaries when you save files)? Thanks.

**Comment by tomohiro-n** [comment]
I use IntelliJ in very standard way (edit source, sometimes switch to other apps, run programs...) so I'm not certain if screencast helps a lot.
On the other hand, I'm using some of that kind of plugins and agree that they are suspicious. I'm trying to disable them one by one and will let you know if I can find some remarkable difference when I disable one of the those plugins.

**Comment by zolotov** [comment]
The main question is who invokes optimize imports action, and how.
Could you attach log directory (Help | Show Log) and IDE settings (File | Export Settings)?

**Comment by akaspin** [comment]
What happens with imports and autocompletion? Previously, everything worked perfectly except one - ignore "./_.." paths. Freezes really killing.

**Comment by dlsniper** [comment]
@akaspin can you provide any logs, a consistent manner to reproduce it constantly, any codebase on which this happens? It's really hard to troubleshoot things like this without a concrete way to reproduce it. Thank you.

**Comment by akaspin** [comment]
@dlsniper I'm already provide logs later in #1623. Ok. Again https://gist.github.com/akaspin/909d68c23c7d47d0406a

**Comment by zolotov** [comment]
@akaspin there are two problems: thread dumps not really descriptive and I can't reproduce freezes. Maybe sharing the project could help.

**Comment by akaspin** [comment]
@zolotov I can't share project: commercial reasons. But my typical setup is project with many modules. Again: previously, everything worked perfectly. With exactly same setup.

**Comment by dlsniper** [comment]
@akaspin how many modules? Of which type? What's your GOPATH like, what settings do you have for Go Libraries do you have configured, do you run anything in background that monitors the files as well? Have you updated any other plugins recently? What happens if you run with only the Go plugin and the default IDEA plugins? 

I do understand that you can't share the code, but please try to report everything from your setup as for example, the multiple modules is a new piece of information. 

Thank you.

**Comment by zolotov** [comment]
@tomohiro-n I've located the problem, new IDEA build will help you a little, there will be exception instead of freezing. 

> Could you attach log directory (Help | Show Log) and IDE settings (File | Export Settings)?

They're still needed.

**Comment by tomohiro-n** [comment]
@zolotov you mean EAP by new IDEA? I checked for updates from the app and it says my version is the latest.

> Could you attach log directory (Help | Show Log)

My last gist, https://gist.github.com/tomohiro-n/b7fd98b36cea56c84929, is from (Help | Show Log).
Regarding(File | Export Settings), I'm a bit afraid to do it since I'm not sure how much personal information will be included in the file.

I'm not confident enough because I've been tied up with other tasks today but apparently disabling one of the plugins, Save Actions (https://plugins.jetbrains.com/plugin/7642), increased the stability. No freeze occurred in the last 30 minutes. It's not long enough to prove so I'll update as soon as I can.

**Comment by zolotov** [comment]
Yes, I mean EAP.

> My last gist, https://gist.github.com/tomohiro-n/b7fd98b36cea56c84929, is from (Help | Show Log).

I didn't need threaddumps, I needed logs.

Sorry, can't help you then. Save Actions plugin looks like reason of wrong `optimize imports` invocation, so likely it will work ok after disabling plugin.
