### ISSUE TITLE
Tab completion does not work for code in a file with a build tag

### ISSUE THREAD

**Issue by lindroth** [go-lang-plugin-org/go-lang-idea-plugin#1649]
If I have a file with a build tag:

```Go
// +build appengine

package blubb
```

Observer that there must  be a new line between the build tag and the package line for the tag to work.

The problem is that any code in a file with a build tag seems to be invisible for the plugin.

**Comment by zolotov** [comment]
I didn't understand how tab completion is related to files visibility and line between build tag and package line.

Anyway, about visibility I'll fix this for project with GAE sdk. Until then, as a workaround you can add `appengine` build flag in `Settings | Go | Build Flags | Custom flags`.

**Comment by dlsniper** [comment]
@zolotov as I haven't had a chance to play with the new UI for build tags support can you please have a look on this? If not, I'll have some time tonight to finally dig it. Thanks.
