### ISSUE TITLE
Unresolved reference when Go SDK is just a module SDK not a project SDK

### ISSUE THREAD

**Issue by pftbest** [go-lang-plugin-org/go-lang-idea-plugin#1650]
plugin version 0.9.325
```Go
package main

import "net/http"

func doIt(arg interface{}) {
	_, err := http.NewRequest("GET", "", nil)
	if err != nil {
		err.Error() // Unresolved reference
	}
}

func main() {
	doIt(nil)
}
```

**Comment by dlsniper** [comment]
I'm sorry, I can't reproduce this. What IDE do you use? What settings do you have? What's your GOPATH, what Go libraries have you configured? Is the Go SDK attached to the module / project? Any further details that could help us identify it are welcomed.

**Comment by pftbest** [comment]
Sorry, my bad, it works fine as a new empty project.
I have two modules in my current project, one is go and another is python.
Module SDK is set to Go 1.4.2, but Project SDK is set to Python. Changing Project SDK to Go fixes the issue. But if i do so, then python module does not work.

**Comment by dlsniper** [comment]
I see, that helps a lot, thanks for reporting :+1:

**Comment by pftbest** [comment]
thank you for your great work!

**Comment by zolotov** [comment]
Should work for builtin types since next nightly. Please feel free to ping me if you'll see any unresolved symbol in Go in your configuration (without go-project sdk)
