### ISSUE TITLE
Comments not indented properly in a long var statement.

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1651]
![screen shot 2015-05-25 at 7 59 33 pm](https://cloud.githubusercontent.com/assets/10180857/7821639/2ac9c304-03be-11e5-997a-1be9f427cfc1.png)

I press command option L and it doesn't format properly, go fmt does it correctly. It'd be nice if the ability to run go fmt was built right in

**Comment by dlsniper** [comment]
Hi,

This is a known problem and there are a few workarounds this for now:
- ```Code | Go fmt file```
- ```Code | Go fmt project```
- ```Code | Goimports file```
- usage of filewatcher plugin + go fmt / goimports on save
- go fmt as a git hook on commiting from the plugin to the VCS

If you have a sample of the code that it's not working with a before and expected after and want to share it that would also help us.

Contributions are welcomed as well as it will help fixing this, or other features faster. You can read the docs on how to get started https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development

I'll close this for now. Thank you.
