### ISSUE TITLE
Scratch file is always named: scratch_1

### ISSUE THREAD

**Issue by vially** [go-lang-plugin-org/go-lang-idea-plugin#1652]
When you create a new scratch file (Tools->New Scratch File... -> Go) it always gets named `scratch_1`.

If you later run it (Run -> Run... -> go run scratch_1) then it gets a random unique filename suffix and the `.go` extension (e.g.: `scratch_1.123123.go` as seen in the tab bar) but the run configuration gets named automatically `go run scratch_1`.

When you later create a new scratch file by repeating the above process the new file is again named `scratch_1` (perhaps because the previous one was renamed to `scratch_1.123123.go`) and the run configuration gets named consecutively: `go run scratch_1 (2)`. This is not such a big deal but It would be nicer if the scratch files would be named `scratch_1`, `scratch_2`, ... so the run configurations would automatically pick a nicer name too like: `go run scratch_1`, `go run scratch_2` and so on.

Edit: After further investigation I saw that if you create three scratch files consecutively **without** running any of them, they get named correctly: `scratch`, `scratch_1`, `scratch_2`, etc. So the problem only manifests itself when you create a scratch file (gets named `scratch_X`), run it (gets renamed to `scratch_X.123123.go`) and then create a new scratch file (gets named again `scratch_X` where X is equal to the previous X).

Tested in Intellij IDEA 14 with plugin version: 0.9.325

**Comment by dlsniper** [comment]
@ignatov I've digged a bit around it and I've realized that in the run configuration the file name changes from scratch_X to scratch_X.rand. Any particular reason for this? If not I guess I could remove it Commit reference: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/542a8001837bdc16f32f5bfe1592c1fc84b0195d
