### ISSUE TITLE
"Use GOPATH that's defined in system environment" option not saving

### ISSUE THREAD

**Issue by Fapiko** [go-lang-plugin-org/go-lang-idea-plugin#1656]
Every time I restart IntelliJ or reopen my project this setting isn't saved and I have to go back into the settings and uncheck it. It's not a huge issue but a minor inconvenience.

I'm using the nightly build, currently 0.9.332 with Intellij build 141.1010.3.

**Comment by dlsniper** [comment]
Hi, Unfortunately I can't replicate this on my setup. 
What values do you use for Go Libraries? Also, can you please attach a log from IDEA? And some steps to reproduce it? Thank you!

**Comment by dlsniper** [comment]
Closing this due to lack of feedback
