### ISSUE TITLE
Can not detect struct initialization using package namespace

### ISSUE THREAD

**Issue by sumsuddinshojib** [go-lang-plugin-org/go-lang-idea-plugin#1657]
if I have the following code in intelliJ ide using this plugin: 

// start of main.go file
```
package main
func main() {
  //following declaration is not determined by the plugin. Though the code works
  // here "pak" is a package and the struct "MyType" is defined in different file
  myStruct := pak.MyType{....}
  // show error at the starting "{" on the previous line, saying "; or newline expected"
  // after the above line the plugin can not detect anything properly.
}
.....
```
//end of main.go file

**Comment by ignatov** [comment]
Please provide a small real code sample, can't understand what happened with your example.

**Comment by dlsniper** [comment]
Also, which version of the plugin are you using, how is your Go Libraries settings look like and what's your GOPATH. I have literally all the projects using the same construct you provided in the sample but I don't have this problem with any of the 0.9.200+ releases. Thank you.

**Comment by dlsniper** [comment]
@sumsuddinshojib what happened with this? How did you managed to resolve it? I'm curious to know so that we can improve the docs if needed or something else in the process of how the plugin works. Thank you.

**Comment by sumsuddinshojib** [comment]
Thanks for the quick response. Your comment helped me to think that, "I didn't set the go path properly on the plugin". I am using ubuntu 14.04. If I write the command "echo $GOPATH" I get the output "/home/{user}/go", as I set it on "/etc/profile" file. $GOROOT is empty. I installed go on "user/local/go", actually extracted the tar file on that directory. Now the plugin on Intellij says "problem with env variable" for both gopath and goroot.

**Comment by dlsniper** [comment]
What version of the plugin are you using? There's no need for such things in the recent releases. 

See here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md#pre-release-builds how you can install it. 
Thank you.

**Comment by sumsuddinshojib** [comment]
Thank you very much. I could make it work using the above link you have given. I was using https://plugins.jetbrains.com/plugin/5047?pr=idea version 0.9.15.3.
