### ISSUE TITLE
404 when trying to add the plugin into IntelliJ from both repos

### ISSUE THREAD

**Issue by philhudson91** [go-lang-plugin-org/go-lang-idea-plugin#1661]
Getting a 404 when clicking to add Go pluging from both repos in IntelliJ

**Comment by dlsniper** [comment]
Hi, I can't reproduce this unfortunately.
Which IDE do you use? What version, which URL are you using exactly? What are the steps to reproduce this? Have you checked the logs for any error there?

Thanks.

**Comment by philhudson91** [comment]
Hey there,

Using both:

alpha: https://plugins.jetbrains.com/plugins/alpha/5047
nightly: https://plugins.jetbrains.com/plugins/nightly/5047

Add either of them to the repositories in IntelliJ, select the repository then click Go to add. After clicking go it returns a 404 error.

Using IntelliJ Ultimate 14.0.3

**Comment by dlsniper** [comment]
>Using IntelliJ Ultimate 14.0.3

It seems that you need to upgrade your IDEA first :)

Please see the readme:
> Pre-release builds can be installed on IntelliJ platform 141.2 or greater. It corresponds to IntelliJ IDEA 14.1, WebStorm 10, PhpStorm 9.

**Comment by philhudson91** [comment]
Oh man I'm so sorry. will close. :)

**Comment by dlsniper** [comment]
Don't worry. Have fun using the plugin.
