### ISSUE TITLE
Clarify what's going to be run and how

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1663]
Right now the plugin does it's fair share of 'magic' in adding paths and setting env vars to the go tool for all the run configurations. It would be nice if we could display this in a nice manner to the user when configuring the runner. I'm not sure how exactly it should look like but it should include the env variables and the command that's going to be executed.

**Comment by dlsniper** [comment]
This was fixed a while ago.

**Comment by zolotov** [comment]
> This was fixed a while ago.

Was it?

**Comment by dlsniper** [comment]
At least when something breaks I can see the command used, which is very useful. Not sure how the env vars should be displayed,maybe just gopath and goroot should be enough?

**Comment by zolotov** [comment]
Yes, I think GOPATH and GOROOT is enough, will add to output
