### ISSUE TITLE
Cannot open Intellij Preferences dialog

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#1665]
Using OSX latest, Intellij latest 14.1.X and the last commit of this awesome plugin `9c2c1e5db07cd13a58380668f42ca5c246354b68` and self compiled the plugin (which always works)

When the Go.zip file is installed and Intellij restarts I'm unable to open the Preference Dialog.
I can only access this dialog window when I uninstall the plugin ... any ideas?

**Comment by dlsniper** [comment]
'Use the Search Luke. Use the Search'. 

Jokes aside, if you self-compiletbe plugin the you should read the Contributing doc which has a section explaining how to build the plugin and that you must have ant and UI Designer plugins activated (in this case the later is not). 

Please enable the UI designer plugin and things will work again :-)

**Comment by SchumacherFM** [comment]
Ups :blush: Thank you very much :-)
