### ISSUE TITLE
Go application running broken if "Output directory" is empty

### ISSUE THREAD

**Issue by akaspin** [go-lang-plugin-org/go-lang-idea-plugin#1670]
853d751630ebd9a2e6a1c9459f72d4d7eab6e4e1 breaks Go Application Run if "Output directory" field is empty.

**Comment by zolotov** [comment]
> And again - no packages.

What does it mean?

**Comment by akaspin** [comment]
> What does it mean?

Ops. Wrong destination. Sorry.

**Comment by dlsniper** [comment]
Thanks, I'll have a look at it but it's strange as I've tested with nothing in the output directory.

**Comment by zolotov** [comment]
Cannot recreate. Logs/OS/error messages?

**Comment by zolotov** [comment]
Can't reproduce
