### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by fireproofsocks** [go-lang-plugin-org/go-lang-idea-plugin#1672]
E.g. http://packages.go-ide.com/goide-osx_386.dmg comes up as ERR_NAME_NOT_RESOLVED

**Comment by dlsniper** [comment]
And that's a good thing :-) 

We don't support those release, please see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md#pre-release-builds for information on how to get the latest version of the plugin that works on all JetBrains IDEs. Please use that combined with IDEA Community or Android Studio if you want a free Go development environment.

**Comment by fireproofsocks** [comment]
Thanks for the update.  It would be more helpful if you removed those links from the site and referenced the above to avoid confusion and the appearance of a broken site.

**Comment by dlsniper** [comment]
I'll ping @mtoader for this as I don't have access to that website but I'm not sure when he'll have time for it. In all fairness, the site was last updated more than one year ago so I didn't even thought about it :)

**Comment by mtoader** [comment]
I'll remove the links from there as soon as a new release is made with the improved plugin.
