### ISSUE TITLE
add "golang" to the name of the plugin in the title

### ISSUE THREAD

**Issue by ingenthr** [go-lang-plugin-org/go-lang-idea-plugin#1674]
In the repository search, even if I add the repositories, I can't search for the plugin with the search at the top in IJ because it won't do the search until you type three characters?  Maybe you should make the title "Go (golang)" or so?

![image](https://cloud.githubusercontent.com/assets/81302/7969043/3850b01a-09e9-11e5-946b-f09adc5db246.png)

Workaround is to select the specific repository:
![image](https://cloud.githubusercontent.com/assets/81302/7969091/7177702c-09e9-11e5-9aba-998d9fa0c366.png)

**Comment by dlsniper** [comment]
Hi, I'll add a PR with golang in the description of the plugin but for consistency I'd leave yhe name as is. What do you guys think?

**Comment by zolotov** [comment]
It was fixed in IDEA platform and will be available in the IDEA 15 EAP
