### ISSUE TITLE
when import name different with package name, can't find reference

### ISSUE THREAD

**Issue by rebill** [go-lang-plugin-org/go-lang-idea-plugin#1675]
for example:
```go
package main

import "gopkg.in/redis.v3"

func main() {
    client := redis.NewClient(&redis.Options{
		Addr:     "127.0.0.1:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
	})
}
```

It doesn't works.

**Comment by dlsniper** [comment]
Please read the readme on how to report bugs. Which plugin version, what's your Go Libraries configuration, where's the project created, which IDE, can you provide a screenshot?

**Comment by rebill** [comment]
I'm sorry, that is my fault. when two packages in my disk at different paths, it won't work. I delete one of that, it works.

**Comment by dlsniper** [comment]
@rebill I don't understand. It should work even if you have two packages that are ```package redis``` in your GOPATH. I have 3 different libraries that provide a package called ```redis``` and it still works.
