### ISSUE TITLE
Missing description for Go section in the settings UI in build 0.9.346

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1677]
Just installed the latest release.  Looking at the `Settings > Languages & Frameworks > Go` and it has `!go.settings.description!`.  I'm guessing that was a bug/oversight

![image](https://cloud.githubusercontent.com/assets/5578559/8060434/481ca8ce-0e93-11e5-824b-d87b1e0634cd.png)

**Comment by dlsniper** [comment]
Good catch, thanks for reporting.

**Comment by zolotov** [comment]
IDEA version?

**Comment by dlsniper** [comment]
For me it happens with 141.1383.1

**Comment by JoeBruner** [comment]
For me it was IDEA 14.1.3, build # IU-141.1010

**Comment by jmhodges** [comment]
For me, 14.1.4 build 141.1532 (Community Edition)

**Comment by dlsniper** [comment]
@zolotov should we close this as it's fixed in 142 branch of IDEA (I've tested with latest EAP).

**Comment by zolotov** [comment]
@dlsniper yes, thanks
