### ISSUE TITLE
"Resolved to several targets" error for all built-in packages

### ISSUE THREAD

**Issue by martyglaubitz** [go-lang-plugin-org/go-lang-idea-plugin#1680]
After the plugin automaticly detected the Go environment installed on the system
and i created a new project, it shows a strange error for all built-in imports.

![resolved_to_several_targets](https://cloud.githubusercontent.com/assets/1542037/8080621/4fe3386c-0f6e-11e5-8f32-e35e59a8e46a.png)

The error lets me guess i scans over the same files several times

I installed go via homebrew on my mac.
GOROOT and GOPATH are set to

    GOPATH=/Users/martyglaubitz/.golang
    GOROOT=/usr/local/opt/go/libexe

I already tried to play around the the Path settings of the detected Go SDK in the settings
but nothing helped.

**Comment by dlsniper** [comment]
Hi, please see https://github.com/go-lang-plugin-org/go-lang-idea-plugin#bugs Also please send screenshots of your ``` Settings | Languages & Frameworks | Go ``` settings. And how did you configured the Go SDK in IDEA? Which plugin version do you use? How did you installed it? Did you compiled it yourself? Which IDE do you use?

**Comment by martyglaubitz** [comment]
Development Machine
![machine](https://cloud.githubusercontent.com/assets/1542037/8080836/18cb55c4-0f70-11e5-98f5-ef080e9a9021.png)

IDE & JDK
![intellij](https://cloud.githubusercontent.com/assets/1542037/8080914/9501bc50-0f70-11e5-9c80-5f04b7b416d5.png)

PLUGIN (installed by steps described in the README of the plugin project under "Pre-release builds")
![plugin](https://cloud.githubusercontent.com/assets/1542037/8080979/01ceb234-0f71-11e5-8b0b-5fcdc2324fab.png)
![plugin_build_flags](https://cloud.githubusercontent.com/assets/1542037/8081049/a0bae44e-0f71-11e5-8929-e56e3b8f9865.png)
![plugin_libraries](https://cloud.githubusercontent.com/assets/1542037/8081077/dd392a66-0f71-11e5-83ff-8d0073dd2331.png)

GO
go version go1.4.2 darwin/amd64

Project Go SDK
Classpath: /usr/local/Cellar/go/1.4.2/libexec/src
Sourcepath: /usr/local/Cellar/go/1.4.2/libexec/src

**Comment by martyglaubitz** [comment]
It should be noted that there **WAS** an Google App Engine SDK installed on the system and a project
in which i used the app engine go SDK worked fine.

But due to deployment issues within app engine i droped GAE and thus completly removed
the app engine SDK from the system.

**Comment by martyglaubitz** [comment]
I configured the Go SDK when creating a new project since the plugin automatically detected the Go SDK installed on my machine and i just used it when it show up in the project wizard

**Comment by dlsniper** [comment]
Much better, thanks. 

So,  the error happes because the Go sdk path is also configured into the Go Libraries. 
Please remove it from there and either configure the Go Libraries to point to where your GOPATH and things should work.

**Comment by martyglaubitz** [comment]
Alright, that did it thanks! :+1: 

By the way: thanks for the crazy fast answer :)
