### ISSUE TITLE
Plugin ignores settings in Go Library panel

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1683]
Using IDEA 14.1.4 RC 141.1531.2, plugin commit: 02ecbaf166e29fe3898aa9a5cb8647392199c485
Ide logs: http://pastebin.com/xp7sZ4FT

Steps to reproduce:
- try to disable the ```Use GOPATH that's defined in the system environment``` -> it will get reenabled when the the IDE starts again
- try to enable the same setting, it won't automatically add the env GOPATH in the list as read-only
- disable the option, remove all Global Go libraries and add a project library path. The project library path won't be attached to the "External Libraries".

My suspicion lies in the line that says:
```
2015-06-15 21:44:15,368 [  61462]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class com.goide.configuration.GoConfigurableProvider$GoCompositeConfigurable
```
but unfortunately I don't have too much time to try and fix it until the weekend.

**Comment by dlsniper** [comment]
CC-ing @simongui as he prompted the discovery of the issue while trying to configure a project to use a project library path for a custom Go project.

**Comment by zolotov** [comment]
> try to disable the Use GOPATH that's defined in the system environment -> it will get reenabled when the the IDE starts again

Will try but doubt that I'll be able to recreate it.

> disable the option, remove all Global Go libraries and add a project library path. The project library path won't be attached to the "External Libraries".

Depends on what you're attaching, likely it works as intended. 

> 2015-06-15 21:44:15,368 [  61462]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class com.goide.configuration.GoConfigurableProvider$GoCompositeConfigurable

It has nothing to do with anything.

And after all I don't see any connection between this issue and problems that @simongui is experiencing.

**Comment by dlsniper** [comment]
> Depends on what you're attaching, likely it works as intended.

I'm attaching the path that would be in the "Global Libraries" (my own GOPATH), there's nothing special for it.

>It has nothing to do with anything.
>
>And after all I don't see any connection between this issue and problems that @simongui is experiencing.

I mentioned it because in his case it would make sense to use the "Project libraries" section to set the GOPATH to ```_vendor```.

I'll try and debug it, but meanwhile, if I should enable some extra logs or something please let me know.

**Comment by zolotov** [comment]
> I'm attaching the path that would be in the "Global Libraries" (my own GOPATH), there's nothing special for it.

This is not the reason to adding this into external libraries group.

> I'll try and debug it, but meanwhile, if I should enable some extra logs or something please let me know.

It's better to attach .idea directory just after changing options and after closing IDE

**Comment by dlsniper** [comment]
Aaaaand I'm an fool. At some point when I changed the idea.sh after I've upgraded to one of the versions, I've forgot to add the ```export``` in front of the ```GOPATH=/path/to/go/path/```` so all the things were broken in that regard. Ignore me
