### ISSUE TITLE
Can not download plugin

### ISSUE THREAD

**Issue by AlejandroVera** [go-lang-plugin-org/go-lang-idea-plugin#1685]
Hi.

I'm trying to download the plugin from PHPStorm. I have added the repository but, when I click on the download button, I get a 404 error.
I think that the xml in https://plugins.jetbrains.com/plugins/nightly/5047 have incorrect values for all the "download-url". Instead of "../../plugin/download?updateId=20062" I think it should be something like "../../../plugin/download?updateId=20062" (one more "../").

**Comment by dlsniper** [comment]
Hi, which version of PHPStorm fo you use? Is it listed in the readme as supported? Thanks

**Comment by AlejandroVera** [comment]
Hi.
Version is 8.0.3 Build #PS-139.1348

**Comment by dlsniper** [comment]
Unfortunately the plugin doesn't support that verison. Please use phpstorm 9 EAP or one of the supported IDEs.

**Comment by dlsniper** [comment]
https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by AlejandroVera** [comment]
OK, thanks for your help.
