### ISSUE TITLE
Error while complete variable name

### ISSUE THREAD

**Issue by rekby** [go-lang-plugin-org/go-lang-idea-plugin#1694]
![screenshot from 2015-06-24 08 34 44](https://cloud.githubusercontent.com/assets/5411205/8323363/ffc0aebc-1a4b-11e5-9351-8c87e3ac42eb.png)

completion work good in other languages (Java) and for methods name.

I use Intellij IDEA community edition 14.1.2.
I have problem few days.
Go plugin was updated today and few days ago from https://plugins.jetbrains.com/plugins/nightly/5047

**Comment by dlsniper** [comment]
Can you share a code sample that we can run and reproduce the error? Otherwise it's impossible to get it fixed. Also, which version do you have exactly? And what's your Go Libraries configuration? Thanks

**Comment by rekby** [comment]
It reproduced in empty project with one main function and a var:
![screenshot from 2015-06-24 09 26 55](https://cloud.githubusercontent.com/assets/5411205/8323913/4230b646-1a53-11e5-8692-a0e3366b2af6.png)

code: 
```
package src

func main(){
	var asd string
	as
}
```

In the example I have only project's source in go libraries:
![screenshot from 2015-06-24 09 29 38](https://cloud.githubusercontent.com/assets/5411205/8323948/a3c0e3fe-1a53-11e5-9803-bf7993765fb4.png)

I don't know how to check commit hash. From plugin.xml:
 version: 0.9.357
Description:
 Support for Go programming language.
Alpha pre-release of the 1.0.0 version.
Doesn't contain all the functionality of the 0.9.x branch but has a completely reworked internals.
 It's faster than 0.9.x, refactoring works to some degree and has native support for gopath packages.

Compatibility
Plugin can be installed on IntelliJ platform 141.2 or greater. It corresponds to IntelliJ IDEA 14.1, WebStorm 10, PhpStorm 9

change-notes:
Initial GAE support: running dev server. Requires resetting project SDK.

Last time I have updated today from nightly repository by IntelliJ update system.

Go version:
go version go1.3.3 linux/amd64

OS: Ubuntu 14.04

I use go bash proxy-script which set right GOPATH for every of my project (set GOPATH to dir, that contains src dir).

**Comment by dlsniper** [comment]
Thanks for details.
Please remove the project dir from the Project Libraries section and it should work out just fine. If it doesn't, let us know.

**Comment by rekby** [comment]
I have tried: It isn't help.

I have added the project dir in Project Libraries becouse without this the plugin doesn't work good (doesn't find code from near folders and show errors in imports, var/method names from other packages and etc).

**Comment by dlsniper** [comment]
How is the project layout on the disk? 
- project dir
- GOPATH
- where is the Go sdk installed
If by any chance the project is open source, can you please share it? 

Thanks

**Comment by rekby** [comment]
project dir:
/home/rekby/git/gotmp

GOPATH (when start go with working dir /home/rekby/git/gotmp/src or any subdir:
go env | grep GOPATH
GOPATH="/home/rekby/git/gotmp"

global GOPATH is empty.

go sdk installed in: 
/home/rekby/bin/go-1.3.3

but go sdk NOT included in PATH. I have bash script with name "go" in PATH to run it instead of go binary and change GOPATH on fly:
https://gist.github.com/rekby/87857ccd9215ed0baed4

it set GOPATH to dir, that contains src dir of current project.

**Comment by dlsniper** [comment]
Ok, got it. The problem happens because the file you aare editing is in GOPATH/src but the package is called ```src``` not ```main```. Try changing that please. Normally a package called src should be placed in GOPATH/src/src for go to work.

**Comment by rekby** [comment]
I tried to move main.go in /home/rekby/git/gotmp/src/src - it isn't help.

The plugin CAN parse the module and show suggestions for methods, types, etc. It show right count on empty lines for suggest of variables and right complete variable name, when I press space.
It only show empty lines in suggestion list for var names (but good for methods, types, etc).

![screenshot from 2015-06-24 10 29 11](https://cloud.githubusercontent.com/assets/5411205/8324780/72b59d96-1a5c-11e5-8438-5e63a27aa7d3.png)

**Comment by ignatov** [comment]
Already fixed. Sorry for any inconveniences.

**Comment by ignatov** [comment]
The build with a fix (0.9.361) has been already uploaded to the plugin repo. Please check for updates.

**Comment by rekby** [comment]
The problem is solved. Thanks.
