### ISSUE TITLE
The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by 631768417** [go-lang-plugin-org/go-lang-idea-plugin#1697]
win7 x64 
go version go1.4rc2 windows/amd64

path : C:\Go

**Comment by dlsniper** [comment]
Thanks for reporting. Can you please paste the content of ```$sdk/src/runtime/zversion.go```? 
Also, after doing that, I highly suggest that you update to the latest version of stable Go (1.4.2).
Thank you.

**Comment by zolotov** [comment]
@631768417 plugin version?

**Comment by 631768417** [comment]
latest version

**Comment by dlsniper** [comment]
> latest version

Yes, but which one?

**Comment by 631768417** [comment]
我从github上下载下来，自己编译的。

version: 0.9.348

**Comment by dlsniper** [comment]
And the contents of: ``` $sdk/src/runtime/zversion.go ``` ?

**Comment by 631768417** [comment]
package runtime

const defaultGoroot = `c:\go`
const theVersion = `go1.4rc2`
var buildVersion = theVersion

**Comment by 631768417** [comment]
Dan teng .... Go Plugin Verson : 0.9.348

**Comment by dlsniper** [comment]
Thank you :)

**Comment by 631768417** [comment]
How to deal with...

**Comment by 631768417** [comment]
Use the go1.3 version?

**Comment by dlsniper** [comment]
Use go 1.4.2 from https://golang.org/dl/ (go1.4.2.windows* ) or wait for the next release, I'll fix this soon.

**Comment by dlsniper** [comment]
The PR with the fix; https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1707

**Comment by 631768417** [comment]
Thanks!!!!!  Already can be

**Comment by 631768417** [comment]
。。。用英文真心别扭。。 可以了。。换成最新版Go1.4.2 可以用了。。
