### ISSUE TITLE
Run tests and gocheck tests from context

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1698]
It would be nice if I could right click anyway in the test function and have an option to run just that single test function instead of the whole test suite / currently selected runner.

I only have gocheck tests at the moment so that's why I've put both gocheck and normal go tests here. Also benchmarks and examples should behave this way.

This functionality was (is?) in the old-master branch (for use as a reference).

**Comment by zolotov** [comment]
![screenshot 2015-06-26 12 40 07](https://cloud.githubusercontent.com/assets/140920/8374725/7b8ba5aa-1c00-11e5-8fa1-5afb45f74344.png)

**Comment by dlsniper** [comment]
I guess because I already have a run configuration selected, I don't have that.

![snapshot101](https://cloud.githubusercontent.com/assets/607868/8374901/3d1db4c2-1bf9-11e5-8322-a414d8938fa4.png)
![snapshot102](https://cloud.githubusercontent.com/assets/607868/8374902/3d1e3d0c-1bf9-11e5-860e-655b3fe1c200.png)
![snapshot103](https://cloud.githubusercontent.com/assets/607868/8374900/3d1d055e-1bf9-11e5-8fa1-401b2e44f67d.png)

Also, when I delete the saved test configuration, it runs everything instead of the selected test:
```
/usr/local/go/bin/go test -v -tags postgres github.com/tapglue/intaker/v02/server -run ^Test$ -check.vv
```

I think this should be kept open.

**Comment by zolotov** [comment]
It's obviously bug, file a bug report about it with code samples

**Comment by dlsniper** [comment]
Ok, I'll file a bug for that.

But in Java when I am in a Test class, regardless of which run configuration I have selected, it will offer to run the current either for the class or for method I'm in. If then I step out and go back to project classes it won't offer to run anything but that's ok.

That's what I wanted to suggest with this issue, to allow people to run whatever they have at cursor rather that the selected run configuration.

**Comment by zolotov** [comment]
> But in Java when I am in a Test class, regardless of which run configuration I have selected, it will offer to run the current either for the class or for method I'm in.

I know how it works in Java and it works in go in the same way. The bug is about handling your particular code, so please just give me code sample, expected result, actual result.
