### ISSUE TITLE
Allow to pass arguments in Go DBG configuration

### ISSUE THREAD

**Issue by mkabischev** [go-lang-plugin-org/go-lang-idea-plugin#1701]
I need to pass some arguments to my application, but i can`t specify them on Go DBG configuration screen, so i have to change values direct in code.

**Comment by dlsniper** [comment]
Thanks for reporting. The GDB runner is experimental at this point due to GDB itself not supporting Go properly: https://golang.org/doc/gdb as such not much time was invested into this particular part of the plugin so far.

**Comment by dlsniper** [comment]
We don't support GDB for now as such I"m closing this. Please use a newer version of the plugin which uses delve as a debugging backend.
