### ISSUE TITLE
Make and Debug buttons do nothing

### ISSUE THREAD

**Issue by AndreKR** [go-lang-plugin-org/go-lang-idea-plugin#1708]
The Run button works, but when I click the Make or Debug button, nothing happens.

For debugging, I tried to check the checkbox described in http://stackoverflow.com/a/28106067/476074 but I couldn't find it anywhere - that seems to be for a different IDEA version? I am using 14.1.4. and if that is supposed to be the Run Configurations dialog, it looks very different for me: 
![image](https://cloud.githubusercontent.com/assets/1188538/8394958/3767b8c6-1d51-11e5-8790-f7d9135706d3.png)

I tried with the alpha from the Repository and also with a version I compiled myself from the current master (17499b2f) following the instructions from http://pivotallabs.com/setting-google-go-plugin-intellij-idea-13-os-x-10-8-5/.

go version go1.4.2 windows/amd64

**Comment by dlsniper** [comment]
Hi, both questions are covered in previous issues, please search for them using the builtin search from github. Thank you.

**Comment by AndreKR** [comment]
I searched for "make" but I admit I did not read all 29 issues, but I also searched for "debug" and I read all 6 issues and none of them is about it not working at all.

**Comment by zolotov** [comment]
@AndreKR 
> I admit I did not read all 29 issues,

There are 285 issues

make: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1453#issuecomment-83124378

I've disabled debug button, use Go GDB run configuration instead. But: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1645#issuecomment-105224937
