### ISSUE TITLE
Modify the CTRL+hover output to show function signature

### ISSUE THREAD

**Issue by JoeBruner** [go-lang-plugin-org/go-lang-idea-plugin#1713]
This has bugged me for quite some time.  Here is an example of holding CTRL while hovering over a method/function in different languages:

Java:
![image](https://cloud.githubusercontent.com/assets/5578559/8457591/38b59ffe-1fe0-11e5-81e1-aa874d61935d.png)

Python:
![image](https://cloud.githubusercontent.com/assets/5578559/8457843/b56d384e-1fe1-11e5-84a1-36b625b960c8.png)

Go:
![image](https://cloud.githubusercontent.com/assets/5578559/8458072/f8f2e0cc-1fe2-11e5-9a0b-837970142cab.png)

As you can see with Java and Python, doing the CTRL hoverover will show what the parameters are to the method and what it might return.  With the Go plugin, all it shows is what file the function came from, which isn't nearly as useful.  This is is especially annoying in languages like go where you can do

    x := foo(y, z)

because I have no idea of telling what x is (is it an int? string?  interface{}?).

**Comment by dlsniper** [comment]
Hi, as a quick workaround you can use the quick documentation feature to get the output you desire.

@ignatov or @zolotov I can have a try at this one if you tell me where to look for it. Thank you

**Comment by ignatov** [comment]
Please implement com.intellij.lang.documentation.DocumentationProviderEx#getQuickNavigateInfo in com.goide.GoDocumentationProvider.

**Comment by ignatov** [comment]
@dlsniper Please don't use bold, pre and code tags.

**Comment by ignatov** [comment]
Fixed

**Comment by pierrre** [comment]
Thank you!
