### ISSUE TITLE
View Parameter Info for returned functions

### ISSUE THREAD

**Issue by gabrielf** [go-lang-plugin-org/go-lang-idea-plugin#1718]
View => Parameter Info works great for simple functions but it does not work for functions created by and returned by other functions. This applies both when trying to call the returned function immediately and when storing it in a variable.

In the code below View => Parameter Info shows:

* `s string` at `$1` when `i int` is expected
* No parameters are shown at `$2` when `i int` is expected

```go
func main() {
    ReturnsFunc()($1)

    f := ReturnsFunc()
    f($2)
}

func ReturnsFunc(s string) func (int) {
	return func (i int) {
		return 1
	}
}
```

**Comment by ignatov** [comment]
The first case has been fixed.

**Comment by ignatov** [comment]
Obsolete.
