### ISSUE TITLE
Add support for platform specific package implementation

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#1721]
**Steps to reproduce:**
1. Inside a package, create two files, e.g. ```proc_linux.go``` and ```proc_darwin.go```
2. In ```proc_linux.go``` add package comment ```// +build linux``` and in ```proc_darwin.go``` add ```// +build darwin```
3. In each file add a function with the same name, e.g. ```func process() {/*...*/}``` as if it implements platform specific functionality.

**Actual result:** functions are marked as duplicate.
**Expected result:** functions are not marked as duplicate.

**Comment by zolotov** [comment]
There is platform specific package implementation support. Just missed for this particular inspection

**Comment by dmitry-vovk** [comment]
Yes, there is. I can see a message above editor window "'series_macos.go' doesn't match the target system", and it correctly figures out what file to use to look for imported types and functions. It is just this one inspection.

**Comment by ruseinov** [comment]
There is a problem with this, when you want to put a tag on a test, say, `// +build integration` it also says something about the system and autocomplete stops working in this file, which is quite annoying.

**Comment by ruseinov** [comment]
http://uploadr.obnovlenie.ru/uploads/lazycoder-2015-10-09-195703.png

**Comment by zolotov** [comment]
>  autocomplete stops working in this file, which is quite annoying.

Because this files doesn't match the target system (due to build flag), IDE cannot know how to resolve and complete in this files.

It's the same if you edit file with `// +build linux` on windows, IDE has know idea how to resolve symbols in this file – via windows-specific files or via linux files.

**Comment by ruseinov** [comment]
I understand why it's not working, that's pretty clear from the issue.

Seems like a bug to me, since you could use build flags for all sorts of things and then all of a sudden the plugin turns off the autocomplete because of this assumption. 

Any workaround for that?

**Comment by zolotov** [comment]
> Seems like a bug to me, since you could use build flags for all sorts of things and then all of a sudden the plugin turns off the autocomplete because of this assumption.

It's hard to call an assumption. When `go build` will compile your files it ignore some of them because of build flags and it's not a bug or assumption.

Of course there is a way to fix it and IDE shows it in a big yellow plate on the top of file: open settings and fill it with target system properties that will be used for compile. I believe in your case you should tell IDE that target system supports `integration` flag.

**Comment by ruseinov** [comment]
Gotcha, that sounds fair enough. It's just not very intuitive, because you
can use build flags to, say, separate unit and integration tests and so
forth. But, indeed, the workaround is good enough.

Thanks

**Comment by ruseinov** [comment]
It was not clear at first that I have to enter this flag into custom flags,
does not really catch the eye. Probably has to do with the end of the day.

Anyway, thanks, that's looking good!

**Comment by zolotov** [comment]
I'm glad that it works for. If you have any thoughts how to make it more discoverable, please share. Maybe change notification text, or add description somewhere, etc.

**Comment by ruseinov** [comment]
Yeah, maybe something like hey, if that does not work for you and it's not
an os build flag - add this flag to custom flags field or something.

But, again, might have to do with the lack of attention on my side, been a
long day.

**Comment by zolotov** [comment]
>  It's just not very intuitive, because you can use build flags to, say, separate unit and integration tests and so forth. 

Hm, I've never thought about this case.

> Yeah, maybe something like hey, if that does not work for you and it's not an os build flag - add this flag to custom flags field or something.

Thanks for suggestion, will try to do something with that.

**Comment by dlsniper** [comment]
> Thanks for suggestion, will try to do something with that.

Could we use an inspection / quick fix for the flags? Whenever the current file flags doesn't match with the used flags we could give the use the ability to change the flags accordingly (or maybe just open the configuration dialog in the beginning). 

What do you think?

**Comment by ruseinov** [comment]
It's alright, these cases is something you never think of before it occurs
to you, basically hacking you way to the goal using standard go features.

I stumbled upon this suggestion when I started thinking how to separate
tests in a way that I could run go test and have my unit tests executed and
go test something to execute something else.

**Comment by ruseinov** [comment]
Sounds good, maybe just two baloons, one that immediately adds a flag and
the other one that lets you do it by hand, or opens a dialog and enters the
integration flag into custom flags field.

Depends on how flexible intellij could be about that, not really familiar
with plugin restrictions there.

**Comment by zolotov** [comment]
> Could we use an inspection / quick fix for the flags? Whenever the current file flags doesn't match with the used flags we could give the use the ability to change the flags accordingly (or maybe just open the configuration dialog in the beginning).

> Sounds good, maybe just two baloons, one that immediately adds a flag and
the other one that lets you do it by hand

Agree, will try. Thanks.

**Comment by Mingan** [comment]
I'm using build tags for test separation as well and while I get the panel with Open target system settings  where I can add those tags, this information isn't persisted and next time I start Idea I have to do it all over again. Is there some way I can specify this information to make it stick?

Idea, build 141.2735
Go plugin version 0.9.562

**Comment by zolotov** [comment]
@Mingan can't recreate, please file a separate issue and attach .idea/ directory from your project (after you've change build flags settings)

**Comment by ruseinov** [comment]
By the way, I have the same issue - custom build flags disappear after
re-opening the project.

On Fri, Oct 23, 2015 at 1:43 PM, Alexander Zolotov <notifications@github.com

**Comment by zolotov** [comment]
@Mingan @ruseinov Recreated and fixed

**Comment by Mingan** [comment]
@zolotov Wonderful! Thank you!

Your comment made me think that I might have messed up my .idea directory and wanted to recreate it from scratch to make sure but you fixed it before I even got to it.

**Comment by ruseinov** [comment]
Good job!
