### ISSUE TITLE
Unresolved reference on map of struct?

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1723]
See below

```go
package main

type (
	client struct {
		message chan string
	}
	clientList struct {
		m (map[string]*client)
	}
)

func main() {
	clientList := clientList{m: make(map[string]*client)}
	message := ""
	for _, c := range clientList.m {
		c.message <- message   // c.message is not resolved.
	}
}
```

Original issue:

http://pastebin.com/XBiNkfSN - little chat server i've been working on. For the function broadcastLoop inside of manageChannel it says on line 201 that message is unresolved. Everything compiles and runs and the function works as expected. Don't know what's wrong.

<img width="1440" alt="screen shot 2015-07-06 at 2 10 45 pm" src="https://cloud.githubusercontent.com/assets/10180857/8529565/3ebb96a8-23e9-11e5-9b7b-ed1e6c088fbb.png">

Latest nightly build btw.

**Comment by dlsniper** [comment]
Thanks for reporting, I can indeed replicate this on f054bf9b55d789bb4566d00fc9a145d5d100132f

**Comment by dlsniper** [comment]
I've updated the example with a smaller sample which reflects the issue.
