### ISSUE TITLE
Unable to resolve variable in switch statement when using pointers

### ISSUE THREAD

**Issue by nhooyr** [go-lang-plugin-org/go-lang-idea-plugin#1727]
Resolving seems to be broken for the following code:

```go
package main

import "net"

func main() {
	clientList := make(map[int]struct{
		message chan string
		conn *net.Conn
	})
	message := ""
	for _, c := range clientList {
		select {
		case c.message <- message:  // message (not c.message) resolves to clientList.message field definition instead of message := "" declaration
		default:
			(*c.conn).Close() // c is not resolved, change the code to c.conn.Close() and resolving will work
		}
	}
}
```

Original report:
<img width="1440" alt="screen shot 2015-07-07 at 5 21 08 pm" src="https://cloud.githubusercontent.com/assets/10180857/8557642/9fc18c9e-24cc-11e5-9df8-7ee1184c1285.png">
<img width="1440" alt="screen shot 2015-07-07 at 5 21 21 pm" src="https://cloud.githubusercontent.com/assets/10180857/8557643/9fccad2c-24cc-11e5-8128-190c6e72b68e.png">

code is here: http://pastebin.com/KHnQ1zJM

First screenshot you can see that it doesn't resolve the conn properly, yes it compiles and functions perfectly. Second shot (line 102) same problem except now it resolves client as a type? Compiles and works perfectly. If I change it to c like the first SS it also gives the same error. Yes my code has naming issues atm, tore up between long vs short not sure but anyways this is a resolving issue for sure.

**Comment by dlsniper** [comment]
Thanks for reporting, I've updated the issue with a smaller sample which has the same problems as described in the original issue.
