### ISSUE TITLE
importing suggests variables from testdata directory

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1728]
testdata directory is a special directory in go and there shouldn't be any suggestions for importing packages based on contents of that directory.

**Comment by zolotov** [comment]
> testdata directory is a special directory in go

That's not true. Following example works fine.

foo/main.go
```
package main
import "foo/testdata"

func main() {
	println(testdata.Variable)
}
```

foo/testdata/foo.go
```
package testdata

var Variable = "string"
```
