### ISSUE TITLE
Inspection to detect when a variable is named as an imported package

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1732]
Since this can lead to a lot of confusion, it would be nice that if there would be an inspection to detect if we name the variable as with a name assigned to an imported package.

Example:

```go
package main

import "fmt"

func main() {
	fmt := "demo" // here we should trigger at least a weak warning if not more
	fmt.Println(fmt)
}
```

**Comment by ignatov** [comment]
Please search a similar issue and add your sample there.

**Comment by dlsniper** [comment]
Right, it was opened by me so I guess I have to solve it now :D
