### ISSUE TITLE
no colouring when checking local history

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1737]
<img width="1440" alt="screen shot 2015-07-10 at 2 02 27 am" src="https://cloud.githubusercontent.com/assets/10180857/8613024/13b76c90-26a8-11e5-8d90-c07128235b1c.png">

right click any file and select local history -> show history

**Comment by dlsniper** [comment]
I suspect that this is a platform issue / correct way of working but if I'm wrong, please reopen this.
