### ISSUE TITLE
switch type default not supported

### ISSUE THREAD

**Issue by pierrre** [go-lang-plugin-org/go-lang-idea-plugin#1741]
IDEA version: 14.1.4
OS version: 4.0.7-2-ARCH 1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux (Xfce desktop env)
Java version: java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Go IntelliJ plugin version: 0.9.388
Go version: 1.4.2

My code:
``` go
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
)

func main() {
	r := image.Rect(0, 0, 1, 1)
	var p image.Image
	p = image.NewRGBA(r)
	//p = image.NewYCbCr(r, image.YCbCrSubsampleRatio444)
	switch q := p.(type) {
	case draw.Image:
		fmt.Println("draw.Image")
		q.Set(0, 0, color.RGBA{0, 0, 0, 0})
	default:
		fmt.Println("default")
		q.At(0, 0)
	}
}
```

`q.At(0, 0)` is highlighted in red with this message: "Unresolved reference 'At'".

The Go spec says for type switch default:
https://golang.org/ref/spec#Type_switches
`type of i is type of x`

**Comment by zolotov** [comment]
should be fixed already in 391 build, please try it
