### ISSUE TITLE
autocomplete suggests test file content

### ISSUE THREAD

**Issue by pierrre** [go-lang-plugin-org/go-lang-idea-plugin#1742]
Autocomplete suggests `bufio.Scanner.ErrOrEOF()` which is defined in a test file.
Autocomplete should only suggest test file content if I'm editing a test file of the same package.

**Comment by zolotov** [comment]
cannot recreate with 391 build. Maybe small code sample would help?

**Comment by pierrre** [comment]
I'm using version 0.9.391 with IntelliJ IDEA 14.1.4.
Just type: `bufio.NewScanner(nil).`.
It will auto suggest `ErrOrEOF()`

**Comment by dlsniper** [comment]
Here's an example using e15c1a0fe30c3f80d6811aa0215c02400eba9d9d :

```go
package main

import "bufio"

func main() {
	bufio.NewScanner(nil).<caret>
}
```

Or without the internal packages:
```go
// $GOPATH/src/pack1/pack1.go
type Demo struct {}

func (d Demo) Add { println("add called"); }
```

```go
// $GOPATH/src/pack1/pack1_test.go
package pack1

func (d Demo) Sub { println("sub called"); }
```

```go
// $GOPATH/src/pack2/pack2.go
package main

import "pack1"

func main() {
	pack1.<caret> // should contain only Add, not Sub
}
```

**Comment by zolotov** [comment]
@dlsniper @pierrre thanks, reproduced

**Comment by pierrre** [comment]
Thank you.
