### ISSUE TITLE
Unresolved reference for mahonia

### ISSUE THREAD

**Issue by ElvizLai** [go-lang-plugin-org/go-lang-idea-plugin#1746]
![qq20150714-1](https://cloud.githubusercontent.com/assets/501861/8664336/6ba704d4-2a08-11e5-9a3e-e77c637e590e.png)

plugin version：391/394

```
package main

import (
	"github.com/axgle/mahonia"
	"fmt"
)

func main() {
	dc := mahonia.NewDecoder("GB18030")
	fmt.Println(dc.ConvertString("abc123"))
}
```

It runs OK, but can not resolve method for "dc"

**Comment by dlsniper** [comment]
I'm puzzled by this, there's no function called NewDecoder for the whole package, at least from what I can see on my phone / github. How does it work?

**Comment by dlsniper** [comment]
Ignore my previous comment, the library was too complex to understand from phone. I'll try to come up with an example that's not dependent on an external library. Thanks for reporting.
