### ISSUE TITLE
go gdb: startup commands not working

### ISSUE THREAD

**Issue by donghwicha** [go-lang-plugin-org/go-lang-idea-plugin#1750]
with go gdb, I've registered "application executable" 
that is compiled binary of my program. 
And then, I added its main argument to "startup commands" but
after debugging argument aren't passed to program. 

if "startup command" area is for main arguments then it's not working,
or if it is not for main function argument, then there is no input for that. 

thank you.

**Comment by dlsniper** [comment]
Hi, GDB support is experimental and it's unmaintained at the moment. If someone is willing on this that's great, otherwise it will have to wait. Sorry.

**Comment by ignatov** [comment]
Obsolete, please try the delve integration in the nightly channel.

**Comment by donghwicha** [comment]
@ignatov  That is so cool! I'll try it. :)
