### ISSUE TITLE
Package name not suggested in auto-completion / import if package name is different than the folder inside test file

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1751]
I have the following package:

```go
// $GOPATH/src/github.com/dlsniper/u/demo/fuzz/fuzz.go
package fuzy

func DemoFunc(s string) string {
	return s+"1"
}
```

And the test for it
```go
// $GOPATH/src/github.com/dlsniper/u/demo/fuzz/fuzz_test.go
package fuzy_test

import "github.com/dlsniper/u/demo/<caret>" // here there's no package called fuzy

func Fuzz(s string) int {
	fuzy.DemoFunc(s) // this is not flagged as auto-importable
	return 0
}

```

The issue is that in the _test file, I can't get autocomplete/autoimport to work but if I move in a different package and start typing ```fuzy.De``` I get the expected result.

Plugin commit: e15c1a0fe30c3f80d6811aa0215c02400eba9d9d

**Comment by zolotov** [comment]
> import "github.com/dlsniper/u/demo/<caret>" // here there's no package called fuzy

import path and package are different things, here should be fuzz only

**Comment by dlsniper** [comment]
True, I mean that there's no package suggested for the path, sorry for inaccuracy.

**Comment by dlsniper** [comment]
Also, once I add the import manually things resolve fine and everything works as expected.
