### ISSUE TITLE
A project with cgo cannot run on Windows

### ISSUE THREAD

**Issue by 7phone** [go-lang-plugin-org/go-lang-idea-plugin#1754]
Environment:
* IDEA Community Edition 14.1.4
* Windows 8.1
* Go 1.5 beta
* JDK bundled with IDEA
* Go plugin updated from nightly channel

A project with the one file "main.go":
```
package main

/*
#cgo LDFLAGS: -L${SRCDIR}/libs -lopus

#include "include/opus.h"
 */
import "C"

func opus_init() {
	var err C.int

	opus := C.opus_encoder_create(8000, 2, 1, &err)

	C.opus_encoder_destroy(opus)
}

func main() {
	opus_init()
}
```

Launched the project configured to run "main.go".
Got error on event log:
```
16:45:16 Error running run: Cannot run program "C:\Users\username\AppData\Local\Temp\run2go" (in directory "E:\dev\IdeaProjects\go-ot"): CreateProcess error=193, %1 не является приложением Win32
```

Directory "C:\Users\username\AppData\Local\Temp" has two files:
* run0go        - 0 bytes
* run0go.exe - 2599608 bytes

------------------------------------
"go run main.go" - success

"main.go" without cgo code - success on IDEA (Windows) and directory "C:\Users\username\AppData\Local\Temp" has one files:
* run0go - 2510336 bytes

**Comment by dlsniper** [comment]
What happens when you run the file from console, manually? How do you run it manually, using which command?

**Comment by 7phone** [comment]
It's an issue of go.

Build with '-o' option:
```
go.exe build -o C:\Users\username\AppData\Local\Temp\run1go E:\dev\IdeaProjects\go-ot\main.go
```
Got two files in temporary directory and one is zero sized.

**Comment by dlsniper** [comment]
Ok, I see, so the error is actually that the plugin doesn't add the ```.exe``` extension to the file when it compiles, is that correct?

**Comment by 7phone** [comment]
The plugin runs the file specified in the -o option. It's OK.

I add an issue to go: https://github.com/golang/go/issues/11725

**Comment by dlsniper** [comment]
I'm not sure if it's related to cgo to be honest, I recall seeing a similar problem a while ago on windows because the windows implementation needed a .exe extension, that's why I asked. I don't have a Windows license at the moment so I can't test, sorry.

**Comment by 7phone** [comment]
The .exe extention needs to run program through a Windows console or a Windows Explorer.
For Windows, it does not matter the name of the file or the file extension to start the process.
The WinAPI function CreateProcess or mapped to it a same Java function can try to run an any file.

**Comment by zolotov** [comment]
Nice catch. I suppose that no matter what will be fixed in golang it's better just to add `.exe` to output file name while building

**Comment by zolotov** [comment]
Please try 397th build from nightly channel

**Comment by 7phone** [comment]
A project with cgo was successfully launched.
Thank you for the fix.
