### ISSUE TITLE
Autoimport breaks build a project with cgo

### ISSUE THREAD

**Issue by 7phone** [go-lang-plugin-org/go-lang-idea-plugin#1755]
Environment:
* IDEA Community Edition 14.1.4
* Windows 8.1
* Go 1.5 beta
* JDK bundled with IDEA
* Go plugin updated from nightly channel

A project with the one file "main.go":
```
package main

/*
#cgo LDFLAGS: -L${SRCDIR}/libs -lopus

#include "include/opus.h"
 */
import "C"

func opus_init() {
    var err C.int

    opus := C.opus_encoder_create(8000, 2, 1, &err)

    C.opus_encoder_destroy(opus)
}

func main() {
    opus_init()
}
```

Add a line in main function:
```
func main() {
    opus_init()
	fmt.Println("Hello")
}
```

Autoimport adds "fmt" package in an import block with "C".
```
#include "include/opus.h"
 */
import (
    "C"
    "fmt"
)
````

The project doesn't compile:
```
C:/dev/go\bin\go.exe build -o C:\Users\username\AppData\Local\Temp\run1go C:\dev\IdeaProjects\go-ot\main.go
# command-line-arguments
could not determine kind of name for C.opus_encoder_create
could not determine kind of name for C.opus_encoder_destroy
```

Expected behavior is add new an import block to save a cgo section (a comment block and next line 'import "C"'):
```
#include "include/opus.h"
 */
import "C"

import (
    "fmt"
)
````

**Comment by dlsniper** [comment]
I'm tempted to add the up for grabs label on this one. @zolotov what do you think? I might give it a try but I have to wait a few more days to do some work. If I'm not mistaken, it should be solved by checking the import statements and if there's an ```import "C"``` present then take it out of the group and add it before the rest of the import group.

**Comment by 7phone** [comment]
Thank you for the fix.
