### ISSUE TITLE
Can't Use "nil" to Initialize a Variable Without an Explicit Type

### ISSUE THREAD

**Issue by eugene-auduchinok** [go-lang-plugin-org/go-lang-idea-plugin#1758]
The "nil" identifier can be used as the "zero value" for interfaces, functions, pointers, maps, slices, and channels. If you don't specify the variable type the compiler will fail to compile your code because it can't guess the type.
```go
package main

func main() {  
    var x = nil //error

    _ = x
}
```

**Comment by zolotov** [comment]
Fixed by @azhidkov
