### ISSUE TITLE
Project Compilation with NullPointerException (GoEnvironmentUtil)

### ISSUE THREAD

**Issue by richard-julien** [go-lang-plugin-org/go-lang-idea-plugin#1759]
Hi,

I try to compile a project with the plugin and i have an exception.
Im currently using the nightly build of the alpha pre release.
I have created the project with the help of the README. (New project).

The stack I have in the idea compile log :
>org.jetbrains.jps.incremental.ProjectBuildException: Go 'Drone' production: java.lang.NullPointerException
>	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:971)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:840)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:663)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:370)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:191)
>	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
>	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:293)
>	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:124)
>	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:242)
>	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:41)
>	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>	at java.lang.Thread.run(Thread.java:745)
>Caused by: java.lang.NullPointerException
>	at com.goide.GoEnvironmentUtil.retrieveGoPathFromEnvironment(GoEnvironmentUtil.java:40)
>	at com.goide.jps.model.JpsGoLibrariesExtensionServiceImpl.retrieveGoPath(JpsGoLibrariesExtensionServiceImpl.java:63)
>	at com.goide.jps.builder.GoBuilder.build(GoBuilder.java:72)
>	at com.goide.jps.builder.GoBuilder.build(GoBuilder.java:38)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTarget(IncProjectBuilder.java:906)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:887)
>	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:945)
>	... 14 more

Its seems related to the line if (ApplicationManager.getApplication().isUnitTestMode()) return null;
My application seems to be null. I will try to checkout and find something.

Thanks.

**Comment by dlsniper** [comment]
> Im currently using the nightly build of the alpha pre release.

There are two different channels, alpha and nightly. Please tell us the plugin version, we'll know from which channel it is. Also, the description is pretty vague, could you share the code maybe (if it's public) or, if not, something that can reproduce it?
Thank you

**Comment by dlsniper** [comment]
Also, which IDE are you using? Is it up to date? What version do you have?

**Comment by zolotov** [comment]
@dlsniper channel doesn't matter. IDE is IDEA.

**Comment by zolotov** [comment]
@richard-julien you're right, it's related to ApplicationManager.getApplication().isUnitTestMode() line, but it's not the error actually. The problem is that I forgot to disable building service. I'll fix the exception but build won't work anyway: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1453#issuecomment-83124378

**Comment by richard-julien** [comment]
I try to compile the project https://github.com/drone/drone with IDEA 14.1.4.
If i undestand correctly the #1453 the make will fail because of the structure of the project (source in subdirs). So i have tried to just setup project configuration. I'm able to start the project but the debug button is not active. But it's not related to this ticket ;) Thanks for your answers.

**Comment by dlsniper** [comment]
If you want to compile the app from the IDE, please see: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#running-your-application

**Comment by richard-julien** [comment]
Thanks for the link, its perfectly working. Debug button is still inactive. Do I need to use GDB instead ?

**Comment by dlsniper** [comment]
Debug is a different issue, GDB support is experimental as GDB doesn't understand Go properly. Please see the other threads from here (they'll also contain the lengthier explanation for GDB / debugging and how you can try to test it).

**Comment by richard-julien** [comment]
Ok perfect. Thanks!

**Comment by zolotov** [comment]
@richard-julien debug support is in progress (integration with delve). GDB itself is behind golang and only future GDB version will support go1.5. In future, when GDB releases will correspond to golang releases, we'll consider the opportunity to implement proper GDB debugging support.

**Comment by zolotov** [comment]
> If i undestand correctly the #1453 the make will fail because of the structure of the project (source in subdirs).

@richard-julien not really, make will fail because it does nothing and it does nothing because I have no idea what it should do. Quote from that issue

> go build could produce different results depending on compiling packages, main files, target arch and so on, IDE has no this information while making project.

Plus many users have very different project layout hence they are building their applications in different ways and again IDE doesn't know what is expected to be done while making project.

**Comment by richard-julien** [comment]
I'm new in the "go world" (coming from java), I really appreciate your explanations.
I will take a look to the delve project, and wait for the integration ;)
