### ISSUE TITLE
Issues with importing third party go libraries

### ISSUE THREAD

**Issue by djhworld** [go-lang-plugin-org/go-lang-idea-plugin#176]
I'm currently experiencing issues with this plugin and I'm struggling to understand what I'm doing wrong.
(setup: IntelliJ 12 Ultimate edition )

Basically I have a project under 

```
$GOPATH/src/github.com/djhworld/project
```

structured like this

```
$GOPATH/src/github.com/djhworld/project
--> src
---> main.go
```

and I have a third party library I'm using here

```
$GOPATH/src/github.com/go-gl/gl
```

In my `main.go` I have the code

```
package main

import "fmt"
import "github.com/go-gl/gl"

func main() {
    fmt.Printf("Hello world!")
}
```

But when I try to run the code I just get the error

```
can't find import: "github.com/go-gl/gl"
```

Is there some setting somewhere to tell the plugin to point to my GOPATH or something?

**Comment by Kevin-Zhang225** [comment]
> $GOROOT/pkg/src/github.com -> $GOPATH/src/github.com

not clear enough
