### ISSUE TITLE
Wrong expression result count on builtin functions calls

### ISSUE THREAD

**Issue by eugene-auduchinok** [go-lang-plugin-org/go-lang-idea-plugin#1760]
`GoInspectionUtil.getExpressionResultCount` returns `-1` for `GoBuiltinCallExpr`.
Example golang code with builtin `make` call:
```go
func f() {
	m := make(map[string]int,10)
	...
}
```
Method definition:
https://github.com/eugene-auduchinok/go-lang-idea-plugin/blob/7118347bf439e09c1cecc4482d0bfd75dc604ca7/src/com/goide/inspections/GoInspectionUtil.java#L31-31

Tell me if I'm wrong and this is a proper behaviour for some reason.

**Comment by dlsniper** [comment]
As an addition to this, I've noticed this weekend that the parameter info are not shown ```CTRL+P``` (on Linux) are not show for ```make``` so I guess maybe it's the same problem?
