### ISSUE TITLE
Cannot use Go 1.5b2 as my SDK

### ISSUE THREAD

**Issue by mamacdon** [go-lang-plugin-org/go-lang-idea-plugin#1761]
Windows 7, IDEA 14.1.4, alpha plugin (version = 0.9.371)
* I installed [go1.5beta2.windows-amd64.msi](https://storage.googleapis.com/golang/go1.5beta2.windows-amd64.msi) in `C:\Go`.
* When I try to set `C:\Go` as my Go SDK, I get an error saying "The selected directory is not a valid home for Go SDK".

The same steps work OK with a Go 1.4.2 SDK.

**Comment by dlsniper** [comment]
Hi, thank you for reporting. This is fixed in the nightly channel and the next alpha release will fix it as well. The next alpha release should be here soon, if nothing major happens. I'll close this for now as it's a duplicate.
