### ISSUE TITLE
Create new Go project?

### ISSUE THREAD

**Issue by victorhooi** [go-lang-plugin-org/go-lang-idea-plugin#1763]
_Pycharm 4.5.3 (Build #PY-141.1899) with version 0.9.402 of the Go IDEA plugin._

I'm wonder how 

The documentation (https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation) simply mentions:

> TODO Document this

I can import an existing Go project using "Open" at the main screen:

<img width="673" alt="screenshot 2015-07-21 09 38 27" src="https://cloud.githubusercontent.com/assets/243499/8790035/59519612-2f8c-11e5-8149-6bc6260cdfed.png">

(Although there's no "Import Project", like, the documentation mentions - no sure why. I assume Open and Import Project are different though, right?)

https://raw.githubusercontent.com/wiki/go-lang-plugin-org/go-lang-idea-plugin/images/snapshot43.png

However, there's no facility for actually creating a new Go project:

<img width="669" alt="screenshot 2015-07-21 09 38 39" src="https://cloud.githubusercontent.com/assets/243499/8790046/7bbda83a-2f8c-11e5-9ea9-752337f7750f.png">

Is this by design, or am I missing something here? If it's by design, could it be documented in the docs?

Thanks,
Victor

**Comment by dlsniper** [comment]
Hi, for PyCharm please try and create a pure python project the start creating a go file see what happens. I'll update the docs soon with some more content, thanks for pointing it out

**Comment by milesich** [comment]
Same with PHPStorm 9. I am using "Empty Project" instead.

**Comment by dlsniper** [comment]
@milesich that's the correct way to setup the project on phpstorm/webstorm. I'll update the docs to state the correct info for all the IDEs, thank you for feedback.

**Comment by thawkins** [comment]
Just my 2cents

There really should be a create go project item,  even if all it does is create a blank project.  Most people after installing tbe plugin will naturaly try and create a go project  and be puzzled when it is not listed as an option, i certainly was, and spent a few hours trying to work out if the plugin was loaded properly. It seems with the little popup notification, and the documentation that the project is expending  a lot of effort to avoid doing something that does not sound complex, and would meet most new users expectation, if i knew how to i would do it myself. 

In fact it may be worth me learning tbe whole process just to fix this which i find to be a major anoyance.

**Comment by ignatov** [comment]
Make sense, thanks.

**Comment by bryanrieger** [comment]
Same with WebStorm.

**Comment by ignatov** [comment]
A simple project generator has been added. Please check out the next nightly build.

**Comment by thawkins** [comment]
I will pull this down and check it out, i have phpstorm

**Comment by thawkins** [comment]
I can confirm this works fine on phpstorm

I was able to

1. Install plugin 
2. create project
3. type hello-world go file
4. compile
5. run 

all in under 2 mins, with out needing any special knowledge, 

Much better "newbie" experience. 

Just some notes, where it could be smoother, for future reference. 

1. If an sdk is detected, just set it up, i only had to keep hitting return, but if a valid sdk is there there does not seem to be any point in having the user go through that process. 

2. If there is no sdk installed, then maybe use something like "gimme" to download and install one.

**Comment by dlsniper** [comment]
Hi, thanks for the feedback. 
Here's my view on it:

> 1. If an sdk is detected, just set it up, i only had to keep hitting return, but if a valid sdk is there there does not seem to be any point in having the user go through that process.

It's not uncommon to have different SDK, think stable and tip or stable and next release, at the same time on a machine. I have 3 SDKs installed for example,with only one matching the default location. As such, for me the current experience allows me to select what I need easily with a minimal distraction in case I want the default. 

> 2. If there is no sdk installed, then maybe use something like "gimme" to download and install one. 

Given there are any tools / use-cases that are not support by the plugin I'd say this shouldn't be taken care of by the IDE but by the user. Also, for example, I'm installing go via tars, I could use apt-get, but Mac users will have brew. I'm not sure if it's the plugin responsibility to use another way to get the SDK in place (Android does it on the other hand so there might be something there). 

This is just my input it doesn't mean it has to stay like this. Let's see what others say / what's the demand for this. Thank you.

**Comment by thawkins** [comment]
Your points are all valid, and im not going to argue one way or the other,
I was just placing myself into the shoes of a new user, often its a good
idea to provide simple defaults and assistance in getting them up and
runnng. The plugin is going to make using go a lot easier for a bunch of
folks who may not be adept at juggling thier machine configurations, so its
worth considering.

**Comment by dlsniper** [comment]
Like I've said, that's just my view on the things but your points are valid as well. A good onboarding of new users should be always kept in mind and I (I dare to say we) appreciate always feedback (more so when it's of the quality you provided).

@ignatov / @zolotov should I open a couple of issues with the points from above to have an overview for them for later down the road or if someone wants to contribute for these (mark them as `up for grab` and `x.x.x pool`) ?

**Comment by zolotov** [comment]
@dlsniper as @ignatov said the `simple` generator was added, just to not scare new users. We'll be working on user experience of generator closer to release, so I don't mind if you created the issue about it. I like all that @thawkins said, maybe except gimme thing. Installation go sdk on each platform is really hard and I'm afraid that the code part responsible for it will be bigger than our resolution algorithm, and IMHO smoother user experience for newbies doesn't worth it :)
