### ISSUE TITLE
very odd problem with colouring

### ISSUE THREAD

**Issue by nhooyr** [go-lang-plugin-org/go-lang-idea-plugin#1779]
<img width="1440" alt="screen shot 2015-07-31 at 6 32 05 am" src="https://cloud.githubusercontent.com/assets/10180857/9005654/ed2dc27a-374d-11e5-833d-f93cef19d6b2.png">

not sure what the problem is but as you can see on line 141 and more the methods of the variable C are not highlighted. Code base is here on github. file tunnel.go and method client. 

https://github.com/aubble/goTunneLS/blob/master/tunnel.go

**Comment by dlsniper** [comment]
Can you please share your color scheme?

**Comment by aubble** [comment]
absolutely :P https://www.dropbox.com/s/ehb4zzrobjktkup/aubble.jar?dl=0
made it myself :D what should I name it?

**Comment by aubble** [comment]
Oh noticed the same problem on line 134 with ln.Accept()?
