### ISSUE TITLE
Plugin 'ro.redeul.google.go' failed to initialize and will be disabled

### ISSUE THREAD

**Issue by Kurt-Shiwz** [go-lang-plugin-org/go-lang-idea-plugin#1787]
mac 10.10.4 idea 14.1.4CE
I build plugin succeed, but when i restart it broken.
Plugin 'ro.redeul.google.go' failed to initialize and will be disabled.
com.intellij.diagnostic.PluginException: com/goide/ui/ProjectTutorialNotification : Unsupported major.minor version 52.0 [Plugin: ro.redeul.google.go]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
...

**Comment by dlsniper** [comment]
Hi, this happens when you compile the plugin with a higher Java version that your IDE uses. Please observe which Java version is used by the IDE and compile the plugin against it. Let me know if you need any further information.
