### ISSUE TITLE
Project Libraries should shadow Global Libraries entries

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1790]
Hi,

There was a case reported on Gitter by @kei-yamazaki where for a specific project the packages (Project Libraries) from the vendored packages overlap with some of the dependencies from the global packages (Global libraries).

To exemplify:
- Global libraries: ```/home/florin/golang``` contains ```github.com/dlsniper/demo```
- Project libraries: ```/home/florin/golang/src/github.com/florin/project/Godeps/_workspace``` contains ```github.com/dlsniper/demo```.

Without shadowing the common packages from Global Libraries the plugin will say: ```Resolved to several targets```. 

The way I see this working would be: if there are entries to the Project Libraries then the resolving and everything else should look into those first. If there are duplicates with Global Libraries then they should be taken only from the Project Libraries.

Example:
- Global Libraries from: ```/home/florin/golang``` contains ```github.com/dlsniper/demo```
- Project Libraries from: ```/home/florin/golang/src/github.com/florin/project/Godeps/_workspace``` contains ```github.com/dlsniper/demo```
- ```github.com/dlsniper/demo``` should match to Project Libraries
- ```github.com/dlsniper/demo/dem``` should match to Global Libraries if it's not present in Project Libraries

I hope the description is clear enough.
Thank you.

**Comment by kei-yamazaki** [comment]
:+1:

**Comment by drichelson** [comment]
This prevents me from using my current godep workflow with IDEA, but in a slightly different way: imports relative to the IDEA project root which are fully qualified aren't found by IDEA because I'm not using the system GOPATH, just my local vendor library generated by godep.
