### ISSUE TITLE
godebug support

### ISSUE THREAD

**Issue by MilovanovM** [go-lang-plugin-org/go-lang-idea-plugin#1793]
Hi!

Do you plan to support https://github.com/mailgun/godebug?

Thanks,
Maxim

**Comment by dlsniper** [comment]
Not as far as I know. The plan is to support [Delve](https://github.com/derekparker/delve) which is a real debugger, much more advanced and better debugger than godebug. Also, if GDB supports improves, it will be (better) supported as well.
Contributions for other debuggers are welcomed as well so if anyone contributes it then that's a different story :)
@ignatov / @zolotov anything else to add?

**Comment by zolotov** [comment]
nope
