### ISSUE TITLE
default output directory should be $GOPATH/bin

### ISSUE THREAD

**Issue by aubble** [go-lang-plugin-org/go-lang-idea-plugin#1794]
It fits better with go, I don't like the executables being put into the same directory as the source files, especially when its a repo, I don't want to upload the executable accidentally. And $GOPATH/bin is easy to set in my path so that I can use my applications conveniently.

**Comment by dlsniper** [comment]
```go build`` produces the executable in the current working directory unless otherwise specified directly by the user. ```go install``` and ```go get``` create the binary in $GOPATH/bin as that's their default location.

So I'm inclined to say no, the go way is to create binaries in the cwd and so does the plugin.

**Comment by aubble** [comment]
@dlsniper fair enough I'll close it then

**Comment by dlsniper** [comment]
Well, it's just my opinion, pretty sure it's not the majority :)

**Comment by zolotov** [comment]
1. You might have several GOPATHs
2. Building != installing
3. Run configurations are about running and not producing artifacts
