### ISSUE TITLE
Coloring problem on Method Receiver and Type Reference

### ISSUE THREAD

**Issue by amirhosseinab** [go-lang-plugin-org/go-lang-idea-plugin#1796]
When changing the color of __Method Receiver__ and __Type Reference__ in the `Preferences>Editor>Colors & Fonts` window it does weird behaviour.

    func (ps PublicStruct) PublicFunc() int {

the color of `PublicStruct` always is the same as `ps`

**Comment by dlsniper** [comment]
Can you please submit a better code sample to reproduce this? A screenshot would also help as I can't replicate it. Thanks.

**Comment by amirhosseinab** [comment]
In the below sample code on line 8 you can see that the `salutations`(Method Receiver) and `Salutations`(Type Reference) are the same color but in the `Colors & Font` window they are different.

<img width="411" alt="screen shot 1394-05-22 at 5 09 52 pm" src="https://cloud.githubusercontent.com/assets/1999772/9249894/3b53fbf0-41de-11e5-949e-f8d4f51af54e.png">

**Comment by dlsniper** [comment]
What version of the plugin do you use, and which IDE? I still can't replicate the issue unfortunately :(
![snapshot24](https://cloud.githubusercontent.com/assets/607868/9250017/3150273c-41ca-11e5-8baf-dd5c43671a20.png)

```go
package main

type (
	Salutation  struct{}
	Salutations []Salutation
)

func (Salutations Salutations) SayHello() {

}
```

**Comment by amirhosseinab** [comment]
IDE: IntelliJ IDEA Ultimate 14.1.4
Plugin Version: 0.9.402

**Comment by dlsniper** [comment]
I think this may have been fixed meanwhile, I'm on latest master and it works as expected. Please try the latest nightly. If it's still there, I guess it will be fixed in the next one.

**Comment by amirhosseinab** [comment]
I upgrade my plugin to the latest nightly build _0.9.446_, and it is still there, and something interesting that I find out now the parentheses after `func` are colorize too.

**Comment by dlsniper** [comment]
For those there's a fix in progress: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1782

**Comment by dlsniper** [comment]
Fixed a while ago
