### ISSUE TITLE
Can not delete a java xxx.class file in a golang project.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1800]
![image](https://cloud.githubusercontent.com/assets/1107541/9287705/a96772c0-4355-11e5-8fe6-364786fc3e69.png)

I was writing a java code generater in golang.I add some java files,then compile with javac,then I want to delete some java files, but i can not delete the xxx.class file.

xxx.class should be a java compiled cached file like the pkg in go project.

ps:
You can not jump around in the java files in golang project.If you create a new java project in idea.it works.Is this a expect behavior or not?

**Comment by zolotov** [comment]
Likely you just have no rights to delete these files, golang plugin has nothing to do with that.

>You can not jump around in the java files in golang project.If you create a new java project in idea.it works.Is this a expect behavior or not?

Yes, It will be changed in future but at the moment you cannot have golang and java in one module, you should create a separate java module in order to get proper navigation.
