### ISSUE TITLE
Cant write input to go-program in console

### ISSUE THREAD

**Issue by Feve2** [go-lang-plugin-org/go-lang-idea-plugin#1801]
Hello there,
when I compile my cl-based go-file with `go run main.go`, the Output appears, and I am not able to enter any Input in, the console doesnt wait until I enter any Input.
I use the built-in terminal. But same for the normal win-cli. In LiteIde it worked, how can I fix it?

**Comment by dlsniper** [comment]
Hi, do you have a small sample that can reproduce the issue? Thanks.

**Comment by Feve2** [comment]
Thanks for your very fast answer!
So, I got to know that the "issue" isnt really an issue:
```
package main

import "fmt"

func main(){
	var input string

	fmt.Println("Enter anything: ")
	fmt.Scanf("%d", &input)
	fmt.Println("K, you said " + string(input))
}
```
How you can see I want to store an integer into a string variable.
And thats why I am not able to enter anything.
But anyway, thanks for your fast Support.
