### ISSUE TITLE
Feature Request: View Documentation of public Methods in "IntelliSense"

### ISSUE THREAD

**Issue by Feve2** [go-lang-plugin-org/go-lang-idea-plugin#1802]
Hello there,
in the golang standard-libraries, all public members (functions and structs) are well documented, so it would be very nice to Display that doc into the "IntelliSense"-Popup, just like VisualStudio does it with C#.

**Comment by dlsniper** [comment]
HI, I believe what you are looking for is the Quick Documentation, which you can usually access from CTRL + Q (at least on Linux). You can view more information here: https://www.jetbrains.com/idea/help/viewing-inline-documentation.html

**Comment by dlsniper** [comment]
Also, if you invoke completion manually the documentation will be displayed
![snapshot26](https://cloud.githubusercontent.com/assets/607868/9293021/26c615fa-4419-11e5-9d82-fe25e2ce2da7.png)

I don't know how to make it appear when the completion is invoked automatically but I don't see a need for it as completion can be invoked manually even if the automatic one kicked in. As such this is a plugin issue, it's something that the platform should handle, as such please file an issue at: https://youtrack.jetbrains.com/

Thanks.

**Comment by Feve2** [comment]
Thats **exactly** what I was looking for.
Thanks for your help!
