### ISSUE TITLE
Tracking for auto-report 906283 (PSI and index do not match)

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1805]
https://ea.jetbrains.com/browser/ea_reports/906283

**Comment by dlsniper** [comment]
I've noticed that there were more than 6 files to be attached but in the UI from ea.jetbrains I can only see one file. Should I file a issue on Youtrack for this as it's not the first time I see it happening. Thank you.

**Comment by ignatov** [comment]
Why?

**Comment by dlsniper** [comment]
I've yet to encounter this again and I do have a reason to believe that it was caused by my setup not the plugin (I was using IDEA 15 EAP and the plugin forced compiled manually). Obviously I can't tell for sure if it's fixed but it's been 3 months since it

**Comment by dlsniper** [comment]
I'll close this given that it's so old probably many things have changed since then and I haven't seen this in a while.
