### ISSUE TITLE
Relative paths don't appear correctly in the stack frame

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1815]
I'm compiling this: https://github.com/dlsniper/u/blob/master/dbg/1/demo.go with the debugger enabled. 
On lines: 7, 12, 14 and 19 I've setup breakpoints.

The run command looks like this:
```
Working dir: /home/florin/golang/src/github.com/dlsniper/u/dbg/1

/usr/local/go1.4/bin/go build -o /home/florin/golang/src/github.com/dlsniper/u/dbg/1/dbg1 -gcflags "-N -l" /home/florin/golang/src/github.com/dlsniper/u/dbg/1/demo.go
/home/florin/.IntelliJIdea14/system/plugins-sandbox/plugins/intellij-go/lib/dlv/linux/dlv --listen=localhost:54124 --headless=true debug /home/florin/golang/src/github.com/dlsniper/u/dbg/1/dbg1 --
```

However, in the stack frame I have the following entries:
```
<invalid frame> at main.main
proc.go:71 at runtime.main
asm_amd64.s:2232 at runtime.goexit
```

I've traced the issue and it comes up because of the following line
```java
LocalFileSystem.getInstance().findFileByPath(url)
```
from 
```java
  @Nullable
  @Override
  public XSourcePosition getSourcePosition() {
    String url = myLocation.file;
    VirtualFile file = LocalFileSystem.getInstance().findFileByPath(url);
    if (file == null) return null;
    return XDebuggerUtil.getInstance().createPosition(file, myLocation.line);
  }
```

It seems "findFileByPath()" will return always `null` for relative paths. The filename returned by delve seems to be `./demo.go` which generates the issue.

There are two solutions to this:
- the plugin resolves relative paths to the working dir / dir of the file being compiled
- delve sends back always the file with full path. CC @derekparker for input on this, should I open up an issue on delve?

IDEA version 14.1.4.
delve version: 0.7 (https://github.com/derekparker/delve/commit/066160f93e1d42d5f4850c6d9e4e907295757339)

**Comment by derekparker** [comment]
Thanks for cc'ing me.

This has been brought to my attention, and the proposed solution was a flag
/ config for controlling the output of paths. Since shortened paths are
really just a terminal UI nicety, I think it would make sense to ensure
that the shortening of the paths happens in the presentation code. With
that, all consumers of the JSON-RPC service would receive full paths.

**Comment by derekparker** [comment]
In other words, this should be a quick fix in Delve and I can have a patch
ready shortly. Feel free to open an issue on Delve to track this.

**Comment by derekparker** [comment]
See https://github.com/derekparker/delve/commit/32b499fa47dfd6bca564d2c1214ff62fb2e7566f for the fix. @dlsniper that patch should address the issue.

**Comment by dlsniper** [comment]
Oh my, that was fast! Thank you @derekparker! Awesome.
