### ISSUE TITLE
Autoimport doesn't prepend a tab character in the import block

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1816]
Hi,

I've noticed that in the version b1fe90b7d4474ee9552fddc6045153720303e275 when using the autoimport/import suggestion feature, the resulting import statement will not be prepended with a tab character.

For example:
```go
import (
	"fmt"
)

func demo() {
	io.Copy // when completing this one the issue manifests
}
```

becomes:
```go
import (
	"fmt"
"io"
)

func demo() {
	io.Copy // when completing this one the issue manifests
}
```

**Comment by eugene-auduchinok** [comment]
It worked correctly when used `runWriteCommandAction` instead of `runUndoTransparentAction` as before 98a38cd1c7c7b6772afad67cd0f93f0e48287145.
I'll try to fix this.

**Comment by dlsniper** [comment]
This has been fixed a while ago.

**Comment by zolotov** [comment]
Nope, still actual on adding imports on the fly
