### ISSUE TITLE
Improve binary artifact name of debug runner

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1821]
Hi,

When opening a new project and using right click + debug, the command that is issues looks like this:

```
/usr/local/go1.4/bin/go build -o "/tmp/Build demo.go and run0go" -gcflags "-N -l" /home/florin/golang/src/github.com/dlsniper/u/dbg/1/demo.go
/home/florin/.IntelliJIdea14/config/plugins/Go/lib/dlv/linux/dlv --listen=localhost:46376 --headless=true debug "/tmp/Build demo.go and run0go" --
```

It would be nicer if the binary name would be named like the project name for example, or something like ` idea-go01 ` rather than ` Build demo.go and run0go `

Thanks.

**Comment by zolotov** [comment]
What's the point? It's auto-generated temporary file in tmpfs? Who cares how it's called?

**Comment by zolotov** [comment]
And current file is named like the run configuration name, so it's on you how it will be called.
