### ISSUE TITLE
Incompatible with WebStorm 11 EAP

### ISSUE THREAD

**Issue by stef-k** [go-lang-plugin-org/go-lang-idea-plugin#1823]
WebStorm updater reports Go plugin as being incompatible.
WebStorm 11 EAP, build 142.4148

**Comment by dlsniper** [comment]
Thanks for reporting. That's correct. For the moment there are no new nightlies compatible with IntelliJ Platform 142. Please use Webstorm 10 meanwhile or a compatible IDE.

**Comment by zolotov** [comment]
142.* builds won't be supported

**Comment by Marlon-Monroy** [comment]
When is it going to be available?

**Comment by dlsniper** [comment]
@Marlon-Monroy I've just tested, the plugin is already released in the main repository at version 0.10.749 while the latest nightly is: 0.10.969 and it's compatible with WebStorm 11.

**Comment by Marlon-Monroy** [comment]
Thanks will check now
