### ISSUE TITLE
Refactoring nested non go projects

### ISSUE THREAD

**Issue by tarqe39** [go-lang-plugin-org/go-lang-idea-plugin#1825]
I have a web app nested inside of go workspace. If i try to refactor javascript (ie extract variable) i get the error:
*Cannot perform refactoring. Cannot modify library or SDK code*

Can you please help me with this?

**Comment by dlsniper** [comment]
How does your workspace look like? Where are the gopath, go project dir and the web app project dir? 

Afaik, this happens when you have a situation like this:
- gopath = /home/florin/golang
- project root = /home/florin/golang/src/github.com/dlsniper/demo
- web app = /home/florin/golang/src/github.com/dlsniper/another

**Comment by tarqe39** [comment]
It look exactly as you described. Is there a workaround to exclude the web app folder from golang refactoring?

**Comment by dlsniper** [comment]
Not as far as I know. I would suggest that you use a different project for the web project but I have to check to see if that works or not (it should afaik). I'll try tomorrow to see if it can be done or not and I'll update this afterwards.

**Comment by dlsniper** [comment]
As a note, this is not related to the refactoring engine but to the way the GOPATH generates libraries in the IDE.

**Comment by tarqe39** [comment]
Ok thank you i will have to use a different project than.

**Comment by zolotov** [comment]
> It look exactly as you described. Is there a workaround to exclude the web app folder from golang refactoring?

There is no workaround, there is a "proper" way for doing this stuff: if you're going to develop both projects simultaneously you have to create project with two modules (sub-projects).
