### ISSUE TITLE
Error when set up "go vet" in before launch

### ISSUE THREAD

**Issue by tenmozes** [go-lang-plugin-org/go-lang-idea-plugin#1834]
I've got an error ```can't load package: package .: no buildable Go source files in path/to/project```
when i added ```vet``` in before launch section in run configuration window 
or ```go: unknown subcommand "vet path/to/project```  when added ```vet path/to/project``` command
os - Ubuntu 14.04
plugin - 0.9.481
go - 1.5
idea - 14.1.4

**Comment by zolotov** [comment]
run configuration screenshot please

**Comment by tenmozes** [comment]
go vet
![selection_012](https://cloud.githubusercontent.com/assets/1381404/9549571/600f7226-4daf-11e5-97b5-75e4c5f5db5a.png)
go vet path/to/project
![selection_013](https://cloud.githubusercontent.com/assets/1381404/9549607/8451091a-4daf-11e5-9d48-54eef637d81f.png)

**Comment by zolotov** [comment]
And what if you run `go vet` in `/var/www/amqp-to-websocket` from command line?

**Comment by tenmozes** [comment]
get error ```can't load package: package /var/www/amqp-to-websocket: cannot import absolute path```
but if i run ```go tool vet /var/www/amqp-to-websocket``` - no errors and normal work and in idea - still see ```go: unknown subcommand "tool vet /var/www/amqp-to-websocket"```
