### ISSUE TITLE
it seems not support multi GOPATH

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1835]
i like put different libs to different dirs, this makes everything clear, but the plugin seems not support multi gopath, just like this

```
export GOROOT=~/golang/go
export GOPATH=~/golang/3rdLibs:~/golang/myLibs:~/golang/myApps
export GOBIN=
export PATH=$PATH:$GOROOT/bin:${GOPATH//://bin:}/bin
```

**Comment by dlsniper** [comment]
Can you please send a screenshot of File -> Settings -> (search for) Go Libraries. Also, do each of the paths in your GOPATH have a /src folder in which the sources are present? Thank you.

**Comment by ziyouchutuwenwu** [comment]
hi dlsniper, before solve this multi gopath issue, i found another bug(maybe), my enviromrnt is
```
idea ic 14.1.4
mac os 10.10.4

java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

i click create a project, when to choose golang sdk, i select my go unziped path
/Users/mmc/golang/go
![path_select_dialog](https://cloud.githubusercontent.com/assets/7458713/9567411/9b179b06-4f5c-11e5-8c2b-7bbf4a35bed5.png)
bug the dialog didn't add this path to gui, no error dialog poped;
![path_select](https://cloud.githubusercontent.com/assets/7458713/9567412/a1bb464c-4f5c-11e5-94dd-bfdcebc15a93.png)
if i continue creating the project, i can't add gosdk from File, Project Structure, SDK yet

here is my golang_path screenshot
![golang_path](https://cloud.githubusercontent.com/assets/7458713/9567404/64d84e64-4f5c-11e5-99c7-1970d04973ac.png)

each of my GOPATH has src subdir, here is my screenshot
![src_demo](https://cloud.githubusercontent.com/assets/7458713/9567407/8920f0be-4f5c-11e5-951d-13cf5c111881.png)

my setting under liteide works fine, thanks very much

**Comment by dlsniper** [comment]
Please follow these instructions in order to install the latest version of the plugin, 0.9.15.3 is not supported anyore (nor should you be able to install it on IDEA 14, I don't know how you managed to so that) https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by ziyouchutuwenwu** [comment]
i tested with the alpha build, it worked, thanks
i tried for many times to download the alpha build, for the gfw, i hava nothing to say......

**Comment by dlsniper** [comment]
@ziyouchutuwenwu since the repository is hosted by JetBrains maybe it's worth getting in contact with them via https://youtrack.jetbrains.com/ . I'll cc @zolotov and @ignatov for this one to keep in mind about China and the Great Firewall but I can't promise anything. Are downloads from Github allowed there? If so we might be able to add the plugin to each Github release.

**Comment by ziyouchutuwenwu** [comment]
the gfw will add update the blacklist frequently, so you need't change anything, i will try to use other method to download the updated release, thanks a lot!
