### ISSUE TITLE
Does not accept wildcard for building application

### ISSUE THREAD

**Issue by amirhosseinab** [go-lang-plugin-org/go-lang-idea-plugin#1836]
In the `Edit Configuration` window, when you add new `Configuration` for building `Go Application` it does not accept `/...` wildcard in the File box.

**Comment by dlsniper** [comment]
Hi, what's the use case for this? The run configuration is also supposed to launch the application and get it's output back as well as launch a debug version of it.

**Comment by dlsniper** [comment]
I'm closing this as it doesn't have feedback for a few months now. @amirhosseinab please feel free to reopen this when you have additional feedback. Thank you.
