### ISSUE TITLE
Unresolved reference on slice objects

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#1837]
Recently I started seeing this issue:

<img width="478" alt="screen shot 2015-08-30 at 1 40 27 pm" src="https://cloud.githubusercontent.com/assets/4350891/9569342/bc6561de-4f1c-11e5-8b28-8adebc1b39d3.png">

It happens with arrays/slices defined as a different type. You can see it happens to SomeId struct member.

```Go

type TestStruct struct {
	SomeId int
}

type DataSlice []*TestStruct

func NewDataSlice() *DataSlice {
	return &DataSlice{}
}

func ErrorCode() {
	data := NewDataSlice()
	for _, element := range data {
		if element.SomeId > 20 {
			println("some text")
		}
	}
}
```

Environment:
➜  ~  uname -a
Darwin domain.com 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
<img width="377" alt="screen shot 2015-08-30 at 2 30 26 pm" src="https://cloud.githubusercontent.com/assets/4350891/9569556/d06fef30-4f23-11e5-9eaf-e3307b0cc82f.png">
<img width="393" alt="screen shot 2015-08-30 at 2 29 49 pm" src="https://cloud.githubusercontent.com/assets/4350891/9569557/d49f4114-4f23-11e5-84d0-08dca9c0c2bf.png">

Go: 1.5 and 1.4.2.

**Comment by dlsniper** [comment]
I can replicate this for commit: c3eb6cdcd66fa44169c025e9c4d528252cca714c
