### ISSUE TITLE
VerifyError: update failed

### ISSUE THREAD

**Issue by NormB** [go-lang-plugin-org/go-lang-idea-plugin#1838]
The following errors happen very often:

9:51:38 AM VerifyError: update failed for AnAction with ID=Debug: com/goide/dlv/DlvDebugProcess
9:51:43 AM VerifyError: update failed for AnAction with ID=Debug: com/goide/dlv/DlvDebugProcess
9:51:48 AM VerifyError: update failed for AnAction with ID=Debug: com/goide/dlv/DlvDebugProcess

**Comment by dlsniper** [comment]
@NormB thank you for your issue. Please read the following section describing how to properly report issues: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#bugs else we can't be helpful in fixing this. Thank you.

**Comment by dlsniper** [comment]
Unfortunately that IDE version is not supported yet. Please see the list of supported IDEs here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by NormB** [comment]
Not a problem.  The plugin appears to be working ok.  It's just the warning/error message that caught my attention.  Thank you for your efforts.
