### ISSUE TITLE
Debug action doesn't stop existing running instance

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1839]
- compile an app, for example:
```go
package main

func main() {
	println("demo")
}
```

- set a breakpoint on line 4 (the one with `println`)
- run the debug option
- while the debugger is stopped on the breakpoint run the debug executor again

```
00:54:09 Error running dbg: Cannot make temporary file executable /path/to/exec
```

Also, in this case, it's not a temporary file but rather the final file.

Plugin revision: f93a5110c25991569cc2566f25196c9867f66563

**Comment by pylover** [comment]
I facing this issue, too. It's good to the `dlv` pass the `SIGINT` signal to the underlying process.

**Comment by zolotov** [comment]
Cannot recreate. Any details?

**Comment by zolotov** [comment]
> Also, in this case, it's not a temporary file but rather the final file.

And what does it mean?

**Comment by zolotov** [comment]
And the last question: why it should stop existing running instance?

**Comment by dlsniper** [comment]
Right now, for the example above, using 0.10.659 build the debugger won't even stop at the breakpoint for that line: https://youtu.be/m-FsGUG6RlE, I'll add an example which allows the debugger to stop and see if the original issue still happens.

**Comment by dlsniper** [comment]
This is the log that I have in my folder (I've cleaned up the folder and started a fresh instance before recording) https://www.dropbox.com/s/szhfu8hwo3qo6mu/log.tar.gz?dl=0

**Comment by zolotov** [comment]
@ignatov take a look at logs, looks like broken api

**Comment by ignatov** [comment]
Yep

**Comment by ignatov** [comment]
It's a platform issue, we're going to revert binary compatibility.

**Comment by dlsniper** [comment]
I've tried this again on a running debugging version and I can't replicate it anymore. Closing this.
