### ISSUE TITLE
Syntax category for built-in methods

### ISSUE THREAD

**Issue by wrouesnel** [go-lang-plugin-org/go-lang-idea-plugin#1841]
Built in methods like new(), delete() and make() etc. should have their own syntax category so they can be independently styled (since they are somewhat special, and somewhat important). There's already a category for built-in types (which inherit from the same module).

**Comment by dlsniper** [comment]
I do agree that the builtin functions are somewhat special but then go has also the "nice" which lets you define your own `new`, `delete` etc.. https://play.golang.org/p/vcuB7TJEdj 

Here's the full list of builtin functions as of go 1.5:

```
func append(slice []Type, elems ...Type) []Type
func cap(v Type) int
func close(c chan<- Type)
func complex(r, i FloatType) ComplexType
func copy(dst, src []Type) int
func delete(m map[Type]Type1, key Type)
func imag(c ComplexType) FloatType
func len(v Type) int
func make(Type, size IntegerType) Type
func new(Type) *Type
func panic(v interface{})
func print(args ...Type)
func println(args ...Type)
func real(c ComplexType) FloatType
func recover() interface{}
```

@ignatov should we highlight these in a special way if they resolve to the builtin package? If so maybe I can find some time for this in the coming weeks.
