### ISSUE TITLE
Publish the latest alpha code to the Intellij repository

### ISSUE THREAD

**Issue by jim-slattery-rs** [go-lang-plugin-org/go-lang-idea-plugin#1844]
**I suggest publishing the latest alpha code to the Intellij repository to keep people from giving up and moving to another Go IDE.**

I have been using the 0.9.15.3 plugin from the Intellij repository for months:
https://plugins.jetbrains.com/plugin/5047

I was frustrated that the project seemed to have been abandoned and the code navigation didn't work in so many cases.

On a whim, I installed the alpha version, and it has been very impressive and satisfying! Code navigation is very thorough, indentation is correct with Ginkgo tests, etc.  Only complaint I have is that the default code highlighting was excellent in 0.9.15.3, but totally sucked in the alpha version.. I have yet to restore the theme to the full glory of 0.9.15.3. :(

There must be many people like me, almost ready to give up on Intellij for Go projects, never realizing that this plugin is very mature and rocking!

**Comment by zolotov** [comment]
Hi @jim-slattery-rs,

Thanks you for feedback. We'll publish the alpha plugin to general channel for sure. At the moment we have no migration mechanism from 0.9.15 -> alphas, as soon it is implemented the plugin will be published.

As for syntax highlighting, maybe @dlsniper can say where you can find more colourful scheme, for now we're no going to change the default one.

**Comment by dlsniper** [comment]
Is there a way to embed multiple color schemes in the plugin for the language? If so, I could work on getting a version that works with IntelliJ and one with Darcula.

**Comment by zolotov** [comment]
@dlsniper not for language, but custom color scheme could be included

**Comment by dlsniper** [comment]
Here's the color scheme that I use for Darcula: https://www.dropbox.com/s/9cqvmhjm4cl9jwh/GoDarcula.icls?dl=0

Screenshot: 
![snapshot51](https://cloud.githubusercontent.com/assets/607868/9713155/cbd8a1a6-554f-11e5-9137-170e7cf6952b.png)

I don't know how to add it to the plugin, but if you can add this one, then I can do one for the IntelliJ (white) background as well and I'll keep updating this accordingly.

Please note this is exported from IDEA 14, not sure if it will work on IDEA 15. IDEA 15 on the other hand can't export the color scheme properly, please see https://youtrack.jetbrains.com/issue/IDEA-144831 (I know we don't support 142 branch yet but in case people wonder about it).

**Comment by wmacgyver** [comment]
given that the plugin is alpha, maybe you can require people to uninstall existing 0.9.15 before installing the new version? I've seen this done before, I remember having to do this with early intellJ scala plugins too.

**Comment by dlsniper** [comment]
@wmacgyver the update process doesn't require tp uninstall the old version as it will install the new one over it. The problem is in migrating existing SDKs and project types seamlessly, among others.

**Comment by Tolsi** [comment]
and what about >142 builds support?

**Comment by zolotov** [comment]
@Tolsi nothing yet, but it definitely will be supported as soon as IDEA 15 beta or release candidate will be available

**Comment by keltia** [comment]
Hello, by 142 builds/IDEA 15, does that include soon-to-be RubyMine 8.0?  I just got notified that the current Go plugin is not compatible with their next 8.0 beta (called EAP)... Using 0.9.460 here for now so I have not upgraded my RubyMine.

**Comment by zolotov** [comment]
@keltia yes, RubyMine 8.0 is based on 143.* build, you can check it in About dialog of IDE

**Comment by keltia** [comment]
Right, previous EAP were 142.something, now the build is 143.90.  Thanks.

**Comment by ignatov** [comment]
Out of date, I beleive.
