### ISSUE TITLE
idea plugin install failed

### ISSUE THREAD

**Issue by tidezyc** [go-lang-plugin-org/go-lang-idea-plugin#1845]
I add `https://plugins.jetbrains.com/plugins/alpha/5047` to my idea plugin's repository, and I can get `0.9.221` , but when install, idea return 404.

I check idea's download link, I get url `https://plugins.jetbrains.com//plugin/download?updateId=19172`, so the problem is double `//`

**Comment by dlsniper** [comment]
0.9.221 is a very very old build and many things have changed since then. Plead upgrade your IDE to one of the latest supported ones (see README).

**Comment by ignatov** [comment]
Please specify your product version and describe how you can get the url with double slash.

**Comment by tidezyc** [comment]
![Uploading Screenshot 2015-09-07 19.24.22.png…]()
![Uploading Screenshot 2015-09-07 19.24.22.png…]()

**Comment by dlsniper** [comment]
@tidezyc you commented before the screenshots were uploaded. Please update the comment. Thank you.

**Comment by tidezyc** [comment]
@dlsniper @ignatov 
<img width="548" alt="screenshot 2015-09-07 19 17 30" src="https://cloud.githubusercontent.com/assets/1592766/9715790/65144b72-5596-11e5-8a5f-5f1fd89ad670.png">
<img width="668" alt="screenshot 2015-09-07 19 21 07" src="https://cloud.githubusercontent.com/assets/1592766/9715785/6469ba36-5596-11e5-94f7-09213076ce57.png">
<img width="494" alt="screenshot 2015-09-07 19 22 06" src="https://cloud.githubusercontent.com/assets/1592766/9715791/65181e82-5596-11e5-995e-5f2a34dc8999.png">
I catch the request...
<img width="583" alt="screenshot 2015-09-07 19 22 24" src="https://cloud.githubusercontent.com/assets/1592766/9715786/646c507a-5596-11e5-9c58-3257ec6d6958.png">
<img width="399" alt="screenshot 2015-09-07 19 24 22" src="https://cloud.githubusercontent.com/assets/1592766/9715787/649b7378-5596-11e5-9e6c-c46f0d7fbfb1.png">

**Comment by dlsniper** [comment]
IDEA 14 is not supported anymore, please see the readme for the list of supported IDEs https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds (@ignatov please feel free to override me on this comment).

**Comment by tidezyc** [comment]
Thanks you @dlsniper , I will upgrade my idea and try again.
