### ISSUE TITLE
Unresolved reference on slices declared as types

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#1846]
Hey folks. This is unresolved reference on slices, round two.
SomeId member highlighted as unresolved.

Originating bug has been fixed, however in that case object was created using NewDataSlice. This time I created a data structure in place: data := &DataSlice{} and as data := DataSlice{}

I am using 488 build of Go plugin.

```Go
type TestStruct struct {
	SomeId int
}

type DataSlice []*TestStruct

func NewDataSlice() *DataSlice {
	return &DataSlice{}
}

func ErrorCode() {
	data := DataSlice{}
	for _, element := range data {
		if element.SomeId > 20 {
			println("some text")
		}
	}
}
```

One more example:

```Go
type TestStruct struct {
	SomeId int
}

type DataSlice []*TestStruct

func NewDataSlice() *DataSlice {
	return &DataSlice{}
}

func ErrorCode() {
	data := DataSlice{}
	for _, element := range *data {
		if element.SomeId > 20 {
			println("some text")
		}
	}
}
```

![image](https://cloud.githubusercontent.com/assets/4350891/9722956/caf7ab8a-556b-11e5-9b44-9d8702bcb862.png)

**Comment by esiqveland** [comment]
Adding example for non pointer slice:
```go
import (
	"testing"
	"fmt"
)

type Route struct {
	Name        string
}
type Routes []Route

func TestRoutesType(t *testing.T) {
	routes := Routes{
		Route{Name: "TestRoute"},
	}
	for _, route := range routes {
		fmt.Println(route.Name) // route.Name is marked as unresolved.
	}

}
```

**Comment by zolotov** [comment]
@esiqveland is it reproducible for the last alpha (0.9.518)?

**Comment by vburenin** [comment]
It still is. Pointer and non pointer examples are both reproducible.

**Comment by esiqveland** [comment]
@ignatov Yes, it is reproducible onn 0.9.518 alpha.
