### ISSUE TITLE
For iteration on a pointer slice is not valid

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1847]
This is a continuation of #1837. The difference is that in that example `data` is initialized via a call to a function, here it's initialized directly 

```go
package main

type TestStruct struct {
	SomeId int
}

type DataSlice []*TestStruct

func _() {
	data := &DataSlice{}
	for _, element := range data {  // here we should have an error: cannot range over data (type *DataSlice)
		if element.SomeId > 20 {
			println("some text")
		}
	}
}

func _() {
	data := DataSlice{}
	for _, element := range &data {  // here we should have an error: cannot range over cannot range over &data (type *DataSlice)
		if element.SomeId > 20 {
			println("some text")
		}
	}
}
```

**Comment by sjamesr** [comment]
How does one resolve a GoExpression to its type in an inspection context? Do we use `getGoType`? What is an appropriate parameter for `ResolveState`?

**Comment by zolotov** [comment]
@sjamesr yes, `getGoType`. Since you're starting resolve there, resolve state should be `ResolveState.initial()`

**Comment by sjamesr** [comment]
One more question :)

Let's say I have

```go
type (
    Packet struct {
        path string
    }
    Plugin struct {
        Path    string
        Packets Packets
    }
    Packets []*Packet
)

And then later

```go
p := Plugin{}
for _, p := range p.Packets {
        println(p.path)
}
```

How can I resolve `p.Packets` in the range expression to a type representing `[]*Packet`?

**Comment by zolotov** [comment]
You can use something like
```java
GoPsiImplUtil.findTypeFromTypeRef(element.getGoType(null).getTypeReferenceExpression())
```

Or see a more advanced version at `com.goide.psi.impl.GoFieldNameReference#findTypeFromRef`, you may want to extract it to `GoPsiImplUtil`.

Btw, `null` as a ResolveContext is ok, actually it's even better than `ResolveContext.initial()`
