### ISSUE TITLE
Debugging panic

### ISSUE THREAD

**Issue by cep21** [go-lang-plugin-org/go-lang-idea-plugin#1849]
Had this panic debugging my production Go server.  Can't spend time getting a small reproducible example, but hope the stack trace helps.  I was trying to set a few break points and inspect variables.  Happens consistently.

panic: runtime error: makeslice: len out of range

goroutine 33 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc2093be990, 0xc820138000, 0xc8200ff3e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/threads_darwin.go:88 +0xb0
github.com/derekparker/delve/proc.(*Thread).readString(0xc2093be990, 0xc820138000, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:596 +0x4d7
github.com/derekparker/delve/proc.(*Thread).extractValueInternal(0xc2093be990, 0xc2084934b0, 0x5, 0x24d368, 0xc8200ff328, 0x44ab2e0, 0xc208e8e540, 0x1, 0x0, 0x0, ...)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:523 +0x7c4
github.com/derekparker/delve/proc.(*Thread).extractValue(0xc2093be990, 0xc2084934b0, 0x5, 0x24d368, 0x0, 0x44ab2e0, 0xc208e8e540, 0x4938601, 0x0, 0x0, ...)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:477 +0xb8
github.com/derekparker/delve/proc.(*Thread).extractVariableFromEntry(0xc2093be990, 0xc209007290, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:410 +0x55f
github.com/derekparker/delve/proc.(*Thread).variablesByTag(0xc2093be990, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:849 +0x238
github.com/derekparker/delve/proc.(*Thread).LocalVariables(0xc2093be990, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:262 +0x5d
github.com/derekparker/delve/service/debugger.(*Debugger).LocalVariables(0xc20802d060, 0x2803, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:378 +0x220
github.com/derekparker/delve/service/rpc.(*RPCServer).ListLocalVars(0xc208021160, 0x0, 0x0, 0xc209340c60, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/service/rpc/server.go:224 +0x96
reflect.Value.call(0x4429400, 0x44eb7a0, 0x13, 0x4505940, 0x4, 0xc209011f28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x4429400, 0x44eb7a0, 0x13, 0xc209011f28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc20922e0c0, 0xc20922e080, 0xc2093aa0b8, 0xc209178700, 0xc209396400, 0x4394fa0, 0xc20933ee40, 0xd4, 0x4371600, 0xc209340c60, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:476 +0x44a

goroutine 1 [chan receive]:
main.execute(0x0, 0xc20805b7c0, 0x1, 0x4, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/ignatov/delve/cmd/dlv/main.go:311 +0x756
main.func·005(0xc208045040, 0xc20805b7c0, 0x1, 0x4)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/ignatov/delve/cmd/dlv/main.go:103 +0x45
github.com/spf13/cobra.(*Command).execute(0xc208045040, 0xc20805b6c0, 0x4, 0x4, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/spf13/cobra/command.go:476 +0x3d4
github.com/spf13/cobra.(*Command).Execute(0xc2080449c0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/spf13/cobra/command.go:550 +0x414
main.main()
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/ignatov/delve/cmd/dlv/main.go:266 +0xbaf

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc20806e2c0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/proc.go:653 +0x5d
created by github.com/derekparker/delve/proc.New
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/proc.go:65 +0x215

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc2091c0060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2091c0060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2091c0000, 0xc2081d2000, 0x600, 0x600, 0x0, 0x4911d60, 0xc20933ee68)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080420d8, 0xc2081d2000, 0x600, 0x600, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc2080ca000, 0x40196f0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc2080ca000, 0x4446360, 0xc2093d0080, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:44 +0x7b
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc2093d0060, 0xc2093962e0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/server.go:66 +0x9c
net/rpc.(*Server).readRequestHeader(0xc20922e080, 0x4acaad8, 0xc2093d0060, 0x0, 0x0, 0xc2093962e0, 0x4792e00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:575 +0x97
net/rpc.(*Server).readRequest(0xc20922e080, 0x4acaad8, 0xc2093d0060, 0xc209178700, 0xc209396400, 0x4394fa0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/rpc/server.go:542 +0xa2
net/rpc.(*Server).ServeCodec(0xc20922e080, 0x4acaad8, 0xc2093d0060)
	/usr/local/go/src/net/rpc/server.go:461 +0x6d
github.com/derekparker/delve/service/rpc.func·002()
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/service/rpc/server.go:65 +0x1c5
created by github.com/derekparker/delve/service/rpc.(*RPCServer).Run
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/service/rpc/server.go:66 +0x18d

**Comment by dlsniper** [comment]
Please report this to delve's repository as that's the correct place to report it. https://github.com/derekparker/delve/issues/new

**Comment by dlsniper** [comment]
Cc @derekparker for this one, just in case :-)

**Comment by cep21** [comment]
Looks like https://github.com/derekparker/delve/issues/189

**Comment by ignatov** [comment]
We'll upgrade out local delve bundle after the fix.

**Comment by bitshark** [comment]
I found the same problem today .. it's definitely fixed when I revert to 0.5.0, but I don't think that will work with Idea. It seems present in versions of Delve after 0.5.0.  https://github.com/derekparker/delve/issues/227

**Comment by dlsniper** [comment]
@bitshark you are correct. The plugin relies functionality that was added after 0.6 and also delve itself had many changes between changes not to warrant a support for multiple versions. Once delve is mature (read 1.0) things might change, but I'd rather not comment on that yet.
