### ISSUE TITLE
Rename a type or method is not supported.

### ISSUE THREAD

**Issue by coocood** [go-lang-plugin-org/go-lang-idea-plugin#185]
I don't know if this is easy or not. 

it requires to search the entire project and determine if the matched code is that identifier.

but rename is so important, i do rename all the time to improve the readability of the source code.

**Comment by smotes** [comment]
What is the status on this issue being resolved?

**Comment by smotes** [comment]
@mtoader Do you know the status on this issue?

**Comment by glyn** [comment]
Renaming a method in an interface is partially implemented, but it can introduce a compile error because it doesn't attempt to rename "corresponding" implementation methods. Similarly for renaming an implementation method.

Anyway, I'm pleased to see this bug has been raised.

**Comment by dlsniper** [comment]
I'll migrate this one to 1.next as I'm not sure if it's that important for 1.0 release. The issue was opened for the 0.9.x branch

**Comment by dlsniper** [comment]
Type renaming is supported, as well as methods (but not from the interface itself). Closing this for now.

**Comment by zolotov** [comment]
>  but it can introduce a compile error because it doesn't attempt to rename "corresponding" implementation methods. Similarly for renaming an implementation method.

**Comment by dlsniper** [comment]
Yes, but I'd rather have this opened as a separate issue (if it's not already one) that continue this ticket. What do you think?

**Comment by zolotov** [comment]
I don't mind

**Comment by glyn** [comment]
Raised https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2909. Thanks for all you are doing!
