### ISSUE TITLE
How to bundle delve into the plugin on local compiling

### ISSUE THREAD

**Issue by sjamesr** [go-lang-plugin-org/go-lang-idea-plugin#1850]
Hi there,

I noticed that when I'm running IntelliJ + go-lang-idea-plugin at HEAD in my dev environment, the debugging option is not available. How does one go about getting delve to work inside the (excellent) plugin dev environment?

Thanks,
James

**Comment by ignatov** [comment]
Hi, you should put delve from https://github.com/ignatov/delve into 
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/runconfig/application/GoApplicationRunningState.java#L102

**Comment by ignatov** [comment]
@dlsniper Will be cool to have such instruction in our contributing page.

**Comment by dlsniper** [comment]
Noted. I'll add them soon. Thanks.
