### ISSUE TITLE
https://plugins.jetbrains.com/plugins/nightly/5047  debug error

### ISSUE THREAD

**Issue by zld406504302** [go-lang-plugin-org/go-lang-idea-plugin#1851]
/usr/local/go/bin/go build -o /private/var/folders/7q/h53xbfx93n97b2hpd363p64r0000gp/T/go_demos0go -gcflags "-N -l" /Users/zhanglida/go_path/src/go_demos/src/xiaosheng/main/demos_main.go
"/Users/zhanglida/Library/Application Support/IntelliJIdea14/Go/lib/dlv/mac/dlv" --listen=localhost:57354 --headless=true exec /private/var/folders/7q/h53xbfx93n97b2hpd363p64r0000gp/T/go_demos0go --
panic: runtime error: makeslice: len out of range

goroutine 15 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc20826d8f0, 0x33166, 0x88201df000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/threads_darwin.go:88 +0xb0
github.com/derekparker/delve/proc.(*Thread).readString(0xc20826d8f0, 0x33166, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/github.com/derekparker/delve/proc/variables.go:596 +0x4d7
github.com/derekparker/delve/proc.(*Thread).extractValueInternal(0xc20826d8f0, 0x0, 0x0, 0x0, 0x820219bf8, 0x44ab2e0, 0xc2083786c0, 0x41e1901, 0x2, 0x0, ...)
	/Users/builduser/buildAgent/work/7f96eedd5bfd3f89/gopath/src/git

**Comment by ignatov** [comment]
Duplicates #1849
