### ISSUE TITLE
Create test files without _test suffix in package name

### ISSUE THREAD

**Issue by jen20** [go-lang-plugin-org/go-lang-idea-plugin#1852]
I briefly searched but didn't find a duplicate of this, possible that it is though (if so apologies!)

Go Plugin Version: 0.9.488

## Steps to reproduce:

1. Create Go Module
1. Add a directory named (for example) `config`
1. Create a new Go file in the `config` directory named `config_test.go`

**Expected result:** the package name should be `config`
**Observed result:** the package name is `config_test`

---
Count for options on how the package should be named when the file is created:
- 2 -> `name_test`
- 3 -> `name`

**Comment by zolotov** [comment]
Why do you think it's incorrect behaviour?

**Comment by Tyndie** [comment]
Just tried this out, if you create a file called this_test.go in the same directory it will use the package config_test which seems correct.

**Comment by zolotov** [comment]
So there is no issue, right?

You can find the rules of choosing package name for new file here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/actions/GoCreateFileAction.java#L48

And here is test file: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/tests/com/goide/actions/GoCreateFileActionTest.java

Please let me know if something wrong with it.

**Comment by jen20** [comment]
I would imagine the package name should follow the containing directory rather than the file - it's disconcerting to add (for example) `config.go` to a directory called `config`, and then to add `config_test.go` and have it in a package anything other than `config` (since it will likely want access to the package internals of the `config` package).

**Comment by zolotov** [comment]
Package name is based on containing directory, since you've added test file, the '_test' suffix was added to directory name and package name became `config_test`, so it doesn't really depend on file name.

> since it will likely want access to the package internals of the config package

It depends on developer, current behavoir is not incorrect, it corresponds to one of several possible test layouts (http://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-in-go-lang). Even if I changed this behaviour someone would like to revert these changes, so at the moment I prefer to do nothing and wait more feedback.

**Comment by jen20** [comment]
Ah, I see, I was misinterpreting how it was constructing the package name. 

Perhaps this should be a configuration point in the future? Personally I almost always use the pattern where tests are in the same package as the code.

**Comment by zolotov** [comment]
> Perhaps this should be a configuration point in the future? 

Perhaps, but usually we avoid any configuration options, so feedback is needed.

**Comment by dlsniper** [comment]
For what it counts, I have over 95% of the tests across my Go code base as it makes it easier to have a clean separation of test code and production code, plus the whole black box testing makes the API cleaner so if it's a +1 count, mine would be for the current behavior (while unexpected, prefered).

@zolotov would it be possible to have an editable selection (like the one in the rename for example, or if something better exists) for the `_test` part of the package name? That way, if the user doesn't need / want the package to be named `name_test` but `name` it can be removed with a press of two keys: DEL + Enter.

**Comment by zolotov** [comment]
@dlsniper not that easy. There is an old related issue https://youtrack.jetbrains.com/issue/IDEA-45030

**Comment by Barberrrry** [comment]
I have the same issue. For example, I have a directory `config` with file `config.go` in it. Package name is `config` too. When I add file `config_test.go` the package become `config_test` which seems wrong to me. It would be great, if package name has been extracted from filename but without suffix `_test`. I believe it's the most popular case.

**Comment by zolotov** [comment]
@Barberrrry 

> When I add file config_test.go the package become config_test which seems wrong to me. 

But it's not wrong, please read all comments here for details.

> It would be great, if package name has been extracted from filename but without suffix _test.

Of course it wouldn't. Different packages in one directory is a error, with algorithm you've suggested IDE will produce errors on each file creating.

> I believe it's the most popular case.

Do you mean the case without using "_test" prefix in package name? Do you have statistic on usage different approaches on naming test packages?

**Comment by Barberrrry** [comment]
There is a Go-convention about creating tests in the same package as functionality, but putting them to file with suffix `_test` to build it only by `go test`. There is no reason to create package `config_test`. I believe, vast majority of gophers follows this convention. 
https://golang.org/doc/code.html#Testing

**Comment by zolotov** [comment]
> There is a Go-convention about creating tests in the same package as functionality

I didn't say anything about creating tests in the same package as functionality

>  I believe, vast majority of gophers follows this convention. 

What convention? You said there is no one.

**Comment by Barberrrry** [comment]
Never mind. It looks like there is no fair solution for this issue.

**Comment by zolotov** [comment]
> Never mind. It looks like there is no fair solution for this issue.

I totally agree with it. However @dlsniper suggested some workaround that can make it easier for you. And likely I'll implement this workaround in future, that's why issue is still open.

**Comment by mdwhatcott** [comment]
Who not have two templates? One that adds the `_test` suffix to the package name and one that doesn't. The practice of appending `_test` to the package name in `*_test.go` files is not universal, nor is it required.

For what it's worth, 99% of all the tests I've ever written have NOT been in a package with the `_test` suffix.

http://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-in-go-lang/20009631#20009631

**Comment by dlsniper** [comment]
> For what it's worth, 99% of all the tests I've ever written have NOT been in a package with the _test suffix.

Yes, but that's your case unfortunately there's no evidence in the wild which one is preferred. This setting is not set in stone and there are voices for either of the choices or even for both. There are some options like you can see above, but it might take a little to find that's the right path to do this (and actually have time to be implemented).

> Why not have two templates?

@zolotov this had me thinking. Could the plugin maybe use an editable file template (I'm thinking Settings -> Editor -> File and Color templates) and then people would just customize that? We already have Go application and Go File.

**Comment by zolotov** [comment]
1. Now test files is created in the same package (without _test suffix)
2. Go File template is editable. Moreover there is one extra variable `GO_PACKAGE_NAME_WITH_TEST_SUFFIX` that is current package or current package + `_test` suffix for test files
3. After file creating caret is placed just after package name, so you can modify package name (manually or using auto-completion) in any way you want

**Comment by mdwhatcott** [comment]
Thanks for the thoughtfully accomodating implementation @zolotov!
