### ISSUE TITLE
Unit test icons do not reflect the pass/fail status of the tests in runner

### ISSUE THREAD

**Issue by jen20** [go-lang-plugin-org/go-lang-idea-plugin#1853]
Version: 0.9.488

When running unit tests, the icons for the tests do not reflect the pass/fail status of each test as expected.

### Steps to reproduce

1. Add a `.go` file with unit tests
1. Run the tests (via the context menu in this case)
1. Wait for the tests to pass or fail (as reported by the console output and the status bar)

**Expected result:** the icons show green/red for pass/fail as when running JUnit tests in IntelliJ
**Observed result:** the icons remain in the "indeterminate" state as per this screenshot:

<img width="1122" alt="Test Window" src="https://cloud.githubusercontent.com/assets/548524/9741669/a68ff478-5629-11e5-8b21-7d1270642b3c.png">

**Comment by sjamesr** [comment]
I think I have a fix, just waiting for Google legal team to approve the (tiny) patch
