### ISSUE TITLE
Contributing document states that Go upto 1.4.1 is supported

### ISSUE THREAD

**Issue by JasonRosenberg** [go-lang-plugin-org/go-lang-idea-plugin#1856]
I'm looking at:  https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#checking-out-the-intellij-idea-platform-sources

It states there's support only for Go version 1.4.1 and below.  However I've been using it just fine using 1.4.2.  So maybe this wiki text should be updated?

**Comment by dlsniper** [comment]
Thank you for this one, I'll update it soon.
