### ISSUE TITLE
Project SDK does not upgrade to new version of Go

### ISSUE THREAD

**Issue by amirhosseinab** [go-lang-plugin-org/go-lang-idea-plugin#1857]
After adding Go 1.5.1 as new SDK to IntelliJ Idea, I have chaneged `Project SDK` to that but in the `Project` toolbox, under the `External Libraries` node it does not change to the new SDK.

Am I doing something wrong or it must change in this way?

**Comment by zolotov** [comment]
Please recheck module SDK: File | Project Structure | Modules

**Comment by amirhosseinab** [comment]
Thanks, it works!

**Comment by dlsniper** [comment]
Also, as long as you don't mind having the old version displayed, you should just install the Go SDK in the previous directory and IDEA will pickup and refresh the it. I'll close this for now as it seems to be "fixed"/answered.
