### ISSUE TITLE
Redeclared import path: underscore

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#1866]
On commit d7e7b53f0cc3fc059717fd3d13ebc8fff3485f25

```go
package main

import (
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png" // flagged as redeclared import
	_ "image/gif" // flagged as redeclared import
	"image/color"
)

func main() {
	_ = image.YCbCr{}
	_ = color.Alpha{}
}
```
Original report:
I'm using: Latest commit from master, Intelij IDEA 14.1.4, OSX 10.10.5
Please see print screen: 
![screen shot 2015-09-17 at 8 30 16 pm](https://cloud.githubusercontent.com/assets/372027/9942466/6fa19652-5d7b-11e5-9133-653e44c72e2a.png)

**Comment by dlsniper** [comment]
@SchumacherFM do you think you could provide a sample code? I'll try to do something as well meanwhile.

**Comment by SchumacherFM** [comment]
Here you go: https://github.com/SchumacherFM/mediamock/blob/master/csv.go

**Comment by dlsniper** [comment]
Thanks, I've managed to isolate it to something smaller, I've added it to the ticket body.

**Comment by sjamesr** [comment]
My bad, the attached pull request (https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1868) should resolve it.

**Comment by dlsniper** [comment]
@sjamesr awesome, thank you!

**Comment by zolotov** [comment]
@sjamesr btw, if commit message will contain `Fixes issue_id` string then issue will be closed automatically after merge.

**Comment by sjamesr** [comment]
Ahh, good to know, thanks!

On Thu, Sep 17, 2015 at 2:22 PM, Alexander Zolotov <notifications@github.com

**Comment by SchumacherFM** [comment]
Thanks guys! :-)
