### ISSUE TITLE
Incorrect type of an argument that is a function with named return values

### ISSUE THREAD

**Issue by carmandrew** [go-lang-plugin-org/go-lang-idea-plugin#1869]
I think there's a problem when inferring the type of an argument that is a function with named return values.

For example, this shows no errors as expected:
```
func foo(fn func() error) {
	err := fn()
	err.Error()
}
```

However this shows an err on the `err.Error()` line:
```
func foo(fn func() (myErr error)) {
	err := fn()
	err.Error()
}
```
like so:
<img width="204" alt="envelope_go_-_s0_-____code_s0_" src="https://cloud.githubusercontent.com/assets/630721/9947869/a480cd26-5d52-11e5-8f9d-b0154ab61843.png">

Probably because it seems to think that `err` has the type `func() (myErr error)`:
<img width="295" alt="envelope_go_-_s0_-____code_s0_" src="https://cloud.githubusercontent.com/assets/630721/9947886/ce47a3a0-5d52-11e5-8b68-33a86d707922.png">

Using intellij 14.1.4 and plugin version 0.9.485

**Comment by ignatov** [comment]
Please try tonight build in several hours.
