### ISSUE TITLE
delve working when path / file name contains a space

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1873]
my os: debian 8.2, amd64

dlv works fine under macos, but not work under my debian, wish to help, 3x

test code is very easy
```
package main

import "fmt"

func main() {
	a :=1
	fmt.Println("aa",a)
}
```

plugin version 0.9.501

**Comment by dlsniper** [comment]
Hi,

Assuming you are using IntelliJ 14, please set the executable bit for delve:
```bash
chmod +x ~/.IntelliJIdea14/config/plugins/Go/lib/dlv/linux/dlv
```
Then you can run
```bash
cd ~/dir/of/the/file/you/want/to/debug
~/.IntelliJIdea14/config/plugins/Go/lib/dlv/linux/dlv debug file_to_debug.go
```
and try to replicate the steps that you are doing in the IDE (setting breakpoints and so on) and let us know how it works out. It might be a bug in Delve, which in this case should be reported to that project.

Thank you for your help.

**Comment by zolotov** [comment]
@ziyouchutuwenwu what does "it doesn't work" means? Any error message are shown? Also logs `Help | Show Log` might be useful.

**Comment by ziyouchutuwenwu** [comment]
ide, webstorm linux version
http://download-cf.jetbrains.com/webstorm/WebStorm-10.0.4.tar.gz

```
package main

import "fmt"

func main(){
  a := 100

  fmt.Println(a)
}
```

i test dlv by command, it seems to work fine, here is the steps

```
cd ~/golang/myApps/src/MyApp
~/.WebStorm10/config/plugins/Go/lib/dlv/linux/dlv debug MyApp.go
```
```
(dlv) sources
/home/mmc/golang/myApps/src/MyApp/MyApp.go
....
....
....
```

```
b MyApp.go:8
Breakpoint 1 set at 0x4010023 for main.main ./MyApp.go:8
```

```
c

print a
100
```

under webstorm,i right click MyApp directory, select "debug app and run" to add a run configuration
then set a breakpoint on line 8, last i click debug button, but no breakpoint stopped.


screenshots

command debug under linux ok
![5](https://cloud.githubusercontent.com/assets/7458713/9976619/6570e9b0-5f1c-11e5-84d4-a275af006c0b.png)

debug configuration
![8](https://cloud.githubusercontent.com/assets/7458713/9976622/707dfc58-5f1c-11e5-8946-8d9c27b6f284.png)

break point not stop
![9](https://cloud.githubusercontent.com/assets/7458713/9976623/723eac4a-5f1c-11e5-8cfd-d3d4cb3cbd03.png)

**Comment by ziyouchutuwenwu** [comment]
problem resolved!

i change the default debug configuration name from "Build XXX and run xxx" to "myApp"
i think maybe the blank is not allowed.

so could you please set the default running configuration name to single word? such as project name or just "run", or just "debug"?

thanks for your great work!

**Comment by zolotov** [comment]
> so could you please set the default running configuration name to single word? such as project name or just "run", or just "debug"?

No, we can't, it's not `debug` configuration, it's just build and run configuration.

I'll try to recreate an issue then, restriction on run configuration looks strange.

**Comment by dlsniper** [comment]
I can recreate the issue on my system. If the executable has a space in the name then delve will get confused apparently.

I've created the issue: https://github.com/derekparker/delve/issues/239.

@zolotov should we close issues like this and refer to the ones from delve when it's the debugger rather that the plugin?

**Comment by zolotov** [comment]
> @zolotov should we close issues like this and refer to the ones from delve when it's the debugger rather that the plugin?

@dlsniper yes, I think so, thank you for investigation
