### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#1879]
```
package main

type Type interface {
	Size() int64
}

type ArrayType struct {
	Type Type
}

func zeroArray(t *Type) {
	at, _ := (*t).(*ArrayType)
	println(at.Type) // shouldn't be a error
	println(at.Type.Size) // shouldn't be a error
}
```

**Comment by Mingan** [comment]
I'm just trying out [Squirell](https://github.com/Masterminds/squirrel) and when I try the Postgres example:
 
    package main

    import sq "github.com/Masterminds/squirrel"
    
    func main() {
        sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
    }

v0.9.562 gives me Unresolved Reference on `PlacehodlerFormat` (and then on subsequent calls). If I read it correctly, this is the same issue and therefore already fixed, right?

**Comment by zolotov** [comment]
@Mingan there are a lot of rules on resolving in Go and code samples from the issue and from your comment look completely different, so I guess it's another resolving issue.

**Comment by dlsniper** [comment]
I think this is a good isolated reproduction for the issue described by @Mingan:

```go
package main

type PlaceholderFormat interface {
	ReplacePlaceholders(sql string) (string, error)
}
type Builder struct{}
type StatementBuilderType Builder

func (b StatementBuilderType) PlaceholderFormat(f PlaceholderFormat) StatementBuilderType {
	return (struct{}{}).(StatementBuilderType)
}

var EmptyBuilder = Builder{}
var StatementBuilder = StatementBuilderType(EmptyBuilder).PlaceholderFormat()

func main() {
	StatementBuilder.PlaceholderFormat(struct{})
}

```

**Comment by Mingan** [comment]
@zolotov thank you for your quick reply. I see you reopened this issue already.

Building on @dlsniper's example: the incorrect highlighting occurs only when called in a function. Any directly chained calls are fine:

```go
var StatementBuilder = StatementBuilderType(EmptyBuilder).PlaceholderFormat().PlaceholderFormat()
```
