### ISSUE TITLE
Debugging in symlinked project paths doesn't work

### ISSUE THREAD

**Issue by alex-pozdnyakov** [go-lang-plugin-org/go-lang-idea-plugin#1880]
Debugging doesn't work in folders with symbolic links. Step-by-step guide:
1) Create some folder:
```
mkdir ~/SomeFolder
```
2) Create symbolic link to this folder:
```
ln -s ~/SomeFolder ~/LinkToSomeFolder
```
3) Create simple project in ~/LinkToSomeFolder
4) Try to debug this project
5) Make sure that application doesn't stop on breakpoints

---
Original report:

When i run debug configuration for application, placed in the path with cyrillic characters, application doesn't stop on breakpoints. Same configuration works well in latin characters named path.

**Comment by zolotov** [comment]
Might be related #1873

**Comment by alex-pozdnyakov** [comment]
Ok, seems like problem is not in cyrillic characters. When i place my project in $GOPATH/src/Test ($GOPATH = /home/user/Projects/Go, Test is project name), debugging doesn't work, but when i place it in user's home directory, debugging works properly. I'm using Ubuntu 14.04 x64 and Go 1.5.1.

**Comment by dlsniper** [comment]
@alex-pozdnyakov can you please make a screenshot of your run configuration? I don't really understand how to try and reproduce the issue. Thank you.

**Comment by alex-pozdnyakov** [comment]
@dlsniper Just finally find the real reason for this problem. Debugging doesn't work in folders with symbolic links. Step-by-step guide:
1) Create some folder:
```
mkdir ~/SomeFolder
```
2) Create symbolic link to this folder:
```
ln -s ~/SomeFolder ~/LinkToSomeFolder
```
3) Create simple project in ~/LinkToSomeFolder
4) Try to debug this project
5) Make sure that application doesn't stop on breakpoints

**Comment by dlsniper** [comment]
I'm sorry, I'm not able to replicate this, at least not from within delve (outside of the IDE).
My layout is like this:
- GOPATH=/home/florin/golang
- project dir=$GOPATH/src/github.com/dlsniper/u
- executable is at $GOPATH/src/github.com/dlsniper/u/dbg/1/demoexec

I've created this symlink: `ln -s $GOPATH/src/github.com/dlsniper/u/dbg/1 ~/demo`. Then I've went in `~/demo` and ran `dlv exec ./demoexec` which executed perfectly fine.

**Comment by alex-pozdnyakov** [comment]
@dlsniper It's not about delve, it's about Go plugin. Plugin creates binary files in /tmp:
```
/home/user/.go/bin/go build -o /tmp/Test0go -gcflags "-N -l" /home/user/Projects/Go/src/Test/Test.go
/home/user/.IntelliJIdea14/config/plugins/Go/lib/dlv/linux/dlv --listen=localhost:34624 --headless=true exec /tmp/Test0go --
```
and this files don't affect debugging process, but directory, that contains source files, do. In my case it's /home/user/Projects/Go/src/Test, and /home/user/Projects is symlink to /home/user/.hdd/Projects.

**Comment by hiromaily** [comment]
I found this issue and have not  solved that yet.
What is current status on the issue?

**Comment by akaspin** [comment]
+1
