### ISSUE TITLE
No SDK Specified

### ISSUE THREAD

**Issue by atilkan** [go-lang-plugin-org/go-lang-idea-plugin#1882]
Since same issue submitted long time ago. I submit again. I don't know if this plugin currently being developed.
1. Install go language support to ide. Restart.
2. Create a project, Choose go project.
3. Choose go sdk path? I choose. It accepts.
4. When clicking next, It warns me "No SDK Specified"

**Webstorm 10 and intellij 14** same error
**Go Version** 1.5
**Go Plugin Version** 0.9.15.3, also tried 0.9.13, 0.9.10
**Ubuntu** 14.04. LTS
**java version** "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6)

**Also submitted to jetbrain:**
https://youtrack.jetbrains.com/issue/WEB-18190

![screenshot from 2015-09-19 18 19 47](https://cloud.githubusercontent.com/assets/1254613/9978737/4d92bc8e-5f4d-11e5-956a-ee675cba1c84.png)
![screenshot from 2015-09-19 18 21 59](https://cloud.githubusercontent.com/assets/1254613/9978736/4d928520-5f4d-11e5-9e7a-06d7dd1745c5.png)

**Comment by dlsniper** [comment]
Hi, please read the README https://github.com/go-lang-plugin-org/go-lang-idea-plugin#go-plugin-for-intellij 
Any version below 0.9.100 is not supported anymore.

Thank you.

**Comment by atilkan** [comment]
Did you intend to write 0.9.10
**If not** versioning confusing for human eye
**else** my version higher

**Comment by dlsniper** [comment]
I did _not_ intended to write 0.9.10.

The latest version of the plugin is 0.9.485 (alpha) and 0.9.509 (nightly).

Please follow the instructions in the readme (link I've mentioned) to install the latest version of the plugin in a supported environment.

**Comment by atilkan** [comment]
Well, Thanks. Instructions are not the best but figured out. It is working now. 
These days to do one thing you gotta learn too many separate tools.

**Comment by dlsniper** [comment]
> Well, Thanks. Instructions are not the best but figured out. It is working now. 

I'm sorry the process is not as clear as it should be.

We welcome contributions of any form and for anything related to the plugin, be it code or documentation. If you want to help us out and improve the documentation on how to install the plugin for the future users, please feel free to send a PR or a suggestion on how to change them.

Thank you.

**Comment by atilkan** [comment]
I can make instructions with images to help.
