### ISSUE TITLE
Allow connecting to existing Delve instance

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1886]
It would be useful if the IDE could connect to an active running Delve session.
The user should supply the right address, which could (should ?) be over HTTPS, and the IDE should be able to interact with the existing instance (read existing breakpoints in that instance, set new ones and so on).

**Comment by dlsniper** [comment]
I've put this as a 1.0 maybe as it could be just as well delayed after 1.0 or until someone contributes it. Hope that's ok.

**Comment by ignatov** [comment]
First of all, this functionality should be supported by delve. At the moment it allows single connection via JSON RCP: terminal or external guy.

**Comment by dlsniper** [comment]
There are two ways to do this:
- existing debug session should allow for JSON RPC connection (maybe there should be a command to enable / disable this)
- one launches delve manually with the proper arguments to support a JSON RPC connection but the machine is not on 127.0.0.1 (say a container or a different machine / network).

The first case is not supported by delve right now but the second case is supported. I'll try to address the first case in delve.

**Comment by dlsniper** [comment]
I'm closing this in favor of #620 which is basically offering the same functionality.
