### ISSUE TITLE
react function ok package will not work perfectly

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#1890]
as topic, here is a test project named MyApp

```
mmcdeMacBook-Air:MyApp mmc$ tree
.
├── Myapp.go
└── aa
    └── gg.go
```

gg.go
```
package aa

func PP()  {
}
```

MyApp.go
```
package main

import (
	"MyApp/aa"
)

func main() {
	aa.PP()
}
```

when i right click "react, rename" on directory aa, change directory name to "qq", MyApp.go does not change each reference.
```
package main

import (
	"MyApp/aa"
)

func main() {
	qq.PP()
}
```
importing not changed, when i did react again, revert directory name to "aa" by right click directory, choose "react, rename", MyApp.go file change nothing

**Comment by zolotov** [comment]
Please use search.

 Duplicates #1294, relates to #1711
