### ISSUE TITLE
evaluate expressions on breakpoints

### ISSUE THREAD

**Issue by ramigg** [go-lang-plugin-org/go-lang-idea-plugin#1892]
Can't evaluate expressions (adding watch expressions) on breakpoints.

**Comment by dlsniper** [comment]
@ramigg can delve support this? Can you please provide a sample?

**Comment by ignatov** [comment]
Delve can't evaluate expressions right now, only symbols. Please create an appropriate request in the delve tracker.

**Comment by dlsniper** [comment]
@ignatov / @zolotov I've quickly had a look in delve, there's no mention in the current version of support for evaluating expressions. The only evaluation it can do right now is to print a variable.

I've created this one: https://github.com/derekparker/delve/issues/251

**Comment by dlsniper** [comment]
Delve gained support for evaluating expressions and we are using the latest build in the nightly so I'll close this for now. If someone wants / needs to evaluate a certain expression I guess all we can do is wait for that someone to open a specific issue here (and then forward it to Delve).
