### ISSUE TITLE
IDE 14.15 build  141.2735 - plugin does not find go sdk location

### ISSUE THREAD

**Issue by miqui** [go-lang-plugin-org/go-lang-idea-plugin#1893]
plugin cannot find go sdk location when creating a new go project

**Comment by dlsniper** [comment]
Hi, as you haven't provided too many details, I'll assume that you are using:0.9.15. As such please follow the instructions https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/#pre-release-builds for how to install the latest version. 
Please feel free to reopen the issue once you can provide more details. 
Thank you.
