### ISSUE TITLE
I having trouble with GOPATH and Intellij idea

### ISSUE THREAD

**Issue by ProIceZa** [go-lang-plugin-org/go-lang-idea-plugin#1898]
I use MACOSX 10.10.5 and use Intellij IDEA as IDE.

I already install GO SDK (by download SDK from website and not from Macports)and try simple program, it work correctly.

I try to use gorilla library (http://www.gorillatoolkit.org/pkg/mux#overview), So I set GOPATH like this

GOPATH=$HOME/work
PATH=$PATH:$GOPATH/bin
go get github.com/gorilla/mux
and Add PATH to intellij, see figure below. Set gorilla library
![screen shot 2015-10-02 at 4 55 15 am](https://cloud.githubusercontent.com/assets/4063169/10236417/62af1816-68cf-11e5-8147-aad58d267d61.png)

![screen shot 2015-10-02 at 5 03 02 am](https://cloud.enter image description heregithubusercontent.com/assets/4063169/10236408/511b7b3a-68cf-11e5-8815-a69088ac3d58.png)

When i import this library IDE throw error like this.
![screen shot 2015-10-02 at 4 55 15 am](https://cloud.githubusercontent.com/assets/4063169/10236425/77fb545a-68cf-11e5-8f0e-00d1dc6d787d.png)

So i try to fixit like this  http://stackoverflow.com/questions/17771091/i-use-intellij-idea-as-golang-ide-and-system-environment-have-already-set-gopat

But it do not work for me. how can I set GOPATH in idea?

**Comment by dlsniper** [comment]
Hi, which version of the plugin are you using?

**Comment by dlsniper** [comment]
I also recommend that you have a look at this tutorial for how to configure the plugin and create your first project http://hadihariri.com/2015/09/30/setting-up-go-on-intellij/ Hope it helps.

**Comment by ProIceZa** [comment]
Um, i might be make some mistake.

I make simple GO application and it work correctly and i have no problem with GOROOT

i have a problem with external library, i make GOPATH directory and i install  library in that PATH and set GOPATH to Intellij idea but int not work.

maybe i asking in a wrong place (Intellij forum tell me to asking in here). 

I use Go plugin version 0.9.485

thank you mr dlsniper

**Comment by dlsniper** [comment]
Could you please post a screenshot of File -> Languages and Frameworks -> Go -> Go Libraries?  Thank you

**Comment by dlsniper** [comment]
@ProIceZa I'll close this as it lacks feedback for almost a month now. Please reopen this when you'll have any additional details. Thank you.
