### ISSUE TITLE
Rune literals marked as syntax error

### ISSUE THREAD

**Issue by jen20** [go-lang-plugin-org/go-lang-idea-plugin#1901]
Version: 0.9.525

Using the rune literal syntax as described in the Go Language Specification is marked as a syntax error by IntelliJ using the nightly build. I do not recall if this is a regression or not. A screenshot is attached - the code compiles and runs using the `go` tool, and IntelliJ.

![Rune literal is marked as syntax error](https://cloud.githubusercontent.com/assets/548524/10261096/266a70a4-6955-11e5-8d34-961291ff53d6.png)

**Comment by dlsniper** [comment]
Hi, sorry for assigning it earlier without checking.
I've just ran into about the same code as above and it worked.
I've then went and created the following sample:
```
package main

import (
	"bufio"
	"io"
)

func main() {
	a := io.Reader{}
	reader := bufio.NewReader(a)
	_, _ = reader.ReadString('\n')
}
```

@jen20 can you please check your import statements and make sure you are importing the correct package?
Also, please try the above example to see if it works.

Thank you.

**Comment by dlsniper** [comment]
Also, what's the exact error IntelliJ is saying? Thank you.

**Comment by dlsniper** [comment]
@jen20 any updates on this? Otherwise I'll close this. Thank you.
