### ISSUE TITLE
[feature request] OrientDB SQL Dialect

### ISSUE THREAD

**Issue by dopgm** [go-lang-plugin-org/go-lang-idea-plugin#1904]
Hi guys,

Would be great to have an OrientDB SQL Dialect in IDEA IDEs.

For example, generic/MySQL won't accept

```SQL
elect expand($c)

    LET $artist = (SELECT FROM...
```

Thank you!
Dennis

**Comment by zolotov** [comment]
Hi @dopgm,

This plugin has nothing to do with SQL support, please forward you feature request to https://youtrack.jetbrains.com

**Comment by dlsniper** [comment]
Hi Dennis,

From your request I understand that this is not related to the Go plugin, for which this repository is meant to be, but rather the whole IntelliJ platform, please see: https://youtrack.jetbrains.com/issues/DBE

**Comment by dopgm** [comment]
@zolotov 
Hi, sorry!!! Posted by mistake

**Comment by dopgm** [comment]
@dlsniper 
Thank you for the link!
