### ISSUE TITLE
Undefined variable is not reported

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#1907]
```Go
func test(ch chan string) string {
	select {
	case s := <- ch:
	}
	return s  // Should be reported error: `undefined: s`
}
```

Plugin version: 0.9.530

**Comment by dlsniper** [comment]
@ignatov I've labeled this as an inspection issue but I think it's more closely to a resolving issue as it seems the value of `s` from `return s` is resolved to the declaration in the `case s := <- ch:` expression and it shouldn't.

@horkhe thanks for reporting.

**Comment by horkhe** [comment]
The pleasure is all mine, as always :)
