### ISSUE TITLE
Run/Debug Configuration Name Used As Executible File Name

### ISSUE THREAD

**Issue by akevinbailey** [go-lang-plugin-org/go-lang-idea-plugin#1908]
When running a Go file or package the Go Plug-in always create the executable file name the same as the Run/Debug Configuration Name.  There is no way to override the <code>go build -o</code> output flag.  In my opinion this is a bug that makes test configuration using IntelliJ impractical.

**Comment by dlsniper** [comment]
Why isn't changing the name of the run configuration good enough?

**Comment by dlsniper** [comment]
Please share more details about the problem you have and are trying to solve. This will help understanding the issues/request. Thank you

**Comment by akevinbailey** [comment]
If I want to test usage I will name the Run/Debug as myapp --help and put --help as a program argument, If I want to test a connection I will name it myapp --connection and put -c tcp://someserver.com.  You get the idea?

This was it is coded now, i get an exe called myapp --help.exe and another one called myapp --connection.exe, etc.  If I have twenty of these configuration I get twenty exes and I only need one!

Either you need to put in a field for program name or you need to allow for the ability to shut off your -o output flag so we can enter our own in the Go tool arguments field.

**Comment by dlsniper** [comment]
Have you tried using `-o appName` in the go tool parameters input? I'm not able to check right now but matbe that will work. 
As for building the binary, you can choose to have a "go run"  based configuration, you shouldn't _need_ the "go build" configuration.

**Comment by akevinbailey** [comment]
Yes.  It does not work, because the plug-in puts its own -o at the end.  Go build will only accept the last -o flag.

**Comment by akevinbailey** [comment]
OK.  I figured it out.  You need to use Go Single File to get go run.  That works for me, but still would be nice to have the option of naming your executible.

**Comment by dlsniper** [comment]
Oh, ok. Then I suggest you use the other configuration type meanwhile. That way you won't have too many binaries built by the plugin. 

@zolotov what do you think, should the plugin detect if `-o appName` is passed by the user and build the binary based on that name? I'd say it's not that important and could be flagged as up for grabs.

**Comment by dlsniper** [comment]
> would be nice to have the option of naming your executible

Technically it's possible right now, just not for that specific use-case unfortunately.
We do happily accept contributions and this one should be easy to figure out so if you want to give this a try, we can help.

**Comment by akevinbailey** [comment]
I would love to help, but unfortunately I don't have the time right now.  Thanks for your time, and keep up the good work.

**Comment by zolotov** [comment]
First of all, IDE is not binary producer, so all issues about that are minor one and up for grabs.

In the second. @akevinbailey I didn't understand your scenario.

> If I have twenty of these configuration I get twenty exes and I only need one!

So what? Why is this should bother anyone? Run configurations are made for run, all output binaries will be deleted after.

**Comment by akevinbailey** [comment]
First of all, IDE does create the command to produce the binary and it is NOT deleted automatically.  And, second I disagree with you.  Good programmers alway abstract the project and configuration names form the executable names.  I'm pretty sure you see my point, but it you don't want to take 5 minutes to modify your code to give someone a choice of a different output name.

**Comment by zolotov** [comment]
> First of all, IDE does create the command to produce the binary and it is NOT deleted automatically. 

It doesn't delete it if you modified output path (someone asked to implement it recently).

> Good programmers alway abstract the project and configuration names form the executable names.

Didn't get it, looks like I'm not a good one. 

> I'm pretty sure you see my point, but it you don't want to take 5 minutes to modify your code to give someone a choice of a different output name.

That's funny, instead of explaining your point you're blaming me in something. Anyway, it's open source, you can take your 5 minutes and modify anything you want, good luck.
