### ISSUE TITLE
Import inside project not resolved

### ISSUE THREAD

**Issue by hobbs** [go-lang-plugin-org/go-lang-idea-plugin#191]
Here is the example project (this is the GOROOT):
https://gist.github.com/4463941

If you clone it, and create a new project in Intellij, whenever I use "conf" in main, it does not resolve that symbol:
![Screen Shot 2013-01-05 at 2 01 04 PM](https://f.cloud.github.com/assets/37571/45444/30d36be8-5785-11e2-821f-31235c345b0c.png)

However, it runs/builds fine with "go run". If I change "somesite.com/api/conf" to just "conf", it autocompletes and doesn't list an error when I use "conf", however "go build" gives the error:
main.go:10:2: import "conf": cannot find package

Another note: if I change "somesite.com/api/conf" to "./conf" it will build, but IntelliJ can't resolve 'conf' in main.

**Comment by varun-s** [comment]
@dmichael Thanks! Invalidating cache worked for me

**Comment by huaapp** [comment]
@dmichael Thanks! Invalidating cache worked for me
