### ISSUE TITLE
hi，can add markdown support in comment？

### ISSUE THREAD

**Issue by zhongguo168a** [go-lang-plugin-org/go-lang-idea-plugin#1912]
hi，can add markdown support in comment? When ctrl + click on [link] in comment, jump to define, 3q

**Comment by dlsniper** [comment]
Hi,

The builtin Markdown support plugin does not support `Inject language or reference`. However you can use the Multimarkdown plugin, https://plugins.jetbrains.com/plugin/7896?pr=idea (search for it in the IDE you use). To use this, please use: ALT+CLICK -> Inject language or reference -> MultiMarkdown
Additionally I've opened a ticket on YouTrack which you can follow here: https://youtrack.jetbrains.com/issue/RUBY-17234

Thank you.
