### ISSUE TITLE
Add word wrap while showing documentation

### ISSUE THREAD

**Issue by renannprado** [go-lang-plugin-org/go-lang-idea-plugin#1914]
It would be nice if there was word wrap while showing the documentation. That way we don't have to scroll left and right to read the documentation.

**Comment by dlsniper** [comment]
Hi,

I think this request is much better suited for the IntelliJ platform as the plugin merely returns the text required to be displayed.
The place to do such a request https://youtrack.jetbrains.com/

I'll close this for now.
@ignatov / @zolotov please reopen this if I'm wrong.

**Comment by zolotov** [comment]
@dlsniper it's not platform issue, it's your `pre`s actually: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1367/files#diff-297312c4b8f7eb144bdb1a24b41bdcb8R49

**Comment by renannprado** [comment]
Cool.
Thanks :+1:
