### ISSUE TITLE
when package name is the same as variable name, unused variable error will occur

### ISSUE THREAD

**Issue by liugangnhm** [go-lang-plugin-org/go-lang-idea-plugin#1916]
![image](https://cloud.githubusercontent.com/assets/743845/10441318/0aa7793e-717a-11e5-95bb-2e57e19b62f3.png)

```go
func TestVariable(t *testing.T) {
	time := time.Now()
	t.Logf("%#v", time)
}
```

Plugin version master (`1.0.0.alpha#538`)

**Comment by ignatov** [comment]
Thanks for reporting.

**Comment by ignatov** [comment]
Fixed in 0.9.540 (already in the nightly channel).

**Comment by ronindev** [comment]
I have same issue with 0.9.558

**Comment by dlsniper** [comment]
Hi @ronindev, 

Please open up a new issue with some more details and a code sample that can reproduce the issue as I can't reproduce it on my setup.

![snapshot97](https://cloud.githubusercontent.com/assets/607868/10586741/013233f2-769e-11e5-85bb-6a246912ad19.png)

Thank you!
