### ISSUE TITLE
Debug in routine

### ISSUE THREAD

**Issue by karboom** [go-lang-plugin-org/go-lang-idea-plugin#1919]
How can I debug a var in routine

**Comment by dlsniper** [comment]
Hi, I don't understand the question. Can you please provide more details? Thank you

**Comment by karboom** [comment]
```Go
func main() {
	a:=1

	go func() {
		b:=2
		fmt.Print(b)
	}()
	
	fmt.Println(a)
}
```
I have add a break point on `b:=2`, but it dosen't stop

**Comment by sjamesr** [comment]
the program finishes before the goroutine can run. Try adding a call to `time.Sleep(time.Second)` after the last print.

**Comment by karboom** [comment]
Thanks
