### ISSUE TITLE
debug button disabled in intellij-Idea

### ISSUE THREAD

**Issue by pylover** [go-lang-plugin-org/go-lang-idea-plugin#1923]
Ubuntu 32 bit, idea: 14.1.5, The latest nightly build of the plugin.
Anyway, the debug button is not enabled.

**Comment by dlsniper** [comment]
Delve doesn't support debugging 32 bit platforms so the IDE can't support that as well. Please keep an eye on delve for support for 32bit or use a supported OS (Linux or Mac OS X x64). Thank you

**Comment by pylover** [comment]
thanks for reply
