### ISSUE TITLE
Reload Changed Classes doesn't work anymore

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1924]
Hi,

Maybe I've configured my plugin incorrectly or something but it seems I can't use the `Reload Changed Classes` functionality anymore when working on the plugin.
The error I have is:
```
Error:Failed to load project configuration: cannot read file /home/florin/IdeaProjects/google-go-lang-idea-plugin/.idea/misc.xml: /home/florin/IdeaProjects/google-go-lang-idea-plugin/.idea/misc.xml (No such file or directory)
```

Is this expected since migrating from the old system to gradle?
Thank you.

**Comment by zolotov** [comment]
> I can't use the Reload Changed Classes functionality anymore when working on the plugin.

How do you run slave IDEA with go plugin?

> The error I have is:

the error has nothing to do with reloading classes functionality.

> Is this expected since migrating from the old system to gradle?

Missing misc.xml also has nothing to do with the project. It's part of you local project model and I have no idea why it doesn't exists, try to reconfigure SDK for project, maybe IDEA will recreate this file.

**Comment by dlsniper** [comment]
> How do you run slave IDEA with go plugin?

I use the `Debug 'Go'` configuration. I'll try and reimport the project, maybe that will fix it.

**Comment by ignatov** [comment]
So, does it work for you?

**Comment by dlsniper** [comment]
I've found the issue, at least using the latest master. Seems I've forgot to change the project SDK, for 141 branch. Updated the SDK to 143 and things work properly now. Sorry for noise.

**Comment by ignatov** [comment]
Nice!
