### ISSUE TITLE
Debugging does not work right for me

### ISSUE THREAD

**Issue by eugen-nw** [go-lang-plugin-org/go-lang-idea-plugin#1931]
I'm brand new to Go so please bear with me.  I have the delve debugger installed and had verified that I can debug using it in a Terminal window.  I installed the  https://plugins.jetbrains.com/plugins/nightly/5047 Go plugin, and all of code completion, formatting, highlighting work.  The debugger stops at the breakpoint, yet I cannot see variables & watches + cannot step in the debugger.  As instructed by https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1252 I made sure that I installed the nightly build of the Go plugin.  Is debugging working at this point, or did I miss configuring something please?

Environment: Ubuntu 12.04.5 LTS, IntelliJIDEA comm. edition 14.1.5, build #IC-141.2735

**Comment by zolotov** [comment]
Hi, thanks for report, watching and stepping into should work.
I think it could be code-specific so code sample would be useful for recreating the issue. Or some screencast, for example.

**Comment by dlsniper** [comment]
Hi, like Zolotov said, code would be great. Additionally, there's a bug in delve which might be what you are experienced but without a way to reproduce it ourselves, there's no way to tell why this happens. Cheers

**Comment by eugen-nw** [comment]
Thanks very much for having looked into this!  In the attached picture I'm stopped on line #14. 
![golangplugin](https://cloud.githubusercontent.com/assets/15199814/10585515/766f0b92-764c-11e5-94a4-fb8f29a378c4.png)

The code itself:
package main

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/sns"
	"fmt"
)

func main() {
	abc := 123
	fmt.Println(abc)
	config := aws.Config{Region: aws.String("us-west-2")}
	svc := sns.New(&config)
	fmt.Println(svc.APIVersion)
}

Could it be possible that the go plugin is not 'seeing' the /home/edaroczy/go3rdParty/bin/dlv executable on my machine?

**Comment by dlsniper** [comment]
@eugen-nw delve is embedded in the plugin, so that's not the problem. To try to fix this please rename your run configuration from `Build main.go and run` to something like `build_main_and_run` and this should work.
Most likely, the reason for this happening is that the version shipped with delve contains a bug which makes it unable to handle binary targets when their name contains spaces.
Let me know if this helps.

**Comment by eugen-nw** [comment]
A mers strună, merci mult!

Thank you,  Eugen

**Comment by dlsniper** [comment]
Happy to hear ;)

**Comment by dlsniper** [comment]
@ignatov could you please update your for of Delve? I've just tested the debugger on the latest commit, https://github.com/derekparker/delve/tree/d4d4021a419bc8ec6c5fef20d4d89919f45e8a60, and everything seems to be working as expected.
This should fix reports like this.

Thank you.
