### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by olomix** [go-lang-plugin-org/go-lang-idea-plugin#1933]
Version 0.9.251, nightly
![screen shot 2015-10-20 at 09 50 20](https://cloud.githubusercontent.com/assets/518068/10600049/4c6c1406-7710-11e5-8c46-fdffd5c9caf4.png)

```go
package main

type A struct {}

type B struct {
    a     *A
}

func f() (resp []B) {
    return nil
}

func main() {
    var resp []A
    for _, a := range f() {
        resp = append(resp, *a.a)
    }

}
```

**Comment by dlsniper** [comment]
Please update to the latest plugin version. 0.9.251 is not supported since a while ago. In the latest releases the issue is fixed, I've just checked.

To see the upgrade instructions, please follow this link: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

Thank you

**Comment by olomix** [comment]
Sorry, I've used Idea 15 EAP and nightly builds doesn't support it. In Idea 14 everything is fine.

**Comment by dlsniper** [comment]
Yeap, no problem ;
