### ISSUE TITLE
Refactoring: rename symbols in comments 

### ISSUE THREAD

**Issue by nodirt** [go-lang-plugin-org/go-lang-idea-plugin#1935]
Given 

```go
// If is a function that does something. If x < 0, panics.
func If(x int){}
```

when renaming `If` to `When`, ask the user which occurrences of `If` in the comment to rename as well, so the user can choose not to rename the second occurrence.

Then perform the renaming in comments

**Comment by ignatov** [comment]
Please press **Shift + F6** twice and check an appropriate checkbox:
<img width="322" alt="screenshot 2015-10-25 01 29 25" src="https://cloud.githubusercontent.com/assets/426890/10713078/db6f33f4-7ab7-11e5-989d-de6af12ac11a.png">
