### ISSUE TITLE
Tree icon go files

### ISSUE THREAD

**Issue by hoenirvili** [go-lang-plugin-org/go-lang-idea-plugin#1940]
![screenshot from 2015-10-24 00-19-30](https://cloud.githubusercontent.com/assets/8754546/10705176/d046e5c2-79e4-11e5-9f66-4b9cabc55ad8.png)

If you look closely files like u.go and newtest.go dosen't have the goLang icon mascot. Why is this behaviour?
At first i tought that was a problem with the $GOROOT or $GOPATH variables or the SDK but i can compile and run code perfectly also i can import code and use without a problem.

### .profile
`
 export PATH=$PATH:/usr/local/go/bin
 export GOPATH=$HOME/Work/Go
 export PATH=$PATH:$GOPATH/bin
`

**Comment by dlsniper** [comment]
Hi @hoenirvili, which plugin version do you use? Thank you.

**Comment by dlsniper** [comment]
Also, do you use any custom IDEA theme? As it seems even the folders have a different color than mine on Darcula so I suspect it's not that theme, no?

**Comment by zolotov** [comment]
Looks like you have another plugin that registered *.go files, please check all installed plugins

**Comment by hoenirvili** [comment]
@dlsniper 
In the Settings>Plugins>Go is on version 0.9.562 Support for Go programming language.Alpha pre-release of the 1.0.0 version.
As theme and syntax i use Material Theme.

**Comment by dlsniper** [comment]
Cool, happy to hear it worked. Btw, what's the link to the theme? And maybe you can report the issue to it so that the maintainers are aware of the change (or maybe it's intentional from them). I'll close this for now. Cheers.
