### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by olomix** [go-lang-plugin-org/go-lang-idea-plugin#1942]
Plugin version 0.9.562
Intellij 14.1.5

![screen shot 2015-10-28 at 14 09 05](https://cloud.githubusercontent.com/assets/518068/10788074/9e980f3c-7d7d-11e5-9050-ea8bb8b38c4e.png)

```go
package main

type B1 struct {}
type B2 B1

func (b B2) method() B2 {
	return B2{}
}

func main() {
	b := B2{}
	b.method()
}
```

**Comment by dlsniper** [comment]
@ignatov this might be interesting to solve and afterwards test with the following sample: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1879#issuecomment-151464113 as, at least from the go code, it looks to follow the same issue, a type if defined on another type.

**Comment by olomix** [comment]
Heh, my version is simplified of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1879#issuecomment-151464113
I think it can be closed as duplicated.

**Comment by dlsniper** [comment]
I can't really comment on that as it might be different parts incorrect. Lets wait and see.
