### ISSUE TITLE
Display download progress for Gradle

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1944]
Hi,

Since the migration to build things with Gradle, it's very hard to predict how long it will take to have the dependencies in place, especially since downloading full IDEA when a version is bumped can be costly on slower network.
I've read this article about download progress with Gradle http://www.michel-kraemer.com/gradle-download-task-download-files-with-progress but I'm not sure if it applies to this or not or if IntelliJ supports this or not.
Any pointers for this?
Thank you!

![snapshot107](https://cloud.githubusercontent.com/assets/607868/10802754/df86063e-7dbe-11e5-8dd0-daa47ad21b8a.png)

**Comment by zolotov** [comment]
Download-task has nothing to do with Gradle dependency resolving mechanism. And go plugin has nothing to do with Gradle support in IntelliJ.

This issue looks similar https://youtrack.jetbrains.com/issue/IDEA-133836, please update it with comment about downloading dependencies, or file a new issue there.
