### ISSUE TITLE
"go tool: no such tool "6g"" when running any go build config

### ISSUE THREAD

**Issue by stevewest** [go-lang-plugin-org/go-lang-idea-plugin#1945]
When running any go run configuration (go application, single file or test) I am encountering the "no such tool" error. From what I understand this is because the `GOROOT` environment variable is not set correctly. I have tried setting it manually via PhpStorm's environment settings for the run configuration with no success, I have also confirmed that the paths defined in the `Go Libraries` settings section are correct.

Running any of the Go tools via a regular terminal either inside or outside of the IDE work without issue.

IDEA version: `PhpStorm 9.0.2`

OS version: `Linux Mint 17 Cinnamon 64-bit`

JDK version:
```
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```
Plugin version: `0.9.562`

Go version: `1.2`

**Comment by dlsniper** [comment]
Please don't set the GOROOT environment variable as it's not needed by the plugin.
As for the error itself, please describe where `go` (the binary) is, what's the directory layout for the Go SDK (where is it installed and the list of top most directories) and how you installed the Go SDK on your machine.
Also, you might want to consider upgrading your Go version as 1.2 is not supported by the Go team anymore (the plugin should still be able to understand the SDK tho).

**Comment by stevewest** [comment]
I was simply running through the things I have tried. I originally had the same issue in general as the GOROOT was not set so thought the issue might be related.

My go binary is at `/usr/bin/go` and was installed using apt from the Mint official repos.

The SDK libraries are under `/usr/lib/go` and the top level directories are: `doc`, `lib`, `pkg`, `src`.

Go works without issue when not using the plugin, it's only when attempting to run anything via the plugin's provided run configurations that the issue occurs.

**Comment by dlsniper** [comment]
@stevewest thanks for the details. One last thing, where is `6g` installed? in `/usr/bin/` as well?

As a temporary workaround I'd recommend to install the Go SDK from the archives https://golang.org/dl/ and things should workout (I admit it's not ideal).

@zolotov I think I'll have to leave this one with you as it's related to how the plugin identifies the SDK / location of the binaries.

From what I understand, Linux Mint maintainers decided to put things in other places than the way other packages have.

**Comment by zolotov** [comment]
@stevewest thanks for feedback. I need some details to fix this. 

1. Please share with github-gist the output of `tree -n 3 /usr/lib/go` command.
2. Please give me a screenshot of SDK that you've configured in plugin.
3. Tell me what's the correct value of GOROOT variable that allows you to use `go build` from terminal

**Comment by stevewest** [comment]
@zolotov 

1. https://gist.github.com/stevewest/e72466676652909c4bab
2. 
![image](https://cloud.githubusercontent.com/assets/2370734/10817012/e37b793e-7e2e-11e5-84ee-271e05b6bad6.png)

3. `/usr/lib/go`

@dlsniper Looking at the tree the `6g` tool is with everything else. I'll hold off on updating the SDK for now incase @zolotov needs any more info.

**Comment by zolotov** [comment]
@stevewest not libraries configuration, but SDK configuration (File | Project Structure | SDKs)

BTW, remove `/usr/lib/go` from go libraries. Including go sdk inside GOPATH may lead to unpredictable behaviour

**Comment by stevewest** [comment]
Whoops, my bad.

I can't find the `(File | Project Structure | SDKs)` that you mention unless you mean `Languages & Frameworks | Go | Go SDK` which currently has its path set to `/usr/share/go` and detects version `1.2.1`

If I remove the paths from the Libraries config the runs fail at finding dependencies, eg:
```
cannot find package "github.com/jessevdk/go-flags" in any of:
	/usr/share/go/src/pkg/github.com/jessevdk/go-flags (from $GOROOT)
	($GOPATH not set)
```

**Comment by zolotov** [comment]
> If I remove the paths from the Libraries config the runs fail at finding dependencies, eg:

Keep there the real GOPATH (/home/uru/work/go) and just remove GOROOT (/usr/lib/go)

> currently has its path set to /usr/share/go and detects version 1.2.1

Quite strange layout. And what is the `tree -n 3 /usr/share/go` output?

Also please tell me where `/usr/bin/go` link points (`ls -l /usr/bin/go`)

**Comment by stevewest** [comment]
Kept just the GOPATH but there's no change, still getting the `no such tool "g6"` error.

`tree -n 3 /usr/share/go` contains too much for my terminal buffer to cope with, but appears to contain all the `.go` libraries. If there's something specific in there you are looking for I can see if that exists.

`/usr/bin/go` is linked to `/etc/alternatives/go` which is linked to `/usr/bin/golang-go`

**Comment by zolotov** [comment]
> Kept just the GOPATH but there's no change, still getting the no such tool "g6" error.

I understand that.

> /usr/bin/go is linked to /etc/alternatives/go which is linked to /usr/bin/golang-go

And `/usr/bin/golang-go` is binary?

> tree -n 3 /usr/share/go contains too much for my terminal buffer to cope with

Maybe `tree -n2` will be enough

Also, please try to reconfigure `Languages & Frameworks | Go | Go SDK` to `/usr/lib/go`, since it's proper GOPATH

**Comment by stevewest** [comment]
`/usr/bin/golang-go` is binary:
```
$ /usr/bin/golang-go version
go version go1.2.1 linux/amd64
```

`tree -n 2` is still too large but what I have got can be found here:
https://gist.github.com/stevewest/197a8d3730735b25205b

Setting my SDK to `/usr/lib/go` works, I can now run through PhpStorm!

**Comment by zolotov** [comment]
I don't know then what's the `/usr/share/go`, you can try `go` binary there and check what it was :)

**Comment by stevewest** [comment]
Not quite sure myself where that came from, but thank you for all the help.
