### ISSUE TITLE
Support go-lang plug-in on recent IntelliJ releases?

### ISSUE THREAD

**Issue by aadrian** [go-lang-plugin-org/go-lang-idea-plugin#1946]
Hi,

the go-lang plug-in does not seems to be available (in the plug-in pane) for ```IntelliJ 14.1.5``` nor ```15 RC2``` :(.

thank you.

**Comment by dlsniper** [comment]
Hi,

The plugin is released in the main channel for IntelliJ 14.1.5
```
version: 0.9.562
IntelliJ Platform builds: 141.1532 — 141.*
Release date: 26.10.2015
```

The plugin is also available for IntelliJ 15 RC2 from the nightly channel, please see the instructions here for how to setup the nightly channel: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

Can you please share more details about you issue as I don't understand what's happening.

Thank you.

**Comment by aadrian** [comment]
> The plugin is released in the main channel for IntelliJ 14.1.5

The latest IntelliJ versions can't see it.

> Can you please share more details about you issue as I don't understand what's happening.

It's not in the list in order to be able to install it:
![golang_not_available](https://cloud.githubusercontent.com/assets/140953/10846965/98ff1cb8-7f13-11e5-83ac-2f24e2bf41a5.png)

**Comment by dlsniper** [comment]
> The latest IntelliJ versions can't see it.

What IDE version are you trying?

The plugin is present in the latest stable version of the IDE for me (14.1.5).
![snapshot109](https://cloud.githubusercontent.com/assets/607868/10847143/bc822576-7f14-11e5-8b42-dab5c0f3727c.png)

Thank you.

**Comment by aadrian** [comment]
> What IDE version are you trying?

I'm using both 14.1.5 and also 15 RC2.

It looks like searching changed between 14 and 15, as in 14 searching for "go" does not seem to really reduce the plug-in list (when sorted by date) compared to 15 :).

So I can browse tru the long list and find it but not really search it :).

Thank you for your support!

**Comment by dlsniper** [comment]
For IDEA 15, please see my comment above:

> The plugin is also available for IntelliJ 15 RC2 from the nightly channel, please see the instructions here for how to setup the nightly channel: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

Happy I could help you out.
