### ISSUE TITLE
contributors.md text doesn't match my experience setting up the project

### ISSUE THREAD

**Issue by patflynn** [go-lang-plugin-org/go-lang-idea-plugin#1947]
I'm following the steps here:
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development

steps:
1) checked out the project master @ a2e0908a7509239e6ad1bb2bc7da20b630ce7dec
2) installed IDEA IU-143.380.20
3) imported the project from Gradle: File -> New Project -> From existing sources
4) all default gradle project import settings
5) selected all the modules to import

expected:
The instructions indicate that there should be a 'go' run config.

actual:
there is no 'go' run configuration. 

The .idea folder contained in the git repository appears to have been replaced by the gradle import.  Is the Gradle import expected to merge its model with what's in .idea?

**Comment by zolotov** [comment]
Hi,

>  Is the Gradle import expected to merge its model with what's in .idea?

It's expected but it doesn't work properly, see IDEA issue: https://youtrack.jetbrains.com/issue/IDEA-146295

Just revert changed files in .idea/ directory and everything should be fine.
