### ISSUE TITLE
com.goide.inspections.GoHighlightingTest.testCgotest fails on master

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1952]
Hi,

It seems that `com.goide.inspections.GoHighlightingTest.testCgotest`test fails constantly on master or any other branches I create from it and I don't know why.

```
cgotest.go: Extra (5:3/6) :'unsafe' (Cannot resolve file 'unsafe') [HighlightInfoTypeImpl[severity=ERROR, key=WRONG_REFERENCES_ATTRIBUTES]]
cgotest.go: Extra (25:52/7) :'Pointer' (Unresolved reference 'Pointer') [HighlightInfoTypeImpl[severity=ERROR, key=WRONG_REFERENCES_ATTRIBUTES]]
```

My master hash is `a6be71fc5b19898e4e42ea60329178c125efd141`
Full log: https://gist.github.com/dlsniper/c18e36efc3b6ebc2f01c

**Comment by zolotov** [comment]
You can check tests state at https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Go_Test&branchSelectorEnabled=true&chartGroup=buildtype-graphs

In your case just try to invoke `gradle clean`

**Comment by dlsniper** [comment]
That helped. Thank you very much.
