### ISSUE TITLE
Wrong lines are not highlighted in build output window.

### ISSUE THREAD

**Issue by DmitriyMV** [go-lang-plugin-org/go-lang-idea-plugin#1956]
Hey everyone!

* IDEA 15.0 Community (same error on Idea 14)
* Windows 10 x64

When I try to build project which contains errors in source code, go build output doesn't highlight incorrect lines and so I can't go-to-source from there,

![image](https://cloud.githubusercontent.com/assets/6999905/10897993/62d8bf4c-81d7-11e5-8349-39e665bc1b2d.png)

Build command look like this 
![image](https://cloud.githubusercontent.com/assets/6999905/10898032/be16711a-81d7-11e5-9214-327214f38126.png)

**Comment by ignatov** [comment]
Please specify your plugin version

**Comment by DmitriyMV** [comment]
![image](https://cloud.githubusercontent.com/assets/6999905/10909607/7576b6ee-824b-11e5-9340-ad45c23afcbe.png)

**Comment by zolotov** [comment]
Thanks for report. Will be fixed in the next nightly.
