### ISSUE TITLE
Scroll from source error.

### ISSUE THREAD

**Issue by Hyzhou** [go-lang-plugin-org/go-lang-idea-plugin#1962]
```go
import (
	"github.com/oscarrr110/cert-tools/Godeps/_workspace/src/github.com/codegangsta/cli"
)

func initAction(c *cli.Context) {
       c.String("xxx")
}
```

I user this import, and the plugins find the source context.go. using Command + B
But, It can not use Scroll from source. to find source file. and can not analysis c.String function.

**Comment by dlsniper** [comment]
Hi, which IDE are you using and what version of the plugin? I'll try to replicate the issue but the translation makes it a bit difficult to understand exactly the problem.

**Comment by Hyzhou** [comment]
The IDE: Intellij IDEA 14.1.4, Build #IU-141.1532
The Plugin: It is build by source, I build it at 2015.09.29, git version is 92ef04ea413ca7fda510249aee4317318c675c18

**Comment by dlsniper** [comment]
Hi. There have been a few updates since then, please update the plugin from the nightly or latest sources. I don't yet have time to look into this but I'll try some time tonight to see how can I reproduce it. Thanks for the details.

**Comment by Hyzhou** [comment]
I used latest source.
When I import a path which loaded with godep tool. It can not be found by plugin.
```go
import (
    "github.com/oscarrr110/cert-tools/Godeps/_workspace/src/github.com/codegangsta/cli"
)

func initAction(c *cli.Context) {
       c.String("xxx")
}
```
In this case, The plugin can find the file. But the plugin can not find the method String.
Godeps/_workspace is management by the godep tool.

**Comment by dlsniper** [comment]
Hi @Hyzhou, I'm not able to replicate your issue unfortunately.
Please see a video of how I've installed the package you've mentioned from scratch and navigating to / from source worked ok: https://youtu.be/B2jpOlJEv2w
Can you please share a similar one?
Or:
- a screenshot of your Settings -> Languages & Frameworks -> Go -> Go Libraries
- how does your GOPATH looks like outside of the IDE

Thank you.

**Comment by Hyzhou** [comment]
![2015-11-05 9 43 44](https://github-cloud.s3.amazonaws.com/assets%2F5910417%2F10957699%2Fc02c561a-83a1-11e5-8458-ffc41268a233.png)

Left, The directory _workspace is red exclude.
So, The file 'init.go' can not find the method in the file 'context.go'

**Comment by dlsniper** [comment]
Aha! So that's why the issue happens. 
If a directory is marked as excluded then the IDE won't process the sources from it and features like the one you are having trouble with or even autocomplete will not work. 
Right-click on the _workspace directory, Mark as - > remove exclude (or something similar) and things should work again.
Please let me know if this worked.

**Comment by Hyzhou** [comment]
Because of library. I can not change the status. In the one hand, It is dependency lib, it can be exclude.On the other hand, I can not get the source, and the plugin can not resolve the method or struct in this file. I think the file under the _workspace can not be excluded.

**Comment by dlsniper** [comment]
Please go to the root of the projec and remove the ignore from there not from the libraries section.
Since you are using Godeps with path rewrite, all the libraries are becoming part of the project and they must be present in order for the IDE to do its job. By excluding them, the IDE cannot resolve them correctly.
I'll post an alternative way to remove the exclude later on. Thank you.

**Comment by dlsniper** [comment]
Can you please post a screenshot of Settings -> Languages & Frameworks -> Go -> Go Libraries.
Also what is your project directory root? 
I'm able to reproduce the `_workspace` directory flagged as excluded when the current project doesn't include it.
Thank you.

**Comment by Hyzhou** [comment]
I think so, This path is excluded. I have try to add the this path to lib. already fix it.
