### ISSUE TITLE
Make button doesn't do anything.

### ISSUE THREAD

**Issue by DmitriyMV** [go-lang-plugin-org/go-lang-idea-plugin#1966]
I know it was raised before, and it was stated that with Go it's hard to guess what this button should actually do. But it was never told how to build golang project in IDEA without running it. Some explanation and/or adding that to the wiki would be really helpfull. Thanks.

P.S. Maybe make button should be disabled entirely?

**Comment by dlsniper** [comment]
Hi. Yes it has been discussed to good amounts, please see: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1453#issuecomment-83124378
Unfortunately disabling it is not an option as this is just a plugin for IntelliJ platform which can be used in all the IDEs / combined with other languages which might need that functionality. It has also been discussed.
If you can think of a way to solve this issue, we are happily receiving feedback.
I'll close this for now.

**Comment by DmitriyMV** [comment]
Hi, yes. I upated the erferenced issue. Also - so there is really no way to build project in IDEA without running it?

**Comment by dlsniper** [comment]
This has been addressed as well in the issue and in the referenced issue. Why would it be useful to build a Go project from the IDE without running it? You can get the binary output if you want it but assuming you are making changes to your source code, that binary becomes obsolete as soon as that happens.

**Comment by DmitriyMV** [comment]
Hmm - the only reason that is coming to my mind is to check sources for errors. But I think I have better solution for this.

**Comment by dlsniper** [comment]
I do admit that not everything is in place yet, especially when it comes to inspections and type inference.
Usually there are test sources and running tests is equivalent (or should be) to running the app (and compile it in the first place).
I use the go build command from the builtin terminal to help me identify such compiling issues when tests aren't an option.
