### ISSUE TITLE
Integrate gotype into plugin.

### ISSUE THREAD

**Issue by DmitriyMV** [go-lang-plugin-org/go-lang-idea-plugin#1967]
Right now we have gofmt and goimports to format and import dependencies. But we don't have anything to check for code correctness aside from plugin's abilities. I propose to add [gotype](https://godoc.org/golang.org/x/tools/cmd/gotype) command into plugin external tools to check for source correctness without building the project.

P.S. There is *Command Line Tool Support* plugin, but it requires Ultimate edition which seems unnecessary for Go ATM. Maybe there are other ways to add arbitrary tools for Go project?

**Comment by zolotov** [comment]
Thanks, I'll add it.

> But we don't have anything to check for code correctness aside from plugin's abilities.

We think that it's better to expand plugin's abilities instead of using external tools like `gotype`, because it's faster (you see all inspection reports while typing the code), more flexible (IDE can provide quickfixes for some types of errors), more predictable (it doesn't lead to bugs like #1965).

Also, implementing type-check inspections on our side can bring benefits to completion, refactoring and add some extra ways to code navigation.

**Comment by DmitriyMV** [comment]
Yes, I agree entirely. That;s why I said add, not replace. Just a little helper tool.

**Comment by zolotov** [comment]
I added the gotype action in Code menu.

However, what exactly functionality from `gotype` util you're missing in plugin?

**Comment by DmitriyMV** [comment]
How does it suppose to work btw? I added gotype into GOROOT bin directory, but it seems like it doesnt work for some reason.

**Comment by dlsniper** [comment]
@DmitriyMV you have to add it in the GOPATH/bin not in GOROOT. simply use `go get -u golang.org/x/tools/cmd/gotype`

![snapshot130](https://cloud.githubusercontent.com/assets/607868/11049548/5a1f63e8-873f-11e5-87c5-5489cf412ef9.png)

If that doesn't work, please send a screenshot of your Settings -> Languages & Frameworks -> Go -> Go Libraries. Thank you.

**Comment by dlsniper** [comment]
P.S. You have to have the editor active in the IDE.

**Comment by DmitriyMV** [comment]
Nope - doesn't work for me for some reason.

![image](https://cloud.githubusercontent.com/assets/6999905/11052095/12bafd10-8766-11e5-9b33-ce7c24be86c4.png)

**Comment by dlsniper** [comment]
Ok, so gotype should be in `C:\Dmitry\Coding\Go\bin`, if it's there and you have the editor file active (you can type stuff in the file) when invoking, can you please open up a follow up issues with the ide name, version, plugin version, os version and the logs from the ide. Preferably you can remove the old logs, start the ide again, go in the menu and use gotype option and see what appears in the logs. 
Thank you.

**Comment by DmitriyMV** [comment]
Works fine - I created a new issue for package check problem.
