### ISSUE TITLE
Add the support to "strings.Split" in search everywhere.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#1970]
I just found that I can not find anything with "strings.Split" in search everywhere in v0.10.607 of this plugin with Community idea 15.
![image](https://cloud.githubusercontent.com/assets/1107541/10986279/a81455c4-8463-11e5-8566-6f7e14974332.png)

I also want to search "json.Marshal".

**Comment by dlsniper** [comment]
Please tick the `include non-project items` in the Search Everywhere dialog and try then. I'm not near a computer to see if this will work but it's a start. Thank you.

**Comment by ignatov** [comment]
Reproduced, thanks. As a workaround please use `go to symbol` action.

**Comment by ignatov** [comment]
You can enable a searching by `package.name` with the registry option: **search.everywhere.pattern.checking**.

**Comment by bronze1man** [comment]
@ignatov I do not understand what you want me to do to use this feature.

Can I use this feature in the next alpha version without any config?

`go to symbol` works,But the order looks strange to me.
![image](https://cloud.githubusercontent.com/assets/1107541/11013488/e108a37a-854a-11e5-9a41-b963efbd170c.png)

**Comment by ignatov** [comment]
@bronze1man 
> Can I use this feature in the next alpha version without any config?

Not so fast. Search everywhre is a platform action: [SearchEverywhereAction.java#L2257](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/ide/actions/SearchEverywhereAction.java#L2257).
I defenetly reccomend you to [enable the registry](http://stackoverflow.com/questions/28415695/how-do-you-set-a-value-in-the-intellij-registry) option **search.everywhere.pattern.checking** at the moment.

**Comment by bronze1man** [comment]
Thanks, it looks like I have to do some config to use it.

**Comment by ignatov** [comment]
BTW, it's an open question for @bulenkov about this registry option.
