### ISSUE TITLE
Support for external documentation (godoc.org)

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1978]
Hi,

I wonder if there's any value in providing the `External documentation` support for the plugin.
It should open godoc.org at the targeted package / function / method / etc. but since the IDE is already doing a good job at this I don't know if it brings any extra value to have it or not.

**Comment by mdwhatcott** [comment]
(The IDE is indeed doing a great job showing documentation.) I also see value being able to open the godoc page or, in the case of the standard library opening the package documentation on golang.org.

**Comment by zolotov** [comment]
> opening the package documentation on golang.org

Implemented with default `show external doc` action

> I also see value being able to open the godoc page

How is that? Could you file a separate issue with detailed description please?
