### ISSUE TITLE
Having trouble configuring the project for hacking...

### ISSUE THREAD

**Issue by mdwhatcott** [go-lang-plugin-org/go-lang-idea-plugin#1981]
Forgive my ignorance with Java and the Intellij plugin platform. I'm trying to get setup to contribute so I'm following the [instructions on the contributing guide](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#getting-started-with-the-plugin-development). The gradle import process seems to be hanging--it gets to a certain point:

<img width="527" alt="screen shot 2015-11-09 at 8 39 59 pm" src="https://cloud.githubusercontent.com/assets/202910/11053855/191ce432-8722-11e5-97f0-ebfb78dfe2f2.png">

And then just sits there forever (I've waited up to 10 minutes--should I wait longer?).

<img width="1316" alt="screen shot 2015-11-09 at 8 38 24 pm" src="https://cloud.githubusercontent.com/assets/202910/11053864/299e692a-8722-11e5-93e0-1dfeef620b4e.png">

Any ideas?

**Comment by mdwhatcott** [comment]
Forgot to mention, I'm on Mac OS X 10.10.5.

<img width="431" alt="screen shot 2015-11-09 at 8 44 02 pm" src="https://cloud.githubusercontent.com/assets/202910/11053913/b1b68ad6-8722-11e5-8181-f79d14a3ddff.png">

**Comment by dlsniper** [comment]
Depending on your Internet speed this might really take a good while. 
However, you are not supposed to get the error, can you please create a gist with the log files? If there are multiple files in the directory, please look at the latest (or remove all of them, restart the ide and start the process again).
Thanks.

**Comment by ignatov** [comment]
You can use `gradle build` from the command line with a reliable progress.

**Comment by mdwhatcott** [comment]
Thanks!
