### ISSUE TITLE
Support benchmark running

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#1995]

**Comment by sjamesr** [comment]
I'm going to have a go at this by adding a new framework type (there will be gotest, gocheck and gobench). Please stop me if you don't think this is the right approach :)

**Comment by zolotov** [comment]
@sjamesr I guess it's ok

**Comment by sjamesr** [comment]
I think this is good to go now, the output looks really nice unless the benchmark emits messages that confuse the output processor.
