### ISSUE TITLE
Add library to module without $GOPATH?

### ISSUE THREAD

**Issue by pspeter3** [go-lang-plugin-org/go-lang-idea-plugin#1997]
What is the right way to add a library to an IntelliJ project when not using the $GOPATH option.

**Comment by dlsniper** [comment]
Hi please describe what you want to achieve with examples as I don't really understand the question. Thank you.

**Comment by pspeter3** [comment]
I'm setting up a project with bazel and downloading files through that mechanism. This means that srcs live under `bazel-{workspace_name}/external` and packages, `*.a` files, live under `bazel-bin`. What directories should I add to access them?

**Comment by dlsniper** [comment]
Assuming your project is under /home/dlsniper/goProject and your libraries are under /home/dlsniper/goProject/external/src then yes. 

To change the GOPATH that a project is using you can go to Settings -> Languages and Frameworks -> Go -> Go Libraries and you can use the settings there. 

If it doesn't answer the question, please provide a clear example. Thank you.

**Comment by pspeter3** [comment]
So any go library must have `src` directory in it? Am I correct in understanding that a Go Library is roughly equivalent to a GOPATH then?

**Comment by dlsniper** [comment]
A Go Library path in the plugin is the equivalent of a GOPATH  entry not to a package entry. Packages are contained in gopat (or in a go library path in plugin language).
 The plugin doesn't support yet the go1.5 vendor experiment and from the description it doest seem you'll use that anyway.

**Comment by pspeter3** [comment]
Thank you for the explanation. As a final question, does the plugin use the source `*.go` files or the `*.a` package files?

**Comment by dlsniper** [comment]
The the source files are used.
The plugin doesn't yet support the compiled packages.
If you'll still have issues, please follow up with a sample import statement from the code and the paths on disk. Thanks.

**Comment by pspeter3** [comment]
No, I'm good. Thank you for all of your help!

**Comment by dlsniper** [comment]
Cool, happy to help. If there will be any other issues, please ping us. Have fun.
