### ISSUE TITLE
Inspection for "continue is not in a loop"

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2002]
```go
func demo(a bool) {
	if a {
		continue // should be an error: continue is not in a loop
	} 
}
```

The quick fix should offer to convert this to a return statement.

**Comment by sjamesr** [comment]
Should we offer the quick fix only if the continue inside a function returning void?

**Comment by dlsniper** [comment]
For now I think it would be good enough to let the user add the missing return parameters as a return statement without all the params will be flagged as error anyway.
