### ISSUE TITLE
Building a package

### ISSUE THREAD

**Issue by iampeter** [go-lang-plugin-org/go-lang-idea-plugin#2008]
Is it correct, and deliberate, that I can build a package (my package, let's say `main`), as `Run type` `Package` only if I put it into `src/main` and add my project directory as a project library in the Settings?

Otherwise the package is not found when definining Run configuration.

Moreover, if I add my project path to be a project library, all subsequent `go get`s will download packages into my `src` dir.

What is the most natural equivalent configuration to `go build` when you have a project consisting of multiple files?

**Comment by zolotov** [comment]
> Is it correct, and deliberate, that I can build a package (my package, let's say main), as Run type Package only if I put it into src/main and add my project directory as a project library in the Settings?

Your project must be in GOPATH, it's the necessary for `go build` as well. So yes, your project must be defined in Go Libraries.

> Moreover, if I add my project path to be a project library, all subsequent go gets will download packages into my src dir.

Depends on order of you libraries, if you have only one GOPATH value – your project root, then yes, all `go get` invoked from IDE will download packages in your project.

 > What is the most natural equivalent configuration to go build when you have a project consisting of multiple files?

`Go Application` run configuration is the most natural equivalent to `go build`. It is the `go build` actually.

**Comment by dlsniper** [comment]
Please add to the description of your issue concrete paths, a screenshot of the run configuration and a screenshot of Settings -> Libraries and Frameworks -> Go -> Go Libraries otherwise this is too abstract to be able to help out more.

And follow what @zolotov said as well.

Thank you.

**Comment by iampeter** [comment]
OK so both approaches (single global GOPATH and global GOPATH + project GOPATH) worked for me now, thank you.

What do you guys suggest is the best approach with this plugin? The generic Golang suggested config - one GOPATH or additional GOPATHs per project?

**Comment by dlsniper** [comment]
I use a single global GOPATH but for the plugin doesn't really matter which approach you are using. Ideally you should use the same approach that you have for your shell or that the project you have need.

**Comment by iampeter** [comment]
OK thank you.

A related question: shouldn't CTRL+B also show the local definitions?

Example:

I have a `Logger` function in my files, but CTRL+B only suggests the global symbols from the `log` package.

**Comment by zolotov** [comment]
@iampeter 

> A related question: shouldn't CTRL+N also show the local definitions?

Ctrl+N shows only types. In order to search among all symbols you should use cltr+shift+alt+n (https://www.jetbrains.com/idea/help/navigating-to-class-file-or-symbol-by-name.html)

Or just use Search everything (Shift+Shift)

**Comment by iampeter** [comment]
Let me re-phrase my question: couldn't it also show functions, all the exported symbols?

**Comment by zolotov** [comment]
> Let me re-phrase my question: couldn't it also show functions, all the exported symbols?

No, Ctrl+N is for types only. For functions and other symbols:  cltr+shift+alt+n or double-shift

**Comment by iampeter** [comment]
OK thanks @zolotov @dlsniper for your assistance.
