### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by BKadishAdFin** [go-lang-plugin-org/go-lang-idea-plugin#2010]
Issue #1879 describes an unresolved refrence while using the [Squirrel Library](https://github.com/Masterminds/squirrel). I am still having the same issue even after updating to the latest build (Version 0.9.661) The unresolved reference is still there.

OS: 10.10.5
IDE: 14.1.5
JDK: 1.8

Small example

```go
import sq "github.com/lann/squirrel"
var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
```

Yields: Unresolved reference PlaceholderFormat 

Code from the library 
```go
var StatementBuilder = StatementBuilderType(builder.EmptyBuilder).PlaceholderFormat(Question)
```

**Comment by zolotov** [comment]
I think it's not backported to 0.9.* versions yet (IDEA 14), works file on 0.10.* versions (IDEA 15)

**Comment by BKadishAdFin** [comment]
Thanks for the heads up

**Comment by ignatov** [comment]
Backported, will be available next nightly build for 141.
