### ISSUE TITLE
GO issue. File undefined

### ISSUE THREAD

**Issue by human87** [go-lang-plugin-org/go-lang-idea-plugin#2012]
From the user feedback:

>Hello, I am trying to use the GO plugin. I have an app that has a directory with approx 20 go files all under package main. I have setup the the intellij config as "Go single File". I try to run the app and it compiles my main.go but then it complains about not finding other types/funcs in the other go files in the same dir. This app compiles fine with go run *.go

>Here is a sample project with 2 go files https://dl.dropboxusercontent.com/u/6595319/gotest.zip <https://dl.dropboxusercontent.com/u/6595319/gotest.zip>

>I cannot get this to work

**Comment by dlsniper** [comment]
For that case the run configuration should be of type Go Application with a package as run kind not file. As the name says, Go Single File run configuration is dedicated to running a single file.

I hope this helps.

**Comment by mistbow-git** [comment]
It's work, but not intuitive... ((

**Comment by dlsniper** [comment]
@mistbow-git how do you usually execute the project? That way it could help the plugin get better at it.

**Comment by mmargerumImpactrx** [comment]
I switched my project from "single file" to "go application" and I chose "run kind package"

I assume I should put "main" for the package setting?  When I do this I see "Error: cannot find package main"

I think the issue may be that I do not have the go files inside of the src directory inside the root of this project file.

**Comment by mmargerumImpactrx** [comment]
once I placed the files inside a src directory and added my root project directory to the "project libraries" in the "Go libraries" prefs, it picked up the other go files and the app runs now.

**Comment by zolotov** [comment]
> I assume I should put "main" for the package setting? When I do this I see "Error: cannot find package main"

You get the same message if you run `go build` form terminal because your project wasn't in GOPATH.

> I think the issue may be that I do not have the go files inside of the src directory inside the root of this project file.

Indeed, but plugin has nothing to do with it, it's actually golang workspace requirement: https://golang.org/doc/code.html#Workspaces

**Comment by margerum** [comment]
No I was able to go build and go run the project from the command line without modify any go path.

**Comment by margerum** [comment]
I do agree though that I should be following the recommended structure for projects.  Thanks

**Comment by zolotov** [comment]
> No I was able to go build and go run the project from the command line without modify any go path.

You can do this only for building by files. For package building you have to have proper GOPATH, otherwise gobuild cannot find target package by its import path.

**Comment by margerum** [comment]
Right I'm effectively doing a multi file build using package main.  That's what was confusing me because I'm not building a package.

**Comment by zolotov** [comment]
@margerum I see. Please follow for updates of #2013, I think I can add multifile run support as part of that issue

**Comment by vchekan** [comment]
I've read this thread and #2013 thread, and I still do not understand what am I suppose to do. If setting GOPATH is the only way, then where do I do it, practically speaking? Not in .bashrc, because I might have more than one go project to work on. Not in command line, because it is just too annoying to set it every time I (re)start IntelliJ. What's left?

**Comment by dlsniper** [comment]
Hi @vchekan, can you please explain a bit more what are you trying to do? It's a bit unclear for me from the message. Maybe you can open up a new issue so that we can talk there without sending mails to others as well. Thank you.

**Comment by vchekan** [comment]
Well, perhaps my problem is typical for all go newcomers. After making simple 1-file program working, I decided that gopath is something like ~./m2 or ~/.ivy, i.e. a folder where dependencies are cached. I know, it is wrong but it is the most logical thing newcomer will conclude. Than my project became too big for one file and I made it 2-file, still keeping all in "main" package. Compiled fine from command line. And than I spent whole evening trying to compile it from IDE. And came to conclusion that go support is not complete in the plugin. Than I found these two topics and a couple of evenings later I realized that gopath is not what I thought to be and they want all my projects to be mixed with all my dependencies in the same folder. So I am slowly realizing that my issue has little relation to the plugin and more to the go itself. 

But I just wonder either IntelliJ ability to mark up a folder as a "source" could help? For example, in "single file" mode, put the file chosen by the user as the first one (it is important for exe generation) and add all files from under "source" folder(s) to the list of compiled files?

**Comment by dlsniper** [comment]
@vchekan there are many issues with running the build in a directory. They are discussed on the linked issue.
There is also a plan to support multiple files in a runner so I'm not sure if I understand what we could do better. We could try and help out new gophers by giving them some warnings about their setup but that might be equally hard to do (and requires time as well).

**Comment by dlsniper** [comment]
Please feel free to help us improving the plugin by suggesting what we could do better to guard new users against mistakes, that would be really helpful!

**Comment by laymanmu** [comment]
This is what I just figured out:

When compiling a main package, don't put "main" in the "Package path" field. 
Instead, for example if your working directory is "/home/user1/go/src/**app1**", then set the following:

- Run kind:  Package
- Package path: **app1**

I don't understand why the "Package path" field is necessary.

**Comment by dlsniper** [comment]
> I don't understand why the "Package path" field is necessary.

The package path is needed because the plugin cannot determine which ` package main ` you want to run. Consider the case where you want to run ` main ` but there are two different ` main ` packages in the current project. As such, the plugin allows the same configuration as the ` go ` tool does and you can specify which package to run.

I hope it's clear why this is needed now.
