### ISSUE TITLE
Linked version of Grammar-Kit in the contributing file is not compatible with IDEA 15

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2028]
Hi,

I'm trying to use the version provided in the contributing file but I bump into an error (I can paste it if needed). I suspect that it's because it is not compatible with IDEA 15 yet.
I'm trying to use it ot add a new method called get name on a `GoCallExpr` type so that it provides the name of the expression being called (maybe I do it the wrong way). I need it for the PR at https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1392.

Thank you.

**Comment by ignatov** [comment]
Please provide an error

**Comment by dlsniper** [comment]
The error is:
`java.lang.ClassNotFoundException: org.intellij.grammar.diagram.BnfDiagramProvider PluginClassLoader[org.jetbrains.idea.grammar, 1.2.1]`

The full error is here: https://ea.jetbrains.com/browser/ea_reports/992425
