### ISSUE TITLE
Inspection for defining methods on non-local types

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2031]
Incorrect version:
```go
package main

func (s *string) Hello() { // cannot define new methods on non-local type string

}
```

QuickFix version:

```go
package main

type myString *string

func (s myString) Hello() {

}
```

**Comment by sjamesr** [comment]
How does one define a "local" type?

**Comment by dlsniper** [comment]
A "local" type has to be defined in the current package.

For example:
```go
package main

import . "go/ast"

func (d Comment) Demo() { // cannot define new methods on non-local type ast.Comment

}

func main() {

}
```

won't compile as well because the type is not defined in the current package.

I've amended the description with the solution for the quick fix, which basically extracts the type and generates a new type out of it and replaces it with the current type of the receiver.

**Comment by sjamesr** [comment]
The definition of "current package" seems to be a bit hazy to me too, with the language spec saying

> A set of files sharing the same PackageName form the implementation of a package. An implementation *may* require that all source files for a package inhabit the same directory.

(emphasis mine)

I believe that the golang.org Go implementation does require files in the same package to be in the same directory, we could add an inspection to check for this.

**Comment by dlsniper** [comment]
> The definition of "current package" seems to be a bit hazy to me too

Yeap, I should have been more clear, current package meant the package which defines the method on the type.

So for example, if there's a type called `Demo` defined in `github.com/dlsniper/pak1` then all the methods have to be defined in the `pak1` package. Defining methods in other packages for `Demo` won't work.

As for:
> I believe that the golang.org Go implementation does require files in the same package to be in the same directory, we could add an inspection to check for this.

Yes, that's correct, the current Go implementations (golang.org and gccgo) require follow the same path of requiring the all sources for a package to be present in the same directory but that's a different issue lets say, not related to the current issue (and I think the plugin already covers this).
