### ISSUE TITLE
Highlight break statements 

### ISSUE THREAD

**Issue by m0sth8** [go-lang-plugin-org/go-lang-idea-plugin#2033]
In such scenarios:
```go
	for i = 0; i < n; i++ {
		for j = 0; j < m; j++ {
			switch a[i][j] {
			case nil:
				state = Error
				break
			case item:
				state = Found
				break
			}
		}
	}
```
somebody (newbie) might think that a "break" statement terminates execution of "FOR" statement. 
It will be great if we highlight somehow what block is terminated by BREAK statement.

According to spec https://golang.org/ref/spec#Break_statements `A "break" statement terminates execution of the innermost "for", "switch", or "select" statement within the same function.`
But break also might have a LABEL, so in this case we can highlight this LABEL.

**Comment by ilinum** [comment]
How do you think that should be highlighted?

Should we highlight `switch` keyword when cursor is on `break`? (and vice versa)
Do you think this will be enough?

**Comment by zolotov** [comment]
> Should we highlight switch keyword when cursor is on break? (and vice versa)
> Do you think this will be enough?

I imagine it in exactly that way.

**Comment by ilinum** [comment]
I'll implement this sometime soon (this week)
