### ISSUE TITLE
Scope of main package should be per file

### ISSUE THREAD

**Issue by mfinger** [go-lang-plugin-org/go-lang-idea-plugin#2034]
Firstly, love the plugin and use it all day long.  Great work.

But, I'm finding that the plugin is not handling the file level scoping of package main like go itself does.  It appears to be handling the main package like other packages which can cross many files.

Example x.go:
```
package main

import "fmt"

func f(s string) {
    fmt.Printf("%s\n", s);
}

func main() {
    f("from x.go");
}
```

Example from y.go:
```
package main

func main() {
    f("From y.go");
}
```

Here is how go reacts trying to build y.go:
```
% go build y.go
# command-line-arguments
./y.go:4: undefined: f
```

The UI is not showing f() (from y.go) as undefined. Also, when I "Goto Declaration" from f() in y.go it takes me to the declaration in x.go.

The scope of package main is special and is limited to the current file.

**Comment by sjamesr** [comment]
If you replace your build command with `go build .` I think you will find that it compiles fine.

**Comment by mfinger** [comment]
Well, it doesn't, but for a different reason.

But does at least prove I was wrong on the scoping of the main package.  :-)

```
% go build .
# _/home/mfinger/go
./y.go:3: main redeclared in this block
	previous declaration at ./x.go:9
```

Thanks for the info!

**Comment by dlsniper** [comment]
At the moment the plugin treats the main package as any other package because that's one way to use the main package (there are many issues about the plugin not knowing how to compile multiple files in main). 

And to be honest this would be hard to solve as sometimes there can be a mix of files in the same dir. @zolotov what do you think?

**Comment by sjamesr** [comment]
@dlsniper the main package should be treated as any other package (at least as far as this issue is concerned). We should close this issue :)

**Comment by zolotov** [comment]
+1 to @sjamesr 

`main` package is just a simple package, nothing special with it.

If you have a function that defined in file `a.go` and you use it in file `b.go` then obviously you'll get a error while compiling only `b.go` file. It has nothing to do with package naming and it has nothing to do with the plugin. Symbol resolution scope is package-scope. Compilation unit in golang is package. We won't change this in plugin. Building command is on user.

**Comment by zolotov** [comment]
> there are many issues about the plugin not knowing how to compile multiple files in main

For example?

**Comment by dlsniper** [comment]
I meant github issues, like this one
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/555 :)

**Comment by zolotov** [comment]
#555 is just about setting up run configuration and has nothing to do with name of package and is not related to this issue.

**Comment by mfinger** [comment]
Yes, I apologize.  It was the way I was building, sorry for opening an issue that was not an issue.
