### ISSUE TITLE
Running Tests with coverage and "Go tool arguments:" '-race'  gives erroneous race conditions

### ISSUE THREAD

**Issue by SonOfBytes** [go-lang-plugin-org/go-lang-idea-plugin#2037]
Coverage uses inserted global variable in the code to track coverage.  When this is combined with the race checks it can lead to erroneous and very confusing race conditions.

The following site presents some simple code when run with the "-race" flag added and in coverage mode will give the false erroneous race conditions.

http://herman.asia/running-the-go-race-detector-with-cover

Package:
```go
package coverrace

func add100() int {
    total := 0
    c := make(chan int, 1)
    for i := 0; i < 100; i++ {
        go func(chan int) {
            c <- 1
        }(c)
    }
    for u := 0; u < 100; u++ {
        total += <-c
    }
    return total
}
```

Test:
```go
package coverrace

import "testing"

func TestCoverRace(t *testing.T) {
    got := add100()
    if got != 100 {
        t.Errorf("got %d, want %d", got, 100)
    }
}
```

Reproducing command generated by PyCharm:
```sh
go test -v -race ./... -coverprofile=/someUserDir/coverrace$All_in__coverrace_.coverage -covermode=count
```

This has been fixed in go > 1.3+ by adding support for the '-covermode=atomic' flag.  This ensures that the access to the coverage global variable is protected by the sync package to avoid race detection.

**Comment by dlsniper** [comment]
@zolotov I'm thinking maybe adding a checkbox to enable the `-race` flag as it's a bit more special? This could appear in all runners. What do you think?

**Comment by zolotov** [comment]
> I'm thinking maybe adding a checkbox to enable the -race flag as it's a bit more special? This could appear in all runners. What do you think?

I don't see any sense in this. As @SonOfBytes mentioned it's simpler to set covermode=atomic, it's the same as count

**Comment by zolotov** [comment]
Thanks @SonOfBytes, will add atomic mode.

**Comment by SonOfBytes** [comment]
Thanks @zolotov et al. for a great plugin and upcoming atomic mode :smiley:
