### ISSUE TITLE
Show recursive call icon on the gutter

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2043]
Hi,I've noticed a really neat feature in Java which shows an icon on the gutter when a function call is recursive and I think it could make a nice addition to the plugin.

**Comment by ignatov** [comment]
Please check out https://github.com/ignatov/intellij-erlang/blob/master/src/org/intellij/erlang/marker/ErlangRecursiveCallLineMarkerProvider.java
