### ISSUE TITLE
After plugin update, run configuration doesn't launch my go project

### ISSUE THREAD

**Issue by ystreibel** [go-lang-plugin-org/go-lang-idea-plugin#2044]
This is my error :
```
Error running agent: Cannot run program "/Users/ykaribou/Library/Application Support/IdeaIC15/Go/lib/dlv/mac/dlv" (in directory "/Users/ykaribou/Projects/SC/SC_Client"): error=2, No such file or directory
```
What can I do ?

**Comment by ystreibel** [comment]
My workaround for this issue is to :

```
unzip /Users/ykaribou/Library/Application\ Support/IdeaIC15/Go/lib/delve-0.10.75.zip
```

**Comment by dlsniper** [comment]
Hi, which plugin version did you updated from and to?

@ignatov by the looks of it there might something wrong with the bundled delve version but I can't test as I don't have a Mac.

**Comment by zolotov** [comment]
Oops, sorry, will fix this soon

**Comment by zolotov** [comment]
Uploaded new nightly and alpha versions

**Comment by ystreibel** [comment]
Thanks for your reactivity. It's works fine !
