### ISSUE TITLE
It can not build with IntelliJ IDEA IU-141.1532.4

### ISSUE THREAD

**Issue by Hyzhou** [go-lang-plugin-org/go-lang-idea-plugin#2047]
Sample:
@ignatov add this code in DlvCommandProcessor
```
import org.jetbrains.rpc.CommandProcessorKt;
```
But IntelliJ IDEA IU-141.1532.4 do not have this class.

The README says, the project can build with IntelliJ IDEA IU-141.1532

**Comment by dlsniper** [comment]
Hi,


There are two ways to build the plugin:

- for IDEA 14, from branch 141
- for IDEA 15, from branch master


I'll update the doca to reflect that.
