### ISSUE TITLE
Show type for variables in ctrl+mouse-over pop-up

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2052]
I've picked this one up from StackOverflow, http://stackoverflow.com/questions/33979270/can-the-golang-plugin-for-intellij-give-better-type-information

On ctrl+mouse-over pop-up the plugin should also display the type of the variable, not just the name and file.

**Comment by zolotov** [comment]
related to #1676 and #1682
