### ISSUE TITLE
Nitpick: rename "Build Flags" to "Build Tags" in settings UI

### ISSUE THREAD

**Issue by mmindenhall** [go-lang-plugin-org/go-lang-idea-plugin#2055]
The godoc for the build package states:

> A build constraint, also known as a build tag, is a line comment...

It would be nice for the terminology in the settings UI to be consistent:

1. Rename "Build Flags" settings section to "Build Tags"
1. Rename "Custom flags" within those settings to "Custom tags"

**Comment by dlsniper** [comment]
Hi, thanks for reporting. 

I guess this is simple enough to be picked up as a contribution for those who'd like to start working on the plugin so I'll leave it like this for a little while.

**Comment by dlsniper** [comment]
@zolotov why did you removed the `up for grabs` label? This looks simple enough to be done by potential contributors.
