### ISSUE TITLE
Debugger during tests?

### ISSUE THREAD

**Issue by pkieltyka** [go-lang-plugin-org/go-lang-idea-plugin#2059]
Can you please give me an ETA as to when I can use the debugger while building/running tests? I am very surprised this plugin is developing so quickly and well (very high quality), but this is still left undone as it feels like low hanging fruit and so many of us will run/develop our programs via tests.

**Comment by zolotov** [comment]
No, I can't provide any ETA, sorry.

Duplicates #1855

**Comment by dlsniper** [comment]
Contributions are welcomed as well :)
