### ISSUE TITLE
Support debugging in the context of using godep

### ISSUE THREAD

**Issue by keviny22** [go-lang-plugin-org/go-lang-idea-plugin#2063]
It would be great if I could debug my program through the IDE but execute it in the context of godep. I think this would be similar to running Ruby projects with the Bundler checkbox, checked

```
godep go build ....
godep go run ....
```

REF: https://intellij-support.jetbrains.com/hc/requests/82625

**Comment by dlsniper** [comment]
`godep go run` simply prepends the `Godeps/_workspace` folder to the GOPATH of the project.

To achieve the similar functionality, add the `<project-dir>/Godeps/_workspace` folder to the Go libraries for the project and hit the Debug/run button button.

See the screenshot below: 
![snapshot155](https://cloud.githubusercontent.com/assets/607868/11599483/7207c612-9ac7-11e5-9117-d4cfb21ffd7a.png)

In that case I have the following setup:
- project root: `/home/florin/golang/src/github.com/dlsniper/u/demo/multi`
- Go project libraries: `/home/florin/golang/src/github.com/dlsniper/u/demo/multi/Godeps/_workspace`

The run configuration looks like this:
![snapshot156](https://cloud.githubusercontent.com/assets/607868/11599519/9f417646-9ac7-11e5-9b1c-43da580fc83c.png)

As such I'll close this as won't fix.

**Comment by alexwforsythe** [comment]
As a related question, how do you include the system `GOPATH` alongside the project's `Godep/_workspace` while still resolving the project's one first? I've tried the following:
* Global libraries: `[GOPATH] /Users/alexf/gocode`
* Project libraries: `/Users/alexf/gocode/src/myproject/Godeps/_workspace`

With this setup, though, running the `Go Test` run configuration still resolves dependencies in my system `GOPATH` first. That's not the same behavior I see when using `godep go test ...`. This becomes a problem when I clone one of my project's dependencies to my system `GOPATH` to work on, but check out a different version than the one in `Godeps/_workspace`.

**Comment by dlsniper** [comment]
Hi @alexwforsythe, would you mind opening a new issue and also attach a screenshot of the run window? That would help out understanding the issue. Thank you!
