### ISSUE TITLE
Unresolved struct fields when a function type alias returns a struct slice

### ISSUE THREAD

**Issue by jawher** [go-lang-plugin-org/go-lang-idea-plugin#2069]
*Plugin version: `0.10.774`*

The following code snippet demonstrates the problem:

To trigger the bug:

1. Define a type aliasing a function returning a slice of structs.
2. Create a variable with that type.
3. Call the function stored in that variable
4. The fields of the structs in the returned slice are not resolved.

In the following example, `s.Value` is marked as error, whereas it compiles just fine with the go compiler.

```go
package bug

type AStruct struct {
	Value string
}

type AFunc func() []AStruct

func Bug() {
	var f AFunc

	structs := f()
	for idx, s := range structs {
		_ = structs[idx].Value
		_ = s.Value
	}
}
```

[edit]
Might be related to #2057

**Comment by dlsniper** [comment]
Hi, thanks for the detailed bug report, I'm able to confirm this. I've also updated it a bit to contain the other way to access the slice. I don't know if it's related to #2057.

**Comment by jawher** [comment]
Thanks @dlsniper for the fast reply !

I'm looking at the source code of the plugin right now, and though my head almost exploded due to my lack of knowledge of all things PSI related, I managed to add a test to reproduce the issue with this code snippet:

`testData/psi/resolve/composite/TypeStructSliceFromFuncType.go`:

```go
package main

type S struct {
    /*def*/a int
}

type F func() []S

var f F

var x = f()[0]./*ref*/a
```

And also adding the `GoLegacyResolveCompositeTest#testTypeStructSliceFromFuncType` method.

I gave up on debugging the issue though, sorry :stuck_out_tongue_winking_eye: !

**Comment by sjamesr** [comment]
The problem is that calling `getType` on the `GoExpression` representing `f()` returns `F`, whereas it probably should return `[]S`. Should `getType` always return the "most base type" in the case of type reference expressions? I don't know enough about type handling in the plugin to know the answer.

**Comment by dlsniper** [comment]
I think we should have something to return the intermediate type, such as `F` instead of `[]S`, like the current `getType` does, as it could be relevant depending on context. Maybe there should be a `getFinalType` (or `getBaseType`) which does "automatically" the resolve dance to the base type.
