### ISSUE TITLE
Mailing list or forum where we can ask questions

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2076]
Is there a mailing list or forum set up where we can ask questions about the plug and help to configure it correctly? We should probably not be using github issues for this purpose though I'm doing just that right now :-(

**Comment by dlsniper** [comment]
You can ask questions here, as that helps the plugin get better at getting documentation, improving usage experience and so on. Also, there's a Gitter room linked in the README:) https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin You can use that as well, but issues on github are fine imho :)

**Comment by dlsniper** [comment]
I'll close this issue for now, @zolotov / @ignatov please feel free to step in if you think I've missed anything.

@bits01 please feel free to ask any questions either via issues or in Gitter. Thanks.
