### ISSUE TITLE
cgo struct fields highlighted as syntax errors

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2078]
Example:

import "C"
var cs *C.S
cs.name   <--- name will be highlighted in red: Unresolved reference
(name is actually valid in that struct, the code compiles and runs fine from the command line)

I realize it's probably hard to be smart about cgo, but it could at least skip errors on data structures from the "C" package so that the screen doesn't light up all red.

**Comment by ignatov** [comment]
```go
package main

/*
#include <stdio.h>
#include <stdlib.h>

void myprint(char* s) {
    printf("%s", s);
}
*/
import "C"

import "unsafe"

func main() {
	Example()
}

var cs *C.S

func Example() {
	cs.name
	cs := C.CString("Hello from stdio\n")
	C.myprint(cs)
	C.free(unsafe.Pointer(cs))
}
```

**Comment by bits01** [comment]
Not sure whether this fix is in the nightly 0.10.837 -- how can I find out what a nightly build includes?
But, it still seems to have error issues with a simple example:

/*
typedef struct {
  int x;
  unsigned char y;
  char *name;
} S;
*/

cs := C.S{}
fmt.Println(cs.x)
fmt.Println(cs.y)
fmt.Println(cs.name)

Same for:
cs := &C.S{}
cs.x, cs.y, cs.name all show as errors.

**Comment by ignatov** [comment]
Thanks

**Comment by bits01** [comment]
Sorry to keep reopening this. I found another case where it doesn't work: when a C struct is returned from a C function call, e.g. with the C.S above:

cs := C.some_C_function_call()
cs.x, cs.y, cs.name references are red

**Comment by bits01** [comment]
And one more case, chained C structs, e.g.
var cs1 C.S1
cs1.s2.s3.x
where s2 and s3 are fields of other C struct types, e.g. C.S2, C.S3, ...

This is getting complicated it seems :-(

**Comment by ignatov** [comment]
@bits01 Fixed again, please provide a nice and short sample with chained structures which I can use as a test data.
