### ISSUE TITLE
Inspection: make([]string) is not marked as an error.

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#2088]
make([]string) - this is definitely wrong, since it is missing at least length. However, code inspection doesn't treat it as an error.

https://play.golang.org/p/ecFXUXieoY

```
prog.go:4: missing len argument to make([]string)
```

IntelliJ: 15.0.2
GoLang plugin: 0.10.797

**Comment by zolotov** [comment]
Works fine for me. Could you provide details?

**Comment by vburenin** [comment]
![image](https://cloud.githubusercontent.com/assets/4350891/11761052/af8fc14c-a067-11e5-92c1-21389ce46952.png)

Compiler error is: testutils/memdbservice.go:112: missing len argument to make([]string)

**Comment by dlsniper** [comment]
Hi,I've updated the description with a link to the playground. I've also tested it in the plugin and it indeed is not flagged as an error.
