### ISSUE TITLE
Consistent receive statement between types

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2101]
In the following example
```go
package main

func Dem() chan interface{} {
	return make(chan interface{})
}

func _() (c chan interface{}) {
	c = Dem()
	if _, ok := <-c; ok { // // this is NOT contained in a GoRecvStatement
		return
	}
	select {
	case _, ok := <-c: // this is contained in a GoRecvStatement
		_ = ok
		return c
	}
	return
}

func main() {}
```

I think both channel ops be contained in a GoRecvStatement to make it easier to operate on the tree. What do you think?

**Comment by ignatov** [comment]
Please read [the spec](https://golang.org/ref/spec#Select_statements) and try to understant why I desiced to close this as a "won't fix" status.

**Comment by dlsniper** [comment]
If I read this ` A case with a RecvStmt may assign the result of a RecvExpr to one or two variables, which may be declared using a short variable declaration ` correctly it says that a RecvStmt `may` be desclared as a short variable declaration. Which means it's not mandatory to be declared as such. But I understand why the current implementation does this like it.
