### ISSUE TITLE
Cannot get parameter info for type asserted function

### ISSUE THREAD

**Issue by gabrielf** [go-lang-plugin-org/go-lang-idea-plugin#2104]
IntelliJ 14.1.5, Go plugin 0.9.748, JRE 1.8.0_45

Here is some code where a function is generated and returned as `interface{}` from a function. The function is then type asserted to be of a certain type but it still isn't treated as if the assertion succeeds when it comes to get parameter info, error highlighting etc.

```go
import "testing"

type funcType func(intParam int)

func TestFunc(t *testing.T) {
	
	aFunc := generateFunc()
	
	if f, ok := aFunc.(funcType); ok {
		// Cannot get parameter info on this function even though it is a funcType
		f("this shows up as valid even though parameter type should be int")
		return
	}
}

func generateFunc() interface{} {
	return func (intParam int) { }
}
```

**Comment by dlsniper** [comment]
Thanks for the report and example.
The plugin currently doesn't have any type inference support so even if the function will be correctly showing the parameters for it, the plugin wouldn't make a difference between int and string params for example (this is a known issue).
