### ISSUE TITLE
not support vendor

### ISSUE THREAD

**Issue by freshcn** [go-lang-plugin-org/go-lang-idea-plugin#2105]
Golang 1.5+ support vendor.But go-lang-idea-plugin not support vendor. Do you have plan to support vendor?

**Comment by dlsniper** [comment]
Please see the discussion in
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820, this
issue is a duplicate of that. Thank you.

**Comment by ignatov** [comment]
Duplicates #1820
