### ISSUE TITLE
Breakpoints doesn't work when building Go Application using Package instead of File

### ISSUE THREAD

**Issue by JeanLebrument** [go-lang-plugin-org/go-lang-idea-plugin#2106]
I just installed IntelliJ v14 and the last version of the Go plugin and I created a simple test project named `test` to try the debugger.

![screen shot 2015-12-16 at 11 02 23](https://cloud.githubusercontent.com/assets/3106676/11838097/14cb95b0-a3e5-11e5-9a62-94a6d89b1178.png)

In the `main` package, I have two files: `main.go` and `lol.go`.
In the `mymodule` package I have one file: `toto.go`.

**main.go**

```golang
package main
import (
	"fmt"
	"github.com/vimies/test/mymodule"
)

func main() {
	fmt.Printf("BEGINNING\n")

	toto := 42

	mymodule.Mdr()

	Haha()

	fmt.Printf("HELLO %d\n", toto)
}
```

**lol.go**  
 
```golang
package main
import "fmt"

func Haha() {
	fmt.Printf("haha\n")
}
``` 

**toto.go** 

```
package mymodule
import "fmt"

func Mdr() {
	fmt.Printf("MDR\n")
}
``` 

Here is the build configuration: 

![screen shot 2015-12-16 at 11 10 43](https://cloud.githubusercontent.com/assets/3106676/11838199/b37da1b2-a3e5-11e5-9265-286110963b31.png)

I added a breakpoint on the line `fmt.Printf("HELLO %d\n", toto)` in the file `main.go`

When I run my project in `debug mode`, the project runs fine and all the `Printf` are displayed in the console, but my breakpoint is never triggered.

However I succeed to have working breakpoints by changing `Run kind` to `File` instead of `Package` in the `Run/Debug Configurations` panel. To do so, I removed the lol.go file and each function call related to be able to compile. With this configuration, my breakpoint has been triggered.

However I would need to be able to use breakpoints in a project with `Run kind` set on `Package`

Any suggestions?
Thanks!

**Comment by zolotov** [comment]
Please try to remove spaces from run configuration name (Build main.go and run -> MyConfiguration) and try again

**Comment by JeanLebrument** [comment]
Thanks for your reply.

I tried but that doesn't work neither.

**Comment by ignatov** [comment]
Please specify your plugin version.

**Comment by JeanLebrument** [comment]
Plugin version: 0.10.749
IntelliJ version: 15.0.2

**Comment by dlsniper** [comment]
I'm using 0.10.852 and for me this works, see below.

![snapshot172](https://cloud.githubusercontent.com/assets/607868/11858221/e5877fc8-a45f-11e5-8344-e6b9281ade13.png)

However, I have a different issue, delve won't terminate after the program stops. It stops at the breakpoint and I send the continue command then it just hangs there in memory with new launch tabs appearing. @ignatov I'll try to investigate this a bit more, which version of delve do we pack? The one from your fork or one from the official repo? Thank you

**Comment by ignatov** [comment]
@dlsniper I've updated delve to the latest version today

**Comment by dlsniper** [comment]
@ignatov thank you. in my case this seems to be an issue with delve. Here's my issue (linked for brevity / further reading) https://github.com/derekparker/delve/issues/262#issuecomment-165609308

**Comment by dlsniper** [comment]
@JeanLebrument would you mind if you'd run delve manually and see what happens if you follow the steps I've described there? The IDE packs it's own Delve, in my case it's under ```/home/florin/.IntelliJIdea15/config/plugins/Go/lib/dlv/linux/dlv``` but you should find it under a similar path on Mac (once you know where your IntelliJ config dir is). Thank you!

**Comment by ignatov** [comment]
https://devnet.jetbrains.com/docs/DOC-181 – IntelilJ config and system files layout

**Comment by dlsniper** [comment]
Any updates on this?

**Comment by dlsniper** [comment]
As there's no feedback on this I'll close it for now. Please feel free to reopen this if needed. Thank you.
