### ISSUE TITLE
Issue with channels of structure type

### ISSUE THREAD

**Issue by stanislav-bios-baranov** [go-lang-plugin-org/go-lang-idea-plugin#2112]
With the following snippet, Idea highlights `TestField` inside 'for' loop as unrecognized, while code is correct and compiles. (This example will not work, when run, but it is only to demonstrate issue) 

```go
package main

import "fmt"

type TestStruct struct {
	TestField string
}

func GetChan() <- chan TestStruct {
	return make(chan TestStruct)
}

func main() {
	testChan := GetChan()

	for data := range testChan {
		fmt.Println(data.TestField)
	}
}
```

![Idea](https://d1ro8r1rbfn3jf.cloudfront.net/ms_73136/4oWk44HjeTT0s2eMGngzXInAkAAxLM/4tree%2B-%2B%255BX__dev_4tree%255D%2B-%2BC__Users_bioss_000_.IntelliJIdea15_config_scratches_scratch_1%2B-%2BIntelliJ%2BIDEA%2B15.0.2%2B2015-12-18%2B17.15.46.png?Expires=1450538217&Signature=fSOLKSOW0UIY25a6HP1m-9uFjc6oSiPl3A2C2PUtgRXIY0yM~~o74Hno3dTpiT3bZZ-YR9a-lBMexbxR~CXMvJlz362vEMO2WzGpTszKa15at1qkXNjCA8RnI0BANtIwGmistqGOwgS2Y-yDjNkbzLESV9V1njgXvWV4oQAJf2Clkj7QsqZdtvJOmwKLhQAqBrJT4w2sv68F4RrGfiFLmFht6a8iMo8XheQbRDtqltnPhAyaPgQSEoMBhHHE6FQA4hbMoYZOEeMUSPkglTHD5iHQHmA~UBPco94E4p~R5e6mW64O0AMXs0N~sPVk7r5i4suTLQimJ6vuBFuEHAsL-A__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by dlsniper** [comment]
Hi, @ignatov where should I look for to fix issues such as this with the
rezolver? I might be able to fix 1-2 of them if they are simple enough.
Doing the assignment count PR helped me understand the system a bit better.
Thank you.

**Comment by ignatov** [comment]
Duplicates #2057, please try the latest nightly build tomorrow (in 2 hours, actually).
