### ISSUE TITLE
regression in type resolution

### ISSUE THREAD

**Issue by sjamesr** [go-lang-plugin-org/go-lang-idea-plugin#2116]
Hi there,

I noticed some of my code started showing up with errors after building the plugin from master. The code itself is fine:

```go
	fin, fill, err := startConvert(c, tt)
	if err != nil {
		return err
	}
	if err := fill.fromBool(src); err != nil {   // fromBool is not resolved
		return err
	}
```

startConvert's prototype is

```go
func startConvert(c convTarget, ttFrom *Type) (fin, fill convTarget, err error)
```

The CTRL-hover text over the `fill` variable indicates that IntelliJ thinks it is of type `error`, whereas it's actually of type `convTarget`. This behavior started after 98be659c9156adb5d2f6780f9ca602dfafe7b8a1.

@ignatov

**Comment by ignatov** [comment]
Thanks for reporting.
