### ISSUE TITLE
`import "testing"` causes incorrect redlines for test signature

### ISSUE THREAD

**Issue by jmhodges** [go-lang-plugin-org/go-lang-idea-plugin#2118]
In Intellij 15.0.2 and Go plugin 0.10.749, the code

    package main

    import "testing"

    func TestFoo(t *testing.T) {
    }

will have TestFoo redlined for "Wrong test signature". When selecting the auto-correct of "Fix signature", the "testing" package will be duplicated at the end of the import statements.

This occurs with both multiple (that is `import ( ... )`) and single import statements in the file.

Selecting the redline and deleting the extra import will cause the redline to go away until the file is closed and re-opened.

**Comment by dlsniper** [comment]
Hi, please try the latest nightly as I can see this is fixed. If that doesn't help, please try and make a short video of the issue as I can't replicate it. Thank you.

**Comment by dlsniper** [comment]
I'll close this as there was no feedback for a while and I can't replicate the issue in the latest nightly. Please reopen if needed. Thank you.

**Comment by jmhodges** [comment]
Just to close this loop:  the latest stable release did fix this. Thanks!
