### ISSUE TITLE
IDEA 16 EAP is not supported yet

### ISSUE THREAD

**Issue by NateLing** [go-lang-plugin-org/go-lang-idea-plugin#2123]
this plugin does not support IDEA EAP 16

**Comment by dlsniper** [comment]
Yup, that's correct. It's not updated yet. I'll keep this open to track the state for it.

**Comment by dlsniper** [comment]
@zolotov shouldn't this be closed now that the nightly channel supports 144.*? I know it might break later on but I guess the fixes will come as well.

**Comment by zolotov** [comment]
sure, let's close it
