### ISSUE TITLE
go run: no go files listed

### ISSUE THREAD

**Issue by Rabrg** [go-lang-plugin-org/go-lang-idea-plugin#2124]
When I try to run a program using Intellij IDEA's / the plugin's runner it fails printing
```
C:/Go\bin\go.exe run "C:/Users/Ryan Greene/IdeaProjects/the-golang/test.go"
go run: no go files listed

```
yet when I use the terminal with the exact same command it works fine
```
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Ryan Greene\IdeaProjects\the-golang>C:/Go\bin\go.exe run "C:/Users/Ryan Greene/IdeaProjects/the-golang/test.go"
Hello, world!
```

I'm using the latest versions of the plugin, Go, IntelliJ IDEA, and Java.

**Comment by dlsniper** [comment]
Hi,

What are the versions for Go and IntelliJ?
Also, how is your project setup? Where is the project root directory and what entries are in Settings -> Lanuages & Frameworks -> Go -> Go Libraries?
How does your run configuration looks like?

Thanks for sharing those details.

**Comment by Rabrg** [comment]
I'm using the latest versions of the plugin, Go, IntelliJ IDEA, and Java. The project root directory is "C:\Users\Ryan Greene\IdeaProjects\the-golang", and there are no entries in Go Libraries, but Use GOPATH is checked and my GOPATH points to "C:\Users\Ryan Greene\IdeaProjects".

The run configuration's file is "C:/Users/Ryan Greene/IdeaProjects/the-golang/test.go" and the working directory is "C:/Users/Ryan Greene/IdeaProjects/the-golang".

**Comment by dlsniper** [comment]
>there are no entries in Go Libraries 

From what I can understand, if there are no entries in the Go libraries it means that detecting the GOPATH from the system failed. Please add manually an entry that points to  "C:\Users\Ryan Greene\IdeaProjects". to the Global Libraries section of the Go Libraries. After that it should work.

> I'm using the latest versions of the plugin, Go, IntelliJ IDEA, and Java.

There are 3 different release channels + manual compiling of the plugin, that's why I'm asking for the version number as it helps narrowing down the problem. Same goes for IntelliJ IDEA. Please specify the versions you are running. If you need help identifying them, please let me know.

**Comment by Rabrg** [comment]
Didn't know you meant version numbers. IntellJ IDEA is 15.0.2 and the plugin is 0.10.749

I tried both "C:/Users/Ryan Greene/IdeaProjects" and "C:/Users/Ryan Greene/IdeaProjects/the-golang" as global libraries and the same thing happened.

**Comment by dlsniper** [comment]
If the GOPATH in your system is: `C:/Users/Ryan Greene/IdeaProjects`  then it should be enough to add that path to Global Libraries.

From what I understand, currently it's not a properly formed Go workspace as it's missing the `src` folder after `IdeaProjects`. The path to your project should be something like this: `C:/Users/Ryan Greene/IdeaProjects/src/some-project`. For more details see: https://golang.org/doc/code.html#Workspaces

As this is a Windows related issue, I'm not sure how to further help, @zolotov can you please take over this? Thanks.

**Comment by dlsniper** [comment]
Ah, maybe you can include some screenshots of the Go Libraries, Run configuration but not sure if that would help out. Thanks.

**Comment by Rabrg** [comment]
Just found out "Build test.go and run" is working, just not "go run test.go", so I'm fine now, but if you guys still want to look into it I'm cool with that.

**Comment by zolotov** [comment]
Still cannot recreate, closing the issue

**Comment by zolotov** [comment]
Recreated on old version, should work in nightly releases

**Comment by zolotov** [comment]
If not, please try to invoke Ctrl+Shift+Alt+/, then select Registry, find `run.processes.with.pty` property there and tell me what's the value of this property

**Comment by Rabrg** [comment]
Thankd!
