### ISSUE TITLE
False-positive for invalid type assertion inspection

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2139]
```go
package demo

type (
	int64Val int64
	boolVal  bool
	Value    interface {
		Demo()
	}
)

func _(x, y Value) {
	switch x := x.(type) {
	case boolVal:
		y := y.(boolVal)
		_, _ = x, y
	case int64Val:
		b := int64(y.(int64Val)) // this is seen as the check on boolVal not on int64Val
		_ = b
	}

}
```

**Comment by sjamesr** [comment]
Actually I think this is a bug in type resolution:

In the line `b := int64(y.(int64Val))`, calling `getGoType` on the expression `y` yields `boolVal`, whereas it should be `Value`.

@ignatov depending on how complicated this is to fix, we should consider disabling the invalid type assertion check until getType is fixed.

**Comment by sjamesr** [comment]
Looking further, resolving the reference `y` yields the var definition `y := y.(boolVal)`, not the parameter `y`. Since the var definition is in a separate case branch, it should not be considered.
