### ISSUE TITLE
Go.exe log output always being wrapped

### ISSUE THREAD

**Issue by markgoodhead** [go-lang-plugin-org/go-lang-idea-plugin#2141]
I'm not sure if this is the right place for this but anyway:

I'm using IDEA 15.0.2 and plugin 0.10.749 on Windows 7

Whenever I build/run a main.go file from IntelliJ the logs produced by the go.exe output (in red) in the Run tab are always wrapped to a much smaller character limit than the normal IntelliJ text (the bit in greyish white which says "C:/Go\bin\go.exe build -o etc etc". I've looked around and can't find anyway to change the wrapping settings of the Go output; when I run the program from a normal command terminal window I don't get any wrapping of the log text. 

How can I change this wrapping in the Go plugin/IntelliJ?

**Comment by dlsniper** [comment]
This looks like a duplicate of: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1784 I'll close this for now.
