### ISSUE TITLE
Paths screwed up without 'src' folder

### ISSUE THREAD

**Issue by karalabe** [go-lang-plugin-org/go-lang-idea-plugin#215]
Hi,

  If I leave out the 'src' folder and instead have my source files in the project root (and insert the root into the Sources list), the editor won't recognize the imports correctly.

Ex: If I have a folder structure like

ROOT
- crypto
  - hkdf

In a main file in the root I import crypto.hkdf - which succeeds - but when I reference anything inside it, the plugin just underlines as "Unresolved symbol". Even though when I compile the project everything's ok, and I can run it too.

Also, probably due to the same error, without the 'src' folder I cannot run any tests. The plugin just complains that no tests are found (which if put inside 'src' work).

Since the extra 'src' folder is going against the standard go package layout, please correct it.

Thanks,
  Peter

**Comment by naquden** [comment]
I had similar problem with not being able to find my local go files (e.g. "import atte/fileX").
My GOPATH was located at C:\go\  and for logical reason my project files which was located at C:\project\folder\anotherfolder\goproject\{main.go}.
If I copied all my goproject files to C:\go\src\atte\ then I could find my local files in IDE. But then they would be not synced with project files as they changed.
I solved this by creating a symbolic directory link in C:\go\src\ to C:\project\folder\anotherfolder\goproject
Reference: https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by fixbugsnow** [comment]
👍 thanks, naquden! your soln on "symlinks" resolved this **"hard rqmt for 'src' folder" issue** for me!! 'coz my inherited Github GO project did not have any such structure/standard for 'src' folder 
and I had to make quite a few urgent fixes

**my 'project-repo' had a 'vendor' subfolder of packages and also the code imported local (non-vendor) packages, like so:
github.repolocation.com/project-repo/pkg-name**

which is why I had to trick the GO compiler by having GOPATH and creating Symlinks, like so:

GOPATH=
%USERPROFILE%\go;
%USERPROFILE%\gomystuff\projroot;
%USERPROFILE%\gomystuff\projrootvendor;
%USERPROFILE%\gomystuff\projrootgithubrepolocation;

```
D:\repos\project-repo>mklink /D "C:\Users\me\gomystuff\projroot\src\project-repo-grp\project-repo" "D:\repos\project-repo"
symbolic link created for C:\Users\me\gomystuff\projroot\src\project-repo-grp\project-repo <<===>> D:\repos\project-repo

D:\repos\project-repo>mklink /D "C:\Users\me\gomystuff\projrootvendor\src" "D:\repos\project-repo\vendor"
symbolic link created for C:\Users\me\gomystuff\projrootvendor\src <<===>> D:\repos\project-repo\vendor

D:\repos\project-repo>mklink /D "C:\Users\me\gomystuff\projrootgithubrepolocation\src\github.repolocation.com\project-repo" "D:\repos\project-repo"
symbolic link created for C:\Users\me\gomystuff\projrootgithubrepolocation\src\github.repolocation.com\project-repo <<===>> D:\repos\project-repo
```

> I had similar problem with not being able to find my local go files (e.g. "import atte/fileX").
> My GOPATH was located at C:\go\ and for logical reason my project files which was located at C:\project\folder\anotherfolder\goproject{main.go}.
> If I copied all my goproject files to C:\go\src\atte\ then I could find my local files in IDE. But then they would be not synced with project files as they changed.
> I solved this by creating a symbolic directory link in C:\go\src\ to C:\project\folder\anotherfolder\goproject
> Reference: https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/
