### ISSUE TITLE
variable life time issue

### ISSUE THREAD

**Issue by dec1985** [go-lang-plugin-org/go-lang-idea-plugin#2172]
```
package main

import "fmt"

func main() {
    for i := 0; i < 3; i++ {
        fmt.Println(i)
    }

    for i := 100; i < 103; i++ {
        fmt.Println(i)
    }
    fmt.Println("done")
}
```
As in my codes, when it breaks at the second "fm.Println(i)", there are 2 variable named i in the debug console, and the watcher only use the prefix one, it should be expired. Is this a known issue? Will be fixed?

Screenshot goes here: http://grab.by/MYkc

**Comment by dec1985** [comment]
```
Because the lifetime of a variable is determined only by whether or not it is reachable, a local variable may outlive a single iteration of the enclosing loop. It may continue to exist even after its enclosing function has returned.
```
I've found something about like this, hmm, that means the previous "i" is still exist, but it's really hard to debug when I met this issue.

**Comment by dlsniper** [comment]
This duplicates https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2121 and it's not a problem of the plugin, it's a problem of Go itself not being able to generate the proper debug information for devle to use. Please subscribe to that issue or the upstream issues to see when this will be fixed. Thanks.
