### ISSUE TITLE
Inspection for unused numeric values

### ISSUE THREAD

**Issue by EtienneBruines** [go-lang-plugin-org/go-lang-idea-plugin#2176]
Using nightly build of the plugin: `0.10.951` , using IDEA Community Edition `15.0.2`. 

Consider the following code:
```go
s.indices[i+1] = uint16(j)
```

The `1` part, results in the inspection error: `Numeric value evaluated but not used`. This is non-sense. This bug did not exist a few days ago (in `0.10.935`). 

Also the case for the numbers `800` and `16`:
```go
if space.Position.X > (800 - 16) {
```

---------

But not for `400` and `16` in an assignment:
```go
space.Position.X = 400 - 16
```
And not for `0` when there's no math operator involved:
```go
if space.Position.Y < 0 {
```

**Comment by SchumacherFM** [comment]
Same for the following code where the `2` after the `%` retrieves the pop up: `Numeric value evaluated but not used.`:

```go
func NewByString(vl ...string) []string {
	if len(vl)%2 != 0 {
		panic("ErrImbalancedPairs")
	}
	vls := make([]string, len(vl)/2)
	j := 0
	for i := 0; i < len(vl); i = i + 2 {
		vls[j] = vl[i] + vl[i+1]
		j++
	}
	return vls
}
```

**Comment by dlsniper** [comment]
Thanks for the new test case, I'll submit a fix soon, I had some issues in
running a more comprehensive test suite so additional test cases are
welcomed.

**Comment by dlsniper** [comment]
I'll close this as it's not applicable anymore (all changes were reverted)
