### ISSUE TITLE
Channel returned by function incorrectly detected as channel value

### ISSUE THREAD

**Issue by davelondon** [go-lang-plugin-org/go-lang-idea-plugin#2177]
What version of Go plugin are you using?
0.10.749
What version of IDEA are you using?
Intellij 15.0.2, #IC-143.1184
What version of Java are you using?
JRE: 1.8.0_40-release-b105 x86_64
What did you do?
See test below
What did you expect to see?
s.String should not be highlighted as an error
What did you see instead?
s.String is red

```go
package chantest

import "testing"

type Struct struct {
	String string
}

func GetChan() chan Struct {
	c := make(chan Struct, 1)
	c <- Struct{"foo"}
	close(c)
	return c
}

func TestFoo(t *testing.T) {
	c := GetChan()
	for s := range c {
		if s.String != "foo" { // "String" is highlighted in red
			t.Fail()
		}
	}
}
```

It looks like the plugin has incorrectly detected the type of the return value of the function as "Struct" instead of "chan Struct":

<img width="527" alt="screenshot 2015-12-25 17 18 45" src="https://cloud.githubusercontent.com/assets/925351/12003928/cc43823c-ab2b-11e5-9f7a-a3b49efca6d2.png">

<img width="395" alt="screenshot 2015-12-25 17 20 59" src="https://cloud.githubusercontent.com/assets/925351/12003932/ef6ecd3e-ab2b-11e5-9a25-371abc863f41.png">

**Comment by ignatov** [comment]
Thanks for reporing

**Comment by ignatov** [comment]
Please try the latest build (since #935 for example), it should be fixed right now.

**Comment by davelondon** [comment]
Yup it works. Thanks Sergey. Have a good New Year!

**Comment by ignatov** [comment]
Thanks, happy New Year.
