### ISSUE TITLE
Directories marked as excluded are still considered

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#2181]
To use the vendor feature I thought I exclude directories in Intellij latest and place a copy of that package in my vendor folder hoping that the latest go plugin will pick it up ... but bummer didn't work.

It seems that excluded directories (right click -> Mark Directory as ...) still gets included. See the printscreen.

![screen shot 2015-12-27 at 8 10 20 am](https://cloud.githubusercontent.com/assets/372027/12009299/544e5782-ac72-11e5-9501-4e0b88a8ee3a.png)

The function `currency.AllCurrencies()` is my vendored version but not in the original package.

This issue might be a duplicate of #1820 if so close it please :-)

**Comment by SchumacherFM** [comment]
stale - maybe already fixed in Goland

**Comment by zolotov** [comment]
@SchumacherFM it is. you can easily check this by using the number of issue in our tracker: https://youtrack.jetbrains.com/issue/GO-2181
