### ISSUE TITLE
Rework the placeholder detection in the placeholder count detection

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2188]
As per comment https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2187#issuecomment-167661791 the placeholder detection should be simplified / improved so that we can can get more out of this:

- simplify the process
- get the pair of placeholder / value(s) (a value can be assigned to multiple placeholders due to placeholder supporting indexes)
- check if the placeholder type is valid for the formatting function

**Comment by dlsniper** [comment]
@zolotov what does ` // todo: implement ConstEvaluator ` from https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/inspections/GoPlaceholderCountInspection.java#L125 means? I want to actually get onto doing this but I'm not sure about this. Thank you.

**Comment by zolotov** [comment]
It means that this should be replaced by real expressions evaluator. Well you can try to implement it if you want, see https://github.com/golang/go/tree/master/src/go/constant

**Comment by dlsniper** [comment]
@zolotov Quick question, I'm working on reimplementing this as discussed in the last PR but I'm faced with an issue.

How do I check if the parameter used in a function call is an unpacked variadic one or not? To give a concrete example: https://play.golang.org/p/lfUmFw9uBN

```go
package main

import (
	"fmt"
)

func demo(args ...interface{}) {
	fmt.Printf("%s %s %s", args...)
}

func main() {
	params := []interface{}{"a", "b", "c"}
	demo(params...) // How do I check that this is unpacked here or not?
}
```

The PSI tree (see below) doesn't look like this is captured into the type itself but I might be horribly wrong.

![snapshot60](https://cloud.githubusercontent.com/assets/607868/15634726/ed5ff484-25c2-11e6-9cdb-65ee95103504.png)

I'm in the middle of the code right now so I can't check yet what happens in this case and how the plugin will "see" that parameter type but I would gladly accept any help.

Thank you!

**Comment by zolotov** [comment]
\cc @ignatov

**Comment by ignatov** [comment]
You can check that com.goide.GoTypes#TRIPLE_DOT is next to the desired argument.
Or better – use com.goide.psi.GoArgumentList#getTripleDot.

**Comment by dlsniper** [comment]
I think I can use the `getTripleDot` method, for now at least, thank you!
