### ISSUE TITLE
cannot detect   placeholder  %+v 

### ISSUE THREAD

**Issue by chenwei767** [go-lang-plugin-org/go-lang-idea-plugin#2194]
###### for example,  the typing following code will get inspections warning

log.Printf("a: %+v",a) ` Got 0 placeholder(s) for 1 arguments(s)`
fmt.Printf("a: %+v",a) ` Got 0 placeholder(s) for 1 arguments(s)`

**Comment by ignatov** [comment]
Please provide a description.

**Comment by dlsniper** [comment]
The fix for this is simply but I'll take the opportunity to redo the support for placeholder detection and hopefully remove the regex we use now.

**Comment by zolotov** [comment]
one more example:

```
fmt.Printf("eq (as-is): %.3f%% score: %v offset: %v descr: [%v]\n", eq, score, offset, descr)
```

**Comment by dlsniper** [comment]
@zolotov is there a way to also highlight the parameters when either the parameter or the placeholder is under the cursor?

**Comment by zolotov** [comment]
@dlsniper you can use `HighlightUsagesHandlerBase` (return and break highlighting are implemented with it). For adding part of psi element you should add ranges directly to myReadUsages, like in https://github.com/JetBrains/intellij-community/blob/master/plugins/groovy/src/org/jetbrains/plugins/groovy/findUsages/GrHighlightExitPointHandler.java
