### ISSUE TITLE
False positive annotation: Non-integer size argument to make

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#2196]
```go
var (
	bgwork = make(chan func(), 1e5)
)
```

**Comment by uvwild** [comment]
still happeing in 2018.1 EAP in an example file:
https://github.com/manuelkiessling/go-cleanarchitecture/blob/96a022b6127638236963ed8f00acc499300a7b70/src/usecases/usecases.go

i disabled all inspections... its still there.... very frustrating....
when I cannot disable false positives the inspections become a bit useless....

**Comment by dlsniper** [comment]
@uvwild I don't understand how this comment is related to the issue here. Furthermore, if you have any issues with GoLand, please open the issue here: https://youtrack.jetbrains.com/issues/Go Thank you
