### ISSUE TITLE
Test* functions from other packages appear in autocomplete list

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#2198]
Happy new year! 🎉

![screen shot 2016-01-02 at 11 15 18 am](https://cloud.githubusercontent.com/assets/372027/12074115/e8202754-b142-11e5-9950-93526605c4da.png)

When writing tests in my package the autocompleter shows the tests from the assert (  "github.com/stretchr/testify/assert") package (from those _test.go files) which are totally useless in the autocompletion dialog in my test files/package.

I use latest Intellij with Go Plugin latest github commit from master branch.

Thanks for fixing :-)

**Comment by zolotov** [comment]
Thanks! Will be fixed in the next nightly

**Comment by SchumacherFM** [comment]
Thanks!
