### ISSUE TITLE
Unable to insert breakpoints

### ISSUE THREAD

**Issue by PatrickLaban** [go-lang-plugin-org/go-lang-idea-plugin#2199]
Plugin Version - 0.10.978
IDEA - PyCharm 5.0.3 Professional
JAVA - 1.7.0_91, OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1), OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
Simply put, I am unable to set a breakpoint anymore within PyCharm in .go files.  .py files work fine.

**Comment by ignatov** [comment]
Please attach your logs '''Help > Show logs in...''' and share a bit more information. Do you use symlinks in your project or not?

**Comment by PatrickLaban** [comment]
The most recent log file is attached, everything else is to old.  Apologies my java version is actually 1.8.0_66 running on windows 10.  Forgot to change that info up.

[ideasave.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/76512/ideasave.txt)

**Comment by dlsniper** [comment]
@PatrickLaban do you use Windows or Ubuntu? From the logs I see Windows which means this is a known issue as Delve doesn't support Windows yet. Please see: https://github.com/derekparker/delve/pull/276 and track this issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922

**Comment by ignatov** [comment]
Duplicates #1922
