### ISSUE TITLE
How to build this plugin from sources on windows?

### ISSUE THREAD

**Issue by mistbow-git** [go-lang-plugin-org/go-lang-idea-plugin#2200]
What I need to setup before build?

**Comment by dlsniper** [comment]
To compile the plugin on Windows, please follow the instructions in the [contributing file](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md) [Configuring and debugging in IntelliJ](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md#configuring-and-debugging-in-intellij)

If you have any issues, please ping here or on the [Gitter room](https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin).

**Comment by dlsniper** [comment]
I've forgot to mention, to get the installable plugin, run the `Build plugin` run configuration and the plugin artifact should be under `build/distributions/Go-0.10.SNAPSHOT.zip` Then you have to install the zip file.

**Comment by mistbow-git** [comment]
I think something wrong in my settings for Java...
```
21:36:23: Executing external task 'buildPlugin'...
The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.2\jre,daemonRegistryDir=C:\Users\Andy\.gradle\daemon,pid=10776,idleTimeout=null,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1251,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=a1132919-ddf4-452f-a7fa-9e13f9f22285,javaHome=C:\Program Files (x86)\Java\jre1.8.0_66,daemonRegistryDir=C:\Users\Andy\.gradle\daemon,pid=15640,idleTimeout=10800000,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1251,-Duser.country=US,-Duser.language=en,-Duser.variant]

21:36:32: External task execution finished 'buildPlugin'.
```

**Comment by zolotov** [comment]
@mistbow-git I believe it's misconfiguration of gradle or jdk on your machine, I've never seen this before. You try to google a solution, e.g. https://discuss.gradle.org/t/gradle-daemon-different-context/2146 or http://stackoverflow.com/questions/30642954/gradle-in-android-studio-giving-error-project-sync-failed

**Comment by mistbow-git** [comment]
@zolotov Thanks! It's my mistake! I did not watched to event log. (
and I do not set up a gradle project...
Now I see that plugin was build successfully, but has some errors:
```
21:47:06: Executing external task 'buildPlugin'...
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :utils.
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :google-app-engine.
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :google-app-engine-yaml.
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :plan9.
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:google-app-engine:compileJava
:google-app-engine:processResources
:google-app-engine:classes
:google-app-engine:jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:plan9:compileJava
:plan9:processResources
:plan9:classes
:plan9:jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:utils:compileJava
:utils:processResources UP-TO-DATE
:utils:classes
:utils:jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:google-app-engine:google-app-engine-yaml:compileJava
:google-app-engine:google-app-engine-yaml:processResources UP-TO-DATE
:google-app-engine:google-app-engine-yaml:classes
:google-app-engine:google-app-engine-yaml:jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:compileJava
:processResources
:classes
[Fatal Error] updates.xml:1:1: Premature end of file.
:prepareSandbox
:buildPlugin

BUILD SUCCESSFUL

Total time: 31.012 secs
21:47:37: External task execution finished 'buildPlugin'.
```
Is this critical?

**Comment by zolotov** [comment]
It's not critical and I think that it won't appear on the next build. It's actually issue of https://github.com/JetBrains/gradle-intellij-plugin/ but I'll take a look. Thanks.

**Comment by mistbow-git** [comment]
But now I want to setup a dalve debugger.
```
@dprime You should create a small patch and build the plugin from sources.
E.g. com.goide.dlv.DlvDebugProcess#IS_DLV_DISABLED = SystemInfo.is32Bit;
and setup a desired customDlvPath in gradle.properties.
```
In the com.goide.dlv.DlvDebugProcess file i see:
public static final boolean IS_DLV_DISABLED = SystemInfo.isWindows || SystemInfo.is32Bit;
What I shall to do? Comment this line?

And how to setup customDlvPath? like this: "d:\Go\bin"?

**Comment by zolotov** [comment]
> public static final boolean IS_DLV_DISABLED = SystemInfo.isWindows || SystemInfo.is32Bit;
> What I shall to do? Comment this line?

According to the text you quoted you should replace this with `public static final boolean IS_DLV_DISABLED = SystemInfo.is32Bit`

> And how to setup customDlvPath? like this: "d:\Go\bin"?

You can set `-Dorg.gradle.project.customDlvPath=d:\Go\bin\dlv` in run configuration or set customDlvPath property in `gradle.properties` file

**Comment by dlsniper** [comment]
Convert the statement `IS_DLV_DISABLED` to:

```java
public static final boolean IS_DLV_DISABLED = SystemInfo.is32Bit;
```

build the plugin and then launch IDEA with: `-Dorg.gradle.project.customDlvPath=/path/to/dlv.exe`

**Comment by mistbow-git** [comment]
I changed files and had installed plugin from file, but debugger is disabled yet. ((
```
public static final boolean IS_DLV_DISABLED = SystemInfo.is32Bit;
customDlvPath = d:/Go/bin/dlv.exe
```

**Comment by zolotov** [comment]
> customDlvPath = d:/Go/bin/dlv.exe

It works on debug IDEA only, apparently program arguments doesn't work after installation, you should pass them to your actual IDEA installation.

**Comment by zolotov** [comment]
However it shouldn't be disabled anyway. Are you sure you have 64bit system?

**Comment by mistbow-git** [comment]
I have 64 bit windows system, but jre in the help/about is x86...
![image](https://cloud.githubusercontent.com/assets/3740898/12080504/39b1000e-b26d-11e5-9124-2169c7879d57.png)

**Comment by zolotov** [comment]
Hm, try to set `IS_DLV_DISABLED = false;` and see what's happened

**Comment by mistbow-git** [comment]
Thanks! Now it's working! )))

**Comment by mistbow-git** [comment]
But has errors:
```
23:05:15 Error running inframe: Cannot run program "C:\Users\Andy\.IntelliJIdea15\config\plugins\Go\lib\dlv\linux\dlv" (in directory "D:\Go\src\inframe"): CreateProcess error=193, %1 is not a valid Win32 application
23:05:15 go build: Interrupted
```

**Comment by zolotov** [comment]
Of corse it can't run program `"C:\Users\Andy\.IntelliJIdea15\config\plugins\Go\lib\dlv\linux\dlv"` it's linux distribution :) What's the question?

**Comment by mistbow-git** [comment]
Ok. I delete inframe linux file in the root folder.
And how i can debug my app now?

**Comment by zolotov** [comment]
> Ok. I delete inframe linux file in the root folder.

I didn't understand what does it mean.

> And how can I debug my app now?

Bundled delve doesn't support windows debugging. If you have one that can do it replace dlv binary in plugin distribution or substitute `customDlvPath` property as I said before

**Comment by mistbow-git** [comment]
I understood you now!
I was builded windows dlv.exe
And I setup customDlvPath = d:/Go/bin/dlv.exe
How can I use this file? Whats wrong?

**Comment by zolotov** [comment]
> And I setup customDlvPath = d:/Go/bin/dlv.exe

`gradle.properties` is used only for debugging plugin, it doesn't work after installation. In order to set `customDlvPath` in production you should patch IDEA system properties `https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties`

**Comment by dlsniper** [comment]
@zolotov / @mistbow-git the correct system property is `dlv.path` not `org.gradle.project.customDlvPath` as in the above / readme. That one is used only when using the plugin in the debug IDEA.

@mistbow-git to set this you need to set the system property called: `dlv.path` in IDEA as described by @zolotov above.

**Comment by mistbow-git** [comment]
I do not see dlv.path in this files in C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.2\bin:
idea.exe.vmoptions
idea.properties
idea64.exe.vmoptions

**Comment by dlsniper** [comment]
> I do not see dlv.path in this files

You have to add it manually as a new entry there.

**Comment by mistbow-git** [comment]
Thanks! It worked! )))

**Comment by dlsniper** [comment]
Please note that delve had a lot of changes (75 commits difference between the master of the original and fork) so it might be that things will not work as expected or work at all in the plugin. As such, before reporting issues here, if something doesn't work in the IDE, please test first in delve using the same steps then report it to the delve PR for Windows if you can replicate it.

**Comment by mistbow-git** [comment]
Yes I seen that!
Why they was not merged with master yet?

**Comment by dlsniper** [comment]
> Why they was not merged with master yet?

Probably because it's not ready to be merged yet. You can follow the discussion with the author of the PR there. Your guess is as good as mine.

**Comment by mistbow-git** [comment]
Maybe we can help @lukehoban to do this together?

**Comment by zolotov** [comment]
@dlsniper you're right about `dlv.path`, thank you. @mistbow-git, sorry for misinformation

**Comment by mistbow-git** [comment]
@zolotov no problem)) thanks a lot!

**Comment by dlsniper** [comment]
@mistbow-git personally I don't have the time, nor the experience required, for working on delve even if I would want to. I barely find the time to work on the plugin as it is. You, and anyone else interested, can certainly help Delve get this merged.

**Comment by mistbow-git** [comment]
@dlsniper Ok! I think that very many people wait for this option!

**Comment by mistbow-git** [comment]
I merged all changes from @derekparker/master and rebuild delve. Still working good. ))
Thanks for all!
