### ISSUE TITLE
Anonymous fields of extended types show warning on initialization

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#2205]
Extended types get warning for anonymous field initialization.

Example:
```go
package mug

import "items"

const TYPE = "MUG"

type Mug struct {
	items.Item
}

func (v Mug) GetTotalPrice() int {
	return v.Price * v.Count
}

func New() *Mug {
	v := &Mug{
		items.Item{     // Marked as "Unnamed field initialization"
			ID: TYPE,   // though it is ok
			Price: 750, // as it cannot be named
		},
	}
	return v
}
```
IDE: IDEA 143.1653
Plugin: 0.10.978

**Comment by dlsniper** [comment]
Theoretically the fix for it would be:
```go
func New() *Mug {
	v := &Mug{
		Item: items.Item{ // Marked as "Unnamed field initialization"
			ID:    TYPE, // though it is ok
			Price: 750,  // as it cannot be named
		},
	}
	return v
}
```

But the question is: shouldn't be better to explicitly do this initialization rather than let it pass for embedded structs?

I'm looking for some input on this as I'm obviously leaning towards the explicit initialization rather than the anonymous one but on the other hand, as the error type suggests, it's a weak warning not a warning.

**Comment by dmitry-vovk** [comment]
Well, you are right. though it adds more verbosity in the code.

Guess, the issue can be closed.

**Comment by dlsniper** [comment]
I'd rather not close it if it doesn't follow the consensus in the community. Maybe a quick fix action to fix it could be useful but it would still add to the code verbosity you mention.

**Comment by mrcook** [comment]
My (strong) preference would be to allow anonymous fields. There are also several examples in the "Effective Go" documentation that use anonymous fields:

https://golang.org/doc/effective_go.html#data
https://golang.org/doc/effective_go.html#embedding

Maybe this is one of those situations in which it would be better to allow for now, and wait to see if the language developers and/or community make a stronger indication in the future?

**Comment by dlsniper** [comment]
This has been solved and it's now allowing for the local type to be inspected or not.
Further more, best practices dictate that the code should using the key names explicitly.
While the inspection is enabled by default, it's a weak warning now and I think we can close this safely.
