### ISSUE TITLE
Plugin is not compatible with IDEA EAP 16

### ISSUE THREAD

**Issue by obourgain** [go-lang-plugin-org/go-lang-idea-plugin#2210]
Is there a way I can help on this topic ?

**Comment by ignatov** [comment]
You can provide a patch for Idea 16. Right now we have a bunch of compilation errors in the debugger module: https://teamcity.jetbrains.com/viewLog.html?buildId=664247&tab=buildResultsDiv&buildTypeId=IntellijIdeaPlugins_Go_TestsOnIdea144Snapshot

Please set up ideaVersion = 144.2608.2 in gradle.properties.

**Comment by dlsniper** [comment]
I've pushed https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2211 I'm testing it right now to see how things work and if there are any issues with the tests.

**Comment by obourgain** [comment]
I also got a PR, #2212 , it looks a lot similar to yours but I also fixed a compilation issue in GoHighlightingTest: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2212/files#diff-544004967bdfc48d2a248a107830982bR298

**Comment by dlsniper** [comment]
Right, I've ended up doing the same changes but still delve doesn't work, so more investigation is needed there.

**Comment by zolotov** [comment]
Compatible with IDEA 16 EAP plugin had been uploaded to the nightly channel.
