### ISSUE TITLE
File structure view freezes sometimes

### ISSUE THREAD

**Issue by segrived** [go-lang-plugin-org/go-lang-idea-plugin#2214]
Sometimes structure view stop refresh content until structure tool window will not be reopened. It can  occur randomly, but i can reproduce this issue every time when removing constant from source, for example. Maybe it's a little hard to explain, [so i record short video](https://www.youtube.com/watch?v=pn7_ghTojsE) with annotations.

**JRE**: 1.8.0_51
**Intellij IDEA version**: 15.0.2
**Go plugin version**: 0.10.978 (recent)

**Comment by zolotov** [comment]
Thanks for report. It looks like #2183. Please attach log to verify this (you can find logs directory via `Help | Show Logs`)

**Comment by segrived** [comment]
Log file:
[idea.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/77696/idea.txt)

**Comment by zolotov** [comment]
Indeed, it's the same issue, will be fixed in the next nightly build. Thanks again
