### ISSUE TITLE
Set custom GOPATH within Intellij

### ISSUE THREAD

**Issue by ruseinov** [go-lang-plugin-org/go-lang-idea-plugin#2216]
I've been trying to work around the 1.5 go vendor experiment by specifying a custom GOPATH within Go Libraries for the project. 

Version of plugin is 0.10.749
Problem is, when I disable the checkbox "Use GOPATH from system environment" and add a custom one - I don't have my project included, which does not get fixed by adding it to Project Libraries.

When I add my new vendor path + enable a default GOPATH with a checkbox, even though there is nothing in my original gopath rather than this project - I get all the project code working, and I can dive into other external library's code, but I can't call any methods on objects from these libraries, only package-level methods work.

Basic example would be: 
```
	api := rest.NewApi()
	api.SetApp(router(ctx))

```
Where SetApp method is not seen by IntelliJ Idea and none of the api object's properties either.

Here's also a screenshot of my setup: http://uploadr.obnovlenie.ru/uploads/lazycoder-2016-01-06-192451.png

And a screenshot of the outcome:
http://uploadr.obnovlenie.ru/uploads/lazycoder-2016-01-06-192528.png

This code does compile and work, also if I remove the vendor folder from the global libraries and add all the libraries contained by it in the gopath - it also works like a charm.

**Comment by dlsniper** [comment]
How do you compile / run your go code from the command line and what's the output of `go env`?

I'm tempted to say that this should be closed and follow: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820  but I need some more info first, thank you.

**Comment by ruseinov** [comment]
I know what you are trying to do:) But, specifying a custom gopath != vendor experiment support, it's just one of the cases. What I'm asking is whether it's possible right now or not, maybe I'm doing something wrong.

@dlsniper I do use `GOVENDOREXPERIMENT=1 go run main.go` for that and my go env is as follows
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lazycoder/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by dlsniper** [comment]
Ok, so your GOPATH entry should be `/Users/lazycoder/go` and that's it, which is the one that's being used in the screenshot already.

How does the import statement looks like? Can you give an example with actual code / paths (you can mock them if needed). Thanks

**Comment by ruseinov** [comment]
My import paths are the usual ones, full github.com/library/package etc
And they are exactly the same in vendor folder.

**Comment by dlsniper** [comment]
What's the error that you receive in the IDE for the lines you've mentioned? And does it happen with or without adding the second entry in the Go Libraries?

**Comment by ruseinov** [comment]
So the error here is "unresolved reference SetApp" and it does happen with the second line added. If it's not there - the libraries are not resolved altogether, since they are not in the go path, so even rest.NewApi() would give an error, since there is no package rest and no NewApi() in it.

**Comment by dlsniper** [comment]
That can happen either if the package doesn't indeed contain the called function or other strange error. Can you please describe your disk layout for the gopath and the packages that you want to use and give a screenshot of the project structure with the Project Libraries section expanded? Sorry, either there's a resolving error, or a setup error but I don't have enough information to understand what happens in the first place.

**Comment by ruseinov** [comment]
You can just test it out
go get github.com/ruseinov/gofail
Then import that to intellij and setup libraries like this: 
http://uploadr.obnovlenie.ru/uploads/lazycoder-2016-01-06-222432.png
Or like this:
http://uploadr.obnovlenie.ru/uploads/lazycoder-2016-01-06-222508.png

Idea would see the package and top-level methods, but object methods would be lost.

**Comment by ruseinov** [comment]
Yeah, and open main.go to see this: http://uploadr.obnovlenie.ru/uploads/lazycoder-2016-01-06-222553.png

**Comment by dlsniper** [comment]
Ok, so the problem because you have the package both in the normal GOPATH and in the project GOPATH (the second GOPATH).

If you copy your dependencies from the vendor folder to the GOPATH/src then it will work. If you remove the system GOPATH and only add `/home/florin/golang/src/github.com/ruseinov/gofail/vendor` as the GOPATH it will work. But if you have both then you'll receive this error and then everything will be (correctly) marked as not resolved (see below).

![snapshot187](https://cloud.githubusercontent.com/assets/607868/12155419/4caad004-b4c5-11e5-9021-d280e63f178b.png)

So either have your packages in the GOPATH as well or have your system GOPATH removed from the Go Libraries entries and set your GOPATH to `/home/florin/golang/src/github.com/ruseinov/gofail/vendor`.

**Comment by ruseinov** [comment]
@dlsniper I don't have the library in both places, I've made sure to clean it up for the sake of experiment.
Removing system gopath makes packages local to the project unavailable.

**Comment by dlsniper** [comment]
> Removing system gopath makes packages local to the project unavailable. 

That's because in that case the project doesn't respect the Go workspace layout in this case. To make this work you have to remove the common libraries from your GOPATH and BOTH the GOPATH and the custom vendor one added to Go Libraries. Otherwise this is a fight against the system as the plugin tries to respect the Go workspace layout and the project must adhere to it.

**Comment by ruseinov** [comment]
I do have this setup right now and it does not work.

**Comment by arvenil** [comment]
I have the same problem. Looks like adding `src` simlink to `vendor` dir helps.
This was described here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1820

**Comment by dlsniper** [comment]
@arvenil can you please describe your situation and solution with proper paths? I still don't understand from @ruseinov what's not working for him so maybe it would help him as well. Thank you.

**Comment by ruseinov** [comment]
So what's not working is that when you both have gopath and vendor folder
added - all object methods and props from vendor directory libraries are
unresolved. That's considering the fact that gopath contains no duplicates
of this libraries.

**Comment by ruseinov** [comment]
And if I only add vendor to gopath - project libraries are unresolved for
obvious reasons.

**Comment by dlsniper** [comment]
@ruseinov thanks for the reply. One last thing to check. Please remove the `src` as symlink and create it as a normal dir and copy the contents of `vendor/*` to the `vendor/src/` folder. I've managed to replicate your issue when I have a symlink but then it disappears when I have a hard copy. Thanks for your help with investigating this so far!

**Comment by arvenil** [comment]
Ok, I need to correct myself, @ruseinov issue is a different issue and I also have it :)
...
and I was just going to paste screenshots for @dlsniper but you just found out the same as me :)
Having `vendor/src/` as hard copy works fine... but it's not a solution as we need it for vendoring to be in `vendor/`.

**Comment by arvenil** [comment]
A temporary hack could be to make `vendor/github.com` a simlink to `vendor/src/github.com`... of course as long as vendoring tools won't complain on this like this library :)

**Comment by dlsniper** [comment]
Symlinks used to work (since there's also a recommendation earlier in the year to use them) so I guess this issue should be correctly described as having a new issue with resolving when symlinks are involved. I'll update it as soon as @ruseinov also confirms it, else I'll open a separate issue.

**Comment by ruseinov** [comment]
I do have src symlink, although it does not help me.
Ultimately it would be nice to be able to add a project library vendor/src
alongside gopath.

**Comment by dlsniper** [comment]
@ruseinov and instead if you have a physical `vendor/src` (or better said, no shortcuts anywhere?)

**Comment by dlsniper** [comment]
I'll close this as there's no feedback in a while for it. Please reopen if needed. Thank you.
