### ISSUE TITLE
Breakpoint cannot work 

### ISSUE THREAD

**Issue by ShevYan** [go-lang-plugin-org/go-lang-idea-plugin#2219]
Hi,

I'm using beego framework to develop a web application. When I set a breakpoint at the entry point of a web controller, the web http request would be pending forever. However, breakpoints at init() can work.

**Comment by ShevYan** [comment]
Add the system information:
Plugin version: 0.10.998
IDEA: IntelliJ IDEA 15.0.2 Ultimate
JDK8
OS version: 10.10.3
----------------------------------
However, I can debug in IntelliJ IDEA 15.0.2 Commnuity with plugin 0.10.749.

**Comment by ignatov** [comment]
Please provide some steps to reproduce.

**Comment by ShevYan** [comment]
1. go get github.com/beego/bee
2. run 'bee new beego-test' at $GOPATH/src
3. import the project at $GOPATH to IDEA
4. set breakpoint at controllers/default.go:12
5. right-click main.go -> debug
6. open "http://localhost:8080" in browser

Issue: Browser hangs and code cannot stop at the breakpoint.

**Comment by ignatov** [comment]
Is it possible to debug your application with standalone delve version?

**Comment by dlsniper** [comment]
This appears to be solved. I suspect it's related to the latest version of delve. I'm currently using 0.10.1128 version of the plugin (should be the same in 0.11.1130).

**Comment by dlsniper** [comment]
I'll close this for lack of feedback. Please reopen if still applicable.
