### ISSUE TITLE
Wrong pointer type detection for short variable declaration

### ISSUE THREAD

**Issue by Requilence** [go-lang-plugin-org/go-lang-idea-plugin#2222]
When using short pointer variable declaration asterisks is missing in the autocomplete
```
package main

type a struct{
	A bool
}

func main() {
	test:=&a{A:true}
	
}
```
![screen shot 2016-01-10 at 02 30 19](https://cloud.githubusercontent.com/assets/1025231/12218796/07f2db02-b743-11e5-8fb5-cfe7cb5ddaa6.png)

_Plugin: 0.10.1000
IntelliJ IDEA 143.1653.2_

**Comment by dlsniper** [comment]
Hi, can you please explain better what's the expected result and where? I'm sorry, I don't really understand what is missing right now from the screenshot and why. Thanks.

**Comment by Requilence** [comment]
@dlsniper need to be marked with asterisks in autocomplete window because *b* var has a pointer type. Just like that case
![screen shot 2016-01-10 at 02 42 43](https://cloud.githubusercontent.com/assets/1025231/12218834/0c56adc6-b744-11e5-9435-1727e470f4c0.png)

**Comment by dlsniper** [comment]
Oh I see now, thanks for the clarification!
