### ISSUE TITLE
UTF-8 characters output as '?' when running a .go file from within intellij

### ISSUE THREAD

**Issue by veqryn** [go-lang-plugin-org/go-lang-idea-plugin#2223]
When I run the following code inside intellij idea, I get '?' instead of international characters for the chinese characters in the string:
```
fmt.Println("日本語")
```

I've already tried all the solutions google proposed for fixing this issue for java files, such as:

"Settings->Editor->File Encodings" has both "IDE Encoding" and "Project Encoding" as UTF-8

both *.vmoptions files in the <installdir>/bin/ have:
-Dfile.encoding=UTF-8
-Dconsole.encoding=UTF-8

My system:
IDEA version 15.0.2
Go plugin version 0.10.749
Go version 1.5.2

**Comment by dlsniper** [comment]
What operating system are you using and can you please provide a sample that reproduces the issue? I can't reproduce it on Linux (plugin compiled from master from 4-5 days ago). Thanks

![snapshot188](https://cloud.githubusercontent.com/assets/607868/12219158/e3f362be-b736-11e5-8cb7-26433837ce8b.png)

**Comment by dlsniper** [comment]
Can you please paste a screenshot like mine? Thanks.

**Comment by veqryn** [comment]
Windows 7, fully updated
I use oracle java 8.
I was able to output chinese characters from a similar program written in java and run by intellij idea.
I was also about to output chinese characters running the same go file in eclipse (you can see in the picture below).

![idea_go_utf8](https://cloud.githubusercontent.com/assets/1897829/12225087/4319c340-b7bf-11e5-8061-193b070430d2.png)

**Comment by zolotov** [comment]
@veqryn please try to invoke Ctrl+Shift+Alt+/, then select Registry, find there `run.processes.with.pty` property and tell me what's the value of this property

**Comment by veqryn** [comment]
@zolotov the box is currently unchecked for that option.

**Comment by zolotov** [comment]
@veqryn what's the font used in `Settings | Editor | Colors & Fonts | Console Font`?

**Comment by veqryn** [comment]
It is the default, which for me is:
Scheme: Darcula
(The following options are grayed out)
Console Font: Show only monospaced fonts
Primary font: Monospaced
Size: 12
Line spacing: 1.0
Secondary Font: (blank)

**Comment by zolotov** [comment]
Sorry, I've missed the version you're using. Please could you try to switch to nightly channel and try with some new version. There is a description how to do it in README.md

**Comment by veqryn** [comment]
Just a note in case anyone asks, after adding the custom repository, you have to specifically browse that new repository and then click REFRESH, otherwise the list will be empty and show no new updates for the Go plugin...

Anyway, I've just upgraded to go plugin version (using nightly branch): 0.10.1032

It looks like this is finally working, so thank you very much!
