### ISSUE TITLE
Invalid call cap() on map

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2235]
```go
package main

func main() {
	m := make(map[string]int,99)
	cap(m) // invalid argument m (type map[string]int) for cap
}
```

**Comment by ignatov** [comment]
Temporary reverted in 02c39130d3916d95fc67628bc9f21ee47f087819 due to #2268

**Comment by dlsniper** [comment]
This can be closed now, was fixed in: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/c2c3513d92ca3d547db6c494fa6c4ee0dcca5c5b
