### ISSUE TITLE
Functions on dereferenced pointers cannot be resolved

### ISSUE THREAD

**Issue by SchumacherFM** [go-lang-plugin-org/go-lang-idea-plugin#2259]
Latest IDEA 15 and compile this plugin with the latest commit ID. Running on OSX.

Test Code:

```go
package main

type GroupSlice []Group

type Group int

func (gs *GroupSlice) Merge(groups ...*Group) error {
	for _, g := range groups {
		if err := (*gs).merge(g); err != nil {
			return err
		}
	}
	return nil
}

func (gs *GroupSlice) merge(g *Group) error {
	return nil
}
```
Result:

![screen shot 2016-01-17 at 6 34 40 pm](https://cloud.githubusercontent.com/assets/372027/12378787/bacd24ec-bd49-11e5-9ef6-322e5f1b6d6b.png)

**Comment by sjamesr** [comment]
@ignatov from bisecting I believe the culprit is d92ebc9fbbdfcabed359e1504658a209b0259965

**Comment by sjamesr** [comment]
It seems to me that `GoPsiImplUtil.resolveCallRaw` does not correctly implement the [rules for selector expressions](https://golang.org/ref/spec#Selectors). The implementation looks like:

```java
    if (e instanceof GoSelectorExpr) {
      GoExpression right = ((GoSelectorExpr)e).getRight();
      PsiReference reference = right instanceof GoReferenceExpression ? right.getReference() : null;
      return reference != null ? reference.resolve() : null;
    }
```

Given the rules of selector expressions, I don't see how the call to `reference.resolve()` can resolve the correct element without reference to the left hand side. Am I missing something?
