### ISSUE TITLE
Outline of Methods not showing up

### ISSUE THREAD

**Issue by lionelmessi** [go-lang-plugin-org/go-lang-idea-plugin#2262]
I have setup a project like:
- default.go (Here I define a struct T1)
- user.go (Here I define user related methods for T1)
- info.go (Here I define info related methods for T1)

I need to separate the methods in two different files as it was getting very long (> 1000 lines).

Initially, when they were in the same file default.go, I was getting the method outline properly.

When I split them, I dont see the outlines in user.go and info.go. But I see all the method outlines in default.go where the struct is defined.

Is this expected behavior? Possible to display the outline based on the content of the files rather than the struct they implement? Getting very difficult to navigate due to this. Any help is appreciated.

**Comment by sjamesr** [comment]
This might be https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1915

**Comment by lionelmessi** [comment]
Yeah looks like the same issue.

**Comment by ignatov** [comment]
Duplicates #1915

**Comment by dlsniper** [comment]
If this duplicates another issue, I'll close this one (easier to keep track of issues this way).
