### ISSUE TITLE
Unresolved reference not resolved unless I reload project

### ISSUE THREAD

**Issue by gtarcea** [go-lang-plugin-org/go-lang-idea-plugin#2263]
The plugin is generating unresolved references for methods that exist. There are multiple ways to have this occur. For example if I reference a non-existing method, and then later create it in, the go plugin will never resolve this reference. In order to get this reference to resolve I have to close the project and then re-open it.

This seems to be a new-ish behavior. It first started occurring when I upgraded to WebStorm 11. This also upgraded the golang plugin, so I cannot tell if the problem is the webstorm upgrade, or the new version of the golang plugin.

This is happening very frequently. I have to reopen the project multiple times a day (and sometimes an hour) to fix these resolve issues.

I've tried running analysis, closing the file, running sync. None of these fix the issue.

Please let me now what additional details I can provide.

Webstorm version: 11.03
Go Plugin Version: 0.10.749

**Comment by dlsniper** [comment]
@gtarcea can you please share screenshots, code samples, details about your setup and so on? Without more information it's next to impossible to understand what's the issue. Thank you.

**Comment by gtarcea** [comment]
Ok, I'll put together the steps to reproduce and my complete setup. I was hoping this was a known issue, since it has been happening so consistently. I'll get something up in the next day.

**Comment by dlsniper** [comment]
It might be a known issue but without logs and steps to reproduce the issue it might be that's a different issue or just a misconfiguration :)

**Comment by dlsniper** [comment]
I'll close this due to lack of feedback and really old plugin version.
If this still happens please open a new issue
Thank you.
