### ISSUE TITLE
Debugging disabled when run/debug config set to single file on Windows.

### ISSUE THREAD

**Issue by kolkov** [go-lang-plugin-org/go-lang-idea-plugin#2264]
Is this a bug?

**Comment by zolotov** [comment]
Not exactly, see #1922 for details

**Comment by dlsniper** [comment]
Hi, no, this is working as intended.
Delve doesn't support yet Windows so there's no debugger for it.
Please watch this ticket https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922

**Comment by kolkov** [comment]
I am using custom plugin builded by myself.
When run/debug config set to package, debugging is enabled!

**Comment by zolotov** [comment]
I see. Yes, debugger is not available for running file, because Run File configuration doesn't produce any binary and debbuger has no process to attach. It might be fixed after #2013

**Comment by kolkov** [comment]
Thanks!
