### ISSUE TITLE
Support for debugging on kernel 2.6

### ISSUE THREAD

**Issue by lekararik** [go-lang-plugin-org/go-lang-idea-plugin#2272]
Hi,
installed WebStorm 11.0.3 Build#WS-143.1559 over CentOS release 6.5 (Final)
installed plugin via https://plugins.jetbrains.com/plugins/nightly/5047

Expected result is get Go Lang Debugging tools working

the debugger start working and then at the following breakpoints it stop and not shows debugger tools or any step forward or step in...
just stuck... 

![image](https://cloud.githubusercontent.com/assets/15989650/12453053/2518e35c-bf9a-11e5-9530-589f1b20b2f2.png)
![image2](https://cloud.githubusercontent.com/assets/15989650/12453054/2519d44c-bf9a-11e5-87bb-c5fd5cb6902d.png)

**Comment by dlsniper** [comment]
It looks like delve doesn't stop the process correctly. Is CentOS 6.5 supported by delve? I can't replicate it on Ubuntu 15.10, sorry.

**Comment by dlsniper** [comment]
Which kernel do you have?

**Comment by lekararik** [comment]
uname -r outputs: 2.6.32-504.12.2.el6.x86_64

**Comment by dlsniper** [comment]
It looks like you are running an unsupported kernel: https://github.com/derekparker/delve/issues/209 (I'm not even sure if Go itself supports this properly).

**Comment by dlsniper** [comment]
@ignatov could we disable debugging if the current OS is linux and kernel version is < 3.4? Eventually show a message that this feature is disabled because of Delve lacking the support for it.

**Comment by dlsniper** [comment]
This was merged in delve and we use the latest version. Please check and reopen if needed. Thanks.
