### ISSUE TITLE
1.6 beta2 support

### ISSUE THREAD

**Issue by vpol** [go-lang-plugin-org/go-lang-idea-plugin#2273]
go-lang-idea-plugin 0.10.749 does not detect "Project SDK" at go 1.6beta2 home (.../go1.6beta2/libexec)

Pycharm 5.0.3
MacOS 10.11

**Comment by zolotov** [comment]
Please try nightly build

**Comment by dlsniper** [comment]
Can you please point your SDK root dir to `<path>/go1.6beta2` ? I can't replicate it on Linux + Idea but it's essentially the same code in the plugin. Thank you

**Comment by dlsniper** [comment]
Ah, sorry, follow what @zolotov said, github didn't show his comment until I've made mine....

**Comment by vpol** [comment]
Yes. Seems to be working fine with 0.10.1032.
