### ISSUE TITLE
Possible annotator / parser issue with escape sequences

### ISSUE THREAD

**Issue by drathier** [go-lang-plugin-org/go-lang-idea-plugin#2274]
Given the following code:
```go
package main

func main() {
	switch 'a' {
	case <caret>
	}
}

```

If you type in the following sequence then the text will remain still highlighted as an error:

- type ``` '' ``` (two single quotes to mark a rune)
- remove the last single quote
- type ``` \n ```
- type again ``` '' ``` two single quotes
- remove any single quote of the new set of quotes
- error should happen

Hopefully the video will help as well: https://youtu.be/AJ4Irzje5wU

----

**Original issue:**

When I type a `case` statement with multiple options I get a red line warning me about the syntax error. When I overwrite this whole case statement by copy/pasting it, it then works as expected. 

`case 'a', 'b':` gives a red line under `'b'` and the text is white. If I cut any part of the source so that I cut out at least `'b'` and then paste it back over (or copy/paste it), it becomes green like `'a'` and works as expected. 

recreate:
1. add this case to any switch statement: `case 'a', 'b':`
2. select the whole switch statement (roughly, not important to get it right, as long as 'b'` is covered.
3. ctrl+c
4. ctrl+v
5. now works as expected

**Comment by dlsniper** [comment]
Hi,

I can't reproduce the issue, please see: https://youtu.be/daSfrUujny0
To be able to reproduce this issue please provide:
- IDE version
- plugin version
- code sample
- description of the error that the plugin reports

Thank you.

**Comment by drathier** [comment]
I remembered it wrong, sorry. The error is with escaped rune litterals, not case statements in particular. Feel free to edit the title. 

It gives me red error lines under `'\` and `'` in `'\n'`, `\t`, `'\v'` etc. but not under the letter. The text inside the quotes, and the quotes themselves, are white. No other syntax highlighting breaks. 
![skarmklipp 2016-01-21 00 14 17](https://cloud.githubusercontent.com/assets/3695812/12466315/f3a9d7ec-bfd3-11e5-84a0-bd90c8c08864.png)

If I type `'` `\` `n` `'` it gives me the error lines, but if I write the letter last, i.e. `'` `\` `'` `left arrow key`  `n` to get the same result, it recognizes it as a rune litteral. Copy/pasting the litteral also works, and restarting pycharm fixes it as well. Until I type a new one; then the new one is broken.

I'm using pycharm 4.5.3 with go plugin 0.9.402 and 0.9.748, on osx 10.11 and windows 10. Bug persist in all combinations of these, i.e. four setups.

**Comment by dlsniper** [comment]
@drathier I've managed to constantly reproduce it but a bit different. I've updated the description of the issue to reflect this. Thank you for reporting. I'm defering now to the experts :)
