### ISSUE TITLE
Request: Quick Documentation should show field documentation

### ISSUE THREAD

**Issue by veqryn** [go-lang-plugin-org/go-lang-idea-plugin#2275]
Quick Documentation (ctrl-q) does not show any documentation for fields.

Auto-complete will at least tell me what type the field is (ex: map[*string]interface{} ).  However, if I have already typed it out, and I ctrl-q on it, it doesn't say what type it is.  It would be extremely useful to show what type it is, and which type it is under (ex: if under an embedded sub-type).

If I ctrl-click and go to the source for the struct type a field is under, I can see the full documentation of each field.  But if there are embedded or nested-embedded types, I would have to keep ctrl-clicking into them and finding and reading each doc.  Any comments preceding a field should be included in the quick-doc for that field.

Plugin version: 0.10.1032 (nightly as of 2016/01/20)
JDK 1.8.0_66
Windows 7 SP1 fully updated

**Comment by zolotov** [comment]
duplicates #1987
