### ISSUE TITLE
Run 'Test all' with coverage should not attempt to include sub-packages

### ISSUE THREAD

**Issue by davelondon** [go-lang-plugin-org/go-lang-idea-plugin#2276]
When I use the context option: "Run 'All in foo' with coverage", where foo is a package, the command executed is:

```/go test -v ././... -coverprofile=/[...]$All_in__foo_.coverage -covermode=atomic```

When the foo package has sub-packages, this always fails with the error ```cannot use test profile flag with multiple packages```. If the command was instead:

```/go test -v . -coverprofile=/[...]$All_in__foo_.coverage -covermode=atomic```

It would work.

**Comment by dlsniper** [comment]
@zolotov until Go determines what's the best way to do this (see https://github.com/golang/go/issues/6909) I think the suggestion to run the coverage only on the current package is ok.

Another option would be to get all the sub-packages of the current package and then run the tests for each package individually, merge the results and display them (but that might be too much of a hassle). 

What do you think? If you agree with this, I have a patch in mind, I'll submit it tonight. Thanks.

**Comment by zolotov** [comment]
@dlsniper @davelondon I don't understand what's suggestion? There is directory target in test run configuration and it runs gotest with `./...` parameter. Are you suggesting to drop Directory target and keep only Package target for tests?

**Comment by dlsniper** [comment]
In Go, the ` ... ` indicates "directory + sub-(directories|packages)". When running the tests in a package (or directory) it could generally be ok to run them in the children packages/dirs as well. 

However, Go coverage doesn't support yet generating coverage reports for multiple packages. In this case, the test runner should choose to run in the current package / directory only and omit the children.

Thus we either run the coverage tests for each children, merge everything together and then display the results or we run only on the current level and that's it.
