### ISSUE TITLE
Refactor does not reformat godoc comments

### ISSUE THREAD

**Issue by drathier** [go-lang-plugin-org/go-lang-idea-plugin#2279]
I would want a refactor on `Str` to also change the godoc comment immediatelly above it, if it follows the godoc format.

    // Str is a string.
    var Str string

**Comment by dlsniper** [comment]
If you are using the refactoring from the shortcut (mine is `CTRL + R`) then you have to press it twice and it will give you a dialog. Choose from that to search in strings and comments and this will work.
