### ISSUE TITLE
Do not able install in CLion 1.5 EAP

### ISSUE THREAD

**Issue by EvgenKostenko** [go-lang-plugin-org/go-lang-idea-plugin#2280]
Do not able install in CLion 1.5 EAP there no in plugins

**Comment by dlsniper** [comment]
The nightly plugin should be there. Please see https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds on how to install it.

**Comment by dlsniper** [comment]
Yup, it's there and it works, I've just checked with the latest nightly. Please let me know if you have any issues with getting it to run on CLion.

**Comment by EvgenKostenko** [comment]
How I can open or create project without C stuff for example CMakeLists.txt?

**Comment by dlsniper** [comment]
@EvgenKostenko that's not possible right now. @ignatov / @zolotov should I file a separate issue for this?

**Comment by zolotov** [comment]
@dlsniper Go plugin has nothing to do with this

**Comment by dlsniper** [comment]
I suspected but I wasn't sure. Thank you.
