### ISSUE TITLE
Not getting the arrow to view variables in Debugger

### ISSUE THREAD

**Issue by lionelmessi** [go-lang-plugin-org/go-lang-idea-plugin#2287]
OS: Ubuntu 14.04
Android Studio: 1.5.1
Plugin: 0.9.1025

```go
package main

import "fmt"

func main() {

	userid := "1139463560489862190"

	type Info struct {
		name  string
		add   string
		phone string
	}

	p := Info{
		name:  "Main",
		add:   "1233",
		phone: "12334546",
	}

	fmt.Println(p)
	fmt.Println(userid)
}
```

I do not have the arrow to check the variables content.
![screenshot from 2016-01-22 18 42 33](https://cloud.githubusercontent.com/assets/5489402/12531459/1231bdb4-c1b0-11e5-8aa9-dba45bdd7b53.png)

**Comment by ignatov** [comment]
Please try the latest nighlty build, bacause everything is fine with my snapshot build:
<img width="1072" alt="screenshot 2016-02-05 23 59 05" src="https://cloud.githubusercontent.com/assets/426890/12859013/8d31169a-cc64-11e5-85c4-e5be448c060b.png">
And also, please specify your OS and delve version. It's inside the plugin's zip.

**Comment by ignatov** [comment]
Please reopen if needed.
