### ISSUE TITLE
Unable to import an existing go project

### ISSUE THREAD

**Issue by ghost** [go-lang-plugin-org/go-lang-idea-plugin#230]
I am unsuccessfully trying to import an existing go project using the "Import Project" feature of IntelliJ. The steps are as follows:

1. Execute git clone https://github.com/jnwhiteh/golang.git in my home directory.
2. Launch IntelliJ.
3. Click on "Import Project".
4. Navigate to the directory.
5. Click next on the "Import Project from Existing Sources" dialog.

The result is

![screen shot 2013-05-19 at 1 08 58 pm](https://f.cloud.github.com/assets/1377100/522549/53f3b0b2-c042-11e2-82cd-754fd1697a44.png)

Plugin version:
IntelliJ version: 12.1.3 (129.451)
OS: Mac OS X - 10.8.3

**Comment by dlsniper** [comment]
This works for now so I'm closing it.
