### ISSUE TITLE
Cannot find the reference for same types

### ISSUE THREAD

**Issue by lionelmessi** [go-lang-plugin-org/go-lang-idea-plugin#2300]
OS: Ubuntu 14.04
Android Studio: 1.5.1
Plugin: 0.9.1052

```go
package main

import (
	"bytes"
	"fmt"
	"net/http/httptest"
)

func main() {
	var Body *bytes.Buffer
	w := httptest.NewRecorder()
	
	Body.String()
	fmt.Println(Body.String())
	fmt.Println(w.Body.String())
}
```

![image](https://cloud.githubusercontent.com/assets/5489402/12545058/dfc326f2-c2f3-11e5-984c-0bef215f20bf.png)

In the above example, both `Body` and `w` are of the same type, yet I am seeing an unresolved error for the `w` one but `Body` is resolved fine for `String()` method.

**Comment by ignatov** [comment]
@lionelmessi Please provide a text from your screenshot.

**Comment by dlsniper** [comment]
@ignatov I've updated the description with the code.

**Comment by ignatov** [comment]
Duplicates #2259
