### ISSUE TITLE
Printf placeholders incorrect count for left-justify

### ISSUE THREAD

**Issue by mrcook** [go-lang-plugin-org/go-lang-idea-plugin#2306]
Using `Printf` with left-justify formatting ("pad with spaces on the right rather than the left") I get a `Got 0 placeholder(s) for 1 arguments(s)` error. Example:

```
fmt.Printf("%-4d", 999)
```

**Comment by dlsniper** [comment]
Thank you for reporting.

**Comment by mrcook** [comment]
A quick update: "always print a sign for numeric values" is the same.

```
fmt.Printf("%+d", 99)
```
