### ISSUE TITLE
Debug support on Windows

### ISSUE THREAD

**Issue by uuf6429** [go-lang-plugin-org/go-lang-idea-plugin#2309]
The latest Delve [build also works on Windows](https://github.com/derekparker/delve/wiki/Building#windows), however this plugin seems to miss (or disable?) some debug functionality, for instance I cannot set breakpoints and the debug toolbar button is disabled (but strangely `Run -> Debug` is enabled).

Am I missing something, or is it just a matter of time until this gets fully supported?

**Comment by dlsniper** [comment]
This is correct, delve is not yet supported by the plugin, but it's getting there. Please follow https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922 I'll close this as duplicate.
