### ISSUE TITLE
Error: The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by yaa110** [go-lang-plugin-org/go-lang-idea-plugin#2310]
go version go1.6beta2 linux/amd64
IDEA version: 15.0.3
OS version: Ubuntu 14.04 64-bit
JDK version: 1.7.0_21
Plugin version: 0.10.749
GOROOT="/usr/lib/go"

![screenshot from 2016-01-27 19 56 34](https://cloud.githubusercontent.com/assets/3187511/12620118/28ea0128-c530-11e5-9911-5cf090a26204.png)

**Comment by zolotov** [comment]
Go version?

**Comment by yaa110** [comment]
go version go1.6beta2 linux/amd64

**Comment by zolotov** [comment]
Fixed in alpha release, please see readme to find out how to install it.

**Comment by yaa110** [comment]
Thanks
