### ISSUE TITLE
Import Popup not working

### ISSUE THREAD

**Issue by AgentO3** [go-lang-plugin-org/go-lang-idea-plugin#2322]
I noticed that the import popup is no longer functioning for the Go plugin. 

Plugin version 0.10.1104
Intellij 15.0.3

If I write fmt without it already declared as an import the import popup never detects that there are possible packages that can be imported. I tried the shortcut to get the popup to come up but still no luck.

**Comment by dlsniper** [comment]
@AgentO3 thank you for reporting this. Please attach a code sample to reproduce this issue as it's hard to understand the conditions this happens without it. Thank you!

**Comment by AgentO3** [comment]
Maybe this gif will help...

1. I create a new file main.go with a package main
2. I create a `func main(){}`
2. In side the func main I type `fmt.Println("hello")`

I expect that Intellij will see that fmt is possibly a package and ask me if I want to add fmt to the import statement or suggest other possible packages that might match. This feature of Intellij is described here.
https://www.jetbrains.com/idea/help/creating-imports.html#d1610518e161

This is happening for all packages in the GOPATH not just the standard library. This was working in previous version but has seemed to stop.

**Comment by zolotov** [comment]
Cannot recreate on nightly. Any details? Plugin version, IDEA version, screenshot of file with following content:

```go
package main

func main() {
  fmt.Println("Hello")
}
```

**Comment by AgentO3** [comment]
As far as I can tell my workspace is setup correctly. If I go and manually add the imports by had I get auto complete suggestions of possible packages.

Plugin version 0.10.1104
Intellij version 15.0.3

I'll try the nightly builds and see if I have the some problem.

**Comment by AgentO3** [comment]
Uninstalled the plugin then reinstalled the plugin has corrected the problem.
