### ISSUE TITLE
Ginormous Editor Indents

### ISSUE THREAD

**Issue by sylnsr** [go-lang-plugin-org/go-lang-idea-plugin#2323]
For some reason, only the go file's editor makes all indents a tab of 8 spaces in size. This never used to be the case. I've been upgrading the GO plugin for a while now but have not been developing in GO so I have not noticed this new issue till today.

When I uninstall the Go plugin and reopen a .go file, the indentation is back to normal. I reinstalled the Go plugin and the humongous indents are back. 

Setting the: Editor > Code Style > Other File Types > Indent: size to whatever, makes no different and there isn't a dedicated Code Style for GO in the settings.

Example: http://bit.ly/1JZ8zFH

OS: Xubuntu 15.10
Java: 1.7
Intelli-J Go Plugin: 0.10.1068
Intelli-J theme: Darcula (although, the default theme makes no difference)
Intelli-J edition: Ultimate

**Comment by sylnsr** [comment]
Never mind, I reinstalled the plugin a third time and now the Code Syle is in the list and can be fixed.

**Comment by dlsniper** [comment]
By default tabs are 8 spaces in Go and this can be overridden from the code styles section for each individual language on a per project or by default basis.
