### ISSUE TITLE
update to 16 eap  144.3600.7 and now can't install plugin

### ISSUE THREAD

**Issue by antonikonovalov** [go-lang-plugin-org/go-lang-idea-plugin#2325]
IntelliJ IDEA (Minerva) IU-144.3600.7
Build #IU-144.3600, built on February 2, 2016
JRE: 1.8.0_40-release-b127 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by zolotov** [comment]
Hi Anton, the plugin will be available in the nightly channel in few minutes.
We have a lag between IDEA EAP release and building plugin for new EAP. So if you strongly depend on go-lang plugin please avoid upgrading to the new IDEA EAP at least for a one day after it's released.

**Comment by antonikonovalov** [comment]
Thanks!
