### ISSUE TITLE
Plugin version

### ISSUE THREAD

**Issue by EagleMoor** [go-lang-plugin-org/go-lang-idea-plugin#2332]
Can't see plugin version. Show only need update.

WebStorm last version + go-lang-idea-plugin nightly

![screen shot 2016-02-08 at 12 48 43](https://cloud.githubusercontent.com/assets/1461295/12882425/87df9360-ce62-11e5-882d-e6de10d85980.png)

**Comment by dlsniper** [comment]
That's a "problem" in the platform. Please restart your IDE so that the version is visible. I've just updated the plugin as well and I could replicate this "issue".

**Comment by EagleMoor** [comment]
Yes, after restart all good. Thanks
