### ISSUE TITLE
If err

### ISSUE THREAD

**Issue by EagleMoor** [go-lang-plugin-org/go-lang-idea-plugin#2334]
Try write ```if err```. Autocomplete help you and get 2 options: ```var err``` or ```If err```.
If use ```If err```, ide not update your code ```if err```. They add new line with ```if err```. Not cool.

![screen shot 2016-02-08 at 14 27 10](https://cloud.githubusercontent.com/assets/1461295/12884546/11786dd8-ce70-11e5-9148-0009a69cefae.png)

**Comment by zolotov** [comment]
duplicates #2315
