### ISSUE TITLE
Problems with Add unambiguous imports

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2336]
Auto-import of packages when Add unambiguous imports is checked adds the wrong package if there are multiple packages which satisfy the same name / function.
For example:

- have ` github.com/lunny/log ` in the GOPATH
- in a file paste ` log.Printf() `
- the import will default to the stdlib `log` package instead of not asking which package to import

Moreover, when this option is unchecked, the package list will still not be shown and the stdlib `log` package will be imported when using `Alt+Enter` key combination.

I can make a video if needed to better describe the issue.

Plugin version: 0.11.1130
IDEA 16 EAP: 144.3600.7
OS: Ubuntu 15.10

**Comment by garukun** [comment]
I would add that if you have a package say `github.com/a/log` whose API is `log.Info` instead of `log.Print`, it still adds the std `log` package, where as it's obvious in this case that it should be `github.com/a/log`

**Comment by growler** [comment]
A test case:

Do `go get github.com/influxdata/influxdb/client/v2`

open Idea and start following .go file:

```
package main

import (
    "github.com/influxdata/influxdb/client/v2"
)

function main() {
    _ := client.
}
```

put cursor at `client.` and wait for autocompletion  menu. Idea will suggest symbols from both `.../client/` and `.../client/v2`. Pick a symbol (i.e., `Query`) from `.../client/v2` library. 

Idea will add another import line for `"github.com/influxdata/influxdb/client/v2"` and still will highlight added symbol as unresolved.

**Comment by zolotov** [comment]
@growler thank you, I will use this as a test sample.
