### ISSUE TITLE
Template Must not enough arguments

### ISSUE THREAD

**Issue by kolkov** [go-lang-plugin-org/go-lang-idea-plugin#2341]
![image](https://cloud.githubusercontent.com/assets/3740898/12996027/2911cc30-d13d-11e5-8838-ee81fe8b0004.png)

**Comment by dlsniper** [comment]
Hi @kolkov, thanks for reporting.
Please give us the plugin version. Also it would be very helpful to have a code sample that is copy-pasteable as screenshots are notoriously hard to copy code from.
Thank you.

**Comment by dlsniper** [comment]
I've just noticed that your ` External Libraries ` section from the `Project Structure` doesn't contain a Go SDK attached to it.
Please attach one to the project.
Also, please attach a screenshot of the ` File | Settings | Languages & Frameworks | Go | Go Libraries `. I believe that your GOPATH settings is wrong (but I need to confirm first).

**Comment by kolkov** [comment]
Yes! Bug in settings. This is my old project from Go 1.5.1.
Project Sttings / Modules / Dependencies / Module: old SDK 1.5.1 instead new 1.5.3. in Module SDK.
Thanks! Solved!

**Comment by dlsniper** [comment]
Cool, I'll close this of then. Cheers.
