### ISSUE TITLE
Loading an existing project from disk

### ISSUE THREAD

**Issue by parhamdoustdar** [go-lang-plugin-org/go-lang-idea-plugin#2343]
Currently, I see no option to load an existing Go project into the IDE. There is the possibility of loading it from an Eclipse project or cloning from git, but not simply opening a directory under `$GOPATH/src/<base path>/<project>`.

Is it because I'm using Android Studio? Am I missing something?

**Comment by ignatov** [comment]
Just use open... action and select the desired directory.

**Comment by dlsniper** [comment]
@parhamdoustdar should I consider this answered (and close it)? Have you managed to open a project the way Sergey described? Thank you.

**Comment by parhamdoustdar** [comment]
My bad. Thank you for the help.
