### ISSUE TITLE
I can't see the goimports file option in the code menu, and setting a keystroke doesn't work either

### ISSUE THREAD

**Issue by parhamdoustdar** [go-lang-plugin-org/go-lang-idea-plugin#2344]
I'm using plugin version 0.10.1068.

For one thing, I can't see the `goimports file` menu item when right-clicking on a file and when checking in the code menu. I'm not sure if I must see them there since there is no user manual. However, I found this out by looking at previous issues.

To better test this, what I did was to set a keystroke to "goimports file", namely alt+ctrl+shift+G. When I press it, nothing happens. I see nothing in the messages window, except this, which I'm guessing is irrelevant:

```
9:38:54 AM NoReadAccessException
           Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
           Details: Current thread: Thread[Thread-2,5,main] 2037334768
           ; dispatch thread: false; isDispatchThread(): false
           SystemEventQueueThread: Thread[AWT-EventQueue-0 Studio 2.0#AI-143.2602393 Studio, eap:true, os:Windows 7 6.1, java-version:Oracle Corporation 1.8.0_73-b02,6,main] 195446184
```

Sorry if my issue doesn't help much; I'm new to IntelliJ and hence I don't know how to provide more information. Let me know what I can do to help you more.

**Comment by dlsniper** [comment]
Hi @parhamdoustdar,

Thanks for the issue.

> For one thing, I can't see the goimports file menu item when right-clicking on a file and when checking in the code menu. I'm not sure if I must see them there since there is no user manual. However, I found this out by looking at previous issues.

That's correct, there's no right-click functionality implemented to display gofmt / goimports file.

>  When I press it, nothing happens. I see nothing in the messages window, except this, which I'm guessing is irrelevant:

Can you please provide the full stack (preferably a link to a pastebin as it can be too long to do it here) to determine if it's the plugin which emits that or something else?

And to finally address your issue, can you see ` Code | Goimports file ` option enabled? For me it looks like this: 
![snapshot219](https://cloud.githubusercontent.com/assets/607868/13033301/663dd280-d312-11e5-973b-6b6590ceda68.png)
If yes then the functionality should work, if not, then it means that the IDE cannot detect the goimports binary in the GOPATH, can you please share a screenshot of your ` File | Settings | Languages & Frameworks | Go | Go Libraries `?

Also please provide the IDE name and version (and OS as well).

Thank you.

**Comment by parhamdoustdar** [comment]
Hi,

I'm on Windows 7. I'm using Android Studio 2.4 Beta 4, and I'm guessing some issues I have is related to that fact. For example, there is no way to actually import a project like the documentation in the wiki shows, and thus, I'm not asked for the Go SDK version.

Anyway, I added `C:\Go\src` to the `Global Libraries`, and afterwards, I could see the `Goimports File` menu item. However, when I run it, either from the menu or using the `ctrl+alt+shift+g` keystroke I mentioned, I get this:

```
Error:Sdk is not set or Sdk home path is empty for module
```

So what I did was to go to the `Project` tab, choose the `Project` tab in that window (which shows my project name and `External Libraries` which includes my `$GOPATH`), then right-click and choose `Open Module Settings`. I then went to the `SDKs` and added `C:\go` as a `Go` SDK. I now see `Go 1.5.2` as an SDK.

However, still, using `ctrl+alt+shift+F` and `ctrl+alt+shift+G` makes the same thing happen:

```
Sdk is not set or Sdk home path is empty for module
```

Unfortunately, I can't send you any screenshots because I'm completely blind (I'd probably send you an image of my desktop instead!). However, in my `Go Libraries`, I have `[GOPATH] C:\Users\Parham\go\src` and `C:\Go\src`.

My `Project Libraries` and `Module Libraries` are both empty.

**Comment by dlsniper** [comment]
Hi,


I understand the setup much better now, thank you for details.
Here's a list of things to check for:
- in `Go Libraries` please remove the `C:\Go\src` (if I understand correctly it's part of the SDK)
- if you added a new SDK for Go, which you can check under `Project Structure | SDKs` then I please check that either `Project Structure | Project` has the SDK configured as the Go SDK or `Project Structure | Modules | <name of your module> | Dependencies | Module SDK` is set to the Go SDK.

Also, please check that the `goimports.exe` is under `C:\Users\Parham\go\bin`.

Hopefully this should fix the issue.

**Comment by parhamdoustdar** [comment]
Hi,

Thanks a lot for your help. Here is what I did:

1. I removed `C:\go\src`.
2. I went to `Project Structure` and chose `Go 1.5.2` as the SDK for this project.

It finally works!

Do you think it'd be helpful to add this set up procedure to the wiki for people using Android Studio? If so, I'll be glad to write up the steps and add it to the wiki.

**Comment by dlsniper** [comment]
That's great news! Happy it works now.

> Do you think it'd be helpful to add this set up procedure to the wiki for people using Android Studio? If so, I'll be glad to write up the steps and add it to the wiki.

Yes, it would be useful. I've been delaying updating the docs as the whole setup should be revamped at some point. If you are willing to write up the procedure that would be great as we could use it until the changes are done.

If it's ok, I'll close the issue for now. Happy coding!
