### ISSUE TITLE
reflect.Value not shown when debugging

### ISSUE THREAD

**Issue by kolkov** [go-lang-plugin-org/go-lang-idea-plugin#2347]
```Go
package main

import (
	"fmt"
	"github.com/go-ozzo/ozzo-config"
)

func main() {
	// create a Config object
	c := config.New()

	// load configuration from a JSON string
	c.LoadJSON([]byte(`{
        "Version": "2.0",
        "Author": {
            "Name": "Foo",
            "Email": "bar@example.com"
        }
    }`))

	// get the "Version" value, return "1.0" if it doesn't exist in the config
	version := c.GetString("Version", "1.0")

	var author struct {
		Name, Email string
	}
	// populate the author object from the "Author" configuration
	c.Configure(&author, "Author")

	fmt.Println(version)
	fmt.Println(author.Name)
	fmt.Println(author.Email)
	// Output:
	// 2.0
	// Foo
	// bar@example.com
}
```
![image](https://cloud.githubusercontent.com/assets/3740898/13106600/3dde514c-d57a-11e5-9d07-e6040d907f51.png)

**Comment by ignatov** [comment]
Please try the same with the console version, I suspect that it's the issue of Delve.

**Comment by kolkov** [comment]
How can I do this?

**Comment by dlsniper** [comment]
To me this looks like an issue in Delve, see below:

![snapshot223](https://cloud.githubusercontent.com/assets/607868/13107043/ee12aa22-d56b-11e5-989b-ec185d286fa5.png)

**Comment by dlsniper** [comment]
@kolkov the debugger that the plugin is using is Delve. You can find it here: https://github.com/derekparker/delve and you can see everything you need in the readme/wiki :)

**Comment by kolkov** [comment]
@dlsniper Where can I do this? In the IDEA Debugger console?

**Comment by dlsniper** [comment]
@kolkov you can do this in your normal console / command line of your operating system.

**Comment by dlsniper** [comment]
Or the builtin terminal of IDEA

**Comment by kolkov** [comment]
@dlsniper Thanks!
I thought it was like in LiteIDE:
![image](https://cloud.githubusercontent.com/assets/3740898/13107667/be276f50-d57f-11e5-9e44-73b7ca5aa8a6.png)

**Comment by dlsniper** [comment]
Delve does not support this functionality yet, please see: https://github.com/derekparker/delve/issues/383 LiteIDE uses gdb as a debugging backend so a different story.

@ignatov I'd close this issue as we can't do too much for this for now (maybe just don't allow expanding of `unsafe.Pointer` type fields.

**Comment by kolkov** [comment]
@dlsniper Do I need to create issue in delve repo?

**Comment by dlsniper** [comment]
I've created the issue there. Thank you.
