### ISSUE TITLE
Unresolved reference when function return types defined on multiple lines

### ISSUE THREAD

**Issue by avaskys** [go-lang-plugin-org/go-lang-idea-plugin#2349]
https://play.golang.org/p/mCyxwALhTD

```go
package main

import "fmt"

type TestType struct{}

func (t TestType) func1() {
	fmt.Println("func1!!!")
}

func test() (
	TestType,
	error,
) {
	return TestType{}, nil
}

func main() {
	t, _ := test()
	t.func1() // Unresolved reference here
}
```

On line 20, go-lang-idea-plugin throws an unresolved reference error even though func1 is a method on TestType.

As a workaround, the return types can be defined on a single line:
```go
func test() (TestType, error) {
    return TestType{}, nil
}
```

**Comment by dlsniper** [comment]
I can confirm this on the latest nightly. @avaskys thank you for reporting!
