### ISSUE TITLE
Golang1.6 is not supported when setting GO SDK

### ISSUE THREAD

**Issue by shawnye** [go-lang-plugin-org/go-lang-idea-plugin#2350]
# Solution below:

Please use the alpha release channel to get this working (see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md#pre-release-builds for how to do this).
The new plugin version should be above 0.x.1000 (where x is 9, 10 or 11). Your IDE **must** be built on IntelliJ platform **143.1184** or newer.

---

**Original issue**

Golang1.6 has released.

Go to IDEA setting : 
`languagages & frameworks > Go > Go SDK`
choose golang1.6 Home , Version: `N/A`
while choose golang1.5 Home , Version: `1.5.3`

**Comment by asktalk** [comment]
i meet the same problom.

**Comment by dlsniper** [comment]
Pleaseuse the alpha release channel to get this working (see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/README.md#pre-release-builds for how to do this).

Thank you and sorry for the inconvenience.

**Comment by asktalk** [comment]
done,  It's OK

**Comment by asktalk** [comment]
thank you!

**Comment by shawnye** [comment]
Sorry, I do not know how to get latest changes.

I try to find plugin `Go` ,custom plugin respositories with `https://plugins.jetbrains.com/plugins/nightly/5047`,
the version do changed from v0.10.749 to v0.10.852, and nothing else changed, restart IDEA ,the problem occurred again.

**Comment by dlsniper** [comment]
@shawnye please upgrade your IDE to 15.0.2+ (or the latest which is 15.0.3). If it still happens, please let me know.

**Comment by shawnye** [comment]
Sorry ,forgot to say , I got the latest version:
webstorm 11.0.3

**Comment by dlsniper** [comment]
Oh... I can't answer this then, sorry. You can try IDEA Community or wait to see if @zolotov / @ignatov have a different answer / solution to this. Sorry I can't be more helpful.

**Comment by shawnye** [comment]
Thanks anyway.

Both webstorm and idea are products from  www.jetbrains.com,
I guess they should share the same plugin system.

**Comment by foolin** [comment]
The selected directory is not a valid home for Go SDK....

**Comment by dlsniper** [comment]
@shawnye the IDEs share the same plugin infrastructure, however Web Store seems to be behind IDEA in terms of version number of the platform thus it cannot use the newer version of the plugin. The building number should be greater than 143.1158 (or very close to that). 

@foolin please see the second comment: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2350#issuecomment-185569813. If that still doesn't work for you then consider including some details about your setup. Thank you.

**Comment by ctd1500** [comment]
I use WebStorm 11.0.3 which is build 143.1559, I've been using the latest nightlies for a long time.

@shawnye you might try uninstalling and reinstalling the plugin, the versions you mentioned are very old and the nightly repository is v0.10.1137 for WebStorm 11.0.3.
You might also try installing from the alpha repo instead of nightly, to see if it can get the newer version.

**Comment by soomtong** [comment]
same issue here

![image](https://cloud.githubusercontent.com/assets/906974/13172263/a09e267e-d73a-11e5-8c5a-cc4c32dfc468.png)

![image](https://cloud.githubusercontent.com/assets/906974/13172275/ab81b25e-d73a-11e5-9886-27defc3fea25.png)

using intelliJ communiti edition

![image](https://cloud.githubusercontent.com/assets/906974/13172294/c19b0b94-d73a-11e5-9d44-6fc862f70e9c.png)

plugin

![image](https://cloud.githubusercontent.com/assets/906974/13172338/ebb5a4ca-d73a-11e5-9934-d8119d03c731.png)

i ve got no problems  Go in 1.5.3 with this plug-in

**Comment by zolotov** [comment]
@soomtong same answer here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2350#issuecomment-185569813

**Comment by soomtong** [comment]
@zolotov Thank you! Sorry my Impatient! :hammer:

**Comment by dlsniper** [comment]
I've edited the original issue to provide the answer in the text, I've already deleted a comment so I could make sure that there are the two first things visible.
I would rather keep this open but locked so that people can actually read the issue instead of +1 / same here.

**Comment by dlsniper** [comment]
This is how it looks like now on my screen: ![snapshot227](https://cloud.githubusercontent.com/assets/607868/13173245/d59cc68e-d6fc-11e5-96ac-f35ec920ddf9.png)

I'd rather not close this as it's still visible in the issue list so hopefully no new issues will be opened (but locked so that we don't have me too's).
