### ISSUE TITLE
Completion does not include other *_test.go content within the same package

### ISSUE THREAD

**Issue by lancehit** [go-lang-plugin-org/go-lang-idea-plugin#2352]
- Plugin version (or commit hash): 0.10.1137 (alpha)
- IDE name and version: PyCharm 5.0.4 (143.1919)
- Java version: 1.8.0_51-b16 x86
- OS name and version: Windows 7 SP1 (x64)

I have a package with a mock_test.go file that contains mocks for interface types that are common between different production files in the same package.

In my actual test file (where I import "testing" and write func Tests) I'm unable to see completion for any of the structs found in mock_test.go. However, I can see parameter information for methods on those mock objects if I type the method name and hit (

This functionality existed previously, but I believe that was due to the over-inclusive nature of the completion implementation in previous versions. Now that it does not show \_test.go content in certain files, the scope of completion has seemingly been reduced to _only_ that file, rather than spanning across all \_test.go files in that package.

**Comment by zolotov** [comment]
Please attach code samples for recreating this.

**Comment by lancehit** [comment]
https://gist.github.com/lancehit/8012a408d3a94fc2f1c5 work for you? i can send you a repo if you need the structure too

**Comment by zolotov** [comment]
@lancehit this is great sample, thank you.

**Comment by laco0416** [comment]
I have same problem in ver.0.10.1137  (WebStorm 11.0.3)

**Comment by laco0416** [comment]
It's still remaining on ver.0.10.1164

**Comment by dlsniper** [comment]
@laco0416 these comments are not helpful nor it will help out solving or speeding up the process to get this fixed.
The best way to have this faster is to contribute to the plugin by following the instructions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/CONTRIBUTING.md 
Also if you are interested in following a certain issue, I highly advise to use the subscribe functionality of Github.
Thank you for your patience.
