### ISSUE TITLE
go reflect

### ISSUE THREAD

**Issue by HollisGW** [go-lang-plugin-org/go-lang-idea-plugin#2354]
![image](https://cloud.githubusercontent.com/assets/6017860/13195677/5e8241f8-d7f3-11e5-8536-319b39dfec11.png)
reflect value Not prompt

**Comment by dlsniper** [comment]
@HollisGW I can't replicate this. Please share more details about the issue, see the issue https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/ISSUE_TEMPLATE.md to see what you need to provide as details.

**Comment by HollisGW** [comment]
![image](https://cloud.githubusercontent.com/assets/6017860/13197159/4520a830-d820-11e5-86f7-92b95d123fb1.png)
Above is normal. 
![image](https://cloud.githubusercontent.com/assets/6017860/13197166/675f3254-d820-11e5-8551-731616db9c2d.png)
this is abnormal. can not normally prompt

**Comment by HollisGW** [comment]
I'm using 0.10.1137.

**Comment by dlsniper** [comment]
@HollisGW please give us more details as I cannot replicate the issue (I have the equivalent plugin version).

![snapshot231](https://cloud.githubusercontent.com/assets/607868/13197285/92dcc91e-d7e9-11e5-9c7f-6c499d11810e.png)

**Comment by kolkov** [comment]
Everything is working for me too

**Comment by dlsniper** [comment]
@HollisGW can you please post a screenshot of your ` Settings | Languages & Frameworks | Go | Go libraries ` as well (besides the additional information requested).

**Comment by HollisGW** [comment]
![image](https://cloud.githubusercontent.com/assets/6017860/13197507/a95bb6d2-d82a-11e5-8a40-b740810735a2.png)

I'm using 0.10.1137.  and go version 1.6

**Comment by HollisGW** [comment]
hi,ALL:
      problem was solved, thank you

**Comment by kolkov** [comment]
@HollisGW Please give instructions for those who will have a similar problem.
