### ISSUE TITLE
Add Go SDK: The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by gaplyk** [go-lang-plugin-org/go-lang-idea-plugin#2356]
- Plugin version (or commit hash):
0.10.852
- IDE name and version:
idea-IU-143.381.4
- Java version:
java version "1.8.0_72
- OS name and version: 
Ubuntu 15.10
- What are you trying to do?
Add Go SDK
- What would you expect to happen?
SDK added
- What happens?
getting message: The selected directory is not a valid home for Go SDK

This happens after i updated go from 1.5.1 to 1.6

**Comment by dlsniper** [comment]
Hi, please update your IDE to the latest version (15.0.3) and then update the plugin as well and it wil work. Thank you
