### ISSUE TITLE
Breakpoint add/remove does not work in a debugging session

### ISSUE THREAD

**Issue by martin-gorner** [go-lang-plugin-org/go-lang-idea-plugin#2359]
- Plugin version (or commit hash): 0.9.1135
- IDE name and version: IntelliJ IDEA 141.3056
- Java version: 1.8.0_31
- OS name and version: OSX 10.11.3

- What are you trying to do?
1/ Add a new breakpoint while the program is stopped at a breakpoint.
2/ Remove a breakpoint while  the program is stopped at a breakpoint.
3/ Use the "step over" command in the debugger

- What would you expect to happen?
1/ I expect the debugger to stop on the new breakpoint
2/ I expect the debugger to NOT stop on the removed breakpoint when execution is resumed
3/ I expect the debugger to stop on the next line

- What happens?
1/ the debugger runs to the end or the next breakpoint
2/ the debugger stops on the now deleted breakpoint
3/ the debugger runs to the end or the next breakpoint

**Comment by dlsniper** [comment]
Hi, can you please provide a code sample that can reproduce the issue? Thank you.

**Comment by martin-gorner** [comment]
The problem is not linked to a specific code snippet for me. It always behaves incorrectly as I described.

**Comment by dlsniper** [comment]
I'm going to close this for lack of feedback. I suspect it's the known issue in delve but we can't investigate for sure if we can't replicate it / have feedback for it.
