### ISSUE TITLE
Unable to pass arguments to debug session on windows

### ISSUE THREAD

**Issue by dprime** [go-lang-plugin-org/go-lang-idea-plugin#2362]
- Plugin version (or commit hash): 0.10.1137
- IDE name and version: Intellij dea 15.0.4
- Java version: 1.8 u60
- OS name and version: Windows 7 Ultimate

When attempting to pass arguments to a debug configuration, it fails and produces the following commands invoking the compiler and delve:

```
I:/go16\bin\go.exe build -o "C:\Users\david\AppData\Local\Temp\snapshot reader1go" -gcflags "-N -l" I:/golang/snapshot_reader/main.go
C:\Users\david\.IntelliJIdea15\config\plugins\Go\lib\dlv\windows\dlv.exe --listen=localhost:23076 --headless=true exec "C:\Users\david\AppData\Local\Temp\snapshot reader1go" -- argument1 argument2
```

The final execution does pass the arguments to the command line, but when you print out os.Args the passed arguments are not present. Perhaps the "--" is somehow breaking things? Is there a special command to pass these arguments in?

I've checked the docs on delve directly and it says to simply call 
`dlv debug binary arg1 arg2`
or 
`dlv exec binary arg1 arg2`

But that isn't what the plugin is doing here, it seems.

Any ideas?

Cheers!

**Comment by dlsniper** [comment]
Thanks for reporting.

I would CC @lukehoban for this one as the `--` is needed on Linux / Mac to pass the params to the binary but apparently this is not supported on Windows. Should the plugin just assume that on Windows it can do ` dlv --dlv-args exec target-binary --target-binary-args ` ? Thanks.

**Comment by mahdiz** [comment]
@dlsniper: No, that doesn't work. Windows grabs all arguments and gives them to dlv in that case. I tried different cases; none worked. It seems that we need support from delve people so that in Windows all args after exec (and the path of the process) will be forwarded by dlv.exe back to the process being debugged. 

Any ideas? This issue is really frustrating; makes the plugin useless for me :(

**Comment by mahdiz** [comment]
By the way, take a look at a similar issue in the delve repo:
https://github.com/derekparker/delve/issues/178

**Comment by dlsniper** [comment]
I've just bought a Windows license, now I need time to download it and install it on my crappy computer. But please don't say the plugin is useless, surely it helps you with other things (especially since this is not the plugins fault). 
It would be really helpful to find a way to specify the arguments on Windows, as this currently works well for Linux and OSX. If you could also look into this would be excellent. 

Thank you.

**Comment by dlsniper** [comment]
And yes, I've seen the "similar" issue, it works for OSX and Linux. Maybe blame Windows?

**Comment by mahdiz** [comment]
The plugin is great! I just meant it doesn't work for the code I'm currently working on as I'm running four different instances each with different set of args :) Anyway, thanks for the quick reply, and I'll certainly look into it more if I come up with a solution. And, yes I agree with you, we should blame Windows for this :)

**Comment by lukehoban** [comment]
FWIW - I believe the issue here is the same one being addressed in https://github.com/derekparker/delve/pull/501 which should be merged soon.

**Comment by mahdiz** [comment]
Yes, it seems to solve our problem here. No change to the plugin code seems to be necessary. I'll compile delve with the branch of derekparker/delve#501 to replace my dlv.exe. I'll get back to you with the result. Thanks @lukehoban!

**Comment by moitias** [comment]
@dlsniper the patch in question here (that I also believe to fix the issue at hand) was developed using the wonderful plugin on Windows, so many thanks for your work on the plugin - I find it indispensable!

As a sidenote; It seems that both options (with the -- or without) do work on Windows too with patched delve (on command line, did not test with the plugin as I didn't even realize you guys are supporting delve) as dlv parses -- and it seems to me you're using dlv to launch it. That is; when the PR lands on master in delve, this issue should resolve itself.

**Comment by mahdiz** [comment]
I just compiled the patched dlv and tested it with the plugin and the args problem is solved. Thanks @moitias!

**Comment by dlsniper** [comment]
Cool, thanks for the heads up. As soon as delve merges this in (and gets a build for it) we'll have it in the plugin as well. 
@moitias thanks for fixing this and @mahdiz thanks for testing it!
And on behalf of all the contributors to the plugin Thank you for the nice words as well ;)
