### ISSUE TITLE
Failed to install plugin on rubymine  and Pycharm

### ISSUE THREAD

**Issue by ohadpartuck** [go-lang-plugin-org/go-lang-idea-plugin#2363]
- Plugin version (or commit hash):
- IDE name and version: Rubymine 7
- Java version: 
- OS name and version:  Mac El captain

- What are you trying to do?
install the plugin
from disk and also from the remote repo (install from repositories)
https://plugins.jetbrains.com/plugin/5047
it's not found 

Or include a screenshot / video of the issue.

<img width="537" alt="screen shot 2016-02-27 at 1 26 26 pm" src="https://cloud.githubusercontent.com/assets/2236337/13372661/c30d6910-dd55-11e5-8a4b-2ee4bcacc0df.png">

@zolotov
@ignatov 
please review

**Comment by dlsniper** [comment]
Please upgrade to Rubymine 7.1 or later.

**Comment by dlsniper** [comment]
Furthermore, you can see the list of supported IDEs / versions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by ohadpartuck** [comment]
thanks , solved
