### ISSUE TITLE
Exclude vendor directories from tests

### ISSUE THREAD

**Issue by F21** [go-lang-plugin-org/go-lang-idea-plugin#2366]
In Go 1.6, the vendor experiment is now enabled by default (which is a really good thing). However, there doesn't seem to be a way to exclude the `vendor` directory when running tests: https://github.com/golang/go/issues/11659

If you're using `glide` for package management, you can run `go test $(glide novendor)` and the `glide novendor` command will generate a list of packages (excluding vendor) to test. However, `$(...)` doesn't work on windows, so it's not possible to set up the plugin to run tests within it.

It would be nice if the plugin had an option to exclude certain directories when running tests. For example, if we exclude the `vendor` directory, it could use that information to create a list of packages to pass to the `go test` tool.
- Plugin version (or commit hash): 0.10.1156
- IDE name and version: PHPStorm 10.0.3
- Java version: java version "1.8.0_73" Java(TM) SE Runtime Environment (build 1.8.0_73-b02) Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
- OS name and version: Windows 10 64-bit
- What are you trying to do?
  Exclude the `vendor` directory when running tests
- What would you expect to happen?
  Tests in the vendor directory should not be run.
- What happens?
  Tests in the vendor directory are run.

This is the my configuration for running tests:
![1](https://cloud.githubusercontent.com/assets/2263040/13382275/7cb05340-dec4-11e5-88ab-166f0407715f.png)

**Comment by dlsniper** [comment]
@F21 how do you run the tests right now? The plugin supports running tests per package / directory. Please follow the new issue template to file an issue. Thank you.

**Comment by F21** [comment]
@dlsniper Updated the original issue :smile:

**Comment by dlsniper** [comment]
@F21 what stops you from running this with a package configuration instead of directory? I'm just trying to understand the situation a bit better?

Maybe this could be avoided if we would would have an option to run with and without sub-dirs. This is also a bit inconsistent right now as we run the directory config with `/...` while the package configuration is running without.

@zolotov what do you think?

**Comment by F21** [comment]
@dlsniper: Usually when I am building something really small and simple (like a microservice) with just a few packages, I want to be able to run all the tests for main and my own packages (but not vendor) with just a click,

**Comment by dlsniper** [comment]
Understood, thanks. Let see how this can be best solved :)

**Comment by zolotov** [comment]
@F21 directory-type run configuration just runs `go test ./...`. How do you avoid `vendor` directory testing while running tests from terminal (e.g. on CI)?

**Comment by dlsniper** [comment]
@zolotov the recommended way is: ` go test $(go list ./... | grep -v /vendor/) `

**Comment by F21** [comment]
@zolotov I am currently using [glide](https://github.com/Masterminds/glide) as my package manager, so it provides a `glide novendor` command which works out the arguments to pass to `go test`.

The problem is that on Windows, the Windows shell does not understand `$(...)` for command expansion, so I have to use the Mingw64 or Git Bash shell.

Unfortunately, that means I can't simply set `$(glide novendor)` as the `go tool arguments` inside the IDE, because Windows can't process `$(...)`.

**Comment by radamsfc** [comment]
Wondering if a generic exclude solution is required as similar issue here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2412

**Comment by dlsniper** [comment]
@radamsfc et all: This is a go tool problem, please follow the discussion: https://github.com/golang/go/issues/11659 A cross-platform solution (Linux, Mac and Windows) has to be found / proposed for this to be solved.

**Comment by radamsfc** [comment]
Great - thanks for the redirect!

**Comment by zolotov** [comment]
relates to #2412

**Comment by s7anley** [comment]
Hi @zolotov, any update on this issue? Is there some workaround, how can I execute `$(go list ./... | grep -v /vendor/)` instead of `./...` ?

**Comment by zolotov** [comment]
@s7anley nope

**Comment by dlsniper** [comment]
@sbrady please understand that the solution you proposed is not cross-platform (Windows won't work). Please address this on the mailing list for Go

**Comment by dlsniper** [comment]
If anyone is using Windows, can you please test this following line and report if it's working for you?
```
 for /f "" %G in ('go list ./... ^| find /i /v "/vendor/"') do @go test %G
```
It should run the test utility against all packages except the vendor directory.
Thank you.

**Comment by itcreator** [comment]
We can be able to add custom parameter (for example `$(glide novendor)`) between `test` and `-v`
src/com/goide/runconfig/testing/GoTestRunningState.java:81

or modify lines 81 and 82

```
executor.withParameters("test", "-v");
executor.withParameterString(myConfiguration.getGoToolParams());

```
Somebody who have installed java and IDE let's do it ))

**Comment by itcreator** [comment]
modify to 
```
executor.withParameters("test");
executor.withParameterString(myConfiguration.getGoToolParams());
executor.withParameters("-v");
```

**Comment by bt** [comment]
Any update on this?

I'm trying to get this to work with my IntelliJ but can't seem to work out specifically which box or setting I should put `$(glide novendor)` into.

I'm also using `glide` for dependency management.

**Comment by mcandre** [comment]
+1

**Comment by kolkov** [comment]
This worked for me on windows 10, thanks!
How to setup go/tests in our plugin with this?
`for /f "" %G in ('go list ./... ^| find /i /v "/vendor/"') do @go test %G`

**Comment by thrawn01** [comment]
I have also run into this issue, I have several projects with many sub packages. Running each sub package in a separate test configuration really sucks =(.

**Comment by dlsniper** [comment]
@thrawn01 please make sure you let the Go team know about this: https://github.com/golang/go/issues/19090

**Comment by davidpope** [comment]
Agreed that the Go team should fix globbing per the issue you linked, but is there no way to edit the command that Gogland/IntelliJ runs when you right-click and select "Run all in <dirname>"?  That would solve this and potentially other unrelated issues.

**Comment by vroldanbet** [comment]
Is there any workaround for this?

**Comment by ryanwalls** [comment]
Looks like go 1.9 will exclude the vendor folder when using `./...`.  See https://go-review.googlesource.com/c/38745
