### ISSUE TITLE
Find usages doesn't work in IDEA 16 EAP for project SDK

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2368]
- Plugin version (or commit hash): 0.11.1155
- IDE name and version: IntelliJ IDEA (Minerva) IU-144.4199.23
- Java version: JRE: 1.8.0_76-release-b19 amd64 / JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: KUbuntu 15.10

- What are you trying to do?
Find usages in a project for a constant.

- What would you expect to happen?
See the usages past the project files.

- What happens?
I can't get the usages show for libraries of the project anymore.

Your issue description goes here.
I've setup a project to have no Go libraries and point it at the Go SDK itself. As the Go SDK was needed to work on some of the features, I configured the Go SDK for the project to be the same as the project. In turn this proved to prevent the option to use the `Find usages` functionality to display matches for what I'm searching that are in the SDK. I can't find any option in those provided by IDEA 16 to allow me to search in all the project, SDK included. See below for a screenshot.

Do you think I should open something against IDEA itself? Or there's a change in the `Find usages` API which the plugin needs to adapt for?

![snapshot111](https://cloud.githubusercontent.com/assets/607868/13411309/ae1934e2-df3c-11e5-8ef6-21125f3c02e4.png)

Thank you.

**Comment by zolotov** [comment]
Just follow the instructions and change search scope

No usages found in Project Files
60 usages are out of scope 'Project Files'
Find Options... Ctrl+Alt+Shift+F7

**Comment by dlsniper** [comment]
@zolotov I've tried the options there but I still couldn't make this work. Maybe it's a problem with the way the project is setup?

- project home dir: `/home/florin/IdeaProjects/go`
- SDK dir: `/home/florin/IdeaProjects/go`

**Comment by zolotov** [comment]
What scope did you try?

**Comment by zolotov** [comment]
And yes, it's not the best project configuration it's better to follow go suk building instructions and use separate go sources and go-bootstrap sdk sources

**Comment by dlsniper** [comment]
@zolotov I've tried `Project files`, `Project production files`, `Module "go"`. And you are right, I should use go 1.4 as an SDK for this. That solved the issue, thank you! Should I close this?

**Comment by zolotov** [comment]
Yes, I think it's not relevant issue. Also I believe Production And Libraries scope should work because project files in described configuration is libraries

**Comment by dlsniper** [comment]
There's no more `Production and Libraries` scope in IDEA 16 (or I can't find it in the options). In IDEA 15 that's what I would usually use.

**Comment by dlsniper** [comment]
Unfortunately for my project this looks different:
![snapshot112](https://cloud.githubusercontent.com/assets/607868/13444027/3ddb8f86-e004-11e5-9957-f2e711333ce3.png)
