### ISSUE TITLE
File that starts with underscore causes warning that it doesn't match target system

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2369]
Files that start with an underscore cause a warning, e.g. if you are editing a file called "_foo.go" you will see a yellow warning "_foo.go doesn't match to target system"
It's useful to have files that start with underscore because they are ignored by go build, they can be used as templates for code generation, etc.

**Comment by dlsniper** [comment]
Thanks for reporting.

If the `_foo.go` file is ignored by the `go build` tool then I guess the plugin should ignore it as a data source for completion as well (since it's not going to be present at compile time in the sources).
And ofc, it shouldn't generate a warning related to the build system.

**Comment by bits01** [comment]
Makes sense. I use it as a template to generate some Go structs from C structs using "go tool cgo -godefs _foo.go > foo.go". I do like that syntax highlighting works on it because it's valid Go code. After I run the command to generate the real foo.go file I do end up with syntax errors in both files because there will be duplicate functions and structs. This builds just fine of course because _foo.go is ignored, it's just a visual problem in the IDE.

But in general if you have a file foo_linux.go for example and you are modifying it in the IDE on a Mac set to generate darwin code, why have that warning at all? It prompts to "Open target system settings", but I don't want to change the platform I compile for, I just want to be able to edit the file on a different platform. It seems to me that it's trying to be too smart. Maybe others like the warning though.

**Comment by zolotov** [comment]
Hi @bits01,

I'm not sure I understand the issue. What exactly are you suggesting?

>  I do like that syntax highlighting works on it because it's valid Go code

Syntax highlighting is there. What exactly are you missing?

>  After I run the command to generate the real foo.go file I do end up with red syntax errors in both files because there will be duplicate functions and structs.

Duplicates #2100

> It prompts to "Open target system settings", but I don't want to change the platform I compile for, I just want to be able to edit the file on a different platform.

Edit the file if you want, IDE doesn't forbid to edit it, IDE just warns you that the file doesn't participate in resolving/completion and IDE cannot validate it.

**Comment by zolotov** [comment]
Is this still actual? @bits01 do you have any suggestions about this issue?

**Comment by bits01** [comment]
Yes, it still behaves the same way. As for suggestions ... change it so that files that start with _ are simply ignored and the IDE doesn't display any warnings for them or considers functions defined in them as duplicates of identical functions defined in other files in the same package, while it still recognizes them as valid .go files that can be edited, with syntax highlighting, etc. (like it correctly does today).

**Comment by zolotov** [comment]
> _ are simply ignored and the IDE doesn't display any warnings for them or considers functions defined in them as duplicates of identical functions defined in other files in the same package

It was done in nightly recently. Please try it and give me a feedback about how it works for you

**Comment by bits01** [comment]
Just tried build .1288, it warned me that the file will be ignored, clicked "Do not show again" and it works as expected. Thank you for fixing it.
