### ISSUE TITLE
Plugin not available on IDEA 145.184.1

### ISSUE THREAD

**Issue by antonikonovalov** [go-lang-plugin-org/go-lang-idea-plugin#2370]
IntelliJ IDEA (Minerva) IU-145.184.1
Build #IU-145.184, built on March 1, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Mac OS

- What are you trying to do?
open go project

- What would you expect to happen?

I am update eap to next and restart

- What happens?
plugin does't work and not see plugin repo after update eap

![2016-03-02 11 02 06](https://cloud.githubusercontent.com/assets/1614346/13454150/3eb66914-e066-11e5-9383-01c89f2867b2.png)
![2016-03-02 11 04 09](https://cloud.githubusercontent.com/assets/1614346/13454198/87df6172-e066-11e5-8d15-c631ce779126.png)

**Comment by dlsniper** [comment]
As @zolotov said in a previous comment: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2325#issuecomment-179706757

> We have a lag between IDEA EAP release and building plugin for new EAP. So if you strongly depend on go-lang plugin please avoid upgrading to the new IDEA EAP at least for a one day after it's released.
