### ISSUE TITLE
Exported functions marked as unused

### ISSUE THREAD

**Issue by fgblomqvist** [go-lang-plugin-org/go-lang-idea-plugin#2374]
- Plugin version (or commit hash): 0.11.1162
- IDE name and version: IDEA 16 EAP

Currently, alI exported functions (starting with a capital letter) that are not used within a library itself, are marked as unused. This seems odd to me. Most exported functions in a library are never used within the library itself, but I think it is wrong to mark them as unused since they are not primarily meant to be used withing the library.

**Comment by dlsniper** [comment]
@fgblomqvist there are a few issues:

- how should the plugin determine if you are working on a library or on a application?
- does disabling this inspection not work for you? Should the plugin rather have an option for this inspection to allow unused exported functions?
- do the library not have an example / tests to use the function?

Thanks.

**Comment by fgblomqvist** [comment]
1. To me, it seems like it doesn't matter what you are working on. If you are writing function names with a capital first letter, then they become available to whoever imports your app/lib. In other words: if you are writing an application, you might want to use lower case first letter if you want to have the unused function inspection.

2. Disabling it also removes all notifications for unused non-exported functions, which I believe could be useful to know about. **An option to allow for unused exported functions seems like the best way to solve this.**

3. I discovered this early on in my adventures with go, so no tests had been written yet. But you are right in that sense, a test should be executing it.

**Comment by dlsniper** [comment]
Ok, I guess it does make sense to add a flag for the inspection. @zolotov / @ignatov what do you think? Is there any example of how to add an option to an inspection?
