### ISSUE TITLE
Improve highlighting on strings that have invalid escape seqences

### ISSUE THREAD

**Issue by mackeyja92** [go-lang-plugin-org/go-lang-idea-plugin#2375]
- Plugin version (or commit hash): 0.10.1164
- IDE name and version: PyCharm
- Java version: Java 8 update 73
- OS name and version:  OSX

- What are you trying to do? 

I am trying to use a large bash command within a string that contains an invalid escape sequence. At first I thought just the syntax highlighting was broken from the string.

- What would you expect to happen?

Some sort of highlighting of the broken escape sequence instead of all highlighting breaking.

- What happens?

Most highlighting breaks.

Broken
```go
cmd := "ip ro | grep default | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])'"
out, err := exec.Command(cmd).Output()
```

Fixed
```go
cmd := "ip ro | grep default | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])'"
out, err := exec.Command(cmd).Output()
```

**Comment by ignatov** [comment]
Duplicates #2217
