### ISSUE TITLE
Update wiki with more detailed instructions for debugging with Delve in IntelliJ (on Windows)

### ISSUE THREAD

**Issue by trpedersen** [go-lang-plugin-org/go-lang-idea-plugin#2377]
- Plugin version (or commit hash): 0.10.1164
- IDE name and version: Idea 15.0.4
- Java version: 1.8
- OS name and version: Windows 10

- What are you trying to do? Get Delve debugging tests, main, etc. using the plugin on Windows.

Now that Delve is now available on Windows, I'm trying to get it working with the golang Idea plugin. Unfortunately the instructions in the wiki aren't very clear on what is needed to set up debugging with Delve. Would someone update the instructions with more detailed information about setting up the IDE for debugging tests & main() code with Delve please?

BTW: does the Windows version of the plugin not have debugging with Delve enabled? Digging around the net, it seems the run/debug configurations screens on my PC don't have the same options as other OSes...?

I've managed to get Delve debugging working with Visual Studio Code - by I'd prefer to keep using IntelliJ - much better IDE!

Great job with the plugin -thanks!

Tim.

**Comment by zolotov** [comment]
Hi Tim,

> Unfortunately the instructions in the wiki aren't very clear on what is needed to set up debugging with Delve. 

That's because you shouldn't do anything to set up debugging with delve in IDEA. You just press debug button for your run configuration and that's all. As for debugging tests see #1855

**Comment by hectorj** [comment]
Then there may be a bug (or something not clear).

Here are my specs:

> PHPstorm 10.0.3
> Plugin version: 0.10.1164
> Delve version: 0.9.0-alpha
> OS: Ubuntu 15.04
> java version "1.7.0_95"
> OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
> OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)


And when I click on Debug > my config (which is an application config), another contextual menu appears with 2 choices, "Run" and "Edit".

"Run" just runs the program normally, without debugging (I put some breakpoint on the first line of my main() and it doesn't stop, + the "run" tab displays the normal command "/usr/local/go/bin/go run [...]")

"Edit" brings me to the configuration edit window, as expected.

How/when does the plugin detect if and where delve is installed?

**Comment by dlsniper** [comment]
@hectorj the plugin bundles delve. Also, you must be on a 64 bit OS for it to work. And you have to have a Go Application configuration type (for now). If all of the above conditions are met then the Debug option should be available as well.

**Comment by hectorj** [comment]
I meet all these conditions, but the Debug button is grey and using "Run" > "Debug" does what I described previously.

> 64 bit OS

```
$ uname -a
Linux hjusforgues-Vostro-5470 3.19.0-51-generic #58-Ubuntu SMP Fri Feb 26 21:22:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I'm gonna test again with a dummy project and with a fresh version of IDEA community, will report back.

Sorry I may have hijacked this thread, not sure if my issue is the same as @trpedersen 's

**Comment by hectorj** [comment]
> I'm gonna test again with a dummy project and with a fresh version of IDEA community, will report back.

It worked... Not sure which config in my PHPStorm is blocking it

Working config:
> IDEA 15.0.4
> Plugin Version: 0.10.1164 (unchanged)
> Everything else unchanged

**Comment by hectorj** [comment]
It works with my PHPStorm after recreating the project

@trpedersen : can you try that?

**Comment by trpedersen** [comment]
I got things working OK now - not sure what the cause was; anyway, reinstalling things seemed to fix it. Debugging programs with main() functions works - though I'm hanging out to be able to debug tests when the plugin authors get around to it :)

I'll close this issue.
