### ISSUE TITLE
Error message when trying to upload Go plugin to Webstorm

### ISSUE THREAD

**Issue by pdgme** [go-lang-plugin-org/go-lang-idea-plugin#2378]
- Plugin version (or commit hash): Go-0.11.1165.zip
- IDE name and version:
- Java version:
- OS name and version: OS X Yosemite 10.10.5
- What are you trying to do?

Upload Golang plugin into webstorm using this plugin https://plugins.jetbrains.com/plugin/5047?pr=idea&offset=30&max=15

- What would you expect to happen?

Webstorm to upload the golang plugin

- What happens?

Error message: error message 'plugin 'Go' is incompatible with this installation.'
![screen shot 2016-03-06 at 12 34 01 pm](https://cloud.githubusercontent.com/assets/17211986/13555868/ad9f2b8c-e399-11e5-8325-8ae2b114f979.png)
 (screenshot attached)

Your issue description goes here.

My issue is it's a brand new install of webstorm (2 days ago). Going through Linda.com Go training course and following the steps outlined by instructor. But keep getting error message 'plugin 'Go' is incompatible with this installation.'

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Hi,

Please uninstall the plugin then simply search for it in the plugin repository using the searching functionality builtin the IDE, it should work.
If it doesn't, please provide the IDE version (` IDE name and version: ` point from the issue template).

Thank you.

**Comment by pdgme** [comment]
Worked like a charm. Thank you very much. I appreciate your speedy help.

My best to you and yours,

Peter David Gustafson
pdgseo.com <http://www.pdgseo.com/category/case-studies>
​Cell: 1-207-602-0299
Skype: peterdavidgustafson44
LinkedIn profile <https://www.linkedin.com/in/peterdavidgustafson>

**Comment by dlsniper** [comment]
You're welcome. If you need more frequent updates, you can see this information from the README: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds Have fun!
