### ISSUE TITLE
FR: "Implement Interface" intention action

### ISSUE THREAD

**Issue by deadok22** [go-lang-plugin-org/go-lang-idea-plugin#2379]
In order to implement an interface, one has to:
1) go to interfaces' signature, 
2) copy method declarations from it, 
3) paste them to the original file, 
4) prepend each of the declarations with "(self *StructName)",
5) and, finally, implement the methods.

First four steps can be done by the plugin

**Comment by dlsniper** [comment]
Duplicates https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1568
