### ISSUE TITLE
Multiple "Package to import" dialogs pop up on top of each other

### ISSUE THREAD

**Issue by deadok22** [go-lang-plugin-org/go-lang-idea-plugin#2381]
![packagetoimport](https://cloud.githubusercontent.com/assets/1259620/13562763/2f8d1402-e47f-11e5-9ee0-bb603d58f602.png)

**Comment by deadok22** [comment]
Also, they keep popping up and you can't just ignore them and continue editing. Very annoying.

**Comment by dlsniper** [comment]
That looks like an potential IDE bug. Please add all the missing information from your issue (the template appears when you open a new issue or you can see it here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/ISSUE_TEMPLATE.md) 

Thank you.
