### ISSUE TITLE
debug button disabled after update on 2016-03-07 to 0.10.1164

### ISSUE THREAD

**Issue by dprime** [go-lang-plugin-org/go-lang-idea-plugin#2382]
- Plugin version (or commit hash): 0.10.1164
- IDE name and version: intellij idea 15.0.4
- Java version: 8u45
- OS name and version: win7 ultimate x64

I allowed intellij to automatically apply an update to 0.10.1164 and now I can't debug. The button is greyed out as it was before the previous release when delve for windows was not enabled and distributed with the go plugin. 
Any ideas?

**Comment by dprime** [comment]
This appears to be on new run configs. Existing run configs with a debug run profile still allow me to run the debug build via delve.

**Comment by dprime** [comment]
D'oh! Looks like you can't debug "single file" execution profiles but you can with "application" profiles. Is this intentional?

**Comment by dlsniper** [comment]
Yes, this is intentional. Only Go application run configuration s are debugable as of now. Sorry for the inconvenience.
