### ISSUE TITLE
question about features

### ISSUE THREAD

**Issue by SlevinT** [go-lang-plugin-org/go-lang-idea-plugin#2385]
Everything with the package so far has gone well. Is there plans to have the plugin auto indent and clean files on saves?

**Comment by dlsniper** [comment]
Hi, if you are referring to the plugin following the formating of gofmt then yes, there are plans to support this someday, see: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1215
Meanwhile you can use gofmt / goimports and bind them to a shortcut which will save then format the file using gofmt / goimports.
Does this answer the question?

**Comment by zolotov** [comment]
closing due to lack of feedback
