### ISSUE TITLE
Resolving issues when importing a package and fetching it from the IDE

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2387]
- Plugin version (or commit hash): 0.11.1180
- IDE name and version: IntelliJ IDEA (Minerva) IU-145.256.33
Build #IU-145.256, built on March 10, 2016
- Java version: JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: KUbuntu 15.10

- What are you trying to do?
I'm trying to use a third party package

- What would you expect to happen?
I'm expecting to have the autocompletion / resolving working on a piece of code
 
- What happens?
The correct symbols are flagged as unresolved

Your issue description goes here.

I've pasted the following code:

```go
package main

import "github.com/google/go-github/github"

func main() {
	client := github.NewClient(nil)
	_, _, _ := client.Organizations.List("demo", nil)
}
```

Then I've let the IDE fetch the package using go get as I didn't had it in my GOPATH.
After the fetching finished, the IDE was marking `List()` as an unresolved symbol. However upon clearing the cache everything went back to normal.

**Comment by zolotov** [comment]
Cannot recreate :(

**Comment by dlsniper** [comment]
I'll try and recreate it this weekend, maybe I missed something from the steps. Thanks

**Comment by dlsniper** [comment]
I can't replicate this for now. Closing it until further changes.
