### ISSUE TITLE
Failed to get nightly version

### ISSUE THREAD

**Issue by ElvizLai** [go-lang-plugin-org/go-lang-idea-plugin#2388]
- Plugin version (or commit hash):
0.10.1164

- IDE name and version:
IDEA 15.0.4 143.2287

- Java version:
1.8.0._40

- OS name and version: 
OS X 10.11.3

- What are you trying to do?
Get lastest nightly build. Only get alpha build(0.10.xxx) even I use nightly channel, but I except 0.11.xxx version

- What would you expect to happen?
Get nightly version 0.11.xxx

- What happens?
![qq20160313-1 2x](https://cloud.githubusercontent.com/assets/501861/13726726/9836f02e-e90f-11e5-9fe8-a0186d960a73.png)

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by ignatov** [comment]
The second number means "platform version", in your case it should be 10 because you're using Idea 15. For Idea 2016.1 EAP it should be 11.

**Comment by ignatov** [comment]
@dlsniper Please document it somewhere.

**Comment by dlsniper** [comment]
@ignatov do you think we should rename the 0.11.* releases as 0.2016.1.*? Not sure if that's supported by the platform but would allow users to follow the versioning of the platform as well as the plugin.

**Comment by dlsniper** [comment]
I've pushed this commit https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/e5f6544b72bfbe8ed00b8502e545004e11662c3a to update the docs.

**Comment by ignatov** [comment]
@dlsniper I thought about it, we can do it accordingly lately.
