### ISSUE TITLE
Inspection for map values just broke.

### ISSUE THREAD

**Issue by vburenin** [go-lang-plugin-org/go-lang-idea-plugin#2390]
- Plugin version (or commit hash): 0.10.1189
- IDE name and version: 
![image](https://cloud.githubusercontent.com/assets/4350891/13825385/8b282102-eb6f-11e5-975e-c49a466a98b1.png)

- What happens?
Map value type inspection stopped working.

Example: https://github.com/vburenin/nsync/blob/master/namedoncemutex.go

Issue:
![image](https://cloud.githubusercontent.com/assets/4350891/13825437/d0c4d336-eb6f-11e5-95b6-962a8db6f540.png)

**Comment by zolotov** [comment]
Please try to invoke `File | Ivalidate Caches`

**Comment by vburenin** [comment]
It seems like it was related to the vendor folder I excluded from the project. closing.

**Comment by vburenin** [comment]
Yah, I cleared cache.

**Comment by zolotov** [comment]
> It seems like it was related to the vendor folder I excluded from the project. closing.

Interesting, could you give more details on that? I've cloned `nsync` project and cannot recreate the problem

**Comment by dlsniper** [comment]
I'll update shortly

**Comment by dlsniper** [comment]
@zolotov to replicate this:

- go get github.com/dlsniper/u
- open the project
- navigate to vendor/github.com/vburenin/nsync/namedoncemutex.go

I have Go 1.6 as SDK and vendor is set to Default for SDK (enabled)

**Comment by dlsniper** [comment]
Actually turns out the project was configured to use the Go SDK but the module referenced an invalid, deleted, Go SDK. When I changed the module SDK to use the project SDK this was recognized again. I'll close this for now as well as I can't replicate it. Sorry for noise.
