### ISSUE TITLE
Autocomplete not importing packages

### ISSUE THREAD

**Issue by F21** [go-lang-plugin-org/go-lang-idea-plugin#2393]
- Plugin version (or commit hash):  0.10.1189
- IDE name and version: PHPStorm 10.0.3
- Java version: Java 8 Update 73
- OS name and version: Windows 10 64-bit

- What are you trying to do?
When typing something like `net.P` and selecting `net.ParseIP()` from the autocomplete dropdown, it does not import the `net` package.

- What would you expect to happen?
Selecting something from the autocomplete dropdown should import the appropriate package.

- What happens?
The package is not imported.

![tmp](https://cloud.githubusercontent.com/assets/2263040/13832637/2387e636-ec32-11e5-91b6-a3e9cdcb57ef.gif)

**Comment by dlsniper** [comment]
Can you please post screenshots of: 
- File | Project Structure | Project
- File | Project Structure | Modules | (name of the Go module) | Dependencies
- File | Settings | Languages & Frameworks | Go | * (all pages there)

Also, which Go version do you use?

Thank you.

**Comment by F21** [comment]
I am using Go 1.6.

I don't have a `File | Project Structure` in PHPStorm.

Here are the screenshots for the plugin:
![1](https://cloud.githubusercontent.com/assets/2263040/13832868/5aa9d7da-ec34-11e5-84f6-898aa5d71501.png)
![2](https://cloud.githubusercontent.com/assets/2263040/13832869/5aaf1d3a-ec34-11e5-9131-027dd2d7c496.png)
![3](https://cloud.githubusercontent.com/assets/2263040/13832870/5ab15352-ec34-11e5-871d-629fb1839c22.png)
![4](https://cloud.githubusercontent.com/assets/2263040/13832871/5ab62b3e-ec34-11e5-8a56-0c52cd4e9393.png)

**Comment by dlsniper** [comment]
@F21 I'm so sorry, I've missed is PHPStorm. I can indeed confirm the issue. Thank you for reporting!

**Comment by zolotov** [comment]
Should be fixed in 0.10.1199, thanks for report
