### ISSUE TITLE
PHPStorm 10.0 doesn't recognize go sdk location

### ISSUE THREAD

**Issue by chuyskywalker** [go-lang-plugin-org/go-lang-idea-plugin#2394]
- Plugin version (or commit hash): 0.10.749
- IDE name and version: PHPStorm 10.0 (143.381)
- Java version: 1.8.0_66
- OS name and version: Windows 10
- What are you trying to do? Add the Go SDK
- What would you expect to happen? It finds the version
- What happens? It reads, in red "N/A" after selecting the `C:\Go` directory

Not much more to add, the plugin doesn't like something and I've got no other output to go on here. The event log doesn't show anything, I'm not getting any errors. Nada.

![2016-03-16 23_15_06-gofiles - c__gofiles - _src_github com_user_hello_hello go - phpstorm 10 0](https://cloud.githubusercontent.com/assets/131800/13837912/0e7241c0-ebcd-11e5-891d-a409bd2c86ae.png)

Is go 1.6 too new perhaps?

**Comment by F21** [comment]
Have you tried upgrading to PHPStorm 10.0.3? I don't see this problem with 10.0.3.

**Comment by zolotov** [comment]
0.10.749 is old and doesn't support Go 1.6, please follow the @F21's advice and upgrade php storm and plugin.
