### ISSUE TITLE
WebStorm / IDEA 2016.1 is not supported

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [go-lang-plugin-org/go-lang-idea-plugin#2395]
- 0.10.1189
- WebStorm 2016.1

- What happens?
https://s3.amazonaws.com/donnicky_screenshots/2016-03-17_16-14-36_6b3733cc-ab37-4e92-bdff-274738d0905f.png

**Comment by markgoodhead** [comment]
I get essentially the same thing from IntelliJ IDEA Ultimate 16.1 - the plugin says it's not compatible with the current version

**Comment by zolotov** [comment]
Uploaded to nightly channel only. It's not tested enough on 2016.1 versions yet

**Comment by nikolaybobrovskiy** [comment]
Great! Thank you.

**Comment by FGM** [comment]
Same for PhpStorm 2016.1. Any idea when it might move from the nightly to regular ?

**Comment by dlsniper** [comment]
@FGM as Alexander said, it's not tested enough to be on stable. If you'd like to see it faster on stable, please help us out and test the nightly release. Thank you!

**Comment by nbgo** [comment]
As to testing. The only problem I have met is dissappeared contexts for custom live templates: https://s3.amazonaws.com/donnicky_screenshots/2016-03-18_15-42-06_fd2d7c88-4fba-4ec0-b400-9b152b89d45f.png
I had to set manually again after plug-in was updated.

**Comment by zolotov** [comment]
We found some critical issues with 0.11.2000 build so 0.11.1197 is reuploaded to be compatible to IDEA 2016.1
