### ISSUE TITLE
Add Go educational plugin features

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2396]
I've seen the Kotlin one: http://blog.jetbrains.com/kotlin/2016/03/kotlin-educational-plugin/ and I wonder if this could be something doable for Go as well. I don't know how easy would it be to create such a plugin but it would be cool to have at some point something that takes the exercises on tour.golang.org and moves them to the IDE.

**Comment by zolotov** [comment]
Please create such issue if you're really going to implement them. Otherwise they will be pollute issues pool for the next five years

**Comment by dlsniper** [comment]
Agreed. I don't plan to work on this in the near future, that's true, I want to get working on inspections again as soon as possible. I'll label it as up for grabs and if someone else wants to pick it up and work on it I guess we can reopen/revisit this
