### ISSUE TITLE
Create chat channel for go-lang-idea-plugin

### ISSUE THREAD

**Issue by asampal** [go-lang-plugin-org/go-lang-idea-plugin#2397]
It would be nice to have a place to chat about this plugin on [gtter.im](https://gitter.im), or, if you prefer, on Slack.

**Comment by dlsniper** [comment]
If only it wouldn't be linked in readme :P https://gitter.im/go-lang-plugin-org/go-lang-idea-plugin

**Comment by asampal** [comment]
Hah! Who looks at those tags? Seriously I'm blind to small graphics like that.
