### ISSUE TITLE
Reproducible excessive CPU usage on some source files

### ISSUE THREAD

**Issue by osklyar** [go-lang-plugin-org/go-lang-idea-plugin#2398]
- Plugin version (or commit hash): 0.11.1200
- IDE name and version: IntelliJ CE 2016.1, IntelliJ 15.0.4
- Java version: 1.8.0_66-b17)
- OS name and version: OSX 10.11.3 (15D21)

- What are you trying to do?
Edit go source files.

- What would you expect to happen?
File is opened and analysed quickly with low to moderate CPU usage -- behaviour normally observable.

- What happens?
Opening or making any change into one particular file, shown below, consistently causes an ultra-high CPU usage often leading to false positives in detecting erroneous code (e.g. function calls are reported to have wrong number of arguments even though this is not the case). This does not happen on other files. The issue confirmed on the latest IntelliJ IDEA CE 2016.1 and on the latest 15.0.4. Here are two screenshots with the activity monitor: one with a file that does not cause any issue, the other one with the file causing issues (the gauge going up for the second time corresponds to a tiny change made in code):

<img width="1627" alt="screen shot 2016-03-17 at 22 34 31" src="https://cloud.githubusercontent.com/assets/7482031/13862222/317a3d10-ec92-11e5-96e4-24066b5f6be8.png">
<img width="1514" alt="screen shot 2016-03-17 at 22 35 30" src="https://cloud.githubusercontent.com/assets/7482031/13862227/37baedc8-ec92-11e5-8b59-ee857bc385bd.png">

This is the (unfinished) code that triggered the CPU usage:
```go
package slf

import (
	"strings"
	"fmt"
)

type Level int

const (
	Debug Level = iota
	Info
	Warn
	Error
	Panic
	Fatal
)

func (l *Level) MarshalJSON() ([]byte, error) {
 return nil, nil // TODO
}

func (l *Level) UnmarshalJSON(data []byte) error {
	s := string(data)
	switch strings.ToLower(s) {
	case "debug":
		*l = Debug
	case "info":
		*l = Info
	case "warn":
		*l = Warn
	case "error":
		*l = Error
	case "panic":
		*l = Panic
	case "fatal":
		*l = Fatal
	default:
		return fmt.Errorf("slf: unknown level %v", s)
	}
	return nil
}
```

**Comment by dlsniper** [comment]
Awesome! I can also confirm this on Ubuntu / 0.11.1197 plugin. Thank you!

**Comment by osklyar** [comment]
I found my issue: the problem is caused by the naming of constants Error, Fatal and Panic cause the excessive load. Renaming these three in e.g. LevelError, LevelFatal, LevelPanic or removing them all together solves the issue.

**Comment by zolotov** [comment]
Known issue, it's better to avoid using common names for exported variables/constants/functions or disable corresponding Unused inspections. I optimized them a little (will be available in tommorow nightly) but they still will lead to high cpu usage

**Comment by osklyar** [comment]
Cool, thanks for the tip.

**Comment by dprime** [comment]
Which inspections can be disabled to prevent this? I suffer from this in a few of my sources, too.

**Comment by dlsniper** [comment]
@dprime like @zolotov said, one of the inspections that might be the issue is: `Unused inspections`. However, this might not be the case for you. Please try and disable all of them and then enable them one by one until you find the culprit, then report it to us, with some code sample to reproduce it (maybe even with a performance snapshot, see this: https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems) and then we can use this information to maybe improve / fix the issue. Thank you!

**Comment by dprime** [comment]
@dlsniper Thank you, I will do.
