### ISSUE TITLE
Plugin not updating?

### ISSUE THREAD

**Issue by chriswalz** [go-lang-plugin-org/go-lang-idea-plugin#2402]
- 10.749:
- Webstorm 11:
- 8:
- Mac OSX Yosemite: 

- What are you trying to do? Update plugin version

- What would you expect to happen? Plugin to update daily

- What happens? I don't appear to receive nightly versions of the plugin. I would like an updated version that supports go 1.5 or 1.6.

**Comment by dlsniper** [comment]
To get the nightly updates, have you followed the instructions in the README: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds ?

**Comment by chriswalz** [comment]
Woops forgot to mention that I followed the instructions in the README. Maybe I did it wrong?

**Comment by dlsniper** [comment]
Do you have WebStorm 11 or WebStorm 11.0.3? If it's the former, please upgrade to the later. Thanks.

**Comment by chriswalz** [comment]
Thanks, I upgraded to 2016.1 and that worked!

**Comment by dlsniper** [comment]
I'm glad it worked. Enjoy coding.
