### ISSUE TITLE
Valid methods in gophercloud being highlighted in red 'Unresolved Reference'

### ISSUE THREAD

**Issue by chongzhang** [go-lang-plugin-org/go-lang-idea-plugin#2405]
- Plugin version (or commit hash): 0.11.1203
- IDE name and version: IntelliJ IDEA 2016.1 Build #IC-145.258, built on March 17, 2016
- Java version:1.8.0_45
- OS name and version:  Mac OS X 10.11.1
- Go version - 1.6

- What are you trying to do?
Writing a Go program to use https://github.com/rackspace/gophercloud
The program executes fun by "go run" with correct env setup. But the editor highlights the method pager.EachPage in red with "Unresolved Reference".

- What would you expect to happen?
No error, and methods show up in code completion list.

- What happens?
The valid method EachPage() is highlighted in red with "Unresolved Reference" error. 
Also the code completion on 'pager' only shows the fields Headers and Err.

Your issue description goes here.
Please be as detailed as possible

```go
package main

import (
        "fmt"
        "github.com/rackspace/gophercloud"
        "github.com/rackspace/gophercloud/openstack"
        "github.com/rackspace/gophercloud/openstack/compute/v2/flavors"
        "github.com/rackspace/gophercloud/pagination"
)

func main() {
        opts, _ := openstack.AuthOptionsFromEnv()
        provider, _ := openstack.AuthenticatedClient(opts)
        client, _ := openstack.NewComputeV2(provider, gophercloud.EndpointOpts{
                Region: "east",
        })
        fopts := flavors.ListOpts{}
        pager := flavors.ListDetail(client, fopts)
        pager.EachPage(func(page pagination.Page) (bool, error) {
                flavorList, _ := flavors.ExtractFlavors(page)
                for _, f := range flavorList {
                        fmt.Println("flavor: ", f)
                }
                return true, nil
        })
}
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Hi @chongzhang, thanks for your report.
Unfortunately I can't replicate this with the sample code.
Can you please add the following details:
- the project path
- the GOATH
- is `gophercloud` in the vendor directory? if so, what is the setting for `Settings | Languages & Frameworks | Go | Project Settings | Enable Vendoring`
- the settings in `Settings | Languages & Frameworks | Go | Go libraries`?

**Comment by chongzhang** [comment]
Hi @dlsniper 

Thanks for your help.  I updated the project with "Change module type to Go and reload project" and that error is gone.

But just to provide you the details for the reference:
- the project path: `/Users/zchong001c/gocode/src/foo`
- the GOATH: `/Users/zchong001c/gocode`
- is gophercloud in the vendor directory? if so, what is the setting for Settings | Languages & Frameworks | Go | Project Settings | Enable Vendoring
No. It's in `gocode/src/github.com/rackspace/gophercloud/`
_And I don't see the "Enable Vendoring" option in the above setting. The "Project Settings" is empty - "Nothing to show"_

- the settings in Settings | Languages & Frameworks | Go | Go libraries?
"Global libraries" is `/Users/zchong001c/gocode`. "Use GOPATH.." is unchecked.
"Project libraries" is empty.

**Comment by dlsniper** [comment]
Happy to know it worked. I'll close this.
