### ISSUE TITLE
Run tests not working in WebStorm 2016.1

### ISSUE THREAD

**Issue by jhngrant** [go-lang-plugin-org/go-lang-idea-plugin#2406]
- Plugin version (or commit hash):
  0.11.1197
- OS name and version: 
  Windows 10 64, Go 1.6

- What are you trying to do?
  Right clicking a Test... function in a test package and choosing Run Test... 

- What would you expect to happen?
  Run the test function as happens in WebStorm 11.0.3. It normally starts something like:

        C:/Go\bin\go.exe test -v crm/migrate/repo/types -run ^Test...$

- What happens?
  Nothing.

**Comment by zolotov** [comment]
Please attach log files (Help | Show logs in <file browser>)

**Comment by jhngrant** [comment]
Hope this helps:
[idea.zip](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/183155/idea.zip)

Let me know if there's anything else I can help with.

**Comment by zolotov** [comment]
Thanks. Will be fixes in the next nightly.

**Comment by jhngrant** [comment]
Thanks Alexander. Impressed by the speed of your response!
