### ISSUE TITLE
Finds no usages in this special case

### ISSUE THREAD

**Issue by gabrielf** [go-lang-plugin-org/go-lang-idea-plugin#2407]
- Plugin version (or commit hash): 0.11.1203
- IDE name and version: IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: OSX 10.11.1

- What are you trying to do?
Find usages of struct method that is not called but passed as a parameter to a function (or method)

- What would you expect to happen?
The usage should be found

- What happens?
When the method, the other method taking the first as a parameter and the actual usage are in separate packages no usages are not found.

Here is a minimal repo that demonstrates the issue: https://github.com/gabrielf/goplugin-usage-bug

Navigate to `handler/handler.go:70` and look for usages. You will find none.

The interesting thing is that you can navigate from usage to implementation but not from implementation to usage for this particular case.

**Comment by zolotov** [comment]
Please try 0.11.1208, I can't recreate the issue there

**Comment by gabrielf** [comment]
Hi, I've upgraded to 0.11.1241 but the issue remains, when on `handler/handler.go:7` show usages yields this error:

![image](https://cloud.githubusercontent.com/assets/137649/14170211/af842492-f72c-11e5-8874-e668ff4a75f8.png)

I use go 1.4.2, can that affect show usages?

**Comment by dlsniper** [comment]
Hi, at least in the sample app you've uploaded, the issue is that your import paths are wrong. They have to be changed from ` import "github.com/gabrielf/go-sandbox/PACKAGE" ` to ` import "github.com/gabrielf/goplugin-usage-bug/PACKAGE" `. Then this will work.

**Comment by gabrielf** [comment]
That was clumsy of me! I've fixed the import path but the problem remain.

![show-usages-bug-lores](https://cloud.githubusercontent.com/assets/137649/14174468/bd4c64d2-f744-11e5-8b9d-41f57f8b01da.gif)

**Comment by dlsniper** [comment]
This is really strange.
How do you create the project? What is the root of the project and what is the root of GOPATH? What values do you have in the Go libraries section?

**Comment by gabrielf** [comment]
Thanks, works like a charm!
