### ISSUE TITLE
"Package to import" popup is too aggressive

### ISSUE THREAD

**Issue by deadok22** [go-lang-plugin-org/go-lang-idea-plugin#2411]
"Package to import" dialog makes it impossible to edit code while you have some unimported things. Whenever you move caret, this dialog pops up and grabs focus.

Why have this dialog at all? There's intention action tooltip already doing what's needed.

**Comment by zolotov** [comment]
@deadok22 could you provide a screencast? I cannot recreate the issue and do not no how it can be possible.

**Comment by deadok22** [comment]
Hm, I can't reproduce it now, too. I'll let you know if I hit it again.

**Comment by zolotov** [comment]
Ok, thanks
