### ISSUE TITLE
Plugin adding double imports due to vendors not being implemented

### ISSUE THREAD

**Issue by biamorton** [go-lang-plugin-org/go-lang-idea-plugin#2419]
- Plugin version (or commit hash):
- IDE name and version: PHP Storm 2016.1
- Java version:
- OS name and version: Windows 10

- What are you trying to do?
Just trying to compile my project but the plugin keeps importing extra stuff because it doesnt recognize the vendors folder.

- What would you expect to happen?
Expect it to realize that i already have the import for what im using from the vendors folder and not try to add extra imports which breaks compile since there are multiple imports for the same thing. this is probably related to issue 1820 where some people are asking for vendor support.

- What happens?
I get my manual import + an extra one that breaks compile... EVERY TIME i try to compile it from cmd line as it auto inserts it on unfocus/save

Have vendors enabled, import something from that folder and use it in the main code. 
Plugin will add a super long import and you wont be able to compile anymore.

**Comment by zolotov** [comment]
Plugin version? Any reproducible code sample? Is vendoring support enabled for project?

**Comment by zolotov** [comment]
closing due to lack of feedback
