### ISSUE TITLE
Code inspection failed on value passed from channel in for-range loop

### ISSUE THREAD

**Issue by hongchaodeng** [go-lang-plugin-org/go-lang-idea-plugin#2421]
- Plugin version (or commit hash):
0.11.1236
- IDE name and version:

IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: MacOSX 10.11

### Problem Description
When I tried to do for-range on channels, code inspection failed on value passed from channel:
![screen shot 2016-03-29 at 9 47 38 pm](https://cloud.githubusercontent.com/assets/920884/14132214/287a5fd2-f5f8-11e5-9a10-2b8bbda7dce0.png)

Watch() returns the following thing
```Go
Watch(...) WatchChan
type WatchChan <-chan WatchResponse
```

However, if I declare it explicitly as follows, it becomes alright:
![screen shot 2016-03-29 at 9 47 57 pm](https://cloud.githubusercontent.com/assets/920884/14132233/6b3d12ba-f5f8-11e5-8ef0-22e4528a54ed.png)

Can anyone help with this? Thanks very much!

**Comment by ignatov** [comment]
Please provide a sample for reproducing.

**Comment by hongchaodeng** [comment]
Sample blew. Thanks for looking into it.\

```Go
package main

import "log"

type sampleType struct {
	a int
}

type sampleChan chan sampleType

func sample() sampleChan {
	return make(chan sampleType, 3)
}

func main() {

	c := sample()
	c <- sampleType{1}
	c <- sampleType{2}
	c <- sampleType{3}
	close(c)
	for t := range c {
		log.Println(t.a)
	}
	log.Printf("Exit!")
}
```

**Comment by hongchaodeng** [comment]
@ignatov 
How can I get the fix?

**Comment by ignatov** [comment]
Here it is https://plugins.jetbrains.com/plugin/download?pr=&updateId=25021
