### ISSUE TITLE
unresolved reference error occured

### ISSUE THREAD

**Issue by liugangnhm** [go-lang-plugin-org/go-lang-idea-plugin#2423]
- Plugin version (or commit hash):0.10.1164
- IDE name and version:idea ce 15.0.4
- Java version:java version "1.8.0_66"
- OS name and version: win7

all code like below will cause `unresolved reference` error

```go
package main

type typ1 struct {
}

type typ2 struct {
	t1 typ1
}

func (t typ1) F() {
	print("t1.F()")
}

func main() {
	t2 := typ2{t1:typ1{}}
	t1 := &t2.t1
	t1.F()
}

```

**Comment by dlsniper** [comment]
That, the error, looks correct as the receiver for the function is not a pointer. I can't remember how Go does this but I think that it will remove the pointer automatically. In this case maybe we could report it as a code smell.

**Comment by liugangnhm** [comment]
Yes, but there should be no error in fact.

**Comment by dlsniper** [comment]
Should this be linked with: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2179 ?

**Comment by mrcook** [comment]
I believe I have another example which falls under this issue. Here also is the code: http://play.golang.org/p/Xn6SePhfhw

![intellij-unresolved-reference](https://cloud.githubusercontent.com/assets/1093101/14158284/97fdadf0-f6cf-11e5-88c6-9e23bd599c5c.png)

I'm using the latest IDEA Ultimate on the latest OSX, using the alpha channel release for the plugin.

**Comment by zolotov** [comment]
@mrcook please file a separate issue with exactly plugin and IDEA versions

**Comment by mrcook** [comment]
Okay, after changing my code to use an array of pointers (`type StoresList []*Store`) I don't get the error any more, so perhaps I don't need to create my own ticket. My apologies for polluting this issue.

**Comment by tuanchauict** [comment]
I also see this error with this example:

```golang
type Foo struct {
	a int
}

type Baz [5]Foo

func foo(){
	b := &Baz{}
	b[0].a = 1 // Unresolved reference 'a'
}

```

Seem like the plugin doesn't recognize second reference via pointer. But this works well: `(*b)[0].a`

**Comment by dlsniper** [comment]
@tuanchauict please open a separate issue and provide this example + additional information as requested in the template. Thank you for your help!
