### ISSUE TITLE
Feature Request: add support for Google AppEngine SDK

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#2425]
- Plugin version (or commit hash): latest nightly
- IDE name and version: IntelliJ Ultimate 2016.1
- Java version:  1.8.0_74
- OS name and version: archlinux 4.1.19-1-lts

- What are you trying to do?
getting autocomplete out of appengine sdk

- What would you expect to happen?
there will be an autocomplete

- What happens?
no autocomplete

Your issue description goes here.
import (
	"appengine"
	"appengine/memcache"
	"appengine/urlfetch"
	"appengine/datastore"
	"appengine/user"
)
```go
Please include a go sample to reproduce the issue
```
https://cloud.google.com/appengine/docs/go/gettingstarted/usingusers

**Comment by dlsniper** [comment]
Go AppEngine SDK is currently supported and working in the plugin, see below:

![snapshot13](https://cloud.githubusercontent.com/assets/607868/14143534/b2a152b6-f683-11e5-867b-1ae973efb348.png)

Have you setup a Go AppEngine SDK or is your project sill using a normal Go SDK?

**Comment by kokizzu** [comment]
Ah I see,

after changing the SDK to `goroot/src` and `gopath` it works fine now :3
