### ISSUE TITLE
IDE freezing

### ISSUE THREAD

**Issue by bionicrm** [go-lang-plugin-org/go-lang-idea-plugin#2430]
- Plugin version (or commit hash): 0.11.1197
- IDE name and version: IntelliJ 2016.1.1 + WebStorm 2016.1.1 (maybe others)
- Java version: 1.8.0_77
- OS name and version: Linux Mint 17.3

- What are you trying to do?
Right-click on the root project directory.

- What would you expect to happen?
The context menu should appear.

- What happens?
The program hangs, memory usage of 'java' shoots to 1.5 GiB and CPU at 104%, eventually crashing.

When I right click on the root project directory, there's a chance that the above will occur. When I encountered this, I started writing a bug report for WebStorm, but as I investigated some more, it appeared that:
- the issue went away when I disabled the Go plugin
- the issue occurs in IntelliJ IDEA 2016.1.1 as well

In this screenshot, the UI has frozen, and the System Monitor is showing 'java' with % CPU used at 104% and (not pictured) now using 1.4 GiB of memory. After a while, the IDE screen blanks out. Here's a screenshot: http://i.imgur.com/UMVC8cl.png

Here's a dump made with `jstack -l <PID of Java>`: https://gist.github.com/bionicrm/37a788a73e1f24018e3b8b639399b92d

This seems to be brand new with 2016.1.1.

**Comment by zolotov** [comment]
Please attach log directory (Help | Show Logs in <file browser>) or make several thread dumps while IDE freezing

**Comment by bionicrm** [comment]
Thanks, I'll get both. Here's 4 Gists of the `jstack -l <PID of Java>` about 5 seconds apart from each other during the freezing: https://gist.github.com/bionicrm/3220b08ebcbf367f050a76d72dd2b659. I've attached my log directory. Here's the logs: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/200656/log.tar.gz

**Comment by zolotov** [comment]
Thanks! Should be fixed in today nightly. Please try 0.11.1253 build, README contains an instruction how to install nightly builds.

**Comment by bionicrm** [comment]
Awesome, thanks. Just updated and everything is working fine.
