### ISSUE TITLE
Regression in plugins parser

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2432]
Hi,

It seems that 0.11.1253 introduced a regression in the parser code (if I understand correctly the error message).
The problem is that in code like this:
```
package main

type Handler func()

func main() {
    x := Handler(func(){})
    handlers := []*Handler{&x}
    for _, handler := range handlers {
        (*handler)()
    }
}
```

The line: ` (*handler)() ` used to generate only an `unresolved reference error` (see #2431) but now it also generates an `Expected <arithmetic operation sign> but got ""` error. However this was not present in 0.11.1246 or older versions and it's also a problem, see below:

*0.11.1253 new error*
![snapshot16](https://cloud.githubusercontent.com/assets/607868/14225065/f01586b4-f8ac-11e5-91b1-2d0631df6754.png)

*0.11.1246 old error*
![snapshot15](https://cloud.githubusercontent.com/assets/607868/14225070/17f9a55c-f8ad-11e5-8ee6-74fc81a05da0.png)

**Comment by zolotov** [comment]
There is no regression, both error messages are correct

**Comment by zolotov** [comment]
I mean it doesn't matter what the message is if it wasn't not parsed

**Comment by dlsniper** [comment]
If I remove the pointer in that example, then everything is fine. But I don't understand why we'd have the second error in the newer version when it could be avoided. It might not be a parser related issue but an inspection one. Or should we just close this and consider bad code as being undefined in behavior until fixed?

**Comment by zolotov** [comment]
The change of error message on broken case doesn't make this case more broken than before. It's still parser issue but it's covered by #2431 so I'm closing it.
