### ISSUE TITLE
I can`t select my GO SDK PATH in mac finder

### ISSUE THREAD

**Issue by javasgl** [go-lang-plugin-org/go-lang-idea-plugin#2434]
- Plugin version (or commit hash):0.9.1163
- IDE name and version:IntelliJ IDEA 14.1.4
- Java version:1.8.0_45
- OS name and version: Mac OS X Yosemite 10.10.3

- What are you trying to do?
trying to import a new go project , follow a step by step form page https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#setting-up-the-go-sdk

- What would you expect to happen?
I should select the Go installation directory. which is `/usr/local/go`
- What happens?
when I meet the dialog for `select go SDK` , I chose the `Configure...` button,
then I cant find my Go Path which the path is `/usr/local/go`

I try to  search the solution  for mac os, then found some files or Directory is protected by os x system, so I execute `defaults write com.apple.finder AppleShowAllFiles TRUE && Killall Finder` in command line tool, then I can see those protected file and directory In Finder , But when I try again to import Go Project From Source, protected Directory dose not show in dialog,I still can not select the go install directory

**Comment by javasgl** [comment]
I just found a solution myself.
I cant create a symbolic link for directory ` /usr/local/go`,
like this command `sudo ln -s /usr/local/go /{$myhomedir}/go_install_dir `
then I can chose `/{$myhomedir}/go_install_dir` as the SDK path.

**Comment by zolotov** [comment]
Plugin has nothing to do with this sorry.

Btw, you can use ⌘+shift+G in finder
