### ISSUE TITLE
golang plugin incompatible with latest IntelliJ 2016.1 bug fix 

### ISSUE THREAD

**Issue by Ravenwater** [go-lang-plugin-org/go-lang-idea-plugin#2437]
- Plugin version (or commit hash): Go v.0.11.1197
- IDE name and version: IntelliJ 2016.1, Build 145.597
- Java version: 1.8.0_73
- OS name and version: Windows 10

- What are you trying to do? use the golang plugin for Golang development

- What would you expect to happen? the golang commands and syntax highlighting to work

- What happens? IDE reports that golang plugin is incompatible

Your issue description goes here.
updated my IntelliJ IDEA to build 145.597, golang plugin has stopped working: incompatible with current version.

 https://intellij-support.jetbrains.com/hc/en-us/articles/207241085 

any go project will exhibit this issue

![image](https://cloud.githubusercontent.com/assets/466641/14247705/11774ab2-fa3e-11e5-806d-901b39cc15a7.png)

**Comment by zolotov** [comment]
Please reinstall go plugin

Duplicates #2428

**Comment by dlsniper** [comment]
Can you also please give the logs from the ide before and after update? That might be useful (and you've already linked to the page which tells you how to get them).
