### ISSUE TITLE
"Terminated" state for fast tests

### ISSUE THREAD

**Issue by ernado** [go-lang-plugin-org/go-lang-idea-plugin#2439]
- Plugin version (or commit hash): 0.11.1256
- IDE name and version: IntelliJ IDEA 2016.1.1
Build #IU-145.59
- Java version: JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: 
Ubuntu 16.04 
Linux x250 4.4.0-16-generic #32-Ubuntu SMP Thu Mar 24 22:38:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- What are you trying to do?
Start tests for project.
- What would you expect to happen?
Tests results are "Tests passed" 
- What happens?
Tests are "Terminated'

I've discussed that issue with @zolotov and discovered that test output is probably not parsed fully if tests are too quick to complete. 

I've made a workaround for this: 
```go
// added to *_test.go file
func TestMain(m *testing.M) {
	m.Run()
	if len(os.Getenv("IDEAWAIT")) > 0 {
		time.Sleep(200 * time.Millisecond)
	}
}
```
And `IDEAWAIT=TRUE` to environment variable, and all tests are "green" and "passed" as expected.

![screenshot from 2016-04-04 19-47-05](https://cloud.githubusercontent.com/assets/866677/14255784/717b5ea2-fa9e-11e5-9cb8-a832c382f000.png)

Without environment variable:
![screenshot from 2016-04-04 19-47-12](https://cloud.githubusercontent.com/assets/866677/14255785/7186140a-fa9e-11e5-9aac-bb0ad1fcc34f.png)

With environment variable:
![screenshot from 2016-04-04 20-00-50](https://cloud.githubusercontent.com/assets/866677/14256080/f5518728-fa9f-11e5-816e-533d4c0039b1.png)

Now i'm trying to reproduce this issue in debug IDEA. Unable to reproduce on 145.258 CE.

**Comment by ernado** [comment]
I've managed to reproduce issue on `IntelliJ IDEA 2016.1.1 Build #IU-145.597` in debug mode.

So we discovered that with
```java
  @Override
  protected GoExecutor patchExecutor(@NotNull GoExecutor executor) throws ExecutionException {
    executor.withParameters("test", "-v");
    executor.withParameterString(myConfiguration.getGoToolParams());
    executor.disablePty();  // <- added
    switch (myConfiguration.getKind()) {
    // ...
```
On com.goide.runconfig.testing.GoTestRunningState#patchExecutor:

![screenshot from 2016-04-04 20-34-52](https://cloud.githubusercontent.com/assets/866677/14257209/5b7918fe-faa5-11e5-95ca-e881fd153c41.png)

Not reproducing anymore.

**Comment by zolotov** [comment]
pty is disabled by default
