### ISSUE TITLE
IndexNotReadyException

### ISSUE THREAD

**Issue by gamermonetary** [go-lang-plugin-org/go-lang-idea-plugin#2440]
- Plugin version (or commit hash):Android Studio Plugin
- IDE name and version: Android Studio 15.1
- Java version: Java 7 Update 79 (64 bit)
- OS name and version: Win 8.1

- What are you trying to do?
I am trying to open the source code of an app in Android studio... 

- What would you expect to happen?
I would like the source to get open in Android Studio so that I can build the project and run in Emulator.

- What happens?

Your issue description goes here.
Please be as detailed as possible

I imported the source to Android studio and in Project -> Android -> GOT ERROR
Erorr is: IndexNotReadyException: please change caller according to com.intellij.openapi.project.indexnotreadyexception

Please include a go sample to reproduce the issue
```
![error](https://cloud.githubusercontent.com/assets/18114105/14267054/a118b8f2-faea-11e5-9fef-bf61092fc734.png)

Or include a screenshot / video of the issue.




Please help me with this error.... help me with the fix for this error.

**Comment by dlsniper** [comment]
Can you please attach the logs? Or at least the stacktrace for the error that should be visible in the error reporting box? And what is the actual plugin version?

**Comment by gamermonetary** [comment]
![as](https://cloud.githubusercontent.com/assets/18114105/14267206/d398cc26-faeb-11e5-8b05-c301d1e7f70a.png)

![error](https://cloud.githubusercontent.com/assets/18114105/14267208/ddff09d2-faeb-11e5-8310-f4a3a16f14f3.png)


Here are the two screenshots, please look at it and guide me @dlsniper

**Comment by dlsniper** [comment]
You can find the log file by going to Help | Shoe logs in...  And there you should have the logs opened in your default directory browser. Get the idea.log (or studio.log I don't remember the name now)  and please attach it here.

**Comment by gamermonetary** [comment]
[idea.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/203524/idea.txt)

Here is the log...I renamed it to idea.txt @dlsniper

**Comment by zolotov** [comment]
Golang plugin is not even installed, why do you created an issue here?

**Comment by dlsniper** [comment]
Plead report this to the tracker of Android Studio, like Alexander said, the Go plugin is not installed in your setup.

**Comment by dlsniper** [comment]
To be clear this repository is for the Go plugin for IntelliJ only, any IDE issue should ne reported to JetBrains or Google or your IDE vendor. For any other plugins, please report to the appropriate tracker. Thanks.
