### ISSUE TITLE
Show "Learn how to setup a new Go project" message once

### ISSUE THREAD

**Issue by mkuzmin** [go-lang-plugin-org/go-lang-idea-plugin#2441]
- Plugin version (or commit hash): 0.11.1262
- IDE name and version: IDEA 2016.1.1
- Java version: 1.8.0_77
- OS name and version: Mac OS 10.11.4, Windows 10

Every time I upgrade the plugin from a repository, IDEA shows me this message:
![screen shot 2016-04-06 at 22 30 06](https://cloud.githubusercontent.com/assets/712402/14330134/c122fb4a-fc47-11e5-97d1-28591cc055bc.png)

This was a helpful link when I installed the plugin for the first time, but please do not show it again after updates.

**Comment by dlsniper** [comment]
Yeah, I should probably improve that. Thanks for reporting.
