### ISSUE TITLE
Add inspection for infinite loop

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2443]
Instead of ` for {} ` the plugin should detect it and suggest ` select {} ` for blocking a function / goroutine.
Also this should be a warning as `for {}` will cause the CPU to spin at 100% while `select {}` will simply block the goroutine and the scheduler will be aware of that (so no performance issue).

**Comment by kaedys** [comment]
As long as it doesn't also spout warnings for legitimate uses of infinite `for` loops, such as in the `Serve()` function for a server.  Beyond that, infinite for loops are often used *around* `select` blocks to allow a routine to continue processing messages off one channel until another channel (like a `time.After()` channel) outputs a value telling it to quit.  The only time a naked `for` is problematic is if the embedded `select` has an default case that's empty or that just has `continue` in it.  For example, the following is perfectly valid (and won't cause the 100% CPU issue you highlighted):

```
func Process(input chan Package, quit chan struct{}) {
    for {
        select {
            case <-quit:
                break
            case p := <- input:
                // Do processing stuff on p
        }
    }
}
```

This loop will block (with essentially no CPU usage) until it receives an input on one of the channels.  If it receives it on quit, it breaks the loop and returns.  If it receives it on the input channel, it processes, then loops back to block again.

**Comment by dlsniper** [comment]
Hi @kaedys, maybe it's not clear from the text of the issue but I do intend to implement this only for ` for {} ` constructs. I can't find anyone to pay me upfront for implementing a universally working infinite for loop detector :|

**Comment by kaedys** [comment]
Heh, infinite loop detector would be nice.  Last I checked, though, it's one of those nasty unsolveables... >.<

However, when you said `for {}`, I thought you just meant naked for loops, not naked and *empty* for loops.  All together different issue, and ya, naked and empty for loops are *very bad*.
