### ISSUE TITLE
Show type info for variable/const declarations

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2444]
E.g.:

x := 7
or 
x, err := f(...)

It's very useful to be able to inspect the type of x, in particular when calling unfamiliar functions and want to know if you get a pointer back, of what type, etc.

Right now if you hold down Cmd (on Mac) and hover over the short var declaration it offers to show usages of the var which is not very useful, I'd rather see the type instead, just like you can when you hover over a variable in use in an expression, after it was declared.

**Comment by zolotov** [comment]
Will do. Btw F1 should also work on Mac
