### ISSUE TITLE
Don't suggest type keyword in type() or var() contexts

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2445]
- Plugin version (or commit hash): 0.11.1267

Given the following example:

```go
type (
	ty<cursor> // the plugin shouldn't suggest type here as a valid keyword
)

var (
	ty<cursor> // the plugin shouldn't suggest type here as a valid keyword
)
```
The plugin shouldn't suggest type as valid keyword there. From m quick tests, I can only see this happening for `type` and only in those two contexts, otherwise var inside var or const inside type doesn't work (or other combinations of type, var and const)

**Comment by zolotov** [comment]
fixed for type declarations, var declarations is on @ignatov.

@ignatov GoCompletionTest#_testNoKeywordCompletionInsideVarDeclarationList, see following code in bnf:
```
VarDeclaration ::= var ( VarSpec | '(' VarSpecs? ')' ) {pin=1 methods=[addSpec deleteSpec]}
private VarSpecs ::= VarSpec (semi VarSpec)* semi? {pin=1}
VarSpec ::= VarDefinitionList ( Type [ '=' ExpressionList ] | '=' ExpressionList ) {
  methods=[processDeclarations deleteDefinition getRightExpressionsList]
  stubClass="com.goide.stubs.GoVarSpecStub"
}
private VarDefinitionList ::= VarDefinition ( ',' VarDefinition )*
```

It's good to have pin there and parse the whole following code as a single VarDeclaration:

```
var (
  a
  b
  c
)
```

**Comment by ignatov** [comment]
@zolotov please see GoCompletionTest#_testNoKeywordCompletionInsideVarDeclarationListAfterEquals
