### ISSUE TITLE
Disable suggestion when in a comment context

### ISSUE THREAD

**Issue by kaedys** [go-lang-plugin-org/go-lang-idea-plugin#2450]
If one is typing in a comment and types certain keywords, the code completion will still try to replace them.  For example, if you type:

```
// main
```
A dialog will pop up suggesting the `main` function.  If you then hit tab or enter (such as to start a new line of comment), you end up with the following:

```
// func main() {

}
```

Which is certainly unexpected behavior.

![screen shot 2016-04-11 at 12 19 56](https://cloud.githubusercontent.com/assets/9020449/14435980/082f5790-ffe0-11e5-887a-8507f9e7eded.png)

**Comment by kaedys** [comment]
Appears to also occur for `imp` (as in `import`, which apparently only triggers on `imp`), `init`, `iota`, `bench`, `con` (as in `const`), `json` (as in the struct tags), `meth` (as in `method`, a default function signature), `p` (as in `package`), `test`, `type`, and `xml` (again, struct tags)

**Comment by zolotov** [comment]
@kaedys it's all live templates, you can disable them in the settings until this got fixed

**Comment by zolotov** [comment]
relates to #1440 #2315

**Comment by kaedys** [comment]
Thanks, appreciate the work-around!

**Comment by zolotov** [comment]
Fixed by #2454
