### ISSUE TITLE
Plugin updates not on Windows

### ISSUE THREAD

**Issue by benbve** [go-lang-plugin-org/go-lang-idea-plugin#2453]
- Plugin version (or commit hash): 11.1197
- IDE name and version: IntelliJ IDEA 2016.1.1
- Java version: 1.8.0-77
- OS name and version: Windows 10

- What are you trying to do?
Get latest Plugin

- What would you expect to happen?
Get latest Plugin

- What happens?
On OSX I was informed this morning of new plugin for Go 11.1262.  On Windows I even ran check for updates and browse repository and only 11.1197 is available?

**Comment by zolotov** [comment]
Just uninstall/install the plugin

duplicates #2428

**Comment by zolotov** [comment]
Btw, since IDE suggested Go 11.1262 for you, you have alpha or nightly repo in IDE on MacOS. You should do it for IDE on Windows as well if you want to use nightly build. See README for details
