### ISSUE TITLE
Better parser handling for struct short assignment

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2457]
- Plugin version (or commit hash): 0.11.1288
IntelliJ IDEA (Minerva) IU-145.844.1
Build #IU-145.844, built on April 5, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- What are you trying to do?
Write an anonymous struct via a short assignment statement
- What would you expect to happen?
Have auto-completion working while I define the struct
- What happens?
Nothing works until I get the struct to be initialized

```go
package main

func main() {
	d := struct {
		name     str<caret>
	}
	_ = d
}
```

Optionally maybe this could be addressed by doing the completion of `struct` as `struct{}{}` if the expression is assigned directly via the short assignment statement (@cc @zolotov for this one).

**Comment by ignatov** [comment]
Works good right now.

**Comment by dlsniper** [comment]
@ignatov thank you!

**Comment by ignatov** [comment]
Please fill another issue about the insert handler.
