### ISSUE TITLE
Completion suggests items that are not present in the current context for structs

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2458]
- Plugin version (or commit hash): 0.11.1288
IntelliJ IDEA (Minerva) IU-145.844.1
Build #IU-145.844, built on April 5, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- What are you trying to do?
Write a struct initialization

- What would you expect to happen?
Have the struct fields appear in the list

- What happens?
Values that are not related to the struct fields appear in the list.

```go
package main

type demo struct{
	FieldA string
	Formatter string
	Hello string
}

func main() {
	a := demo{
		<caret>
	}
}
```

Normal autocompletion while typing
![snapshot86](https://cloud.githubusercontent.com/assets/607868/16248105/02cd381e-3805-11e6-8e88-f44d28cba847.png)

CTRL+SPACE (smart completion?)
![snapshot87](https://cloud.githubusercontent.com/assets/607868/16248116/15b622c4-3805-11e6-817b-d5afd370e5a0.png)

**Comment by dlsniper** [comment]
I've opened this as a reminder for me since I don't have the time to get a small sample to replicate this, I'll do it as soon as I can.

**Comment by zolotov** [comment]
any update on description?

**Comment by dlsniper** [comment]
ah, sorry, yes, I'll do those now.

**Comment by dlsniper** [comment]
Done.

I understand that for the both the completion styles (normal and smart) other values might be useful as you could potentially refer anything else and it's great that the plugin first suggests field names.
However I wonder if we could have either an option or the smart completion show only the struct fields as that's what the other editors mostly show (due to lack of more advanced features).
Or at least show the fields until we have a way to do type inference + suggestions for completion.

What do you think? Does it make sense now?

Thank you.

**Comment by zolotov** [comment]
There is no smart completion, both completions are normal.

> it's great that the plugin first suggests field names

I think this is enough, so I'll fix the completion on the second screenshot and disable auto-import completion for structs which doesn't consist of unnamed fields.
