### ISSUE TITLE
Found several packages [main, time] in '/usr/local/go/src/time'

### ISSUE THREAD

**Issue by aanm** [go-lang-plugin-org/go-lang-idea-plugin#2460]
- Plugin version (or commit hash): 0.11.1197
- IDE name and version: IntelliJ IDEA 2016.1.1 Build #IC-145.597, built on March 29, 2016
- Java version: JRE: 1.8.0_76-release-b18 amd64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: Fedora 23 x86_64

- What are you trying to do?
Write a normal golang file and importing `time` package.

- What would you expect to happen?
Not seeing any import errors.

- What happens?
There's an import error with the message: `Found several packages [main, time] in '/usr/local/go/src/time' This inspection highlights invalid imports.`
The main package exists in https://github.com/golang/go/blob/master/src/time/genzabbrs.go
However it contains a [`+build ignore`](https://github.com/golang/go/blob/master/src/time/genzabbrs.go#L5).

Example code.
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Printf("Hello, playground! It is %+v", time.Now())
}
```

**Comment by dlsniper** [comment]
@aanm please reinstall the plugin. It's a known issue and it will be fixed when the new version comes up (or try the new release from the Alpha channel, see Readme). Thank you

**Comment by aanm** [comment]
@dlsniper On which version is it fixed? I've try it with Version: 0.11.1288 and I'm still seeing this problem. Thanks!

**Comment by dlsniper** [comment]
Oh my. Can you please send the log file from idea?  @zolotov check this as well please.

**Comment by aanm** [comment]
@dlsniper Sorry. It's happening on my current project, not on a new one. How can I somehow re-trigger a clean up?

**Comment by dlsniper** [comment]
Not sure if it should be closed, that's why I've reopened it. It would be really helpful if you can provide the log file from IDEA (I can guide you how, you can send it in gitter / to my mail if you don't want it public) as it would be nice to work with existing projects as well :)

**Comment by aanm** [comment]
@dlsniper `system/log/idea.log`? -> http://pastebin.com/buzHJRxa

**Comment by dlsniper** [comment]
Do you have the one before updating IDEA? they should be in log.1 and so on. Thanks.

**Comment by aanm** [comment]
Sorry... I delete those ones because I wanted to see a fresh log.

I've removed this new version, and installed the old version (`0.11.1197`).

This file starts with `0.11.1288` and around line 219 starts with `0.11.1197`
http://pastebin.com/Fsw6DarC

**Comment by dlsniper** [comment]
Ah, no, it would have been useful to understand what was there before the IntelliJ upgrade. Anyway, @zolotov is there a way to trigger index rebuilding for projects when upgrading the plugin version as it seems the problem persisted when upgrading to 0.11.1288 (I was expecting it will go away). Thanks for helping out @aanm!

**Comment by aanm** [comment]
Oh okay. Let me know if I can help with anything. Thanks!

**Comment by zolotov** [comment]
> @zolotov is there a way to trigger index rebuilding for projects when upgrading the plugin version as it seems the problem persisted when upgrading to 0.11.1288

Indicies cannot be involved to this problem. But yes, there is a trigger.

@aanm please attach your *.iml files

**Comment by aanm** [comment]
@zolotov I only have one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="GO_MODULE" version="4">
  <component name="Go">
    <buildTags>
      <option name="goVersion" value="go1.6" />
    </buildTags>
  </component>
  <component name="NewModuleRootManager" inherit-compiler-output="false">
    <output url="file://$MODULE_DIR$/bin" />
    <exclude-output />
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="GOPATH &lt;project&gt;" level="project" />
  </component>
</module>
```

**Comment by zolotov** [comment]
@aanm thanks. And what IDE show if you open `genzabbrs.go` file from `time` package?

**Comment by zolotov** [comment]
@aanm find a possible reason, will try to fix as soon as possible

**Comment by aanm** [comment]
If I open only the file, within my project, I get this: "Checks multiple package in directory declaration"

**Comment by zolotov** [comment]
Please try 0.11.1295 from nightly channel

**Comment by aanm** [comment]
@zolotov Fixed! Thanks!

**Comment by liyuanhang** [comment]
go.17 does not has this problem

**Comment by zyzhang-free** [comment]
go 1.18 appear

**Comment by zzxCNCZ** [comment]
> go 1.18 appear

got same problem

**Comment by zzxCNCZ** [comment]
change go version to 1.17.8 will solve it

**Comment by zengqingfa** [comment]
clean goland cache can solve it.

**Comment by denkensk** [comment]
> go 1.18 appear

+1

**Comment by zyzhang-free** [comment]
> 

upgrade goland will also solve it

**Comment by gilsegment** [comment]
It started for me after upgrading to go 1.18
Tried to upgrade to 1.18.1 and still happening

**Comment by dlsniper** [comment]
This project is officially not maintained anymore. If you are using [GoLand](https://jetbrains.com/go) or [IntelliJ IDEA Ultimate](https://jetbrains.com/idea) 2017.3 or later, please report your issue at the official tracker: https://youtrack.jetbrains.com/issues/Go

**Comment by vignesh-desk** [comment]
upgrade GoLand 2022.1 resolved this

**Comment by WenHv587** [comment]
> upgrade GoLand 2022.1 resolved this

useful, thank you
