### ISSUE TITLE
Test runner fails to start test(s)

### ISSUE THREAD

**Issue by charneykaye** [go-lang-plugin-org/go-lang-idea-plugin#2462]
# Note: This was resolved when I added the [nightly](https://plugins.jetbrains.com/plugins/nightly/5047) and [alpha](https://plugins.jetbrains.com/plugins/nightly/5047) plugin repos and updated to `0.11.1295`

- *Plugin version*

    > go-lang-plugin 0.11.1197

- *IDE*

    > IntelliJ IDEA 2016.1.1
    > Build #IC-145.597, built on March 29, 2016
    > JRE: 1.8.0_76-release-b18 amd64
    > JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- *OS*

    > Description:	Ubuntu 14.04.4 LTS
    > Codename:	trusty

- *Machine*

    > Architecture: x86_64

- *What are you trying to do?*

    I'm trying to run tests. **I've been using go-lang-plugin for months, and doing this fine without any issues. Then just this week, it mysteriously 'broke' which I will describe here.** Unfortunately I have not been able to identify an exact change to my system that caused the change in go-lang-plugin behavior.

    **All of this testing is run on an open-source project for ease of sharing.** That project is https://github.com/go-music-theory/music-theory

    There are three scenarios I'm testing:

    1. Run all tests in the `music-theory` package.

    2. Run all tests in one file `music-theory_test.go`

    3. Run one test `TestHelpCmd` in one file `music-theory_test.go`

- *What would you expect to happen?*

    1. There's **44 Tests** in this package, and they all pass during a normal command-line test run. I'd expect to see 44 tests run and pass.

    2. There's **2 Tests** in this file, and they all pass during a normal command-line test run. I'd expect to see 2 tests run and pass.

    3. The test passes during a normal command-line test run. I'd expect to see 1 test run and pass.

- *What happens?*

    1. The failures are **sporadically different** What's consistent is that tests are left out. What's inconsistent is that only *sometimes* I see a "test not started" in the list. So I might see "14 tests pass" which is missing 30 whole tests.  Or I might see "7 passed, 1 not started" *(see 4x screen captures attached)*

        ![run all tests in the music-theory package - failure type a](https://cloud.githubusercontent.com/assets/8584836/14498970/7241de92-016a-11e6-8880-3b3de00046a3.png)

        ![run all tests in the music-theory package - failure type b](https://cloud.githubusercontent.com/assets/8584836/14498968/724162c8-016a-11e6-9632-455f3c44432a.png)

        ![run all tests in the music-theory package - failure type c](https://cloud.githubusercontent.com/assets/8584836/14498969/7241d62c-016a-11e6-9ae2-e6a0044a3278.png)

        ![run all tests in the music-theory package - failure type d](https://cloud.githubusercontent.com/assets/8584836/14498971/72426bd2-016a-11e6-82c7-6643345756ae.png)

    2. Consistently, I see "0 passed, 1 not started" *(see screen capture attached)*

        ![run all tests in one file music-theory_test go](https://cloud.githubusercontent.com/assets/8584836/14499000/89999508-016a-11e6-8176-3638ca3b3b05.png)

    3. Consistently, I see "1 not started" *(see screen capture attached)*

        ![run one test testhelpcmd in one file music-theory_test go](https://cloud.githubusercontent.com/assets/8584836/14499021/947cb860-016a-11e6-8293-ba52d0ff8cb9.png)

**Comment by zolotov** [comment]
Indeed, it was fixed in alpha
