### ISSUE TITLE
Not Support build single file or package, Just need build. 

### ISSUE THREAD

**Issue by wangxingge** [go-lang-plugin-org/go-lang-idea-plugin#2473]
- Plugin version (or commit hash):
- IDE name and version:
Intellij 2016 _1.1
- Java version:
1.8
- OS name and version: 
Windows 7
- What are you trying to do?
Just Build package or single go file.
- What would you expect to happen?
Just Build package or single go file.
- What happens?
Build and run.

Add a function such as. Click Run-> Build current file or current folder.

I'm really don't need always build main.go, just need build current file, I'd like to configure a build configuration if you can show me how to do that, and I'll share it to the people which has the same concern.

Thanks

**Comment by dlsniper** [comment]
Hi. Building current file is not supported by the plugin. Building a package is supported but not building the current package. 
If you need those actions, please use the "External. Tool" functionality: https://www.jetbrains.com/help/idea/2016.1/external-tools.html
If you have any issues with getting this working please let me know. 

@zolotov I'll leave this up to you but I think we can close this.

**Comment by wangxingge** [comment]
@dlsniper thank you
I'll try it,cause of I used sublime and liteide before, so I want this function.

**Comment by wangxingge** [comment]
@dlsniper 
I'll close this issue after test which you mentioned.

**Comment by wangxingge** [comment]
@dlsniper 
Does Intellij support debug on windows?
I'v read this https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922, my question is does this change merged into master?

**Comment by dlsniper** [comment]
Merged in master, yes, released in stable, yes.

**Comment by wangxingge** [comment]
Yes, I've test it.
Thank you.
