### ISSUE TITLE
Builtin symbol marked as unresolved on MacOSX

### ISSUE THREAD

**Issue by kokizzu** [go-lang-plugin-org/go-lang-idea-plugin#2474]
- Plugin version (or commit hash): 0.11.1316
- IDE name and version: IntelliJ IDEA 2016.1
- Java version: java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
but on the System Properties it shows Java 8, not Java 6
- OS name and version: Mac OSX El-Capitan

- What are you trying to do?
configure the golang idea plugin

- What would you expect to happen?
configured correctly

- What happens?
built-in symbols unresolved (string, etc)

Your issue description goes here.
![image](https://cloud.githubusercontent.com/assets/1061610/14624758/b93d652c-0607-11e6-8293-0d4a1ef16436.png)
![image](https://cloud.githubusercontent.com/assets/1061610/14624779/d1118de0-0607-11e6-803c-194c63679033.png)
![image](https://cloud.githubusercontent.com/assets/1061610/14624787/e5e937c2-0607-11e6-8255-d74099def108.png)
![image](https://cloud.githubusercontent.com/assets/1061610/14624807/1adb4bbe-0608-11e6-93f9-6d7b4ce3f9ad.png)
![image](https://cloud.githubusercontent.com/assets/1061610/14624819/28b5b6ac-0608-11e6-9ec1-13c9fca35c7c.png)

```go
package main
import "fmt"
func main() {
  var x string
  x = `test`
  fmt.Println(x)
}
```

**Comment by kokizzu** [comment]
Nevermind, I should check the Dependencies tab first

![image](https://cloud.githubusercontent.com/assets/1061610/14624952/2a1d29d4-0609-11e6-9e63-eb45af7861b3.png)

after setting that tab to the correct version it works well

**Comment by dlsniper** [comment]
Hi there, I've noticed that you also have the Go sdk in the Go Libraries (/usr/local/go). Please remove that as it's not needed.

**Comment by kokizzu** [comment]
btw other not, I found the library autocomplete doesn't work well if the library name is only 1 character, for example: https://gitlab.com/kokizzu/gokil

**Comment by dlsniper** [comment]
Please open a separate issue as it's not related to this. Thank you.

**Comment by zolotov** [comment]
@kokizzu if you mean autoimport completion then it's intended behavior

**Comment by kokizzu** [comment]
ah i see, ok then.

**Comment by zolotov** [comment]
@kokizzu please try to invoke completion twice (ctrl+space ctrl+space), if it doesn't work than it's bug

**Comment by kokizzu** [comment]
Ah it shows, but it's really far below, XD i'm ok with this

![image](https://cloud.githubusercontent.com/assets/1061610/14639976/8ebc65f2-0669-11e6-96e4-b58484d3ddb2.png)

**Comment by zolotov** [comment]
@kokizzu I see, thanks, added your example here #2206
