### ISSUE TITLE
Problems window (automatic build?)

### ISSUE THREAD

**Issue by jackmanlabs** [go-lang-plugin-org/go-lang-idea-plugin#2475]
- Plugin version (or commit hash): 0.11.1295

- IDE name and version:
IntelliJ IDEA 2016.1.1 (Community Edition)

- Java version: 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

- OS name and version: Debian 8.4

- What are you trying to do?
I just want to see compile-time issues in the 'Problems' window.

- What would you expect to happen?
I expect to see the project automatically build and show compile-time errors in the 'Problems' window.

- What happens?
No 'Problems' window appears.

As I work on my project, I want to be able to easily see what problems are arising and what files need attention. Currently the only way to achieve this is to attempt to build the project on the command line.

According to IntelliJ documentation, I just need to turn on automatic builds. This has no effect.

```go
package main

func main() {
	testMethod(1)
}

func testMethod(foo string) {}
```

The above code formats correctly, and a red squiggly appears to hint a problem, but not textual information appears regarding the issue.

**Comment by dlsniper** [comment]
Hi,

Can you please post a screenshot of the problem, I can't see any red inspection with the sample code.
As for the `Problems window`, the plugin currently doesn't support the that option / functionality.
Please use a run configuration if you want to run your project.
Thanks.

**Comment by jackmanlabs** [comment]
I'm only concerned about the Problems window. If you don't plan on supporting it, this ticket should just be closed as erroneous.

**Comment by zolotov** [comment]
duplicates #2408

**Comment by dlsniper** [comment]
I'm a bit concerned with the possibility of having an inspection showing an error for you and not for me on the same code. That's why I asked for the screenshot. I guess Alexander replied to the other part of the issue.
