### ISSUE TITLE
running path set request

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [go-lang-plugin-org/go-lang-idea-plugin#2480]
WebStorm 2016.1.1
Build #WS-145.597, built on March 30, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- Plugin version (or commit hash): 0.11.1295
- IDE name and version: webstorm
- Java version:
- OS name and version: mac osx 10.11.4 (15E65)

- What are you trying to do?
now when i create a sample project, the console info of debugging is like these
```
"/Users/mmc/Library/Application Support/WebStorm2016.1/Go/lib/dlv/mac/dlv" --listen=localhost:50617 --headless=true exec "/private/var/folders/kv/p78h0g757pdb9t2fbt492jsh0000gn/T/Build MyApp.go and rungo" --
GOROOT=/Users/mmc/dev/golang/go
GOPATH=/Users/mmc/dev/golang/myApps:/Users/mmc/dev/golang/3rdLibs:/Users/mmc/dev/golang/myLibs
/Users/mmc/dev/golang/go/bin/go build -o "/private/var/folders/kv/p78h0g757pdb9t2fbt492jsh0000gn/T/Build MyApp.go and rungo" -gcflags "-N -l" /Users/mmc/dev/golang/myApps/src/MyApp/MyApp.go
```

- What would you expect to happen?
some times, when i use a web framework with relative path config files, i need delve to debug under the source path, not using  "/private/var/folders/xxxx" path, but now i can not find any place to set the output path for debugging.

so, would you please make a option to set? thanks.

**Comment by zolotov** [comment]
> when i use a web framework with relative path config files

you can set working directory for particular run configuration

> i need delve to debug under the source path

you can set output file path as well, but it's not needed in your case
