### ISSUE TITLE
suggest support gometalinter

### ISSUE THREAD

**Issue by safeie** [go-lang-plugin-org/go-lang-idea-plugin#2493]
gometalinter is a strong tool for go format check. can you support it?

**Comment by dlsniper** [comment]
gometalinter can be used today by configuring an `External Tool`.
I'll leave this open but last time I know this was brought up the consensus was that gometalinter will not be supported BUT matching its functionality in the plugin will be preferred.

**Comment by safeie** [comment]
ok, thank you.

**Comment by zolotov** [comment]
#2220
