### ISSUE TITLE
New inspection: "Return value name required"

### ISSUE THREAD

**Issue by deadok22** [go-lang-plugin-org/go-lang-idea-plugin#2494]
This code doesn't compile:
```go
func mixNamedAndUnnamedReturnValues() (a string, error) {
	return
}
```

I'd like the plugin to highlight this code red. 

I like it that ```error``` is parsed as type here (the compiler parses it as variable name) - it allows navigating to types while working on implementation. So I propose adding an inspection which would complain on unnamed parameters.

Note that this code is valid, though:
```go
func mixNamedAndUnnamedReturnValues() (string, a json.Decoder) {
	return
}
```

Plugin version: 0.11.1316

**Comment by ignatov** [comment]
The PR is welcome :)
