### ISSUE TITLE
debug is disabled on pycharm 5.0 windows 7 

### ISSUE THREAD

**Issue by nkbai** [go-lang-plugin-org/go-lang-idea-plugin#2495]
- Plugin version (or commit hash):
0.10.749
- IDE name and version:
pycharm 5.0
- Java version:
1.8.0_31
- OS name and version: 
win7 64 professional
- What are you trying to do?
run menu-> "Debug  Build *.go  and run" menu is disabled 
- What would you expect to happen?
could debug golang with this plugin

all version of idea 15.0? i test with the latest idea ,it clould not work too.

**Comment by dlsniper** [comment]
Please upgrade to IDEA 15.1.latest or to IDEA 2016.1.latest (or in your case PyCharm the latest). After upgrading the IDE also check the plugins for updates (they should be updated automatically but you never know). 
The latest builds of the plugin are much higher than indicated.

**Comment by dlsniper** [comment]
PyCharm latest is 2016.1.2 (or the older 5.0.4), IDEA is 2016.1.1 (or the older 15.0.5)
If you have any further issues please feel free to comment here.
Also, please note that there's a bug in delve right now which gives a bit of a rough experience for debugging, it should be addressed soon hopefully (but has nothing to do with your issue).
