### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by nkbai** [go-lang-plugin-org/go-lang-idea-plugin#2496]
- Plugin version (or commit hash):
0.11.1162
- IDE name and version:
idea community edition 145.184.1
- Java version:
1.8.0
- OS name and version: 
win7 64
- What are you trying to do?
run-> debug build hello.go and run
- What happens?
panic: runtime error: slice bounds out of range

Your issue description goes here.
Please be as detailed as possible

```go
package main

import "fmt"

func main(){
	fmt.Println("hello,world")
}

```

Or include a screenshot / video of the issue.

goroutine 9 [running]:
github.com/derekparker/delve/dwarf/frame.parseFDE(0xc08223a0c0, 0xb9ddf0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:74 +0x406
github.com/derekparker/delve/dwarf/frame.Parse(0xc08223c000, 0x10780, 0x10800, 0x2d5cc8, 0xdbb860, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/dwarf/frame/parser.go:33 +0x1c8
github.com/derekparker/delve/proc.(*Process).parseDebugFrame(0xc082050700, 0xc082036ee0, 0xc0820e4420)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:174 +0x4df
created by github.com/derekparker/delve/proc.(*Process).LoadInformation
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:154 +0x112

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0820e442c)
	c:/go/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0xc0820e4420)
	c:/go/src/sync/waitgroup.go:126 +0xbb
github.com/derekparker/delve/proc.(*Process).LoadInformation(0xc082050700, 0xc082007ec0, 0x38, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:157 +0x18c
github.com/derekparker/delve/proc.initializeDebugProcess(0xc082050700, 0xc082007ec0, 0x38, 0x2d5b00, 0x4, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:707 +0x2a9
github.com/derekparker/delve/proc.Launch(0xc082007d40, 0x1, 0x4, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:103 +0xafc
github.com/derekparker/delve/service/debugger.New(0xc0820e0480, 0xc0820e0480, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:60 +0x384
github.com/derekparker/delve/service/rpc.(*ServerImpl).Run(0xc08202a0f0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/service/rpc/server.go:70 +0xbc
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc082007d40, 0x1, 0x4, 0xc08202a0c0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:355 +0x2fc
github.com/derekparker/delve/cmd/dlv/cmds.New.func4(0xc082078e00, 0xc082007d40, 0x1, 0x4)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:126 +0x51
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc082078e00, 0xc082007d00, 0x4, 0x4, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:569 +0x870
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc082078600, 0xc082078e00, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:656 +0x572
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc082078600, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:615 +0x34
main.main()
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/cmd/dlv/main.go:13 +0x51

goroutine 5 [syscall]:
os/signal.loop()
	c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc082050700)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:775 +0xd8
created by github.com/derekparker/delve/proc.New
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:77 +0x1db

goroutine 10 [runnable]:
syscall.SetFilePointer(0x1d8, 0x0, 0xc0820d7b14, 0x0, 0xc08221a000, 0xc082021380, 0xb9eab0)
	c:/go/src/syscall/zsyscall_windows.go:310
syscall.Seek(0x1d8, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/syscall/syscall_windows.go:350 +0x10e
os.(*File).pread(0xc08202a0f8, 0xc08224e000, 0x150c00, 0x150c00, 0x400, 0x150c00, 0x0, 0x0)
	c:/go/src/os/file_windows.go:327 +0x2dc
os.(*File).ReadAt(0xc08202a0f8, 0xc08224e000, 0x150c00, 0x150c00, 0x400, 0x0, 0x0, 0x0)
	c:/go/src/os/file.go:117 +0xd3
io.(*SectionReader).ReadAt(0xc0821a6900, 0xc08224e000, 0x150c00, 0x150c00, 0x400, 0x150c00, 0x0, 0x0)
	c:/go/src/io/io.go:493 +0x150
debug/pe.(*Section).Data(0xc08200b590, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/debug/pe/file.go:75 +0xba
github.com/derekparker/delve/proc.loadPETable(0xc082036ee0, 0xab03e0, 0xf, 0xb08a50, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:212 +0x3b0
github.com/derekparker/delve/proc.pcln(0xc082036ee0, 0x401000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:233 +0x181
github.com/derekparker/delve/proc.(*Process).obtainGoSymbols(0xc082050700, 0xc082036ee0, 0xc0820e4420)
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc_windows.go:254 +0x77
created by github.com/derekparker/delve/proc.(*Process).LoadInformation
	C:/BuildAgent/work/gopath/src/github.com/derekparker/delve/proc/proc.go:155 +0x148

**Comment by dlsniper** [comment]
That bug is in delve not the plugin. Also your IDE is very old, I've just commented in the previous ticket what are the latest versions. Most likely it was fixes in delve since.
