### ISSUE TITLE
Support for debugging

### ISSUE THREAD

**Issue by alexandre-normand** [go-lang-plugin-org/go-lang-idea-plugin#25]
It should be possible to implement the idea debugger interface and integrate with gdb to debug go programs from IDEA.

**Comment by prsolucoes** [comment]
+1 debugger

**Comment by dlsniper** [comment]
@prsolucoes what's the point of +1-ing a closed issue? Do you suggest you'd like to work on it? If so, please have a look at the PR for delve which is a work in progress https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1640

**Comment by ignatov** [comment]
The latest nightly build contains dlv integration.

**Comment by svalleru** [comment]
@ignatov, that's great, where to get the nightly build ?

**Comment by dlsniper** [comment]
@svalleru please read the instructions in the README: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds Also keep in mind that there are some issues that might appear that are not catched yet or are part of delve itself. If you do encounter such issues, please open an issue for them (if they are not reported already). Thank you.

**Comment by svalleru** [comment]
Sure thing.

**Comment by aaa4xu** [comment]
Any instructions about starting debug with dlv? I'm downloaded latest nightly build and Debug button is disabled

**Comment by dlsniper** [comment]
I'll add the instructions soon. Delve only supports Linux and Mac OS X

**Comment by dlsniper** [comment]
@aaa4xu and everyone else who's wondering how the integration works: Please make sure you are running on a supported IDE (see the README in the root of the project), open your project, set the breakpoints you want and then press the Debug option instead of the run option. You need to create a run configuration of type Go Application as a Run configuration of type Go file is not supported yet (the debug button is disabled for that configuration).

Hope it helps.

**Comment by pylover** [comment]
+10000 for supporting debug

**Comment by zolotov** [comment]
@pylover it's been implemented month ago

**Comment by dlsniper** [comment]
@pylover I'm sorry but clearly you haven't read the README nor the comment above. Delve support is currently implemented and working (on the platforms delve is working).

**Comment by pylover** [comment]
Thanks a lot, i'll read it
