### ISSUE TITLE
How To compile with multi file

### ISSUE THREAD

**Issue by linyilong33** [go-lang-plugin-org/go-lang-idea-plugin#2511]
- Plugin version (or commit hash):
0.10.1296
- IDE name and version:
pycharm 5.02
- Java version:
None
- OS name and version: 
Windows 7-64bit

how to compile multi-file liks this:
go build -o mygo.exe main.go export.go

I compile "Go Application --- File", it support single file
and I try to compile "Go Application-package",but it tips cannot find package 'xxxx'

**Comment by dlsniper** [comment]
Closing as accidentally opened issue. Please edit it and reopen or open a new one. Thank you.

**Comment by dlsniper** [comment]
If you use Go Application, which you should, your package needs to be present in GOPATH and you must type the full package path (e. g. github.com/user/package).

**Comment by linyilong33** [comment]
@dlsniper 
i wanna build main.go and export.go

i add my project to GOPATH,and edit config, input package "mygo" or full package path(E:\study\mygo), but it tips cannot find package "xxx"

**Comment by dlsniper** [comment]
The plugin respects the Go workspace layout: https://golang.org/doc/code.html#Workspaces
If you add your package under `GOPATH/src/xxx` then it you'll be to use it with `xxx` not `e:\some\directory\path\src\xxx` If your package is under `GOPATH/src/github.com/user/xxx` then you must use `github.com/user/xxx`
The plugin will print the GOPATH used in the compilation, please provide a screenshot with the output of that window.
If the go tool will complain that something is missing from the GOPATH then most likely there's a misconfiguration either in the plugin or the package is not present in the GOPATH.
