### ISSUE TITLE
Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by brandonecraig** [go-lang-plugin-org/go-lang-idea-plugin#2522]
- Plugin version (or commit hash): 0.10.749
- IDE name and version: IntelliJ IDEA 15 CE
- Java version: 1.8
- OS name and version: Mac OS X Yosemite

- What are you trying to do?
Setup my Go SDK

- What would you expect to happen?
I enter my $GOROOT and it works.

- What happens?
`Project SDK is not defined Setup SDK` across the top. 
Click Setup SDK
Click Configure...
Click +, Click Go SDK
By default IntelliJ goes to /usr/local/Cellar/go/1.6/libexec
Click ok
`Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK`
Change to /usr/local/Cellar/go. Click ok.
`Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK`

Check $GOROOT ==> /usr/local/opt/go/libexec
Change to /user/local/opt/go/libexec
`Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK`
Change to /user/local/opt/go/
`Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK`
Reattempt all previous attempts but with + /bin
`Select Home Directory for Go SDK: The selected directory is not a valid home for Go SDK`

I see plenty of other issues with this title but none provide a solution that works for me.
FWIW:
$GOROOT => /usr/local/opt/go/libexec
$GOPATH => /Users/bracraig/Go

**Comment by dlsniper** [comment]
Hi, please upgrade your IDE to 2016.1.2.

**Comment by ramilexe** [comment]
I use 2016.1.3 and have the same issue

**Comment by dlsniper** [comment]
@ramilexe please open a separate issue and provide the details like the OP did. Thank you.
