### ISSUE TITLE
Dismiss button on "GOPATH is empty" message

### ISSUE THREAD

**Issue by chris-martin** [go-lang-plugin-org/go-lang-idea-plugin#2523]
This is related to #2142, but @akamensky suggested that it's a separate issue, so I'm making a separate issue.

As I'm not a fan of any filesystem thing ever being global, I've avoided use of `GOPATH`, and I just symlink each project directory into the appropriate place within its `vendor` directory. I now have the IDE working properly, except there is still this "GOPATH is empty" message that I can't get rid of. Since it's totally fine to have an empty `GOPATH`, can we have some way to remove the error message?

**Comment by dlsniper** [comment]
Hi, I can see the point of having a way to dismiss the dialog but the GOPATH is still required to do the compilation as far as I know. I'll check this tomorrow. 
As for symlinking, this is highly discouraged as the `go tool` or other tools might behave unexpectedly. 

@zolotov I'll be able to check/provide feedback for the above comments either Sunday or next week. If you look into this issue before I can do so, please take those scenarios into account.

**Comment by chris-martin** [comment]
I generally use Nix to compile everything. Does the IDE need to be able to do compilation to function properly?
