### ISSUE TITLE
Cannot resolve file  error in IDE editor - after importing the packages to GOPATH directory

### ISSUE THREAD

**Issue by rajcspsg** [go-lang-plugin-org/go-lang-idea-plugin#2527]
- Plugin version (or commit hash): Version: 0.11.1295
- IDE name and version: ntellij IDEA 2016.1.2
- Java version: JDK  1.8.0_76
- OS name and version: KUbuntu 16.04

- What are you trying to do?
steps:
1. I have configured GOPATH in my environment variable.
2. By default enabled the option to use GOPATH defined in th System environment.
3. Downloading the go libraries using the go get command and it is successful.
4. Creating a Go project and Module.
5. Created a Go Application.
6. Imported the library in the Application which I downloaded in the step 3.
7. The application it is displaying error "Cannot resolve file" but when I run the program it runs detetcs the file in GOPATH and executes it.

- What would you expect to happen?

Golang IDE should be able to detect the files in GOPATH and should not display the error in IDE editor screen.

- What happens?
Golang IDE is  able to detect the files in GOPATH when run the Go Application and is showing  error in IDE editor screen.

I have attached the screen shot for your reference.

![goinaction-chapter2 error](https://cloud.githubusercontent.com/assets/10123965/15386176/2b3fa42c-1d5b-11e6-9efa-865e03bddd98.jpeg)

**Comment by dlsniper** [comment]
By the looks of it, you are trying to use the search package which should be in GOPATH/src/search. Most likely the package is under a different path, for example: GOPATH/src/github.com/<user>/search. 

You can see which GOPATH the IDE is using as it's printed in the output of the run command.

**Comment by rajcspsg** [comment]
Hi dlsniper,

I have provided the screen shot of GOPATH environment variable, GOPATH Golang IDE settings and the path where Search is present.

![go ide gopath setting screenshot](https://cloud.githubusercontent.com/assets/10123965/15420017/01996080-1e1f-11e6-9141-96c416d2b08f.jpeg)


![gopath_konsole](https://cloud.githubusercontent.com/assets/10123965/15420018/0692ee76-1e1f-11e6-8528-0f5b0fc1fca4.jpeg)


![go search path location](https://cloud.githubusercontent.com/assets/10123965/15420053/402c1e3c-1e1f-11e6-968a-2a8ac31d241b.jpeg)


Please let me know if you need further details.

**Comment by dlsniper** [comment]
Sorry, this is not a plugin issue.

You have to import `github.com/goinaction/code/tree/master/chapter2/sample/search` not `search` and things will work out. Please read the book, [Go in Action](https://www.manning.com/books/go-in-action) and/or the official Go documentation and see how to work with packages in Go. For even more help, you can join the Slack community at https://gophers.slack.com (to get the invite: https://invite.slack.golangbridge.org/ ) which has a channel called [#golang-newbies](https://gophers.slack.com/messages/golang-newbies/).

**Comment by dlsniper** [comment]
As I've messed up in my copy-paste above, the import statement has to be:

```
import (
 "..other packages.."

 "github.com/goinaction/code/chapter2/sample/search"
)
```

If you remove the current `search` package and then let the IDE suggest what to import, if everything is correctly setup then it will suggest the packages above (and/or possibly other `search` packages as well)
