### ISSUE TITLE
Debugger not working IDEA EAP

### ISSUE THREAD

**Issue by kolkov** [go-lang-plugin-org/go-lang-idea-plugin#2538]
- Plugin version (or commit hash): 0.12.1392
IntelliJ IDEA 2016.2 EAP
Build #IU-162.74.16, built on May 13, 2016
IntelliJ IDEA EAP User
Expiration date: June 12, 2016
JRE: 1.8.0_25-b18 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

- OS name and version: Windows 10

```
C:\Users\Andy\.IntelliJIdea2016.2\config\plugins\Go\lib\dlv\windows\dlv.exe --listen=localhost:5886 --headless=true exec C:\Users\Andy\AppData\Local\Temp\Rungo --
GOROOT=C:/Go
GOPATH=D:/Go
C:/Go\bin\go.exe build -o C:\Users\Andy\AppData\Local\Temp\Rungo -gcflags "-N -l" inframe

Process finished with exit code -1
```

[IDEA_Log (2).txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/280026/IDEA_Log.2.txt)

**Comment by dlsniper** [comment]
This is a problem in the debugger backend, delve. Please understand this. We we'll update the relevant tickets when this works.

**Comment by kolkov** [comment]
In the old version though occasionally it works. On the EAP does not work at all. ((
