### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by chic01taliano** [go-lang-plugin-org/go-lang-idea-plugin#2541]
- Plugin version (or commit hash): 0.10.1296
- IDE name and version: Webstorm 11.0.4
- OS name and version: Windows 7

Repo: https://github.com/chic01taliano/golang

Steps to reproduce the issue:
1) on **main.go** (before line 17) insert `salutations[0].ReGreet("Yo!")`
2) on **greeting.go** insert
`func (salutation *Salutation) ReGreet(newGreet string) {
    salutation.Greeting = newGreet
}`

Screen:

![immagine](https://cloud.githubusercontent.com/assets/15007338/15541770/630b36f4-228e-11e6-9950-20105d784b96.png)

**Comment by dlsniper** [comment]
Like I've said in my previous comment, please make sure your project respects the Go workspace, please see: https://golang.org/doc/code.html

To give you an example:
- my GOPATH is `/home/florin/golang`
- my project is under `/home/florin/golang/src/github.com/dlsniper/u`
- my imports all use fully qualified package names, for example: `/home/florin/golang/src/github.com/dlsniper/u/demo/pkg`
- the settings under File | Settings | Languages & Frameworks | Go | Go libraries contain only one entry for `/home/florin/golang`

Moreover, relative imports are highly discouraged from Go and you should not use them.

@zolotov I'm not sure there's anything to be done here, on my machine it works as expected (albeit with a newer plugin version).

**Comment by chic01taliano** [comment]
My GOPATH is `C:\Users\Alessandro\Documents\github.com`

**Comment by dlsniper** [comment]
@chic01taliano if your GOPATH is: `C:\Users\Alessandro\Documents\github.com` then you'll need to do the following:
- go to File | Settings | Languages & Frameworks | Go | Go Libraries and add an entry to the `Globral Libraries` section (if it's not present already) for `C:\Users\Alessandro\Documents\github.com`
- move your project from `C:\Users\Alessandro\Documents\github.com\chic01taliano\golang` to `C:\Users\Alessandro\Documents\github.com\src\github.com\chic01taliano\golang`
- create the project in IntelliJ from `C:\Users\Alessandro\Documents\github.com\src\github.com\chic01taliano\golang`
- in your import statement from `main` you need to change `./greeting` to `github.com/chic01taliano/golang/greeting`

Also, please upgrade your IDE to 2016.1.2b as older versions have a security issue, for more details please see: https://blog.jetbrains.com/blog/2016/05/11/security-update-for-intellij-based-ides-v2016-1-and-older-versions/

Finally, please have a look and understand how Go workspaces work. If you have any problems with this, please use the mailing list or the slack channel to get more help into setting up the project correctly.

**Comment by chic01taliano** [comment]
@dlsniper thanks for the heads up about Go's workspace: everything is in src now as it should be.
Import statement corrected, however, the issue remains.
To be noted that i had 2016.1.2 before i rolled back to 11.x because the new version has an issue refocusing the cursor on the editor after coming back from the terminal (Alt-F12)

**Comment by chic01taliano** [comment]
@zolotov i would appreciate your collaboration in testing this code under Webstorm 11. Thanks

**Comment by dlsniper** [comment]
@chic01taliano I'm not @zolotov but I'll say it again, your environment is not correctly configured which is most likely why you are getting that problem.

I'm using 0.10.1399, and while I'm on Linux, I hope this doesn't affect the outcome. Please see the screenshot below
![snapshot56](https://cloud.githubusercontent.com/assets/607868/15628881/f0ccc53e-2504-11e6-821d-b9dafc7fce1f.png)

Please follow _all_ the steps I've sent above,  didn't made any copy-paste mistake with the paths and anything. Please attach screenshots of your File | Settings | Languages & Frameworks | Go | Go Libraries opened with the IDE in the background, like in my screenshot. Thank you.

**Comment by zolotov** [comment]
>  but I'll say it again, your environment is not correctly configured which is most likely why you are getting that problem.

I think in this case `Rename` function would be unresolved as well.

@chic01taliano I've reproduced this for WS 11, investigating

**Comment by zolotov** [comment]
Fixed in upcoming nightly

**Comment by dlsniper** [comment]
I apologize for missing that. I was so driven by the "wrong" setup part (and it working on my machine) that I couldn't see the screenshot correctly.

**Comment by chic01taliano** [comment]
@zolotov that's great. Keep up the good work!
@dlsniper my workspace has been fixed after your advice.
