### ISSUE TITLE
Program arguments can't use in the debug mode

### ISSUE THREAD

**Issue by wang-xin** [go-lang-plugin-org/go-lang-idea-plugin#2550]
Program arguments ： add 1 2
Main func ： args := os.Args 

It can't use os.Args get arguments in the debug mode,but can use in the run mode.My operation system is windows7.

**Comment by dlsniper** [comment]
Please provide the IDE name and version and the plugin version.

**Comment by wang-xin** [comment]
IDE name : IntelliJ IDEA 15.0.2 
plugin version : 0.10.1296

from IntelliJ IDEA Repositories

**Comment by dlsniper** [comment]
Can you please provide a screenshot of the IDE when launching the debug action, specifically the Console tab of the debugger?

**Comment by wang-xin** [comment]
![debug image](https://cloud.githubusercontent.com/assets/17465385/15665087/543525c0-273b-11e6-8b77-2cc49edcf067.png)

**Comment by wang-xin** [comment]
[
![debug error2](https://cloud.githubusercontent.com/assets/17465385/15665162/db79afd8-273b-11e6-9391-2a036ad71150.png)
](url)

**Comment by wang-xin** [comment]
I input four arguments,but it can received one.

**Comment by dlsniper** [comment]
Hi, in your last image you've attached the Debugger tab. Please attach one with the Console tab. Thank you!

**Comment by wang-xin** [comment]
[
![debug error3](https://cloud.githubusercontent.com/assets/17465385/15665291/bec0c3b2-273c-11e6-9849-6da60fa36cdb.png)
](url)

[
![debug error4](https://cloud.githubusercontent.com/assets/17465385/15665301/c9cfda36-273c-11e6-9149-47fa06631060.png)
](url)

**Comment by dlsniper** [comment]
Please switch to the nightly release branch https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds and this should be fixed. If not, please upgrade your IDE to 2016.1.2b (you should do it anyway since it contains a critical security fix).

**Comment by wang-xin** [comment]
Thank you for your help.

**Comment by dlsniper** [comment]
Did it worked?

**Comment by wang-xin** [comment]
I have tried the first one.It did not worked.

**Comment by wang-xin** [comment]
I am downloading the version 2016.1.2b.

**Comment by dlsniper** [comment]
Hi, nightly is the second link there, the first one is Alpha

**Comment by wang-xin** [comment]
I have tried the nightly link.

**Comment by wang-xin** [comment]
[
![Uploading golang plugin resp.png…]()

](url)

**Comment by wang-xin** [comment]
[
![golang plugin resp](https://cloud.githubusercontent.com/assets/17465385/15669218/bb9a783a-2751-11e6-8f87-f7262803cfb5.png)
](url)

**Comment by wang-xin** [comment]
I have tried the version  2016.1.2b.It did not worked.
[
![debug golang error1](https://cloud.githubusercontent.com/assets/17465385/15695562/0357552e-27db-11e6-9a76-02d25bc88e35.png)
](url)

[
![debug golang error2](https://cloud.githubusercontent.com/assets/17465385/15695568/0e7cb656-27db-11e6-93cb-61465bfdbb86.png)
](url)

**Comment by wang-xin** [comment]
I have switched to the nightly release branch.After reinstall the plugin,it did not worked.

**Comment by wang-xin** [comment]
[
![debug error3](https://cloud.githubusercontent.com/assets/17465385/15695849/e433cc60-27dd-11e6-8f09-5cd5be17ba69.png)
](url)

![debug error4](https://cloud.githubusercontent.com/assets/17465385/15695854/ee7c5bc4-27dd-11e6-90b5-e75ac5be20f7.png)

**Comment by dlsniper** [comment]
That's odd, it should have been fixed in the delve version bundled with the plugin after 21st of April. I'll look over it. Thanks for helping out tracking this!

**Comment by wang-xin** [comment]
Is this problem related to delve version?Is there a way to adjust its version?

**Comment by wang-xin** [comment]
I have the same problem with my colleagues.

**Comment by wang-xin** [comment]
I have tried in the Mac OS X.It have already worked,but it have not worked in the windows 7.Their version are the same.

**Comment by wang-xin** [comment]
The IDE's version and plugin's version are same in the windows 7 and mac OS X.

**Comment by zolotov** [comment]
@wang-xin updated delve, please use upcoming nightly build with the fix
