### ISSUE TITLE
"Duplicate function name" inspection on Init function

### ISSUE THREAD

**Issue by zuoRambo** [go-lang-plugin-org/go-lang-idea-plugin#2553]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: PhpStorm 2016.1
- Build #PS-145.258, built on March 16, 2016
- JRE: 1.8.0_40-release-b132 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Java version: 1.8
- OS name and version: OS X EI Caption 10.11.4

- What are you trying to do?

- What would you expect to happen?
Init function should be allowed
```
The init function

Finally, each source file can define its own niladic init function to set up whatever state is required. (Actually each file can have multiple init functions.) And finally means finally: init is called after all the variable declarations in the package have evaluated their initializers, and those are evaluated only after all the imported packages have been initialized.

Besides initializations that cannot be expressed as declarations, a common use of init functions is to verify or repair correctness of the program state before real execution begins.
```
- What happens?
it report error by code inspector

**Comment by zolotov** [comment]
> What are you trying to do?

The question is still actual.

> Init function should be allowed

In what context?

> it report error by code inspector

What error?

> ```go
Please include a go sample to reproduce the issue
```
> Or include a screenshot / video of the issue.

Still actual

**Comment by zolotov** [comment]
closing due to lack of feedback
