### ISSUE TITLE
False positive `Assignment count mismatch`

### ISSUE THREAD

**Issue by ignatov** [go-lang-plugin-org/go-lang-idea-plugin#2554]
Assignment count mismatch: 2 = 1 less... (⌘F1) 
Checks variable declarations.

```go
foo() {
	a, b := (foo123())
}

func foo123 () (int, int) {
	return 1, 2
}
```

**Comment by dlsniper** [comment]
This appears to be fixed in: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2507

**Comment by dlsniper** [comment]
I'll close this for now, pending merge of that PR.
