### ISSUE TITLE
Incompatible with IDEA 2016.1.3

### ISSUE THREAD

**Issue by caizixian** [go-lang-plugin-org/go-lang-idea-plugin#2560]
- Plugin version (or commit hash): N/A, cannot install the plugin from JetBrains repo
```
IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by dlsniper** [comment]
Hi,

I cannot reproduce this. How are you trying to install the plugin? From where?
Thank you.

**Comment by caizixian** [comment]
@dlsniper Sorry, I think I encountered a cache issue. Now fixed.
