### ISSUE TITLE
autocomplete many variables

### ISSUE THREAD

**Issue by EagleMoor** [go-lang-plugin-org/go-lang-idea-plugin#2561]
- Plugin version (or commit hash): Version: 0.11.1295
- IDE name and version: PhpStorm
- Java version: inside in phpstorm
- OS name and version: Mac Os Capitan

```go
func dumpFile(filename string) (int, error) {
	f, err := os.Open(filename)
	if err != nil {
		return 0, err
	}

	buf := bufio.NewReader(f)

	for {
		line, err := buf.ReadString('\n')
		if err != nil {
			return 0, err
		}
	}

	return 0, nil
}
```
![screen shot 2016-06-10 at 17 07 33](https://cloud.githubusercontent.com/assets/1461295/15967286/15690f1e-2f38-11e6-8be8-c614ff920f9f.png)

**Comment by EagleMoor** [comment]
and in 'elf....' no found 'err' word, why its show?

**Comment by dlsniper** [comment]
> and in 'elf....' no found 'err' word, why its show?

The IDE has this feature in order to help you autocomplete longer words by using the initials only.
