### ISSUE TITLE
Plugin will not install

### ISSUE THREAD

**Issue by th3fallen** [go-lang-plugin-org/go-lang-idea-plugin#2562]
- Plugin version (or commit hash): 0.12.1495
- IDE name and version: 
```
PhpStorm 2016.2 EAP
Build #PS-162.844.9, built on June 8, 2016
PhpStorm EAP User
Expiration date: July 8, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
- Java version: 1.8.0_76
- OS name and version: OSX Yosemite

- What are you trying to do? Install plugin

- What would you expect to happen? it to install?

- What happens? It downloads but never installs

Or include a screenshot / video of the issue.
http://cl.ly/0j2t0x0o0Y1U

**Comment by dlsniper** [comment]
I think this is a platform issue, @zolotov?

**Comment by zolotov** [comment]
@th3fallen I've filed an issue at jetbrains tracker: https://youtrack.jetbrains.com/issue/IDEA-157452. Please attach logs there or here, you can find them via `Help | Show Logs in <file browser>` action

**Comment by zolotov** [comment]
should be fixed in the next eap
