### ISSUE TITLE
go program debug

### ISSUE THREAD

**Issue by HollisGW** [go-lang-plugin-org/go-lang-idea-plugin#2563]
- Plugin version (or commit hash):
- IDE name and version: idea 2016 1.2
- Java version:jdk 1.7
- OS name and version: mac 

why not debug setting?

**Comment by dlsniper** [comment]
Debugging is currently enabled for `Go Application` run configurations. Please make sure you are using one of those and then you should be able to have this running.

**Comment by HollisGW** [comment]
How to set it up？Can you give me an example ？Thanks

**Comment by konart** [comment]
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#debugging-a-go-project

**Comment by dlsniper** [comment]
I'll close this due to inactivity. Please reopen this if needed. Thank you.
