### ISSUE TITLE
support default golang project layout.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#2569]
If the plugin find that the GOPATH is not config and there is a src directory in the project root,and there is some .go file in some subdir of the src directory. 
The plugin should guess the GOPATH is the project root.

**Comment by dlsniper** [comment]
But how would this work if you don't have a single GOPATH entry? Or if you have a project which has a src inside it and you happen to open that one?

**Comment by bronze1man** [comment]
@dlsniper
How about the user touch an empty `.kmg.yml` file under the project root to indicate that he need this kind of project layout?
The user can then commit that file into git project so that his co-worker can skip the plugin config step.

**Comment by dlsniper** [comment]
`.kmg.yml` is not a wide-spread format for this. I have not heard of it before and even now it tells me nothing about what it does and what it is. Is it some sort of a dependency management tool? And even so, it still doesn't answer the above questions.

Do you really think that a configuration of < 1 minute (in case the GOPATH is not inferred automatically from the system) is such a big win?

**Comment by bronze1man** [comment]
> .kmg.yml is not a wide-spread format for this. I have not heard of it before and even now it tells me nothing about what it does and what it is. Is it some sort of a dependency management tool? And even so, it still doesn't answer the above questions.

How about a file named `.IdeaGOPATH` ?

> Do you really think that a configuration of < 1 minute (in case the GOPATH is not inferred automatically from the system) is such a big win?

So we should skip small optimization ? or you think it is too difficult to learn to use it?

**Comment by zolotov** [comment]
> So we should skip small optimization ? or you think it is too difficult to learn to use it?

it's good but it's better to reuse existing things for dependency/project management. 
Creating special files like .IdeaGOPATH or .kmg.yml looks like inventing yet another project management tool

**Comment by dlsniper** [comment]
> How about a file named .IdeaGOPATH ?

Definitely not, we have `.idea` folder already and people are surely not excited with that, to say the least. People are not excited with the prospect of having two files extra files in their repos even if that would mean fixing the vendoring issue once and for all.

Even once we'll have the vendoring tools agree on a format, we still won't be able to infer the GOPATH from a directory.
That's why the plugin either reads the environment variable or allows you to configure it manually.

**Comment by bronze1man** [comment]
I do have a project management tool use `.kmg.yml` https://github.com/bronze1man/kmg/blob/master/kmg/SubCommand/goCmd/Go.go

Do you have another popular one?

If you do not have that stuff.I think .IdeaGOPATH or .kmg.yml is good for me.

**Comment by dlsniper** [comment]
Right now there's a whole discussion about unifying vendoring tools to use a single common format. See: https://gophers.slack.com/messages/vendor/ (get the invite from here: https://invite.slack.golangbridge.org/ )

When that happens it still wouldn't avoid configuring the GOPATH as you want.

**Comment by bronze1man** [comment]
@dlsniper 
Thanks.
So the file should be something named like `.GoVendorManifest.json`
How about choose one name here,and then modify to the finial name after the discussion has a conclusion?

I think I do not need vendor stuff right now.
I write code that only dependency on two big lib project : kmg and go stdlib.
It looks like git submodule is enough for me.

**Comment by dlsniper** [comment]
@zolotov I don't see how we can support this for now or in the future unless changes happen in the Go toolchain. Should we close it for now?

**Comment by zolotov** [comment]
agreed
