### ISSUE TITLE
Unresolved reference when open etcd project

### ISSUE THREAD

**Issue by mqliang** [go-lang-plugin-org/go-lang-idea-plugin#2578]
- Plugin version (or commit hash):v0.11.1538
- IDE name and version:IDEA v2016.1.3
- Java version:1.8.0_71
- OS name and version: mac OSX v10.11.5

- What are you trying to do?
Use IDEA with go-lang-idea-plugin open [Etcd](https://github.com/coreos/etcd) project:
```
mkdir -p /Users/mqliang/Documents/NetEase/Etcd/src/github.com/coreos/
cd /Users/mqliang/Documents/NetEase/Etcd/src/github.com/coreos/
git clone https://github.com/coreos/etcd
export GOPATH=/Users/mqliang/Documents/NetEase/Etcd/Godeps:/Users/mqliang/Documents/NetEase/Etcd
ln -s /Users/mqliang/Documents/NetEase/Etcd/src/github.com/coreos/etcd/cmd/vendor /Users/mqliang/Documents/NetEase/Etcd/Godeps/src
```

- What would you expect to happen?

    go-lang-idea-plugin works fine

- What happens?
    Some "Unresolved reference" errors:

<img width="1280" alt="screen shot 2016-06-20 at 8 04 59 pm" src="https://cloud.githubusercontent.com/assets/12423751/16193605/c3bdf45c-3722-11e6-982f-18ee4557e83f.png">

NOTE: etcd put vendor folder in $PROJECT_DIR/cmd/vendor instead of $PROJECT_DIR/vendor, to avoid pollute other project which import etcd client.

**Comment by dlsniper** [comment]
Hi @mqliang, thanks for reporting.
Can you please attach a screenshot of: File | Settings | Languages & Frameworks | Go | Go Libraries?
Thank you.

**Comment by mqliang** [comment]
@dlsniper 
<img width="1279" alt="screen shot 2016-06-20 at 8 19 35 pm" src="https://cloud.githubusercontent.com/assets/12423751/16193936/8e4c1d06-3724-11e6-825a-b513527cb308.png">

**Comment by dlsniper** [comment]
That looks good, thanks. I think the problem is that you are doing 
```shell
/Users/mqliang/Documents/Etcd/src/github.com/coreos/etcd/cmd/vendor /Users/mqliang/Documents/Etcd/Godeps/src
```

instead of:
```
/Users/mqliang/Documents/Etcd/src/github.com/coreos/etcd/cmd/vendor /Users/mqliang/Documents/Etcd/Godeps
```
Can you please try with that?

Also, you shouldn't need the symlink if you run things from the plugin as it will take care of configuring the GOPATH when launching the application.

**Comment by dlsniper** [comment]
Actually, sorry, I got confused by the order of args for `ln`.

Can you move the "Godeps" outside of `Etcd`? If not, I''ll have a look later on, thank you.

**Comment by mqliang** [comment]
@dlsniper I try:
``
➜  ~ mkdir /Users/mqliang/Documents/NetEase/Godeps
➜  ~ ln -s /Users/mqliang/Documents/NetEase/Etcd/src/github.com/coreos/etcd/cmd/vendor /Users/mqliang/Documents/NetEase/Godeps/src
```

and set GOPATH as 

```
➜  etcd git:(proxy-compact) ✗ go env    
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mqliang/Documents/NetEase/Godeps:/Users/mqliang/Documents/NetEase/Etcd"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

The problem still exists.

**Comment by dlsniper** [comment]
Ok, I'll have a look to confirm it and see why it happens, thanks for the help.
It might be because of the symlink but I can know for sure right now.

**Comment by mqliang** [comment]
@dlsniper You could reproduce this problem by creating a etcd project. Even if I copy the whole $PROJECT_DIR/cmd/vendor/ to $Godeps/src, or running `godep restore` in $PROJECT_DIR/cmd, the problem still exists.

**Comment by dlsniper** [comment]
will do, thanks. Unfortunately I'm at work now so it has to wait a bit to check it out (unless @zolotov picks it up before I can dig into it a bit)

**Comment by mqliang** [comment]
@dlsniper Never mind. Take your time.

**Comment by dlsniper** [comment]
Hi @mqliang I think I've got this working correctly.
Here are the steps I've done:
```bash
mkdir ~/etcd
ln -nfs $GOPATH/src/github.com/coreos/etc/cmd/vendor ~/etc/src
```
Then in the IDE, I've set the `Project Libraries` as `~/etcd` and created a project by opening `$GOPHAT/src/github.com/coreos/etcd`. You then have to open a Go file, change the module type to Go (prompted by a yellow bar on top of the opened file) and that's it.

You might need to wipe your `.idea` folder and any `.iml` files for this to work.

Please let me know if this worked out for you.


@zolotov since this seems to emerge as a common pattern to the projects such as etcd in order to fix some vendoring issues, do you think it's feasible to support detecting a `$PROJECT_ROOT/cmd/vendor` folder besides the regular `$PROJECT_ROOT/vendor` folder?

And finally, could we display in the `Go Libraries` that vendoring is used from a certain directory? I'm thinking something like we have for the GOPATH where it appears in the `Global Libraries` have the vendor path appear under `Project Libraries`. What do you think?

Should I open two issues for these things?

**Comment by zolotov** [comment]
@dlsniper I didn't understand anything.

> And finally, could we display in the Go Libraries that vendoring is used from a certain directory? 

What does it mean? vendoring is not related to any particular directory, there is not such thing as `vendor path`

**Comment by mqliang** [comment]
@dlsniper It works fine. Great thanks!

**Comment by dlsniper** [comment]
> @dlsniper I didn't understand anything.

Sorry, I'll try to be more clear.
Right now the plugin is checking for `vendor/` directory in the root of the project, correct?
If so, I wonder if we could also make it check for `cmd/vendor` as this is a common pattern to avoid vendor pollution for projects which are both libraries and binaries (like etcd is).

> And finally, could we display in the Go Libraries that vendoring is used from a certain directory?
What does it mean? vendoring is not related to any particular directory, there is not such thing as vendor path

Ok, that makes sense.

**Comment by zolotov** [comment]
> Right now the plugin is checking for vendor/ directory in the root of the project, correct?

No, it doesn't check anything like this
