### ISSUE TITLE
Can only install version 0.11.1295 on IntelliJ Idea 2016.1.3

### ISSUE THREAD

**Issue by jtblin** [go-lang-plugin-org/go-lang-idea-plugin#2580]
- Plugin version (or commit hash): 0.12.1518
- IDE name and version: IntelliJ Idea 2016.1.3
- Java version:
- OS name and version: 

- What are you trying to do?
I'd like to install the latest plugin but it looks I can only install 0.11.1295 whereas I can see 0.12.1518 has been released in https://plugins.jetbrains.com/plugins/alpha/5047 and release page indicates latest version is 1.0.0.alpha#1288.

- What would you expect to happen?
Maybe I don't understand how the versioning works but I'd like to install the latest plugin as I'm getting some serious performance issues lately. 

- What happens?

When I download Go-0.12.1518.zip and try to install it manually I get an error message saying it is incompatible with my version of IntelliJ.

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by zolotov** [comment]
If you want to install the latest builds you should use plugin's nightly channel or IDEA EAP

**Comment by jtblin** [comment]
When I add the nightly build url, IntelliJ doesn't show any available plugin.

**Comment by dlsniper** [comment]
@jtblin Hi, can you remove any previously installed Go plugin then restart IDEA? After that, if the issue still happens, please attach a picture of the Plugin manager window with the nightly repository selected as source. If you have any issues doing this, please let us know.

**Comment by jtblin** [comment]
Thanks. Huh, it worked this time after I deleted the url alpha repo url as well, not sure if that's related. So now I have access to 0.11.1544 which still seems to be far away from 0.12.1518 or 1.0.0.alpha#1288. Is that expected?

**Comment by dlsniper** [comment]
Yes, that's fine. 0.11.x is for 2016.1 IDEs, 0.12.x is for 2016.2 IDEs, see the naming convention in the README. Happy it worked for you. If you have any further issues, please let us know.

**Comment by dlsniper** [comment]
P.S. The plugin for 2016.1 IDEs has in fact newer features that the one for 2016.2 at the time of writing this.

**Comment by jtblin** [comment]
Ok, thanks for the info.

**Comment by jtblin** [comment]
And great work for the plugin btw, best Go IDE experience IMHO 👍
