### ISSUE TITLE
Types of constans expressions differ https://golang.org/ref/spec#Constant_expressions

### ISSUE THREAD

**Issue by grenki** [go-lang-plugin-org/go-lang-idea-plugin#2584]
- Plugin version (or commit hash):
commit a91131858072f400e6d04bf1c38b14c40e9e0193
- IDE name and version:
IntelliJ IDEA (Community Edition) 2016.2 EAP
Build #IC-162.105, built on May 11, 2016
- Java version:
JRE: 1.8.0_76-release-b66 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: 
Ubuntu 16.04 LTS

- What are you trying to do?
- What would you expect to happen?
- What happens?
I try to getGoType(null) from untyped constants and types from some expressions differ to golang spec
const a = 2 + 3.0       expected:  a == 5.0   (untyped floating-point constant)  actual type : int
const j = true             expected:  j == true  (untyped boolean constant)           actual type : null
const Σ = 1 - 0.707i   expected:  (untyped complex constant)                         actual type : int

**Comment by ignatov** [comment]
Feel free to impove it
