### ISSUE TITLE
Add support for IntelliJ EAP (162.1120.6)

### ISSUE THREAD

**Issue by albertsj1** [go-lang-plugin-org/go-lang-idea-plugin#2588]
- Plugin version (or commit hash): using nightly URL: https://plugins.jetbrains.com/plugins/nightly/5047
- IDE name and version: IntelliJ IDEA 2016.2 EAP (162.1120.6)
- Java version: 1.8.0_91-b14
- OS name and version: osx 10.11.5

- What are you trying to do? Install the latest nightly on new 2016.2 IntelliJ EAP

- What would you expect to happen? IntelliJ should show the go-lang-idea plugin as available to install.

- What happens? Running 'check now' when adding the URL shows 'no plugins found'

A new release of IntelliJ EAP is out 2016.2 (162.1120.6) is out.  Please add support for this new release.

**Comment by dlsniper** [comment]
Please hold off with updates on EAPs next time. It usually takes a couple of days until the plugin is updated to support the new IDE version.
