### ISSUE TITLE
File watchers are activated every time I write

### ISSUE THREAD

**Issue by dashaus** [go-lang-plugin-org/go-lang-idea-plugin#2590]
- Plugin version (or commit hash): nightly
- IDE name and version: 2016.1.3
- Java version: 1.8
- OS name and version: El Capitan OS X

- What are you trying to do?

Coding

- What would you expect to happen?

Nothing

- What happens?

File watchers are activated every time I write (Impossible to code). I had to return to old version (alpha).

**Comment by dlsniper** [comment]
@dashaus which nightly have you used? Also why do you need FileWatchers? What's your configuration? Can you share more details to make this repeatable?

**Comment by dashaus** [comment]
gofmt and goimports as file watchers. The nightly is the latest.

**Comment by dashaus** [comment]
immediate file synchronization desactivated in both file watchers.

**Comment by dashaus** [comment]
![captura de pantalla 2016-07-01 a las 1 08 53](https://cloud.githubusercontent.com/assets/1870208/16508175/6d0117e4-3f28-11e6-8fbe-648017c52c7d.png)
![captura de pantalla 2016-07-01 a las 1 08 49](https://cloud.githubusercontent.com/assets/1870208/16508174/6cfefda6-3f28-11e6-9b9e-56a443e30ee4.png)

**Comment by dlsniper** [comment]
@dashaus the nightly still has a version, please specify it.

**Comment by dlsniper** [comment]
As for that usage case, you can bind a shortcut to goimports so that you don't need the file watcher plugin to do the save + invoke goimports.

**Comment by dashaus** [comment]
the nightly is the latest. I don't remember the version but is the last available today.

**Comment by dashaus** [comment]
I want that when I save the files then it invokes the file watchers.

**Comment by dashaus** [comment]
I think that is more comfortable to me.

**Comment by dlsniper** [comment]
If you assign a shortcut to goimports it will do a save (which you do now) and run goimports automatically (which filewatcher does).

**Comment by dlsniper** [comment]
Anyway, thank you for reporting, I hope it's enough info for Alexander / Sergey to look into it.

**Comment by dashaus** [comment]
How assign a shortcut to goimports?

**Comment by dlsniper** [comment]
See: https://www.jetbrains.com/help/idea/2016.1/configuring-keyboard-shortcuts.html and search for goimports / go fmt actions.

**Comment by dashaus** [comment]
thanks!

**Comment by jerome-laforge** [comment]
I think you can find a way how to configure Intellij to enable file watcher only on save (by disabled the autosave):
https://rootpd.com/2016/02/04/setting-up-intellij-idea-for-your-first-golang-project/

**Comment by dlsniper** [comment]
I think we should close this. Let me know if I was wrong. Thank you.
