### ISSUE TITLE
Program arguments  is  out of action in debug mode

### ISSUE THREAD

**Issue by aqualee** [go-lang-plugin-org/go-lang-idea-plugin#2591]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: Intellij IDEA 2016.1.3 Build #IU-145.1617
- Java version: 1.8.0_31
- OS name and version: windows7

Program arguments  is  out of action in debug mode,but  works well in run mode

**Comment by dlsniper** [comment]
Hi, please try the nightly, it should be fixed there https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by dlsniper** [comment]
Closing as duplicate of https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2550
