### ISSUE TITLE
Quick Documentation Ctrl+Q omits channel <- operator from func parameter list

### ISSUE THREAD

**Issue by jhngrant** [go-lang-plugin-org/go-lang-idea-plugin#2596]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: WebStorm 2016.1.3 Build #WS-145.1616, built on May 27, 2016
- Java version: JRE: 1.8.0_77-b03 x86
- OS name and version: Windows 10

- What are you trying to do?
View Quick Documentation (Ctrl+Q) of the following function:
```Go
func ImportStream(src func(chan<- []interface{}) error, sink string) {
...
}
```
- What happens?
Channel **<-** operator missing:

![quick-documentation](https://cloud.githubusercontent.com/assets/5324735/16534249/4017b19e-3fd6-11e6-8a2f-43348f095344.png)

**Comment by dlsniper** [comment]
Hi,

Thanks for reporting.
Please try the latest nightly as this seems to be fixed there, https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds
Let me know how it works out.

Thank you!

**Comment by jhngrant** [comment]
@dlsniper Thanks for your quick response.
I confirm 0.11.1582 has fixed the issue.
Cheers.

**Comment by dlsniper** [comment]
Great, thanks for the update.
