### ISSUE TITLE
failure to resolve type in nested switch

### ISSUE THREAD

**Issue by cirel10** [go-lang-plugin-org/go-lang-idea-plugin#2597]
- Plugin version (or commit hash):
Version: 0.11.1295

- IDE name and version:
IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- Java version:
- OS name and version: 
OSX Version 10.11.5

- What are you trying to do?
Get syntax highlighting / resolution. See sample code.

- What would you expect to happen?
Proper recognizing of type.

- What happens?
IntelliJ reports "Unresolved reference 'Format'" for a variable used in a double switch. IntelliJ highlights the word "Format" in red (see code below) and won't drill down to the function via Go To Declaration. The program runs fine; this appears to be syntax highlighting + inability to resolve the type within IntelliJ.

```go

package main

import "fmt"
import "time"

func main() {
	var s *string = new(string)
	var dest interface{}
	dest = s

	t := time.Time{}
	var z interface{}
	z = t

	switch s := z.(type) {
	case time.Time:
		formatted := s.Format(time.RFC3339Nano) // this resolves fine
		_ = formatted
		case *string:
			*d = s.Format(time.RFC3339Nano) // this is flagged by IntelliJ
		}
	}

	fmt.Println(*s)
}
```

**Comment by dlsniper** [comment]
Hi, your code is incorrect, there's an extra closing brace in the case.
More over, `*string` type doesn't have a `Format()` method attached to it so it's not a problem in the plugin, but in the code.
If you need help with the code I'd recommend the [Gophers Slack](https://gophers.slack.com/messages/golang-newbies/), get the [invite from here](https://invite.slack.golangbridge.org/)

**Comment by cirel10** [comment]
That's what I get for editing after pasting. The code is correctly pasted below. Should I open a new bug?

```go
func main() {
	var s *string = new(string)
	var dest interface{}
	dest = s

	t := time.Time{}
	var z interface{}
	z = t

	switch s := z.(type) {
	case time.Time:
		formatted := s.Format(time.RFC3339Nano) // this resolves fine
		_ = formatted
		switch d := dest.(type) {
		case *string:
			*d = s.Format(time.RFC3339Nano) // this is not allowed
		}
	}

	fmt.Println(*s)
}
```

**Comment by dlsniper** [comment]
Please try the latest nightly, the issue should be fixed there: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds If it's not, please ping me and I'll reopen this. Thank you.

**Comment by dlsniper** [comment]
Did it worked?
