### ISSUE TITLE
Unresolved field after applying `Delete redundant type declaration` quickfix

### ISSUE THREAD

**Issue by zolotov** [go-lang-plugin-org/go-lang-idea-plugin#2601]
<img width="450" alt="screenshot 2016-07-04 01 10 48" src="https://cloud.githubusercontent.com/assets/140920/16547878/3e49438c-4184-11e6-95fb-a59f69f55844.png">

<img width="354" alt="screenshot 2016-07-04 01 10 56" src="https://cloud.githubusercontent.com/assets/140920/16547879/41075834-4184-11e6-910e-cdfd12763dfa.png">

**Comment by deadok22** [comment]
Was about to report the same problem:
![redundant-type-decl](https://cloud.githubusercontent.com/assets/1259620/16575590/73dff5b8-42c4-11e6-9946-43023f10907f.png)
![redundant-type-decl-after](https://cloud.githubusercontent.com/assets/1259620/16575591/73e2038a-42c4-11e6-9215-1be075aed592.png)
