### ISSUE TITLE
Debugging main package fails with 'could not launch process error'

### ISSUE THREAD

**Issue by silasdavis** [go-lang-plugin-org/go-lang-idea-plugin#2614]
I am running:

Go plugin version: 0.11.1636

Operating system: Arch Linux; 4.6.3-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

After creating a 'Build main.go and run' go app run configuration by selecting Build > Run on a file, I then try to debug run that configuration. It fails with:

```
could not launch process: Unreadable version number: could not read string len input/output error
```

It does not seem to matter which main package I try to run.

I note this has the same error as the ticket: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2360, which references https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2599 as a fix, but for me that does not seem to be the case.

I have also tried on Intellij 2012.2 and both the alpha and nightly channels.

My local version of delve is from master, but I believe that is not relevant as the plugin ships its own.

**Comment by dlsniper** [comment]
Do you have a sample of code which can help reproduce this? And on what OS are you on?

**Comment by silasdavis** [comment]
Added OS (Arch Linux). I tried with a completely minimal hello world main.go and it does indeed work.

I'll try and create a minimal example, could you suggest a non-trivial go project where debugging does work and I can try and work from there? I just tried with https://github.com/mitchellh/packer, which doesn't give the error, but nor does it actually stop at my breakpoints.

**Comment by dlsniper** [comment]
The IDE will print out the commands that it runs, if you run them can you replicate with delve itself? You've mentioned you also have that installed. Thank you.

**Comment by silasdavis** [comment]
The issue seems to be down to delve. I've failed to create a minimal example so far, but I can make the issue go away if I do not import a certain package. In delve what fails is it trying to read: `runtime.buildVersion`:

https://github.com/derekparker/delve/blob/master/proc/proc.go#L786

When I import a particular package of mine I get the `could not launch process: Unreadable version number: could not read string len input/output error`. Here is the line in delve that produces it: 

https://github.com/derekparker/delve/blob/master/proc/variables.go#L857

I guess I should take this upstream. But before I do in case you have any insight, do you understand what delve is trying to do here, and why it might fail when a certain import is used?

**Comment by silasdavis** [comment]
Ah hah! I think this is it: https://github.com/derekparker/delve/issues/477 

I probably do have some native c bindings, will verify. Thanks for you assistance.
