### ISSUE TITLE
Inspection in infinite loop

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2615]
Given the following code: https://play.golang.org/p/fKHZXlvtfo

The inspection which causes this is: ` Unused function inspection `

Plugin Version: 0.12.1625
IntelliJ IDEA 2016.2
Build #IU-162.1121.10, built on July 5, 2016
Licensed to Florin Patan
You have perpetual fallback license for this version
Subscription is active until January 26, 2018
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

There's at least one inspection which never ends (looks line an infinite loop).
I'll try and investigate and see further into it.

**Comment by dlsniper** [comment]
After further investigation, it doesn't look like an infinite loop but rather the issue comes from my rather large GOPATH and this function call: ` ReferencesSearch.search(o, o.getUseScope()).findFirst() `. Is it possible to somehow limit the scope for usage only to the current project but not libraries?

**Comment by zolotov** [comment]
> Is it possible to somehow limit the scope for usage only to the current project but not libraries?

A scope is limited according to resolving rules, if you have an example where a scope is unreasonable wide, attach the code, please.

**Comment by dlsniper** [comment]
The code is in the playground example link, I'll try and get a profile from IDEA. It seems I'll need to run this against the installed IDEA since I can't launch a profiling instance `Go` from the plugin sources.

**Comment by zolotov** [comment]
```
func Check(err error){

}
```

That's enough to include libraries for checking whether `Check` function is used

**Comment by zolotov** [comment]
Now all scope restrictions are located here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/util/GoPathUseScope.java and https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/util/GoPathScopeHelper.java

**Comment by dlsniper** [comment]
Here's a snapshot and a video for the issue: https://youtu.be/-SXoaGa8Xag
The video corresponds to the profile after 2:12 until then IDEA was starting / loading files etc.
[snapshot.tar.gz](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/355497/snapshot.tar.gz)

I'll take a look at the files you've mentioned, thank you.

**Comment by zolotov** [comment]
Snapshot is useless. IDEA loads files to check whether there are references or not. Well, ok, it should do it.
