### ISSUE TITLE
Call hierarchy for Go

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2616]
Breadcrumbs for Java were added a couple of EAPs ago in 2016.2, https://blog.jetbrains.com/idea/2016/06/intellij-idea-2016-2-eap-adds-breadcrumb-for-java/ , I wonder if we could add them for Go as well.
They should function by showing the path from `package main` to the location so that it provides a call stack but I fear that it is very early in the plugin stage that we can do this.
Is there any documentation that could help out with the implementation?

**Comment by zolotov** [comment]
We can but I don't want to. At least until IDEA has an option to disable them by language

**Comment by dlsniper** [comment]
@zolotov maybe I wasn't very clear. I was thinking of adding the breadcrumbs to define a call stack from say `main()` (or if we don't have a `main() in the project from the package root I guess?) to the location in which the cursors is currently is.
That would really be helpful and I see it being asked often in Slack (related to Go not the plugin itself) if there's a tool to get the call stack diagram for an app. If getting the call stack is doable then this would be a really great addition for functionality.

**Comment by zolotov** [comment]
Do you something like #1930?

**Comment by dlsniper** [comment]
Yes, something like that. I guess we can close this as a duplicate then?

**Comment by PerMildner** [comment]
The title for this ticket is confusing (after it was renamed). As far as I can tell it is not about the command/feature that IntelliJ calls "Call Hierarchy".
