### ISSUE TITLE
Create function quickfix does not always allow setting a name

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2653]
Plugin version: 0.12.1625
IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
Licensed to Florin Patan
You have perpetual fallback license for this version
Subscription is active until January 26, 2018
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- What are you trying to do?
Use the quickfix to create a new function and give parameter names custom names

- What would you expect to happen?
Once a parameter name has been set, it should remain like that upon pressing Enter

- What happens?
The parameter name remains in the suggested by the plugin form not the name I desire it to be.

```go
package main

import "net/http"

func demo(w http.ResponseWriter, r *http.Request) {
	_ = greet(w, r) // create this function
}
```

I would like to create the following function:
```go
func greet(w http.ResponseWriter, r *http.Request) interface{} {
}
```

The problem happens because I want to type a name which starts with the suggested name and thus confuses the plugin, see here: https://youtu.be/DytfOn-6O5k

**Comment by zolotov** [comment]
1. it has nothing to do with plugin
2. unlikely it will be fixed: https://youtrack.jetbrains.com/issue/IDEABKL-6454

**Comment by dlsniper** [comment]
can we at least make the first suggestion to be what the user types? especially for http handlers this is unfortunate.

**Comment by zolotov** [comment]
do you mean change completion on each typing? no

**Comment by zolotov** [comment]
if you want to custom name, press Esc. It's quite straightforward: do not want completion – close completion

**Comment by dlsniper** [comment]
Sure, the issue is that then I would need to jump manually to each entry and change it vs just pressing enter/tab but I guess I can live with that. Thank you.
