### ISSUE TITLE
Move 'Go File' to proper context menu location

### ISSUE THREAD

**Issue by kevin-ashton** [go-lang-plugin-org/go-lang-idea-plugin#2654]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: Webstorm
- OS name and version: MacOS

Really this is just a minor request. It is annoying that 'Go File' shows up at the top when creating new files and not in the language specific language area. No other language specific plugin I am aware of does this. I assume I'm not the only developer that typically hits the 'File' menu item and then specifies the file extension. 

![image](https://cloud.githubusercontent.com/assets/1718984/16808983/dd5d7368-48db-11e6-8d49-868d96761c32.png)

**Comment by zolotov** [comment]
There is no such thing as `language specific area`

<img width="236" alt="screenshot 2016-07-13 18 33 26" src="https://cloud.githubusercontent.com/assets/140920/16809283/632cfe36-4928-11e6-9a06-88cebff212cd.png">

**Comment by kevin-ashton** [comment]
I suppose I made that assumption based upon the grouping of files within Webstorm, since all web related files are within the 2nd grouping. Regardless it appears to be fairly inconsistent between Jetbrain products.
