### ISSUE TITLE
Inspection "Direct assignment to struct field in map"

### ISSUE THREAD

**Issue by fgrosse** [go-lang-plugin-org/go-lang-idea-plugin#2655]
Plugin version: **0.12.1680**

After the last update I get multiple false error reports in my projects from the Go Inspection "Direct assignment to struct field in map". The issue is that this inspection now also triggers when assigning to struct fields in _slices_ which is entirely legal.

```go
package main

import (
	"fmt"
)

func main() {
	type foo struct{ Name string }
	foos := []foo{
		{"Foo1"},
		{"Foo2"},
		{"Foo3"},
	}

	for i := range foos {
		foos[i].Name = foos[i].Name + " Updated" // inspection marks this line as error
	}

	fmt.Println(foos)
	// Output: [{Foo1 Updated} {Foo2 Updated} {Foo3 Updated}]
}
```

https://play.golang.org/p/D-vk0DMiYj

----

IDE, Java, OS versions available in the details below (click arrow)
<details>
- IDE name and version:
PhpStorm 2016.2
Build #PS-162.1121.38

- Java version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

- OS name and version: 
Linux Fedora 4.4.13-200.fc22.x86_64
</details>

**Comment by dlsniper** [comment]
Thank you for the very thorough report, I wish all of them would be like this. Sorry for the inconvenience, I'll try to get this fixed as soon as possible.

**Comment by dlsniper** [comment]
Meanwhile you can disable the inspection as a temporary workaround.

**Comment by dlsniper** [comment]
hi @fgrosse I cannot replicate the issue with 0.12.1680. using IntelliJ, see this: http://i.imgur.com/LlKt5Ks.png
I'll try with PhpStorm as soon as I have a chance but I doubt this would yield different results.

Does this happen if you type the code or perform any special action?

**Comment by dlsniper** [comment]
Just tested in PHPStorm as well, still can't replicate it, I'll add a test for it later on. Please send a screenshot and steps to reproduce this as I'm clueless right now. Thank you.

**Comment by fgrosse** [comment]
Ok seems like I was a bit hasty when pinning down the issue and creating an example this morning.

There is a reproducable issue but it is has nothing to do with slices but with maps: Assignment to struct fields of map entries is legal if the entry is referred to by a pointer.

Code ro reproduce (for real this time):
```go
package main

import (
	"fmt"
)

func main() {
	type foo struct{ Name string }

	foos := map[string]*foo{
		"1": {"Foo1"},
		"2": {"Foo2"},
		"3": {"Foo3"},
	}

	for key := range foos {
		foos[key].Name = foos[key].Name + " Updated" // inspection marks this line as error
	}

	for k, v := range foos {
		fmt.Println(k, v)
	}
	// Output looks something like this:
	// 1 &{Foo1 Updated}
	// 2 &{Foo2 Updated}
	// 3 &{Foo3 Updated}
}
```

Apologies for leading you in thr worng direction and thx in advance for the fast responses and the **awesome** plugin

**Comment by dlsniper** [comment]
@fgrosse thanks for the update, I can confirm the issue with the new code.
