### ISSUE TITLE
Printf format placeholder checker false positive if the format is a variable

### ISSUE THREAD

**Issue by bits01** [go-lang-plugin-org/go-lang-idea-plugin#2659]
If you use a variable for the Printf format, the format placeholder checker returns a false positive and highlights the code. It should not try to be smart in this case, it has no way of properly checking unless one uses a constant string for the format.

See attachment.

<img width="577" alt="format" src="https://cloud.githubusercontent.com/assets/10517679/16853709/6724954a-49c2-11e6-9b4c-4ba1fcfa77d7.png">

**Comment by dlsniper** [comment]
Ah, screenshots, the bane of copy-paste :P

But thanks for the report, fixed in: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2661
