### ISSUE TITLE
Type inference style variable creation

### ISSUE THREAD

**Issue by rambocoder** [go-lang-plugin-org/go-lang-idea-plugin#266]
While creating a Revel interceptor I came across this bug:
```
type Traceable struct {
	*revel.Controller
}

func (c *Traceable) Begin() revel.Result {
	return c.RenderText("Intercepted")
}
func init() {
	// type inference and variable assignment below is highlighed 
	p := (*Traceable).Begin
	revel.InterceptMethod(p, revel.BEFORE)
}
```
while without type inference it is fine:
```
var p interface{}
p = (*Traceable).Begin
revel.InterceptMethod(p, revel.BEFORE)
````

**Comment by rambocoder** [comment]
@dlsniper in the 1.0-alpha the code is not highlighted as invalid, however the code suggestion does not kick in when I do (*Traceable). (Ctrl+Space)

I agree that we should close this for now.

**Comment by dlsniper** [comment]
@rambocoder can you please open a different ticket for the autocomplete issue? And possibly a small snippet to reproduce? If not, I'll create one but I need as many details as possible to create one.
Thank you!
