### ISSUE TITLE
Plugin cann't be installed from disk

### ISSUE THREAD

**Issue by Viktorrrr** [go-lang-plugin-org/go-lang-idea-plugin#2675]
- Plugin version (or commit hash): 0.12
- IDE name and version: 2016.1.3
- Java version: 1.8.0_91
- OS name and version: Windows 10

- What are you trying to do?
I'm trying to install plugin from disc.
- What would you expect to happen?
I expect this plugin will be installed.
- What happens?
I see error message.

![image](https://cloud.githubusercontent.com/assets/20494468/16897058/d8bb1c54-4bae-11e6-8951-1dfd48d3007e.png)

Hi, guys!
I am trying to install this plugin from disc but something wrong. 
It's installing from repositories very well but in my case I have no internet at a job. 
Thanks!

**Comment by dlsniper** [comment]
Please see this table: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#release-versions-schema

In your case, you must download the 0.11.xyz releases since they are the ones for 2016.1 IDEs.

Please let me know if you have any further issues with this.

**Comment by Viktorrrr** [comment]
Sorry, I don't pay attantion this table. I have updated IDE up to 2016.2. But problem don't resolved.
I have found the strangeness when I am installing plugin from repositories its size is 12,4 M. And when I am downloading it from github.com its size is 1.8 M (or unpacked 5.2 M).

**Comment by Viktorrrr** [comment]
Sorry, I don't pay attantion this table. I have updated IDE up to 2016.2. But problem haven't resolved.
I have found the strangeness when I am installing plugin from repositories its size is 12,4 M. And when I am downloading it from github.com its size is 1.8 M (or unpacked 5.2 M).

**Comment by dlsniper** [comment]
According to this page https://plugins.jetbrains.com/update/index?pr=idea&updateId=27180 (and from building the plugin manually), the plugin should indeed be at least 12M,which would suggest that the problem is on your end. Try downloading it via https.

The only other option is to build the plugin from sources.

**Comment by Viktorrrr** [comment]
It works! I tryed to install plugin manager (from github) as golang plugin. It was wrong. I'm sorry...
Link for directly plugin is https://plugins.jetbrains.com/plugin/5047?pr=idea
Thanks a lot! Your product is great))
