### ISSUE TITLE
Complete tags with their snake style field names

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2677]
After this tweet: https://twitter.com/fatih/status/754477622042689536 I've got two separate requests from two different users so maybe it's something that we should provide as an option if possible?

**Comment by zolotov** [comment]
![json_xml_live_templates](https://cloud.githubusercontent.com/assets/140920/16901563/177d79fe-4c50-11e6-8602-d8c639cccca2.gif)

**Comment by dlsniper** [comment]
That's so awesome! Thank you!
