### ISSUE TITLE
Test status is reported incorrectly if output contains "--- FAIL"

### ISSUE THREAD

**Issue by nmiyake** [go-lang-plugin-org/go-lang-idea-plugin#2678]
- Plugin version (or commit hash): 0.10.1679
- IDE name and version: IntelliJ IDEA 15 Community Edition 15.0.6
- Java version: 1.8.0_65
- OS name and version: OS X El Capitan 10.11.5

- What are you trying to do?
Run tests that contain a `fmt.Printf` or `t.Logf` statement that prints `--- FAIL:`

- What would you expect to happen?
Tests run, print the specified output, complete, and are marked as passing.

- What happens?
Lines that start with `--- FAIL:` are not shown as part of the test output, and the string that comes after `FAIL:` is reported as a failing test, which causes the tests to show as failed.

When the same test is run using `go test -v`, the output and reporting is correct.

```go
package badtest

import (
	"fmt"
	"testing"
)

func TestPrintfOkay(t *testing.T) {
	// this line is okay -- test passes and prints output
	fmt.Printf("--- FAIL: TestRun (from fmt.Printf)")
}

func TestPrintfBad(t *testing.T) {
	// this causes IntelliJ to report that "PhantomTest" has failed, and output is not available anywhere
	fmt.Printf("--- FAIL: PhantomTest (from fmt.Printf)\n")
}

func TestLogf(t *testing.T) {
	// this causes IntelliJ to report that "NonexistentTest" has failed, and output is not available anywhere
	t.Logf("--- FAIL: NonexistentTest (from t.Logf)")
}
```

Tests reported as failing in IntelliJ:
![intellij_fail](https://cloud.githubusercontent.com/assets/4267425/16900002/cab6c136-4bcb-11e6-8f23-84364e0ff9d5.png)

Tests passing with all output using `go test -v`:
![gotest_pass](https://cloud.githubusercontent.com/assets/4267425/16900003/cab6b452-4bcb-11e6-8b4c-458ddcd8c070.png)

**Comment by dlsniper** [comment]
The problem in your case is that there's no new line at the end of each line and thus confuse the test parser.
Is this something that happens when you run proper tests or it's specific only to the code above?

**Comment by dlsniper** [comment]
see this: https://play.golang.org/p/_sn1VaZTgW

![snapshot102](https://cloud.githubusercontent.com/assets/607868/16900112/ef108dea-4c12-11e6-8db1-fdd5be9aefe8.png)

**Comment by nmiyake** [comment]
The code above was a simplification showing the minimal possible case. This is something I ran into for real code.

The use case is that I wanted to test a tool that would re-format the output of `go test` in certain ways. It reformats certain parts of the output, but does maintain the same format for `ok` and `FAIL`.

The problem I ran into was when trying to print output to the console to debug or print failure messages. Here's a more realistic test that illustrates the issue:

```go
package demo_test

import (
	"testing"
)

func TestActualCase(t *testing.T) {
	expected :=
`MyTest:
--- FAIL: Test output from other tool`
	actual := "not expected"

	if expected != actual {
		t.Errorf("Differed.\nExpected: %v\nActual: %v\n", expected, actual)
	}
}
```

IntelliJ output:

```
/usr/local/go/bin/go test -v github.palantir.build/deployability/badtest -run ^TestActualCase$
	foo_test.go:14: Differed.
		Expected: MyTest:
				Actual: not expected
exit status 1
FAIL	github.palantir.build/deployability/badtest	0.056s
```

`go test -v` output:

```
➜  badtest go test -v
=== RUN   TestActualCase
--- FAIL: TestActualCase (0.00s)
        foo_test.go:14: Differed.
                Expected: MyTest:
                --- FAIL: Test output from other tool
                Actual: not expected
FAIL
exit status 1
FAIL    github.palantir.build/deployability/badtest     0.049s
```

The IntelliJ output is really confusing because it displays part of the output but consumes/hides the `--- FAIL` line. This is even true when trying to print the output in a quoted manner using `%q`:

```go
package demo_test

import (
	"testing"
)

func TestActualCase(t *testing.T) {
	expected :=
`MyTest:
--- FAIL: Test output from other tool`
	actual := "not expected"

	if expected != actual {
		t.Errorf("Differed.\nExpected: %q\nActual: %q\n", expected, actual)
	}
}
```

IntelliJ:

```
/usr/local/go/bin/go test -v github.palantir.build/deployability/badtest -run ^TestActualCase$
	foo_test.go:14: Differed.
		Expected: "MyTest:\n		Actual: "not expected"
exit status 1
FAIL	github.palantir.build/deployability/badtest	0.055s
```

`go test -v`:

```
=== RUN   TestActualCase
--- FAIL: TestActualCase (0.00s)
        foo_test.go:14: Differed.
                Expected: "MyTest:\n--- FAIL: Test output from other tool"
                Actual: "not expected"
FAIL
exit status 1
FAIL    github.palantir.build/deployability/badtest     0.052s
```

The latter was surprising to me -- I would have expected whatever is parsing the output to not have considered things in quotes/that don't literally start the line, but it's even stripping from within there.

This ended up taking a bunch of my time because I was trying to fix a test that was failing, but since I was running it in IntelliJ and it was silently consuming the relevant output I couldn't figure out what was going on. I didn't consider that the IntelliJ runner itself might alter the contents of the stream being written during tests -- I would somewhat understand it parsing the output and reporting things incorrectly based on that, but actually altering the output (even within quotes) was a big surprise to me.

This may not be a super common case, but I think that not being able to print any text that has `\n--- FAIL: ` in a test that uses an IntelliJ runner does fall under the category of a bug.

**Comment by nmiyake** [comment]
Go Playground version of the more realistic case: https://play.golang.org/p/enZzN5Cf2u

**Comment by zolotov** [comment]
Won't fix, `--- FAIL` is gotest-specific string and it's impossible to distinct gotest marker and user output. The only option is to make gotest reporting mechanism better: https://github.com/golang/go/issues/2981
