### ISSUE TITLE
Plugin does not recognize Go 1.7rc1 as supporting the vendoring experiment

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2680]
- Plugin version (or commit hash): 0.12.1704

![snapshot104](https://cloud.githubusercontent.com/assets/607868/16915525/e06021f6-4cef-11e6-9258-c6704cbccaa7.png)

More over, since Go 1.7 the vendor experiment will also be known just as vendoring and there won't be any flags for it to turn it off or not (`GO15VENDOREXPERIMENT` was switched on by default in Go 1.6 and now in 1.7 it will be removed).

**Comment by dlsniper** [comment]
Hmm, I've just seen: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/8cb79cf70815e6047135a90a49f9c595e8fce2c7 but I haven't checked if it made it to the nightly or not.

**Comment by zolotov** [comment]
> More over, since Go 1.7 the vendor experiment will also be known just as vendoring and there won't be any flags for it to turn it off or not (GO15VENDOREXPERIMENT was switched on by default in Go 1.6 and now in 1.7 it will be removed).

This is exactly what is shown on the screenshot, right? There is `go 1.7rc doesn't support disabling vendor experiment`?

8cb79cf has nothing to do with this

**Comment by dlsniper** [comment]
Aaand I need to learn to read. Sorry for noise.
