### ISSUE TITLE
how to open go docs?

### ISSUE THREAD

**Issue by TUTUBIG** [go-lang-plugin-org/go-lang-idea-plugin#2684]
- Plugin version (or commit hash):
- IDE name and version:
- Java version:
- OS name and version: 

- What are you trying to do?

- What would you expect to happen?

- What happens?

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
The plugin supports displaying the documentation using quick documentation. However, if you want to see the external documentation, the process is similar, please see: https://www.jetbrains.com/help/idea/2016.1/viewing-external-documentation.html
