### ISSUE TITLE
Moving "go" file to another package does not change the name of the package

### ISSUE THREAD

**Issue by kolkov** [go-lang-plugin-org/go-lang-idea-plugin#2689]
- Plugin version (or commit hash): 0.12.1740
- IDE name and version: IDEA 2016.2
- Java version: 
- OS name and version: Windows 10

- What are you trying to do? 
Refactor/Move file to another folder. 

- What would you expect to happen?
Name of package changes to new package name.

- What happens?
The package name remains the same.

Maybe I something wrong doing?

**Comment by zolotov** [comment]
Nope, just not implemented yet

duplicates #1711
