### ISSUE TITLE
Variable being declared in type switch is in scope in rvalue when the rvalue is an expression

### ISSUE THREAD

**Issue by daboyuka** [go-lang-plugin-org/go-lang-idea-plugin#2692]
- Plugin version (or commit hash): 0.11.1295
- IDE name and version: IntelliJ IDEA build 145.1617
- Java version: 1.8.0_25
- OS name and version: Windows 7 x64

- What are you trying to do?
Use a Go type switch with a declaration of the form `x := x.Method().(type)`, where `x.Method()` returns an interface type.

- What would you expect to happen?
A new variable `x` should be declared within the scope of each case statement, with the value of `x.Method()` and with type according to the Go rules for type switches. This construct does compile under Go 1.6 (and probably most/all earlier versions).

- What happens?
`Method` is marked in IntelliJ with error `Unresolved reference to Method`.

(Note: Invalidate Cache / Restart did not help, for what it's worth.)

Minimum Working Example:
```
package main

import "fmt"

type typ struct{}

func (_ typ) Method() interface{} { return "world" }

func main() {
	x := typ{}
	switch x := x.Method().(type) {
	case string:
		fmt.Printf("Hello, %s! ", x)
	}
}
```

Screenshot from the IDE:
![](http://puu.sh/qfOZO/1d6843e879.png)

Running this example does indeed print `Hello, world!`, but IntelliJ marks `Method` as unresolved. Furthermore, the `x` in the declaration `x := typ{}` is marked as "Unused variable 'x'". The issue appears to be that the R-value considers the L-value to be in scope, when this should not be the case.

**Comment by zolotov** [comment]
please try to upgrade plugin

**Comment by daboyuka** [comment]
Looks good now :+1:. I updated to IntelliJ IDEA 2016.2.1 (build 162.1447.26) and plugin version 0.12.1724 and the code is now analyzed as expected. I thought I had the most up-to-date version when I posted, but apparently not. Thanks for your help!

**Comment by zolotov** [comment]
Thanks for update
