### ISSUE TITLE
The selected directory is not a valid home for Go SDK

### ISSUE THREAD

**Issue by SerkanSipahi** [go-lang-plugin-org/go-lang-idea-plugin#2701]
- Go Version: `1.6.3`
- Plugin version: `0.12.1724`
- IDE name and version:
```
PhpStorm 2016.2
Build #PS-162.1121.38, built on July 12, 2016
Licensed to PhpStorm Evaluator
Expiration date: August 30, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
- OS name and version: `OS X El Capitan 10.11.1`
- What are you trying to do? `Add SDK`
- What would you expect to happen? `It finds the version`
- What happens? `It can select /usr/local/go/bin/go`

Something gone wrong! I cant select the `/usr/local/go/bin/go` ! 

Info: the problem occurs in php-storm. In another editor no problems with go.

**Comment by zolotov** [comment]
> It can select /usr/local/go/bin/go

The path looks loke the path to binary, not to GOROOT. Are you sure that Go SDK is installed to `/usr/local/go/bin/go`? Can you show output of `tree -L 3 /usr/local/go/bin/go` command?

**Comment by SerkanSipahi** [comment]
Sorry it was my false, i have accidentally select `/usr/local/go/bin/go` instead of /usr/local/go :(

**Comment by zolotov** [comment]
Good to know it works. Thanks for update
