### ISSUE TITLE
Valid home for go sdk

### ISSUE THREAD

**Issue by Shalousun** [go-lang-plugin-org/go-lang-idea-plugin#2704]
- Plugin version (or commit hash):0.10852
- IDE name and version:15.0.1
- Java version:1.7
- OS name and version: win10

go version:1.6.2

![qq 20160802232959](https://cloud.githubusercontent.com/assets/9592228/17334577/4d57294c-5909-11e6-8863-72e78b6d51fa.png)

**Comment by zolotov** [comment]
plugin and IDEA are too old, please update IDEA at least up to 15.0.6, then update the plugin
