### ISSUE TITLE
Autocomplete callbacks as arguments, not as functions

### ISSUE THREAD

**Issue by ernado** [go-lang-plugin-org/go-lang-idea-plugin#2708]
- Plugin version (or commit hash): 0.12.1751
IntelliJ IDEA 2016.2
Build #IC-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- What are you trying to do?
```go
package idea_autocomplete

type argument func(foo string)

func withCallback(callback argument) {
	callback()
}

var (
	arg1 = func(foo string) {
		println(foo)
	}
)

func badAutocompletes() {
	withCallback(arg1()) // <- on that line
}
```
I'm typing `withCallback(ar`.

- What would you expect to happen?
IDE autocompletes it to `withCallback(arg1)` placing cursor 
after `arg1` (or after `arg1)` ideally).

- What happens?
IDE autocompletes it to `withCallback(arg1())` placing cursor 
after `arg1(`.

![screenshot from 2016-08-04 19-01-20](https://cloud.githubusercontent.com/assets/866677/17408979/ed7b6c0e-5a75-11e6-966e-ab5110f6756e.png)

**Comment by ernado** [comment]
Буду очень признателен, если это запилите.
Написание тестов на goconvey станет намного удобнее.

Там когда пишешь `So(10, shoeq` автопомплитит до `So(10, ShouldEqual()`,и надо вручную удалять скобки, было бы очень удобно, если бы было до `So(10, ShouldEqual,`.

**Comment by zolotov** [comment]
@ernado it's on the plan! and it duplicates #2324
