### ISSUE TITLE
Go test always runs with the "-v" flag

### ISSUE THREAD

**Issue by amitaifrey** [go-lang-plugin-org/go-lang-idea-plugin#2715]
- Plugin version (or commit hash): 0.12.1625
- IDE name and version: IDEA 2016.2
- Java version: 1.6.0_24
- OS name and version: Red Hat 6.3
- What are you trying to do?
  Run tests through the IDE. 
- What would you expect to happen?
  The tests to run only with the configured flags and not add the "-v" flag. 
- What happens?
  They run with the "-v" flag as well. 

I think this occurs in src/com/goide/runconfig/testing/GoTestRunningState.java at line 91.

**Comment by dlsniper** [comment]
That is needed in order to extract the tests information.
Is there any issue caused by this or you just thought it's a bug?
Thank you.

**Comment by amitaifrey** [comment]
When I run all the tests in my project I don't want all the verbose logging of all the tests, I just want to see they all passed. Therefore, the "-v" flag is redundant and should not be forced at every go test run.

**Comment by dlsniper** [comment]
Without -v it would be impossible for the plugin to provide the information about which test ran and status for it. And if something fails I think you'd need those logs anyway so I'm not sure if anything can be improved there. 

I don't think we can do anything to change this, @zolotov I think it should be closed.
