### ISSUE TITLE
Skip _ variables when checking for collisions

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#2716]
```go
package main

import _ "fmt"

func demo() (int, int) {
	return 1, 2
}

func main() {
	a, _ := demo()
	_ = a
}
```

**Comment by orian** [comment]
It was introduced recently. Previous versions either didn't check for collision or were correct.

**Comment by dlsniper** [comment]
Yup, I know, I did the mistake, I'll try to fix it tonight / tomorrow. Sorry for any inconvenience.

**Comment by dlsniper** [comment]
Fixed in: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2717 (should be in the next nightly I think).
