### ISSUE TITLE
Run specific benchmarks only

### ISSUE THREAD

**Issue by risboo6909** [go-lang-plugin-org/go-lang-idea-plugin#2744]
Hello,

Is there any possibility to run only benchmarks I need? For instance if I want to create several configurations each of which runs specific benchmarks but I can't figure out, how to do this properly because If I specify my own set of benchmarks here

![image](https://cloud.githubusercontent.com/assets/1838968/17742383/7f1de3d0-64a8-11e6-95ba-4aad73060091.png)

it says that ```-bench``` argument is already defined by plugin and includes all the benchmarks exist in project:

```
/usr/local/go/bin/go test -v -bench=BenchmarkXXX -benchtime=5s github.com/risboo6909/goblin/misc -bench "^BenchmarkXXX|BenchmarkYYY|BenchmarkZZZ$" -run ^$

go test: bench flag may be set only once
```

Is this an issue or can you give me a hint how to do this properly?

**Comment by zolotov** [comment]
1. it must be Benchmark, not Test type
2. `filter` field is made for this
3. you can run particular benchmark via right click menu on the benchmark function

**Comment by risboo6909** [comment]
Thanks a lot for your help, it solves the problem.

I was able to create required config using right mouse button, don't know but ```Benchmark``` type is absent in the list of types otherwise.

Great plugin =)

**Comment by zolotov** [comment]
> don't know but Benchmark type is absent in the list of types otherwise.

it's still GoTest run configuration but with `gobench` option selected as a `TestFramework`

**Comment by risboo6909** [comment]
> it's still GoTest run configuration but with gobench option selected as a TestFramework

Yes, but then there is no ```Pattern``` field there =)

![image](https://cloud.githubusercontent.com/assets/1838968/17743587/da29d42e-64ac-11e6-93cc-ee44391c1200.png)

**Comment by zolotov** [comment]
because you can't use filter while running a file, you should use package test kind instead

please follow the screenshot or use run configuration created by right-click-menu as an example

**Comment by risboo6909** [comment]
Thanks again, it's clear now
