### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by jinsong1213** [go-lang-plugin-org/go-lang-idea-plugin#2745]
Hi:
![qq20160818-0](https://cloud.githubusercontent.com/assets/19601354/17760836/40252520-6535-11e6-9ddc-57249c75aa14.png)

mac 10.10
idea 2016.1.2

thx

**Comment by zolotov** [comment]
See contribution instructions to build proper plugin's distribution file or you official repository to install the plugin
