### ISSUE TITLE
vendor support?

### ISSUE THREAD

**Issue by gliptak** [go-lang-plugin-org/go-lang-idea-plugin#2749]
- Plugin version (or commit hash): Version: 0.12.1795
- IDE name and version: IntelliJ IDEA 2016.2.2
Build #IC-162.1628.40, built on August 16, 2016
- Java version: JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: Ubuntu 16.04.1 LTS

- What are you trying to do? Following https://tour.golang.org/moretypes/18 trying to setup ```golang.org/x/tour/pic``` into ```vendor```. Configuring as follows shows green ```import```:
```
pic.go
vendor/tour.golang.org
```
- What would you expect to happen? ```pic.go``` runs

- What happens? Trying to run ```pic.go``` shows following:
```
GOROOT=/usr/lib/go-1.6
GOPATH=/usr/lib/go-1.6/src
/usr/lib/go-1.6/bin/go build -o "/tmp/Build pic.go and rungo" /tmp/tour/pic.go
pic.go:3:8: cannot find package "golang.org/x/tour/pic" in any of:
	/usr/lib/go-1.6/src/golang.org/x/tour/pic (from $GOROOT)
	/usr/lib/go-1.6/src/src/golang.org/x/tour/pic (from $GOPATH)
```
I tried various configurations around Modules, Libraries in Project Settings to correct to no avail.

Please comment. Thanks

**Comment by dlsniper** [comment]
It doesn't seem that the vendor directory is included in the search path of the go tool,  I'll have a look in a bit.

**Comment by zolotov** [comment]
> GOROOT=/usr/lib/go-1.6
GOPATH=/usr/lib/go-1.6/src

your code is not under gopath or vendor support is disabled in the settings

**Comment by gliptak** [comment]
@zolotov I have "out-of-box" configuration for this project, and other Go files do run. With Go 1.6, vendor support is enabled by defult. Could you offer a pointer on how to enable vendor support (in the plugin?)? Thanks

**Comment by dlsniper** [comment]
@gliptak please follow the convention regarding the Go workspaces: https://golang.org/doc/code.html#Workspaces I'm sorry I've missed this initially.
Place your code into a different folder. In your case, GOPATH should not be pointing to `/usr/lib/go-1.6` but anywhere else, like `/home/User/gopath` for example.

**Comment by gliptak** [comment]
@dlsniper Florin, I didn't set GOPATH directly for this project, the setting came from creating Go SDK and pointing it to the system installed location (GOROOT). Am I expected to add project specific entries? Thanks

**Comment by dlsniper** [comment]
Ok, I don't understand this then. Have you followed the instructions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#setting-up-the-go-sdk to create the Go SDK and then add the GOPATH to the Go Libraries?
