### ISSUE TITLE
Debugging tests

### ISSUE THREAD

**Issue by rlewczuk** [go-lang-plugin-org/go-lang-idea-plugin#2750]
- Plugin version (or commit hash): 0.10.1726
- IDE name and version: Idea Ultimate 15.0.6
- Java version: 1.8.0_25
- OS name and version: Ubuntu Linux  16.04

Currently debugger only starts programs (dlv exec command). Debugging unit tests with dlv test command is possible from dlv command line but not available from IDE. I suppose it should be fairly easy to implement.

**Comment by sjamesr** [comment]
This is the same as https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1855, an oft-requested feature! ;)
