### ISSUE TITLE
Cannot find declaration to go to

### ISSUE THREAD

**Issue by eaglewu** [go-lang-plugin-org/go-lang-idea-plugin#2755]
- Plugin version (or commit hash): **0.10.1726**
- IDE name and version: **IntelliJ IDEA 15.0.6**
- Java version: **JRE 1.8.0_76**
- OS name and version: **OS X**

- What are you trying to do?

Try trace and go to declaration location with method.

- What would you expect to happen?

Go to the declaration location.

- What happens?

Cannot find declaration to go to

```go
// Test code
func (this *Client) getCookie(w http.ResponseWriter, r *http.Request) *http.Cookie {
	c, err := r.Cookie("sessionCookieName")   // The method Cookie can't go to
       //.....
}
```

![image](https://cloud.githubusercontent.com/assets/3753615/17954741/8588c282-6aaf-11e6-9df4-6fb4d2233c6f.png)

![image](https://cloud.githubusercontent.com/assets/3753615/17954746/94b77a78-6aaf-11e6-8551-92c4a15d5d4f.png)

![image](https://cloud.githubusercontent.com/assets/3753615/17954761/b2f7a7d8-6aaf-11e6-9440-803e96142cd9.png)

**Comment by zolotov** [comment]
0.10.* builds are not supported anymore, upgrade IDEA and the plugin
