### ISSUE TITLE
Need support go run *.go

### ISSUE THREAD

**Issue by netroby** [go-lang-plugin-org/go-lang-idea-plugin#2756]
Need support go run *.go

for large go project. there be many files in the same directory. 

under main package. there may be 
frontEnd.go, admin.go, thirdParty.go, api.go, main.go and etc

**Comment by elvizlai** [comment]
I have the same problem.
.
├── Dockerfile
├── block
├── block.go
├── crawler.go
├── crawler_test.go
├── main.go
└── spider.go

**Comment by dlsniper** [comment]
You can choose Go Application type as rinmer and run either a package or a director. Does that help?

**Comment by netroby** [comment]
If we choose go application and select package. if we want run main package. you type main at the package field. 

the error message: can not find main package.

What the hell?

**Comment by dlsniper** [comment]
If you choose a package type then you have to type the package that is contains the main package. 
For example, if your main package is under ` $GOPATH/src/github.com/dlsniper/demo/cmd ` then you need to use ` github.com/dlsniper/demo/cmd `. 
This is how Go works. I'm not sure how to mare this more clear but suggestions are welcomed.

**Comment by netroby** [comment]
no . i just want a simple way to execute my program

cd /path/to/my/dir && go run *.go

very clear and very simple .

**Comment by netroby** [comment]
And it is application .not a package. You can not define every go application a package. 
The package name was main.

**Comment by zolotov** [comment]
duplicates #555

**Comment by dlsniper** [comment]
There is a path to that main. Please follow the instructions and you get this working. You can also use the directory as a type and specify the directory name. 

go run is also discouraged from usage by the Go community at large.

**Comment by zolotov** [comment]
> And it is application .not a package. 

@netroby they are not mutually exclusive

> You can not define every go application a package. The package name was main.

It's recommended way to program in go: https://golang.org/doc/code.html#Workspaces
