### ISSUE TITLE
Can "The selected directory is not a valid home for Go SDK" be more detailed?

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#2758]
![image](https://cloud.githubusercontent.com/assets/1107541/18026348/6ee282a2-6c76-11e6-9bd1-f420aa0ba42b.png)

Why not just print those strings?

There are too many sitations that the "The selected directory is not a valid home for Go SDK" is printed.I have to read the code at https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/c1f96b2d60163eecac52878a4561716843ae76e0/src/com/goide/sdk/GoSdkType.java#L62 to find that I write a version string that idea can not parse.

**Comment by dlsniper** [comment]
Can you give an example of such string? I was sure that we cover all of known possibilities for it. Thank you.

**Comment by bronze1man** [comment]
@dlsniper 
I think the error message should contain more details. It should more than "The selected directory is not a valid home for Go SDK".

**Comment by zolotov** [comment]
@bronze1man if you manually edit versions file, you should be prepared to look at the code or to enable debug logging. Won't fix, sorry

**Comment by chris-martin** [comment]
I hope you'll reconsider this - I'm currently stuck on "The selected directory is not a valid home for Go SDK" and I have no idea how to figure out what's wrong. How do you enable debug logging?

**Comment by dlsniper** [comment]
@chris-martin can you please open a separate issue and I'll help you out. 
Also, have you followed the documentation here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#setting-up-the-go-sdk ?
Thank you.

**Comment by chris-martin** [comment]
Created #2770
