### ISSUE TITLE
Unable to add GO SDK in Intellij 2016 2.2 using the latest Golang plugin

### ISSUE THREAD

**Issue by nikileshsa** [go-lang-plugin-org/go-lang-idea-plugin#2759]
- Plugin version (or commit hash):
v0.12.1799
- IDE name and version:
Intellij IDEA 2016.2.2
- Java version:
- OS name and version: 
Windows 10
- What are you trying to do?
After installing the latest go plugin through the Intellij plugin installation process, I am unable to add GO SDK. The bin folder in the C:\Go\bin is empty when trying to browse to go.exe file. But when I try to locate the go.exe file through windows explorer, I am able to see the file.
- What would you expect to happen?
ability to add go SDK to the project

- What happens?
Unable to add go SDK to the project since the bin directory is empty 
Your issue description goes here.

Steps to reproduce
1) Install intellij idea 2016 2.2
2) Install latest go in Windows 10
3) Open intellij and install go lang plugin
4) Try to add go SDK to a go project
5) Traverse to the Go installation directory (C:\go\bin\go.exe for example) 
6) go.exe is not visible from the file explorer inside "Select Home directory for Go SDK"

Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Hi @nikileshsa, I don't have a Window machine to test but could you please try the ` C:\go ` as SDK directory? Thank you.

**Comment by nikileshsa** [comment]
Thanks dlsniper. C:\go as the SDK directory works!

 I remember navigating to the C:\Go\bin\go.exe when I installed before. But again this is from my memory.

**Comment by dlsniper** [comment]
Awesome. I'll close this for now then.
