### ISSUE TITLE
Debug not working: Process finished with exit code 2

### ISSUE THREAD

**Issue by vacuumn** [go-lang-plugin-org/go-lang-idea-plugin#2765]
- Plugin version (or commit hash): 0.12.1724
- IDE name and version: IntelliJ IDEA 2016.2.3
- Java version:1.8.0_112-release-b287 amd64, JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS name and version: Ubuntu 16.04.1 
- What are you trying to do?

Run program in debug mode
- What would you expect to happen?

Program is runned
- What happens?

Program cant start:
```
/home/username/.IntelliJIdea2016.2/config/plugins/Go/lib/dlv/linux/dlv --listen=localhost:41230 --headless=true exec /tmp/server_rungo -- --DevMode
GOROOT=/usr/local/go
GOPATH=/home/username/sources/go_play:/home/username/sources/go_play
/usr/local/go/bin/go build -o /tmp/server_rungo -gcflags "-N -l" /home/username/sources/go_play/src/server/server.go

Process finished with exit code 2
```
But when running through Run button works fine, program launches correctly.

**Comment by dlsniper** [comment]
this could be a problem in delve. Can you please run the same commands and see what happens? The IDE prints the commands there. You don't need to run delve with the http server. If you need any help to figure this out, please let me know. Thank you.

**Comment by lowjoel** [comment]
I'm seeing this on OS X also. Delve however exits with exit code 0.

Running the command manually says that the path was not found. If I build the binary in the requested path (using `go build`) then Delve just sits there (which I expect to be the expected behaviour.)

Is there some additional logging that can be turned on?

**Comment by lowjoel** [comment]
Hmm, manually building Delve and replacing the binary bundled in the plugin seems to allow my project to boot.

**Comment by dlsniper** [comment]
@lowjoel unfortunately I can't send a PR to upgrade delve as it seems that it's currently failing on master and it's being doing so for a while now. Thanks for looking into this tho.

**Comment by ignatov** [comment]
I've updated the binary – 671943ad70ec7f1c4e2b59662cdb06d84f81cf1c

**Comment by vacuumn** [comment]
Cant reproduce after IDEA upgrade
