### ISSUE TITLE
No parsing of methods in 3rd party packages when using vendoring

### ISSUE THREAD

**Issue by fgblomqvist** [go-lang-plugin-org/go-lang-idea-plugin#2767]
- Plugin version (or commit hash): 0.12.1811
- IDE name and version: IDEA 2016.2.3
- OS name and version: Ubuntu 16.04

- What are you trying to do?
Use autocompletion/checking when coding using a 3rd party package that is located in the `vendor` directory.

- What would you expect to happen?
For it to parse 3rd party packages and autocomplete methods etc.

- What happens?
It says "Unresolved reference" about all methods from all 3rd-party packages in `vendor`.

If I remove the vendor folder, IDEA immediately recognizes all the methods.
Normally I use Godep to manage the vendoring, but even if I manually copy the package folder to the vendor dir it still doesn't work. However, it was working just like 5-6 days ago.

**Comment by dlsniper** [comment]
Hi, is there a way to provide more information? Can you please attach screenshot for the  Settings | Languages and Frameworks | Go | Go Libraries? Also for how the Go SDK is configured. And is vendoring enabled for the project? Which Go version do you use?

**Comment by fgblomqvist** [comment]
![screenshot from 2016-09-04 00-31-28](https://cloud.githubusercontent.com/assets/649260/18229682/1e08cec4-7237-11e6-8162-ab942541d080.png)
![screenshot from 2016-09-04 00-33-25](https://cloud.githubusercontent.com/assets/649260/18229686/34fb710e-7237-11e6-8a8d-a85182451560.png)
The "Sourcepath" is the same as the "Classpath". The other 2 are empty.
Vendoring is enabled since I am using Go 1.6 and 1.7. It's building fine btw.

**Comment by dlsniper** [comment]
Is the project open-source by any chance? I'm still not able to replicate this. Thank you.

**Comment by fgblomqvist** [comment]
Unfortunately it's not, but I'll try to create a small program later today that can replicate it

**Comment by fgblomqvist** [comment]
I wasn't able to replicate it so I ended up just deleting all of the vendor/Godeps stuff and redid it, and now it's working again. Problem was probably Godeps fault. Sorry about that, will close this now.
