### ISSUE TITLE
Can "The selected directory is not a valid home for Go SDK" be more detailed?

### ISSUE THREAD

**Issue by chris-martin** [go-lang-plugin-org/go-lang-idea-plugin#2770]
- Plugin version (or commit hash): 0.10.1296
- IDE name and version: IntelliJ IU 15.0.6
- Java version: OpenJDK 1.8.0_122
- OS name and version: NixOS 16.03
- What are you trying to do? - Set up a Go SDK

I've fetched Go via the Nix package manager:

```fish
chris@renzo ~> nix-store -r (nix-instantiate '<nixpkgs>' -A go_1_6)
/nix/store/jvsx0g86is0ryjxdrsql5q7nv349jnf1-go-1.6.3
chris@renzo ~> /nix/store/jvsx0g86is0ryjxdrsql5q7nv349jnf1-go-1.6.3/bin/go version
go version go1.6.3 linux/amd64
```

I'm not sure which directory needs to be used as the Go SDK home. I've tried `/nix/store/jvsx0g86is0ryjxdrsql5q7nv349jnf1-go-1.6.3` and various subdirectories, but none of them have worked so far.

The error message isn't helpful:

![screenshot from 2016-09-07 13-50-52](https://cloud.githubusercontent.com/assets/399718/18324457/9ba75ad2-750a-11e6-8745-bc9a43a87d4c.png)

Could it clarify what it's looking for and/or output the reason why it fails?

Alternatively, if there's a way to enable some kind of debug logging that might shed more light on the issue, instructions on how to do that would be great.

**Comment by dlsniper** [comment]
Can you please do a ` tree -L 3 /nix/store/jvsx0g86is0ryjxdrsql5q7nv349jnf1-go-1.6.3 `? Use a pastebin to share if possible. Thank you.

**Comment by chris-martin** [comment]
https://gist.github.com/chris-martin/000d48f629507f1467c063c2859a3421

**Comment by dlsniper** [comment]
Please try to select ` /nix/store/jvsx0g86is0ryjxdrsql5q7nv349jnf1-go-1.6.3/share/go ` as directory, if that doesn't work, please do a `tree -L 3` on it. Thanks you.

**Comment by chris-martin** [comment]
That's what I suspected as well, but same result.

https://gist.github.com/chris-martin/0729cfa8e1fdf8b7242b5c444683b906

**Comment by dlsniper** [comment]
Please go to ` Help | Debug Log Settings ` and add a new line like this:
```
#com.goide.sdk.*
```
Then go to ` Help | Show Log in File Manager ` and see what's the path to your log file. The log file should be named ` idea.log `

Now restart the IDE and try to select the folder again, some logs lines should appear regarding why the SDK failed.

Also I think you are running a very old version of the plugin that is not supported anymore, please try to upgrade the IDE as well. I think the fix for this issue was added after that one was released.

Thank you.

**Comment by chris-martin** [comment]
I just updated plugins and now am on version 0.10.1726 of the Go plugin, no change. I'd rather not upgrade the IDE because I'm not a big fan of the new subscription licensing model.

There is nothing called `Help | Show Log in File Manager` in the menu, but my log file is `~/.IntelliJIdea15/system/log/idea.log`.

The debug log configuration doesn't seem to have any effect. Nothing gets logged when I try to select the Go SDK path.

**Comment by zolotov** [comment]
> #com.goide.sdk.*

I believe it's `#com.goide.sdk.GoSdkService`

Anyway, we are not going to support more than three IDEA versions (for now it's 2016.1, 2016.2 and 2016.3 EAP). 
So 
1. You free to fork the repo and periodically move all changes from master to 141 branch (which stands for IntelliJ 15) and fix compatibility.
2. You can use IntelliJ Community edition, it's free, does not require any subscribtion and Go plugin works there
