### ISSUE TITLE
Feature request: Comments should begin with the name of the thing being described

### ISSUE THREAD

**Issue by saturn4er** [go-lang-plugin-org/go-lang-idea-plugin#2772]
That's would be cool, if plugin will highlight comments, which doesn't begin with the name of the thing being described.

Example:
![image](https://cloud.githubusercontent.com/assets/11644585/18344885/d458b1e8-75c1-11e6-869a-efa3d875413b.png)

**Comment by zolotov** [comment]
It is implemented, just turn on `Comment of exported element starts with incorrect name`
<img width="743" alt="screenshot 2016-09-08 12 46 05" src="https://cloud.githubusercontent.com/assets/140920/18345016/43d615d8-75c2-11e6-8bf5-556b878abddf.png">

**Comment by dlsniper** [comment]
It's disabled by default because of this as well: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2255
