### ISSUE TITLE
Repeatedly execute one or group of test without recompiling

### ISSUE THREAD

**Issue by ggeorgiev** [go-lang-plugin-org/go-lang-idea-plugin#2775]
I would like if I can run the same test(s) multiple times - limited (by number or until it fail). Please see JUnit configuration for reference.

Note that running the same tests in go without recompiling it is a bit of chore. Check this for reference: http://stackoverflow.com/questions/28492694/golang-how-to-run-go-test-repeatedly-without-recompiling (please provide a better answer if this there is not true). Since there are no incremental builds for the tests - building them is time-consuming. For example, in my project, the build of my tests takes about 5s ... and  for them to execute just 200ms. 

Having this organized from the IDE will be a great gain.

**Comment by zolotov** [comment]
> http://stackoverflow.com/questions/28492694/golang-how-to-run-go-test-repeatedly-without-recompiling 

It won't help you, with `-c` IDE will compile test into a file, but it will do it each time you're running tests. No, we do not plan to implement our own `go` compiler that will be able to track all changes and decide what package should or should not be recompiled

**Comment by ggeorgiev** [comment]
I am sorry but closing this request with such motivation is ... interesting, but complete in the spirit of the go community - so no surprise there.

This request is to add a new feature for the plugin you own ... and if possible to provide an additional extra capability since a tool could easily bundle several commands together to achieve a result that a single operation can't.

And, yes, creating your implementation of go compiler is ridiculous almost exactly as it is to assume that this is what I was asking for.

**Comment by dlsniper** [comment]
@zolotov I think @ggeorgiev wanted something like this: 
![snapshot130](https://cloud.githubusercontent.com/assets/607868/18411589/49f61bfa-7772-11e6-910b-546eb17ab114.png)


Probably this is a feature of JUnit rather than the IDE but I might be wrong. In Go's case, it might worth raising an issue contribute to Go to have.

**Comment by ggeorgiev** [comment]
yes. And as if the precompiling the tests helps or not try these two in any package:

    time for i in {1..5}; do go test; done
    time (go test -c; for i in {1..5}; do ./<package>.test; done)

**Comment by dlsniper** [comment]
Actually, after looking at ` go test --help `, I've learned about a parameter to the ` go test ` tool called ` -count ` which does what you need to do.

Currently it's possible to specify this in the ` Go tool arguments ` section, see below:

![snapshot131](https://cloud.githubusercontent.com/assets/607868/18411689/604fa2d4-7774-11e6-8452-e256055bd701.png)

Having the dropdown from the JUnit form might be a nice feature but it's currently possible to do it without it.

**Comment by ggeorgiev** [comment]
Thank you, @dlsniper. This seems way easier. I am sorry I missed that. Trusting that if something is out there StackOverflow community will know about it - sometimes is misleading.

Still dedicated UI for such an important feature seems reasonable to have.
