### ISSUE TITLE
Put .iml files in project folder .idea/modules insted of module root

### ISSUE THREAD

**Issue by isiandrasi** [go-lang-plugin-org/go-lang-idea-plugin#2779]
- Plugin version (or commit hash):
  0.12.1799
- IDE name and version:
  IntelliJ IDEA 2016.2.4
  Build #IC-162.2032.8, built on September 9, 2016
- Java version:
  JRE: 1.8.0_92-b14 amd64
  JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
- OS name and version:
  Win7

- What are you trying to do?
  Have .iml files in projects .idea/modules folder, rather than in module roots.

- What would you expect to happen?
  No .iml file in module root.

- What happens?
  An .iml file is created in module root.

I tried to edit .idea/modules.xml and move the .iml file to .idea/modules, but that relocated my module root to .idea/modules.

**Comment by zolotov** [comment]
It has nothing to do with Go-plugin, please use IntelliJ IDEA issue tracker: https://youtrack.jetbrains.com
