### ISSUE TITLE
Adding option to run subtests

### ISSUE THREAD

**Issue by ramigg** [go-lang-plugin-org/go-lang-idea-plugin#2780]
Since go 1.7 we can now create subtests.

```go
func TestFoo(t *testing.T) {
    // <setup code>
    t.Run("A=1", func(t *testing.T) { ... })
    t.Run("A=2", func(t *testing.T) { ... })
    t.Run("B=1", func(t *testing.T) { ... })
    // <tear-down code>
}
```
on the CLI there is an option to run specific subtests:
```go
go test -run Foo/A=  # Run subtests of Foo matching "A=".
```
Is it possible to add this feature to the IDE?

Thanks!

**Comment by sjamesr** [comment]
This might have to work something like JUnit parameterized tests, where you first run the whole test suite, then you can debug individual tests by selecting them in the test results viewer.

**Comment by zolotov** [comment]
You can specify test filter via `Go Test` run configuration, see `Pattern` field:

<img width="1063" alt="screenshot 2016-09-15 00 03 40" src="https://cloud.githubusercontent.com/assets/140920/18529962/e23ea798-7ad7-11e6-95e0-75e62fd87a78.png">


Running sub tests from editor is covered by #2546

**Comment by ramigg** [comment]
This solution is not convenient and not usable when you have many subtests. A very good solution would be a play button near each subtest just as you made for the main tests.

**Comment by dlsniper** [comment]
Can you please give an example of how you organize these subtests? The problem with subtests is that they can  be launched from a for loop with no way to identify what is the subtest name.

**Comment by ramigg** [comment]
Sorry for the late response.
I'm using subtest when I want to do BDD style testing. Instead of using goconvey/ginkgo I prefer to use standard library.
Also when I have common setup, it's convenient to use subtests, it's very readable that way.

**Comment by dlsniper** [comment]
Hi, I meant a code example. Like I've said, this is very hard to figure out as there are too many ways to do it without a specific form. Thank you.

**Comment by ramigg** [comment]
I'm using it the straightforward way similar to how it is done with goconvey.
```go
func TestFoo(t *testing.T) {
    // <setup code>
    t.Run("A=1", func(t *testing.T) { ... })
    t.Run("A=2", func(t *testing.T) { ... })
    t.Run("B=1", func(t *testing.T) { ... })
    // <tear-down code>
}
```
