### ISSUE TITLE
Impossible to run test with debug mode

### ISSUE THREAD

**Issue by jerome-laforge** [go-lang-plugin-org/go-lang-idea-plugin#2781]
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: 
- Java version:
- OS name and version: 
IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- What are you trying to do?
Run test into debug mode

- What would you expect to happen?
that works

- What happens?
Error running TestFuzzxxxxxxxx in xxxxxxxxx_test.go: Cannot find runner for TestFuzzxxxxxxxx in xxxxxxxxx_test.go

But this test run correctly when I run it directly from intellij with nominal mode (not into debug mode)

![toto](https://cloud.githubusercontent.com/assets/9979375/18552906/ca05a1f4-7b5e-11e6-8be8-0dbcef98733f.png)

**Comment by dlsniper** [comment]
Hi, this is a know issue. Please follow https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1855 for updates. Thank you and sorry

**Comment by jerome-laforge** [comment]
Great, I will look the #1855 
Many thx.
