### ISSUE TITLE
Can't launch test from Right-click menu

### ISSUE THREAD

**Issue by MarkSRobinson** [go-lang-plugin-org/go-lang-idea-plugin#2782]
- Plugin version (or commit hash): 0.12.1799

- IDE name and version:
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016

- Java version:
JRE: 1.8.0_112-release-b343 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

- OS name and version: 
Ubuntu 14.04

- What are you trying to do?

Launch a test by right-clicking it, and selecting 'Run/Debug test...' from context menu

- What would you expect to happen?

When I right click a test file, I should have an option to 'Run/Debug/Coverage' the file.

- What happens?

The right-click menu is missing these options.

When you right click on a Go Unit Test file, I should have an option to 'Run/Debug' the file  This option is missing.  If I open the file, I can right click the code and select 'Run/Debug'

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.
![runnable main program context menu](https://cloud.githubusercontent.com/assets/2237823/18559427/0658dc6c-7b2c-11e6-8591-c7edece65d98.png)
![unit test context menu](https://cloud.githubusercontent.com/assets/2237823/18559428/065ace14-7b2c-11e6-9768-8233129f8323.png)

**Comment by zolotov** [comment]
According to screenshot, the test is located inside the library. Running from context works for project-files only.
