### ISSUE TITLE
Plugin 'Go' is incompatible with this installation

### ISSUE THREAD

**Issue by gshilin** [go-lang-plugin-org/go-lang-idea-plugin#2785]
- Plugin version (or commit hash): 0.13.1825
- IDE name and version: RubyMine 2016.3 EAP #RM-163.4830.21
- Java version: JRE 1.8.0_122-release-b340 amd64; JVM: OpenJDK 64-Bit Server VM by JetBrains
- OS name and version: Ubuntu 16.04.1 LTS

- What are you trying to do?
That's latest EAP version of RubyMine. Trying to install plugin from disk

- What happens?
Getting popup: Plugin 'Go' is incompatible with this installation

**Comment by dlsniper** [comment]
This version is not supported by the plugin and from what I've understood it won't be supported. You'll have to revert to a previous EAP or stable. Sorry and thank you.
