### ISSUE TITLE
The 'step *' button is gray when debuging

### ISSUE THREAD

**Issue by yangxikun** [go-lang-plugin-org/go-lang-idea-plugin#2793]
- Plugin version (or commit hash): 0.9.1235
- IDE name and version:intellij idea 14
- Java version:1.7.0_75
- OS name and version: debian jessie
- Go version: 1.7.1

I try to debug a simple go program.When I click Debug, program stop on breakpoint, but I cann't use 'step *' to continue debug.
![selection_008](https://cloud.githubusercontent.com/assets/3364160/19064849/8dba6a34-8a42-11e6-9982-622e54468358.png)
![selection_009](https://cloud.githubusercontent.com/assets/3364160/19064854/92833ac8-8a42-11e6-93d5-f7b3ba3f5cbd.png)

Thanks for any help.

**Comment by dlsniper** [comment]
Please upgrade the IDE to version 2016.2, this one is not supported for a while now. Thank you for understanding.

**Comment by yangxikun** [comment]
After upgrade the IDE to version 2016.2, the debug work. Thanks.
