### ISSUE TITLE
can't debug go application in idea2016.2.4

### ISSUE THREAD

**Issue by runthinker** [go-lang-plugin-org/go-lang-idea-plugin#2794]
- Plugin version (or commit hash):0.12.1844
- IDE name and version:idea 2016.2.4
- Java version:1.8
- OS name and version: win7

can't debug go application in idea2016.2.4

![image](https://cloud.githubusercontent.com/assets/22365346/19227395/67e18d12-8eeb-11e6-9aee-fe97bbfdc57e.png)
![image](https://cloud.githubusercontent.com/assets/22365346/19227398/6f692d7e-8eeb-11e6-8fc2-4006aa80f156.png)

**Comment by runthinker** [comment]
plugin version:0.12.1844

**Comment by dlsniper** [comment]
Run file configuration is not supported, please use Go Application type. Thank you.

**Comment by dlsniper** [comment]
Sorry, the picture did not loaded.
Your project does not seem to belong to a GOPATH, can you please pase a screenshot of your Settings | Languages and Frameworks | Go | Go Libraries? 
Thank you.

**Comment by runthinker** [comment]
Yes,GOPATH is other directory.
![image](https://cloud.githubusercontent.com/assets/22365346/19228644/c90ea792-8ef9-11e6-9ec9-4b11056e4557.png)

**Comment by runthinker** [comment]
go env
![image](https://cloud.githubusercontent.com/assets/22365346/19228787/02d9ce6a-8efb-11e6-93a1-f6bd65583dab.png)

**Comment by runthinker** [comment]
Copy my Project files to GOPATH,but can't debug too.

**Comment by dlsniper** [comment]
Oh, sorry, delve cannot run on 32 bit OSes/binaries for now, nothing that we can do to make this work in this case. 
Please follow this issue: https://github.com/derekparker/delve/issues/20 and when it will be resolved it will work in the plugin as well. Thank you.
