### ISSUE TITLE
Sub-tests do not produce test reports

### ISSUE THREAD

**Issue by ravlio** [go-lang-plugin-org/go-lang-idea-plugin#2800]
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: IntelliJ IDEA 2016.2.4
- Java version: 1.8.0_112-release-b343 x86_64
- OS name and version: os X 10.12 Sierra

- What are you trying to do?

I'm trying to run test case with subtests with IDE runner by clicking "Run" .

- What would you expect to happen?

Detailed report on each subtest of TestSub in `Test Results` section in `Run` panel. The first subtest should be failed, the second should be pass, etc ...

- What happens?

Test results section just print overall result of `TestSub` test case without subtests results.

```go
func TestSub(t *testing.T) {
	for i := 0; i < 10; i++ {
		t.Run(fmt.Sprintf("Case %d", i), func(t *testing.T) {
			if i % 2 == 0 {
				t.Fail()
			}
		})
	}
}
```
<img width="291" alt="2016-10-15 11 43 02" src="https://cloud.githubusercontent.com/assets/2349151/19408707/88027ee6-92cc-11e6-80d9-7dbb02f98ddc.png">

**Comment by zolotov** [comment]
The fix of subtest reporting will be available in the nearest nightly build.

Navigation support is not ready and covered by #2546 issue.

**Comment by ravlio** [comment]
Currently subtests began to appear, without proper logs. For instance, if some subtest throws an error, error will not be viewable in logs by clicking on subtest. As if sub test do some info logs. 

![2016-10-17 10 16 05](https://cloud.githubusercontent.com/assets/2349151/19428426/c51a4a66-9452-11e6-888c-87c1c9017ee0.png)

But logs did not completely disappears. They are still available in overall `Test Results`. And in last subtest, which is more interesting. No matter what status last subtest is, it's contains all error and success logs of all subtests.

![2016-10-17 10 04 57](https://cloud.githubusercontent.com/assets/2349151/19428400/a78470da-9452-11e6-8d5f-ebb4b6fd6704.png)

**Comment by zolotov** [comment]
@ravlio please attach an output of `go test -v` command for these tests. I suspect that it's not possible to distinguish outputs of different subtests.

**Comment by ravlio** [comment]
```
=== RUN   TestTime
=== RUN   TestTime/12:31_in_Europe/Zuri
=== RUN   TestTime/12:31_in_America/New_York
=== RUN   TestTime/08:08_in_Australia/Sydney
--- FAIL: TestTime (0.01s)
    --- FAIL: TestTime/12:31_in_Europe/Zuri (0.00s)
        matcher_test.go:29: could not load location
    --- FAIL: TestTime/12:31_in_America/New_York (0.00s)
        matcher_test.go:33: got 07:31; want 7:31
    --- PASS: TestTime/08:08_in_Australia/Sydney (0.00s)
FAIL
exit status 1
```

Looks like greppable without any problems.

**Comment by zolotov** [comment]
> Looks like greppable without any problems.

Does it? By this output I cannot say for sure which test said `matcher_test.go:29: could not load location`.

**Comment by ravlio** [comment]
> By this output I cannot say for sure which test said matcher_test.go:29: could not load location.

Obviously this error is related to `12:31_in_Europe/Zuri` subtest of `TestTime` test, isn't it?
Subtest outputs are definitely defined by `\s{8}` regexp after test header.

**Comment by zolotov** [comment]
> Obviously this error is related to 12:31_in_Europe/Zuri subtest of TestTime test, isn't it?

Of course not. As I said it can be output of any test which were run in that moment:
```
=== RUN   TestTime
=== RUN   TestTime/12:31_in_Europe/Zuri
=== RUN   TestTime/12:31_in_America/New_York
=== RUN   TestTime/08:08_in_Australia/Sydney
```

> Subtest outputs lines are definitely defined by \s{8} regexp each and go after test header.

Ok, TestTime doesn't fit, but three other tests are still possible owners of the output

**Comment by zolotov** [comment]
> Subtest outputs lines are definitely defined by \s{8} regexp each and go after test header.

Btw, it doesn't work either. Imaging that I have following test:

```
func TestTime(t testing.T) {
   // ... adding subtests
   fmt.Println("        indented output")
}
```

Do you think that `        indented output` should be part of the last subtest?

**Comment by ravlio** [comment]
> it can be output of any test which were run in that moment

Which moment it was be? Test is running in isolated process with dedicated output. Test results are  consistent event if they run in parallel.

> Do you think that `        indented output` should be part of the last subtest?
I got that you mean. And this example is rare and synthetic as it could be :) Normally nobody will put intents in prints, so we can know exactly the involvement of the output to the test. There either do with such assumptions or do not do at all.

As I imagine, the raw output:
```
=== RUN   TestTime
        indented output
=== RUN   TestTime/12:31_in_Europe/Zuri
        indented subtest output
=== RUN   TestTime/12:31_in_America/New_York
        indented subtest output
=== RUN   TestTime/08:08_in_Australia/Sydney
        indented subtest output
--- FAIL: TestTime (0.00s)
    --- FAIL: TestTime/12:31_in_Europe/Zuri (0.00s)
        matcher_test.go:32: could not load location
    --- FAIL: TestTime/12:31_in_America/New_York (0.00s)
        matcher_test.go:36: got 07:31; want 7:31
    --- PASS: TestTime/08:08_in_Australia/Sydney (0.00s)
FAIL
exit status 1
```

need to be converted in report tree like:

```
TestTime (fail)
        indented output
TestTime/12:31_in_Europe/Zuri (fail)
        indented subtest output
        matcher_test.go:32: could not load location
TestTime/12:31_in_America/New_York )fail)
        indented subtest output
        matcher_test.go:36: got 07:31; want 7:31
TestTime/08:08_in_Australia/Sydney (pass)
        indented subtest output
```

Then I can say that the integrated IDE reports are useful. Right now integration is useless with subtests and I have to go to terminal and manually run tests.

**Comment by zolotov** [comment]
> And this example is rare and synthetic as it could be :) 

When the user will come to me and said that output is messed up, I don't think that claiming that his or her code is synthetic and rare will be satisfied enough ;)

> As I imagine, the raw output:

I admit, some cases can be handled but I'm not going to implement it and will wait a `json` output format for `go test`. If you see a way to do this, feel free to make a pull request, I'll show you a direction if you want

**Comment by mdwhatcott** [comment]
Another side-effect is that the test output window has extra leading whitespace which I presume is generated by each subtest. Notice that the initial "ok" is indented several spaces. The more subtests there are, the more leading whitespace appears.

<img width="796" alt="screen shot 2016-10-24 at 11 04 54 am" src="https://cloud.githubusercontent.com/assets/202910/19655592/de72378a-99d9-11e6-8e10-d1d41d5dda6e.png">

**Comment by mdwhatcott** [comment]
@zolotov - So, just to clarify: Are you waiting for https://github.com/golang/go/issues/2981 (`go test -json`) to be implemented before fixing subtest reporting?

**Comment by zolotov** [comment]
@mdwhatcott subtest reporting is fixed, all tests are shown in the test tree. I'm waiting that proposal implemented to group tests output properly

**Comment by mdwhatcott** [comment]
@zolotov - Great! Do you know when will that be published as part of a versioned release?

**Comment by zolotov** [comment]
@mdwhatcott I think just after IDEA 2016.3 release. It's about a month or two
