### ISSUE TITLE
Two-finger click on object by trackpad tends to initiate incorrect drag on Mac

### ISSUE THREAD

**Issue by zhaohaidao** [go-lang-plugin-org/go-lang-idea-plugin#2805]
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: 2016.2.5   IC162-2228.15
- Java version:1.8.0_112
- OS name and version: macOS 10.12

- What are you trying to do?
two-finger click on object to open context menu to use 'find usage' function

- What would you expect to happen?
open the context menu corresponding the target object.

- What happens?
Two-finger click on 'EngineConn' sometimes initiates a drag operation, and the cursor moves to 'Close' and opens context menu for 'Close'
'''
type EngineConn interface {
	Close() error
	Dial(addr string) erro
'''

Your issue description goes here.
it seems to be related with trackpad operation in macOS 10.12
the mouse operation performs as expected.

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by zolotov** [comment]
Sorry, it has nothing to do with the Go plugin and should be reported to IntelliJ IDEA issue tracker.
