### ISSUE TITLE
Error: List of plugins was not loaded for following hosts: https://github.com/go-lang-plugin-org/go-lang-idea-plugin

### ISSUE THREAD

**Issue by Gyga8K** [go-lang-plugin-org/go-lang-idea-plugin#2807]
- Plugin version (or commit hash):
- IDE name and version: WebStorm 2016.2.4
- Java version:
- OS name and version: Windows 10

- What are you trying to do?
Update plugin

- What would you expect to happen?
Update plugin

- What happens?
Thos message  "List of plugins was not loaded for following hosts: https://github.com/go-lang-plugin-org/go-lang-idea-plugin"

Your issue description goes here.
Please be as detailed as possible
![screenshot_1](https://cloud.githubusercontent.com/assets/13306227/19667127/0efbadc6-9a1d-11e6-9f6c-7c5c983447b0.png)

**Comment by dlsniper** [comment]
Please don't use the github address directly. If you want to use the nightly or alpha channels, use those addresses instead. 
The addresses are: https://plugins.jetbrains.com/plugins/alpha/5047 for alpha and https://plugins.jetbrains.com/plugins/nightly/5047 for nightly. 
Hope this helps. I'll close it for now but if you still have an issue with this please reopen it here.

Thank you.

**Comment by Gyga8K** [comment]
OK
