### ISSUE TITLE
Plugin 'Go' is incompatible with this installation

### ISSUE THREAD

**Issue by Kurt-Shiwz** [go-lang-plugin-org/go-lang-idea-plugin#2808]
- Plugin version (or commit hash):
0.13.1871

- IDE name and version:
pycharm 2016.2.1

- Java version:
1.8.0_73

- OS name and version: 
macOS Sierra 10.12.1

- What are you trying to do?
Trying to install plugin from disk.

- What happens?
Getting popup: Plugin 'Go' is incompatible with this installation

**Comment by zolotov** [comment]
0.13 is made for 2016.3. Won't fix
