### ISSUE TITLE
Enable Connections to Running Delve Debugger

### ISSUE THREAD

**Issue by rsstreamx** [go-lang-plugin-org/go-lang-idea-plugin#2817]
Rather than start a new process for debugging, I'd like to connect to and existing debugger session that I've started on the command line.  It appears that the Delve Intellij plugin has the majority of the plumbing to handle this use-case, but it not exposed in a configurable fashion.  Rather than finding a free port at startup and connecting to localhost, the Delve Debug configuration could expose these as configurable parameters to enable debugging over the wire.

**Comment by zolotov** [comment]
duplicates #620
