### ISSUE TITLE
"Find usages" does not work for package names

### ISSUE THREAD

**Issue by dcelasun** [go-lang-plugin-org/go-lang-idea-plugin#2821]
Running **0.12.1885** on **IDEA Ultimate 2016.2.5**.

- **What are you trying to do?**

In a Go file, right click the package name at the top of the file and choose "Find Usages".

- **What would you expect to happen?**

The find dialog should open, displaying all the places that package is imported.

- **What happens?**

![find_usages](https://cloud.githubusercontent.com/assets/144373/20062076/a9ed0cf4-a502-11e6-9daa-7b37e287cda1.png)

**Comment by zolotov** [comment]
Import statement import a directory with a given `import path`, not package, so you should use `find usages` on directory, not on the package clause.

**Comment by dcelasun** [comment]
That works, thanks! Maybe the same thing should happen when it's being invoked from the package clause?

**Comment by zolotov** [comment]
Eventually I'll make it will work for looking for quialifiers like `thrift.SomeFunction()` but still not for imports, sorry
