### ISSUE TITLE
Support for latest IntelliJ IDEA 2016.3 EAP (163.7743.17) 

### ISSUE THREAD

**Issue by gwuhaolin** [go-lang-plugin-org/go-lang-idea-plugin#2823]
- Plugin version (or commit hash):
can't find go plugin
<img width="828" alt="screen shot 2016-11-10 at 3 36 06 pm" src="https://cloud.githubusercontent.com/assets/5773264/20168188/82d5cff6-a75b-11e6-90db-27c9a2ca86ed.png">

- IDE name and version:
IntelliJ IDEA 2016.3 EAP
Build #IU-163.7743.17, built on November 9, 2016

- Java version:
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

- OS name and version: 
macOS 10.12.1 (16B2657)

**Comment by dlsniper** [comment]
Have you tried to install the nightly version? See the link in the readme for how to do that. If 163.7743.17 is just released, it might be a day or two until the plugin gets updated. Or it might be a release cycle until it does if the Platform has any changes in it that make it incompatible. 
Let me know how it goes.

**Comment by asampal** [comment]
I get the same as the OP and I've added the nightly repository. The Idea version I'm using is 163.7743.17. The curious thing is that I upgraded from 2016.2 and the Go plugin I had was transferred over, but was shown as non functional with this version of Idea.

**Comment by dlsniper** [comment]
Then it just need to be upgraded to the latest version of IDEA. Probably tomorrow should work. 
As a rule of thumb, wait at least a couple of days before upgrading EAP releases.
