### ISSUE TITLE
Support semantic highlighting feature

### ISSUE THREAD

**Issue by nvartolomei** [go-lang-plugin-org/go-lang-idea-plugin#2824]
IDEA 2016.3 which is currently in EAP adds support for [Parameter hints and Semantic highlighting](https://www.jetbrains.com/idea/nextversion/#editor).

Would be cool to make plugin compatible with these features.

**Comment by dlsniper** [comment]
The plugin supports Semantic highlight since February last year, you can use the ` Darcula - dlsniper ` theme for Go.

**Comment by zolotov** [comment]
@dlsniper it's not the same, take a closer look at the screenshot – each variable has its own color:

![image](https://cloud.githubusercontent.com/assets/140920/20264304/e43ed486-aa7b-11e6-802e-c698fd00810f.png)

**Comment by zolotov** [comment]
@nvartolomei thank you for the issue, I've splited it in two. Let this one will be about semantic highlighting. Here is the second one: #2827
