### ISSUE TITLE
conflict with IntelliJ IDEA Python plugin

### ISSUE THREAD

**Issue by xring** [go-lang-plugin-org/go-lang-idea-plugin#2825]
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: IntelliJ IDEA 2016.2.2 ULTIMATE
- Java version: 1.8.0_91
- OS name and version: OS X EI Capitan 10.11.2 

- What are you trying to do?
install go and python plugin in IDEA. python plugin version: 2016.2.162.43

- What would you expect to happen?
both work fine

- What happens?
can not move file, code auto-complete do not work, can not run code and so one

Your issue description goes here.
Please be as detailed as possible

```go
simple hello world code
```

Or include a screenshot / video of the issue.

**Comment by zolotov** [comment]
Please attach logs directory (Help | Show Logs in <file browser>)

**Comment by zolotov** [comment]
closing due to lack of feedback
