### ISSUE TITLE
Library Paths Aren't Resolved

### ISSUE THREAD

**Issue by TomAshley303** [go-lang-plugin-org/go-lang-idea-plugin#2829]
- Plugin version (or commit hash): 0.12.1799
- IDE name and version: Intellij IDEA 2016.2.5
- Java version: 8
- OS name and version: Ubuntu 16.10

- What are you trying to do?
Reference a library.

- What would you expect to happen?
The IDE to look for the library reference from $GOPATH

- What happens?
The error: "Cannot resolve file ..."

Your issue description goes here.
Please be as detailed as possible
The IDE thinks I'm referencing something that doesn't exist.
```go
import (
    "fmt"

    "github.com/user/stringutil"
)
```

**Comment by TomAshley303** [comment]
If I do "../../../github.com/user/stringutil" the IDE is happy with it but of course we can't compile like that.

**Comment by zolotov** [comment]
Have you set GOPATH in settings? `File | Settings | Languages & Frameworks | Go | Go Libraries`?

**Comment by zolotov** [comment]
closing due to lack of feedback
