### ISSUE TITLE
Make the Stop Process button send a SIGINT to the running Golang process

### ISSUE THREAD

**Issue by Ravenwater** [go-lang-plugin-org/go-lang-idea-plugin#2832]
- Plugin version (or commit hash): 0.13.1896 (163.7743)
- IDE name and version: 2016.3
- Java version: jdk 1.8
- OS name and version: Windows 10 Pro

- What are you trying to do?
On Windows, "Stop Process" should gracefully shutdown a process so that any resources held by the process can be properly released.

- What would you expect to happen?
Golang net/http package has a SIGINT handler to trigger a graceful server shutdown. However, on Windows the "Stop Process" button in the IDE appears to SIGKILL the process, thus improperly stopping the process. Shutdown is where stateful resources, such as file handles, database connections, and session state is cleaned up, so essential to the functional flow of a server.

- What happens?
On Windows the "Stop Process" button in the IDE appears to SIGKILL the process, thus improperly stopping the process. So the Stop button behaves like a Kill button.

```go
any program that has a SIGINT handler
```

This is the behavior of the "Stop Process" button in the current IDE:
```
C:/Go\bin\go.exe run server.go
2016/11/23 07:50:52 Initialize Environment
2016/11/23 07:50:52 Successfully serialized customer database
2016/11/23 07:50:52 Successfully serialized score database
2016/11/23 07:50:52 Serving mp scoring at https://127.0.0.1:8090

Process finished with exit code 1
```

and this is what it is supposed to trigger:

```
PS > .\server.exe
2016/11/23 07:54:11 Initialize Environment
2016/11/23 07:54:11 Successfully serialized customer database
2016/11/23 07:54:11 Successfully serialized score database
2016/11/23 07:54:11 Serving mp scoring at https://127.0.0.1:8090
---->SIGINT
2016/11/23 07:54:15 Stopped serving mp scoring at https://127.0.0.1:8090
2016/11/23 07:54:15 Successfully serialized customer database
2016/11/23 07:54:15 Successfully serialized score database
```

**Comment by zolotov** [comment]
Will be fixed in the nearest nigtly build for IDEA 2016.3
