### ISSUE TITLE
Windows incorrect gcflags param

### ISSUE THREAD

**Issue by Stoyvo** [go-lang-plugin-org/go-lang-idea-plugin#2834]
- Plugin version (or commit hash):  0.12.1885
- IDE name and version: Idea 2016.2
- Java version: 1.8.0_101
- OS name and version: Windows 10

- What are you trying to do? Debug golang application

- What would you expect to happen? Anything

- What happens?
```
could not launch process: Could not determine version number: could not find symbol value for runtime.buildVersion
```

Currently I see the following debug command:
```
C:\Users\stoyvo\.IntelliJIdea2016.2\config\plugins\Go\lib\dlv\windows\dlv.exe --listen=localhost:52787 --headless=true exec "C:\Users\stoyvo\AppData\Local\Temp\Build main.go and rungo" --
GOROOT=F:/Development/Go/Go Library/Core
GOPATH=F:/Development/Go/Go Library/Packages
"F:/Development/Go/Go Library/Core\bin\go.exe" build "-gcflags=-N -l" -o "C:\Users\stoyvo\AppData\Local\Temp\Build main.go and rungo" -gcflags "-N -l" "F:/Development/Go/Go Library/Packages/src/myapp/main.go"
```

Notice the command before myapp main.go. The `-gcflags "-N -l"` is incorrect, it should be `-gcflags="-N -l"`

**Comment by Stoyvo** [comment]
Note: Updated to latest alpha version (0.13.1914) and idea 2016.3, issue still exists.

**Comment by zolotov** [comment]
Attach screenshot of the run configuration you're trying to run

**Comment by Stoyvo** [comment]
@zolotov 

![image](https://cloud.githubusercontent.com/assets/6148099/20668106/fd09d8de-b53a-11e6-8e53-7c3d44334fe8.png)

**Comment by zolotov** [comment]
Why did you set -gcflags="-N -l" there?

Anyway `-gcflags "-N -l"` looks quite legit to me and I'm not experiencing any problem in debug on windows. So I won't change it.

As for your problem, see https://github.com/derekparker/delve/issues/477

**Comment by Stoyvo** [comment]
Running the command manually with the = works. Not sure how this pluggin can be an exception.

**Comment by zolotov** [comment]
> Not sure how this pluggin can be an exception.

I didn't say a word about it. I didn't say that something doesn' work because of `=`. I said that it works without `=`

**Comment by dlsniper** [comment]
The flags are only needed to turn off the optimizations and allow Delve and other debuggers to better inspect the binary. This has been working for the past few Go releases as well as the plugin release.

I would advise not setting them manually because it can produce situations like yours where the flags are there twice and that's something that I don't know how the Go tool will handle.
