### ISSUE TITLE
could not launch process: could not get thread count

### ISSUE THREAD

**Issue by aicochow** [go-lang-plugin-org/go-lang-idea-plugin#2835]
- Plugin version (or commit hash):

> 0.13.1914

- IDE name and version:

> IntelliJ version:2016.3

- Java version:

> java version "1.8.0_112"- OS name and version: 

- What are you trying to do?

> debug go

- What would you expect to happen?

> can debug go

- What happens?

> when I debug go
 `could not launch process: could not get thread count`

Your issue description goes here.
Please be as detailed as possible

```go
package main

import "fmt"

func main() {

	pos, neg := adder(), adder()
	for i := 0; i < 10; i++ {
		fmt.Println(pos(i), neg(-2 * i))
		
	}
}
func adder() func(int) int {
	sum := 0
	return func(x int) int {
		sum += x
		return sum
	}
}

```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Hi,

This is a problem in Delve, the debugger backend for the plugin.
We can't do anything about it until this is solved.
Please see: https://github.com/derekparker/delve/issues/645 for more information on it.
I'll close this for now.
