### ISSUE TITLE
The auto indentation seems not work in PyCharm 2016.3

### ISSUE THREAD

**Issue by bobcyw** [go-lang-plugin-org/go-lang-idea-plugin#2836]
- Plugin version (or commit hash): Version: 0.13.1914
- IDE name and version:PyCharm 2016.3
- Java version: java version "1.7.0_79"
- OS name and version: MacOSX 10.12.1

- What are you trying to do?
I create a new line.

- What would you expect to happen?
Auto indentation will insert the tab as it do in old version.

- What happens?
New line start at beginning without tabs or spaces.

![2016-12-01 05 03 28](https://cloud.githubusercontent.com/assets/4155602/20771227/897ca338-b783-11e6-8c0f-3cf1d9f12784.png)

**Comment by zolotov** [comment]
Cannot recreate. Please provide whole file content

**Comment by bobcyw** [comment]
After reboot the PyCharm and operation system, this issue does not exists any more. Maybe can close it first. When I meet it again I'll use screen capture to record it.

**Comment by bobcyw** [comment]
@zolotov when I check the "Preferences -> Editor -> Code Style -> Go -> Keep indents on empty lines", this problem seems to be solved.
