### ISSUE TITLE
Scanln fails to stop for input during debug on Linux

### ISSUE THREAD

**Issue by michaljaros84** [go-lang-plugin-org/go-lang-idea-plugin#2838]
- Plugin version (or commit hash):
 0.13.1914

- IDE name and version:
IntelliJ IDEA community

- Go version;
1.7.3

- Java version:
1.8.0_111

- OS name and version: 
Ubuntu 16.04.1 LTS

- What are you trying to do?
Trying to get program to stop for input on fmt.Scanln

- What would you expect to happen?
Execution to wait for input when Scanln is reached

- What happens?
Execution continues and program acts like empty string/white space was entered 

This is really simple example I created to test the Scanln issue as I used to get it on Windows. Funny story: on windows it now works (same IDE, plugin and go versions) but fails under Linux.

Code:

package main

import "fmt"

func main() {
	var x string
	fmt.Println("Type smth:")
	fmt.Scanln(&x)
	fmt.Println("Typed:", x)
}

This works if simply executed either in IDE or using simple 'go build' from command line, but fails when debuger is attached.

Tested configuration:
1)  GOROOT and GOPATH on separate partition mounted into /media/usr
![ide](https://cloud.githubusercontent.com/assets/11840312/20814725/cd650c2c-b812-11e6-88d4-cf30aeb848d9.png)

2) Default root and go path in /home/usr
![default](https://cloud.githubusercontent.com/assets/11840312/20814747/e13b1912-b812-11e6-9b98-fdb55c19b698.png)

**Comment by michaljaros84** [comment]
Ok did something most obvious and try to handle the error. Looks like the Scanln when called through Delve throws EOF -> this is not thrown when program is simply run, without debuging. Happens both through the IDE and directly in command line:

IDE
![latest](https://cloud.githubusercontent.com/assets/11840312/20862522/173ee37a-b9a5-11e6-8a9f-9b5ab5e0bd7c.png)

CMD 
![cmdln](https://cloud.githubusercontent.com/assets/11840312/20862523/28ff6486-b9a5-11e6-99c7-2323cbcd70ec.png)

**Comment by michaljaros84** [comment]
This looks like delve issue. Moved to https://github.com/derekparker/delve/issues/679. 

Closed.

**Comment by zolotov** [comment]
Thank you for investigation. Indeed it looks like delve's issue
