### ISSUE TITLE
Missing godoc reference

### ISSUE THREAD

**Issue by Viking1983** [go-lang-plugin-org/go-lang-idea-plugin#2850]
- Plugin version (or commit hash): 0.13.1914
- IDE name and version: Webstorm 2016.3.1
- Java version: JRE: 1.8.0_112-release-408-b2 amd64
- OS name and version: Xubuntu 16.04.1
- What are you trying to do?
Check reference interensing method
- What would you expect to happen?
Godoc docs is show in pop up window
- What happens?
Does not display the documentation methods
![webstorm_go](https://cloud.githubusercontent.com/assets/12736118/21131761/b3feab1a-c110-11e6-8c3a-941856bf7849.png)

In Visual Studio Code is possible checking detailed documentation :(

Best regards,
Paul

**Comment by dlsniper** [comment]
Hi, 

If you move the cursor over to the function name, then you can use the Quick Documentation feature to get this working.
Please let us know if this is what you are looking for.

**Comment by Viking1983** [comment]
Hi,
i moved cursor after function name, and I remove braces. Then use combination ctrl + q and see documentation on the function. Thanks a lot :)
