### ISSUE TITLE
Cannot achieve automatic generation of import line

### ISSUE THREAD

**Issue by carlca** [go-lang-plugin-org/go-lang-idea-plugin#2853]
- Plugin version (or commit hash): go version go1.7.4 windows/amd64
- IDE name and version: WebStorm 2016.3.2 Build #WS-163.9166.30
- Java version: no idea
- OS name and version: Windows 10 Pro 64 bit Insider Edition build 14986

- What are you trying to do? I am trying to follow Todd McLeod's GOLANG course video in which he appears to activate the automatic generation of the line <quote>import "fmt"</quote> simply by typing <quote>fmt.PrintLn </quote> without the means of any additional software (eg. goimports)

- What would you expect to happen? I would expect to achieve to same as Todd.

- What happens? Absolutely nothing. Further development: I tried installing "goimports" and now the situation is worse and I do not appear to be able to uninstall "goimports".

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by zolotov** [comment]
Hi carla. This feature should work out of the box. The only thing you need to do is to download Go and set it as a SDK for the project. Take a look at help: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/Documentation#setting-up-the-go-sdk

**Comment by carlca** [comment]
Hi Alexander, thanks for the prompt reply. I'm currently working through
reinstalling GO and will look to the SDK documentation link you sent.
Another thing is puzzling me: why, when I explicitally opened C:\gocode\src\
github.com\GoesToEleven\GolangTraining\01_getting-started\Carl01_helloWorld\main.go,
does the editor insist on displaying
C:\Users\Carl\AppData\Local\Temp\main.go and behaving as if this was the
file I opened. It's really annoying and it's like the editor is saying "No,
no you're so stupid let me tell you where you opened the file" to which my
reply is "Fuck you, I am in charge here".
Cheers,
Carl

**Comment by carlca** [comment]
Hi Alexander, thanks for the guidance you gave me. It works!!! I had gone
through the SDK procedure before but I must have missed a tiny but vital
step. But it works now so I can plough on through Todd's excellent course
and aim to achieve global world GO dominance in a matter of months! Oh that
other business about the file locations was caused by my being too
impatient and not setting up the project structure properly before
attempting to use it.
Thanks again for digging me out of that hole, I really appreciate it,
Best Wishes,
Carl
