### ISSUE TITLE
Is that possible automatically run gofmt when file saved?

### ISSUE THREAD

**Issue by pfctgeorge** [go-lang-plugin-org/go-lang-idea-plugin#2854]
I'm turned into IDEA from Atom. In Atom, it automatically run `gofmt` when the file saved.

I'm very looking forward this feature. Is it possible right now?

**Comment by dlsniper** [comment]
Yes, this is possible now. Please edit your keybindings and set aa shortcut for them. Or use the file watcher plugin. 
See the previous issues on how to do this.
