### ISSUE TITLE
config.go file not recognised 

### ISSUE THREAD

**Issue by jsaguiar** [go-lang-plugin-org/go-lang-idea-plugin#2855]
- Plugin version (or commit hash): Version: 0.13.1914
- IDE name and version: IntelliJ CE 2016.3.1 build: IC-163.9166.29
- Java version: 1.8.0_101
- OS name and version: 10.12.2

All my Config.go files are not being recognised as Go files. But if I change the name to something else like Config1.go it will work as expected.

**Comment by dlsniper** [comment]
Can you please provide a sample project? Please include the `.idea` folder as well.

**Comment by jsaguiar** [comment]
[untitled.zip](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/660778/untitled.zip)
<img width="1552" alt="screen shot 2016-12-19 at 10 39 45" src="https://cloud.githubusercontent.com/assets/4295126/21309819/b31b7f86-c5d7-11e6-973d-6173a314103c.png">

**Comment by zolotov** [comment]
check you file type settings for text files: File | Settings | Editor | File Types | Text

**Comment by jsaguiar** [comment]
It was that. Thank you for the help
