### ISSUE TITLE
Found several packages compiler error

### ISSUE THREAD

**Issue by lawtonykaps** [go-lang-plugin-org/go-lang-idea-plugin#2860]
- Plugin version (or commit hash): Go version 1.7.4
- IDE name and version: Intellij IDEA 2016.3.2
- Java version: 1.8.0_111 x64
- OS name and version:  Windows 10

- What are you trying to do? compile code which contains the lxn/walk functions. (Windows GUI) 

I am receiving an error message when compiling code which contains the lxn/walk functions. The error is Found several packages [walk,main] in 'C:/Go/src/github.com/lxn/walk'

In have reinstalled IntelliJ IDEA 2016.3.2, the Golang plugin, deleted and re-downloaded the Github rep and various other actions without success.

![intellij](https://cloud.githubusercontent.com/assets/24626105/21764264/756ae5f0-d662-11e6-9bcb-1cd463efe400.jpg)

The error is repeatable.

**Comment by zolotov** [comment]
Cannot recreate. Please specify exact revision of `walk` dependency and attach the sample project to recreate.

**Comment by lawtonykaps** [comment]
Hi, in the end I gave up on using the WALK Windows interface. I decided to use a browser as a user interface.
