### ISSUE TITLE
Can not update External Libraries tree after change project SDK

### ISSUE THREAD

**Issue by zjhmale** [go-lang-plugin-org/go-lang-idea-plugin#2861]
- Plugin version (or commit hash): 610ff0ef4e8a55690b9a480efe725c5776e341f8
- IDE name and version: IntelliJ IDEA 2016.2.2
- Java version: 1.8.0_111
- OS name and version: OSX 10.10.5

- What are you trying to do?

I want to update the Go SDK after I change the project SDK in `Project Structure` panel.

- What would you expect to happen?

The External Libraries tree can be updated immediately after I change project SDK.

- What happens?

It always displays the same Go SDK no matter how I change the project SDK.

I run the plugin from source using Gradle.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21892040/7b265b4a-d910-11e6-80cb-dd41e11e3994.gif)

Additionally, I think `go-lang-idea-plugin` and `intellij-erlang` have a similar internal design, but I can easily update the External Libraries tree immediately after I change project SDK with `intellij-erlang` even I comment all the configurations [here](https://github.com/ignatov/intellij-erlang/blob/master/plugin/resources/META-INF/plugin.xml#L44-L57) which confuses me a lot.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21892986/2844b1d4-d914-11e6-863d-4a573b7b2432.gif)

Thanks in advance for any help or advice :)

**Comment by zolotov** [comment]
How did you create a module? Did you choose a concrete SDK version or select Project inherited SDK?

**Comment by zolotov** [comment]
Works as intended, sorry. Changing project SDK != changing module SDK, which can be changed in Project Structure | Modules

**Comment by zjhmale** [comment]
Ok, change module SDK works as expected, thanks!

**Comment by zjhmale** [comment]
@zolotov so where is the option to inherit project SDK when creating a new Go module? I think selecting a concrete Go SDK is the only way to create a new Go module

**Comment by zolotov** [comment]
> when creating a new Go module? 

There is no. As I said in PR, this is the issue.

**Comment by zjhmale** [comment]
@zolotov Sorry, I did not read all the comments you posted on that PR 😅  Yeah, it is a UI problem indeed, we need a checkbox for inherit SDK option.
