### ISSUE TITLE
Testing: can't load package (./. instead of ./...)

### ISSUE THREAD

**Issue by fasa123** [go-lang-plugin-org/go-lang-idea-plugin#2862]
I have a folder with the following structure:

```
pkg
     sub1
     sub2
     sub3
```
 

pkg is the package root dir. 

If I run the tests I get a "can't load package: package" even if I pass ./... as go tool argument since the plugin automatically passes ./. making the executed command be "/usr/lib/go/bin/go test -v ./... ./.". If one wants to pass ./. one can pass it on their own no need to force ./. so please just remove it from the parameters.

 If there is another way to fix this please enlighten me.

**Comment by dlsniper** [comment]
This has been solved by the Go team in 1.8 RC3 as a regression. It can be closed.
