### ISSUE TITLE
Can set breakpoints inside go routines, but they are not honored.

### ISSUE THREAD

**Issue by lwoydziak** [go-lang-plugin-org/go-lang-idea-plugin#2867]
Go Plugin: 0.13.1924
IntelliJ IDEA 2016.3.4
Build #IC-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
MacOS: 10.11.4

- What are you trying to do?
```go
func main() {
	go func(){
		fmt.Print("this is a breakpoint in a go routine") //<- set breakpoint 1 here 
	}()
       fmt.Print("this is main")    //<- set breakpoint 2 here
       fmt.Print("main")
}
```
- What would you expect to happen?
Debugger would break at both breakpoint 1 & 2

- What happens?
Debugger only breaks at breakpoint 2

**Comment by dlsniper** [comment]
Hi,

That behavior is expected as the goroutine does not have a chance to be triggered while the program executes, goroutines are not scheduled as soon as they are called.
I'll close this for now.

**Comment by lwoydziak** [comment]
Great point, totally a race. Thank you, works fine after adding some synchronization.
