### ISSUE TITLE
Status of this plugin

### ISSUE THREAD

**Issue by fgblomqvist** [go-lang-plugin-org/go-lang-idea-plugin#2874]
What is the status of this plugin now that Gogland is maturing? Will development continue? It has obviously slowed off considerably lately, so I take that as a sign that it might not?

**Comment by ignatov** [comment]
@zolotov and I are planning to improve Gogland, and we don't have any specific plans about the open source plugin.
We could also ask @mtoader as an owner of this repo about his plans.

**Comment by mtoader** [comment]
I don't have definite plans so far but if the intent of Jetbrains is to only focus on gogland and not strive to keep this plugin in sync, and if there is value to this plugin i'm willing to start working on this again. 

The biggest point for me is what is the value of the plugin to the world. 

The biggest risk is functionality diverging between the plugin and the golangd but i might be ok with that.
