### ISSUE TITLE
intentionally ironic or typo

### ISSUE THREAD

**Issue by zlwp** [go-lang-plugin-org/go-lang-idea-plugin#2876]
[v1.0.0 Setup initial project](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/v1.0.0-Setup-initial-project)
Unfortunate. Unfortunately? Hope I'm not ruining the joke.
<img width="734" alt="screen shot 2017-03-02 at 4 00 34 pm" src="https://cloud.githubusercontent.com/assets/23284050/23529010/6be280ba-ff61-11e6-9fc5-9d19376b3e44.png">

**Comment by mtoader** [comment]
No joke. typo :).

**Comment by mtoader** [comment]
Fixed.
