### ISSUE TITLE
debug jumps to start panic

### ISSUE THREAD

**Issue by rahmanme** [go-lang-plugin-org/go-lang-idea-plugin#2877]
- Plugin version (or commit hash): 0.13.1933
- IDE name and version: intellij 2016.3.4
- Java version:
- OS name and version: MacOS 10.12.3

- What are you trying to do?
debug a golang application

- What would you expect to happen?
go to next level when press Step Over [F8]
- What happens?
jump to startpanic on panic.go

the error that i'v got is like this
unexpected fault address 0x6e52003cc28
fatal error: fault
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution

```go
package main

import "log"

func main() {

	log.Println("line 1")               <--- breakpoint


	log.Println("line 2")
}
```

<img width="1418" alt="screen shot 1395-12-19 at 03 00 37" src="https://cloud.githubusercontent.com/assets/3822228/23728946/a7b7b688-0474-11e7-9602-fc435695f100.png">

**Comment by ChristopherElliott** [comment]
Seeing the same issue. Was so confused as I'm just learning Go and thought I was misunderstanding the syntax.

**Comment by tomas-bareikis** [comment]
I am having the same issue too.

**Comment by tagarwal** [comment]
Same issue on Mac OSX

**Comment by adamlavie** [comment]
Same here. Using Ubuntu 16.04 using intellij v2017.1

**Comment by rahmanme** [comment]
I used Gogland and it works finally

**Comment by swojtasiak** [comment]
I had the same problem. It was caused by a panic inside init function of a module that was imported before main was called.

**Comment by dlsniper** [comment]
@swojtasiak please feel free to try https://www.jetbrains.com/go/ and see if it fixes your problem.
