### ISSUE TITLE
can't start a go project.

### ISSUE THREAD

**Issue by connelevalsam** [go-lang-plugin-org/go-lang-idea-plugin#2881]
- Plugin version (or commit hash):Go 1.7.1
- IDE name and version:Intellij CE
- Java version:1.8.0_111
- OS name and version: Ubuntu 16.04LTS

- What are you trying to do? 
Start a go project though I've already started running it with sublime text2 and terminal.

- What would you expect to happen? 
for it to be straight to the point. 

- What happens?
Directory '/usr/local/go/src' is not writable!
Please choose another project location.

Your issue description goes here.
Please be as detailed as possible

Followed your screenshot wiki docs but it's not getting past the choose project location where you suggested GOPATH which is ~/usr/local/go/src

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
the docs say to use ` ~/go ` not ` /usr/local/go`. Do not create projects inside GOROOT.

**Comment by connelevalsam** [comment]
good morning @dlsniper but that directory doesn't exist. It's going to read from home path.
