### ISSUE TITLE
cannot install plugin on intellij eap 2017.2

### ISSUE THREAD

**Issue by paologentili** [go-lang-plugin-org/go-lang-idea-plugin#2890]
- Plugin version (or commit hash): alpha or nightly
- IDE name and version: intellij 2017.2 eap
- Java version: 
- OS name and version:  Win7

- What are you trying to do?
installing the plugin via a custom repository using
alpha: https://plugins.jetbrains.com/plugins/alpha/5047
nightly: https://plugins.jetbrains.com/plugins/nightly/5047

- What would you expect to happen?
find the golang plugin
- What happens?
intellij can't find any plugins from that url

**Comment by zolotov** [comment]
https://plugins.jetbrains.com/plugin/9568-go is available for 2017.2

> https://plugins.jetbrains.com/plugins/nightly/5047

These plugins are not going to be updated (at least by me)

**Comment by paologentili** [comment]
thanks

**Comment by pavolloffay** [comment]
For goglang plugin does not work in 2017.2.

**Comment by ignatov** [comment]
Just repeated the comment by @zolotov:
> https://plugins.jetbrains.com/plugin/9568-go is available for 2017.2
> This plugin is not going to be updated (at least by me)

**Comment by pavolloffay** [comment]
I mean gogland plugin does not work in my idea 2017.2. I tied to install `Go 172.3317-EAP-CANDIDATE-SNAPSHOT.20` and `172.3317.6.107` and it even does not recognize go files..

**Comment by zolotov** [comment]
@pavolloffay likely something wrong with your settings, works fine for me. Please make sure that plugin is installed and enabled and check file types settings

**Comment by fangzhzh** [comment]
After I download `172.3317-EAP-CANDIDATE-SNAPSHOT.20` and install, it shows as red in plugins and doesn't recognise go source code.

**Comment by dlsniper** [comment]
Are you using IntelliJ Community?

**Comment by pavolloffay** [comment]
Yes that was the issue :/. new gogland works only in ultimate. It would be great to say it somewhere.

**Comment by zolotov** [comment]
> It would be great to say it somewhere.

@pavolloffay do you have a suggestion on the place where it should said?

At the moment, it is said in [FAQ](https://www.jetbrains.com/help/go/faq.html#d3e18). Also, community editions are not listed in `Compatible with` part of [plugin page](https://plugins.jetbrains.com/plugin/9568-go).
