### ISSUE TITLE
Receiving Incorrect Error - "not enough arguments in call to ..."

### ISSUE THREAD

**Issue by rjdlee** [go-lang-plugin-org/go-lang-idea-plugin#2894]
- Plugin version (or commit hash): 0.171.1931
- IDE name and version:
WebStorm 2017.1.4
Build #WS-171.4694.29, built on June 7, 2017
Licensed to Richard Lee
Subscription is active until January 24, 2018
For educational use only.
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

- What are you trying to do?
Trying to make a Gomega asynchronous assertion (https://onsi.github.io/gomega/#making-asynchronous-assertions).

- What would you expect to happen?
No error to happen. The code compiles are runs correctly.

- What happens?
An error.

```go
func Eventually(actual interface{}, intervals ...interface{}) GomegaAsyncAssertion {
	return EventuallyWithOffset(0, actual, intervals...)
}

...

// Plugin errors with "not enough arguments in call to Eventually"
Eventually(func() int {
			return len(0)
		}, 5 * time.Second, time.Second).Should(Equal(0))
```

**Comment by dlsniper** [comment]
You can uninstall the plugin you are using and install the JetBrains supported one, https://plugins.jetbrains.com/plugin/9568-go (you can find it in the IDE as well). That problem should be solved there. Hope it helps.
