### ISSUE TITLE
Cannot run debugger, permission denied

### ISSUE THREAD

**Issue by abzfarah** [go-lang-plugin-org/go-lang-idea-plugin#2896]
I am trying to run the mattermost application on my machine. I am trying to run debugger but I get the following error

`Error running Unnamed: Cannot run program "/Volumes/Gogland 1.0 EAP/Gogland 1.0 EAP.app/Contents/plugins/intellij-go-plugin/lib/dlv/mac/dlv" (in directory "/Users/***/go/src/github.com/mattermost/platform"): error=13, Permission denied`

How can I resolve this? It works fine on vscode.

**Comment by dlsniper** [comment]
Hi,

Can you please attach a screenshot of the tool window with the error?
What version of the IDE do you use? You can find it via: Help | About and click the Copy to Clipboard link.
Also, for future reference, the tracker for the issue can be found here: https://youtrack.jetbrains.com/issues/Go

Thank you

**Comment by zolotov** [comment]
You should install the IDE first

**Comment by abzfarah** [comment]
@zolotov I have it installed.

**Comment by abzfarah** [comment]
@dlsniper 

Screen shots

<img width="2296" alt="screenshot 2" src="https://user-images.githubusercontent.com/13402859/28146979-c84fcc5a-67c0-11e7-9737-19b7ca6487a6.png">
<img width="1073" alt="screenshot" src="https://user-images.githubusercontent.com/13402859/28146980-c850cf6a-67c0-11e7-8a1e-9c3583327edb.png">

**Comment by abzfarah** [comment]
Works fine when I just run it

<img width="2323" alt="screenshot 3" src="https://user-images.githubusercontent.com/13402859/28147048-2ffc8d02-67c1-11e7-999f-8cb43b570f1b.png">

**Comment by zolotov** [comment]
According to paths you provided, you run idea from mounted dmg, so it's not installed

**Comment by abzfarah** [comment]
@zolotov Legend :)

**Comment by kalpesh17021997** [comment]
@zolotov and @abzfarah
can you send me steps to resolve this issue?
