### ISSUE TITLE
Not able to install go lang plugin on intellij 2017.2 community edition

### ISSUE THREAD

**Issue by shruti1701** [go-lang-plugin-org/go-lang-idea-plugin#2897]
IDE name and version:
IntelliJ IDEA 2017.2
Build #IC-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-28-generic

After upgrading my intellij to 2017.2 i am getting the below error
Unknown Module Type
Cannot determine module type ("GO_MODULE") for the following module:"work"
The module will be treated as a Unknown module.

So i uninstalled the go plugin and tried to re-install it but i am not able to find it from the repositories. 
Also i tried to download the plugin( 172.3317-EAP-CANDIDATE-SNAPSHOT.20 and172.3198.6.18)
 from this url https://plugins.jetbrains.com/plugin/9568-go.
And tried with install plugin from disk options , but that does not work either

**Comment by dlsniper** [comment]
There are currently no plans to make this plugin compatible with 2017.2 as far as I know. The JetBrains maintained one is not going to compatible with the community version. You can use https://www.jetbrains.com/go/ if you want as a much better alternative than this plugin.

If you want to have this plugin working in IntelliJ community 2017.2, please send a PR. Thank you.

**Comment by josh-padnick** [comment]
I haven't yet explored how well it works, but here's how I at least go Golang functionality working again in in IntelliJ 2017.2:

1. Go to **Preferences...** > **Plugins**

1. Click on **Browse repositories...**

![image](https://user-images.githubusercontent.com/4295964/28477847-bdea8c28-6e0a-11e7-988f-85584c20ac73.png)

1. Type "Go" and select the official JetBrains Go plugin:

![image](https://user-images.githubusercontent.com/4295964/28477878-dff43bfc-6e0a-11e7-96ee-8d3c898d94dc.png)

At first blush, it feels like an improvement over the previous community-maintained plugin.

**Comment by dlsniper** [comment]
Please note that the above plugin works for only in the Ultimate Edition, not in the Community one. 

You can read more about the plugin here https://blog.jetbrains.com/go/ and you can find a part of the differences here https://www.jetbrains.com/help/go/faq.html#d3e55

**Comment by jerome-laforge** [comment]
Unfortunately, Goglang is not fully compatible with all plugins (e.g. [gitflow plugin](https://plugins.jetbrains.com/plugin/7315-git-flow-integration))

**Comment by dlsniper** [comment]
You need to install the ` Task Management ` plugin, restart the IDE then install the ` GitFlow ` plugin and it will work.

**Comment by dlsniper** [comment]
If you have any other plugins that don't work, please feel free to open an issue here: https://youtrack.jetbrains.com/issues/Go

**Comment by jbernhardsch** [comment]
Any solution for this issue?
Thanks

**Comment by dlsniper** [comment]
Yes, see my first comment on the issue https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2897#issuecomment-316320489

**Comment by bmarguer** [comment]
Opened Issue  #GO-4191 for Ant support.
Thanks

**Comment by Disastorm** [comment]
I found a workaround.
In intellij-go-0.171.1931.jar you change META-INF/plugin.xml file
from:

  <idea-version since-build="171.1834" until-build="171.*"/>
to:

  <idea-version since-build="171.1834" until-build="172.*"/>
The plugin seems to be working after this.

I'm not sure what you need to change in this repo to do that.

**Comment by suztomo** [comment]
@Disastorm 
Thanks, it worked:

    mkdir /tmp/foo
    cd /tmp/foo
    unzip ~/Downloads/Go-0.13.1947.zip
    mkdir intellij-go-0.13.1947.until-build-172
    cd intellij-go-0.13.1947.until-build-172/
    unzip ../Go/lib/intellij-go-0.13.1947.jar
    vim META-INF/plugin.xml # edit for the above
    rm ../Go/lib/intellij-go-0.13.1947.jar
    jar cvf ../Go/lib/intellij-go-0.13.1947.jar .

Then a zip file from /tmp/foo/Go directory (Go.zip) worked well for me with "Install plugin from disk" of my IntelliJ 2017.2 Community Edition.

**Comment by GoForGopher** [comment]
@Disastorm 
Thank you!
I searching for more than an hour.This worked perfectly.

**Comment by tiagopotencia** [comment]
For Intellij 2017.3, is just change to:

`until-build="173.*"/>`

**Comment by meetsubhojit** [comment]
@suztomo thanks for the commands

**Comment by notzippy** [comment]
I created a release that works without changes here - https://github.com/notzippy/go-lang-idea-plugin/releases I will try to keep this compatible with intellij

**Comment by andreyvolosyuk** [comment]
I've added all instructions given by @suztomo to a bash file. Run it as soon as phpstorm or another editor version was changed.

https://gist.github.com/andreyvolosyuk/fe87c3bfe2e1d8d5fb30719072c91e1f

**Comment by QuentinFra** [comment]
Any way to make this plugin work in IntelliJ community edition 2019.2?

**Comment by akshaygoyal** [comment]
@QuentinFra Try this:

`<idea-version since-build="171.1834" until-build="192.*"/>`

**Comment by rushi47** [comment]
If anybody is looking for answer with 2020 version its 
<idea-version since-build="171.1834" until-build="202.*"/>
But it seems its way different from Ultimate edition plugin as it have lot of Feature, for example it can show whole struct just by hovering to it.
Switching to **VS Code** -_-
