### ISSUE TITLE
Create new go file error

### ISSUE THREAD

**Issue by elvizlai** [go-lang-plugin-org/go-lang-idea-plugin#2904]
- Plugin version (or commit hash):
   173.2696.186
- IDE name and version:
   Gogland 173.2696.28
- Java version:
- OS name and version:
   Mac OS X

- What are you trying to do?
   create a new go file
- What would you expect to happen?

- What happens?

<img width="717" alt="dingtalk20171016150734" src="https://user-images.githubusercontent.com/501861/31599217-02a54728-b284-11e7-9056-eefb7e8ab1e9.png">

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
Hi. This has been addressed here https://youtrack.jetbrains.com/issue/GO-4562

For all Gogland / JetBrains maintained Go plugin  issues please use https://youtrack.jetbrains.com/issues/GO in the future.
Thank you.
