### ISSUE TITLE
File Watcher - Default go fmt

### ISSUE THREAD

**Issue by LaughingCabbage** [go-lang-plugin-org/go-lang-idea-plugin#2905]
- Plugin version (or commit hash): 173.3188.31
- IDE name and version: Build #GO-173.3188.63, built on October 17, 2017
- Java version: 1.8.0_152-release-1024-b5 amd64
- OS name and version: Windows 10 10.0

- What are you trying to do?
Use the default preset for go fmt in the File Watcher

- What would you expect to happen?
Runs go fmt on the current file

- What happens?
Output indicates go fmt runs but then does not actually format the file. A second command is executed to create a directory in my windows folder which obviously is rejected by the OS because Gogland is not running with elevated privileges. 

C:\go\bin\go.exe fmt *myfilepath*
mkdir C:\WINDOWS\go-build###... : Access is denied.

WORKAROUND:
Manually configure go fmt as a custom File Watcher tool. I've duplicated the exact commands used in the default configuration and it runs without issue, thus the confusion.

**Comment by dlsniper** [comment]
Thank you for reporting and sorry for the confusion. I've created the issue here: https://youtrack.jetbrains.com/issue/GO-4682 to track it. Please open any further issues on the tracker. Thank you.
