### ISSUE TITLE
packages in project GOPATH not getting resolved

### ISSUE THREAD

**Issue by darkpssngr** [go-lang-plugin-org/go-lang-idea-plugin#2906]
- Plugin version (or commit hash):
    172.3968.45
- IDE name and version:
  IntelliJIDEA 2017.2.5 IU-172.4343.14
- Java version:
  1.8
- OS name and version: 
   OSX El Capitan
- What are you trying to do?
   I'm using go-gradle plugin which automatically creates a directory called .gogradle and symlinks the entire project inside  .gogradle/project_gopath/src and also adds a project gopath which points to .gogradle/project_gopath
  When it does that IntelliJ is not able to resolve the packages even though go build from that gopath works fine. 
  
  My guess is that IntelliJ is not recognizing the project scoped GOPATH as I don't see it in the list of external dependencies.

<img width="358" alt="screen shot 2017-10-19 at 10 34 46 pm" src="https://user-images.githubusercontent.com/4415079/31783975-c4bd08aa-b51d-11e7-9fec-0a76798a6ce1.png">

can someone please help? Am I doing something wrong or is it a bug.

Thanks.

**Comment by dlsniper** [comment]
This is not the correct place to ask about the JetBrains supported Go plugin. You can ask here: https://youtrack.jetbrains.com/issues/Go However, based on the current information, I don't understand what is exactly the project layout or where the symlinks are and point to. When you'll open the issue there, please add that missing information. Thank you.
