### ISSUE TITLE
Running Extract Method Refactoring from an other plugin

### ISSUE THREAD

**Issue by selmadjiAnfel** [go-lang-plugin-org/go-lang-idea-plugin#2908]
- Plugin: Extract Method Refactoring
- IDE name and version: Eclipse mars 
- Java version: 1.8
- OS name and version: ubunto 14.04

- What are you trying to do?
 I am developing a plugin in which the first step is to extract new methods. My plugin determines the sequence of statements to be extracted as a new method. I want to know, please, how can I run the extract method operation from my plugin. 

- What would you expect to happen?
I expect that my plugin determines the sequence of statements to be extracted and then use the extract method operation to extract a new method.

- What happens?

Can you help me please. I read about ExtractMethodAction (http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fui%2Factions%2FExtractMethodAction.html) but I do not know how to use it. Thank you.
```

**Comment by dlsniper** [comment]
This is not related to Eclipse in any way, shape or form. Please see the open-source IntelliJ Platform supported plugins that have this functionality if you want to create a plugin for the IntelliJ Platform or the Eclipse plugins for Eclipse related functionality.
