### ISSUE TITLE
Cannot change GOROOT

### ISSUE THREAD

**Issue by brunoterkaly** [go-lang-plugin-org/go-lang-idea-plugin#2910]
- Plugin version (or commit hash):
- IDE name and version:
- Java version:
- OS name and version: 

I am trying to update the gogland ide to use a more recent version of golang. When I go into File/Settings/go/GOROOT, I am unable to change directory to a locally installed version of go, outside of the forced location of /usr/lib/go.

The reason I need to do this is that some of the libraries are dated.

For example, I am getting a compiler error, "undefined: io.SeekStart.

I am using Linux Ubuntu. I am using the bill from October 25, version 173.3415.23.

So to boil this down to simple questions is:

Why can I not change the goroot folder?

Can I copy the latest binaries of golang into /usr/lib/go to compensate for the fact that I cannot change goroot?

![jetbrains](https://user-images.githubusercontent.com/1461866/32919486-dcb8ac0c-cada-11e7-8796-d455b5895ce0.png)

![jetbrains2](https://user-images.githubusercontent.com/1461866/32919533-1337fce2-cadb-11e7-9062-a0aec7c6a7bc.png)

![snap0271](https://user-images.githubusercontent.com/1461866/32919643-73b64f42-cadb-11e7-9631-e893d1fee82a.png)
![snap0270](https://user-images.githubusercontent.com/1461866/32919644-7423ed04-cadb-11e7-9c3e-bf31e3cf294d.png)

**Comment by dlsniper** [comment]
This is not the correct place for the issue. I was writing the reply to your ticket on YouTrack.

**Comment by brunoterkaly** [comment]
Checking youtrack. No answer yet.

**Comment by dlsniper** [comment]
There is an answer now. This tracker is not the one for GoLand. I'll not provide further help on this issue here. Thank you for your understanding.
