### ISSUE TITLE
Plugin 'Go' is incompatible with this installation

### ISSUE THREAD

**Issue by vadim-codefresh** [go-lang-plugin-org/go-lang-idea-plugin#2911]
- Plugin version (or commit hash):Go 173.3727.25
- IDE name and version:WebStorm 2017.2.5
- Java version:1.9
- OS name and version: MAC OS 

- What are you trying to do?
Install Go plugin
- What would you expect to happen?

- What happens?
Plugin 'Go' is incompatible with this installation

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by dlsniper** [comment]
This is working as intended. Please use GoLand, https://jetbrains.com/go or IntelliJ Ultimate.

Also, in the future please open issues here https://youtrack.jetbrains.com/issues/Go for the GoLand specific issues.

Thank you.
