### ISSUE TITLE
there is no go sdk option where new sdk to project.

### ISSUE THREAD

**Issue by xiaoxuez** [go-lang-plugin-org/go-lang-idea-plugin#2915]
- Plugin version (or commit hash): 1.9.2
- IDE name and version: intelliJ IDEA
- Java version: 1.8
- OS name and version: Mac OS 10.12.1

- What are you trying to do?

new go sdk to project

- What would you expect to happen?

there is go sdk in option

- What happens?
 
just jdk,android.. no go sdk

```go
Please include a go sample to reproduce the issue
```

![2018-01-15 2 26 27](https://user-images.githubusercontent.com/18527267/34929708-706529b8-fa00-11e7-9651-b9109ae8acb9.png)
![2018-01-15 2 26 12](https://user-images.githubusercontent.com/18527267/34929710-76012246-fa00-11e7-83a6-526184433f54.png)
![2018-01-15 2 25 50](https://user-images.githubusercontent.com/18527267/34929715-7a01378c-fa00-11e7-9c63-ec62b6eabcae.png)

**Comment by dlsniper** [comment]
As you can see in the last screenshot you attached, the Go SDK is under Settings | Languages & Frameworks | Go | GOROOT. This has been so for a while and it will not change.

Furthermore, if you are using IntelliJ IDEA Ultimate, please open future support requests at the official JetBrains tracker, https://youtrack.jetbrains.com/GO, this project is abandoned now.

Thank you.
