### ISSUE TITLE
Fail to compile and run gotest

### ISSUE THREAD

**Issue by Ewg-sha** [go-lang-plugin-org/go-lang-idea-plugin#2916]
- Plugin version (or commit hash): 173.4381.1
- IDE name and version: IntelliJ IDEA 2017.3.3 (Ultimate edition)
- Java version: 1.8.0_152-release-1024-b11 amd64
- OS name and version: Redhat

- What are you trying to do?
run go test

- What would you expect to happen?
successful rnu

- What happens?
Compilation error

Your issue description goes here.
Please be as detailed as possible

The problem is in the way how IntelliJ tries to run compiler. It compiles single file instead of compiling the whole package (folder):
OROOT=<path>/go #gosetup
GOPATH=<my_path>/build/private/bgospace/pkg1:<my_path>/build/private/bgospace/Go3p-Ginkgo-Gomega:<my_path>/build/private/bgospace/Go3p-Github-Fortytw2-Leaktest:<my_path>/build/private/bgospace/Go3p-Github-Gogo-Protobuf:<my_path>/build/private/bgospace/Go3p-Github-Golang-Protobuf:<my_path>/build/private/bgospace/pkg2:<my_path>/build/private/bgospace/Go3p-Github-Grpc-GrpcGo:<my_path>/build/private/bgospace/Go3p-Github-Pkg-Errors:<my_path>/build/private/bgospace/Go3p-Github-Stretchr-Testify:<my_path>/build/private/bgospace/Go3p-Golang-X-Crypto:<my_path>/build/private/bgospace/Go3p-Golang-X-Net:<my_path>/build/private/bgospace/Go3p-Golang-X-Sync:<my_path>/build/private/bgospace/Go3p-Golang-X-Text:<my_path>/build/private/bgospace/Go3p-Gopkg-Check:<my_path>/build/private/bgospace/Go3p-Gopkg-Yaml:<my_path>/build:<my_path>/build/private/bgospace/pkg3 #gosetup
<path>/go/bin/go test -c -i -o /tmp/___config_file_parsing_test_go__1_ <my_path>/<another_path>/proxy/config_file_parsing_test.go #gosetup
# command-line-arguments
./config_file_parsing_test.go:12:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:22:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:38:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:38:53: undefined: commandLineOptions
./config_file_parsing_test.go:64:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:64:53: undefined: commandLineOptions
./config_file_parsing_test.go:84:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:84:53: undefined: commandLineOptions
./config_file_parsing_test.go:100:17: undefined: initializeProxyConfig
./config_file_parsing_test.go:100:53: undefined: commandLineOptions
./config_file_parsing_test.go:100:53: too many errors

Compilation finished with exit code 2

All undefined symbols could be found in
<my_path>/<another_path>/proxy/config_file_parsing.go

The same setup works in GoLand, where IDE issues a bit different compilation instruction:
<path>/go test -c -i -o /tmp/___config_file_parsing_test_go <another_path>/proxy #gosetup

**Comment by dlsniper** [comment]
Please report any further issues on the official tracker: https://youtrack.jetbrains.com/issues/Go, this is not to be used anymore.

However, to answer your question for now: You need to create the run configuration to use the package instead of a single file. To do so, go to ` Run | Edit Configuration | Go Application | <name of your configuration> | Run ` kind and select ` Package ` instead of ` File ` then the IDE will complete automatically the first part of the package in the field, for example ` github.com/dlsniper/demo ` and then you can add the rest of the package path as needed.
