### ISSUE TITLE
No plugins found

### ISSUE THREAD

**Issue by hxun123** [go-lang-plugin-org/go-lang-idea-plugin#2917]
- IDE name and version: PhpStorm
- OS name and version:  MacOS

- What are you trying to do?
Install this plugin

- What would you expect to happen?
Install success

- What happens?
No plugins found

<img width="1279" alt="wx20180120-145059 2x" src="https://user-images.githubusercontent.com/9814393/35180771-63887c78-fdf1-11e7-9aca-f96155485eeb.png">

**Comment by dlsniper** [comment]
Please read this https://blog.jetbrains.com/blog/2017/12/01/clarification-on-go-support-plugin-availability-in-intellij-based-ides/ and contact sales@jetbrains.com to get help with this.

**Comment by dlsniper** [comment]
Furthermore, this plugin is discontinued from support, see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2913
