### ISSUE TITLE
Fail to load plugin descriptor from file go-lang-idea-plugin-master.zip

### ISSUE THREAD

**Issue by sonofwindsven** [go-lang-plugin-org/go-lang-idea-plugin#2919]
If you are using [GoLand](https://jetbrains.com/go) or [IntelliJ IDEA Ultimate](https://jetbrains.com/idea) 2017.3 or later, please report your issue at the official tracker: https://youtrack.jetbrains.com/issues/Go

This repository is not maintained anymore.

- Plugin version (or commit hash):
- IDE name and version:
- Java version:
- OS name and version: 

- What are you trying to do?

- What would you expect to happen?

- What happens?

Your issue description goes here.
Please be as detailed as possible

```go
Please include a go sample to reproduce the issue
```

Or include a screenshot / video of the issue.

**Comment by xxz199539** [comment]
here is my IDEA version
```
PyCharm Community Edition 2017.2.3
Build #PC-172.3968.37, built on September 1, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```
when i install plugin from disk,i get this err:`Fail to load plugin descriptor from file go-lang-idea-plugin--1288.zip`
