### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [go-lang-plugin-org/go-lang-idea-plugin#2923]

**Comment by hidayatdwi82** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCWe3sCr4ZWlKjTP7CZ46CpVqV8Q_Y7RtbKTLtNqiRXrRgf7FbvkUTb3vVTrjlXh00b2PDsfhJKeeIzEfJEHLLbyBG-VnqUMl6G2sc-STyLaf9yN4AprBCQoaiyNbwlAvJRzxcU3c_MoHEtyn46Df40yFPd1OeS38mFZY0MnzLxyzO42ix93Jj6WQkPcc/s1600/image_2024-11-28_080456073.png)](https://t.co/tVdM4jwOr4)
