### ISSUE TITLE
OSX Mavericks cannot run with imported remote package

### ISSUE THREAD

**Issue by jamra** [go-lang-plugin-org/go-lang-idea-plugin#318]
# My go env

```
GOARCH="amd64"
GOBIN="/Users/jacob/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jacob/go/src"
GORACE=""
GOROOT="/Users/jacob/go"
GOTOOLDIR="/Users/jacob/go/pkg/tool/darwin_amd64"
TERM="dumb"
CC="clang"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
# Additional env info

OSX Mavericks
Intellij 13.0
# Issue

Builds Hello World just fine. When I import a remote package, it does not work even though the go run command works fine from the terminal.

The output is:

```
/Users/jacob/IdeaProjects/untitled1/src/main.go:8:2: cannot find package "github.com/opesun/goquery" in any of:
    /Users/jacob/go/src/pkg/github.com/opesun/goquery (from $GOROOT)
    /Users/jacob/IdeaProjects/untitled1/src/github.com/opesun/goquery (from $GOPATH)
    null/src/github.com/opesun/goquery
```

**Comment by honkskillet** [comment]
I just did a mac install using homebrew and I have the same problem.  Cannot import remote packages and get essentially the same errors...
> $ go install
> demo.go:3:8: cannot find package "github.com/bradfitz/gomemcache/memcache" in any of:
>	/usr/local/Cellar/go/1.4/libexec/src/github.com/bradfitz/gomemcache/memcache (from $GOROOT)
>	/Users/white/go/src/github.com/bradfitz/gomemcache/memcache (from $GOPATH)
