### ISSUE TITLE
go lint support

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#342]
It would be nice if the plugin would support ``` go lint ``` as an external tool for running for running against a package / module / file.

The only issue with it is that it's not always available as it needs to be installed by the user (maybe we should have a: 'Install go lint' option first').

go lint documentation can be found [here](https://github.com/golang/lint).

I've opened this to keep track of it.

Thanks.

**Comment by dlsniper** [comment]
Run configurations support running go tools before actual runner. Also, the rules in golint should rather be ported in the plugin. Closing this for this reason.

**Comment by ignatov** [comment]
Better to use is as an external annotator.

**Comment by dlsniper** [comment]
I'll have a look into that next then. Thank you.

**Comment by nikicat** [comment]
:+1:

**Comment by dlsniper** [comment]
Some updates for this one: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1554#issuecomment-108069809 TL;DR: we should wait for IDEA 15 then see how things go or... Implement the checks inside the plugin (prefered way).

**Comment by pires** [comment]
15 is out. Any update on this?

**Comment by dlsniper** [comment]
if @zolotov and @ignatov greenlight this, I can redo https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/1554 but I don't know if the internal of the platform support this better now or not.
On the other hand, many of the "inspections" that go lint support could be integrated fairly easy with the plugin, but there are not many contributors that seem to want to pick up the work on this.
Finally, to make this fully work, the plugin lacks type inference so that things such as `var demo string = 10` can be flagged as errors but that's a known issue.

**Comment by zolotov** [comment]
@pires @dlsniper nope, still the same. Also I prefer to implement all usable checks from all go linters (gometalinter) as a intellij inspections, it's proper solution and it would work much better, but apparently we need more time for this.

**Comment by pires** [comment]
+1 for gometalinter

**Comment by dlsniper** [comment]
@pires what @zolotov meant was that the checks should be implemented in the plugin not to use gometalinter in the plugin. The checks are usually easy to medium to do, but unfortunately it takes a bit of time to have them in the plugin since there are not too many contributors helping out with them.

Instead of +1-ing, it would be much more helpful if contributors could try and pick up some of the inspections from the list: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues?q=is%3Aopen+label%3A%22up+for+grabs%22+label%3Ainspections @zolotov and @ignatov are very helpful with new contributors (unfortunately I know too little to help in complicated issues).

Please don't misunderstand me, it's good to know that people are interested in a certain feature, but +1-ing just sends an email to everyone watching the issue with no new update. You might also want to ping Github support to add a voting feature instead, which would also benefit everyone else.

**Comment by dlsniper** [comment]
Closing this as all inspections have been translated into issues.

**Comment by montera82** [comment]
this task is closed, was this finally implemented?
