### ISSUE TITLE
Implement Search Everywhere API

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#423]
It would be a nice to have.
See some sample work here:
- https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/189#ref-commit-981c9bb

**Comment by dlsniper** [comment]
@ignatov or @zolotov seems I'll need a bit more than the link I've found as on a first glance, the implementation the plugin has for ```GoSymbolContributor``` and ```GoTypeContributor``` looks the same as the one in the reference I've had. Also the element returned, ```com/goide/tree/GoStructureViewFactory.java::Element``` seems to be implementing the same interfaces as well.

Am I missing something? I couldn't find anything in the Confluence docs or YouTrack when I've searched for ```search everywhere api```.

Thank you.

**Comment by zolotov** [comment]
I believe it could be closed, right?
