### ISSUE TITLE
Is it possible to apply different colors to method name and it's arguments in method call(not definition)?

### ISSUE THREAD

**Issue by AlexLuya** [go-lang-plugin-org/go-lang-idea-plugin#436]
I am using rethink db,and it query language is quite special,some thing like this:

_, err := rt.Table(s.Table).Insert(model).RunWrite(s.Session)

sometime,it is much longer.if the color of method name here(Table,Insert,RunWrite) can applied different color with arguments(s.Table,model,s.Session).It will help to code reading.

**Comment by dlsniper** [comment]
Fixed in 1.0
