### ISSUE TITLE
GOROOT and GOPATH warning shows up even those were properly set.

### ISSUE THREAD

**Issue by coocood** [go-lang-plugin-org/go-lang-idea-plugin#442]
It's very annoying, can we just remove it?

**Comment by jalateras** [comment]
This still seems to be an issue with intellj and webstrom. I am still getting these warning indicating that the variables have not been set

**Comment by dlsniper** [comment]
@jalateras and all, please try the latest 1.0 release from the github releases section and things should work better.

**Comment by jalateras** [comment]
@dlsniper thanks. just installed it and all is good so far

**Comment by seb0zz** [comment]
Does anyone else still have this problem? I cannot get rid of the message even when I start Webstorm directly with GOPATH or GOROOT as environment variable :-1:

**Comment by dlsniper** [comment]
@seb0zz which IDE and what version are you using? :+1:

**Comment by seb0zz** [comment]
Just upgraded to Webstorm11

**Comment by dlsniper** [comment]
Please upgrade the plugin as well. There are no warnings in the latest plugin releases about the GOPATH and GOROOT. Which plugin version are you currently using? if you installed it manually it might be needed to uninstall it first.

**Comment by seb0zz** [comment]
I am currently using version 0.10.607

**Comment by dlsniper** [comment]
Can you please open up a new issue and attach a screenshot to it? It's very strange. Thank you.
