### ISSUE TITLE
Help inside the plugin

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#465]
It would be cool if we would have some plugin help sections as we refer sometimes to them in the plugin, I've forgot exactly where.

**Comment by dlsniper** [comment]
@ignatov do you know of any way where I could start working on this for the 1.0 release? Thank you.

**Comment by ignatov** [comment]
Ping ;)

**Comment by dlsniper** [comment]
@ignatov I've started working on it here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/%5BWIP%5D-v1.0-Documentation I plan to add more by the end of the week.

Please let me know what do you think about it. Thank you.

**Comment by ignatov** [comment]
Seems to be closed, right?

**Comment by dlsniper** [comment]
Yes, good catch.
