### ISSUE TITLE
Function arguments that are functions always are flagged as wrong

### ISSUE THREAD

**Issue by kcrca** [go-lang-plugin-org/go-lang-idea-plugin#508]
The following completely legal Go code generates an error: 

```go
package gona

type Filter func(name string) bool

func runFilter(f Filter) {
	return
}

func filterFunc(name string) bool {
	return name == "foo"
}

func foo() {
	runFilter(filterFunc)
}
```
It marks the runFilter(filterFunc) invocation as a type mismatch. It isn't one.

I've looked at the source, and traced it this far: in GoUtil.CompairTypes, there is the following block of code:

```
        if (element2 instanceof GoTypePsiBacked) {
            GoPsiType psiType = ((GoTypePsiBacked) element2).getPsiType();
            if (psiType != null)
                return psiType.isIdentical(element);
        }
```
This gets followed for the invocation in question. `psiType` is not null, so isIdentical() is called. in this case, `psiType` is a `GoFunctionDeclarationImpl`. But `GoFunctionDeclarationImpl.isIdentical()` always (always!) returns false. There's a big TODO there. Which is fine, but it should return true, so as at least not to falsely flag an error. If it knows how to do nothing, it shouldn't say it's found something bad.

Unfortunately fixing this correctly is beyond me. I just changed that method to return true. This is a workaround for now, but it is a better state of affairs.

(FWIW, the `goType` passed in is not a `GoPsiTypeFunction`, as inspected, so it returns the first false, not the second. However, since this is a valid construct, this `instanceof` check is wrong. It is at least incomplete, and considering this a mismatch an error is wrong.)

**Comment by dlsniper** [comment]
This is fixed under 1.0
