### ISSUE TITLE
Do not index everything under GOPATH

### ISSUE THREAD

**Issue by nbrownus** [go-lang-plugin-org/go-lang-idea-plugin#519]
I have a ton of code in my GOPATH, a lot of it is not go code. I assume it would be ok to only index the Go SDK, the project root (and everything underneath it), and any imports.

With the current setup it will take a few hours to index everything under my GOPATH and anytime anything changes anywhere in my GOPATH I will be in a world of hurt.

**Comment by kgdev** [comment]
I used webpack to generate temporary js files (watch mode) under gopath. It will indeed slow down webstorm a lot! Is there any way not to index JS files at least?

**Comment by zolotov** [comment]
@kgdev only by disabling JavaScript plugin
