### ISSUE TITLE
Type assertions should be properly parsed inside expressions

### ISSUE THREAD

**Issue by mtoader** [go-lang-plugin-org/go-lang-idea-plugin#553]
Right now we don't correctly parse expressions like:

```go

var a = x.(type)

```
which is correct as a `expr.(type)` assertion is only valid inside a switch expression. However it should be parsed and highlighted appropriately.

**Comment by dlsniper** [comment]
@ignatov this is still relevant in 1.0.

In the example below, the completion engine doesn't work anymore after a such error.

```go
package main

import "fmt"

func main() {
	b := 0
	var a = b.(type)
	_ = a
	fmt.// I should autocomplete here but...
}
```
