### ISSUE TITLE
plugin ignores package names

### ISSUE THREAD

**Issue by gertcuykens** [go-lang-plugin-org/go-lang-idea-plugin#554]
goapp serve does find the module cloud
![image](https://f.cloud.github.com/assets/863731/1951013/1636a59a-8167-11e3-85eb-e23aaf595017.png)

**Comment by ignatov** [comment]
@zolotov @dlsniper Does it work correctly with the latest build?

**Comment by dlsniper** [comment]
@ignatov yes, this should work now, I think, it's a bit tricky to check as I don't have a good case to reproduce it right now. I suggest closing this and if needed we can either have it reopened or a new issue.
