### ISSUE TITLE
'No Go Sdk defined for this project' error occurs even when a Go module is set to a Go SDK

### ISSUE THREAD

**Issue by skyllo** [go-lang-plugin-org/go-lang-idea-plugin#583]
Hii!

I wanted to include one golang module into my existing project, the other modules in that project were Java so the project sdk was the Java JDK. I set the 'Module SDK' of the only golang module to the 'Go SDK go1.2...' thinking that would be okay.

However when I ran the go module it says 'No Go Sdk defined for this project', as the current project sdk is set to the Java JDK.

My current workaround for this is setting the whole project sdk to the Go SDK, and setting the individual Java projects to the Java JDK. Then this mixing of modules seems to work fine.

I don't know if this is intended or not but it seems like it the Java plugin does handle this case.

Thanks, happy to help further if needed!

**Comment by dlsniper** [comment]
This is properly working right now.
