### ISSUE TITLE
Issue Resolving func & method in local import 

### ISSUE THREAD

**Issue by olekukonko** [go-lang-plugin-org/go-lang-idea-plugin#587]
We a topical project structure 

```
project/
├── app.go
├── search.go
├── lib/
│   └── util.go
│   └── probe.go
└── server.go
```

Using the following import is valid in `app.go` , `search.go` & `server.go`

```go
import (
	"./lib"
)
```
But the current plugin can not resolve methods & function when modules are created in a a package:

`Screen Short app.go`

![image](https://f.cloud.github.com/assets/2615393/2111154/c0d9b992-900d-11e3-8788-34b533e72a94.png)

`Screen Short util.go`

![image](https://f.cloud.github.com/assets/2615393/2111175/f00a1040-900d-11e3-8534-b9f722ed6875.png)

As you can see it shows `red` but the application complies perfectly

**Comment by dlsniper** [comment]
Fixed in 1.0
