### ISSUE TITLE
Go-ide darwin-amd64 package broken ("Go Ide" is damaged and can't be opened)

### ISSUE THREAD

**Issue by alexandre-normand** [go-lang-plugin-org/go-lang-idea-plugin#590]
Since it's one of the only contribution I made early in this project, it's ironic that this would be the thing that is now blocking me from trying the newer version of the Go-ide. I downloaded the Mac amd64 version (twice, just to be sure) and the dmg opens fine but the app that's included seems to be corrupted. I get `"Go ide" is damaged and can't be opened` when trying to run it. 

I tried using the `package.sh` script that was used a while back and got stuck on a few things. I started changing the script a bit to get further but finally got to the ant build of the plugin that failed on a compilation error before I had to stop my efforts (I was time-boxing it). 

Am I the only one having trouble with the mac package for the bundled Go-ide 1.0? Are the packaging scripts still used? 

For reference, I was running with these environment variables
```
SOURCE_PATH_IDEA=<mypathto>/idea/
SOURCE_PATH_GO=<mypathto>/go
RELEASE_TAG_GO=go1.1.1
RELEASE_TAG_IDEA=idea/130.1190
CGO_ENABLED=0
```
And this tweaked version of the packaging script: https://github.com/alexandre-normand/google-go-lang-idea-plugin/compare/darwin-packaging?expand=1

And here's the output (minus the build of go and idea because that's a run with `SKIP`):
https://gist.github.com/alexandre-normand/882019e135e90552bedc

**Comment by dlsniper** [comment]
I'll close this as the plugin currently supports all IDEs
