### ISSUE TITLE
WS.Malware.1 appear to be in GoIde htmlify.bin ! This is what I get on Windows 7 From Norton.

### ISSUE THREAD

**Issue by patrickToca** [go-lang-plugin-org/go-lang-idea-plugin#593]
![image](https://f.cloud.github.com/assets/2913677/2125259/373a975e-924e-11e3-8356-fa0bce654fc0.png)

**Comment by dlsniper** [comment]
I'll close this as the plugin currently supports all IntelliJ IDEs.
