### ISSUE TITLE
Congrats for the project

### ISSUE THREAD

**Issue by cthackers** [go-lang-plugin-org/go-lang-idea-plugin#597]
Hi guys, I'm sorry I raised this as an issue but there's no messaging board for the project (perhaps that's what github is missing). I just wanted to congratulate and thank you all for this project you have going on. I love Go and IntelliJ and this is the perfect matchmaker. Also the latest code spree that seems to be happening here can only bring joy to any gopher.

Do you guys plan to integrate the debug functionality soon ? I really, really, really would want to see that happening. 

Cheers, and keep up the good work.

**Comment by dlsniper** [comment]
I'm closing this for various reasons. One of them is the delve integration which is a work in progress now.
