### ISSUE TITLE
Sometimes idea gets confused when calculating unused variables

### ISSUE THREAD

**Issue by twoolie** [go-lang-plugin-org/go-lang-idea-plugin#600]
![screenshot from 2014-02-11 16 49 26](https://f.cloud.github.com/assets/270117/2134467/8d7cdd60-92e5-11e3-88b8-6055adad512c.png)

As you can see from the screenshot; on the second line, idea doesn't think that `interpreter` exists. On the line above, it doesn't like `interpreter` because it believes it to be unused.

The problem seems to present when certain lines are being cut/paste from other parts of the program. Reproducing it is hit and miss. The problem disappears if these three lines are cut and pasted back into the same exact place.

**Comment by dlsniper** [comment]
Missing steps to reproduce
