### ISSUE TITLE
Add support for go coverage tool

### ISSUE THREAD

**Issue by m0sth8** [go-lang-plugin-org/go-lang-idea-plugin#602]
Go 1.2 has new "go tool cover" program.

http://golang.org/doc/go1.2#cover

**Comment by ignatov** [comment]
Obsolete?

**Comment by dlsniper** [comment]
Yes, I'll close it. the support is working pretty nice in the latest versions + IDEA 14.1. Thank you!

**Comment by JoeBruner** [comment]
?? Did I misinterpret what you said?  It sounds like you're saying that the go tool cover is integrated into IDEA. I haven't seen any way to do it other than running from terminal.

**Comment by dlsniper** [comment]
To get this working you need to create a test run configuration and then simply select ```Run with Coverage``` instead of ```Run``` from the IDE. I'll start working on the plugin documentation and I'll make sure to cover this as well.

**Comment by zolotov** [comment]
@JoeBruner see the [demo](http://screencast.com/t/S2N0q9F7D)
