### ISSUE TITLE
decompile from binary golang execute file support

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#606]
Something like objectdump, but with goto ,found usage or other idea stuff in it.
Asm code is useful for adjustment performance, fix some pointer bugs.
Is there some idea plugins can achieve this?
Is gdb support in this plugin can achieve this?
I think this is a low priority feature.

**Comment by dlsniper** [comment]
I'd close this for now, as there are no other requests to support this and there are more well suited apps to decompile apps.
