### ISSUE TITLE
Missing ENV.md needs to mention that windows also has a problem

### ISSUE THREAD

**Issue by ghstahl** [go-lang-plugin-org/go-lang-idea-plugin#608]
in your documentation you state the following; Windows is not reported to have similar issues.
However, I have this the missing environment paths problem on both Windows 8.1 and MAC OS X

My Fix on Windows 8.1
1. I create my workspace on h:\gocode
2. I set a User Variable:  GOPATH = h:\gocode.

That make intellij not complain about a missing GOPATH.  
On Windows 8.1  Intellij doesn't complain about a missing GOROOT, but It does complain about it on MAC OS X

**Comment by dlsniper** [comment]
There's no need for this anymore.
