### ISSUE TITLE
Disabling Use Tab Character in Go code style has no effect

### ISSUE THREAD

**Issue by SpOOnman** [go-lang-plugin-org/go-lang-idea-plugin#611]
I've disabled "Use Tab Character" as I want to use spaces instead of tabs. Disabling this option has no effect - IDEA still idents my code with tabs when I write or reformat code. I expect IDEA to use spaces when I disable "Use Tab Character".

IntelliJ IDEA 13.0.2 with Go plugin 0.9.16.

**Comment by hnsl** [comment]
http://emacswiki.org/emacs/TabsAreEvil

**Comment by vburenin** [comment]
https://golang.org/cmd/gofmt/

Gofmt formats Go programs. It uses tabs (width = 8) for indentation and
blanks for alignment.


Feel free to file a bug against Go.

**Comment by dlsniper** [comment]
I've yet to check in the latest release but like @vburenin said, the go way of doing things is with tabs and the plugin aims to respect those standards and help Go programmers be compatible with the rest of the Go ecosystem. You can read more about this in the link I've posted above.
