### ISSUE TITLE
Run go build on a directory instead of specific file

### ISSUE THREAD

**Issue by jkbbwr** [go-lang-plugin-org/go-lang-idea-plugin#614]
Go build is able to run against a directory so the plugin should be able to do this as well.

The interface should be changed to accommodate for this.
## Old description

With two files like so

```
package main

import (
    "fmt"
)

func main() {
    fmt.Printf("Hello world! %d", test())
}
```

And 

```
package main

func test() int {
        return 2+2;
}
```

I get the following errors 

```
Could't build project C:\projects\CronOverlord\bin/CronOverlord.exe
C:/Go/bin/go.exe build  -o C:\projects\CronOverlord\bin/CronOverlord.exe     C:/projects/CronOverlord/src/github.com/jkbbwr/cronoverlord/CronOverlord.go

Could't build project C:\projects\CronOverlord\bin/CronOverlord.exe
# command-line-arguments
   C:\projects\CronOverlord\src\github.com\jkbbwr\cronoverlord\CronOverlord.go:8: undefined: test
```

My output for `go env`

```
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\projects\go;C:\projects\CronOverlord
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-g -O2 -m64 -mthreads
set CGO_ENABLED=1
```

My project is structured as so

```
src\github.com\jkbbwr\cronoverlord\
    - CronOverlord.go
    - test.go
```

In the command line I can build it by going into the directory and running `go build`
I can even run it by doing `go run CronOverlord.go test.go`

I currently have `build before run` turned on

It tries to build, fails because it can't find `test.go` And then tries to run the single file `CronOverlord.go` which fails for the same reason. 

Is there a fix? Because this makes using this plugin impossible

**Comment by mageddo** [comment]
The follow command works great for me 

    $ go build -o build/hello hello.go 
	.
	├── build
	│   └── hello
	└── hello.go
