### ISSUE TITLE
Go debug doesn't work

### ISSUE THREAD

**Issue by betmenorg** [go-lang-plugin-org/go-lang-idea-plugin#621]
Except breaking on arbitrary breakpoints, nothing actually works. I cannot inspect any variable or see anything in the debugger window (frames, variables, watches).

Also, on Windows, all paths must be manually converted to / in the Run/Debug Configurations window for the debugger to start. If not it will try to load the build from a path like C:ProjectsGoTestdebug/main.exe stripping every slash

**Comment by dlsniper** [comment]
Not relevant for 1.0 anymore (at least for now).

**Comment by johnnywidth** [comment]
@nkev I can run debug like you on ubuntu, and preference go application look like in this question http://stackoverflow.com/questions/28104508/how-to-use-intellij-idea14-0-2-to-debug-the-golang
But on mac 10.10.3 with idea 14.1 my go application preference look like this
![image](https://cloud.githubusercontent.com/assets/3796597/7430203/fa8f05be-f017-11e4-93d0-6f49fd26f216.png)
What wrong?

**Comment by dlsniper** [comment]
@johnnywidth there's nothing wrong with the screenshot you've mentioned. That is part of the unreleased version 0.9.16 which was available in the master branch for the better part of the last year.
Meanwhile, the plugin was updated heavily and debug support for GDB still exists, but it's highly experimental. You should upgrade the plugin in both installations of the IDEs by following the instructions here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds

**Comment by johnnywidth** [comment]
@dlsniper Add alpha url and upgrade plugin to 0.9.300, nothing change.

**Comment by dlsniper** [comment]
@johnnywidth please open a new issue to not send messages to the other issues as the thread is a year old. Thank you.

**Comment by johnnywidth** [comment]
@dlsniper thanks, created. https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1593

**Comment by Kup3a** [comment]
For people, who meet this issue during search of ways to debug go-project.
My main file was in directory `...go/src/project/cmd/project/`. To debug my project I edited configuration in following way: 
```
Run kind:    Directory
Directory:   ...go/src/project/cmd/project/
```
It helped.

**Comment by dlsniper** [comment]
Or you can use ` Run Kind: Package ` and ` Package: project/cmd/project `. However, this project is unmaintained for more than a year now. If you use GoLand or IntelliJ IDEA Ultimate 2017.3+, the issue tracker is here: https://youtrack.jetbrains.com/issues/Go
