### ISSUE TITLE
error Interface not recognized correctly by the IDE

### ISSUE THREAD

**Issue by dvirsky** [go-lang-plugin-org/go-lang-idea-plugin#630]
(this happens to me with a build of the master, with go 1.2). 
I have a custom error type that implements the `error` interface, and a function that returns `error`. returning my own error type works in compilation but is wrongfully detected as a wrong return type by the IDE.

code to reproduce:

```go
type MyError struct {}

//this makes my type compliant with error
func (m MyError)Error() string {
	return "foo"
}

func foo() error {
	return MyError{} // <<---- the IDE will report an error "Experession type mismatch, the expected type is error
}

```

**Comment by dlsniper** [comment]
Fixed in 1.0
