### ISSUE TITLE
Proposal: Have debugger use a virtual PTY.

### ISSUE THREAD

**Issue by twoolie** [go-lang-plugin-org/go-lang-idea-plugin#655]
Currently, the output from the debugger is interleaved between GDB output and Stream output. sometimes, Streams to not end with a newline, and this means that the GDB-mi parser has to try to parse inside stream lines. This sometimes causes problems with parsing (as my previous patches have tried to address). Additionally, all input is interpreted as GDB commands, making it impossible to debug an interactive go program.

While reading through the GDB documentation, I discovered that it is possible to instruct gdb to hook the process up to a virtual PTY using GDB command `set pty {PTY_LOC}`. It is also possible to use `com.jediterm.pty.PtyProcessTtyConnector` to create and connect to a virtual PTY in a platform agnostic way. This would allow us to have full duplex communication with the process under test, and allow command input in the debugger console.

I'm having a bit of trouble finding documentation for `PtyProcessTtyConnector` so before I disappear down the rabbit hole, is this something that the core devs/contributors would consider accepting If I were to get it working?

**Comment by dlsniper** [comment]
Not applicable anymore. @twoolie see Dereks and my efforts in: https://github.com/derekparker/delve/pull/57 if you want to help getting IDEA (and the Go community) a nice debugger. Thank you!
