### ISSUE TITLE
Build rewrite source file to binary

### ISSUE THREAD

**Issue by rockerzz** [go-lang-plugin-org/go-lang-idea-plugin#664]
If set "Build before run" option in the "Run" settings and then press "Shift-F10" for run project IDEA is freezes and source file changes to binary:

![image](https://f.cloud.github.com/assets/872690/2480807/2d110430-b0ca-11e3-9cc0-5bb0aaa87429.png)

Plugin version is master baadb103c3fe523c3a41cc51a9bd9b9c2108e758
Idea Ultimate 13.1

**Comment by dlsniper** [comment]
Not applicable anymore.
