### ISSUE TITLE
Default Debug-Build arguments

### ISSUE THREAD

**Issue by d3xter** [go-lang-plugin-org/go-lang-idea-plugin#672]
Currently, we pass in "-N -I" as gcflags.

I had some problems with it, and so i looked it up.

**-N** disables optimizations, but
**-I** specifies include paths (C folks will be familiar with it).
This can cause problems, depending on what strings come after it)

So i was wondering, if we need -I as default gcflag?

**Comment by dlsniper** [comment]
Not applicable anymore.

**Comment by cyphunk** [comment]
Could you perhaps remember how this was resolved? I'm running into similar errors but in a different project. I'm assuming that my 2 year old go installation has to be updated to support the `latest` and greatest flags?

**Comment by dlsniper** [comment]
@cyphunk Please open a separate issue. This was closed as the IDE will now handle the gcflags automatically when building the debug version of the binary. Please include what error you are receiving and if possible any steps to reproduce the issue. Thank you!

**Comment by cyphunk** [comment]
i resolved the issue. For me it was just an old go version installed. At the time that wasn't clear to me. Thanks for the response though

**Comment by dlsniper** [comment]
Ok, glad to hear you've managed to solve the issue. Enjoy using the plugin.
