### ISSUE TITLE
fmt doesn't work on active tab, if split

### ISSUE THREAD

**Issue by tollek** [go-lang-plugin-org/go-lang-idea-plugin#684]
I am working with vertically split tabs.
If I run formatting (ctrl+alt+shift+f), code is always formatted in the right tab (even if the left one is active).
I'd expect formatter to run for source in my active tab.

IntelliJ 13.1.1
Ubuntu 13.10
OpenJDK 1.7

**Comment by dlsniper** [comment]
Not sure if applicable anymore.
