### ISSUE TITLE
Use module defined SDKs instead of project wide ones

### ISSUE THREAD

**Issue by gertcuykens** [go-lang-plugin-org/go-lang-idea-plugin#687]
Projects should be organized so that they support setting module SDKs instead of project-wide SDKs.

Original report:
===

If I have a mix of sdk's for example android and go_appengine, the plugin only wants to run when the go_appengine sdk is set to default. It should not do that check and refer to the module settings instead. (v671)

![c1](https://cloud.githubusercontent.com/assets/863731/2755084/75e81332-c962-11e3-8ba5-8e93d85c495e.PNG)
![c2](https://cloud.githubusercontent.com/assets/863731/2755085/75e96354-c962-11e3-8bcd-86a58b7c8b96.PNG)

**Comment by dlsniper** [comment]
This is fixed in 1.0
