### ISSUE TITLE
Make Icons Retina Screen Compatible 

### ISSUE THREAD

**Issue by robertsosinski** [go-lang-plugin-org/go-lang-idea-plugin#695]
Hey Everyone,

Would be great if the icons for the plugin looked good on a Retina Screen as IntelliJ has support for such.

Thanks,

**Comment by dlsniper** [comment]
I'll close this as it doesn't have any feedback unfortunately, @activars or @robertsosinski please feel free to send a PR against the 1.0 branch to fix this. Thank you.
