### ISSUE TITLE
Intellij 13: homebrew install, can't recognize SDK

### ISSUE THREAD

**Issue by Aranir** [go-lang-plugin-org/go-lang-idea-plugin#696]
I read through the issue #219, and it was mentioned that this has been fixed. (6 months ago)

Unfortunately it is still not working for me:

- installed go via homebrew
- installed go plugin from within intellij plugin browse repositories
- inside Project Structure -> Platform Settings -> SDKs-> +
- selected '/user/local/Cellar/go/1.2.1/

And nothing is displayed, idea doesn't recognize it.

I am using intellij idea 13.0.3

**Comment by dlsniper** [comment]
This will be fixed in 1.0 and there's already a ticket for it I believe.
