### ISSUE TITLE
Binary has different names depending if you choose run or debug

### ISSUE THREAD

**Issue by FredFool** [go-lang-plugin-org/go-lang-idea-plugin#702]
When you run a program through configuration, then the output filename is set by the generated build command.

Given a configuration is named test.go, the binary will be test for a call to debug, test.go for a call to run.

I would suggest that .go is removed in all cases and that you might be able to configure a suffix for the debug build, so you can distinguish test and for example test-dbg.

**Comment by dlsniper** [comment]
We'll follow up in 1.0
