### ISSUE TITLE
Run Debug uses incomplete gopath

### ISSUE THREAD

**Issue by FredFool** [go-lang-plugin-org/go-lang-idea-plugin#705]
When you do Run->Debug the working directory seems not to be added to the gopath. Using gom to keep your externals within the project under the _vendor directory, the build fails.

```
# _vendor/src/github.com/clbanning/mxj
open _vendor/src/github.com/clbanning/mxj: No such file or directory
# _vendor/src/github.com/kennygrant/sanitize
open _vendor/src/github.com/kennygrant/sanitize: No such file or directory
```

Works fine with Run->Run though. 

This came up after the #701 fix was included.

**Comment by dlsniper** [comment]
This should be reviewed when we have a proper debugger for go that we can integrate in IDEA.
