### ISSUE TITLE
"error while processing go build command" on Macbook Pro Mavericks/Idea 13.1.2

### ISSUE THREAD

**Issue by nkev** [go-lang-plugin-org/go-lang-idea-plugin#717]
Uninstalled previous released version of plugin from Idea plugins (which worked fine building/running hello world). Intalled build of yesterday's repo using instructions at http://pivotallabs.com/setting-google-go-plugin-intellij-idea-13-os-x-10-8-5/. Not sure if it's a configuration issue but I cannot build or run from Idea. All works fine in Terminal. I cannot even run "go env" from the Idea tools/go tools menu, I get dialog "Error while processing go env command". Here is "go env" result from terminal:

Nuris-MacBook-Pro:src nuri$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nuri/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
TERM="dumb"
CC="clang"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by dlsniper** [comment]
Not applicable for the moment. Check 1.0
