### ISSUE TITLE
No Go Sdk defined for this project

### ISSUE THREAD

**Issue by darrennoble** [go-lang-plugin-org/go-lang-idea-plugin#728]
I just installed go 1.2.2 on my Mac from the installer package and installed the golang plugin inside IntelliJ 13.1 Community.  I created a new module inside my existing project and when I try to run the module I get the error, "No Go Sdk defined for this project"

The module settings shows that it has /usr/local/go as the Go SDK.  My /etc/launchd.conf looks like this:

setenv GOROOT /usr/local/go
setenv GOPATH /Users/[username]/dev/go

I first tried running "egrep -v '^\s*#' /etc/launchd.conf | launchctl" to read in those setting and then tried rebooting and I still get this error.  Is there a setting I'm missing or is something else wrong?

**Comment by merriam** [comment]
Added the "External Tools" workaround to http://stackoverflow.com/questions/22928364/google-go-language-plugin-with-pycharm

**Comment by dlsniper** [comment]
Please usr the latest release from Github releases https://github.com/go-lang-plugin-org/go-lang-idea-plugin/releases. It supports PyCharm 4.0.5+

**Comment by merriam** [comment]
Thank you.  Tried it and failed so far.   I'm using the PyCharm community
edition v4.0.4 on OS/X Yosemite.  Trying to install the file go.134.zip, I
get a dialog error "Plugin Go is incompatible with current installation".

**Comment by dlsniper** [comment]
Please wait for the next version of PyCharm. Or try IDEA Community :-)
