### ISSUE TITLE
default imports for packages that don't have the same package name as the last entry in the import path is broken

### ISSUE THREAD

**Issue by warvariuc** [go-lang-plugin-org/go-lang-idea-plugin#736]
My `GOPATH` is `~/projects/go/`

I did

    go get github.com/vaughan0/go-ini

Which downloaded the package to `~/projects/go/src/github.com/vaughan0/go-ini`.

I created a project which imports that package, but go-plugin doesn't see it:

![snapshot3](https://cloud.githubusercontent.com/assets/1035452/3420367/1347f656-fea6-11e3-9329-e3a3585a5b27.png)

**Comment by jiminoc** [comment]
happy new year! :)  just wondering if there was any update on a potential fix?

**Comment by mtoader** [comment]
Happy new year to you too!. Nothing that we can release yet.

**Comment by dlsniper** [comment]
This should be fixed under 1.0 branch / releases.

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://billypurple.com/nearly.php?h7ab5>

 

info@whywouldwe.com
