### ISSUE TITLE
Show Function Arguments

### ISSUE THREAD

**Issue by kristian-puccio** [go-lang-plugin-org/go-lang-idea-plugin#767]
Thanks for your work on this plugin, it's very enjoyable to use.

An awesome feature to have would be when you are editing the arguments of a function it would be great to have details about the arguments. Much like https://github.com/syohex/emacs-go-eldoc does for emacs.

In fact getting the type info of any variable that the cursor is on would be amazing.

Thanks,
Kristian

**Comment by dlsniper** [comment]
Fixed in 1.0
