### ISSUE TITLE
GAE multi-module apps without app.yaml

### ISSUE THREAD

**Issue by olostan** [go-lang-plugin-org/go-lang-idea-plugin#771]
According to documentation ( https://cloud.google.com/appengine/docs/go/modules/ ) application can be without `app.yaml` file - when there are several modules, and each module is located in separate folders with yaml file describing each module.

Currently plugin checks for existing of app.yaml file inside working directory. I assume this assertion could be removed if `goapp arguments` contains yaml files.

**Comment by juanibiapina** [comment]
@olostan  I also have a project with multiple modules. How do you even start working with it?

**Comment by olostan** [comment]
@juanibiapina as I've wrote above: created empty `app.yaml` file to satisfy validation.

**Comment by strotz** [comment]
with 0.9.250 Go App Engine runner calls "goapp serve ." and it seems like there is no way to do multi-modules, since Go runtime returns error:

/google-cloud-sdk/bin/goapp serve . module/other.yaml
goapp serve: . is not a YAML file

**Comment by olostan** [comment]
I also can't find way to start multi-module project except run serve in terminal...

**Comment by juanibiapina** [comment]
It seems to me you guys are talking about running the project from intellij. I am still stuck trying to get it to compile.

It doesn't find any app engine imports.

**Comment by dlsniper** [comment]
@juanibiapina which version of the plugin are you using? A few releases ago there were some changes that requires the GAE SDK to be reset. Can you give some more details please? If you want, ping me on our Gitter channel and I should be able to help you sort things out so that AppEngine works for you as well.

**Comment by juanibiapina** [comment]
@dlsniper Thanks for the help, but I'm currently changing jobs so I will stop working with app engine for now.

**Comment by 0xor1** [comment]
can anyone tell me how to set the GAE SDK path for the plugin? when I updated to the latest, it asked me to confirm my GOROOT and GOPATH which works great now, but I can't see where you add the GAE SDK path.

**Comment by dlsniper** [comment]
Hi @0xor1 . Please point the go sdk to the gae sdk and add it as a normal go sdk, the ide will recognize it as such.

**Comment by 0xor1** [comment]
@dlsniper thanks, I'll do that, it's a shame I can't register both at the same time as I have one group of submodules that has my ObjDataStore that writes to a file on the local hard drive when I'm using a local exe build of my app, then I have an ObjDataStore that uses the GAE datastore api when I deploy to GAE. well thanks, you were a huge help, I can just manually swap the configs around when working on diferent parts

**Comment by dlsniper** [comment]
@0xor1 you can use modules for that, if you are using intellij idea. You can configure one module to use the go sdk and one to use the gae sdk. I haven't tried it myself yet but it should work (theoretically) :D

**Comment by 0xor1** [comment]
@dlsniper sweet, thanks a bunch!
