### ISSUE TITLE
ImportPathInspection,Import path case insensitive bug.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#799]
I had thought that import path is matched exactly.
But after I read some code that dealing with import path case insensitive,I google something,
I found that:
* The last part of Import path must match package name in source file exactly(not match directory path case).
* The other part of import part match directory path case insensitive.

I think I found a dark part of golang.

So that is what we should do:
* If go compiler can compile it, this plugin will not show an error.
* If import path is not match package directory path exactly, this plugin will show a warning.

I do not think this bug is high priority.

A example that can pass go compiler:
file in ./src/missingArgumentToTypeConversioN/good.go
```go
package main

import (
	"missingArgumentToTypeConversioN/packagea"
	"fmt"
)

func main() {
	a := packagea.ABC(1)
	fmt.Println(a)
}
```

file in ./src/missingArgumentToTypeConversioN/packageA/packageA.go
```go
package packagea

type ABC int
```

@mtoader is trying to solve:
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/777#issuecomment-58612312

**Comment by dlsniper** [comment]
Fixed in 1.0
