### ISSUE TITLE
Proper configuration for a per-project GOPATH?

### ISSUE THREAD

**Issue by DallanQ** [go-lang-plugin-org/go-lang-idea-plugin#867]
A question on documentation - I use a per-project GOPATH, which I set to the IntelliJ project root. I've configured the golang plugin:

GOPATH = root of a "global tools" go project where I install tools like goimports - not the project I'm currently working on

Project GOPATH: Project GOPATH=Project-Workdir

Is this the correct way to configure the golang plugin for a per-project GOPATH?

Thanks for a __great__ plugin!

**Comment by dlsniper** [comment]
Fixed in 1.0.
