### ISSUE TITLE
Ignore non exported struct members for imported structs.

### ISSUE THREAD

**Issue by mtoader** [go-lang-plugin-org/go-lang-idea-plugin#900]

**Comment by dlsniper** [comment]
To be checked for 1.0

**Comment by ignatov** [comment]
Please provide a description and a code sample if needed.

**Comment by ignatov** [comment]
@dlsniper Ping

**Comment by dlsniper** [comment]
Sorry, this can be closed as it was meant to be for the resolving subsystem which works correctly now, as far as I can see (aside from the existing bugs).
