### ISSUE TITLE
Import formatting broken after deleting packages references

### ISSUE THREAD

**Issue by dmitry-vovk** [go-lang-plugin-org/go-lang-idea-plugin#915]
Before:
```go
import (
	. "dbtest"
	"github.com/kr/pretty"
	"logger"
	"os"
	"testing"
)
// ...
logger.ErrorLog.Printf("%# v", pretty.Formatter(found3))
```
After deleting the last line imports are automatically rewritten and formatted as follows:
```go
import (
	. "dbtest"    "os"
	"testing"
)
```
And that's obviously wrong.

IDE: IU-139.144.2
Plugin: latest EAP master build (from dropbox when it was there)

**Comment by dlsniper** [comment]
The issues with the formatter will be addressed in 1.0 as that has its own problems
