### ISSUE TITLE
setting go sdk fails sometimes

### ISSUE THREAD

**Issue by fuxiaohei** [go-lang-plugin-org/go-lang-idea-plugin#927]
After install golang1.4 beta1 sdk via official mac pkg installer "go1.4beta1.darwin-amd64-osx10.8.pkg", the code completion is gone.

Then I remove old golang-sdk setting in project-structrue and add new one to correct golang source directory , it shows error :
 
    IllegalArgumentException: Argument for @NotNull parameter 'virtualFile' of com/intellij/openapi/projectRoots/impl/ProjectRootContainerImpl.addRoot must not be null

If re-install pkg with golang1.3.3, set new golang-sdk, invalidate caches and restart,  all things are recovered.

So I think something was wrong when plugin scans the sdk directories.

PS: plugin version is 0.9.16-alpha.4 and IDEA version is IDEA-IU-139.222.5 EAP version

**Comment by dlsniper** [comment]
This shouldn't be a problem under 1.0 branch / releases anymore.
