### ISSUE TITLE
Request: support for Go Oracle

### ISSUE THREAD

**Issue by inercia** [go-lang-plugin-org/go-lang-idea-plugin#957]
Hi there,

I would just to suggest that it would be great to have some support for [Go Oracle](https://docs.google.com/document/d/1SLk36YRjjMgKqe490mSRzOPYEDe0Y_WQNRv-EiFYUyw/edit?usp=sharing). It could be used for providing information about the code being edited, giving us things like the callers for a function, the call graph, who implements a interface, etc...

Thanks in advance

Alvaro

**Comment by mqliang** [comment]
> Go Oracle is the poor-man version of IDEA. It basically offers the same functionality as the IDE itself for those who don't want an IDE (kinda pointless, no?). Long story-short: the plugin is already doing this so Go Oracle ain't gonna happen.

Is there any way to know "who implements a interface" using IDEA? It's a really helpful.
