### ISSUE TITLE
GOPATH handling use cases

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#960]
The document can be found in the [wiki page](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/wiki/GOPATH-use-cases)

We can use this place to discuss and then update it.

**Comment by bronze1man** [comment]
I use one GOPATH one project.
I use a `.kmg.yml` file like a `.git` file to mark where is the GOPATH of my current project,so I can use my own tool `kmg gorun` to run my code without set GOPATH again and again in command line.

**Comment by dlsniper** [comment]
So in this case is it correct to assume that you have the second use case described in the wiki page?

**Comment by bronze1man** [comment]
I think it looks like c in the wiki page.
I only use a single path as GOPATH.

**Comment by dlsniper** [comment]
Ah, right. Sorry, I was almost asleep when I posted that :D The plugin should be able to use a single GOPATH / project right now, but I've personally not tried it yet.

**Comment by dlsniper** [comment]
Also, obsolete. master does it nicely now.
