### ISSUE TITLE
Make test runner gocheck aware

### ISSUE THREAD

**Issue by horkhe** [go-lang-plugin-org/go-lang-idea-plugin#988]
From the `go test` prospective a [gocheck](https://labix.org/gocheck) testsuite looks like just one test case. It would be nice to make the test runner automatically detect that a test is featuring gocheck and present test cases properly in the output console.

**Comment by horkhe** [comment]
I am working on adding support for [gocheck](https://labix.org/gocheck). The work is about 50% complete. I will submit a PR soon. Writing this just to avoid two people working on the same thing.

**Comment by dlsniper** [comment]
Hi, cool, thanks for the heads-up. I think it's even better if you can open a WorkInProgress PR like the one that I have right now as it's more visible (our experience shows people are still discovering thr search functionality for existing issues :-D) 

As for supporting gocheck, I've opened this PR https://github.com/go-check/check/pull/36 a while ago as I'm using it already but the author doesn't seem to be interested in maintaining it anymore. I'm considering forking and rereleasing the project with all the missing PRs at this point. 

@zolotov, what do you think? How should we support multiple Go test runner packages? They are about a half a dozen out there.

**Comment by zolotov** [comment]
> As for supporting gocheck, I've opened this PR go-check/check#36 

Actually it's better if test tool provides [IDEA reporting format] (https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests). In the ideal world test tool shouldn't know about IDEA format but accept external reporters.
