### ISSUE TITLE
new project have a lot inspection errors.

### ISSUE THREAD

**Issue by bronze1man** [go-lang-plugin-org/go-lang-idea-plugin#999]
In my working project,go compiler says that there is no bug in it. 
There is about 1-3 errors in one file (they are inspection bugs,I had wrote test cases for them).

I copy my working project to another place, run git clean -xdf
Open it in idea,config sdk ,set ./src as source path.
There is 10+ errors in the bugs.

When it broken:
* A lot packages are marked as "not found". But they are exist in the project.
* Elements which reference package that "not found" are also unsolved.
* goto anywhere can not go to function in the "not found" package.

### good one
![image](https://cloud.githubusercontent.com/assets/1107541/5058229/9556a594-6d22-11e4-93a8-3f9337e29f01.png)

### broken one
![image](https://cloud.githubusercontent.com/assets/1107541/5058214/f55887ba-6d21-11e4-8fab-8e7d291b7b71.png)

Those errors are not exist in the same file of the old folder of the project.

* It works fine, if I copy all files in the old folder without delete .idea folder.
* If a folder name works, it will works again after `git clean -xdf`. change the folder name and repeat those steps it fails again.

I guess that there is some bugs in GoPackageName index.

**Comment by dlsniper** [comment]
Shouldn't happen in 1.0 anymore
